mesonbuild/meson

mesonbuild/interpreter/interpreter.py
In commit dd22546bdd5b7de34025437ae1360f6dd20491eb the various typed_pos_args for different BuildTarget functions was refactored into a common tuple of types.
It overlooked the fact that jar specifically does NOT accept the same types, and began to allow passing structured_sources in.
=> fix regression that broke sanity checking of jar sources

mesonbuild/dependencies/cmake.py
[PyTorch](https://github.com/pytorch/pytorch) is a project built with cmake, and provides cmake packages for applications to link with it. The cmake prefix of PyTorch can be found by running:
```bash
python -c 'import torch.utils; print(torch.utils.cmake_prefix_path)'
```
you will see something like below from the above command:
```
/home/gaoxiang/.virtualenvs/nvfuser/lib/python3.11/site-packages/torch/share/cmake
```
Inspecting this directory:
```
❯ tree /home/gaoxiang/.virtualenvs/nvfuser/lib/python3.11/site-packages/torch/share/cmake
/home/gaoxiang/.virtualenvs/nvfuser/lib/python3.11/site-packages/torch/share/cmake
├── ATen
│   └── ATenConfig.cmake
├── Caffe2
│   ├── Caffe2Config.cmake
│   ├── Caffe2Targets.cmake
│   ├── Caffe2Targets-release.cmake
│   ├── FindCUDAToolkit.cmake
│   ├── …
```
=> Add `''` to cmake `common_paths`

mesonbuild/build.py, mesonbuild/interpreter/interpreter.py, mesonbuild/interpreter/kwargs.py, mesonbuild/interpreter/type_checking.py
This gets all of the executable exclusive keyword arguments ported to typed_kwargs
=> Use typed_kwargs for exclusive executable args

mesonbuild/modules/__init__.py
ExternalProgram currently assumes that if a command is passed it exists and can be used as is. In case we extract the path from pkgconfig the path might not exist, on Windows it might be missing the ".exe" suffix.
By passing the variables as a name ExternalProgram will validate that the command exists at configure time and will fail if not, and it will try to fixup the command by appending .exe etc.
Fixes #12271
=> find_tool: don't assume the pkgconfig variable is a valid command

test cases/nasm/2 asm language/meson.build
The code in this test to make Linux system calls is not compatible with the SunOS kernel system call conventions.
Without this change, the test fails when running "ninja test":
```
[0/1] Running all tests.
1/2 hello                  FAIL            0.37s   killed by signal 11 SIGSEGV
>>> MALLOC_PERTURB_=122 '/export/alanc/git/github/meson/test cases/nasm/2 asm language/builddir/hello'
2/2 hello_w_threads        FAIL            0.37s   killed by signal 11 SIGSEGV
>>> MALLOC_PERTURB_=201 '/export/alanc/git/github/meson/test cases/nasm/2 asm language/builddir/hello_w_threads'
Summary of Failures:
1/2 hello           FAIL            0.37s   killed by signal 11 SIGSEGV
2/2 hello_w_threads FAIL            0.37s   killed by signal 11 SIGSEGV
```
=> nasm tests: skip asm language test on Solaris & illumos

mesonbuild/dependencies/dub.py
This was introduced by pylint 3.0.0.
See https://github.com/pylint-dev/pylint/issues/9095.
=> temp disable pylint falsepositive on dub.py

ci/ciimage/build.py, ci/ciimage/common.sh, ci/ciimage/opensuse/install.sh
The eternal quest to get CI images periodically updating. This doesn't actually fix anything, but it does make the image builders get a bit further before erroring: in particular, the opensuse image now successfully builds, so we can see where the self-tests fail.
- CI: install an older java on opensuse
- CI: fix broken ciimage builder script failing to correctly copy meson
- CI: fix the fix for python actually being mildly useful
=> CI misc updates

docs/markdown/Commands.md, docs/markdown/snippets/executable-suffixes.md, docs/markdown/snippets/meson_compile_suffixes.md, docs/yaml/functions/executable.yaml, mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/interpreter/interpreter.py, mesonbuild/linkers/linkers.py, mesonbuild/mcompile.py, test cases/unit/119 executable suffix/main.c, test cases/unit/119 executable suffix/meson.build, unittests/allplatformstests.py
The type suffix is used when determining the id of a target. This is important since having multiple targets with the same id isn't allowed. Because the type suffix is unconditionally `@exe`, this made it impossible to have targets of the same name but with different suffixes in the same directory (i.e. foo and foo.bin). An easy way to fix this is to simply alter the type suffix if a name_suffix kwarg is passed in executable. Basically, just change it to @ + suffix instead of `@exe`. If no name_suffix is available, then leave it as `@exe` like before.
Not sure if this needs to be documented somewhere. I didn't attempt to change how libraries worked since that seemed a lot more obscure to me, but one could do something similar.
=> build: use suffix when getting target id for exes

docs/markdown/snippets/env_kwarg_generator_process.md, docs/yaml/objects/generator.yaml, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/build.py, mesonbuild/interpreter/interpreterobjects.py, mesonbuild/interpreter/kwargs.py, test cases/common/272 env in generator.process/generate_main.py, test cases/common/272 env in generator.process/main.template, test cases/common/272 env in generator.process/meson.build
This PR adds support for the `env:` argument in the `generator.process()` method. It works in the exact same way it works in `custom_target()`. Useful to batch process multiple files with tools that require certain environment variables without having to abuse `foreach` loops and `custom_target.`
=> Add env kwarg in generator.process()

mesonbuild/backend/ninjabackend.py, mesonbuild/environment.py, mesonbuild/scripts/coverage.py
lcov 2.0 deprecates `--rc lcov_branch_coverage=1` for `--rc branch_coverage=1` and gives an error when an exclude is used on a non existing directory.
I added a version check for lcov and removed the subprojects directory from the exclusion list if it does not exist.
Fixes #11995
=> Add support for lcov 2.0

mesonbuild/wrap/wrap.py
This most likely happens when the source archive has files which take advantage of case sensitivity, and someone is unfortunate enough to have to work with broken operating systems that do not have the capacity to use modern technology, like the 1970s invention of case sensitive filesystems.
For example, Windows and macOS both have retrocomputing environments, where case sensitive abilities were carefully removed from modern filesystems in order to share the delights of classical computing with the masses.
On such systems, innocent tarballs fail to extract with:
```
OSError: [Errno 22] Invalid argument: 'C:\path\to\file'
```
thereby demonstrating Microsoft's unbounded and enthusiastic love for users (who are, universally, retrocomputing fans).
n.b. there is, begrudgingly, a secret option …
=> wrap: catch failure to extract tarball and raise WrapException

mesonbuild/compilers/cpp.py, unittests/linuxliketests.py
This PR allows using `cpp_std=c++23` with gcc-11 as per issue #12291.
Currently meson requires GCC version `>=12.2.0` for `cpp_std=c++23`.  However, this seems incorrect, as `gcc-11` also supports `-std=c++23`.  Obvious c++23 support isn't complete in gcc-11, but it isn't complete in gcc-12 either.
The commit adding support for `-std=c++23` was done in January 2021, several months before the gcc-11 release, so `11.0.0` seems fine.
- https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=78739c2df788ee5c868d998a6333d453317d8711
In GCC-11, three new features are enabled by this flag:
- https://gcc.gnu.org/projects/cxx-status.html
- Literal Suffix for (signed) size_t 
- Make () more optional for lambdas 
- Allow Duplicate Attributes
=> Allow cpp_std=c++23 with gcc-11.

mesonbuild/msubprojects.py
1. Abort the rebase if there's conflicts on update
2. Don't rebase if the branch is already tracking upstream, just checkout and update
=> msubprojects: Fix conditions around rebase on update

mesonbuild/backend/ninjabackend.py
This fixes #12329 by replacing `$in` with `$in_newline` when `rspfile quote style` is `RSPFileSyntax.MSVC`
=> Fix MSVC LNK1170

mesonbuild/dependencies/framework.py, test cases/osx/5 extra frameworks/meson.build, test cases/osx/5 extra frameworks/stat.c
System headers will continue to "preempt" the framework headers. This should allow both <GStreamer/gst/gst.h> and <gst/gst.h>
Fixes: #10002
=> Use -idirafter when adding Apple framework include paths

mesonbuild/compilers/cpp.py
Notes: 
- this is my first contribution, I am not really a compiler person so I hope I got this right.
The <lang>_stdlib can be used in cross files to use a custom standard library for a given language.
When cpp_stdlib is used in a cross file, meson passes
* -nostdinc++ to the compiler
* -nostlib to the linker
According to [1] (gcc) and [2] (clang), we should pass -nostlib++ to the linker when we don't want to link to the standard C++ library. Currently, we pass -nostlib.
Fix this by implementing a C++ specific get_no_stdlib_link_args() function.
[1] https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html#index-nostdlib_002b_002b
[2] https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-nostdlib
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>
=> cpp: use -nostlib++ instead of -nostlib for custom cpp_stdlib

mesonbuild/backend/ninjabackend.py
Fixes https://github.com/mesonbuild/meson/issues/12349
=> ninjabackend: Use the right ranlib for static linker rules on macOS

mesonbuild/modules/rust.py, test cases/rust/9 unit tests/meson.build
This is required to test non-executable targets when they set an explicit type.
=> modules/rust: remove rust_crate_type for test() method

mesonbuild/modules/rust.py
Avoid adding args that bindgen doesn't understand by limiting the arguments we accept to -D, -U, and -I arguments
=> modules/rust: only use include and define args from global/project args

docs/markdown/snippets/int_to_string_fill.md
The release notes were using the older spelling "length". Replace it with the spelling that was actually committed.
=> release notes: fix snippet for "fill:" argument

test cases/frameworks/15 llvm/meson.build, test cases/frameworks/15 llvm/test.json
There's a bug in the zstd find_package module:
https://github.com/llvm/llvm-project/commit/e7fc7540daa9333f0be4f380fc9c619236d17f57#r130257253
=> test cases/15 llvm: Disable cmake on clangx64ninja

mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/compilers/asm.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/d.py, mesonbuild/compilers/mixins/visualstudio.py, mesonbuild/compilers/rust.py
Rustc assumes "md" by default, but we should always respect Meson
options. Building some targets with different vscrt makes them fail to
link together. This is also what other compilers does.
=> rust: Always inject vscrt args

docs/markdown/Unit-tests.md, docs/markdown/snippets/sanitizers_test.md, docs/yaml/functions/test.yaml, mesonbuild/mtest.py
Do as we do for MALLOC_PERTURB and set a sensible value for both ASAN_OPTIONS and UBSAN_OPTIONS to abort on failure and give more helpful output at the same time. We do not set these options if the user has exported a value themselves to allow override.
In the last week alone, I've observed two cases where people were expecting sanitizers to abort on failure and were surprised when it didn't: 1) https://github.com/git/git/commit/252d693797912ddb2684733160170f0408b73274 2) https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/c47df433f7bc9936fc59b323ca5e53ea4a04f40e
Correct this - which is in-line with meson's DWIM/DTRT philosophy.
=> mtest: set ASAN_OPTIONS and UBSAN_OPTIONS to abort by default

docs/markdown/snippets/pkgconfig_deprecated_machine_file.md, mesonbuild/envconfig.py
This was previously allowed for different usage. Keep allowing it, but with non fatal deprecation notice, and ignore the value from legacy pkgconfig.
=> pkgconfig: Allow setting both pkgconfig and pkg-config

docs/markdown/snippets/shorthand_argument_for_mtest_num_processes.md, mesonbuild/msubprojects.py, mesonbuild/mtest.py
We already use -j to support parallelism in meson compile. So let's add the same for meson test and subprojects.
=> Support -j as a shorthand for --num-processes

mesonbuild/build.py, mesonbuild/interpreter/interpreter.py
adb1a360b9f9edb26eda233326b1d539baeccd5b added the feature and also the usual meson-style warning to users that might be using the feature but were not targeting a new enough meson version. Well unfortunately the warning both doesn't actually work (it didn't take different directories into account) and is also really slow because it creates an O(N^2) loop for checking this.
Instead, rework this by having another dictionary that stores target names along with any ids that have the same name. When we do the check on a new target, lookup up the name in the new targetnames dictionary (should be O(1)). If we do have something, then loop through all the target ids for the key and check if the fetched target is actually an executable and has the same subdirectory. Print the warning if so. This …
=> build: improve the warning for executables with the same name

mesonbuild/modules/i18n.py, mesonbuild/scripts/itstool.py
Hi,
This PR attempts to make calling `itstool` work on environments where shebang lines are not directly supported, by prepending the `itstool` call with `sys.executable`.
This was found while attempting to add `clang-cl` build support for appstream.
=> itstool.py: Prepend call to itstool with sys.executable

mesonbuild/interpreter/type_checking.py, mesonbuild/modules/simd.py
Regression in commit a3d287c553b9598f010fe0755c5528ef62055e44.
When a given kwarg is not specified, we want to not generate it as a simd variant. Since the default for buildtarget sources is `[]` it resulted in building a static library with no sources, and a warning stating that this was buggy and will eventually be removed.
Fix this by teaching buildtarget sources to allow None, and defaulting to it specifically for the simd module. We can check this and then skip processing entirely.
Fixes #12438
=> simd module: fix regression that broke using only some simd variants

mesonbuild/cargo/interpreter.py
Previously, creating a meson wrap with "method=cargo" for https://github.com/sunfishcode/is-terminal would cause meson to crash, because `is-terminal`'s Cargo.toml contains a `[target]` section without dependencies.
Instead, we now fall back to an empty list in case of no specified dependencies (like everywhere else in "_convert_manifest")
The relevant wrap file looks like this:
```ini
[wrap-file]
directory = is-terminal-0.4.9
source_url = https://crates.io/api/v1/crates/is-terminal/0.4.9/download
source_filename = is-terminal-0.4.9.tar.gz
source_hash = cb0889898416213fab133e1d33a0e5858a48177452750691bde3666d0fdbaf8b
method = cargo
```
Note: First time contributor, i didn't find any documentation about commit message style and such, can amend if necessary
=> Fix crash for cargo wrap files with [target] sections without dependencies

data/shell-completions/bash/meson, mesonbuild/coredata.py, mesonbuild/mcompile.py, mesonbuild/mconf.py, mesonbuild/mdevenv.py, mesonbuild/mdist.py, mesonbuild/minit.py, mesonbuild/minstall.py, mesonbuild/mintro.py, mesonbuild/msetup.py, mesonbuild/msubprojects.py, mesonbuild/mtest.py, mesonbuild/munstable_coredata.py, mesonbuild/rewriter.py, mesonbuild/scripts/env2mfile.py, mesonbuild/wrap/wraptool.py
#11422 was merged but 7 months old, so here's bash support for options added since then that can hopefully go in before the next release.
Perhaps a comment in `coredata.py` (or wherever best) alongside
```
```
about updating shell completion helpers might help keep things synced?
Thanks
=> completions: bash: added a bunch of missing completion options.

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/compilers/compilers.py, mesonbuild/minstall.py
This PR is for fixing issue number #12219 in meson for AIX operating system as discussed.
=> Enhance shared library support for AIX

mesonbuild/build.py, test cases/rust/20 transitive dependencies/foo.c, test cases/rust/20 transitive dependencies/foo.rs, test cases/rust/20 transitive dependencies/meson.build, test cases/rust/20 transitive dependencies/proc.rs
=> rust: proc-macro should be ignored in transitive dependencies

docs/markdown/snippets/subprojects_excluded_from_scanbuild.md, mesonbuild/backend/ninjabackend.py, mesonbuild/scripts/scanbuild.py
When a user invokes the `scan-build` target that Meson generates, bugs found by `scan-build` in subprojects are included in the resulting report. This commit modifies the invocation of `scan-build` in order to exclude all bugs that are found inside subprojects from the final report.
I would like to be able to use Meson's `scan-build` target in a continuous integration workflow to notify of any newly added code that the static analyser considers to be a possible bug.
In order to do this I would like to invoke the `scan-build` and raise an error if a report exists after ninja exits, `scan-build`'s default behaviour being to not create a report if no bugs were found. For trivially small projects this works well, but for anything which uses subprojects, this doesn't work so well as …
=> scan-build: Exclude subprojects from scan-build report

mesonbuild/interpreterbase/interpreterbase.py, unittests/platformagnostictests.py
We try to backtrack through the filesystem to find the correct directory to build in, and suggest this as a possible diagnostic. However, our current heuristic relies on parsing the raw file with string matching to see if it starts with `project(`, and this may or may not actually work.
Instead, do a bit of recursion and parse each candidate with mparser, then check if the first node of *that* file is a project() function.
This makes us resilient to a common case: where the root meson.build is entirely valid, but, the first line is a comment containing e.g. SPDX license headers and a simple string comparison simply does not cut it.
Fixes the bad error message from #12441, which was supposed to provide more guidance but did not.
=> Fine-tune the error message when trying to build outside the project root

mesonbuild/compilers/c_function_attributes.py, test cases/common/197 function attributes/meson.build
`has_function_attribute()` depends on `-Wattributes` being emitted when an attribute is not supported by the compiler. In case of GCC on Window (at least) there is no warning in case the attribute is used on a declaration. Only once there is also a function definition does it emit a warning like:
```
a.c: In function ‘foo’:
a.c:8:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
8 | }
```
To fix this add a dummy function definition to all visibility compiler checks in meson.
The tests in "197 function attributes" only checked for positive return result on non-msvc compilers, except one special case for dllexport/dllimport. Refactor the tests a bit so one can specify also a negative expected result, and add tests for all visibility attribute …
=> Fix visibility attribute support check for GCC on Windows

mesonbuild/modules/__init__.py
If a tool that is looked up in a .pc file is supposed to be there and has a pkg-config variable entry, but the value is incorrect, we can't actually use it.
Since commit ab3d02066c91974922948f8b8b0fc944875d1a90 we actually do run the ExternalProgram search procedure on it though -- which caused it to go wonky and return a None if it doesn't exist, instead of containing a path to a program that does not exist and fails at build time. This is better in the case where searching helps resolve .exe file extensions -- and worse in the case where patches to the dependency means nothing we do is ever enough to actually find what is expected, since now we crash.
Raise an explicit error in such a case, pointing out that the dependency itself is broken and needs a distributor-side resolution.
Fixes …
=> gnome module: fix invalid find_tool variable contents causing crash

mesonbuild/msubprojects.py
This is a regression caused by
https://github.com/mesonbuild/meson/pull/11951.
Fixes: #12466
=> msubprojects: Fix --sourcedir argument not working

mesonbuild/backend/ninjabackend.py
This solves StableCrateId collision when using multiple versions of the same crate.
=> rust: Add unique metadata id

mesonbuild/backend/backends.py
=> msvc: Do not include pch obj when b_pch=false

mesonbuild/mtest.py
It is already done by RealPathAction and mypy started complaining about it.
=> mtest: -C argument does not need type convertor

mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, test cases/rust/15 polyglot sharedlib/adder.c, test cases/rust/15 polyglot sharedlib/adder.rs, test cases/rust/15 polyglot sharedlib/meson.build, test cases/rust/15 polyglot sharedlib/zero/meson.build, test cases/rust/15 polyglot sharedlib/zero/zero.c, test cases/rust/15 polyglot sharedlib/zero/zero_static.c, test cases/rust/20 transitive dependencies/diamond/func.c, test cases/rust/20 transitive dependencies/diamond/main.c, test cases/rust/20 transitive dependencies/diamond/meson.build, test cases/rust/20 transitive dependencies/diamond/r1.rs, test cases/rust/20 transitive dependencies/diamond/r2.rs, test cases/rust/20 transitive dependencies/diamond/r3.rs, test cases/rust/20 transitive dependencies/meson.build, test cases/rust/20 transitive dependencies/test.json
`-l static=` expects a filename and not a relative path, rustc already has `-L` flags to find the library. Weirdly passing a path to `-l dylib=` works fine, but better never do it.
Fixes: #12484
=> rust: Fix linking with C libraries in subdir

mesonbuild/interpreter/interpreter.py, mesonbuild/interpreter/type_checking.py
We haven't actually verified that these kwargs are equal to what we had before, and should probably revert the entire series. But I have multiple reports in the wild of projects that no longer build because of `install: [true, false, get_option('foobar')]` which was always incorrect and always equal to just dropping values all over the floor and treating it the same as "bool(value) == True".
Special case this particular typed kwarg and allow it with a sternly worded warning that it was always wrong and should never ever ever be done.
Fixes: https://bugs.gentoo.org/917118
Fixes: http://qa-logs.debian.net/2023/11/11/rhythmbox_3.4.7-1_unstable_meson-exp.log
Thanks to the Gentoo Tinderbox project, and Lucas Nussbaum of the Debian project.
=> fix regression in converting build_target kwargs to typed_kwargs

mesonbuild/backend/ninjabackend.py, test cases/rust/21 transitive dependencies/app.rs, test cases/rust/21 transitive dependencies/meson.build, test cases/rust/21 transitive dependencies/static1.c, test cases/rust/21 transitive dependencies/static2.c
In the case r1 -> s1 -> s2 where s1 and s2 are uninstalled C static libraries, the libs1.a rule does not depend on libs2.a. That means that r1 rule must depend on both s1 and s2.
=> rust: Add transitive dependencies to ninja rules

mesonbuild/build.py, mesonbuild/interpreter/type_checking.py
This time we have a case where people are passing non-objects by using them as str | File, which we never warned about and silently accepted. If it was passed via custom_target outputs we *would* error out, interestingly enough. At the backend layer, we just pass them directly to the linker... which is valid, if we misdetected what's a valid linker input or people just used funny names. In particular, the mingw toolchain allows passing a *.def file directly, and some people are doing that.
If we do want to allow this, we should do it consistently. For now, just follow the current theme of what's expected, but do so by warning instead of fatally erroring, for cases where users were able to do it in the past.
=> fix another regression in converting build_target kwargs to typed_kwargs

docs/markdown/snippets/pkgconfig_define_variable.md, docs/yaml/objects/dep.yaml, mesonbuild/dependencies/pkgconfig.py, mesonbuild/dependencies/scalapack.py, mesonbuild/interpreter/interpreterobjects.py, mesonbuild/interpreter/type_checking.py, mesonbuild/mdevenv.py, test cases/linuxlike/1 pkg-config/meson.build
It was previously impossible to do this:
```
dep.get_pkgconfig_variable(
'foo',
define_variable: ['prefix', '/usr', 'datadir', '/usr/share'],
)
```
since get_pkgconfig_variable mandated exactly two (if any) arguments.
However, you could do this:
```
dep.get_variable(
'foo',
pkgconfig_define: ['prefix', '/usr', 'datadir', '/usr/share'],
)
```
It would silently do the wrong thing, by defining "prefix" as `/usr=datadir=/usr/share`, which might not "matter" if only datadir was used in the "foo" variable as the unmodified value might be adequate.
The actual intention of anyone writing such a meson.build is that they aren't sure whether the .pc file uses ${prefix} or ${datadir} (or which one gets used, might have changed between versions of that .pc file, even).
A recent refactor made this into …
=> dependencies: allow get_variable to define multiple pkgconfig defines

mesonbuild/rewriter.py
The shebang should not be in the `rewriter.py` file, because the file cannot be run:
```
$ chmod +x mesonbuild/rewriter.py
$ mesonbuild/rewriter.py
File "/opt/src/meson/mesonbuild/rewriter.py", line 27, in <module>
from .ast import IntrospectionInterpreter, BUILD_TARGET_FUNCTIONS, AstConditionLevel, AstIDGenerator, AstIndentationGenerator, AstPrinter
ImportError: attempted relative import with no known parent package
$
```
=> Remove shebang from rewriter.py

docs/markdown/Tutorial.md
`G_APPLICATION_DEFAULT_FLAGS` enum is only available with glib v2.74 (or higher).
Otherwise, one has to use `G_APPLICATION_FLAGS_NONE`.
=> note on glib library

mesonbuild/backend/backends.py, test cases/common/272 unity/meson.build, test cases/common/272 unity/slib.c, test cases/common/272 unity/slib1.c, test cases/common/272 unity/slib2.c, test cases/common/272 unity/test.json
=> Fix unity builds

mesonbuild/backend/vs2010backend.py
<details> 
<summary>Given this relatively simple setup</summary>
The code attempts to create a file named `zß水🍌` with standard C++ APIs (which use the ANSI variants of Win32 APIs), then checks whether it succeeded by using the Wide variant of a Win32 API. There is sufficient variation in the filename to not be covered by a single codepage, so unless the ANSI variants operate in the UTF-8 codepage, the check will fail. In more recent versions of Windows 10, [this can be requested in the application manifest](https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page), which this setup also attempts, and, using the VS backend and current release versions of Meson, fails to do.
<ul>
<li><details> 
<summary><code>embed-manifest-test.cpp</code></summary>
```cpp …
```
=> vs2010backend: fix incompatibility with custom manifests

mesonbuild/modules/pkgconfig.py
Whilst working on the Reproducible Builds effort, we noticed that meson was generates .pkgconfig files that are not reproducible.
For example, here is `neatvnc`'s pkgconfig file:
```
Name: neatvnc
Description: A Neat VNC server library
Version: 0.7.0
-Requires.private: pixman-1, aml < 0.4.0, aml >= 0.3.0, zlib, libdrm, libturbojpeg, gnutls, nettle, hogweed, gmp, gbm, libavcodec, libavfilter, libavutil
+Requires.private: pixman-1, aml >= 0.3.0, aml < 0.4.0, zlib, libdrm, libturbojpeg, gnutls, nettle, hogweed, gmp, gbm, libavcodec, libavfilter, libavutil
Libs: -L${libdir} -lneatvnc
Libs.private: -lm
Cflags: -I${includedir}
```
This is, ultimately, due to iterating over the contents of a `DefaultDict[Set]` and can thus be fixed by sorting the output immediately prior to generating the …
=> Make the Requires.private line in generated .pkgconfig files reproducible

mesonbuild/compilers/mixins/clike.py
**[why]**
On Apple clang 15.0.0 linker (i.e. `ld64 1015.7`) giving the same rpath multiple times raises a warning:
```
ld: warning: duplicate -rpath '/local/lib' ignored
```
This can frequently happen when linking several dependencies that all have that rpath in e.g. pkgconfig.
**[how]**
Deduplicate all rpath arguments.
**[note]**
I'm not sure how the code handles --start/end-group, but for rpath that should not make any difference as that is not bound to a group.
=> clike: Deduplicate rpath linker flags

docs/markdown/Rust-module.md
> error: unsupported option '--target'; did you mean '-target'?
=> docs: fix bindgen_clang_arguments example

docs/markdown/Release-procedure.md
Releases have been happening an average of once every 90 days for the past two years (since 0.60.0). If we just look at releases since 1.0.0, the average is over 100 days.
It has been 101 days since 1.2.0, and there is no 1.3.0rc yet.
Ref:
Version | Date | Days since previous release
-- | -- | --
1.2.0 | 2023-07-16 | 97
1.1.0 | 2023-04-10 | 108
1.0.0 | 2022-12-23 | 47
0.64.0 | 2022-11-06 | 126
0.63.0 | 2022-07-03 | 104
0.62.0 | 2022-03-21 | 70
0.61.0 | 2022-01-10 | 78
0.60.0 | 2021-10-24 | 98
0.59.0 | 2021-07-18 |  
=> Update release frequency to match reality

docs/yaml/elementary/str.yml
=> docs: document out of bounds behavior in str.substring

docs/yaml/functions/dependency.yaml
In the description both types are used.
=> docs/dependency: fix type of version kwarg

docs/markdown/snippets/file-full-path.md, docs/yaml/objects/file.yaml, mesonbuild/interpreter/interpreterobjects.py, test cases/common/74 file object/meson.build
This is needed now that str.format() is not allowing it any more. It is also more consistent with other objects that have that method as well, such as build targets.
Fixes: #12406
=> File: Add full_path() method

.github/workflows/lint.yml, .mypy.ini, docs/refman/loaderyaml.py, mesonbuild/compilers/mixins/compcert.py, mesonbuild/interpreter/compiler.py, mesonbuild/mdevenv.py, run_mypy.py
If an annotation could not be resolved, it's classified as a "missing import" and our configuration ignored it:
```
Skipping analyzing "mesonbuild.backends": module is installed, but missing library stubs or py.typed marker
```
As far as mypy is concerned, this library may or may not exist, but it doesn't have any typing information at all (may need to be installed first).
We ignored this because of our docs/ and tools/ thirdparty dependencies, but we really should not. It is trivial to install them, and then enforce that this "just works".
By enforcing it, we also make sure typos get caught.
=> fix broken type annotation imports being ignored

mesonbuild/compilers/detect.py
Closes #11887
@tolnaisz - I don't actually know what particular `armar` compiler you're using. Can you test this fix on your end?
Instead of using a different version flag (the output of which isn't even parsed), just catch the error that all the TI linkers print when `--version` is specified, which is similar to what we do with other compilers that don't support this flag.
For reference, this is what I get on *all* of `ar430`, `ar2000` and `armar` when given `--version`:
`  -->  error: bad option 'e'`
And what I get for `?` (again, not used any more, just in case we need the specificity in the future):
```
.\ar430.exe ?
MSP430 Archiver                         v18.12.8.LTS
Copyright (c) 2003-2018 Texas Instruments Incorporated
Syntax : ar430 [arxdt][quvsh][012] archive files ...
ar430 …
```
=> More robust linker detection for armar (TI vs non-TI)

mesonbuild/utils/universal.py
This caused a regression with mesondefine where
`conf_data.set("FOO", true)`
turned into
`#define FOO 1`
instead of
`#define FOO`
=> Only convert boolean values for cmake formats

mesonbuild/linkers/detect.py
Previously macos reported "ld: unknown option: --version" when being passed --version, but now sometimes it reports in plural, albeit without an obvious pattern when.  To handle that, simply just check for the prefix without the :
Fixes: https://github.com/mesonbuild/meson/issues/12552
=> Handle macos linker reporting error message in plural during detection

unittests/darwintests.py
The path tested prior does not exist anymore in Sonoma. It seems less likely that 'cp' will be removed.
CC: @tristan957
=> macos: Fix path in test to be Sonoma compatible

mesonbuild/dependencies/python.py
The code assumed that sysconfig.get_platform() returns "mingw" for mingw Python, but that's no longer the case for 2.5 years now, as it now only starts with "mingw" and contains futher information like the arch and other ABI relevant things to avoid conflicts.
This updates the detection code to the current status quo. mingw Python only documents right now that it starts with "mingw", and none of that arch stuff, but it's unlikely that this will change, and this looks less error prone than looking at CC.
Fixes #12547
=> python: fix mingw python detection code in case pkg-config isn't available

test cases/common/173 as-needed/meson.build
The new linker in Sonoma / Xcode 15 considers the dependency via the initializer sufficient to pull in the library. The man page now notes:
The linker never dead strips initialization and termination routines.
They are considered "roots" of the dead strip graph.
I could not find a good way to skip only if the linker version is new enough. Before long everyone will be using the new linker anyway...
=> macos: Skip as-needed test, the linker is too smart

mesonbuild/scripts/coverage.py
Version 2.0 of lcov triggers an error when an exclude pattern is unused.  This can happen when the project has subprojects, but no code in them ends up covered:
lcov: ERROR: 'exclude' pattern '/[...]/subprojects/*' is unused.
(use "lcov --ignore-errors unused ..." to bypass this error)
So, simply do as it says.  Unused patterns doesn't seem problematic (or even interesting) here, so I don't think there's any risk in simply turning this off, which matches what happened with earlier versions of lcov anyway.
=> Fix coverage with lcov 2.0 and uncovered subprojects

mesonbuild/backend/backends.py
This commit modifies the get_target_filename_for_linking function to always return POSIX-style paths, even on Windows systems. This is necessary because the Ninja generator can have issues with Windows-style paths when using the `/WHOLEARCHIVE:` flag.
This is consistent with the syntax accepted by the cl and clang-cl compilers, as documented in the Microsoft documentation: https: //learn.microsoft.com/en-us/cpp/build/reference/cl-filename-syntax?view=msvc-170
Fixes: 12534
=> Always use posix paths when retrieving link name

mesonbuild/backend/vs2010backend.py, test cases/common/52 object generator/meson.build, test cases/common/52 object generator/prog.c, test cases/common/52 object generator/source4.c
Fixes #12550 . Also see that issue for more discussion of the problem.
This in particular reverts commit baa6df2ce73877747c6327a0850a3eaa00e69f5f, which claimed that VS2015 automatically includes outputs from `CustomBuild` commands. As far as I could see from testing on Visual Studio versions 2022, 2015, 2013, and 2010 (stock versions of each, with no settings changed) this is not true: In the example given in the issue, all tested versions fail with the given linker error. I'm not sure what the reason for baa6df2ce73877747c6327a0850a3eaa00e69f5f was - maybe other parts of the project files were changed in the meantime that caused this behavior, or there's some additional configuration I'm missing?
Tests like `nasm/1 configure file` or `common/52 object generator` should already cover …
=> vs: Manually add generated .o objects to project file

mesonbuild/compilers/detect.py
It's possible to use flang on windows, but currently, `detect_fortran_compiler` will only run `guess_nix_linker`, and therefore never pick up the right linker for windows. Use the same try-except fallback that's used for C/C++ compilers also for flang.
Closes #10778
Tested in https://github.com/conda-forge/scipy-feedstock/pull/246
=> detect windows linkers for flang in detect_fortran_compiler

unittests/internaltests.py
The unit test infrastructure hardcodes the architecture as x86_64. On macos, the test_pkgconfig_parse_libs() test creates a few libraries for testing using clang. This leads to the test failing on arm based macs, as darwin_get_object_archs() will skip over these libraries, which then leads to the test failing because of using -l instead of referencing the libraries by their full path.
I am not at all sure this is the best approach.
I am also somewhat confused why nobody else has encountered this? CI apparently just runs on x86_64 macs?
CC: @tristan957
=> macos: Fix test_pkgconfig_parse_libs() test on arm

docs/markdown/snippets/cmake-project-version.md, mesonbuild/cmake/fileapi.py, mesonbuild/cmake/interpreter.py, test cases/cmake/27 dependency fallback/meson.build, test cases/cmake/27 dependency fallback/subprojects/cmMod/CMakeLists.txt
This properly sets the project version in projects meson generates from cmake projects. This allows dependency fallbacks to properly check the version constraints in dependency calls when falling back to a cmake subproject. Before this would fail, because the project version was undefined.
I modified an existing test for this, but feel free to suggest a different approach to testing this. I also am not experienced with any of this, so feedback is welcome!
Motivation was mostly that I had a lot of configure steps fail with the following error message (when trying out cmake fallbacks) and I'd rather not remove the version constraint:
```
Dependency Olm from subproject subprojects/Olm found: NO found undefined but need: '>=3.2.6'
```
=> cmake: parse project version

mesonbuild/dependencies/dev.py
This should have been done in my earlier fix, but kinda forgot to test and fix it there as well.
See https://github.com/mesonbuild/meson/pull/11733 for the discussion.
Fixes: 8284be813 ("dependencies/llvm: strip default include dirs")
=> dependencies/llvm: strip default include dirs also for config-tool version

.github/workflows/macos.yml
We're getting errors that we don't care about on the CI like:
```
==> Pouring node@18--18.19.0.monterey.bottle.tar.gz
The formula built, but is not symlinked into /usr/local
Error: The `brew link` step did not complete successfully
Could not symlink lib/node_modules/npm/docs/content/commands/npm-sbom.md
Target /usr/local/lib/node_modules/npm/docs/content/commands/npm-sbom.md
already exists. You may want to remove it:
rm '/usr/local/lib/node_modules/npm/docs/content/commands/npm-sbom.md'
```
We don't care about node, the only reason it's getting updated is because it's already installed on the image and brew is auto-updating it. So let's disable auto-update.
=> ci: Don't auto-update brew when installing

mesonbuild/backend/vs2010backend.py, mesonbuild/modules/__init__.py, mesonbuild/modules/cuda.py, mesonbuild/modules/external_project.py, mesonbuild/modules/python3.py, mesonbuild/msetup.py
Also fix the vs backend to use the host machine instead of the target machine, since that's more correct.
=> Stop using MachineInfo Interpreter objects when the raw objects are available

mesonbuild/compilers/mixins/elbrus.py
Meson will spawn around ~700 child processes without caching to get default include dirs for my project.
```
$ time ~/dev/meson/meson.py setup build
...
real    0m26,988s
user    0m18,299s
sys     0m9,251s
$ time ~/dev/meson/meson.py setup build
...
real    0m6,774s
user    0m5,367s
sys     0m1,497s
```
=> Cache get_default_include_dirs for E2K

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/compilers/asm.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cs.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/cython.py, mesonbuild/compilers/d.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/java.py, mesonbuild/compilers/mixins/arm.py, mesonbuild/compilers/mixins/ccrx.py, mesonbuild/compilers/mixins/compcert.py, mesonbuild/compilers/mixins/gnu.py, mesonbuild/compilers/mixins/intel.py, mesonbuild/compilers/mixins/islinker.py, mesonbuild/compilers/mixins/metrowerks.py, mesonbuild/compilers/mixins/pgi.py, mesonbuild/compilers/mixins/ti.py, mesonbuild/compilers/mixins/visualstudio.py, mesonbuild/compilers/mixins/xc16.py, mesonbuild/compilers/rust.py, mesonbuild/compilers/swift.py, mesonbuild/compilers/vala.py, mesonbuild/linkers/linkers.py
This is a first step to make `buildtype` a true alias of `debug` and `optimization` options.
See #10808.
Relates to:
- #11645
- #12096
- #5920
- #5814
- #8220
- #8493
- #9540
- #10487
- #12265
- #8308
- #8214
- #7194
- #11732
=> Remove `get_buildtype_args` function

run_project_tests.py
Fixes crash when running the tests and yasm is installed, but nasm is not. When printing the compilers at early startup in run_project_tests.py, we try to detect the nasm compiler, which in this case turns out to be yasm, and its exelist assumes that the meson command is set.
Fixes #12662
=> project tests: handle code internally fetching the meson command

mesonbuild/compilers/mixins/clike.py
This reverts commit 53ea59ad8455277797117d225f326851fe7d369c.
This breaks at least:
- frameworks/17 mpi
- frameworks/30 scalapack
The problem is that openmpi's pkg-config emitted link arguments includes:
```
-Wl,-rpath -Wl,/path/to/libdir
```
The deduplication logic in meson doesn't contain sufficient information to tell when the compiler is passing an argument that requires values, and definitely cannot tell when that argument is split across argv. But for arguments that *can* do this, it is not possible to deduplicate a single argument as standalone, because it is not standalone.
The argument for deduplicating rpath here was that if you have multiple dependencies that all add the same rpath, the Apple ld64 emits a non-fatal warning "duplicate -rpath ignored". Since this is non-fatal, …
=> Revert "clike: Deduplicate rpath linker flags"

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/cuda.py
This PR mainly does following thing:
1. Add support for dumping dependent headers in nvcc
2. Add version check mentioned in [the comment](https://github.com/mesonbuild/meson/pull/11229#issuecomment-1370287546).
3. Nvcc doesn't support `-MQ` flag, so we have to manually escape cuda target name. This PR escape `$out` to `$CUDA_ESCAPED_TARGET`, so now we can just use `-MT` flag in nvcc to generate header dependencies. This is implemented according to [LLVM](https://github.com/llvm/llvm-project/blob/bbe1b06fbb7127d613cb4958e06c737967878388/clang/lib/Basic/MakeSupport.cpp#L11).
This PR supersedes #11229 and #10993, fixes #11969. It also fix some problems mentioned in comments of #11229, including
1. https://github.com/mesonbuild/meson/pull/11229#issuecomment-1369915553
2. …
=> Add support for dumping dependent headers in nvcc

docs/markdown/IDE-integration.md
Please consider the following changes to Documentation -> IDE integration -> Existing integrations:
- Added CLion to the list of integrations (https://www.jetbrains.com/help/clion/meson.html).
- Added "3rd party" to the Meson Syntax Highlighter plugin to indicate that it doesn't come from JetBrains.
- Sorted the list alphabetically.
Thank you!
=> Adding CLion to the list of the existing IDE integrations

mesonbuild/cmake/interpreter.py
I noticed during unrelated work that the lint/mypy check was failing on this, so I propose this fix.
=> Add missing type annotation

docs/markdown/Dependencies.md, docs/markdown/Qt6-module.md, docs/markdown/_include_qt_base.md
Some suggestions after learning to use the Qt6 module for the first time. I think making it clear that `0.63.0` is the effective minimum version for Qt6 would be helpful.
=> Qt documentation updates

docs/markdown/Reference-tables.md, mesonbuild/envconfig.py
Add support for specifying Cython compiler using the `CYTHON` environment variable. If not set, proceed with the names hard coded for Cython. Inspired by issue #1645, which ended up with this solution being implemented for `VALAC` (https://github.com/mesonbuild/meson/commit/bc30ad6dbada192ae4ab0665c0c43781c7957ec7).
There is already [a line in the existing code](https://github.com/mesonbuild/meson/blob/master/run_project_tests.py#L1119) that reads the `CYTHON` variable, but only in test code.
Motivation: MacPorts uses versioned names (e.g., `cython-3.12`) and so does not expose `cython` or `cython3` by default (there is a command to create symlinks to `cython`/`cython3`). Its NumPy package is currently built by [patching NumPy’s bundled version of …
=> envconfig: read CYTHON from the environment and use it if set

.github/workflows/macos.yml
A .yamllint file is created for the lint.yml job, which can also be used on the command line
e.g. to find the problem without the macos.yml commit:
```
$ yamllint .github/workflows/
.github/workflows/macos.yml
81:32     error    syntax error: mapping values are not allowed here (syntax)
```
=> Fix macos.yml and add a yamllint job to lint.yml

mesonbuild/backend/vs2010backend.py
This pull request fixes two separate issues related to the "genvslite" option. These issues don't affect compilation, but prevent intellisense correctly parsing code in the generated project files, arguably the main incentive to generate VS projects in this form in the first place.
To reproduce the issues, do the following:
1. Download and extract [MesonIntellisense.zip](https://github.com/mesonbuild/meson/files/13782183/MesonIntellisense.zip)
2. From the extracted folder, run the following command: `meson.exe setup --genvslite vs2022 "VSProject"`
3. Open "VSProject_vs\TestIntellisense.sln" in Visual Studio
4. Open the "main.cpp" file
You should now see several intellisense errors (red squiggles) like this:
Both of the issues relate to the options that appear in the generated "NMake" …
=> Fix intellisense errors in genvslite projects

.github/workflows/macos.yml, test cases/java/9 jni/meson.build
compiler.has_header() isn't an assert, even though the comments say it is. With `required: true` it is an actual assert.
=> tests: fix java JNI test assert for jni.h existing

mesonbuild/backend/vs2010backend.py
=> Fix warning_level=everything in vs backends

mesonbuild/coredata.py, test cases/common/222 native prop/nativefile.ini
79ed2415e9a5 didn't get this one. I'm not familiar enough with the codebase to be sure that this is the only instance of a missing handling of ParenthesizedNode; someone with more insight may want to look into it. Regardless:
<details>
<summary>meson.build</summary>
```meson
project('a', 'c')
```
</details>
<details>
<summary>a.ini</summary>
```ini
[constants]
foo = ('b' + 'ar')
```
</details>
Before: dies an early death without even printing version info
```
$ meson setup --cross-file=a.ini build
ERROR: Malformed value in machine file variable 'foo': Unsupported node type.
```
After: works fine
```
$ meson setup --cross-file=a.ini build
Version: 1.3.99
...
```
=> machine file: Fix parenthesized expressions

mesonbuild/ast/interpreter.py, mesonbuild/ast/introspection.py, mesonbuild/ast/printer.py, mesonbuild/ast/visitor.py, mesonbuild/build.py, run_mypy.py
What remains is more complicated because of layering violations that will be difficult to fix
=> Fix typing for most of the AST module

docs/markdown/snippets/cpp-debug.md, mesonbuild/compilers/cpp.py
None of the options set here affect ABI and are intended for detecting constraint violations.
For GCC, we simply need to set -D_GLIBCXX_ASSERTIONS.
For Clang, the situation is far more complicated:
* LLVM 18 uses a 'hardened mode' (https://libcxx.llvm.org/Hardening.html). There are several levels of severity available here. I've chosen _LIBCPP_HARDENING_MODE_DEBUG for now given it does the most but does not affect ABI, but we could change it to something more lightweight.
* LLVM 17 uses a similar approach to libstdc++ called '_LIBCPP_ENABLE_ASSERTIONS'
Note that LLVM 17 while in development had fully deprecated _LIBCPP_ENABLE_ASSERTIONS in favour of hardened, but changed its mind last-minute: https://discourse.llvm.org/t/rfc-hardening-in-libc/73925/4.
=> compilers: cpp: wire up stdlib assertions

mesonbuild/backend/ninjabackend.py
=> ninja: Use platform dependent quote instead of shlex.quote() in gcc_rsp_quote()

docs/markdown/snippets/cpp-stldebug.md, mesonbuild/compilers/cpp.py
compilers: cpp: wire up stdlib_stl for Clang
For Clang, we now pass -D_GLIBCXX_DEBUG=1 if debugstl is enabled, and
we also pass -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG.
Per https://discourse.llvm.org/t/building-a-program-with-d-libcpp-debug-1-against-a-libc-that-is-not-itself-built-with-that-define/59176/3,
we can't use _LIBCPP_DEBUG for older Clang versions as it's unreliable unless
libc++ was built with it.
We choose MODE_DEBUG for stldebug while building with assertions will do
MODE_EXTENSIVE.
=> compilers: cpp: wire up debugstl for Clang

mesonbuild/backend/ninjabackend.py, mesonbuild/modules/__init__.py, mesonbuild/modules/gnome.py, test cases/vala/28 generated ui file/TestBox.ui.in, test cases/vala/28 generated ui file/meson.build, test cases/vala/28 generated ui file/test.gresource.xml, test cases/vala/28 generated ui file/test.vala
Fixes #12417.
Introduces two primary changes:
* Makes Vala targets depend on gresources compiled alongside them. The reason behind this is that valac may use same files as resource compiler, which it does for `.ui` files. This leads to race condition if `.ui` files are generated as part of the build and `valac` is invoked before they are (or `.c`/`.o` target is built directly instead of whole executable) and does not cause vala recompilation if `.ui` files are changed.
* Automatically passes `--gresourcesdir` to valac. I consider this to be a bugfix as well rather than a feature since passing of both `--gresources` to valac and `--source` to `glib-compile-resources` was already automated and only led to failure in specific cases.
I'm not 100% happy with how `source_dirs` is set in …
=> Vala: fixes to gresource handling

mesonbuild/cmake/interpreter.py, test cases/cmake/8 custom command/subprojects/cmMod/CMakeLists.txt, test cases/cmake/8 custom command/subprojects/cmMod/cmMod.cpp, test cases/cmake/8 custom command/subprojects/cmMod/cpyBase.cpp.am
GENERATED files can be used as dependencies for other targets, so it's misguided (at best) to filter them with a blunt whitelist.
However, there does exist an extension that needs to be skipped: on Windows + MSVC, CMake will by default try to generate a Visual Studio project, and there dependencies with no inputs are instead tied to a dummy .rule input file which is created by the generation step. The fileapi will still report those, so it will cause Meson to bail out when it realises there's no such file in the build tree.
Fixes #11607
=> cmake: Fix blunt target filtering skipping GENERATED dependencies

mesonbuild/backend/backends.py, test cases/unit/17 prebuilt shared/meson.build, test cases/unit/17 prebuilt shared/meson_options.txt, unittests/allplatformstests.py
Fixes https://github.com/mesonbuild/meson/issues/12338
This PR also extends the logic in Backend to produce build rpaths for any external *versioned* `.so`'s listed on the link line, e.g. `/path/to/libxyz.so.1.2.3`. CMake happily generates paths of this form instead of the currently supported `/path/to/libxyz.so`. The rpaths added here get removed on install, regardless of whether the `.so` was versioned or unversioned.
=> Add build rpaths for CMake dependencies

mesonbuild/dependencies/misc.py, test cases/common/184 openmp/meson.build
Resolves issue https://github.com/mesonbuild/meson/issues/5298
I do know that this fix resolves the referenced issue for clang-cl 17.0.6 on windows (https://github.com/peter-urban/demonstrate-meson-openmp/actions/runs/7474295927/job/20340150365)
However, I am struggling with the test cases (test cases/common/184 openmp/meson.build)
- I am not 100% sure that i made the correct change to activate openmp testing for clang-cl
- I do not know which is the minimum clang-cl version that works now
Hints and comments welcome
=> fix openmp dependency for clang-cl

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/rust.py, test cases/rust/23 crt-static/lib.c, test cases/rust/23 crt-static/main.rs, test cases/rust/23 crt-static/meson.build, test cases/rust/23 crt-static/test.json
For the same reason as for static libraries, we have to use -l when generating static executables.
Fixes: https://github.com/mesonbuild/meson/issues/12585
---
I wasn't sure how to test this, because we'd have to skip the tests if it's not possible to build static executables, and I don't know how to do that from a test case.
=> rust: fix linking static executables

mesonbuild/compilers/compilers.py
With LTO, the linker will re-execute the compiler and various warnings may be emitted. We must therefore pass -Werror to the linker as well when -Werror is enabled to capture these. This is only required / useful with LTO.
Closes: https://github.com/mesonbuild/meson/issues/7360
=> Compilers: pass -Werror to the linker with b_lto

mesonbuild/linkers/detect.py
xtools is in use on Gentoo Prefix x86_64 and ppc based Darwin installs. Pick it up as a valid linker.
Since xtools is answering with a version to --version, as opposed to ld64, detection of xtools in the ld64 handling block is not possible, since --version already succeeded.
Author: Fabian Groffen <grobian@gentoo.org>
Bug: https://bugs.gentoo.org/868516
Bug: https://github.com/mesonbuild/meson/issues/10805
=> linkers_detect: detect xtools (Apple ld64 derivative)

mesonbuild/interpreter/mesonmain.py
Per the docs, it is available since 0.48.0. Notify about this at runtime too.
Fixes #12773
=> Add missing FeatureNew for meson.add_dist_script

docs/markdown/Build-targets.md
Use common conventions for documentation of shared library version and soversion. In general, the numeric version part is expected to be first component of version, so suggest this in the example code.
=> docs: Use common conventions for shared libs

mesonbuild/backend/backends.py, mesonbuild/backend/vs2010backend.py, mesonbuild/backend/xcodebackend.py
Currently, this pull request is a work-in-progress and contains some "questionable" fixes. They will be cleaned up later on.
Known issues (incomplete list):
Current limitations (on my end):
- ~~Only able to test on arm64 Mac~~ Recently obtained old x86_64 Mac to test on, so will test on both architectures
- Using latest stable version of Xcode (14.3.1 at the time of this PR) and macOS (13.5)
=> Repair Xcode backend as much as possible

mesonbuild/compilers/detect.py
Currently both print `Detecting linker via`, which can be confusing. Clarifying this by printing "archiver" instead of "linker" for the static linker/archiver
=> Differentiate message between dynamic linker and archiver

mesonbuild/dependencies/hdf5.py, test cases/common/219 include_type dependency/meson.build, test cases/frameworks/25 hdf5/test.json
- hdf5 tests:
- dependencies: detect when it is bad
- CI: mark as not-found and skipped for macOS
- test that uses boost, needs to require a suitable `$CXX -std`
=> CI fixes for macOS

docs/markdown/Dependencies.md, docs/markdown/snippets/numpy-custom-dependency.md, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/python.py
These are being added for NumPy 2.0 (see https://github.com/numpy/numpy/pull/25570#issuecomment-1912545457). The implementation closely follows the one for the `pybind11` dependency.
=> Add a numpy dependency with pkg-config and configtool methods

mesonbuild/backend/vs2010backend.py
=> Fix minsize optimization for vs backend

mesonbuild/dependencies/cmake.py, mesonbuild/dependencies/data/CMakeListsLLVM.txt, mesonbuild/dependencies/dev.py
In https://github.com/mesonbuild/meson/commit/89146e84c9eab649d3847af101d61047cac45765, a heuristic was introduced where
if libLLVMSupport is available as a static library, LLVM itself is assumed
to be availble as a static library as a whole.
This is unfortunately not the case at least on Gentoo and Arch Linux, where
a subsequent llvm-config call yields:
```
$ /usr/lib/llvm/17/bin/llvm-config --libfiles --link-static
llvm-config: error: missing: /usr/lib/llvm/17/lib64/libLLVMTargetParser.a
llvm-config: error: missing: /usr/lib/llvm/17/lib64/libLLVMBinaryFormat.a
llvm-config: error: missing: /usr/lib/llvm/17/lib64/libLLVMBitstreamReader.a
llvm-config: error: missing: /usr/lib/llvm/17/lib64/libLLVMRemarks.a
[...]
```
On Gentoo, where LLVM's static libraries are not included, we still have: …
=> cmake: improve heuristics for static LLVM detection

docs/yaml/functions/alias_target.yaml, mesonbuild/interpreter/interpreter.py
This was accidentally changed in
982973f303e3d0431d9b79f89cdf2c8f1ee67bc0, when alias_target was changed to use typed_pos_args.
=> Document that alias_target accepts run_tgts since 0.60.0

mesonbuild/backend/backends.py
The type of quoting was changed in 522392e to one that is suitable for use with `cmd.exe` on Windows. However, the documentation states that the type of quoting in `MESONINTROSPECT` is compatible with `shlex.split()` and elsewhere in the code, the same variable is still quoted with `shlex.quote()`. As mostly identified in #12148, there are a few choices:
1. Use `shlex.quote()` consistently and support Python but not `cmd.exe`.
2. Use `join_args` and support `cmd.exe` but not Python.
3. Use `join_args` and support splitting through the `mesonbuild` Python library.
This commit implements the first option and reverts part of 522392e.
Regression testing is implemented in #12115.
Fixes #12148
=> backends: restore shlex quoting of MESONINTROSPECT

mesonbuild/backend/backends.py, mesonbuild/minstall.py
Raise MesonException if a postconf script fails to let the user know about the failure.
=> Raise if a postconf script fails

docs/markdown/Dependencies.md
A config-tool method has been supported since c02593f and it says so just a few lines below the outdated statement.
=> docs: Remove outdated HDF5 dependency pkg-config statement

.github/workflows/macos.yml, .github/workflows/msys2.yml, .github/workflows/os_comp.yml, run_project_tests.py
On Debian systems the cython compiler binary is installed as `cython3`. The current logic for detecting whether to run the Cython unit tests instead checks for `cython` or the value of the `CYTHON` environment variable, which leads to cases where the underlying Meson can correctly compile Cython code but the test harness excludes these tests from execution because it cannot find `cython3`.
This commit makes the test harness use the same detection method as Meson itself. It also takes the opportunity to refactor some existing code which does the same job for Objective C and Objective C++ tests to avoid repetition.
=> run_project_tests: Fix Cython compiler detection

mesonbuild/scripts/coverage.py
The .lcovrc file can contain several directives for genhtml, mostly pertaining the visualisation of the generated HTML report. Passing the config file to genhtml allows the user to customize their report.
Fixes #12863
=> coverage: pass .lcovrc config file to genhtml

docs/yaml/functions/find_program.yaml
They accept list as documented:
https://github.com/mesonbuild/meson/blob/616bf1f79d855c6d5494f71806ce42961d8ce85e/docs/yaml/functions/dependency.yaml#L189
=> doc: fix descriptions of dependency and find_program

mesonbuild/backend/ninjabackend.py
Using scan-build gives the following warning: "Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated."
This commit fixes this issue by adding the setup keyword to the scan-build invocation.
=> Fix warning in scan-build

mesonbuild/modules/python.py, test cases/python/5 modules kwarg/meson.build, test cases/python/5 modules kwarg/test.json
0e7fb07f915b7a2b04df209fbacd92aca19c87af introduced a subtile bug in the Python module.
If a python version is found, but is missing a required module,
it is added to the list of python installations, but the
`run_bytecompile` attribute for that version was not initialized.
Therefore, if any other python version added something to install, it
was raising a KeyError when trying to read the `run_bytecompile`
attribute for the python version with missing module.
Stack trace:
```
File "<HIDDEN PATH>\mesonbuild\mesonmain.py", line 194, in run
^^^^^^^^^^^^^^^^^^^^^^^^^
File "<HIDDEN PATH>\mesonbuild\msetup.py", line 358, in run
app.generate()
File "<HIDDEN PATH>\mesonbuild\msetup.py", line 181, in generate
return …
```
=> Fix KeyError in Python module

mesonbuild/build.py
Since we don't get a location for these errors, we can at least tell you which targets you happen to be mixing together that produce this problem.
Ran into while trying to debug a target mixing bug.
=> Provide a better error message when mixing host and build machines

mesonbuild/build.py, test cases/common/168 preserve gendir/meson.build
This code cleverly tried to use a fancy new pathlib.Path method to get the os.path.commonpath of two paths and check whether one is inside the other. It failed pretty badly, because of a hidden secret of pathlib: it is designed to throw random exceptions at all times instead of performing useful work. Return to `os.path`.
In particular, before this change, we wanted to check if files are NOT in a subpath of `preserve_path_from`, and raise a meson "ERROR: xxx" in such a case. However, the code to check for it would raise a python ValueError if that was the case, so we never got to the properly formatted error.
=> fix crash in generator.process() with an invalid preserve_path_from

mesonbuild/build.py, mesonbuild/modules/i18n.py
The frontend is supposed to validate this, and does in other cases. In some cases the i18n module makes this work by ensuring that install_dir is set to a valid value.
Also fix some incorrect annotations.
=> modules/i18n doesn't always validate that `install_dir` is set when `install` is True

mesonbuild/msubprojects.py, mesonbuild/wrap/wrap.py
`Resolver.resolve()` alters the state of the `Resolver()` object including creating new attributes. In some cases though other public methods relying on this state can be called without `resolve()` being called first, which causes errors. Instead, pass the state in directly. 
Fixes: #12869
=> Handle conditions where wrap.Resolver expects state that doesn't exist

mesonbuild/scripts/env2mfile.py
As putting them in the `properties` section is considered deprecated, and Meson would then complain when trying to consume the resulting machine file.
=> env2mfile: move language args to `built-in options`

docs/yaml/objects/compiler.yaml
This was inherited from documentation of build target, but some sentences do not make sense in the context of the preprocessor.
=> doc: fix compiler.preprocess varargs documentation

docs/markdown/Rust-module.md, docs/markdown/snippets/rust-bindgen-cpp.md, docs/markdown/snippets/rust-bindgen-language.md, docs/markdown/snippets/rust-bindgen-std.md, mesonbuild/compilers/compilers.py, mesonbuild/interpreter/interpreter.py, mesonbuild/modules/__init__.py, mesonbuild/modules/rust.py, test cases/rust/12 bindgen/cpp/meson.build, test cases/rust/12 bindgen/meson.build, test cases/rust/12 bindgen/src/cpp.rs, test cases/rust/12 bindgen/src/header.hpp, test cases/rust/12 bindgen/src/impl.cpp, test cases/rust/12 bindgen/test.json
This has 3 distinct changes wrapped up into one smallish PR:
- Meson will check the header extension against it's own heuristic for whether a header is C or C++ instead of relying on bindgen, which only supports `.hpp`
- Meson will add the appropriate C or C++ standard to the clang invocation
- The internal finder for bindgen has it's version constraint arguments exposed.
=> Improve rust.bindgen's handling of of C++

docs/markdown/snippets/environment_unset.md, docs/yaml/objects/env.yaml, mesonbuild/interpreter/interpreterobjects.py, mesonbuild/utils/core.py, test cases/common/273 environment/meson.build, test cases/common/273 environment/testenv.py
My usecase is that I'm running from an active Python venv, and I need to perform some function calls inside different python venv, but the `VIRTUAL_ENV` environment variable interferes. Therefore, I need to unset it in the environment I use to perform the function call.
=> env.unset method

mesonbuild/interpreterbase/interpreterbase.py, mesonbuild/mparser.py, test cases/failing/130 utf8 with bom/meson.build, test cases/failing/130 utf8 with bom/test.json, test cases/failing/131 utf8 with bom subdir/meson.build, test cases/failing/131 utf8 with bom subdir/subdir/meson.build, test cases/failing/131 utf8 with bom subdir/test.json, test cases/failing/132 utf8 with bom options/meson.build, test cases/failing/132 utf8 with bom options/meson.options, test cases/failing/132 utf8 with bom options/test.json
Some text editors on Windows may use utf8bom encoding by default. Prevent crash by stripping the bom before trying to interpret the build files.
Fixing this at the Lexer level allows to do it at one place. Another solution would be to open the build files with `utf-8-sig` encoding, but that would require to do it at each places build files are opened.
Fixes #12766.
=> Detect utf8 bom from meson build files

docs/markdown/Unit-tests.md, docs/markdown/snippets/sanitizers_test.md, docs/yaml/functions/test.yaml, mesonbuild/mtest.py
Followup to 7b7d2e060b447de9c2642848847370a58711ac1c which handles ASAN and UBSAN.
It turns out that MSAN needs the same treatment. I've checked other sanitizers like HWASAN and TSAN - it looks like they may both need it too, but Meson doesn't currently suppose those anyway (see https://github.com/mesonbuild/meson/pull/12648).
=> mtest: set MSAN_OPTIONS to abort by default

docs/markdown/Rust-module.md, mesonbuild/modules/rust.py, test cases/rust/12 bindgen/meson.build, test cases/rust/12 bindgen/src/header3.h, test cases/rust/12 bindgen/src/main3.rs
This way the `rust.bindgen` can generate a second output being a C file, which contains wrapper functions for static inline ones.
This output file can then be compiled via C targets.
=> meson/rust: wrap `bindgen`s `wrap-static-fns` functionality

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/detect.py, mesonbuild/environment.py, mesonbuild/scripts/coverage.py
In this PR, we attempt to implement the logic devised in issue #12145 and fix how Meson detects and uses LLVM tooling when Clang is picked as compiler.
This addresses Clang/LLVM 17 and 18 being a thing now for the get_llvm_tool_names hard-coded list. Plus it makes it so Meson does its best that if a specific suffixed Clang has been chosen, that it will also pick to use a matching specifically suffixed llvm-ar and llvm-cov rather than being able to pick older tools and configuring a broken build directory.
the GCOV environment variable is still ignored with this PR, which is still a problem, but that can be solved separately. Fixes #12145
=> Fix: LLVM tool detection

mesonbuild/cmake/tracetargets.py, mesonbuild/dependencies/framework.py, test cases/osx/9 framework recasting/main.cpp, test cases/osx/9 framework recasting/meson.build
This PR allows the combination of macOS + GCC to still find frameworks. This can already be done through CMake's own support of framework lookup (which is undocumented at the moment).
However, there's a catch: CMake's fileapi sometimes exposes these through raw framework directories, which are recast at generation time into `-F /path/to/framework/folder -framework name`. This needs to be done manually, so I duplicated two bits of code in `ExtraFrameworkDependency` to achieve this.
Fixes #12160
=> cmake: Allow recasting a CMake dependency into an Apple framework

mesonbuild/rewriter.py
Alterations to kwargs come in two flavors:
1. Remove/replace values (delete/set)
2. Modify values (add/remove)
Only for the second flavor do we care about the type of any existing value.
---
This is a _minor_ rewrite of the rewriter. When merged, #12277 will need to be rebased.
Changes:
- The type modification classes no longer have a `set_value` method.
- The `new_node` and `supported_nodes` methods of the type modification classes are now classmethods.
- The `new_node` method of the type modification classes is now public and can take an initial value.
- When a variable is too complex to modify, the action is actually skipped.
Conceptually, the mutability of kwargs now follows Python variable assignment. You don't change a value by reassigning to a variable name. Instead, this replaces …
=> rewriter: allow setting values regardless of the previous type

mesonbuild/compilers/cuda.py
* `-Wpedantic` creates useless churn due to its use of gcc-line directives: ../foo.cu:1:3: warning: style of line directive is a GCC extension 1 | namespace Foo {
|   ^~
https://stackoverflow.com/a/31001220
=> nvcc: avoid adding `-Wpedantic` to compile lines

mesonbuild/compilers/detect.py, mesonbuild/coredata.py, mesonbuild/interpreter/interpreter.py, run_project_tests.py, test cases/unit/122 reconfigure base options/meson.build, unittests/allplatformstests.py, unittests/baseplatformtests.py, unittests/platformagnostictests.py
Fixes #12920.
Note: #12923 is still an issue, i.e. when no languages are setup.
=> Fix base and compiler options not reconfigurable. 

docs/markdown/Creating-releases.md, docs/markdown/Reference-tables.md, docs/yaml/builtins/meson.yaml, mesonbuild/mdist.py, test cases/unit/35 dist script/subprojects/sub/dist-script.py, test cases/unit/35 dist script/subprojects/sub/meson.build, test cases/unit/35 dist script/subprojects/sub/version-test.py
Together with #12782, this allows versioning via git (#688) as follows.
`meson.build`:
```meson
project('tig', 'c',
version : run_command('version.sh', 'get_vcs').stdout.strip())
meson.add_dist_script('version.sh', 'set_dist', meson.project_version())
```
`version.sh`:
```sh
#!/bin/sh
if [ "$1" = "get_vcs" ]; then
git -C "$MESON_SOURCE_ROOT" describe --always --dirty
elif [ "$1" = "set_dist" ]; then
$MESONREWRITE --sourcedir="$MESON_PROJECT_DIST_ROOT" kwargs set project / version "$2"
else
exit 1
fi
```
Without #12782, the rewriting will not work, so that one needs to be merged before the current pull request.
=> Support `meson dist` when getting project versions from VCS

mesonbuild/compilers/mixins/clike.py, mesonbuild/linkers/linkers.py, unittests/internaltests.py
- We erroneously include `-Wl,-soname,libfoo.so.1` inside of groups
- We pointlessly make a single library into a group.
Ref: https://github.com/google/liblc3/pull/45#issuecomment-1965603859
=> reduce unnecessary use of --start-group in compiler command lines

docs/markdown/Users.md
- [asteria](https://github.com/lhmouse/asteria) is a scripting language implemented in modern C++, still under development.
- [mcfgthread](https://github.com/lhmouse/mcfgthread) is the cornerstone library for the `mcf` thread model [since GCC 13](https://github.com/gcc-mirror/gcc/commit/f036d759ecee538555fa8c6b11963e4033732463).
=> Users:  Add asteria and mcfgthread

test cases/common/103 has header symbol/meson.build
musl 1.2.5 exposes this symbol in the default profile, and in future will expose it unconditionally, as it is on track to becoming part of POSIX.
So rather than maintaining a list of systems to run this on, let's just skip testing the feature test macro if we find ppoll in the default proifle.
=> test cases/common/103 has header symbol: fix for musl 1.2.5

mesonbuild/backend/ninjabackend.py, test cases/rust/24 system deps/main.rs, test cases/rust/24 system deps/meson.build, test cases/rust/24 system deps/wrapper.rs
When linking with a Rust rlib, we should also link with its external
system dependencies. This was currently done only for C ABI crates, do
it for both rlib and staticlib now.
=> rust: Link with rlib external dependencies

mesonbuild/ast/introspection.py, mesonbuild/compilers/detect.py, mesonbuild/coredata.py, mesonbuild/interpreter/interpreter.py, mesonbuild/modules/java.py, run_project_tests.py, test cases/unit/122 reconfigure base options/subprojects/sub/meson.build, unittests/allplatformstests.py, unittests/platformagnostictests.py
cc4cfbcad92945a1629c80664e1eb755c68905dd added detection for unknown base options, but it was not working for subproject base options. This should fix it.
=> Fix detection of unknown base options in subproj

.github/workflows/lint.yml
Version 1.9 removes support for python 3.7, so we either need to pin the version to 1.8 as long as we're support Python 3.7, or we need to drop linting for 3.7
=> CI: pin mypy to version 1.8

cross/ti-c6000.txt, docs/markdown/Reference-tables.md, docs/markdown/snippets/ti_c6000_compiler_support.md, mesonbuild/build.py, mesonbuild/compilers/c.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/detect.py, mesonbuild/compilers/mixins/clike.py, mesonbuild/envconfig.py, mesonbuild/linkers/linkers.py
Created new compiler and linker classes:
- C6000CCompiler
- C6000CPPCompiler
- C6000Linker
- C6000DynamicLinker
It was necessary the compiler  can detect both extension for static libs (*.a, *.lib) and for dynamic libs (*.dll, *.so) => added function is_baremetal()
Added new cpu family 'c6000' into known_cpu_families for which the C6000 compiler is used (https://www.ti.com/tool/C6000-CGT)
=> Added support for Texas Instruments C6000 compiler.

mesonbuild/interpreter/interpreterobjects.py
Use a capital letter at the beginning of a sentence.
=> interpreterobjects.py: fix a typo

mesonbuild/dependencies/base.py, mesonbuild/interpreter/mesonmain.py, test cases/common/98 subproject subdir/meson.build
Otherwise internal dependencies have auto-generated names that are not human readable. Instead, use the name that the dependency overrides. For example:
```meson
meson.override_dependency('zlib', declare_dependency())
dep_zlib = dependency('zlib')
assert(dep_zlib.name() == 'zlib')
```
Fixes: #12967
=> interpreter: when overriding a dependency, override its name too

mesonbuild/cargo/interpreter.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/cython.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/mixins/emscripten.py, mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, mesonbuild/compilers/rust.py, mesonbuild/coredata.py, mesonbuild/mcompile.py, mesonbuild/optinterpreter.py, mesonbuild/utils/universal.py, test cases/failing/98 number in combo/test.json, test cases/failing/99 bool in combo/test.json, unittests/platformagnostictests.py
By adding the option name to UserOption object, it is now possible to
display the name of the affected option when the given option value is
not valid.
Fixes https://github.com/mesonbuild/meson/issues/12635
=> Improve error messages for invalid option values

unittests/baseplatformtests.py, unittests/linuxliketests.py
On Arch's shiny new 48-core/96-thread build server, the `test_install_log_content` test fails because of an unexpected `invalid-symlink.txt` file. Apparently the test runs in parallel with `test_install_subdir_symlinks`, which modifies the `59 install subdir` source directory.
To fix this, make `install_subdir_invalid_symlinks` copy the entire test into a tmpdir before modifying it.
=> tests: Fix unit tests with high parallelism

mesonbuild/environment.py
environment: fix LLVM 18 support in get_llvm_tool_names()
In 67afddbf431140c1ee064bf79a2fa5a95575488e, we added LLVM 18, but LLVM >= 18
uses a new version scheme of X.Y, not X.0.Y (where using "X" was enough).
See https://discourse.llvm.org/t/rfc-name-the-first-release-from-a-branch-n-1-0-instead-of-n-0-0/75384.
Without this, I get a test failure:
```
mesonbuild.interpreterbase.exceptions.InterpreterException: Assert failed: config-tool and cmake returns different major versions
-> frameworks: 15 llvm    (method=combination link-static=False)
```
Fixes: https://github.com/mesonbuild/meson/issues/12961
Signed-off-by: Sam James <sam@gentoo.org>
=> environment: fix LLVM 18 support in get_llvm_tool_names()

mesonbuild/modules/cmake.py
Probably a copy-and-paste error
=> cmake: fix incorrect decorator for append_link_args

docs/markdown/snippets/meson_configure_options_changes.md, mesonbuild/ast/introspection.py, mesonbuild/coredata.py, mesonbuild/interpreter/interpreter.py, mesonbuild/mconf.py, unittests/baseplatformtests.py, unittests/platformagnostictests.py
It was pointed out to me recently that doing the following will not work:
```
meson setup builddir
echo "option('foo', type : 'string', value : 'foo')" > meson.options
meson configure builddir -Dfoo=bar
```
Since meson doesn't know that for exists. This does not make for a good user experience.
This PR attempts to make that situation better in most cases. This works by tracking which option file (meson.options or meson_options.txt) was used, and a hash of that file. When `meson configure` is called, if the option file has been added, removed, or the hash has changed, then meson setup will reload the options, which allows it to correctly set new or changed options, as well as correctly rejecting options that have been removed.
There is one case I know that doesn't work, which is the case …
=> Reload the option file in meson configure if it has changed on disk

mesonbuild/mdevenv.py, mesonbuild/utils/universal.py
It's utterly broken, and only works when one path is inside the other:
```
File "/usr/lib/python3.12/site-packages/mesonbuild/mesonmain.py", line 194, in run
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/mesonbuild/mdevenv.py", line 188, in run
write_gdb_script(privatedir, install_data, workdir)
File "/usr/lib/python3.12/site-packages/mesonbuild/mdevenv.py", line 142, in write_gdb_script
rel_path = gdbinit_path.relative_to(workdir_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.12/pathlib.py", line 682, in relative_to
raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: '/path/to/builddir/.gdbinit' is not in the subpath of '/path/to/workdir' …
```
=> devenv: Don't use Path.relative_to() to resolve relative paths

mesonbuild/mtest.py
If `MSAN_OPTIONS` is not set, `UBSAN_OPTIONS` is overwritten, even if `UBSAN_OPTIONS` is already set. This fix sets `MSAN_OPTIONS` instead.
=> mtest: fix setting `MSAN_OPTIONS` when not set, rather than `UBSAN_OPTIONS`

test cases/frameworks/15 llvm/test.json
They were skipped with llvm 17 based on the version, and they are now no longer skipped with v18 and also pass now.
This depends on #12964 for llvm 18 support in meson.
=> tests: don't expect msys2 llvm cmake tests to skip with llvm 18

mesonbuild/backend/ninjabackend.py, mesonbuild/scripts/depscan.py
This is all work that's been pulled from https://github.com/mesonbuild/meson/pull/12539, but is perfectly fine as a standalone fixes with no user-facing changes. I'm hoping to land this sooner so that I don't have to continue to carry this for the two-step depscanner work
=> Cleanups, fixes, and speedups for the depscanner

mesonbuild/scripts/depfixer.py
This somewhat aligns "darwin" (Mach-O) with how ELF RPATHs are treated. Instead of blindly removing all RPATHs, only remove the ones that are in the rpath_dirs_to_remove set.  This way, RPATHs that were added by the toolchain or user are left untouched.
It is important not to remove RPATHs as they may be vital for the executable at runtime.  Issues #12045 and #12288 are examples of this.
Fixes: https://github.com/mesonbuild/meson/issues/12045
=> depfixer: change fix_darwin to act like fix_rpathtype_entry

mesonbuild/scripts/env2mfile.py
It makes no sense to add them into vala_link_args, for example.
=> env2mfile: Only consume LDFLAGS for relevant languages

mesonbuild/compilers/mixins/clang.py, mesonbuild/compilers/mixins/visualstudio.py, mesonbuild/linkers/detect.py, mesonbuild/linkers/linkers.py, test cases/common/180 has link arg/meson.build
This PR fixes passing and detection of link arguments when using Microsoft's linker in combination with clang-cl or stock clang.
Currently, not only Meson lacks a way to induce a `--fatal-warnings` on LINK.exe, thus rendering all flag detection morose, it is also unable to pass flags appropriately by wrapping them in `-Wl,`.
This commit fixes it by implementing `fatal_warnings()` in the MSVCDynamicLinker and ClangCLDynamicLinker classes, and by implementing the requisite conversion steps in linker_to_compiler_args for ClangCompiler.
=> linkers: Fix detection of link arguments to Clang(-cl) + MSVC

docs/markdown/Windows-module.md, docs/yaml/functions/custom_target.yaml, docs/yaml/functions/generator.yaml, docs/yaml/functions/run_target.yaml, mesonbuild/backend/vs2010backend.py, mesonbuild/build.py, mesonbuild/interpreter/type_checking.py, test cases/common/51 run target/meson.build, test cases/common/71 ctarget dependency/meson.build
Code like
```meson
a = custom_target(..., output: 'foo', 'bar')
foo = a[0]
run_target(..., depends: foo)
```
does not setup otherwise.
=> run_target/DEPENDS_KW: accept CustomTargetIndex

mesonbuild/interpreter/compiler.py
We incorrectly warns that `compiler.run()` is new in 1.5.0 for Fortran, but that works fine for older versions (tested with 1.2.3). This makes sense, as FortranCompiler inherits CLikeCompiler
=> interpreter/compiler: Fortran.run() has always worked

mesonbuild/dependencies/boost.py
Skip the check filtering on that condition, otherwise only .a files will be found.
=> boost.py: OpenBSD does not use the convention that the .so version numbers are equal to the boost version number

mesonbuild/modules/gnome.py, test cases/frameworks/7 gnome/mkenums/meson.build
Commit 83facb39593fbfa4d9cd68e86f5f56f86f1fe1eb switched to using `textwrap.dedent` for the code templates for `gnome.mkenums_simple`. That changed indentation, however, making the generated code harder to understand.
We improve this by properly indenting the multiline strings before dedenting them. For optional parameters `decl_decorator` and `header_prefix`, we add a newline if they are set to keep separation between generated code blocks.
Also, some tests for `gnome.mkenums_simple` were only compiled, but not run. Most bugs will be caught by compilation alone, but it's better to run the generated binary too in case there are runtime issues in the generated code. The naming of all enum tests is now unified as well.
**Before and after**\
To illustrate what I mean with hard to understand, …
=> gnome: Improve mkenums_simple code generation and running tests

run_project_tests.py, run_tests.py, test cases/frameworks/4 qt/meson.build
Spamming tons of stuff for passing tests is distracting. Only print errors to stdout.
Also includes a one liner documentation fix because I was too lazy to post it in a separate PR.
=> Clean the output of test runs

mesonbuild/dependencies/dev.py
The warning we have is not clear, as we've had several questions about why the CMake finder for LLVM isn't being used. I have found the warning that both a C and C++ compiler must be available and enabled to be unclear, and I've attempted to make the warning more helpful. Also make it not fatal, since it's probably not in the control of the end user that the CMake method is being tried
=> Improve the warning that LLVM lookup by CMake needs both a C and C++ compiler

docs/markdown/howtox.md
Adds a howto section describing how to put files in a separate build target and override the unity build setting, and why you might want to do this.
Closes: #13031
=> docs: Howto exclude file from unity build

mesonbuild/backend/backends.py, mesonbuild/backend/xcodebackend.py, mesonbuild/compilers/asm.py, test cases/nasm/1 configure file/meson.build, test cases/nasm/2 asm language/meson.build, test cases/nasm/3 nasm only/meson.build, test cases/nasm/4 through configure/dummy.asm.in, test cases/nasm/4 through configure/dummy.def, test cases/nasm/4 through configure/meson.build
Hi @xclaesse @eli-schwartz, and cc @dragonmux,
This PR implements support for building Nasm files with the Xcode backend generator. This was inspired by https://aomedia-review.googlesource.com/c/aom/+/173602, where I realised that both CMake and Meson lacked support for it.
The approach is pretty simple, I've fixed the .asm files to have the `sourcecode.nasm` file type, and then I added a per-target build rule that packs all the compiler flags into a shell script. For this, I factored out a bit of code pertaining to the VS backend and the escaping code for the shell script build phase.
Since Xcode supports GNU-style escaped spaces in the Makefile rules, I've added support for it as well. This is supported only with Nasm, as Yasm spits them unescaped and Xcode cannot parse them.
Finally, I …
=> backends: Add Nasm build rules to Xcode

data/shell-completions/zsh/_meson, docs/markdown/snippets/bztar_support.md, mesonbuild/mdist.py, unittests/allplatformstests.py
Some projects, like Postgres, distribute code in this format.
=> Add bztar support to meson dist

mesonbuild/dependencies/python.py
`Compiler.has_header` returns a tuple, this is always considered "truthy" in Python which makes the header check for `Python.h` a no-op. The first return value is the actual test result, check that explicitly.
Fixes https://github.com/mesonbuild/meson/issues/12862
=> python: Fix header check for system method

mesonbuild/backend/ninjabackend.py
When getting debug file arguments we can sometimes pass None, where a None is unexpected. This becomes a particular problem in the Cuda compiler, where the output will unconditionally be concatenated with a static string, resulting in an uncaught exception. This is really easy to spot once we annotate the functions in question, where a static type checker like mypy easily spots the issue.
This commit adds those annotations, and then fixes the resulting error.
Fixes: #12997
=> backend/ninja: Fix cases where None is passed when unexpected

mesonbuild/compilers/mixins/gnu.py
If there're weird symlinks in the system like Fedora RISC-V
/lib64/lp64d -> /lib64
and glibc is installed to /lib64/lp64d
When calling cxx.find_library, it will first search for /lib64/lp64d/../lib64/lp64d/
https://github.com/mesonbuild/meson/blob/2fbc7b5ce3aced483b196dd10ca9eee1713b7494/mesonbuild/compilers/mixins/clike.py#L205
https://github.com/mesonbuild/meson/blob/2fbc7b5ce3aced483b196dd10ca9eee1713b7494/mesonbuild/compilers/mixins/gnu.py#L475
Then generate linkargs ['/lib64/lp64d/../lib64/lp64d/libbz2.so']
which will cause ninja build fail: https://github.com/ninja-build/ninja/issues/1330
Here is a simple example
```
meson.build：
project('my_project', 'c')
c_compiler = meson.get_compiler('c')
bzip2_dep = c_compiler.find_library(
'bz2',
dirs: '/usr/lib',
)
executable('main', …
```
=> Fix ninja cannot find the library when libraries contain symlinks.

mesonbuild/coredata.py
The keys in `BUILTIN_OPTIONS_PER_MACHINE` are `OptionKey` values, not strings.
This fixes a regression introduced in 71db6b0.
=> coredata: Fix is_per_machine_option() for builtins

docs/markdown/Machine-files.md
Refer https://github.com/mesonbuild/meson/blob/master/docs/markdown/Machine-files.md?plain=1#L285
=> docs: fix a typo of path

docs/markdown/Style-guide.md
- Mention 2 space indent seems to be the most ideomatic
- Mention trailing commas are good
- Update example to use trailing commas
=> Add a few more notes to the style guide

mesonbuild/compilers/vala.py, test cases/vala/29 compiler.links/meson.build
Fixes issue #12959
compiler.links command for vala crashes
=> Fix compiler.links for vala

docs/markdown/snippets/find_library_name.md, docs/yaml/objects/dep.yaml, mesonbuild/interpreter/interpreterobjects.py
This allows `cc.find_library().name()` to work, just like `dependency().name()`.
Fixes: #13053
=> interpreter: implement the `name()` method for `ExternalLibraryHolder`

test cases/unit/71 summary/meson.build
Fedora has switched to zlib-ng, which has a version of `1.3.0.zlib-ng`, causing AllPlatformTests.test_summary to fail. dl is much less likely to change format.
=> Use dl instead of zlib for checking an external dependency

data/shell-completions/bash/meson, data/shell-completions/zsh/_meson, docs/markdown/Unit-tests.md, docs/markdown/snippets/test_interactive.md, mesonbuild/mtest.py
This is very similar to --gdb, except it doesn't spawn GDB, but connects stdin/stdout/stderr directly to the test itself. This allows interacting with integration tests that spawn a shell in a container or virtual machine when the test fails.
In systemd we're migrating our integration tests to run using the meson test runner. We want to allow interactive debugging of failed tests directly in the virtual machine or container that is spawned to run the test. To make this possible, we need meson test to connect stdin/stdout/stderr of the test directly to the user's terminal, just like is done with the --gdb option.
=> Add meson test --interactive

docs/markdown/snippets/cmake_build_type.md, mesonbuild/cmake/interpreter.py
This is a follow up to #12947. It contains the release note snippet as well as the formatting/typing changes requested by @dcbaker. I considered adding annotations and all-caps for the constants in `cmake/common.py` as well, but since the `language_map` variable from that module is 'exported' and used elsewhere I decided not to. It may make sense to at least add typing information to that variable, because I wasn't sure whether it was final (i.e. read-only), or whether it would be okay for some other code to extend it.
~Many of the constants typed as sequences could have been typed as collections because that more closely reflects how they are used. However, there are no distinct types for immutable and mutable collections and I figured the immutable nature was more important than the …
=> cmake: build type propagation release notes

mesonbuild/compilers/rust.py
=> rust: Fix warning_level=everything case

.github/workflows/macos.yml, mesonbuild/dependencies/boost.py, test cases/common/103 has header symbol/meson.build
The install location seems to have moved, which breaks our job to unbreak things.
=> CI: fix macos unbreaking python

mesonbuild/compilers/mixins/clike.py
The user almost certainly has to be using a compiler wrapper script that doesn't actually work if we land here.
Fixes: #12982
=> Catch Python exception in the event alignment can't be converted to int

test cases/d/10 d cpp/meson.build
Which just checked for clang++ and aborted, instead of for the combination it claimed.
=> tests/d/10: Fix condition with clang++ and gdc

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/cs.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/swift.py
C#, Java, and Swift targets were manually collecting compiler arguments rather than using the helper function for this purpose.  This caused each target type to add arguments in a different order, and to forget to add some arguments respectively:
| Language | Arguments |
| -- | -- |
| C# | `/nologo`, `-warnaserror` |
| Java | warning level (`-nowarn`, `-Xlint:all`, `-Xdoclint:all`), debug arguments (`-g`, `-g:none`), `-Werror` |
| Swift | `-warnings-as-errors` |
Fix this.  Also fix up some no-longer-unused argument processing in the `Compiler` implementations and correct werror options for the Intel Fortran compiler.
Fixes https://github.com/mesonbuild/meson/issues/13059.
=> backend/ninja: use `generate_basic_compiler_args()` for C#, Java, Swift

mesonbuild/mdist.py, unittests/allplatformstests.py
Running `touch` on a tracked file in Git, to update its timestamp, and then running `meson dist` would cause dist to fail:
ERROR: Repository has uncommitted changes that will not be included in the dist tarball
Use --allow-dirty to ignore the warning and proceed anyway
Unlike `git status` and `git diff`, `git diff-index` doesn't refresh the index before comparing, so stat changes are assumed to imply content changes.  Run `git update-index -q --refresh` first to refresh the index.
Fixes: #12985
=> mdist: gracefully handle stale Git index

mesonbuild/dependencies/base.py
Some meson log as following is confusible :
```Dependency glib-2.0 found: NO found 2.76.4 but need: '>=2.79.0'```
This PR modifies some meson log with adding a punctuation and makes prompt information more understandable.
Could U please help to review it?
=> add punctuation mark to make log more understandable

mesonbuild/ast/interpreter.py, mesonbuild/coredata.py, mesonbuild/interpreter/interpreter.py, mesonbuild/interpreterbase/interpreterbase.py, mesonbuild/optinterpreter.py
Previously, if a junked meson.build or native.ini was used we got a lengthy traceback ending in UnicodeDecodeError.
Fixes: #13154
Fixes: #13156
=> catch build files that cannot be opened in utf8 mode and emit useful error

mesonbuild/compilers/vala.py, test cases/vala/30 dependencies for compiler.links/meson.build
Using the keyword argument dependencies with compiler.links() for vala doesn't work as the library being linked to needs to be prefixed with --pkg= before being passed to valac.
=> Fix dependencies for vala.links

mesonbuild/backend/vs2010backend.py
Closes #13041
#12472 disabled the `EmbedManifest` node in `.vcxproj`.
But it conflicts with the `/MANIFEST:NO` option, or the `GenerateManifest` node should be disabled.
This PR make meson set false to `GenerateManifest` when `target.link_args` disables the manifest creation with `/MANIFEST:NO`.
=> Fix an error when using /MANIFEST:NO with VS backend

docs/markdown/snippets/requires_kwarg_on_more_compiler_methods.md, docs/yaml/objects/compiler.yaml, mesonbuild/interpreter/compiler.py, test cases/common/275 required keyword in compiles functions/invalid.c, test cases/common/275 required keyword in compiles functions/meson.build, test cases/common/275 required keyword in compiles functions/meson_options.txt, test cases/common/275 required keyword in compiles functions/valid.c
This is a similar commit to the one that added required to all the compiler.has* functions.
=> Add required kwarg to compiler.{compiles,links,run}

mesonbuild/build.py, test cases/common/276 generator custom_tgt subdir/include/meson.build, test cases/common/276 generator custom_tgt subdir/meson.build
We need the subdir of where the output file will actually be created, not the current subdir of the interpreter.
Fixes: #13168
=> Use correct subdir when generating processed file path

docs/markdown/Reference-tables.md, docs/markdown/snippets/null_terminated_string_arg.md, mesonbuild/compilers/c_function_attributes.py, test cases/common/197 function attributes/meson.build
=> Add support for GCC's null_terminated_string_arg function attribute

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/cuda.py, mesonbuild/dependencies/cuda.py, test cases/cuda/12 cuda dependency (mixed)/meson.build, test cases/cuda/17 separate compilation linking/b.cu, test cases/cuda/17 separate compilation linking/b.h, test cases/cuda/17 separate compilation linking/main.cu, test cases/cuda/17 separate compilation linking/meson.build
This PR fixes two issues:
1. When using `cuda_dep = dependency('cuda')` with another language (such as C or C++), the dependency lacked the correct `-L<CUDA_ROOT>/lib` flag, which lead to broken links:
/usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lcudart_static: No such file or directory
/usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lcublas: No such file or directory
2. Currently, Meson cannot produce valid CUDA binaries when multiple `.cu` files rely on separate compilation/device linking. Device linking implies that the final SASS/machine code is generated at link time, since no one `.cu` file contains all code necessary to build the final kernel code. The fix is somewhat painful, because we cannot …
=> Cuda linking

docs/markdown/Builtin-options.md
Addresses side issue (not primary issue) raised in #8636.
=> In Builtin-options documentation, clarify warning_level=0 is not 'none' but 'compiler default'.

docs/markdown/snippets/pln_bsn_support.md, docs/yaml/functions/configure_file.yaml, docs/yaml/functions/custom_target.yaml, mesonbuild/interpreter/interpreter.py, mesonbuild/utils/universal.py, unittests/internaltests.py
`@PLAINNAME@` and `@BASENAME@` cannot be used on targets with multiple inputs. For those, similar macros are needed with an index.
Fixes #13164
=> implement @PLAINNAME0@ and @BASENAME0@

docs/markdown/snippets/ti_armclang.md, mesonbuild/compilers/detect.py, mesonbuild/linkers/detect.py, mesonbuild/linkers/linkers.py
The linker identifies itself with a custom name on stderr when given the --version flag:
```
fatal error: invalid option:  --version
tiarmclang: error: tiarmlnk command failed with exit code 1 (use -v to see invocation)
```
And the error for invalid options is different:
```
fatal error: invalid option:  --allow-shlib-undefined
```
Note _two_ spaces between the colon and the bad flag.
Compiler successfully identified afterwards as:
```
C compiler for the host machine: C:/ti/ti-cgt-armllvm_2.1.2.LTS\bin/tiarmclang.exe (clang 2.1.2 "TI Arm Clang Compiler 2.1.2.LTS")
C linker for the host machine: C:/ti/ti-cgt-armllvm_2.1.2.LTS\bin/tiarmclang.exe ld.lld unknown version
```
~As noted in the changelog, `b_lundef=false` and `b_asneeded=false` are both needed due to being unsupported flags, not …
=> Basic support for TI Arm Clang toolchain

mesonbuild/compilers/c.py, test cases/wasm/1 basic/meson.build
Emscripten version numbers are unrelated to Clang version numbers, so it is necessary to change the version checks for `c_std=c17` & co. Without that, no project that defaults to C17 or newer will build with Emscripten.
See https://github.com/pyodide/pyodide/discussions/4762 for more context. Also note that this bug caused defaulting to C17 in scikit-learn to be reverted (scikit-learn#29015), and it may be a problem for SciPy 1.14.0 too since that release will upgrade from C99 to C17.
Cc @lesteve.
=> Fix handling of C standard support for Emscripten

mesonbuild/build.py, mesonbuild/coredata.py, mesonbuild/interpreter/dependencyfallbacks.py, mesonbuild/interpreter/interpreter.py, mesonbuild/modules/__init__.py
Because the return value of get_option can be WrapMode, _every_ single place where options are used need to handle WrapMode.
This MR changes it to be a basic string combo, which gets transformed into a WrapMode only at the point where it is actually used.
This simplifies things for the option rewrite branch.
=> Pass wrapmode value around a a string.

mesonbuild/compilers/d.py, mesonbuild/compilers/detect.py
Dear developers,
This PR aims to fix #7523, so that we can cross-compile using LDC compiler for a windows target.
There were some underlying issues :
- `Unable to determine dynamic linker`  --> happened because the target arch was not forwarded to `guess_win_linker` function.
- When trying to cross-compiling, the sanity check basically runned : `ldc2 -m64 sanity.d` so it created a linux executable, not a windows one.
=> Fix cross-compilation with LDC

mesonbuild/build.py, test cases/rust/18 proc-macro/lib.rs, test cases/rust/18 proc-macro/meson.build, test cases/rust/18 proc-macro/subdir/meson.build, test cases/rust/18 proc-macro/transitive-proc-macro.rs
This reverts commit aee941559c4b88a062e88186819a820c69c200ae.
The commit being reverted breaks compilation of a major Meson consumer (Mesa). As a result, various distros are either pinning to <1.4.0 (before the commit) or performing this same revert downstream.
Fixing a regression takes priority, so let's revert.
Fixes: https://github.com/mesonbuild/meson/issues/12973
=> Revert "rust: recursively pull proc-macro dependencies as well"

mesonbuild/interpreter/interpreter.py
`configure_file` kwarg `copy` runs at configure time, whereas `fs.copyfile` runs at build time. Both have use cases, so this undeprecates the `configure_file` version.
Fixes: #12792
=> remove deprecation warning for `configure_file` kwarg 'copy'

docs/markdown/Users.md
The master branch isn't in experimental state anymore.
=> docs: Update GIMP meson adoption

mesonbuild/backend/ninjabackend.py, mesonbuild/interpreter/interpreter.py, test cases/cuda/17 separate compilation linking/meson.build
This fixes the problem of thin archives when CUDA is optional and only added later through `add_languages('cuda')`
=> Optional cuda thin archives

mesonbuild/mintro.py
Small innocuous change but it's a very big improvement when debugging meson builddirs, especially when working with meson-python.
=> mintro: write humman-readable JSON

mesonbuild/backend/xcodebackend.py
This pull request enables Meson to detect the installed version of Xcode and generate project files for that version, rather than just assume it's Xcode 3.2. This will enable us to finely adjust how the project files are generated. As an example, Xcode 9 eliminated `PBXBuildStyle`, so we can skip generating that for Xcode 9 and newer.
This also addresses a mostly benign issue in Xcode 15, where project formats older than Xcode 12 do not appear as options.
=> Autogenerate Xcode projects by the detected version

mesonbuild/linkers/linkers.py, unittests/darwintests.py
The apple linker uses -export_dynamic instead of --export-dynamic [1]. This should be set when setting export_dynamic: true.
Resolves #13290
[1]: https://opensource.apple.com/source/ld64/ld64-609/doc/man/man1/ld.1.auto.html
=> Add -export_dynamic flag for AppleDynamicLinker

mesonbuild/wrap/wrap.py
From python 3.11 [1]:
> The entry in the netrc file no longer needs to contain all tokens.  The missing
> tokens' value default to an empty string.  All the tokens and their values now
> can contain arbitrary characters, like whitespace and non-ASCII characters.
> If the login name is anonymous, it won't trigger the security check.
[1] https://github.com/python/cpython/commit/15409c720be0503131713e3d3abc1acd0da07378
=> wrap: default values for netrc are empty string from python 3.11

mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/cython.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/rust.py
This change:
- Makes the code cleaner with less repetition
- Is preparatory work for the option refactor branch (we need to change the defintion of OptionKey and now we can do that change in a single place)
=> Build language keys in a helper function

docs/markdown/Builtin-options.md, docs/markdown/Python-module.md
New people that want to use Meson for building Python extensions most probably will read Python module docs first. Direct them to meson-python and suggest to set `python.install_env=auto`.
=> Add note about meson-python and installation path

man/meson.1
The man page has fallen behind the other documentation and so lacks documentation for some of the most useful meson commands. This set of commits adds help for the rest of the commands. The added documentation was manually created from the output of the meson help command in much the same way as the markdown documentation is programmatically created.
=> Update the meson man page.

mesonbuild/dependencies/python.py, mesonbuild/modules/python.py, test cases/python/9 extmodule limited api/limited.c, test cases/python/9 extmodule limited api/meson.build, test cases/python/9 extmodule limited api/test_limited.py, unittests/pythontests.py
Link to the correct Python limited API DLL under mingw
This aims to fix #13167
=> Python: Fix limited API under mingw

mesonbuild/compilers/fortran.py
Closes #13319. I'm not sure if there's a way to test this on CI, couldn't find anything for trying various `FFLAGS` with `sanity_check`, but it does work, e.g.
```meson
project('test', 'fortran')
executable('blah', 'sanitizer.f')
```
```fortran
PROGRAM MAIN
PRINT *, "Fortran compilation is working."
END
```
```sh
FFLAGS='-ffixed-form' meson setup bbdir 
meson compile -C bbdir
./bbdir/blah
```
As reported in #13319, without this change, the `setup` line will fail with `meson.build:1:0: ERROR: Compiler gfortran cannot compile programs.`
=> BUG: Use an F77 snippet for sanity testing Fortran

mesonbuild/cargo/interpreter.py, mesonbuild/cargo/manifest.py
In ansi_term-0.12.1 the packages do not have a checksum entry but it can be found in the global metadata table.
=> cargo: Fall back to the checksum in Cargo.lock metadata table

data/shell-completions/bash/meson, data/shell-completions/zsh/_meson, docs/markdown/Unit-tests.md, docs/markdown/snippets/test_max_lines.md, mesonbuild/mtest.py
Let's allow users to configure how many lines are shown at most when a test fails.
=> Add meson test --max-lines

mesonbuild/scripts/symbolextractor.py
This fixes the unit test `TestAllPlatformTests.test_noop_changes_cause_no_rebuilds`, when run with an `nm` binary from `cctools-port` (as shipped by conda-forge, see https://github.com/conda-forge/cctools-and-ld64-feedstock).
It also addresses the issue discussed in https://github.com/mesonbuild/meson/discussions/11131, and this build warning:
```
[48/1383] Generating symbol file scipy/special/libsf_error_state.dylib.p/libsf_error_state.dylib.symbols
WARNING: ['arm64-apple-darwin20.0.0-nm'] does not work. Relinking will always happen on source changes.
error: arm64-apple-darwin20.0.0-nm: invalid argument --
```
as reported in [scipy#20740](https://github.com/scipy/scipy/issues/20740).
The unit test traceback was:
```
>       self.assertBuildRelinkedOnlyTarget('mylib')
E …
```
=> Improve `nm` usage in symbolextractor script on macOS

mesonbuild/mformat.py, test cases/format/1 default/gh13242.meson, test cases/format/1 default/meson.build
There was a case where a trailing comma was missing a whitespaces attribute
Fixes https://github.com/mesonbuild/meson/issues/13242
=> Fix meson format crash

mesonbuild/utils/universal.py, test cases/common/14 configure file/config6.h.in, test cases/common/14 configure file/meson.build, test cases/common/14 configure file/prog6.c
Update meson logic to only consider matched pairs of `\@` when escaping variables in 'meson' and 'cmake@'
style `configure_file` invocations.
The previous approach, escaping a single `\@`,
had undesirable side effects, including mangling valid perl that is being configured.
Closes: https://github.com/mesonbuild/meson/issues/7165
=> `configure_file`: update \@ escape logic

mesonbuild/backend/backends.py
In large monolithic codebases with many intertwined shared libraries, test serialization in meson master can cause configuration times to balloon massively from a single `test()` invocation. Using py-spy to find where meson is spinning its wheels shows that most of the time is being spent running `os.path.join`. After investigating, I found that this function was being run on many duplicate paths.
This PR mitigates the aforementioned issue by first deduplicating all transient dependent shared libraries in create_test_serialisation, *then* constructing the paths for the test's ld_library_path. In the tested codebase and using meson 1.4.1, this change dropped the total time to run `meson setup` from 215 seconds to 28 seconds - a nearly 8x improvement.
=> create_test_serialisation: Significantly improve performance with many transitive deps

mesonbuild/dependencies/boost.py
`boost_root` doesn't work if lib and include are in different directories like in the `nix` `boost` package.
The `prefix` checking could probably be removed, in 2019 conan (the
reason why the check was added) had `libdir` and `includedir` in its
generated pkg-config file
https://github.com/mesonbuild/meson/issues/5438#issuecomment-498761454
If there's no return then boost isn't found for some reason, further logic is unnecessary in any case if direct paths are passed.
`roots += [Path(boost_lib_dir), Path(boost_inc_dir)]` did not work
=> dependencies/boost.py: Allow getting `lib_dir` and `include_dir` via pkg-config

test cases/osx/9 framework recasting/meson.build
Preface: why are we doing this?
For reasons of cross-platform interop, the Lix team is strongly considering switching to build on a case sensitive filesystem in the macOS installation, since otherwise storing case overlapping filenames is busted and requires very very bad hacks:
https://git.lix.systems/lix-project/lix/issues/332
What's wrong:
```
Command line: `clang++ '/nix/temp/meson/b d01bff197e/meson-private/tmpjqid64j1/testfile.cpp' -o '/nix/temp/meson/b d01bff197e/meson-private/tmpjqid64j1/output.exe' -O0 -fpermissive -Werror=implicit-function-declaration -F/nix/store/qa92ravmclyraw7b46cz3q3m834mmbw9-apple-framework-OpenAL/Library/Frameworks -framework openal` -> 1 stderr:
ld: framework not found openal
clang-16: error: linker command failed with exit code 1 (use -v to see …
```
=> tests: fix OpenAL test case on case sensitive fs on macOS

mesonbuild/scripts/coverage.py
--html-details option is used to create a separate web page for each file. Each of these web pages includes the contents of file with annotations that summarize code coverage.
--html-nested option is used to create a separate web page for each file **and directory**. Each of these web pages includes the contents of file with annotations that summarize code coverage.
(https://github.com/gcovr/gcovr/blob/main/doc/source/output/html.rst)
=> coverage: Change --html-details to --html-nested (gcovr)

mesonbuild/interpreter/interpreter.py
=> Fix subproject typo in interpreter.py

mesonbuild/scripts/clangtidy.py
This adds the `-quiet` option when invoking clang-tidy for the generated `clang-tidy` target. (Note that the `clang-tidy-fix` target already does so.)
This prevents messages like
```
Suppressed 1084 warnings (1084 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
```
from being repeated for every file, which drowns out the actual warnings/errors from clang-tidy when more than a few files are processed.
Also the tip about `-header-fileter` and `-system-headers` is not very useful here because Meson doesn't currently provide a way to supply these options to clang-tidy.
Even with `-quiet`, clang-tidy still prints a line like `1084 warnings generated.` for each file.
---
Before:
```
$ …
```
=> clang-tidy: use -quiet

mesonbuild/compilers/compilers.py
The cppm extension is used to signify a c++ source files meant to be treated as c++ modules. Both msvc and clang support this extension. gcc seems to have no support of any dedicated extension for c++ modules.
Currently, without this patch, meson fails saying no compiler can handle cppm files.
=> cppm extension support

mesonbuild/dependencies/python.py, mesonbuild/scripts/python_info.py
This does a couple of things:
1. Scrape the `Py_GIL_DISABLED` sysconfig var, which is the best way as of today to determine whether the target interpreter was built with `--disable-gil`.
2. Link against the correct `libpython`.
3. On Windows, work around a known issue in the python.org installer with a missing define in `pyconfig.h`, which the CPython devs have said is unlikely to be fixed since headers are shared between the regular and free-threaded builds in a single NSIS installer (see https://discuss.python.org/t/windows-installer-freethreading-and-building-extension-modules/54391/2).
I have tested this with NumPy; the `libpython` change makes numpy build, and the added define fixes the ABI issue that otherwise makes `import numpy` segfault immediately due to the `pyconfig.h` …
=> Add support for detecting free-threaded Python on Windows

docs/markdown/snippets/find_program_version_argument.md, docs/yaml/functions/find_program.yaml, mesonbuild/dependencies/python.py, mesonbuild/interpreter/interpreter.py, mesonbuild/programs.py, test cases/common/26 find program/meson.build, test cases/common/26 find program/print-version-custom-argument.py
When trying to get the version of a program, meson was previously hardcoded to run the binary with `--version`. This does work with the vast majority of programs, but there are a few outliers (e.g. ffmpeg) which have an unusual argument for printing out the version. Support these programs by introducing a version_argument kwarg in find_program which allows users to override `--version` with whatever the custom argument for printing the version may be for the program.
=> find_program: add a kwarg to specify custom version argument

mesonbuild/cmake/tracetargets.py, test cases/osx/9 framework recasting/meson.build
Amends #12181:
- Make the test actually use the cmake dependency method.
- Make the recasting handle frameworks which appear in IMPORTED_LOCATION properties.
This PR does not:
- Fix processing of the result. `resolve_cmake_trace_targets` is called from three locations. One of them sorts and removes duplicates, potentially breaking non-trivial cases (https://github.com/mesonbuild/meson/pull/13287#issuecomment-2149476953).
- Deduplicate framework processing. Another processing loop is in interpreter.py.
- Deal with `-framework Xyz` in `INTERFACE_LINK_LIBRARIES`.
- Create proper `ExtraFrameworkDependency` objects.
=> Recast CMake's IMPORTED_LOCATION into framework flags

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, test cases/common/277 custom target private dir/meson.build
Some custom target commands will expect the `@PRIVATE_DIR@` to already exist, such as with `make -C @PRIVATE_DIR@ ...`
=> Ensure private directory exists for custom targets

mesonbuild/mesonmain.py
Suggested by @lazka in order to be clearer when delineating between mingw-w64-x86_64-python and mingw-w64-ucrt-x86_64-python.
Fixes: #12772
=> Suggest mingw Python URL instead of specific package names

mesonbuild/compilers/cpp.py
There are two issues:
1. has_header() wants just the header name without surrounding <> or similar; it fails otherwise.
2. has_header() returns a tuple of two bools, where the first element determines whether or not the header has been found. So use that element specifically, otherwise the tuple will always evaluate to true because it is not empty.
=> compilers: cpp: fix header name and return value use in header check

mesonbuild/minstall.py, mesonbuild/msetup.py
minstall: fix symlink handling on python 3.13
We passed a wrapper hack for shutil.chown because some functionality wasn't available in the stdlib. It was added in python 3.13 beta1, so the tests fail when we actually test symlink handling.
Fixes failure to run test_install_subdir_symlinks_with_default_umask_and_mode on python 3.13.
...
There's still another failing test that I haven't debugged yet but I am running out of time this Friday.
=> fix support for python 3.13

mesonbuild/compilers/detect.py, mesonbuild/compilers/mixins/clang.py, mesonbuild/compilers/mixins/gnu.py
_get_gnu_compiler_defines and _get_clang_compiler_defines were broken by not defining the language they used.
Neither GCC nor Clang infer the language based on the driver name which means `self.defines` isn't populated correctly in compilers/cpp.py.
e.g.
```
$ echo "" | g++ -E -dM - | grep -i cplus
$ echo "" | g++ -x c++ -E -dM - | grep -i cplus
#define __cplusplus 201703L
```
Fix that by passing '-x LANGUAGE' as a first pass. If it fails, try again without '-x LANGUAGE' as before, as its portability isn't certain.
While here, make the debug & error message strings consistent between the GCC and Clang probes.
Without this change, a63739d394dd77314270f5a46f79171a8c544e77 is only partially effective. It works if the system has injected Clang options via /etc/clang configuration files, but …
=> compilers: detect: fix pre-processor scraping by defining language

mesonbuild/mformat.py, mesonbuild/mparser.py, test cases/format/1 default/gh13242.meson, test cases/format/1 default/meson.build
format was adding a new empty line each time when trying to split a long line containing a function with no arguments
=> format: fix edge case with empty functions

.github/workflows/macos.yml, mesonbuild/_typing.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/mixins/apple.py, mesonbuild/compilers/mixins/clang.py, mesonbuild/compilers/mixins/elbrus.py, mesonbuild/compilers/mixins/gnu.py, mesonbuild/compilers/mixins/intel.py, mesonbuild/compilers/mixins/pgi.py, mesonbuild/compilers/mixins/visualstudio.py, mesonbuild/dependencies/misc.py, mesonbuild/linkers/linkers.py, test cases/common/184 openmp/meson.build
Supersedes and closes #13079. I followed @tristan957's advice in https://github.com/mesonbuild/meson/pull/13079#issuecomment-2186833677.
=> Detect OpenMP on macOS with Apple's Clang (rebased on `master`)

mesonbuild/scripts/depfixer.py
Fixes regression in commit 78e9009ff9d36925e04f329f9082841002ddd848.
new_rpath is only set when install_rpath appears in meson.build.
Before this commit, we treated new_rpath as a single string to pass to -add_rpath. This worked as long as new_rpath had a single rpath in it, though for ELF we explicitly supported multiple rpaths separated with ":" (as binutils ld is quite happy with that too).
install_name_tool does not support paths with colons in it:
```
21:12 <awilfox> Load command 19          cmd LC_RPATH      cmdsize 40         path /bar:/baz:/eli:/ldap (offset 12)
21:12 <awilfox> Load command 20          cmd LC_RPATH      cmdsize 24         path /foo (offset 12)
21:14 <awilfox> so the result is: do not use colons
```
After commit 78e9009ff9d36925e04f329f9082841002ddd848, we simply …
=> depfixer: fix darwin regression when install rpaths are used

mesonbuild/dependencies/python.py, test cases/frameworks/24 libgcrypt/test.json
When building a limited API module on Windows with GCC the library to link with should be python3.dll, not python3X.dll.
=> Python: fix limited API logic under GCC on Windows

mesonbuild/linkers/detect.py
Don't require the string to be enclosed in parentheses. https://github.com/llvm/llvm-project/pull/97323 changed the LLD version printout to no longer be enclosed in parentheses, which made Meson fail to detect the linker style used here.
The LLD change is being reverted in
https://github.com/llvm/llvm-project/pull/97698 in order to fix building with existing Meson versions, but for the future, loosen the check slightly, to not require the parentheses.
=> linkers: Loosen the check for GNU interface style in LLD for Windows

docs/markdown/Configuration.md, docs/yaml/objects/cfg_data.yaml, docs/yaml/objects/env.yaml, mesonbuild/interpreter/interpreterobjects.py, mesonbuild/interpreterbase/_unholder.py, mesonbuild/interpreterbase/baseobjects.py, test cases/common/113 interpreter copy mutable var on assignment/check_env.py, test cases/common/113 interpreter copy mutable var on assignment/meson.build, test cases/common/14 configure file/meson.build, test cases/failing/70 configuration immutable/meson.build, test cases/failing/70 configuration immutable/test.json
This reverts commit 9f02d0a3e5a5ffc82256391c244b1af38e41ef78.
It turns out that this does introduce a behavioral change in existing users of ConfigurationData, which it wasn't supposed to (it was supposed to preserve behavior there, and add a new *warning* for EnvironmentVariables).
This breaks projects such as pulseaudio, libvirt, and probably more. Roll back the change and try again after 1.5.0 is released.
Fixes: #13372
Given this is still not fixed in rc2 and rc3 is imminent, I think we really need to hold off on making this change.
I tried to find time two weeks ago to debug this but didn't, and it's going into the weekend and I won't have any time then either. The original design seems flawed to me but I am not sure how to do it better.
I have spent more time than I really wanted to …
=> Revert "Clarify mutable objects usage"

mesonbuild/dependencies/base.py, mesonbuild/interpreter/mesonmain.py, test cases/common/98 subproject subdir/meson.build
Revert "interpreter: when overriding a dependency make its name match"
This reverts commit b1340e9bb1f243e4de8f2d89415a45ade476a3dc.
Revert "dependency: define equality and hash operators for Dependency"
This reverts commit 6d713e40f81512eadb0cc4654408d90cb22ba774.
This caused some projects to fail to build, such as libplacebo and libepoxy. Taking libplacebo as the example, the produced build.ninja does not include libvulkan.so as a linker input for src/libplacebo.so.338.
We are probably getting dependency hashing wrong somewhere. Unsure where exactly and unsure how to create a test case. We are also deep into rc2. Revert it for now and try to re-land these changes for 1.6.
Bug: https://bugs.gentoo.org/935443
Fixes: #13352
=> Revert PR12972 as a regression.

mesonbuild/compilers/asm.py
Hi all,
This PR fixes building Nasm objects with Meson's native language support, when depending against a library that exports that flag, like Glib.
```
Called: `E:/cerbero-sources/build-tools/bin\pkg-config.EXE --cflags harfbuzz` -> 0
stdout:
-mms-bitfields -IE:/cerbero-sources/dist/mingw_x86_64/include/harfbuzz -IE:/cerbero-sources/dist/mingw_x86_64/include/freetype2 -IE:/cerbero-sources/dist/mingw_x86_64/include/libpng16 -IE:/cerbero-sources/dist/mingw_x86_64/include/glib-2.0 -IE:/cerbero-sources/dist/mingw_x86_64/lib/glib-2.0/include
```
```
FAILED: libass/libass-9.dll.p/x86_blend_bitmaps.asm.obj 
"nasm" "-Ilibass\libass-9.dll.p" "-f" "win64" "-DWIN64" "-D__x86_64__" "-Ox" "-Dprivate_prefix=ass" "-DPIC=1" "-DARCH_X86_64=1" "-IE:/cerbero-sources/dist/mingw_x86_64/include/freetype2" …
```
=> nasm: Add -mms-bitfields to the list of ignored flags

mesonbuild/dependencies/cmake.py
09b53c534f seems to have done an over-eager search-replace.
=> cmake dependency: Fix accidental use of T.Optional in warning message

mesonbuild/dependencies/framework.py, test cases/osx/11 case sensitive apfs/meson.build, test cases/osx/11 case sensitive apfs/prog.c, test cases/osx/11 case sensitive apfs/test.json
This PR fixes a test failure on case-sensitive filesystems when a CMake dependency is turned into an Apple framework. I ran into this issue while working on the Darwin stdenv in nixpkgs after Meson was updated to 1.4.0 because my Nix store is installed on a case-sensitive APFS volume.
The extraframeworks search logic was already case insensitive. The fix was to use the match’s actual name instead of the one that was requested. I included a test, though the original test for https://github.com/mesonbuild/meson/pull/12181 also serves as a test for case-sensitive filesystems.
I found https://github.com/mesonbuild/meson/issues/12480 in the issue tracker, but the scope of fixing that seems like a much larger fix and wouldn’t address the issue I encountered building the Darwin stdenv in …
=> dependencies: find extraframeworks on case-sensitive filesystems

mesonbuild/environment.py, mesonbuild/scripts/coverage.py, mesonbuild/utils/universal.py, unittests/internaltests.py
The documentation for subprocess.run at https://docs.python.org/3/library/subprocess.html#popen-constructor has a warning, pointing to using shutil.which() instead of subprocess.run for detecting if exe files exists on the path.
I have experienced problems with detecting llvm-cov, when running as non-root in a container. In this situation subprocess.run would throw a Permission denied exception if llvm-cov is not on the path.
=> More robust exe_exist function

mesonbuild/backend/xcodebackend.py
XCode project file contains dictionary-like structures. Strings for the mapped values have to be quoted if these include special characters. Previously this quoting was happening in-place, before adding a new value to the dictionary. This produce big amounts of boilerplate error-prone code. For example if there are targets whose names contain special characters (grpc++ in my case), produced file will be invalid.
This moves checking and quoting subroutine to the PbxDictItem class, eliminating the need to do this on the caller side.
[Kin](https://github.com/Serchinastico/Kin) tool was used to validate produced PBXProj files.
=> Refactor duplicated quoting code for XCode backend

mesonbuild/environment.py, run_tests.py
Fix Several type check warnings reported by Pyre@Google, which were outdated after code modifications.
1. update the return type of function `detect_ninja` from `T.List[str]` to `T.Optional[T.List[str]]`, since it could be None after commit https://github.com/mesonbuild/meson/commit/48e6db89ab702c0f7c0fb8b9cbcac857dce9c6ef
2. update the return type of function `run_mtest_inprocess` from `T.Tuple[int, str, str]` to `T.Tuple[int, str]`, since the return value only include two str after commit https://github.com/mesonbuild/meson/commit/faf79f4539841cbf89fe8d53cf35aa91fd8273c9
=> Fix Type hints

docs/yaml/functions/subdir_done.yaml
I noticed that the description of this function uses “build” where it should use “built” in a couple of places.
Fix this, and add a couple of commas that I think make the description read better
=> docs: Fix typo in subdir_done() description

mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/cython.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/rust.py
The public facing name of language options is compiler option, so let's standardise on that.
=> Rename langopt method

docs/markdown/Cython.md, docs/markdown/Python-module.md
Currently `cython_args` only appears [in this table](https://mesonbuild.com/Reference-tables.html#language-arguments-parameter-names). This makes it a little more discoverable along with the other docs. It also adds a cross-reference from the `py.extension_module` docs to the cython reference.
=> docs: mention cython_args in cython reference docs

mesonbuild/backend/backends.py
Test dependencies can be of type CustomTargetIndex, similar to other targets.
=> backend/backends: Fix type assertions in backend

.github/workflows/os_comp.yml
by forcing an older nodejs
the node v20 build no longer works in bionic. While actions/checkout@v3 uses node v16 GHA forced it to use v20 some time ago after a deprecation cycle. This env var makes it use v16 again, despite that being EOL.
=> tests: try to fix ubuntu bionic tests

test cases/rust/12 bindgen/meson.build
-m arguments aren't portable across architectures. -fipa-pta will hopefully be portable for gcc, but also not implemented by clang.
Fixes: #13417
=> test/rust: Replace gcc -m argument with a -f argument

test cases/linuxlike/1 pkg-config/prog-checkver.c, test cases/linuxlike/13 cmake dependency/prog-checkver.c
Fedora, at the very least, now packages zlib-ng as zlib. This means the
version reported for the dependency is now X.Y.Z.zlib-ng by pkgconfig
whereas the test expected X.Y.Z. Make the version check work for both
regular zlib and zlib-ng.
=> Fix failing tests for zlib-ng

docs/markdown/snippets/cmake_only_public_link_flags_in_dep.md, mesonbuild/cmake/interpreter.py, mesonbuild/cmake/tracetargets.py, test cases/cmake/2 advanced/main3.cpp, test cases/cmake/2 advanced/meson.build, test cases/cmake/2 advanced/slib.cpp, test cases/cmake/2 advanced/subprojects/cmMod/CMakeLists.txt, test cases/cmake/2 advanced/subprojects/cmMod/vers.map
CMake has two target properties for linker flags: [`LINK_OPTIONS`](https://cmake.org/cmake/help/latest/prop_tgt/LINK_OPTIONS.html) for those applied to the target itself (`PRIVATE`) and [`INTERFACE_LINK_OPTIONS`](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_LINK_OPTIONS.html) for those propagated when the target is linked into other targets (`PUBLIC`/`INTERFACE`). In a CMake subproject, Meson currently concatenates both properties into one and applies the same flags to the both the `*_library()` and `declare_dependency()` generated calls. This causes downstream build failures whenever one of the `PRIVATE` link flags is extremely specific to the target library, e.g. `-Wl,--version-script`.
This PR adds a separate data field for `INTERFACE_LINK_OPTIONS` pulled from the CMake …
=> cmake: Only propagate PUBLIC linker flags in dependencies

mesonbuild/environment.py
This reverts commit cc201a539674babf46f726859587afb5ed6a6867 (PR #7367).
It's true that some aarch64 CPUs can run 32-bit ARM code, but some (especially high-end ones, those most likely to be running builds) cannot.  It's better to assume that they can't, so builds don't unnecessarily fail due to attempting to run a sanity check executable.
=> Revert "Support armel/armhf builds on native arm64 hosts."

mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/build.py, mesonbuild/cmake/interpreter.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/mixins/elbrus.py, mesonbuild/compilers/mixins/emscripten.py, mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, mesonbuild/coredata.py, mesonbuild/environment.py, mesonbuild/mconf.py, mesonbuild/modules/__init__.py, mesonbuild/modules/pkgconfig.py, mesonbuild/modules/python.py, mesonbuild/modules/rust.py, mesonbuild/options.py, run_tests.py, unittests/allplatformstests.py, unittests/datatests.py, unittests/internaltests.py, unittests/linuxliketests.py
The goal is that `OptionKey` becomes a simple object that only holds option name, subproject and whether it is for build or not. All the "business logic" goes inside `OptionStore` as opposed to being splattered about.
This needs to be done piece by piece. This MR (currently) removes the "option type" only. It will be followed by more standalone commits that remove features one by one. They might go to this one as subsequent commits or they might be standalone, have not decided yet.
=> Move all logic from OptionKey to OptionStore

mesonbuild/build.py, test cases/rust/18 proc-macro/lib.rs, test cases/rust/18 proc-macro/meson.build, test cases/rust/18 proc-macro/subdir/meson.build, test cases/rust/18 proc-macro/transitive-proc-macro.rs, test cases/rust/21 transitive dependencies/meson.build
aee941559 ("rust: recursively pull proc-macro dependencies as well") had to be reverted (in a66cb97e8) because it broke Mesa cross compilation.  This happened because a C shared library was linked with a Rust C-ABI static library, which caused it to inherit the proc macro dependency the Rust static library was linked with.
The right way to handle this is for only Rust targets to inherit proc macro dependencies from static libraries they link with.  A Rust executable, library, or whatever will need the proc macros its Rust dependencies use, as illustrated in the test case that I've reintroduced here.
I've verified that Mesa still cross compiles correctly with this change.  The same failure was also identified by the "rust/21 transitive dependencies" test case, but only when cross …
=> rust: recursively pull proc-macro deps for rust targets

docs/markdown/Include-directories.md
Background for this PR: https://www.enricozini.org/blog/2024/debian/meson-includedir-and-current-directory/
It would have helped me to see `implicit_include_directories` linked from `include_directories`' documentation, so here's my attempt for it
=> Link include_directories to implicit_include_directories

mesonbuild/compilers/mixins/clike.py, test cases/common/104 has arg/meson.build
For other reasons, Meson transforms "-Wno-x" into "-Wx -Wno-x" for GCC, but this breaks with "-Wno-attributes=x" with:
```
cc1plus: error: arguments ignored for '-Wattributes='; use '-Wno-attributes=' instead
```
Suppress that workaround for -Wno-attributes=.
Closes: https://github.com/mesonbuild/meson/issues/13022
=> compilers: handle -Wno-attributes= for GCC

mesonbuild/modules/gnome.py
CustomTargets must have `install_dir` if installing. Since they do not implement a default install dir like BuildTargets do.
gnome.compile_resources() would result in an unhandled python exception when missing install_dir argument together with providing following arguments:
gresource_bundle: true
install: true
closes: https://github.com/mesonbuild/meson/issues/13447
=>  fix: modules/gnome: gnome.compile_resources() must have `install_dir` if installing

mesonbuild/utils/universal.py, unittests/internaltests.py
This function is no longer used since shutil.which() is used instead.
=> Remove the exe_exists function

mesonbuild/compilers/cpp.py
Fallout from the OptionStore refactor, and specifically commit 9a6fcd4d9a0c7bb248c5d0587632b741a3301e03. The `std` object was migrated from having an option itself, to having the value fetched and saved directly. In most cases, this also meant avoiding `.value`, but in a couple cases this refactor went overlooked, and crashed at runtime.
Only affects Elbrus and Intel C++ compilers, seemingly.
Fixes #13401
=> compilers: fix partial refactor of coredata options

mesonbuild/dependencies/data/CMakePathInfo.txt
The existing `*-linux-gnu*` works on the Debian multiarch model for Linux architectures; tweak it to be `*-gnu*` so it works also for Hurd architectures.
This makes the cmake-based search of dependencies work on Debian GNU/Hurd.
=> cmake: extend library pattern to work on GNU/Hurd as well

mesonbuild/mdist.py
In commit c9aa4aff66ebbbcd3eed3da8fbc3af0e0a8b90a2 we added a refresh call to git to catch cases where checking for uncommitted changes would misfire. Unfortunately, that refresh performs a write operation, which in turn misfires on readonly media. We don't actually care about the return value of the refresh, since its purpose is solely to make the next command more accurate -- so ignore it.
Fixes: c9aa4aff66ebbbcd3eed3da8fbc3af0e0a8b90a2
Fixes: #13461
=> mdist: don't fail on readonly source trees

mesonbuild/coredata.py
This fixes the issue. It might be argued that it is not the "proper" fix but the entire `OptionsView` class will get deleted once option refactoring lands.
=> Ensure override var exists. Closes #13402.

mesonbuild/scripts/depfixer.py
Duplicated -delete_rpath arguments will cause macOS's install_name_tool failed.
Maybe related: 78e9009ff9d36925e04f329f9082841002ddd848
Cc @grobian @eli-schwartz
=> depfixer: deduplicate rpaths on darwin

mesonbuild/backend/ninjabackend.py
There are two issues here being fixed.
- An off-by-one when calculating the line length
- Using a command line limit that is valid from an OS point of view, but causes problems for some programs.
=> Fix the Ninja backend heuristic for using an RSP file

mesonbuild/environment.py
Some distros (gentoo) install clang-VERSION but not e.g. llvm-cov-VERSION.
This PR makes detection work for this edge case.
=> coverage: improve llvm-cov detection

mesonbuild/mtest.py
On **Windows**, the output read from the stream has '\r\n', which in .txt, .json and console logger (when captured to a file) translates to '\n\n'. This results in every log line being separated by an empty line.
Playground project to see the issue: https://github.com/the-risk-taker/meson-playground
Before, the testlog looked like:
```text
==================================== 1/1 =====================================
test:         example_cpp
start time:   18:41:18
duration:     0.01s
result:       exit status 0
command:      ...
----------------------------------- stdout -----------------------------------
Log line: #0
Log line: #1
Log line: #2
Log line: #3
Log line: #4
Log line: #5
Log line: #6
Log line: #7
Log line: #8
Log line: #9
```
With this patch it looks like:
```text …
```
=> mtest: remove superfluous '\r' from read_decode()

docs/markdown/Contributing.md, docs/markdown/Reference-tables.md, docs/markdown/snippets/llvm_flang.md, mesonbuild/compilers/detect.py, mesonbuild/compilers/fortran.py, run_project_tests.py
=> add initial support for llvm-flang

.github/workflows/codeql-analysis.yml, .github/workflows/cygwin.yml, .github/workflows/file_format.yml, .github/workflows/images.yml, .github/workflows/lint.yml, .github/workflows/macos.yml, .github/workflows/msys2.yml, .github/workflows/nonnative.yml, .github/workflows/os_comp.yml, .github/workflows/stable_builddir.yml, .github/workflows/unusedargs_missingreturn.yml, .github/workflows/website.yml
Supposedly, breakage will happen in a few months.
=> Fix some CI summary deprecation warnings

mesonbuild/backend/ninjabackend.py, mesonbuild/build.py
Instead of storing the generated header cache in the Target, store it in the NinjaBackend, as it really is just data for the NinjaBackend to use.
=> backend/ninja: stop adding random attributes to BuildTargets

mesonbuild/mformat.py, unittests/platformagnostictests.py
Running meson format multiple times on an empty file was adding a new line each time, which is bad for pre-commit checks...
=> mformat: fix formatting of empty build file

mesonbuild/minstall.py
Updating the log message generated when installing a symbolic link. The new message format may be a bit more clear on the link being created.
=> minstall: update symlink install message presentation

.github/workflows/cygwin.yml, test cases/common/230 external project/test.json, unittests/allplatformstests.py
Fixes #13465 
`make` is used internally by gcc (for scheduling multithreaded lto) when the '-flto' flag is used.
=> Fix LTO-related testcases on Cygwin

docs/yaml/functions/dependency.yaml
Ref https://github.com/mesonbuild/meson/pull/9603
=> docs: document prefer_static effect on dependency()

docs/yaml/objects/feature.yaml
The example incorrectly uses `then` after the if condition, which is incorrect meson syntax as meson does not support a `then` keyword.
=> docs: fix example for feature.require

ci/ciimage/ubuntu-rolling/install.sh, test cases/frameworks/24 libgcrypt/test.json
https://github.com/mesonbuild/meson/pull/12293#issuecomment-1737706555
@eli-schwartz 
This could be reviewed and merged here or I could do a PR against the branch and fork used in #12293 ?
/cc @Akaricchi
=> Add Zig to ubuntu-rolling image, CI test

ci/run.ps1, mesonbuild/dependencies/dub.py, mesonbuild/modules/dlang.py, test cases/d/11 dub/meson.build, test cases/d/14 dub with deps/meson.build
This is https://github.com/mesonbuild/meson/pull/12143 with CI fixed for Windows.
---
- check version of DUB for compatibility with Meson
- use "cacheArtifactPath" to locate DUB libraries in the cache
- propose `dub build --deep` command to Meson users for missing DUB
packages
Depending on DUB version, it will look either in the old cache structure
or use this new `dub describe` entry.
Closes: #12143
Closes: #11773
=> dependencies/dub: Correctly handle dub >= 1.35 as well as older dub (+ fixed Windows CI)

mesonbuild/compilers/asm.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/mixins/gnu.py, mesonbuild/compilers/mixins/visualstudio.py, mesonbuild/linkers/detect.py, mesonbuild/linkers/linkers.py
Fixes: #8981
Fixes: 2be074b1d445fcd30535bcf7518f8ce0738bcbf3
=> linkers: Fix RSP syntax for linkers invoked with clang

mesonbuild/linkers/linkers.py, unittests/allplatformstests.py
When building with LLD as the linker, response files are never used.
It's because of an issue with the `LLVMDynamicLinker` class hierarchy:
```python
▸ python <<'EOF'
from mesonbuild.linkers.linkers import LLVMDynamicLinker
print(LLVMDynamicLinker(['lld'], '', '', []).get_accepts_rsp())
EOF
False
```
After correcting the base classes so GNU-like linkers all default to supporting response files:
```python
▸ python <<'EOF'
from mesonbuild.linkers.linkers import LLVMDynamicLinker
print(LLVMDynamicLinker(['lld'], '', '', []).get_accepts_rsp())
EOF
True
```
I added a test, but the CI would also need a build that actually use LLD as a linker.
=> linkers: fix LLD linker response file handling

mesonbuild/compilers/mixins/clike.py
Meson accidentally strips '-isystem' from C build args like ['-isystem', '/path/to/headers'] if the compiler includes the current working directory in the header search paths. The root cause is that '-isystem'[8:] evaluates to an empty string and os.path.realpath('') returns the absolute path to the current working directory, causing meson to think that '-isystem' specifies a default include path.
Different compiler versions varies whether the current working directory is in its search paths. For example, on Ubuntu 21.04:
```
gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1)
#include "..." search starts here:
#include <...> search starts here:
.
/usr/lib/gcc/x86_64-linux-gnu/10/include
/usr/local/include
/usr/include/x86_64-linux-gnu
/usr/include
End of search list.
```
While on Ubuntu 24.04: …
=> compilers: do not strip '-isystem' from C build arguments

ci/ciimage/opensuse/install.sh, ci/ciimage/ubuntu-rolling/install.sh, test cases/frameworks/17 mpi/meson.build, test cases/frameworks/17 mpi/test.json
Like in a5211a15207a2e6e30e213c5530a5d1bf5c2531c.
=> ci: try to install urld harder for opensuse, ubuntu

mesonbuild/mformat.py, test cases/format/3 editorconfig/meson.build, test cases/format/3 editorconfig/subdir/.editorconfig, test cases/format/3 editorconfig/subdir/sub.meson
Which happens when a .editorconfig is in a subdirectory, not the root. In this case we need Set the fallback value to `False`, which is what editorconfig expects.
Closes: #13568
=> mformat: correctly handle editorconfig files without the root setting

mesonbuild/mformat.py, mesonbuild/mparser.py, test cases/format/1 default/indentation.meson, unittests/platformagnostictests.py
Fixes #13508
- Fix indentation of comments in arrays
- Fix indentation of comments in dicts
- Fix indentation of comments in if clauses
- Fix indentation of comments in foreach clauses
=> format: fix indentation of comments

mesonbuild/linkers/linkers.py, unittests/darwintests.py
Resolves #13543.
@barracuda156 @ryandesign can anyone test this on MacOS 10.6.x and MacOS 10.7 to confirm? I only have a much more recent version available.
CC @tristan957
=> linkers: skip -export_dynamic flag before MacOS 10.7

mesonbuild/mformat.py, test cases/format/5 transform/default.expected.meson, test cases/format/5 transform/file_compare.py, test cases/format/5 transform/muon.expected.meson, test cases/format/5 transform/options.expected.meson, test cases/format/5 transform/source.meson
The following is valid meson:
```meson
a = '''This string can't be simplified'''
```
which cannot be simplified because of the `'` in it, as
```meson
a = 'This string can't be simplified'
```
Is invalid.
Potentially we could convert that with escapes, but it seems reasonable
to me to leave this, since it may be desirable to not have lots of
escapes in a string. `'''I can't believe it's her's!'''` is much more
readable than `'I can\'t believe it\'s her\'s!'`, for example.
Closes: #13564
=> mformat: A triple string with a ' in it cannot be simplified

mesonbuild/compilers/detect.py
`meson setup build` in swift project runs `swiftc -Xlinker -v some_tmp.swift` command to detect linker.
This leaves bunch of junk files like 'tmpc90jgpg7' in working directory. PR forwards output of command to /dev/null.
=> Discard swiftc linker detect output

mesonbuild/scripts/run_tool.py
It was possible (with some frequency) for the clang-tidy/format target to continue starting new subprocesses after a CTRL-C, because we were not canceling the already queued tasks and waiting for all of them.
This makes a best-effort attempt to cancel all further subprocesses. It is not 100%, because there is a race that is hard to avoid (without major restructuring, at least): new subprocesses may be started after KeyboardInterrupt (or any other exception) is raised but before we get to the cancellation.
When the race happens, the calling ninja may exit before Meson exits, causing some output (from clang-tidy/format and Meson's traceback) to be printed after returning to the shell prompt. But this is an improvement over potentially launching all the remaining tasks after having returned …
=> Better handle CTRL-C during clang-tidy/format

mesonbuild/cmake/interpreter.py
Namely, be strict about not including None in places we promised we wouldn't.
=> Handle Optionals in the cmake interpreter better

docs/markdown/snippets/test_args_accepts_external_program.md, docs/yaml/functions/benchmark.yaml, mesonbuild/backend/backends.py, mesonbuild/interpreter/interpreter.py, mesonbuild/interpreter/interpreterobjects.py, mesonbuild/interpreter/kwargs.py, mesonbuild/interpreter/type_checking.py, test cases/common/41 test args/meson.build, test cases/common/41 test args/wrap.py, test cases/failing/112 run_target in test/test.json
Although it's not especially common, there are certainly cases where it's useful to pass the path to an external program to a test program.
Fixes: https://github.com/mesonbuild/meson/issues/3552
=> Allow external programs in test()'s 'args' parameter

docs/markdown/Unit-tests.md, mesonbuild/mtest.py
Previously, setting `MESON_TESTTHREADS` to a number lower than 1 resulted in unexpected behavior. This commit introduces test for negative value (with fallback to 1), and fallback to core count in case it is set to 0.
It improves experience in job-matrix type of CI workflows, where some jobs within the matrix require single job execution, whereas others can default to taking core count as the job count.
=> mtest: Extend MESON_TESTTHREADS usage

docs/markdown/snippets/always_report_deprecations.md, mesonbuild/build.py, mesonbuild/environment.py, mesonbuild/interpreter/interpreter.py, mesonbuild/interpreter/interpreterobjects.py, mesonbuild/interpreterbase/decorators.py, mesonbuild/modules/pkgconfig.py, mesonbuild/mparser.py, mesonbuild/options.py, mesonbuild/utils/universal.py, unittests/allplatformstests.py
When projects do not specify a minimum meson version, we used to avoid giving them the benefit of the Feature checks framework. Instead:
- warn for features that were added after the most recent semver bump, since they aren't portable to the range of versions people might use these days
- warn for features that were deprecated before the upcoming semver bump, i.e. all deprecated features, since they aren't portable to upcoming semver-compatible versions people might be imminently upgrading to
=> Feature checks: fall back to reporting insufficiently portable features

docs/markdown/Reference-tables.md
There are two environments on Windows:
* When invoked in a Cygwin or MSYS2 MSYS shell, `host_machine.system()` returns `cygwin`.
* When invoked in a MSYS2 MINGW32/MINGW64/UCRT64/CLANG64/etc., `host_machine.system()` returns `windows`.
=> docs: Update descriptions of `host_machine.system()` about Windows

mesonbuild/modules/gnome.py
In cases, when localized media files are provided by some languages, we need to use `gnome.yelp ()` with `symlink_media: false` which copies all files from `C` locale in addition to the localized media. This wastes storage space. The alternative is to use `symlink_media: true` which symlinks entirely to `C` media files ignoring localized media files.
As a middle ground, if the localized media file exists in the source tree for a language, we use that file rather than symlinking to `C` media with the same filename even when `symlink_media: true`. This saves storage space.
If there are no localized media files in non-C language, the existing behaviour is maintained.
=> modules/gnome: Make 'gnome.yelp()' install actual media with symlinks

mesonbuild/mformat.py
I ran into this with `option = true;` (not the trailing `;`). Now we provide a nicer message instead of an uncaught Python traceback.
Closes: #13565
=> mformat: provide nice error message instead of traceback for invalid value

mesonbuild/mformat.py, test cases/format/4 config/indentation.meson
If `kwargs_force_multiline` is enabled, an `ArgumentNode` in a kwarg value can already be marked multiline by the time we notice that the line needs to be broken for length.  Ensure we still break the line in this case.
Fixes: #13512
=> mformat: regenerate long lines even if they're already multiline

test cases/linuxlike/14 static dynamic linkage/verify_static.py
The zlib symbols may not be of type 'T' but rather e.g. 'D' -- instead, tell nm to emit the POSIX format and also to only emit defined symbols, not undefined ones. Then we just check if the symbol is listed at all, regardless of type.
We already depend on -U elsewhere (e.g symbolextractor). There's no real replacement for it, sadly.
Bug: https://bugs.gentoo.org/938259
=> tests: handle uncommon architecture format for nm

mesonbuild/environment.py
Fixes #13643  (Architecture was being incorrectly detected for 32-bit clang-cl)
I am not sure how to write test for this. Also tests don't work for me in this case, due to #13645 .
=> Fix check for 32-bit clang-cl

mesonbuild/interpreterbase/baseobjects.py
And fix all of the issues that pop up once we remove the use of `Any`, which hides so many problems.
=> interpreterbase: Use explicit `TypeAlias` annotation to allow recursive types

mesonbuild/compilers/mixins/clike.py
Otherwise, `CFLAGS='-Wall -Werror' meson build` can fail detection:
```
void bar(void) {
struct stat foo;
foo.st_mtim.tv_nsec;
}
-----------
Command line: `cc ./project/build/meson-private/tmpqz_gi65d/testfile.c -o ./project/build/meson-private/tmpqz_gi65d/output.obj -c -O3 -Werror -Wall -D_FILE_OFFSET_BITS=64 -O0 -std=gnu99` -> 1
stderr:
./project/build/meson-private/tmpqz_gi65d/testfile.c: In function 'bar':
./project/build/meson-private/tmpqz_gi65d/testfile.c:45:24: error: statement with no effect [-Werror=unused-value]
45 |             foo.st_mtim.tv_nsec;
|             ~~~~~~~~~~~^~~~~~~~
cc1: all warnings being treated as errors
```
=> compilers: avoid -Wunused-value compiler warning in CLikeCompiler.has_members()

mesonbuild/dependencies/base.py, mesonbuild/modules/pkgconfig.py, test cases/common/278 pkgconfig-gen/meson.build, test cases/common/278 pkgconfig-gen/simple.c, test cases/common/278 pkgconfig-gen/simple.h, test cases/common/278 pkgconfig-gen/simple2/exports.def, test cases/common/278 pkgconfig-gen/simple2/meson.build, test cases/common/278 pkgconfig-gen/simple2/simple2.c, test cases/common/278 pkgconfig-gen/simple2/simple2.h, test cases/common/278 pkgconfig-gen/test.json
Was caused by 7b3169f. Fixes #13657.
I'm not sure about the new test. Ideally, it should be integrated with "44 pkgconfig-gen". However, I don't have the requirements to run it on my machine.
=> Fix pkgconfig.generate handling of BothLibraries dependencies

ci/ciimage/gentoo/install.sh
Qt 6 now has stable keywords (and has for a while). Recent stabilisation of Plasma 6 now pulls in Qt 6 in the image builder so frameworks: 4 qt fails as qttools is missing.
=> ci: gentoo: install dev-qt/qttools

ci/run.ps1
Bump the version of the cidata archive and remove the code that tries to setup dmd and the dub packages from run.ps1 as it doesn't work as expected (builds for x86 instead of x86_64) and cidata should already take care of them.
=> ci/run.ps1: Clean up D related code

docs/markdown/Qt6-module.md, mesonbuild/backend/xcodebackend.py, mesonbuild/compilers/detect.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/configtool.py, mesonbuild/interpreter/kwargs.py, mesonbuild/mconf.py, mesonbuild/modules/rust.py, mesonbuild/programs.py
These errors can make reading comments and documentation unnecessarily confusing for users and contributors who do not speak English as their first language.
=> Fix various incorrect uses of `its` vs `it's`.

mesonbuild/interpreter/interpreterobjects.py, test cases/failing/132 module use inside project decl/meson.build, test cases/failing/132 module use inside project decl/test.json
If a user imports a module and invokes a method on it, a raw Python exception is raised to the user. This commit adds a check to ensure that in this case an appropriate exception is raised instead.
A test has been added to ensure that this exception is in fact raised on offending code.
Fixes #11393
Fixes #5134
=> Prevent raw exception during project()

mesonbuild/mesonmain.py, mesonbuild/mlog.py, run_project_tests.py
A common, and challenging, issue in CI runners is debugging issues when you know the information you want to check, but it's in the log file which you don't have because remote CI machines.
There are various edge cases where this is especially hard to solve, such as inside of `pip install` where the build directory with the log file is automatically cleaned up. But it's never really *easy* when you don't expect it, and the best case scenario is your iteration time gets cut in half as you hurriedly go add some `cat`s to your CI scripts.
Meson can, at least sometimes, detect platforms where text can be emitted inside of "folds", which are auto-collapsed and don't obscure the general output, but when clicked will expand the logfile contents. Hook this up.
We start off with a Github Actions …
=> When configuring fails in Github Actions, print folded logs

mesonbuild/compilers/mixins/clike.py
We always pass the string value of the mode to `determine_args`, which causes the check on the mode argument inside `determine_args` to always evaluate to false.
Fix this by passing the mode itself, not its value.
Discovered this while investigating #13610. I noticed that `determine_args` is always called with a string as its `mode` argument, causing the condition at line 275 to always evaluate to false:
https://github.com/amcn/meson/blob/2b80d4cca174916a4b6d0c47c54ad56795741bb6/mesonbuild/interpreter/compiler.py#L266-L280
=> compilers: Pass mode to determine_args, not its string value

mesonbuild/backend/ninjabackend.py
Rust-analyzer relies on sysroot to discover its proc-macro server [1] which is typically installed at <sysroot>/libexec/rust-analyzer-proc-macro-srv. When used with rust-project.json, rust-analyzer expects the json file to specify sysroot and fails to launch the proc-macro server otherwise.
So add sysroot to the meson-generated rust-project.json and point it to the sysroot of the detected rustc compiler.
[1] https://github.com/rust-lang/rust-analyzer/blob/2024-09-16/crates/project-model/src/sysroot.rs#L175
=> backend/ninja: Generate sysroot in rust-project.json

mesonbuild/mdist.py
https://www.gnu.org/software/gettext/manual/html_node/The-LANGUAGE-variable.html
GNU Gettext defines a feature, whereby for translation purposes, if LC_ALL / LANG are *not* set to C, but rather define an active translation, the LANGUAGE variable can be used to specify fallback languages in a colon-separated list wherein the first option is the primary language and the rest are fallbacks.
CPython, instead, checks the LANGUAGE variable first, and the first variable that has a non-null value is treated as the canonical language specification, splitted, and iterated over. LC_ALL=C is therefore totally ignored, which is a major problem, and the variables aren't checked for consistency, which is a less major problem.
GNU libc documents the same behavior CPython does -- which is broken as it …
=> mdist: correctly detect dirty hg repos with non-English locale, redux

.pylintrc
Added in 3.3.0, split from `too-many-arguments`, which is disabled.
=> pylint: disable `too-many-positional-arguments`

mesonbuild/mlog.py, mesonbuild/rewriter.py, unittests/rewritetests.py
Send the info to stdout, where it belongs.
=> rewriter: don't output target info to stderr

docs/markdown/Dependencies.md, docs/markdown/snippets/dia_sdk.md, docs/markdown/snippets/system_variable_in_dep.md, docs/yaml/objects/dep.yaml, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/cmake.py, mesonbuild/dependencies/configtool.py, mesonbuild/dependencies/dev.py, mesonbuild/dependencies/pkgconfig.py, mesonbuild/interpreter/interpreterobjects.py, mesonbuild/interpreter/kwargs.py, test cases/windows/23 diasdk/dia_registered.cpp, test cases/windows/23 diasdk/meson.build, test cases/windows/24 diasdk copy dll/config.h.in, test cases/windows/24 diasdk copy dll/dia_from_dll.cpp, test cases/windows/24 diasdk copy dll/meson.build
Solves: https://github.com/mesonbuild/meson/issues/13627
Tested on Windows with [msvc, clang_cl], building [x86, x86_64, arm, aarch64] targets (latter two via cross-compiling). AFAIK this is all that DIA SDK supports.
Possible issues:
1. Version of dependency is not provided. The only way I could find would require us to drag in some library for parsing the version out of msdiaXXX.dll resources. 
2. Should the dependency be named 'dia' or 'diasdk'? I am afraid the name 'dia' may be too generic and may conflict with something else in future. This library in particular is very commonly called 'DIA SDK', including the 'SDK' part, maybe for the very same reason.
3. Trickiest part is how to allow users to copy the runtime DLL to build directory, if they want to. This is not strictly required, …
=> Add DIA SDK dependency

mesonbuild/wrap/wrap.py
closes https://github.com/mesonbuild/meson/issues/13701
=> Add Accept-Language and Accept-Encoding headers to wrap requests

mesonbuild/compilers/compilers.py
When running in some settings, a C compiler may demand newlines at the end of each file.  Instead of modifying everywhere that writes out test files to incorporate newlines in each indivudual string, simply add a newline when writing it out.
An examples of when this is a problem is running with `CC=clang` and `CFLAGS="--std=c99 -pedantic-errors"` and meson.build contains (for example) the following:
```
project('myproject', 'c')
executable('myexecutable', 'main.c')
cc = meson.get_compiler('c')
sizeof_int = cc.sizeof('int')
```
sizeof_int will be -1, because the compile failed.  The meson logs contain the error `testfile.c:7:10: error: no newline at end of file`
Fixes https://github.com/mesonbuild/meson/issues/13684
=> Add a newline at the end of test files

run_meson_command_tests.py, run_single_test.py
I've been running the testsuite locally for various in-flight things and I noticed that it can pollute the repo with intermediate files in some cases.
The changes in this PR address this such that running the suite no longer produces these intermediate files.
=> Clean up testsuite intermediate files

.github/workflows/os_comp.yml
D tests in CI are currently skipped on OpenSUSE:
```
2024-09-13T05:41:49.5905706Z ##[group]Run bash -c 'source /ci/env_vars.sh; cd $GITHUB_WORKSPACE; ./tools/run_with_cov.py ./run_tests.py $CI_ARGS'
2024-09-13T05:41:49.5906827Z bash -c 'source /ci/env_vars.sh; cd $GITHUB_WORKSPACE; ./tools/run_with_cov.py ./run_tests.py $CI_ARGS'
2024-09-13T05:41:49.5910232Z shell: sh -e {0}
2024-09-13T05:41:49.5910719Z env:
2024-09-13T05:41:49.5911076Z   ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
2024-09-13T05:41:49.5911543Z   MESON_CI_JOBNAME: linux-opensuse-gcc
2024-09-13T05:41:49.5912026Z ##[endgroup]
2024-09-13T05:41:49.6638977Z /ci/env_vars.sh: line 12: /github/home/dlang/dmd-2.109.1/activate: No such file or directory
2024-09-13T05:41:50.2631396Z Meson build system 1.5.99 Project and Unit Tests …
```
=> .github/workflows/os_comp.yml: set HOME to /root on OpenSUSE

mesonbuild/dependencies/base.py, mesonbuild/interpreter/mesonmain.py, test cases/common/183 partial dependency/declare_dependency/meson.build, test cases/common/183 partial dependency/external_dependency/header_only.c, test cases/common/183 partial dependency/external_dependency/link.c, test cases/common/183 partial dependency/external_dependency/meson.build, test cases/common/183 partial dependency/meson.build, test cases/common/98 subproject subdir/meson.build
#12972 was reverted due to causing failures in libepoxy and a few other libraries.
This second spin identifies those issues as partial_dependency objects, where we *sometimes* would get a new id for the partial dependency (correct), but not in most cases. This respin replaces the `id()` based id with with `uuid.uuid4()` based one, and generates a new id for dependencies when they are `partial_dependency`'d, in all cases, not just those that happened to do so because of implementation.
=> interpreter: when overriding a dependency, override its name too, V2

mesonbuild/dependencies/configtool.py, mesonbuild/dependencies/mpi.py
Fixes #7045, fixes #9637 and fixes #13615. See also the old PR #7373.
This PR improves support for MPI detection on Unix, which is currently quite broken. I didn't try to study what happens on Windows.
- Currently, Meson only supports IntelMPI with Intel compilers and OpenMPI with other compilers. MPICH is not supported at all. (see #7045 and #13615)
- Currently, pkg-config gets priority over detecting mpicc/mpiicc (and friends), which can lead to very unexpected results because only OpenMPI supports pkg-config and all implementations (at least on Unix) state that the correct way to detect/use MPI is to use mpicc/mpiicc (and friends). Then if the system pkg-config gives a positive result, Meson detects OpenMPI even if `PATH` has been correctly modified such that `mpicc` indicates …
=> Improve MPI detection

docs/markdown/Qt6-module.md, docs/markdown/snippets/qt_has_tools_ignore.md, mesonbuild/modules/_qt.py, test cases/frameworks/4 qt/meson.build, test cases/frameworks/4 qt/meson_options.txt, unittests/linuxliketests.py
This allows checking for tools that may not be available in older version of qt or avoiding requesting tools that may not be necessary for a given project
this MR supersed #13524 as discussed [here](https://github.com/mesonbuild/meson/pull/13524#issuecomment-2285522509)
=> qt module: allow has_tools to specify which tools to check

docs/markdown/Reference-tables.md, docs/markdown/snippets/zig_ld.md, mesonbuild/linkers/detect.py, mesonbuild/linkers/linkers.py
Adds support for Zig's linker (zld)
Merges #13493, #12293, and #12953.
Context from https://github.com/mesonbuild/meson/pull/13493#issuecomment-2269602518
> What we really need here is to have a single PR that contains all the necessary changes:
> 
>     * this patch
> 
>     * the patch from [linkers: basic support for the 'zig cc' linker #12293](https://github.com/mesonbuild/meson/pull/12293)
> 
>     * a patch to enable zig in the CI workflows, see [Add Zig to ubuntu-rolling image, CI test #12953](https://github.com/mesonbuild/meson/pull/12953)
> 
> 
> And a second PR that adds zig to the CI images _without_ adding it to the CI workflows, see #12953 again.
> 
> Currently everything is spread out quite a bit and it's difficult to get a handle on whether it all works.
=> Add zig linker support 

mesonbuild/backend/ninjabackend.py, mesonbuild/environment.py, mesonbuild/scripts/clangtidy.py
The `clang-tidy-fix` target spawns an excessive number of threads, because on top of Meson's thread pool `run-clang-tidy` also spawns a thread pool with `os.cpu_count()` threads. On a system with 96 CPU threads this results in over 3000 threads in practice, and if the number of threads is limited (e.g. [in a container](https://docs.podman.io/en/latest/markdown/podman-run.1.html#pids-limit-limit)) this causes errors at runtime.
This PR rewrites the `clang-tidy-fix` target to avoid `run-clang-tidy`, more specifically it performs the same task but exclusively on Meson's thread pool. In practice this means `clang-tidy` is invoked in parallel as normal but "fix-it" snippets are exported to `meson-private/clang-tidy-fix/`. Once the parallel phase is complete (to avoid filesystem races) the …
=> clang-tidy-fix: Avoid spawning too many threads

mesonbuild/scripts/env2mfile.py
Debian cross architectures are detected via dpkg-architecture, not via dpkg-reconfigure.
=> env2mfile: Fix a typo

mesonbuild/linkers/detect.py, unittests/allplatformstests.py
Fixes: #13711
After applying this fix, `./run_unittests.py test_compiler_detection` passes on Solaris 11.4.75.
=> linkers: Fix linker detection with clang on Solaris

packaging/createmsi.py
Guards against exit when the default nuget source is already installed, or when wix is installed but not the wix ui toolset.
Fixes #13704
=> Don't fail to create msi package when run twice.

mesonbuild/compilers/detect.py
Clang's resource files, e.g. /usr/share/clang/clang++.cfg, can be used to bump the default standard level across the system.  
However due to llvm/llvm-project#61641 `clang++ -std=c++17 -E -dM -` doesn't work. The workaround is to pass the language explicitly.  
4ad792e158b6059eb847dd0562aff9bd7029981f fixed the issue by passing the language explicitly, but started passing the `-cpp` flag, which Clang doesn't support.  
Basically Clang would always fallback to the second detection attempt as a result. Remove the unsupported flag and the above scenarios works now too. 🙂
See-also: https://github.com/llvm/llvm-project/issues/61641  
Fixes: 4ad792e158b6059eb847dd0562aff9bd7029981f
=> compilers/detect: remove unsupported -cpp flag for Clang preprocessor detection

mesonbuild/interpreter/mesonmain.py, mesonbuild/programs.py
When we're using the output of `configure_file()` with `override_find_program()`, we weren't storing the version anywhere, so `get_version()` was trying to run the script during setup.
This is usually fine, except in cases where the `configure_file()` script actually has to import a library built as part of the project, and fails to run.
For built executables, we simply use the project version, and we now do the same here too.
=> programs: Store the project version when overriding find_program

test cases/common/36 has function/meson.build
Both recvmmsg/sendmmsg and statx require the `_GNU_SOURCE` symbol to be defined to be shown in headers, but statx has the additional property of being defined on all glibc systems ([ref1][1]), unlike recvmmsg which isn't implemented on Hurd([ref2][2], [ref3][3]).
With this fix, all tests now pass on Hurd.
$ cat meson.build
project('test', 'c')
cc = meson.get_compiler('c')
cc.has_header_symbol('sys/stat.h', 'statx')
cc.has_header_symbol('sys/stat.h', 'statx', prefix: '#define _GNU_SOURCE')
cc.has_function('statx')
$ meson setup build
Version: 1.5.1
Source dir: /tmp/tmp.XcWk4fMra4
Build dir: /tmp/tmp.XcWk4fMra4/build
Project name: test
Project version: undefined
C compiler for the host machine: cc (gcc 14.2.0 "cc (Debian 14.2.0-3) 14.2.0")
C …
=> tests: use statx instead of sendmmsg in has_function test

mesonbuild/compilers/compilers.py
These are all supported by GCC: https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Overall-Options.html
I've encountered at least one project in the wild that uses the .cp extension somewhere...
=> Add additional C++ filename extensions

mesonbuild/backend/ninjabackend.py
I fixed the upstream issue here, so if we have >= 1.12 we don't need to worry about the dyndeps issue.
See: https://github.com/ninja-build/ninja/pull/2406/
=> backend/ninja: allow cleandead with dyndeps and ninja >= 1.12

docs/yaml/builtins/build_machine.yaml
Previously, the documentation said that the CPU name might be amd64, but in fact x86_64 (AMD64) machines are detected as x86_64 in both cpu() and cpu_family() during native builds. Reference: https://buildd.debian.org/status/fetch.php?pkg=libglvnd&arch=amd64&ver=1.7.0-1%2Bb1&stamp=1714222481&raw=0
Instead, mention the only common case for more-specific CPU names other than 32-bit x86, namely 32-bit ARM. On Debian's autobuilders (which are running 32-bit user-space on a 64-bit-capable CPU), native builds genuinely do present as `armv8l`:
https://buildd.debian.org/status/fetch.php?pkg=libglvnd&arch=armhf&ver=1.7.0-1%2Bb1&stamp=1714223924&raw=0 On other machines, they might be some older CPU functionality level.
At the time of writing, cpu() *can* return amd64 when using `meson env2mfile` on …
=> docs: Use examples for build_machine.cpu() that genuinely exist

docs/yaml/builtins/build_machine.yaml
Which were added in Meson 1.2, but don't have entires in the reference manual.
=> Document the .kernel() and .subsystem() methods

mesonbuild/scripts/env2mfile.py, unittests/internaltests.py
* env2mfile: Convert MachineInfo into a dataclass
This will make it easier to unit-test functions that work with a
MachineInfo, by constructing the expected object in a single call.
* env2mfile: Split detect_cross_debianlike()
Separating the part that runs dpkg-architecture from the part that
interprets its results will make it easier to unit-test the latter.
* unittests: Test env2mfile's dpkg_architecture_to_machine_info
This test parses several possible outputs of dpkg-architecture and
asserts that they produce the expected MachineInfo.
To avoid depending on suitable cross-tools being installed, use
unittest.mock to override locate_path with a version that pretends that
all of the tools we're interested in are in /usr/bin.
Similarly, use mock environment variables to exercise what …
=> env2mfile: Add unit test coverage for dpkg -> Meson, and fix some obvious errors

mesonbuild/dependencies/configtool.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/ui.py, mesonbuild/interpreter/interpreter.py, mesonbuild/programs.py, unittests/failuretests.py
macOS mistakenly ships `/usr/bin/ncurses5.4-config` and a man page for it, but none of the headers or libraries are available in the location advertised by it. Ignore `/usr/bin` because it can only contain this broken configtool script. Homebrew is /usr/local or `/opt/homebrew`.
Xcode's command-line tools SDK does include curses, but the configtool in there is wrong too, and anyway we can't just randomly pick it up since the user must explicitly select that as a target by using a native file. The MacOSX SDK itself does not include curses.
We also can't ignore ncurses5.4-config entirely because it might be available in a different prefix.
=> curses: Ignore /usr/bin/ncurses5.4-config on macOS

mesonbuild/compilers/cpp.py, test cases/wasm/1 basic/meson.build
The first versions of Emscripten that correspond with the Clang version Meson uses to determine flag support don't actually support the expected flags. So I went through and picked the first version that actually worked with the expected flags.
Fixes #13628
=> Fix C++ standard support for Emscripten

docs/markdown/Rust.md
As the 2018 standard changes the way rust handles externs, and is the first edition that allows `--extern crate=path` to completely replace (in all but a few corner cases) the use of `extern crate` in the rust files.
=> docs: Mention that rust edition/standard 2018 or later should be used

docs/markdown/Cross-compilation.md
I wanted to suggest (or ask about) this. I don't know how common it is for windres to be required. My first time trying this and I got an error until I added this line.
If you want this change, would you also like me to add some brief info about windres to this page?
Also, what do you think about adding this example I found:
```
[binaries]
c = '/usr/bin/x86_64-w64-mingw32-gcc'
cpp = '/usr/bin/x86_64-w64-mingw32-g++'
fortran = '/usr/bin/x86_64-w64-mingw32-gfortran'
rust = ['rustc', '--target', 'x86_64-pc-windows-msvc', '-C', 'linker=/usr/bin/x86_64-w64-mingw32-gcc']
ar = '/usr/bin/x86_64-w64-mingw32-ar'
pkgconfig = '/usr/bin/x86_64-w64-mingw32-pkg-config'
ranlib = '/usr/bin/x86_64-w64-mingw32-ranlib'
strip = '/usr/bin/x86_64-w64-mingw32-strip'
windres = …
```
=> docs: Add windres to cross-compiling example

mesonbuild/cmake/toolchain.py, test cases/cmake/1 basic/subprojects/cmMod/CMakeLists.txt, test cases/cmake/10 header only/subprojects/cmMod/CMakeLists.txt, test cases/cmake/11 cmake_module_path/subprojects/cmMod/CMakeLists.txt, test cases/cmake/12 generator expressions/subprojects/cmMod/CMakeLists.txt, test cases/cmake/13 system includes/subprojects/cmMod/CMakeLists.txt, test cases/cmake/16 threads/subprojects/cmMod/CMakeLists.txt, test cases/cmake/17 include path order/subprojects/cmMod/CMakeLists.txt, test cases/cmake/18 skip include files/subprojects/cmMod/CMakeLists.txt, test cases/cmake/2 advanced/subprojects/cmMod/CMakeLists.txt, test cases/cmake/21 shared module/subprojects/cmMod/CMakeLists.txt, test cases/cmake/23 cmake toolchain/subprojects/cmMod/CMakeLists.txt, test cases/cmake/23 cmake toolchain/subprojects/cmModFortran/CMakeLists.txt, test cases/cmake/24 mixing languages/subprojects/cmTest/CMakeLists.txt, test cases/cmake/25 assembler/subprojects/cmTest/CMakeLists.txt, test cases/cmake/27 dependency fallback/subprojects/cmMod/CMakeLists.txt, test cases/cmake/27 dependency fallback/subprojects/cmake_subp/CMakeLists.txt, test cases/cmake/27 dependency fallback/subprojects/force_cmake/CMakeLists.txt, test cases/cmake/3 advanced no dep/subprojects/cmMod/CMakeLists.txt, test cases/cmake/8 custom command/subprojects/cmMod/CMakeLists.txt, test cases/failing build/3 cmake subproject isolation/subprojects/cmMod/CMakeLists.txt, test cases/failing/109 cmake executable dependency/subprojects/cmlib/CMakeLists.txt, test cases/failing/119 cmake subproject error/subprojects/cmlib/CMakeLists.txt, test cases/unit/1 soname/CMakeLists.txt
This mitigates maintenance burden as CMake minimum version isn't
relevant for these tests. CMake >= 3.31 warns if CMake minimum version
is less than 3.10.
ref: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9875
=> CMake minimum version 3.10

mesonbuild/compilers/c.py
Follow-up of https://github.com/mesonbuild/meson/pull/13221 where the C23 support minimal emscripten version was wrong. Reported in https://github.com/pyodide/pyodide/discussions/4762#discussioncomment-10839496.
=> Fix minimal version for Emscripten C23 support

mesonbuild/backend/ninjabackend.py, test cases/common/52 object generator/dir/meson.build, test cases/common/52 object generator/dir/source5.c, test cases/common/52 object generator/dir/source6.c, test cases/common/52 object generator/meson.build, test cases/common/52 object generator/prog.c
`outfilelist` is the output list of the target, while `outfiles` is the output list of the individual commands
Bug: mesonbuild/meson/pull/13304#issuecomment-2226398671
=> backend/ninja: fix bad @OUTPUTn@ replacements

mesonbuild/ast/introspection.py, mesonbuild/mintro.py, unittests/allplatformstests.py
The main use case is using this information in meson-python. I don't know whether we should bump the introspection format version for this. I think that the use of JSON for the introspection data makes adding fields backward compatible, thus I don't strictly see the need for it.
=> mintro: Add license and license_files to project introspection data

docs/markdown/snippets/add_support_for_ibm_clang_for_AIX.md
Updating release notes to indicate openXL compiler is supported in AIX.
=> Update release notes for 1.6.0

mesonbuild/dependencies/pkgconfig.py, mesonbuild/interpreter/interpreter.py, run_project_tests.py, test cases/common/279 pkgconfig override/meson.build, test cases/common/279 pkgconfig override/subprojects/pkg-config.wrap, test cases/common/279 pkgconfig override/subprojects/pkg-config/bin/pkg-config.py, test cases/common/279 pkgconfig override/subprojects/pkg-config/meson.build
In the GStreamer monorepo, the goal is for users to build GStreamer and its dependencies out-of-the-box with meson, requiring a minimal setup. Some of the build dependencies such as `flex` `bison` or `nasm` are provided through subprojects that download the binary and override them via `find_program` like: `meson.override_find_program('bison', find_program(meson.project_source_root() / ret.stdout() / 'bin/bison'))`.
`pkg-config` is one of the build dependencies required to build `gobject-introspection`, but it's not possible to override it via ` meson.override_find_program`. The goal of this MR is to support this scenario to simplify the setup and provide a way to provide through an override like the rest of the dependencies. 
I am not sure this is the canonical way, but it allows …
=> Add support to override pkg-config with meson.override_find_program

docs/markdown/Reference-tables.md, mesonbuild/environment.py, mesonbuild/scripts/env2mfile.py, unittests/internaltests.py
uname -s does return gnu there.
Resolves: https://github.com/mesonbuild/meson/issues/13740
=> Add GNU/Hurd kernel results

mesonbuild/scripts/env2mfile.py, unittests/internaltests.py
Depends on #13722, for its test coverage.
* env2mfile: Generalize detection of pkg-config to have a list of tools
Cross-tools on Debian generally follow the naming convention set by
Autotools AC_CHECK_TOOL, where the name is prefixed with the GNU
architecture tuple for the host architecture. env2mfile was already
using this for pkg-config, but there are many other tools that can
be detected in the same way.
* env2mfile: Use Debian cross-prefixed GObject-Introspection tools
In Debian testing/unstable, there are wrappers available for various
GObject-Introspection tools during cross-builds, using qemu internally.
* env2mfile: Automatically set exe_wrapper on Debian if possible
Recent versions of the architecture-properties package provide a
cross-exe-wrapper package containing …
=> env2mfile: Generalize handling of architecture-prefixed tools on Debian derivatives

mesonbuild/dependencies/pkgconfig.py, unittests/linuxliketests.py
I suspect https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3247 might be caused by this issue in meson.
We should prepend the path of uninstalled libraries to PKG_CONFIG_PATH so they have preference over other search paths set by the user.
Support for using uninstalled libraries was added by @xavierclaessens  in https://github.com/mesonbuild/meson/pull/10275.
=> pkgconfig: fix use of uninstalled libraries

docs/markdown/snippets/fixed_sizeof_and_find_library_for_fortran.md, mesonbuild/compilers/fortran.py
The output_is_64bit, sizeof, cross_sizeof, compute_int and cross_compute_int methods are reimplemented for Fortran compilers. Those inherited from CLikeCompiler do not work since they assume C or C++.
Note that those tests rely on Fortran 2008 features (notably the c_sizeof operator).
Closes #12757
=> Reimplement several methods for Fortran compilers

mesonbuild/cargo/interpreter.py, mesonbuild/cargo/manifest.py
This adds support for parsing the new `autolib` member (https://github.com/rust-lang/cargo/pull/14591).
This is a quick and easy fix, suitable for backport. A larger more involved fix will be to stop splatting out the cargo dictionaries, and instead pass the fields we know about 1 by 1, and warning the user if we come across unknown fields.
Fixes: #13826
=> modules/rust: Add support for autolib field in the Cargo.toml

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/mixins/clike.py, mesonbuild/linkers/linkers.py
The purpose of this PR is to enable building for TI C28x targets with Meson without workarounds and un-mesonic ways.
I've looked through the implementation of the support for TI C28x currently in Meson and it appears workarounds have been used to avoid dealing with these issues directly, like including the arg `-llibc.a` in the linker args in the cross file for the MSP430 and using linker command files that can include the runtime support library rather than doing it the Mesonic way.
The existing support for TI C28x cross compilation (C2000, C6000, etc.) omits the compiler args that are required to be included in the linker command for TI C28x and formats the names of static libs incorrectly. An example that demonstrates the issue has been created as a [repo with a Docker …
=> Fix TI C2000 support 

mesonbuild/mtest.py
Fixes #13795.
The logic already existed for the case where we have a test binary with multiple results, I simply ported it over for the else clause.
=> test: report timeout as failure

mesonbuild/compilers/mixins/clike.py
This reverts commit 8242187eb06adaabbd9c9dbb6e5d9a8c102ee6a2.
This same change was previously introduced in #12495 / commit 30ab9747ae03364ac2ccd4a8f508286c57ed54a5 and subsequently reverted in #12672 / commit 2fbc7b5ce3aced483b196dd10ca9eee1713b7494
Reintroduced in #13819 but it's still the same old problem. To repeat the problem:
This breaks at least:
- frameworks/17 mpi
- frameworks/30 scalapack
The problem is that openmpi's pkg-config emitted link arguments includes:
```
-Wl,-rpath -Wl,/path/to/libdir
```
The deduplication logic in meson doesn't contain sufficient information to tell when the compiler is passing an argument that requires values, and definitely cannot tell when that argument is split across argv. But for arguments that *can* do this, it is not possible to deduplicate a …
=> Revert "meson: De-dup rpath arguments"

docs/markdown/Python-module.md
python.install_env is the correct command, as documented in https://mesonbuild.com/Builtin-options.html#python-module. 
python.install_venv causes an error, it is not immediately obvious that the slight typo is the cause.
=> Correct typo in example Python module option

docs/markdown/Wayland-module.md
A lot of projects vendor protocols, since the ones they are using aren't available in default system directories. One example would be kanshi, where I am trying to use the wayland module (see <https://github.com/ericonr/kanshi/pull/2>).
Right now this PR has a few issues. The main one is that the first configuration works and the project can be built successfully, but then, when I touch any of the `meson.build` files, the reconfiguration fails:
```
../protocol/meson.build:3:31: ERROR: The file protocol/wlr-output-management-unstable-v1.xml does not exist.
```
I feel like I'm using a totally wrong way of getting the current source directory.
Furthermore, I don't think this is the ideal interface. A "directory" key might work better? For example in cases where people grab the protocol from …
=> modules/wayland: document that scan_xml can take any protocol.

mesonbuild/dependencies/python.py
This fixes a case not covered in PR #13338, which causes Meson not to locate the Python free-threaded DLL libraries, whose suffix ends in `t` when using GCC.
cc @rgommers
=> Enable GCC to find free-threaded python DLL library

data/shell-completions/bash/meson, data/shell-completions/zsh/_meson, mesonbuild/minstall.py
Since `meson test` already has both `-q` and `--quiet` it makes a lot of
sense to add the short option to `meson install` too for reasons of
symmetry.
Also changes the output order of `-n` and `--dry-run` for consistency in a separate commit.
=> Add `-q` as alternative to `--quiet` for meson install

mesonbuild/cmake/toolchain.py
When a "CMake Toolchain: Failed to determine CMake compilers state" is reported, it seems the CMake output is discarded -
which is unfortunate, as that may contain some valuable information on why that failure occurred.
Hence, log the CMake output so there's more to go on when investigating the failure.
=> CMakeToolchain: Log output on compiler state failure

mesonbuild/backend/xcodebackend.py
Add a check before using an `appleframeworks` to make sure it was found. This fixes an exception in meson while encountering an optional dep for the target.
=> Xcode backend: only use found appleframeworks

mesonbuild/scripts/coverage.py
`--html-nested` was added to gcovr in version 6.0 so passing it to versions before this will result in gcovr complaining that it doesn't recognise the argument.
Added a version check to ensure that we pass a recognised argument for versions before 6.0
Fixes #13781
=> coverage.py: Guard use of `--html-nested` behind version check.

docs/markdown/Reference-tables.md
Meson allows to set the archiver via the `AR` environment variable and a native / cross file. Only the latter approach seems to be documented. This patch adds the `AR` environment variable to the reference tables next to the compilers.
=> Add archiver to reference tables

mesonbuild/cargo/interpreter.py, mesonbuild/cargo/manifest.py, run_single_test.py, test cases/rust/22 cargo subproject/subprojects/bar-0.1-rs/Cargo.toml, test cases/rust/22 cargo subproject/test.json
This prevents use from having uncaught python exceptions when a new key is added, as one recently was. The downside of course of warning is that we might configure incorrectly. At the moment I think that is the preferable way to go, especially since Cargo support is experimental and may fail anyway.
=> Warn when Cargo.toml contains keys we don't expect

docs/markdown/Hotdoc-module.md
Document the results of commit bcc127b3f,
which added 'depends' and deprecated using
'dependencies' for custom targets.
Fixes: #11479
=> Document hotdoc.generate_doc(depends:) kwarg

docs/markdown/snippets/vcs_tag.md, docs/yaml/functions/vcs_tag.yaml, mesonbuild/interpreter/interpreter.py, test cases/common/66 vcstag/meson.build, test cases/common/66 vcstag/test.json
=> vcs_tag: Add install kwargs

docs/markdown/Wrap-dependency-system-manual.md, mesonbuild/msubprojects.py
This change may be more robust. I get these errors when using `head` for the value of `revision` in a wrap file and using 'checkout' or  'update' with the meson `subprojects` option:
```
$ meson subprojects checkout
Checkout head in decimal...
-> Could not checkout head in subprojects/decimal
fatal: invalid reference: head
Git command failed: ['/usr/bin/git', 'checkout', '--ignore-other-worktrees', 'head', '--']
```
```
$ meson subprojects update
Updating decimal...
-> Could not fetch revision head in subprojects/decimal
fatal: couldn't find remote ref head
Git command failed: ['/usr/bin/git', 'fetch', '--refmap', '+refs/heads/*:refs/remotes/origin/*', '--refmap', '+refs/tags/*:refs/tags/*', 'origin', 'head']
```
When I change the revision value to 'HEAD', there's no problem:
$ meson …
=> Check for uppercase 'head' when updating subprojects (fixes #12730)

docs/markdown/Users.md
We introduced Meson with netatalk 3.2.0, and removed Autotools with netatalk 4.0.0
=> Update Users.md with netatalk

docs/markdown/Python-module.md
There is actually very little overlap between `install_sources` and `install_data` in arguments they accept: only 2/7 keywords for `install_data` apply to `install_sources`.
Closes gh-12601
=> docs: fix description of `py.install_sources` arguments

mesonbuild/modules/external_project.py, test cases/common/33 run program/check-mingw.py, test cases/common/33 run program/meson.build, unittests/windowstests.py
On Python 3.12, self.prefix.relative_to(self.prefix.drive) no longer works and raises error like:
ValueError: 'C:/msys64/mingw64' is not in the subpath of 'C:'
```
File "C:/msys64/mingw64/lib/python3.12/site-packages/mesonbuild/mesonmain.py", line 193, in run
^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:/msys64/mingw64/lib/python3.12/site-packages/mesonbuild/msetup.py", line 365, in run
app.generate()
File "C:/msys64/mingw64/lib/python3.12/site-packages/mesonbuild/msetup.py", line 188, in generate
return self._generate(env, capture, vslite_ctx)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:/msys64/mingw64/lib/python3.12/site-packages/mesonbuild/msetup.py", line 227, in _generate
intr.run()
File …
```
=> external_project: workaround for MinGW

mesonbuild/modules/rust.py, test cases/rust/9 unit tests/meson.build, unittests/allplatformstests.py
Any argument from the base target is copied to the test target, but some keyword arguments for libraries are not available in executable. Remove them, and add a unit test that checks for it with --fatal-meson-warnings.
=> rust: avoid warnings from rust.test

run_single_test.py
This fixed `run_single_test.py` on my local development environment (base on MSYS2)
=> run_single_test.py: skip setup_symlinks() call on Windows

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/rust.py
Using a rustup-based toolchain fails the "rust/2 sharedlib" test for me:
```
./prog: error while loading shared libraries: libstd-211931512faabf29.so: cannot open shared object file: No such file or directory
```
This happens because recent rustup places the standard library under SYSROOT/lib/rustlib/TARGET/lib.  Retrieve the right directory using "--print target-libdir".  This also provides a more accurate version for rustc installed in /usr.
Before:
```
$ echo $(/usr/bin/rustc --print sysroot)/lib
/usr/lib
```
After:
```
$ /usr/bin/rustc --print target-libdir
/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib
```
While at it, cache the value to avoid repeated process invocation.
=> Fix computation of rustc library directory

mesonbuild/environment.py
It is possible to run a container or chroot with one ABI on a CPU and kernel that would normally have a different ABI, most commonly by running a 32-bit container on a 64-bit CPU and kernel. When we do a native build in such an environment, the build and host architectures are both equal to the architecture of the container, and it is safe to assume that we can run executables from that architecture, because if we could not, we wouldn't be running Python successfully.
Until now, we have been handling this by adding explicit special cases in `machine_info_can_run()` for each known-good combination of the detected CPU and the host architecture: every x86_64 can run x86 binaries, and every mips64 is assumed to be able to run 32-bit mips binaries. However, the equivalent would not be true on …
=> environment: Never require an exe_wrapper for native builds

mesonbuild/backend/xcodebackend.py
Reorder compile args so the target can override options set by its dependencies.
Fix piling up of custom target include paths.
It is still terribly wrong in many aspects, but at least better than before.
=> Fix OTHER_CFLAGS order for Xcode backend

ci/ciimage/fedora/install.sh, test cases/frameworks/24 libgcrypt/test.json
I have no idea about the Arch failure:
```
2024-11-20T16:22:36.4765258Z [1/5] c++ -Isubprojects/cmMod/libcmModLib__.so.p -Isubprojects/cmMod '-I../test cases/cmake/1 basic/subprojects/cmMod' -Isubprojects/cmMod/__CMake_build '-I../test cases/cmake/1 basic/subprojects/cmMod/__CMake_build' -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu++14 -O0 -g -fPIC -g -DDO_NOTHING_JUST_A_FLAG=1 -DMESON_MAGIC_FLAG=21 -DcmModLib___EXPORTS -MD -MQ subprojects/cmMod/libcmModLib__.so.p/cmMod.cpp.o -MF subprojects/cmMod/libcmModLib__.so.p/cmMod.cpp.o.d -o subprojects/cmMod/libcmModLib__.so.p/cmMod.cpp.o -c '../test cases/cmake/1 basic/subprojects/cmMod/cmMod.cpp'
2024-11-20T16:22:36.4771685Z [2/5] c++  -o subprojects/cmMod/libcmModLib__.so …
```
=> Fix ci images

mesonbuild/mtest.py, test cases/rust/9 unit tests/doctest1.rs, test cases/rust/9 unit tests/meson.build
Doctests have a slightly different output compared to what "protocol: rust" supports:
```
running 2 tests
test rust/qemu-api/libqemu_api.rlib.p/structured/lib.rs - QemuAllocator (line 49) ... ignored
test rust/qemu-api/libqemu_api.rlib.p/structured/zeroable.rs - zeroable::Zeroable (line 9) ... ok
test result: ok. 1 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.11s
```
Add a little more parsing in order to parse this correctly.  I plan to contribute an extension of the rust module to invoke doctests, for now this allows running rustdoc --test with "protocol: rust" and get information about the subtests:
```
2/3 qemu:unit+rust / rust-qemu-api-doctests           RUNNING
...
▶ 2/3 test rust/qemu-api/libqemu_api.rlib.p/structured/lib.rs:QemuAllocator:49 SKIP
▶ 2/3 test …
```
=> mtest: rust: allow parsing doctest output

docs/markdown/Commands.md, docs/markdown/snippets/format_from_stdin.md, mesonbuild/mformat.py
=> format: allow input from stdin

mesonbuild/templates/rusttemplates.py, mesonbuild/templates/sampleimpl.py
Provide a better example of a Rust program that is built with Meson:
* specify 2021 edition to avoid need for `extern crate`
* put tests in the same file as the library
* use the `rust` module and specifically `rust.test`
=> modernize Rust template

mesonbuild/utils/universal.py
Follows upstream cmake, see [configure_file](https://cmake.org/cmake/help/latest/command/configure_file.html).
cmake substitutes `${VAR}` and `@VAR@` by default and only `@VAR@` if `@ONLY` is specified.
meson previously substituded `${VAR}` with `cmake` and `@VAR@` with `cmake@` but this has now been fixed so that `cmake` also substitudes `@VAR@`.
Ontop of that I also split most of the cmakedefine and mesondefine code into specific functions so changes to either won't cause regressions in the other (as the previous cmakedefine PR did).
work was done to ensure all the exported interfaces continue being available.
cmakedefine was tested using [cmakedefine-test](https://github.com/Jan200101/cmakedefine-test) and mesondefine was tested using the `AllPlatformTests.test_do_conf_file_by_format` …
=> separate cmakedefine and mesondefine logic 

mesonbuild/compilers/mixins/clang.py
Recently, it is possible to install Clang with Visual Studio Installer. By default this Clang has a MSVC target, and invokes the Microsoft Linker; if `-fuse-ld=lld` is specified, it will invoke LLD-LINK. Both linkers take MSVC-style arguments, and take DEF files with `/DEF:<path>`.
Previously DEF files were passed in the GNU way, directly on the linker command line like an object file, which caused errors like
lld-link: error: ..\my.def: unknown file type
While Clang-CL takes Unix-style options, it actually passes MSVC-style options to LINK or LLD-LINK with `-Wl,`. There is already a check for both linkers in `linker_to_compiler_args()`, so it's necessary to do the same in `gen_vs_module_defs_args()`.
This commit closes https://github.com/mesonbuild/meson/issues/13988.
=> compilers: Pass `vs_module_defs` with `/DEF:` to LLD-LINK

mesonbuild/backend/xcodebackend.py
Xcode treats this dict value as a space-separated string, any spaces in the path will invalidate the path by splitting it into pieces.
Xcode happens to be doing double quoting with escaping internal quotes for the case.
=> Xcode backend: better quoting for spaces in HEADER_SEARCH_PATHS

docs/markdown/IDE-integration.md, docs/markdown/Unit-tests.md, docs/markdown/howtox.md, docs/markdown/snippets/clippy.md, docs/markdown/snippets/introspect_machine.md, docs/markdown/snippets/num-processes.md, mesonbuild/ast/introspection.py, mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/detect.py, mesonbuild/compilers/mixins/gnu.py, mesonbuild/compilers/rust.py, mesonbuild/mintro.py, mesonbuild/mtest.py, mesonbuild/scripts/clangformat.py, mesonbuild/scripts/clangtidy.py, mesonbuild/scripts/clippy.py, mesonbuild/scripts/externalproject.py, mesonbuild/scripts/run_tool.py, mesonbuild/utils/universal.py, unittests/allplatformstests.py
Running clippy by setting a custom rustc compiler that points to "clippy-driver" is suboptimal, because it requires reconfiguration. Similar to the "ninja scan-build" target for C, add a clippy internal tool that runs clippy-driver on all crates in the project.
This also provide infrastructure to find sibling tools to rustc, such as "clippy-driver" itself or rustdoc, when using the "rustup run TOOLCHAIN rustc" to invoke rustc. Adding rustfmt for example is trivial.
A few extra new features are included as a bonus :angel: 
* `MESON_NUM_PROCESSES` respected every time Meson invokes multiple processes in parallel (supersedes `MESON_TESTTHREADS`
* clang-tidy targets respect `b_colorout`
* clang-tidy target do not mix output from multiple files
* target introspection gains a `machine` entry …
=> Add a new target "ninja clippy" for Rust projects

mesonbuild/compilers/mixins/clang.py
`-fuse-ld=` is a driver option for selection of a linker; it shall not be passed to a linker with `-Wl,`.
Previously, using Clang-CL and LLD-LINK, given:
cc = meson.get_compiler('c')
assert(cc.has_link_argument('/LTCG'))
This code failed to detect the `/LTCG` option, because `-fuse-ld` was passed to the linker, as an invalid option:
Command line: `clang E:\lh_mouse\Desktop\t\build\meson-private\tmpg0221f
ee\testfile.c -o E:\lh_mouse\Desktop\t\build\meson-private\tmpg0221fee\o
utput.exe -D_FILE_OFFSET_BITS=64 -O0 -Werror=implicit-function-declarati
on -Wl,-WX -Wl,/LTCG -Wl,-fuse-ld=lld` -> 4044
stdout:
LINK : warning LNK4044: unrecognized option '/fuse-ld=lld'; ignored
LINK : error LNK1218: warning treated as error; no output file generated
=> compilers: Do not pass `-fuse-ld=lld` via `-Wl,`

mesonbuild/interpreter/compiler.py
This is my first code pull request to meson, so please be patient with me. I have done little to no testing for this PR, but the change is taken directly from [`mesonbuild/interpreter/compiler.py:541`](https://github.com/mesonbuild/meson/blob/83253cdbaa8afd268286ca06520ca1cf2095dd28/mesonbuild/interpreter/compiler.py#L541), the change looks reasonable and only logging is affected (no core functionality is modified).
The following log output:
```
Checking if "strnstr() available" : links: NO
```
now becomes:
```
Checking if "strnstr() available" links: NO
```
This is more consistent with the `compiles()` method.
=> compiler: fix leftover chars in compiler.links()

mesonbuild/utils/universal.py, test cases/common/14 configure file/config10.h.in, test cases/common/14 configure file/meson.build, test cases/common/14 configure file/prog10.c, test cases/frameworks/7 gnome/mkenums/meson.build
the upstream behavior of configure_file in cmake parses both @VAR@ and ${VAR} and only supports disabling the bracket variables through the `@ONLY` argument, meson needs to follow this behavior for compatibility
this is an ugly solution but I think its best considering the alternatives:
- calling `do_conf_str` twice with both formats
- will break if the first iteration places substitutes that match the format of the second iteration
- adapt the existing bracket format regex to support @
- the existing regex is unholy and broken in more ways than I am willing to list, it would be better to completely gut this part of the code and replace it with regular python code
- rewrite the code to not use regex
- this would be quite complex and I am not familiar enough with mesondefine to be able to …
=> do @ variable substitution when parsing cmake format

mesonbuild/modules/rust.py
bindgen by default may output code that an older rustc cannot successfully consume. To avoid this, we check if bindgen supports the rustc version we're using, if so, and if the user didn't set the `--rust-target` option, we will supply it to ensure that bindgen writes out code our rustc can use. If it does not support that version explicitly, we leave it at the default, assuming that our compiler version is newer than bindgen.
=> modules/rust: Specify the compiler version to bindgen when possible

mesonbuild/backend/backends.py, test cases/failing/126 generator host binary/test.json, unittests/linuxcrosstests.py
It's not the first time I run into an issue with an intentionally missing exe_wrapper during cross compilation. In pretty much all the cases the project I tried to build already had code available to not need one in the first place. Print out what command was actually the culprit to make debugging this easier.
=> print out which command needs an exe_wrapper

.github/workflows/macos.yml
Using Homebrew Clang leads to failures when testing objfw. We probably
want to ensure we use Apple Clang here given the workflow job name, in
any case.
=> Prioritise Apple's toolchain in project-tests-appleclang

test cases/frameworks/8 flex/lexer.l, test cases/frameworks/8 flex/parser.y, test cases/frameworks/8 flex/prog.c
With C23 (as upcoming GCC 15 will default to), `void yyerror()` is the same as `void yyerror(void)`, i.e. `yyerror` takes no arguments.
Fix the prototype given we *do* call it with an error string:
```
pgen.p/parser.tab.c: In function ‘yyparse’:
pgen.p/parser.tab.c:1104:7: error: too many arguments to function ‘yyerror’
1104 |       yyerror (YY_("syntax error"));
|       ^~~~~~~
../test cases/frameworks/8 flex/parser.y:3:12: note: declared here
3 | extern int yyerror();
|            ^~~~~~~
pgen.p/parser.tab.c:1215:3: error: too many arguments to function ‘yyerror’
1215 |   yyerror (YY_("memory exhausted"));
|   ^~~~~~~
../test cases/frameworks/8 flex/parser.y:3:12: note: declared here
3 | extern int yyerror();
|            ^~~~~~~
```
Bug: https://bugs.gentoo.org/946625
=> test cases: fix '8 flex' with C23

mesonbuild/arglist.py, mesonbuild/compilers/mixins/clike.py
Continuation of https://github.com/mesonbuild/meson/pull/13819.
CC: @eli-schwartz
=> Try #2: De-dup rpath arguments on apple clang

docs/markdown/Dependencies.md, docs/markdown/snippets/atomic-dependency.md, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/misc.py
Almost exactly the same as how the dl dependency works. On certain systems (like BSDs that use clang), stdatomic is provided by compiler-rt and doesn't need a separate library explictly linked. On a typical GNU/LINUX system, atomic is a separate library that must be explictly found and linked against. So just add a builtin and system method for these two use cases.
=> dependencies: add custom atomic dependency

mesonbuild/envconfig.py, unittests/failuretests.py
With
CC=ccache meson ...
meson crashes with
[...]
File "/usr/lib/python3.10/site-packages/mesonbuild/compilers/detect.py", line 364, in _detect_c_or_cpp_compiler
compiler_name = os.path.basename(compiler[0])
IndexError: list index out of range
Improve this by throwing an `EnvironmentException` to fail gracefully when no compiler is specified.
Fixes #9933
Fixes #13589
=> Fail gracefully when compiler cache is specified without compiler

mesonbuild/wrap/wrap.py
This fixes the problem described in the related issue https://github.com/mesonbuild/meson/issues/14072.
=> Fix #14072 symlinks not handled correctly by wrap patch.

mesonbuild/build.py, mesonbuild/dependencies/base.py
Internal dependency names were generated from object id. This cause problem when objects are copied, especially when generating partial dependency, or when extracting shared or static dependencies from both_library, because dependency names in target and dependencies introspection files become unrelated.
This fixes that by generating the dependency name from the internal id, and by using that base name when generating partial dependencies.
=> Fix internal dependency names

.github/workflows/cygwin.yml
Use a tagged version of cygwin-install-action, rather than whatever happens to be master at the moment.
This should help isolate meson CI from random breakage there.
=> CI: Use a tagged version of cygwin-install-action

mesonbuild/programs.py
On Windows, if the native file contains a path without the extension, the executable may be found, but custom target would fail because that path does not exist.
=> fix missing extension in command path

unittests/allplatformstests.py
Tests can tread on each other's toes when parallelism is high enough.
In this case, `test_prebuilt_shared_lib` creates an object file in the `17 prebuilt shared` test dir.
`test_prebuilt_shared_lib_rpath_same_prefix` uses `shutil.copytree` to copy that same test dir to a temporary location.
If the former test cleans up its object file while `copytree` is running, the copy can fail with a fatal ENOENT `shutil.Error`.
Use `copy_srcdir` to prevent this from happening.
=> tests: Avoid modifying '17 prebuild shared' test dir

docs/markdown/snippets/test_dependencies.md, mesonbuild/backend/ninjabackend.py, mesonbuild/mtest.py, run_project_tests.py, test cases/unit/106 underspecified mtest/main.c, test cases/unit/106 underspecified mtest/meson.build, test cases/unit/106 underspecified mtest/runner.py, unittests/platformagnostictests.py
Regression in the original implementation of commit 79e2c52a15e896e46ff3cfa3ec16fbf3f132ee01.
If an explicit list of targets is passed on the CLI, then that is passed to rebuild_deps. If not, we pass every loaded test to rebuild_deps instead. This means we cannot distinguish between "trying to run all tests" and "trying to run specific tests". We then load all the deps for all tests, and try to build them all as explicit arguments to the underlying ninja.
This is usually papered over by people running `ninja test`, which depends on "all" anyway as a prerequisite for invoking the underlying `meson test --no-rebuild --print-errorlogs`, however, instead running `meson setup builddir && meson test -C builddir` with under-specified test deps would actually build a handful of deps and not …
=> mtest: fix rebuilding correct target list before running tests

docs/markdown/Builtin-options.md, docs/markdown/snippets/cargo_cap_lints.md, mesonbuild/cargo/interpreter.py, mesonbuild/compilers/rust.py, mesonbuild/scripts/clippy.py
In Rust, the equivalent of -W/-D options can be added inside the sources themselves (`#[warn]`, `#[deny]`) and therefore it's quite common for a crate to stop building with newer compilers.
To avoid this, Cargo hides warnings from non-path dependencies using the special flag `--cap-lints allow`. Do the same for downloaded Cargo subprojects by adding `warning_level=0` to the generated subproject's default options. While warning_level=0 generally means "compiler default", Rust has always used it for the similar but inferior option `-A warnings`, so just replace that with `--cap-lints allow`.
The question is what to do for pure-Meson Rust subprojects. Here I'm leaving them aside, because they can do the check themselves with `meson.is_subproject()` if they wanted and because in general I'm …
=> Hide warnings from Cargo downloaded subprojects

data/macros.meson
In rpm >= 4.20[1], a new feature Declarative Buildsystem[2] will be introduced to simplify spec files. I think we should add support on it.
[1]: https://github.com/rpm-software-management/rpm/issues/1087
[2]: https://rpm-software-management.github.io/rpm/manual/buildsystem.html
=> Add macros for declarative buildsystems of rpm >= 4.20

mesonbuild/compilers/cpp.py
I tried to compile a C++20 project with intel's icx and noticed meson only allows up to C++17. 
I was only able to check icl version 2021.2.1 and icx versions 2024.4.2 and 2025.0.1, so the version checks are rough guesses.
=> Update C++ standards list for intel compiler on windows

mesonbuild/programs.py, unittests/internaltests.py
When using `find_program('perl')` we misdetect its version number:
Program perl found: YES 40 40 (/usr/bin/perl)
This is caused by Perl outputting the version information in a somewhat weird format:
$ perl --version
This is perl 5, version 40, subversion 0 (v5.40.0) built for x86_64-linux-thread-multi
...
The problem here is that our version number detection picks the first match of at one digit followed by at least one more digit and/or dot. Consequently, as "40" matches that regular expression, we'd return its value as the version number.
Naturally, the version number detection we perform is best-effort, only, as there is no standardized format used by all programs. That being said, we can do better here by first trying to match a dotted version number so that we'd match the "5.40.0" …
=> programs: favor version numbers with dots

mesonbuild/backend/ninjabackend.py, mesonbuild/interpreter/interpreter.py, mesonbuild/interpreterbase/interpreterbase.py, mesonbuild/mparser.py, mesonbuild/utils/universal.py
Optimize a few uses of uncompiled regex that amount to a visible % of meson's run time. Frequently used regexes should be either compiled, or removed altogether.
Version checks remain quite inefficient, taking about 2% of the runtime; but they're not easy to improve (e.g. by pre-building the Version objects) because most of them are of the compare_condition_with_min kind.
While these are small improvements, they pile up.
=> Speedup regex usage

mesonbuild/programs.py, unittests/internaltests.py
In a3679a64e (programs: favor version numbers with dots, 2025-01-03) we have changed the regex used to extract version numbers to favor dotted versions. It was reported though that the regex doesn't match major version numbers that start with multiple digits correctly. Fix this.
=> programs: fix regex to match multi-digit major version

mesonbuild/build.py
Fixes https://github.com/mesonbuild/meson/pull/12875.
=> Copyedit an error message

docs/markdown/Builtin-options.md, docs/markdown/Reference-tables.md, mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/build.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/detect.py, mesonbuild/compilers/mixins/apple.py, mesonbuild/compilers/mixins/elbrus.py, mesonbuild/compilers/mixins/gnu.py, mesonbuild/compilers/mixins/tasking.py, mesonbuild/envconfig.py, mesonbuild/linkers/base.py, mesonbuild/linkers/linkers.py
This PR adds support for the TASKING compiler family, and its MIL linking feature as mentioned in #11866.
=> Add support for the TASKING compiler family, and its MIL linking feature

docs/markdown/Reference-tables.md, docs/markdown/snippets/linearasm_features.md, mesonbuild/compilers/asm.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/detect.py
Fix #13670
PS:
- same feature for [cmake](https://gitlab.kitware.com/cmake/cmake/-/issues/26510)
- feature request for [xmake](https://github.com/xmake-io/xmake/issues/5163)
=> Add Linear ASM compiler

docs/markdown/Users.md
Git 2.48 introduced support for the Meson build system:
https://github.com/git/git/commit/904339edbd80ec5676616af6e072b41804c1c8eb
https://github.blog/open-source/git/highlights-from-git-2-48/
=> docs: add Git to list of projects using meson

mesonbuild/dependencies/ui.py
Currently, the vulkan system dep detects its vulkan version by building and running:
```c
#include <stdio.h>
#include <vulkan/vulkan.h>
int main() {
printf("%i.%i.%i", VK_VERSION_MAJOR(VK_HEADER_VERSION_COMPLETE),
VK_VERSION_MINOR(VK_HEADER_VERSION_COMPLETE),
VK_VERSION_PATCH(VK_HEADER_VERSION_COMPLETE));
return 0;
}
```
this causes cross builds that do not have the possibility of running on the build machine to evaluate the vulkan dependency with an 'Unknown' version.
The new implementation provides a fallback mechanism that first evaluates the same code as above (just without the stdio import) using the C Preprocessor for the host machine and then takes the evaluated main function, adds the required stdio and stdint headers and builds it using the build machine c compiler in order to …
=> vulkan system dep: determine version on cross builds

mesonbuild/compilers/cpp.py
Fixes https://github.com/mesonbuild/meson/issues/14075.
=> Fix minimum required Apple clang version for C++26

data/shell-completions/zsh/_meson
All flags which don't have the `(Since 0.a.0)` comment in their description aren't currently completed by ZSH completions. This is pretty annoying, because I use `--destdir` and `--dry-run` often, so I wanted to fix this.
The `--skip-subprojects` flag introduced by this PR currently doesn't have suggestions.
=> zsh: Add missing flags to 'meson install'

data/shell-completions/zsh/_meson
This PR fixes invalid syntax, which leads to
```
(eval):1: number expected
_arguments:465: command not found: _
```
when trying to complete `meson init --language=<TAB>`.
=> zsh: Fix 'meson init --language' completion

ci/ciimage/gentoo/install.sh, ci/ciimage/opensuse/install.sh
I assume I only added this when copying Arch as a template initially, it certainly isn't needed now, as pointed out by Eli being suspicious of its presence...
=> ci: gentoo: drop fakeroot, ci: opensuse: drop gtk-sharp3-complete

mesonbuild/backend/ninjabackend.py, mesonbuild/scripts/clippy.py
Found these while trying rc1 on QEMU and using the new "ninja clippy". I will try to add test cases next week.
=> Fixes for "ninja clippy"

mesonbuild/build.py, mesonbuild/dependencies/base.py, test cases/common/273 both libraries/meson.build
#13837 broke both_lib transitive deps, because the
`as_static` and `as_shared` functions return libraries that still contain references to the other lib type.
=> Fix broken both_libraries transitive dependencies

mesonbuild/interpreterbase/interpreterbase.py, test cases/common/158 disabler/meson.build, test cases/common/158 disabler/subprojects/bar/meson.build
Add an exception to the disabler check to allow objects with a `get_variable` method to not always pick a disabler if their arguments contain one. This mimics the behaviour already in place for calls to functions, which has a set of excepted functions.
Fixes #13717
=> interpreterbase: Add disabler exception for `get_variable` method

mesonbuild/compilers/mixins/clike.py
Expand the expression passed into cross_compute_int using the preprocessor first and then try to evaluate the expanded expression using the host machine compiler and test if the result is valid.
See #13910 for previous discussion
=> compilers/clike: Speedup cross_compute_int

docs/meson.build
It pulls in 22 (!!!) dependencies and is only needed in CI for a trivial lint of the HTML docs. This is a big problem for people that simply want to compile the manpage. Let the tests fail at test time if this dependency isn't available.
Fixes: 74aab8a42c479cdeeda9371dbd591a19d070c48e
/cc @dnicolodi @thesamesam 
This should fix Gentoo's from-git builds of meson.
=> docs: do not require aiohttp to build

mesonbuild/compilers/mixins/gnu.py
This inclusion was a misunderstanding on my part: this warning isn't generally applicable to standard C (it prevents using double literals whatsoever since C doesn't have a suffix for them), but exists to support a GNU C extension.  It also has no counterpart in clang.  So, remove it, since warning_level=everything doesn't include such things.
=> Remove GCC's -Wunsuffixed-float-constants from warnings

docs/markdown/Dependencies.md
Persumably this list of was supposed to be alphabetized, but a few of the items were out of order. This confused me because I was looking for numpy, got the the Os and thought it wasn't there.
=> Alphabetize the Docs on Dependencies

mesonbuild/linkers/linkers.py, test cases/unit/10 build_rpath/meson.build
rpaths are calculated in bytes, and that's also how depfixer processes them. We need to ensure that the ascii padding we use (bytes == unicode) is the correct offset for the install rpath - build rpath (both specified in unicode which then gets converted to bytes).
In the event of a unicode install_rpath, we can get into a situation where the install rpath is longer than the padding, since we assumed that the install_rpath was shorter than it actually is -- because we counted the length in characters instead of the length in bytes.
This then broke installation for people who e.g. install into a prefix inside their home directory, when their home directory contains multibyte unicode characters.
Bug: https://gitlab.gnome.org/GNOME/gnome-builder/-/issues/2280
=> linkers: fix rpath padding calculation for non-ascii

README.md
See https://pypi.org for confirmation of the capitalization.
=> Fix capitalization of "PyPI" in README.md

docs/yaml/functions/declare_dependency.yaml
Based on a conversation I had with @eli-schwartz
=> docs: clarify use cases for declare_dependency()

docs/markdown/snippets/tasking_compiler.md
I missed adding a release snippet for the TASKING compiler in #12342
=> docs: Add missing release snippet for the TASKING compiler support

docs/markdown/Builtin-options.md, docs/markdown/Configuring-a-build-directory.md, mesonbuild/compilers/c.py
Clang introduced a new standard for C: [C2Y](https://clang.llvm.org/c_status.html#c2y). It is available for clang 19 onwards. My commit is simple enough, just adding the std flag to the appropriate version. I did test this successfully on my machine with clang-19 installed, but it is my first commit here.
BTW: I just want to mention that I (coming from CMake) really like meson so much, and I am really grateful to all the wonderful people who are maintaining and have contributed to this project.
=> adding c_std=c2y option for clang

mesonbuild/templates/cpptemplates.py, mesonbuild/templates/cstemplates.py, mesonbuild/templates/ctemplates.py, mesonbuild/templates/cudatemplates.py, mesonbuild/templates/dlangtemplates.py, mesonbuild/templates/fortrantemplates.py, mesonbuild/templates/javatemplates.py, mesonbuild/templates/mesontemplates.py, mesonbuild/templates/objcpptemplates.py, mesonbuild/templates/objctemplates.py, mesonbuild/templates/rusttemplates.py, mesonbuild/templates/samplefactory.py, mesonbuild/templates/sampleimpl.py, mesonbuild/templates/valatemplates.py
There's a couple of changes here. There's some just plain code cleanups, there's some formatting work, some replacement of deprecated methods, and some work to combine the templates and make them more powerful.
On that work I've done the following:
- combined the "brand new project" and "add Meson to a project" paths to use the same code, this has enhanced both paths
- updating the pkg-config API usage to use the "lib as a positional argument" approach
- updating the way Meson version is handled to allow each template to set its own minimum
- call `meson.override_dependency()` when we create the dependency for subprojects
- use library() and `<lang>_shared_args` instead of shared_library
=> Cleanup and modernize the templates and commands used by `meson init`

mesonbuild/interpreter/interpreter.py
If a module exists but errors during importing (e.g. a bad import inside the module itself) it will act as if the module doesn't exist, which is pretty confusing. In this case propagate the real error.
(Should this unconditionally fail instead of soft-failing when required is False?)
=> Show real error if module exists but import failed

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py
When building QEMU, about 10% of the time is spent in flatten_object_list due to its use of _determine_ext_objs and object_filename_from_source. With a little preparation, the results from both of these can be memoized.
This PR tackles _determine_ext_objs() and a particularly hot part of object_filename_from_source() (which is `canonicalize_filename()`), both of which can be (mostly) handled just with functools.lru_cache.
=> Speedup extract_objects

mesonbuild/backend/ninjabackend.py
As the comment to get_generated_headers says, these dependencies should be order-only dependencies.
Fixes #10882.
=> ninjabackend: Make header deps order-only deps

mesonbuild/compilers/cpp.py
This PR adds a non-configurable flag to clang++ PCH builds: `-fpch-instantiate-templates` which in my own tests with a medium sized project (~1m loc) cuts build times in half.
see:
- https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5168
- https://reviews.llvm.org/D69585
I ran `CXX=clang CXX_LD=mold ./run-tests.py` locally and all relevant tests passed, but I'm not a python dev so I have very little idea of what I'm doing when I touch python, please be patient with me.
=> compilers/clang++: Add `-fpch-instantiate-templates` flag to speed up clang++ builds

mesonbuild/interpreter/interpreter.py
It's not especially explanatory to say:
```
meson.build:357:34: ERROR: Automatic wrap-based subproject downloading is disabled
```
But if we instead say this:
```
ERROR: Subproject libsamplerate is buildable: NO
meson.build:357:34: ERROR: Automatic wrap-based subproject downloading is disabled
```
It becomes a lot clearer to casual inspection, why it failed. And it matches the way we otherwise report errors for an unbuildable subproject (configure errors).
Bug: https://github.com/jacktrip/jacktrip/issues/1380
=> When subproject() fails because downloading is disabled, say what failed

mesonbuild/compilers/c.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/detect.py, mesonbuild/compilers/mixins/apple.py, mesonbuild/compilers/mixins/clang.py, mesonbuild/compilers/mixins/gnu.py, mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, test cases/unit/116 c cpp stds/meson.build, test cases/unit/116 c cpp stds/meson.options, unittests/allplatformstests.py, unittests/baseplatformtests.py, unittests/failuretests.py, unittests/machinefiletests.py
Also, share the implementations between the C and ObjC, and C++ and OjbC++ instance of both Clang and GNU compilers, so that we update once, and only once for each compiler.
Mostly this just ends up moving code around.
Fixes: #13639
=> Support lists for ObjC and ObjC++ standards

mesonbuild/interpreter/interpreter.py, mesonbuild/utils/universal.py
On Windows, if you accidently add a space at the end of a file name, like `files('myfile.txt ')`, the file is not reported as missing, because of the normalization performed by the OS. However, ninja will reference it with the trailing space, and will fail because the file does not exist.
One solution is to prepend the file name with `\\?\` to prevent the normalization of the name.
See https://github.com/python/cpython/issues/115104 for reference.
=> Detect missing files with trailing space on Windows

mesonbuild/scripts/symbolextractor.py
It should be possible to just use the first line rather than the last.
=> symbolextractor: use -nologo with lib.exe and llvm-lib.exe

mesonbuild/compilers/swift.py, test cases/swift/9 sdk path from dep/foo.swift, test cases/swift/9 sdk path from dep/meson.build
SwiftPM issue with more context: https://github.com/swiftlang/swift-package-manager/issues/6439
Some dependencies can bring include paths pointing to older macOS SDK's. In this case, it was libffi pointing to SDK from 12.0. When the Foundation framework is imported in Swift, swiftc attempts to import the FFI module from the most recent version of the SDK, which causes a compilation error because of conflicting definitions between the two SDK versions.
It would error out like so:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include/module.modulemap:1171:1: note: in file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include/module.modulemap:1171:
extern module …
```
=> swift: Fix compilation error when dependency adds the macOS SDK in the include dirs

mesonbuild/backend/vs2010backend.py
There was a missing parameter in one call.
This was caused by b95e1777ddbf0f8aebb56b84a6011468088c06ec
=> Fix call to object_filename_from_source in vs2010

mesonbuild/scripts/symbolextractor.py
If `windows_syms()` doesn't find the proper symbol with the tools of the environment, it ends up doing the same thing as `dummy_syms()`.
This may work for other platforms, but was only tested on a Windows cross-compilation.
=> symbolextractor: generate symbol files for cross-compiled Windows

docs/markdown/Creating-releases.md
See https://github.com/PowerDNS/pdns/issues/15048
=> Mention add_dist_script in meson dist docs

mesonbuild/dependencies/python.py
Hi all,
This PR enables generating Python bindings and linking against `python3-embed` without resorting to later `install_name_tool` changes, as the pkg-config module provided by Xcode doesn't say that Python3.framework requires a rpath entry:
$ otool -L /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Python3
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Python3:
@rpath/Python3.framework/Versions/3.9/Python3 (compatibility version 3.9.0, current version 3.9.0)
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1933.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
All feedback is appreciated.
cc @nirbheek
=> Python: Work around missing rpath in Xcode python3-embed

mesonbuild/utils/universal.py
The main thing I wanted to fix is that currently calling `PerMachineDefaultable[T].default_missing()` returns a `PerMachine[T | None]`, according to it's annotations and is possible according to its implementation but we universally expect that it should return `PerMachine[T]`. I've added asserts to ensure that this is the case, but we could write this as a return of `PerMachine[T] | None`, and then have the callers do a check to ensure that they're not getting a None. But I didn't like that.
Anyway, I've also ported these over to be a dataclass, as that simplifies the initializer logic and allows us to remove custom `__repr__` methods, leading a net win on LOC and copying ourselves.
=> Cleanup PerMachine classes, especially nullability

mesonbuild/mformat.py
Fix #14167. This PR makes mformat search `meson.format` in parent directories.
=> mformat: try to detect meson.format in parent directories

mesonbuild/backend/backends.py
SharedModule (like Python extension modules) are loaded dynamically. Therefore, they cannot be detected from executable dependencies, and we must call `determine_windows_extra_paths` on them as well.
Also, those extra paths need to be computed even if the module or the executable is not installed in the default location.
=> Fix PATH for SharedModule in Windows devenv

mesonbuild/minstall.py
This is an annoying issue to look at, because shutil.chown has (for our purposes) three signatures:
```python
chown(path: int | AnyPathLike, uid: int | str, group: None = None) -> None: ...
chown(path: int | AnyPathLike, uid: None, group: int | str) -> None: ...
chown(path: int | AnyPathLike, uid: int | str, group: int | str) -> None: ...
```
This is a really difficult thing to guarantee from our code. We more or less depend on being able to pass two parameters of `None | int | str`, and it working. In our only caller we do ensure that at least one of the variables is not None, but convincing mypy of this is more work than it's worth.
This issue only shows up in CI with python >= 3.13. It also shows up with pyright (used in VSCode) for earlier versions because of an updated typeshed.
=> minstall: help mypy out with our chown overriding

mesonbuild/cmake/interpreter.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/cython.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/mixins/emscripten.py, mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, mesonbuild/compilers/rust.py, mesonbuild/coredata.py, mesonbuild/mconf.py, mesonbuild/mintro.py, mesonbuild/optinterpreter.py, mesonbuild/options.py, run_mypy.py
This fixes all of the issues in the options module, as well as fixing type safety issues introduced by it. This really falls into four parts:
1. fix the pre-existing issues with the `UserOption` classes
2. clean up some uses of `Any` that would hide real issues
3. Correct annotations for the OptionKey type that were broken
4. add missing annotations to the `OptionStore` class.
This fully supersedes #13616
=> Make the new options module fully type safe

mesonbuild/interpreter/interpreter.py
We end up mixing Shared and Static so that we cast to Static args for Shared Libraries and vice versa.
=> interpreter: fix swapped casts

mesonbuild/dependencies/cmake.py
Previous sorting algorithm mangles -framework args. Seems like it was already thought of in resolve_cmake_trace_targets (https://github.com/mesonbuild/meson/blob/c508b26867741b83b3b73fc88de1ad97acc39c18/mesonbuild/cmake/tracetargets.py#L158-L161) but not here.
Previous output:
```
Libraries:            ['-F/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk/System/Library/Frameworks', '-framework', '/opt/homebrew/lib/libvsg.a', '/opt/homebrew/lib/libvulkan.dylib', 'Cocoa', 'QuartzCore']
```
New output:
```
Libraries:            ['-F/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk/System/Library/Frameworks', '-framework', 'Cocoa', '-framework', 'QuartzCore', '/opt/homebrew/lib/libvsg.a', '/opt/homebrew/lib/libvulkan.dylib']
```
=> Fix CMake import's linker args sorting algorithm mangling -framework arguments

mesonbuild/modules/pkgconfig.py
The `mesonlib.is_*` functions are not correct to use here, since they are for the build machine, not the host machine. This means if the build machine if Linux but the host is Haiku, then pkg-config files willb e installed into $libdir/pkgconfig, instead of $prefix/develop/lib/pkgconfig
=> modules/pkgconfig: use host machine to calculate install prefix

mesonbuild/compilers/mixins/clike.py, test cases/common/104 has arg/meson.build
When supplying -Wno-vla-larger-than to compiler.get_supported_arguments, meson will inject -Wvla-larger-than as an argument which considered invalid by GCC, as the converse argument is -Wvla-larger-than=<value>.
Just like CLikeCompiler._has_multi_arguments special-cases -Wno-attributes=, do the same for -Wno-vla-larger-than.
Resolves: https://github.com/mesonbuild/meson/issues/14208
=> c: add -Wno-vla-larger-than to the exceptions for -Wno*

mesonbuild/backend/ninjabackend.py
The swift compiler does not update the modification time of output object files when the code has not changed. Without this, Swift targets may continuously be rebuilt.
=> Add restat = 1 to Swift compile rule

mesonbuild/backend/backends.py, mesonbuild/build.py
In large repositories, transitive link dependency resolution using the current recursive algorithm can result in enough duplicate calls to cause the full system memory space to be used up.
This commit simplifies link dep resolution by converting the currently used recursive algorithm to an iterative one that avoids performing work more than once. If a target's direct dependencies have already been processed, that target will not be processed again.
These changes result in multiple orders of magnitude of improvements to dep resolution time and memory usage in the worst case. In a repro provided by @andrei-pavel, the following stats on `meson setup` were achieved on [this project](https://gitlab.isc.org/isc-projects/kea/-/tree/1f158da82886b9b9a41adda4c0abfb1d72672d8f):
| | 1.7.0 | #13532 | …
=> build: Optimize transitive link dep resolution

mesonbuild/options.py, unittests/optiontests.py
=> Fix yielding when top project does not define the option.

mesonbuild/compilers/c.py
For some reason, a change in https://github.com/mesonbuild/meson/commit/181c3499fde491650269c236ea639c92f10c6914 required `opts` to _not_ be a dict, while that seems to be exactly what it's supposed to be.
This fixes issue https://github.com/mesonbuild/meson/issues/14089
=> Fixes issue 14089 (detection of Intel compiler)

mesonbuild/mtest.py, test cases/unit/124 interactive tap/meson.build, test cases/unit/124 interactive tap/script.py, unittests/allplatformstests.py
When running tests with `--interactive` we don't redirect stdin, stdout or stderr and instead pass them on to the user's console. This redirect causes us to hang in case the test in question needs parsing, like it is the case for TAP output, because we cannot read the process's stdout.
Fix this hang by not parsing output when running in interactive mode.
=> test: fix hang when running tests that need parsing with `--interactive`

mesonbuild/compilers/detect.py, mesonbuild/compilers/rust.py, mesonbuild/modules/rust.py
This makes the following adjustments:
- update the error message check for an invalid --rust-version
- pass --rust-edition if the rust edition is not "none"
- pass --rust-verison=nightly if we have a nightly compiler
This also fixes a related bug where we don't strip suffixes from the rustc version from the short version. We fix this by setting the `full_version` with the suffix (something full_version is meant for), and just the `X.Y.Z` is in the `version`. We also store the nightly and beta information so we can make use of that elsewhere, like in the rust module.
Fixes: #14299
=> Rust: Update bindgen handling for changes in bindgen 0.71

mesonbuild/backend/backends.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/mixins/islinker.py, mesonbuild/coredata.py, mesonbuild/mconf.py, mesonbuild/mintro.py, mesonbuild/modules/__init__.py, mesonbuild/options.py, unittests/optiontests.py
This is all pretty straight forward stuff I pulled out of other work I was doing. there's a few typing cleanups, some dead code removal and one case of moving a method that's only used in unittests to a helper function in the unittest module.
=> Cleanups after the option refactor

test cases/python/4 custom target depends extmodule/blaster.py
We check to see if a test extension exists, and if so add its path to sys.path... immediately before unconditionally importing it, obviously.
This raises the question: why bother checking? Can it ever fail? What if it does fail, do we simply not add path entries and then expect the rest of the test file to work??? The whole thing seems silly and useless.
In fact it can fail, if the python interpreter and/or standard library is broken. This is the case for the initial release of PyPy 3.11, in which `'*tachyon*'` fails to glob correctly (and `'tachyon*'` would work, funnily enough -- this is valid too for our use case although still just as pointless).
Delete the useless check. It's technically correct to delete it, and it *also* works around the PyPy breakage as a bonus.
Closes: …
=> tests: work around broken PyPy globbing by removing inert code

mesonbuild/utils/universal.py
Trying to chmod a symlink results in trying to chmod the file or directory it points to, not the symlink itself which has no permissions. Either a symlink points to within the tree we're making writable in which case it'll be handled eventually by os.walk() or it points outside of the tree we're making writable in which case we don't want to touch it. Let's avoid touching files outside of the tree by simply skipping symlinks in _make_tree_writable().
=> Skip symlinks in _make_tree_writable()

mesonbuild/backend/ninjabackend.py, test cases/swift/13 file name matches module name/Library.swift, test cases/swift/13 file name matches module name/Library2.swift, test cases/swift/13 file name matches module name/main.swift, test cases/swift/13 file name matches module name/meson.build
If you have a library target such as `static_library('Foo', 'Foo.swift', '...')` and link it to another target, swiftc will crash.
> SwiftDriverExecution/MultiJobExecutor.swift:207: Fatal error: multiple producers for output .../Foo.o: Wrapping Swift module Foo & Compiling Foo Foo.swift
Two problems here:
- The .swiftmodule output target unintendedly also outputs the .o files compiled by the real compile target (it includes the argument -c via get_compile_only_args() which outputs .o files).
- The combination of -g -emit-module outputs a {modulename}.o for some reason.
This takes away -c -g from the module target command to fix both of these.
=> Fix Swift targets with same module name as source file name

mesonbuild/coredata.py, mesonbuild/options.py
OptionKey objects are used extensively. We want them with a simple API, but they also need to be optimized to not compromise meson performances.
Since this is an immutable object, it is possible to cache the OptionKey object creation. We need to do it using the __new__ to make the caching mechanism transparent.
Fixes #14245
=> Add cache to OptionKey

mesonbuild/compilers/compilers.py, mesonbuild/envconfig.py, mesonbuild/environment.py, mesonbuild/machinefile.py, run_mypy.py
Not too much here, mostly just asserts because of potentially code returning unions where we have a pretty good idea of what the type is.
=> Make the Environment module fully type safe

docs/markdown/Gnome-module.md, mesonbuild/modules/gnome.py, test cases/frameworks/7 gnome/gir/meson.build
Add the support for the doc-format argument if g-ir-scanner supports it.
Ignore the argument otherwise as this is a no-op in such cases.
=> modules/gnome: Allow to specify the doc-format argument

mesonbuild/arglist.py
This speeds up the target generation of QEMU, which is very slow.
* Before: 41 seconds (total time 174 seconds)
* After: ~~29~~ 21 seconds (total time ~~150~~ 134 seconds)
=> Speedup arglist

mesonbuild/options.py
As a cleanup, this causes the cache to use the same tuple layout that the `_to_tuple` method does, which makes it easier to ensure everything is right.
=> options: Fix nullability of OptionKey.subproject

mesonbuild/msetup.py, unittests/platformagnostictests.py
This is just a bad warning, while it *could* give the user useful information, it often doesn't since it can get values to warn about from:
- environment variables
- the command line
- machine files
- `project(default_options : ...)`
- `subproject(default_options : ...)`
- `dependency(default_options : ...)`
The problem of course is that user may have no control over these values. 3 of them are hardcoded into the meson.build files, so the user can't do anything about them. And there are legitimate reasons to have unused values in those, like setting defaults for a language only used on specific platforms.
Environment variables may be set by the distro (NixOS sets them for any enabled language, so just having a D compiler causes `DFLAGS` to be set, for example). They likely don't want to …
=> msetup: remove bad warning about unused options

mesonbuild/coredata.py
This should be `(key, value, is_first_invocation)`, but is instance `(key, is_first_invocation, value)`
=> coredata: fix arguments that are swapped

mesonbuild/coredata.py, test cases/linuxlike/3 linker script/meson.build
Which was improperly updated by the option store refactor.
Fixes: #14329
=> coredata: fix handling of prefix

ci/ciimage/opensuse/install.sh, ci/ciimage/ubuntu-rolling/install.sh, mesonbuild/dependencies/dub.py, test cases/d/11 dub/meson.build, test cases/d/17 dub and meson project/.gitignore, test cases/d/17 dub and meson project/dub.json, test cases/d/17 dub and meson project/dub.selections.json, test cases/d/17 dub and meson project/meson.build, test cases/d/17 dub and meson project/multi-configuration/.gitignore, test cases/d/17 dub and meson project/multi-configuration/dub.json, test cases/d/17 dub and meson project/multi-configuration/dub.selections.json, test cases/d/17 dub and meson project/multi-configuration/source/app.d, test cases/d/17 dub and meson project/source/app.d, test cases/d/17 dub and meson project/x/y/z/dub.json, test cases/d/17 dub and meson project/x/y/z/dub.selections.json, test cases/d/17 dub and meson project/x/y/z/meson.build, test cases/failing/133 dub missing dependency/dub.json, test cases/failing/133 dub missing dependency/dub.selections.json, test cases/failing/133 dub missing dependency/meson.build, test cases/failing/133 dub missing dependency/source/app.d, test cases/failing/133 dub missing dependency/test.json
The current approach of determining dub dependencies is by specifying a name and, optionally, a version. Dub will then be called to generate a json summary of the package and code in meson will parse that and extract relevant information. This can be insufficient because dub packages can provide multiple configurations for multiple use-cases, examples include providing a configuration for an executable and a configuration for a library. As a practical example, the dub package itself provides an application configuration and multiple library configurations, the json description of dub will, by default, be for the application configuration which will make dub as a library unusable in meson.
This can be solved without modifying the meson build interface by having dub describe the entire …
=> dependencies/dub: First try to describe local project

mesonbuild/coredata.py, mesonbuild/mesonmain.py, mesonbuild/optinterpreter.py, mesonbuild/options.py, unittests/allplatformstests.py, unittests/datatests.py
This class served two purposes:
- to allow initializing builtin options
- to allow creating argparse arguments from UserOptions
The former function creates a layer of indirection that is difficult to correctly type annotate, and frankly serves as a useless abstraction. The second function can be handled by working directly with the UserOptions and their OptionKeys. This makes the whole function a useless abstraction, and prime to be reaped.
Based on #14321
=> Remove the BuiltinOption class

mesonbuild/build.py, mesonbuild/utils/universal.py
Use lazy_property for get_id(). To avoid touching code all over the place, keep get_id() but make it access the actual lazy property (which will be simply an entry in self.__dict__)
=> Remove get_id() hotspot

mesonbuild/environment.py
this fixes the "frameworks: 15 llvm" tests with llvm 20.1
=> get_llvm_tool_names: add llvm 20

mesonbuild/backend/ninjabackend.py
`ninja clang-tidy` will not work if you are using pch files and have not run a full build yet: the pch files will not yet be built and there is no dependency between the pch targets and the clang-tidy target.
Furthermore, the pch files must be in clang format; if a project uses PCH and they are for e.g. GCC, it will not help to build them before running clang-tidy.  Just skip creating the clang-tidy and clang-tidy-fix targets in that case.
Fixes: #13499
=> Broken clang-tidy{,-fix} targets when precompiled headers are in use

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/interpreter/interpreter.py, mesonbuild/scripts/gtkdochelper.py, mesonbuild/utils/universal.py
pathlib's implementation of Path iteration is expensive; "foo.parents" has quadratic complexity when building it:
return self._path._from_parsed_parts(self._drv, self._root,
self._tail[:-idx - 1])
and comparisons performed by "path in file.parents" potentially have the same issue.  Introduce a new function that checks whether a file is under a path in the same way, removing usage of Path from the biggest hotspot.
=> Remove hot uses of pathlib

mesonbuild/backend/backends.py, mesonbuild/compilers/mixins/clike.py, mesonbuild/coredata.py, unittests/allplatformstests.py
Inspired by #14103, I did some profiling on my project generation, and added some optimisations. The most significant is the _get_file_from_list() that cut generation time from 60 sec to 45 sec on my project.
=> Optimize object filename from source

test cases/d/14 dub with deps/meson.build
Dub is very thorough about what it encodes in a build id even collecting the compiler path. Therefore, if dub is not provided the exact same compiler path that meson got during setup, the dependency would not be found and the test would fail.
=> tests: support DC being more than plain dmd or ldc2

mesonbuild/compilers/detect.py, test cases/cuda/1 simple/test.json
@eli-schwartz I think this would be a candidate for a 1.7.1 backport.
=> Cuda `-Dcuda_link_args=foo` single arg fix

docs/markdown/Gnome-module.md
The behavioral change is there since be1d013453e3df3b83da0c91f5211c822d4da4d7 so align the documentation with what is allowed here.
=> modules/gnome: header argument of generate_gir accepts an array of strings

mesonbuild/dependencies/hdf5.py
The u-config implementation of pkg-config intentionally does not support the `--list-all` option [1]. When trying to build meson using it, this results in hard failure. This functionality is currently only used to find incorrectly named hdf5 pc files, without it just the correctly named files are queried. This patch changes it so that only warning is logged and empty list is returned if the `list_all` method is not successful.
[1]: https://github.com/skeeto/u-config/issues/7
=> hdf5: don't throw if the pkg-config doesn't support --list-all

.github/workflows/msys2.yml
MSYS2 dropped Python 2 in https://github.com/msys2/MINGW-packages/pull/23713
=> ci: stop installing python2 for the msys2 jobs, it's gone

mesonbuild/backend/backends.py, mesonbuild/build.py, test cases/common/42 subproject/meson.build, test cases/common/42 subproject/test.json
We should simply remap these to elide the ../ as it's pretty obviously the natural expectation of using ../ to fetch files from outside the project and then drop them *into* the project.
Monorepos will likely have a single license file (or set) under which the monorepo is licensed. But there will be many components, each of which may use a different build system, which are "standalone" for the most part. We already support this case as long as you build from the monorepo, but the resulting license file gets installed to
```
{licensedir}/../
```
which is silly and unhelpful.
Bug: https://github.com/apache/arrow/issues/36411
=> handle monorepo license files specified in project() via ../

man/meson.1
The man page's discussion of basic `meson` usage in the intro was extremely out of date, suggesting that running `meson` without a command was the same as `meson setup` (despite being deprecated syntax). This PR updates the text to:
- Move the mention of the (deprecated) default command mode down near the end of the page, instead of presenting it right up front.
- <s>Replace instructions to run 'ninja' with 'meson compile' as the build command.<s/>
=> man page: Update basic instructions

.github/workflows/cygwin.yml, unittests/baseplatformtests.py, unittests/linuxliketests.py
Put cygwin filemode tests back under the sourcedir
Remove inheritable permissions from the sourcedir
For :reasons:, the unit tests which check file mode were built in the tempdir.
Instead, remove inheritable permissions from the working directory (which the GitHub VM image has set for some reaons), since they can interfere with getting exactly the file mode you asked for.
Partially reverts 04ae1cfb7999e25f476f84572ff0ad853629346c
=> CI: Fix filemode tests with cygwin 3.6.0

mesonbuild/options.py
Cuts down the spam radically when building with MSVC.
=> options: Make sure the gnu99 deprecation is only printed once

mesonbuild/dependencies/dev.py
Don't hardcode paths in /usr when looking for the GTest sources, as in cross-compile or other builds with a sysroot this will find the host sources, not ones that we want to use in the sysroot.
Closes #12690.
=> dependencies/dev: prepend sysroot when searching for GTest sources

docs/markdown/Unit-tests.md
This PR relocates and spruces up the `meson test --print-errorlogs` documentation originally written in #3809.
=> Fix doc for `meson test --print-errorlogs` [skip ci]

docs/markdown/Builtin-options.md, mesonbuild/linkers/linkers.py
Both dynamic libraries and bundles these days can be dynamically loaded using the dl APIs (e.g. dlopen, dlclose). It is not possible to include bundles on a linker command line as if they were shared libraries, but that's pretty much the only difference.
However, bundles fail the Apple verification for iOS:
2025-02-10 13:54:09.095 ERROR: Validation failed (409) The binary is invalid.
The executable 'Runner.app/Frameworks/numpy._core._operand_flag_tests.framework/numpy._core._operand_flag_tests'
has type 'BUNDLE' that is not valid. Only 'EXECUTE' is permitted.
2025-02-10 13:54:09.096 ERROR: Validation failed (409) Missing load commands.
The executable at 'Runner.app/Frameworks/numpy._core._operand_flag_tests.framework'
does not have the necessary load commands. Try rebuilding the app with …
=> linkers: darwin: do not use -bundle for shared_modules

docs/markdown/Syntax.md
For string path building, if an absolute path is appended, all segments before it are dropped.
This is now clarified in the docs without the reader's having to refer to the obsolete `join_paths()` to understand the example.
=> docs: Clarify string building with absolute paths

mesonbuild/envconfig.py
When users forget to specify the required `endian` parameter in a cross-compilation configuration file, Meson currently throws an unhandled `KeyError` exception. This creates confusion as the error message doesn't clearly indicate what's missing, and instead suggests that this is a Meson bug that should be reported.
Modified the condition check in the `MachineInfo.from_literal` method from:
```python
if set(literal) < minimum_literal:
```
to:
```python
if minimum_literal - set(literal):
```
This ensures that when mandatory fields are missing, users receive a clear error message explicitly stating which fields are missing, rather than encountering an unhandled exception.
Fixes #14385
=> envconfig: fix unhandled exception when cross-file lacks required keys

mesonbuild/mesonmain.py
We have previously updated the python_command handling to correctly detect PyInstaller builds without assuming that it is only Windows, back in commit c39ee881a1959ae37aded8e0c24cec23b2bd6a90. But the fix was incomplete. This affects e.g. running --internal scripts such as symbolextractor.
The issue in this case is slightly more subtle. While sys.executable won't be a valid python so it intuitively falls over quite badly when trying to run it as one, getting the original command is broken in a more interesting way. PyInstaller sets `sys.argv[0]` to the basename of the executable, which then got absolutized to a nonexistent file in the current working directory.
Fixes: https://github.com/mesonbuild/meson/issues/14412
=> select the correct meson_command for pyinstaller builds, even on not-Windows

docs/markdown/snippets/rustdoc.md, mesonbuild/backend/ninjabackend.py, mesonbuild/scripts/rustdoc.py, unittests/allplatformstests.py
Another rust tool, another copy of roughly the same code as clippy and rustfmtb but with slightly different command lines. Other unique points are that the output is in a directory, so print that on successful execution of rustdoc, and that test targets are skipped.
=> rust: new target "ninja rustdoc"

docs/markdown/Rust-module.md, docs/markdown/snippets/rust-test-link-whole.md, mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/cmake/toolchain.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/detect.py, mesonbuild/compilers/rust.py, mesonbuild/dependencies/dev.py, mesonbuild/interpreter/interpreter.py, mesonbuild/interpreter/interpreterobjects.py, mesonbuild/interpreter/kwargs.py, mesonbuild/interpreter/type_checking.py, mesonbuild/linkers/linkers.py, mesonbuild/modules/rust.py, test cases/rust/9 unit tests/doctest1.rs, test cases/rust/9 unit tests/meson.build
Most of the series is refactoring that avoids duplicating the code that creates arguments to rustc. The integration with build.BuildTarget is a bit rust-specific, so I am willing to change things if you guys don't like it.
=> Allow running doctests via rust.doctest()

docs/markdown/Wayland-module.md, mesonbuild/modules/wayland.py
There is no point in printing warning about unstable module, in the
worst case we can just depracate and add new API. It has been tested in
a few projects already, and this warning is a blocker on wider adoption.
=> wayland: Mark module stable

mesonbuild/coredata.py, mesonbuild/environment.py, mesonbuild/mintro.py, mesonbuild/msetup.py, mesonbuild/options.py
Here is another set of cleanups to the option handling code, peeled off of a large set of patches looking into how we handle options. This series is mostly moving code around to more optimal places and better documenting the code to explain what things are for or why something is done.
This code motion does allow some cleanups now (namely by putting the compile base option definitions in the options module), and will allow for more cleanup later.
=> More option cleanups

docs/markdown/snippets/valgrind_test.md, mesonbuild/mtest.py
We currently suggest that users run `meson test --wrapper valgrind`, but this doesn't do what one might expect: Valgrind doesn't error out on violations/issues it detects.
In the past, we had special handling for Valgrind in tests, see 1f76b76a84cb635f764ecbd2b77aaba1d375d72b but it was later dropped in 951262d7590343ffa9730666c427ad9d708a9fb6.
This is similar to what we do for {A,UB,M}SAN_OPTIONS to give sensible behaviour that users expect out-of-the-box.
Note that we're not adding --exit-on-first-error=yes here, as there may be several issues in an application, or a test may be rather slow, and so on. But --error-exitcode=1 to simply make Valgrind's exit status reflect whether an error was found is uncontroversial.
Bug: https://github.com/mesonbuild/meson/issues/4727
Bug: …
=> mtest: set VALGRIND_OPTS to fail tests on errors

docs/markdown/Commands.md
`sort_files` has always defaulted to true.
Fixes #12318.
=> docs: fix default for `meson format` `sort_files` option

docs/refman/templates/notes.mustache, docs/theme/extra/css/notes.css
This PR adds a new documentation theme CSS file (`docs/theme/extra/css/notes.css`) and makes changes to the template which generates admonishment boxes in the Meson documentation (`docs/refman/templates/notes.mustache`), in order to update the styles applied to admonishments and make them more readable.
I don't claim to be a web designer and I'm sure these could be made to look much better, but what I care most about is that the actual contents of the boxes are readable. Now they are, as they share the same styles as the rest of the document.
Fixes: #12328
=> Docs: Cleaner admonishment styling

mesonbuild/compilers/rust.py
Windows toolchains append `.exe` to executables. When cross-compiling on Linux, attempting to run `./rusttest` will not execute the generated `rusttest.exe`.
Fix this by always appending `.exe`, which is a valid filename on all supported platforms. This is what the `CLikeCompiler` class does too.
While reviewing `rust.py`, there are opportunities for improvements and better unification with the rest of the Meson code. However, this commit focuses on fixing cross-compilation with minimal changes.
Fixes: #14374
=> compilers/rust: fix sanity_check for Windows targets

docs/theme/extra/css/notes.css
A followup to #13505, as I'd inadvertently made the headings of the Note/Warning boxes use white text, instead of black as intended. The white text really doesn't work with the blue Note background color.
cc: @jpakkane 
(Sorry about that!)
=> Docs: Set note/warning title color to black text

mesonbuild/cmake/interpreter.py
This is required to resolve ambiguous `LINK_LIBRARIES` passed as bare names.
Context: I'm trying to use SDL3 as a CMake subproject. It links correctly against the `SDL3-shared` target, but with `SDL3-static` it fails to link against system library and framework dependencies on Windows and macOS. Debugging the windows case has lead me here: the `SDL3-static` target has a bunch of windows system libraries listed in `LINK_LIBRARIES` without the `-l` prefix. This case is supposed to be handled in `resolve_cmake_trace_targets()` in the `reg_is_maybe_bare_lib` case, however, it requires the `clib_compiler` argument, which is never passed.
The cmake interpreter code is a very unfamiliar territory for me, so I'm not sure if this is the best way to detect an appropriate compiler.
I'm not sure …
=> cmake: pass clib_compiler to resolve_cmake_trace_targets()

docs/markdown/snippets/rust-objects.md, mesonbuild/backend/ninjabackend.py, mesonbuild/interpreter/interpreter.py, test cases/rust/27 objects/lib1-dylib.rs, test cases/rust/27 objects/lib1.c, test cases/rust/27 objects/lib1.h, test cases/rust/27 objects/lib2.c, test cases/rust/27 objects/lib2.h, test cases/rust/27 objects/main.rs, test cases/rust/27 objects/meson.build
Because rustc does not support extract_objects, QEMU creates a static library
with all the C objects. It then passes this static library as link_whole,
together with another static library containing general purpose utility
functions which is passed as link_with.
However, this is brittle because the two have a circular dependency and
they cannot be merged because of the link_whole/link_with difference.
While lld seems to have the --start-group/--end-group semantics
automatically, ld.bfd can fail if these options are needed. This can
cause difference between distros depending on how Rust is packaged
(e.g. Ubuntu 22.04 and Debian bookworm seem to use ld.bfd).
The simplest solution is for Meson to implement "objects:" properly
for Rust.  Then QEMU can use the same internal dependency objects …
=> Add "objects" support to Rust targets

test cases/d/9 features/app.d, test cases/d/9 features/meson.build
Since dmd frontend version 2.111 integer debug and version statements error during parsing:
https://dlang.org/changelog/2.111.0.html#dmd.deprecation-version-debug-number
This should fix the failing opensuse image build.
=> tests/d: Limit integer debug and version statements

mesonbuild/cmake/interpreter.py, test cases/cmake/28 include directories/main.c, test cases/cmake/28 include directories/meson.build, test cases/cmake/28 include directories/subprojects/cmTest/CMakeLists.txt, test cases/cmake/28 include directories/subprojects/cmTest/include/cmTest.h, test cases/cmake/28 include directories/subprojects/cmTest/src/cmTest.c
Don't add `<project_source_dir>/<subproject>/__CMake_build` directory to include directories.
Fixes #12351
=> cmake/interpreter: Don't add __CMake_build to includes

docs/markdown/Unit-tests.md
We document --wrapper and --wrap works only by expanding it automatically to --wrapper as it is unambiguous.
=> docs: say '--wrapper', not '--wrap' for tests

mesonbuild/ast/introspection.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/cython.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/mixins/clang.py, mesonbuild/compilers/mixins/emscripten.py, mesonbuild/compilers/mixins/gnu.py, mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, mesonbuild/compilers/rust.py, mesonbuild/compilers/swift.py, mesonbuild/coredata.py, mesonbuild/interpreterbase/interpreterbase.py, mesonbuild/mconf.py, mesonbuild/mintro.py, mesonbuild/optinterpreter.py, mesonbuild/options.py, test cases/rewrite/7 prefix/meson.build, unittests/optiontests.py, unittests/rewritetests.py
~based on: https://github.com/mesonbuild/meson/pull/14353 for practical reasons~
This removes the last use of `coredata.set_default_options`, which is only used in the rewriter path after the optionrefactor merge, and is completely broken by that merge. Instead we use the same path that the other interpreters use, so we can completely delete this code.
Closes: #14382
=> Fix rewrite after the option refactor

mesonbuild/dependencies/python.py, mesonbuild/modules/gnome.py, test cases/frameworks/7 gnome/gir/meson-python-sample.c, test cases/frameworks/7 gnome/gir/meson-python-sample.def, test cases/frameworks/7 gnome/gir/meson-python-sample.h, test cases/frameworks/7 gnome/gir/meson.build, test cases/frameworks/7 gnome/meson.build, test cases/frameworks/7 gnome/resources-data/meson.build, test cases/frameworks/7 gnome/test.json
Fixes communicating the RPATH to g-i-scanner in macOS.
See #14169
cc @nirbheek
=> modules/gnome, modules/Python: Allow injecting RPATH flags through LDFLAGS if needed

docs/markdown/i18n-module.md, docs/markdown/snippets/i18n_xgettext.md, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/modules/i18n.py, mesonbuild/utils/universal.py, test cases/frameworks/38 gettext extractor/meson.build, test cases/frameworks/38 gettext extractor/src/lib1/lib1.c, test cases/frameworks/38 gettext extractor/src/lib1/lib1.h, test cases/frameworks/38 gettext extractor/src/lib1/meson.build, test cases/frameworks/38 gettext extractor/src/lib2/lib2.c, test cases/frameworks/38 gettext extractor/src/lib2/lib2.h, test cases/frameworks/38 gettext extractor/src/lib2/meson.build, test cases/frameworks/38 gettext extractor/src/main.c, test cases/frameworks/38 gettext extractor/src/meson.build, test cases/frameworks/38 gettext extractor/test.json
This method call xgettext to extract translatable
string from source files into a .pot translation template.
It differs from a plain CustomTarget in three ways:
- It accepts build targets as sources, and automatically resolves source
files from those build targets;
- It detects command lines that are too long, and writes, at config
time, the list of source files into a text file to be consumed by the
xgettext command;
- It detects dependencies between pot extraction targets, based on the
dependencies between source targets.
This does the specific thing I need for my project, that I was trying to implement in a more generic way in #12272 and #11822.
=> New xgettext method to i18n module

mesonbuild/linkers/linkers.py
Use the custom suffix instead of .dylib in `get_soname_args`, so that executables that are linked to a custom-suffix library can be ran from the build tree.
Fixes: #14470
=> linkers: fix Apple ld -install_name with custom suffix

cross/wasm.txt
This makes it possible to run tests ("1 trivial" passes).
=> add exe_wrapper to the wasm cross file

mesonbuild/minstall.py
As documented in https://docs.python.org/3/library/os.html#os.walk:
> dirnames is a list of the names of the subdirectories in dirpath
> (including symlinks to directories, and excluding '.' and '..')
So currently, we treat any symlink to a directory as a directory instead of as a symlink. In practice, this means symlinks to directories are installed as empty directories instead of as symlinks.
Let's make sure the symlinks are kept intact by checking for symlinks when we iterate over the directory names and treating any symlinks we find as files instead of as symlinks.
=> minstall: Don't treat symlinks to directories as directories in do_copydir()

mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/compilers/rust.py
=> ninjabackend: ensure that native static libraries use Unix-style naming

mesonbuild/linkers/linkers.py
```
$ LDFLAGS="-fuse-ld=lld" meson setup builddir/
[...]
linker = lld_cls(
compiler, for_machine, comp_class.LINKER_PREFIX, override, system=system, version=v)
TypeError: LLVMDynamicLinker.__init__() got an unexpected keyword argument 'system'
```
Fixes regression in commit cece1a7e9992a3bbcc35f90777ba22ba9d62b538. We pass system=system to the linker construction, which worked fine for Apple LLVM LD64 as that inherited `__init__` from DynamicLinker. But non-Apple LLD had an overridden `__init__` which wasn't adapted.
Even if it is thrown away and never used, since LLVM isn't an Apple linker, we still need to obey the argument contract.
=> linkers: fix regression when using lld after iOS changes

docs/yaml/functions/executable.yaml, mesonbuild/build.py, mesonbuild/interpreter/interpreter.py, mesonbuild/interpreter/kwargs.py, mesonbuild/interpreter/type_checking.py, run_project_tests.py, test cases/android/1 exe_type/exe_type.c, test cases/android/1 exe_type/meson.build
This is the idea I've came up with in regards to https://github.com/mesonbuild/meson/discussions/13758
It doesn't do anything regarding application glue right now, as I'm unsure if and how to implement it, but I thought about it some more and belive having it would simplify things quite a bit.
---
By setting android_usecase to `application`, the executable gets actually built as a shared library instead of an executable. This makes it possible to use an application within an android application process.
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7555/
=> android: Added android_usecase kwargs to executable

mesonbuild/mesonmain.py, test cases/unit/128 long opt vs D/meson.build, test cases/unit/128 long opt vs D/meson_options.txt, unittests/allplatformstests.py
`validate_original_args` only checks whether an option is *prefixed* with the name of a built-in option that was also set.  It does not check whether the prefix is the full name of the option specified with -D.  Adding an "=" at the end fixes the test.
Fixes: #14487
=> Fix behavior with options whose prefix is a builtin option name

mesonbuild/dependencies/cmake.py
If CMake fails to find a package, we should log it in `meson-log.txt`, but shouldn't bother the user unless there are details to report.  In addition, we were calling `mlog.warning()` without `fatal=False`, so if `msetup` was called with `--fatal-meson-warnings` we'd fail the entire setup in this case, even for optional dependencies.  Log a notice with `fatal=False` if CMake reported an error, and a debug message otherwise.
Notably, the `even though Meson's preliminary check succeeded` case can occur when a dependency is missing but its `Find*.cmake` is shipped with CMake itself.
Fixes https://github.com/mesonbuild/meson/pull/14216.
=> Log non-fatally if CMake doesn't find a package

docs/markdown/Users.md
We don't want churn with thie list for every project someone creates that uses Meson. Change the intro to say we want notable projects and link to a GitHub search for 'meson.build' files for people who want further examples to consider.
=> docs: users: list is for notable meson adoptees

mesonbuild/backend/backends.py
This PR switches to using an `OrderedSet` to keep track of the directories that will be added in `PATH`. Using an OrderedSet seems the right choice because:
1. We don't want duplicate entries in `PATH`
2. Order really matters
3. While we may use an unordered set for internal deps and an unordered set for external deps, then concatenate at the end, it's best to have deterministic results. Due to that, we also use an `OrderedSet` for the `prospectives`
Fixes #12330
Fixes #14400
=> determine_windows_extra_paths: append external dependencies after internal ones

mesonbuild/interpreter/interpreter.py
Returning the default value for `b_sanitize` now misses the special check for it's handling (as would a feature option, but we don't currently have any builtin options that are features). don't do that.
Fixes: #14501
=> Fix interaction between b_sanitize as array and option refactor

mesonbuild/interpreter/interpreter.py, test cases/unit/125 declare_dep var/meson.build, test cases/unit/125 declare_dep var/meson_options.txt, unittests/linuxliketests.py
If a directory that is passed to declare_dependency is not accessible (a parent has the x permission cleared), this can result in an OSError:
ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
This can cause false positives, for example, if the directory is under /var and root-owned.  Do the is_dir() test last, once it's known that the directory is related to the source directory, to avoid the false positives.
Fixes: #13584
=> avoid false positive PermissionError in declare_dependency

unittests/allplatformstests.py
The unit tests for the `meson test --slice=` option check that the option is working by extracting all tests that have been run from the command output. This is done with a rather loose regular expression "test-[0-9]*", which can easily match other parts of the output, as well.
One user for example reported that the test broke because they were executing tests in a directory called "meson-test-1.8.0-build", and given that the "test-1" part of that directory matches the regular expression we have too many matches.
Fix the issue by tightening the regex so that is way less likely to match anything from the host's build environment.
Reported-by: Dominique Leuenberger <dleuenberger@suse.com>
Fixes https://github.com/mesonbuild/meson/issues/14523.
=> unittests: fix overly loose regex in tests for `--slice=` option

mesonbuild/compilers/compilers.py, mesonbuild/compilers/cs.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/d.py, mesonbuild/compilers/java.py, mesonbuild/compilers/mixins/clike.py, mesonbuild/compilers/rust.py, mesonbuild/compilers/swift.py
The logic for compiler sanity checks is duplicated across all languages. Improve it across the board by introducing a new helper function that handles cross compilation, logging and exception reporting.
=> improve and unify logging for sanity checks

mesonbuild/interpreter/interpreter.py, mesonbuild/options.py, unittests/allplatformstests.py
Not the most surgical way to fix it, but I prefer to have a bigger fix that is conceptually more correct. Setting the backend as early as possible makes the processing of toplevel project and subprojects more similar.
Fixes: #14524
=> Fix backend options

mesonbuild/compilers/cpp.py
libc++ deprecated `_LIBCPP_ENABLE_ASSERTIONS` from version 18. However, the libc++ shipped with Apple Clang backported that deprecation in version 17 already, which is the version which Apple currently ships for macOS. This PR changes the `_LIBCPP_ENABLE_ASSERTIONS` deprecation check to use version `">=17"` on Apple Clang.
I decided to do this by adding a `is_libcpp_enable_assertions_deprecated` method to `ClangCPPCompiler`, whose default behavior is to compare the version against `">=18"`, but which gets overridden by `AppleClangCPPCompiler` to check against `">=17"`. This felt fairly clean to me and avoided hard-coding macOS/Apple specific quirks into the general `ClangCPPCompiler` class.
Fixes https://github.com/mesonbuild/meson/issues/14440.
=> Fix _LIBCPP_ENABLE_ASSERTIONS warning on Apple Clang

docs/markdown/Cross-compilation.md
As of this commit, meson has three different pathways to set an `exe_wrapper` for test binaries.
exe_wrapper set through `meson test --wrapper`
CLI arg or `add_test_setup()` meson function argument are treated equally. One wrapper may be set through either of these mutually exclusive routes at a time.
The exe_wrapper field set in the cross file is handled separately internally in mtest.py. This route is *not* mutually exclusive with the others, and this field has more consequence over meson test behavior that the other two routes do not affect.
When I encountered this behavior in a project, it was very unintuitive to me, so I'm documenting what I see now.
Perhaps a future version of meson should treat these fields equally and explicitly document how they are combined.
For now, I think its …
=> docs: disambiguate exe_wrapper

.github/workflows/macos.yml, mesonbuild/dependencies/python.py
When building for iOS, and Python is a dependency, linking against the Python *framework* is required. This is done [automatically for all the standard library modules](https://github.com/python/cpython/blob/v3.14.0a7/configure.ac#L3459-L3463).
This behavior differs from macOS. On macOS, binary modules are linked with `-undefined dynamic_lookup`; that option is marked as deprecated for the iOS compiler, so it can't be used.
It also differs from Unix platforms that link against libPython - the link must be against the framework, not the library, as iOS doesn't allow "normal" dynamic library linking. As a result, existing `link_libpython` can't be used.
=> Add framework linking for iOS builds.

docs/markdown/CMake-module.md, mesonbuild/modules/cmake.py, test cases/cmake/13 system includes/main2.cpp, test cases/cmake/13 system includes/meson.build
The return value of the include_directories() function from the CMake module is created like this:
dir_node = assign(dir_var, function('include_directories', tgt.includes))
sys_node = assign(sys_var, function('include_directories', tgt.sys_includes, {'is_system': True}))
inc_node = assign(inc_var, array([id_node(dir_var), id_node(sys_var)]))
So it is a list of IncludeDirectories objects, not just one.
=> Fix assertion failure for cmake.include_directories

mesonbuild/dependencies/python.py
In this case, self.raw_link_args is None.
Fixes #14534.
=> dependencies/python: Fix Framework Python when pkg-config is installed

mesonbuild/ast/introspection.py, mesonbuild/build.py, mesonbuild/coredata.py, mesonbuild/interpreter/dependencyfallbacks.py, mesonbuild/interpreter/interpreter.py, mesonbuild/interpreter/type_checking.py, mesonbuild/interpreterbase/decorators.py, mesonbuild/mconf.py, mesonbuild/options.py, mesonbuild/utils/universal.py, unittests/optiontests.py
Fix cases in which `str` was used for values that could actually be any type valid for an option.
Stop going back and forth between lists and dictionaries. Also stop going back and forth between str and OptionKey.
=> Cleanup OptionStore types

mesonbuild/mdist.py
This is already done for bz2 and lzma, but even gzip is not always available in a minimal Python installation. For example, this happens when building Python from source without having zlib available.
Basically, this is the same solution as https://github.com/mesonbuild/meson/pull/6077 but for gzip.
=> mdist.py: Import gzip only when needed

mesonbuild/compilers/cpp.py
Fixes a regression introduced in commit d37d649b08b8 "Make all Meson level options overridable per subproject." This change results in every file printing the warning "cl : Command line warning D9002 : ignoring unknown option '/std:vc++14'"
Now that "get_option_..." is called before overwriting the option (instead of after), we have to operate on compiler options, not meson options.
There is no such compiler option as /std:vc++14 (the meson option vc++xx is split into /std:c++xx for the C++ standard version, and a separate flag that enables Microsoft extensions). Remove the mapping from c++14 to vc++14.
=> cpp: Fix cpp_std=vc++14

cross/ubuntu-armhf.txt, mesonbuild/modules/rust.py
`rustdoc --test` relies on running host binaries, and has no way of wrapping them with Meson's exe_wrapper.  Just skip the doctests in that case.
Fixes: #14583
=> rust: skip doctests when host machine cannot run binaries directly

mesonbuild/mdevenv.py, unittests/allplatformstests.py
On Windows, os.execv spawn the process in background and returns 0. Therefore, it prevents devenv to return proper exit code from the called process. (see https://github.com/python/cpython/issues/63323 for reference.)
The solution is to call subprocess.run instead, on Windows, at the price of keeping the meson python process alive while the devenv subprocess runs.
=> devenv: do not use os.execv on Windows

mesonbuild/compilers/compilers.py, mesonbuild/environment.py, mesonbuild/options.py, unittests/linuxliketests.py
For compatibility with Autotools, CFLAGS is added to the linker command line if the compiler acts as a linker driver.  However, this behavior was lost in commit d37d649b0 ("Make all Meson level options overridable per subproject.", 2025-02-13).
The issue is that LDFLAGS is stored in env.options as (for example) c_link_args, and from that point on it is treated as a machine-file option.  This includes not being able to override it in compilers.get_global_options:
- initialize_from_top_level_project_call places it in pending_options
- add_lang_args passes the right value to add_compiler_option
- add_compiler_option calls add_system_option_internal
- add_system_option_internal fishes the value out of pending_options and ignores what get_global_options provided.
Instead, store the putative …
=> options: restore special behavior of CFLAGS vs. c_args

mesonbuild/coredata.py, mesonbuild/mconf.py, mesonbuild/msetup.py, test cases/common/40 options/meson.build, unittests/platformagnostictests.py
Project options were basically ignored when --reconfigure was passed, because after coredata was loaded nothing was going to look at them. This is because these lines were removed from the initialization of Environment
```
self.options.update(cmd_options.cmd_line_options)
```
Fortunately a fix is easy by reusing the the code that runs for `meson configure`.
Fixes: #14575
=> setup: restore behavior of project options together with --reconfigure

mesonbuild/options.py, unittests/platformagnostictests.py
Trivial patch to avoid a Python exception by doing nothing.
Fixes: #14603
=> Fix --buildtype=custom

mesonbuild/ast/introspection.py, mesonbuild/compilers/detect.py, mesonbuild/coredata.py, mesonbuild/interpreter/interpreter.py, run_project_tests.py
=> Fix IntrospectionInterpreter._add_languages to allow simplifying compiler options

docs/markdown/snippets/vs2010-masm-support.md, mesonbuild/backend/vs2010backend.py, mesonbuild/coredata.py, test cases/windows/21 masm/meson.build
Fix #11653
xrefs: https://github.com/libffi/libffi/pull/746
=> vs2010backend: Initial MASM language support

docs/markdown/Builtin-options.md
Hi @eli-schwartz,
Perhaps adding this note to the docs would be helpful to avoid user's confusing debug/non-debug builds with the setting of the NDEBUG macro.   Feel free to merge or reject this PR as you think best (or suggest wording changes).
Regards,
Paul
=> docs: Note that debug=false does not define NDEBUG

.github/workflows/msys2.yml, test cases/frameworks/15 llvm/test.json
Due to some recent package splits llvm is no longer installed when clang is installed and the meson test suite was depending on the transitive dependency.
Instead explicitly install llvm in all cases.
=> CI: always install llvm for MSYS2

mesonbuild/wrap/wrap.py, mesonbuild/wrap/wraptool.py
When fetching wrap files and `releases.json`, ask for gzipped data and decompress it if the server obliges.  Wrap files come from GitHub releases, thus from Azure blob storage, and Azure currently doesn't compress these responses.  `releases.json` comes from Git master, and GitHub does support compression there, reducing the response body from ~64 KiB to ~10 KiB. That's a small change in absolute terms, but straightforward to support.
=> wrap: Support gzip Content-Encoding when fetching WrapDB metadata

mesonbuild/compilers/compilers.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/mixins/clike.py, mesonbuild/compilers/mixins/emscripten.py, mesonbuild/compilers/vala.py, mesonbuild/dependencies/cuda.py, test cases/cuda/10 cuda dependency/modules/meson.build, test cases/cuda/11 cuda dependency (nvcc)/modules/meson.build, test cases/cuda/12 cuda dependency (mixed)/meson.build, unittests/internaltests.py
* cuda: avoid `-l` arguments for linking
When trying to pick between a CUDA library that has both shared and static libraries and the same basename, e.g. `libnvidia-ml.a` and `libnvidia-ml.so`, it becomes impossible to pick a specific variant with `-l` arguments.
* cuda: look for stubbed libraries too
Some libraries in CUDA are stubbed out to load the actual implementation from the driver at runtime. One example is NVML, that only exists in `stubs/`.
Ensure that the stubs dir is searched last, like FindCUDAToolkit.cmake:
https://github.com/Kitware/CMake/blob/4f2482700b6a6231c697b1178239acf76955bfeb/Modules/FindCUDAToolkit.cmake#L1163-L1173
=> Multiple cuda fixes

mesonbuild/msetup.py, mesonbuild/options.py, unittests/optiontests.py
This fixes #14615, which is reported as a 1.8.1 regression but was actually reproducible even  before with `meson configure` (instead of `meson setup --reconfigure`).
It's not trivial fix, though in the end the code becomes almost simpler. The crux of the issue is the disagreement between `OptionStore.validate_cmd_line_options`, `MesonApp.check_unused_options` and `OptionStore.set_option_from_string`. Place the desired semantics (mostly those from `check_unused_options`) in a new function so that the three share the same logic.
Fixes: #14615
=> Make configuration accept unknown-but-maybe-valid-in-the-future options

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/modules/gnome.py, mesonbuild/utils/universal.py
This MR aims to update the work made in https://github.com/mesonbuild/meson/pull/4966 to allow (known) custom targets, like Gnome's `glib-mkenums`, to use response files.
I'm setting it as draft because this doesn't completely work on Windows; this is because I cannot find a suitable point in the target lifecycle to convert arguments to response files:
- Doing so in the Gnome module breaks placeholder variables conversion
- Doing so at the Ninja backend level breaks generation altogether (making the `CUSTOM_COMMAND` rule rspable means I have to supply a placeholder to `rsp_content` -- see below)
- Doing so at the generic backend level (either in `as_meson_exe_cmdline` or `get_executable_serialisation`) seems like the wisest choice, however on Windows scripts must go through an …
=> gnome.mkenums: Use rspfiles on Windows when possible

mesonbuild/build.py, mesonbuild/interpreter/interpreter.py, mesonbuild/interpreter/interpreterobjects.py, mesonbuild/interpreter/mesonmain.py, mesonbuild/modules/__init__.py, test cases/native/9 override with exe/subprojects/sub/meson.build
Right now, the set of available methods depends on the type of object returned by find_program. Specifically it fails if you attempt to call version on it, if it was an Executable put there with `meson.override_find_program`.
This also makes it possible that .get_version() can be called on the output of _find_tool by the modules (which is kind of required for #14422 [not really, as the returned value should never be an executable; but the mypy can't know that]).
For now this only uses the version of the subproject that called override_find_program but an additional `version` kwarg for `meson.override_find_program` could be added if required (at least from the Executable side, not sure about ExternalProgram)
=> Allow .version() to be called for overridden executables

mesonbuild/dependencies/ui.py, test cases/frameworks/18 vulkan/meson.build, test cases/frameworks/18 vulkan/meson.options, test cases/frameworks/18 vulkan/test.json
I'm trying to make Vulkan work for GTK on macOS.
On macOS, the Vulkan SDK can be installed in a user's home folder. If not installed system-wide (e.i. in `/usr/local`), Meson is not able to do a proper version check for Vulkan.
The (obsolete) environment variable `VK_SDK_PATH` has to be set, or the `VULKAN_SDK` will not be used at all.
Vulkan version check fails, even if both `VK_SDK_PATH` and `VULKAN_SDK` are set:
```
Dependency vulkan found: NO. Found -1.-1.-1 but need: '>= 1.3'
```
`VULKAN_SDK` can be set without `VK_SDK_PATH`
The include path (based on `VULKAN_SDK`) is now provided to the version-check command, so `vulkan.h` can be found, and a version check can be done.
=> vulkan: Find Vulkan libraries in non-standard locations

mesonbuild/options.py, unittests/optiontests.py
I'm not sure if this is the right fix or too big a hammer, but let's try.
Fixes: #14608
=> options: process project options before machine options

mesonbuild/cmake/common.py, mesonbuild/cmake/toolchain.py
The most egregious cases are Nasm (which needs to be transformed to `ASM_NASM`) and Rust (which is not yet supported by CMake).
Without this change, projects including multiple languages will generate a toolchain file e.g.
```cmake
set(CMAKE_SIZEOF_VOID_P "8")
set(CMAKE_C_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/bin/HostX64/x64/cl.EXE")
set(CMAKE_CXX_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/bin/HostX64/x64/cl.EXE")
set(CMAKE_RUST_COMPILER "C:/Users/Amalia/.cargo/bin/rustc.EXE" "-C" "linker=link")
set(CMAKE_NASM_COMPILER "C:/Users/Amalia/.cargo/bin/nasm.EXE")
```
which will then cause:
```
WARNING: CMake Toolchain: Failed to determine CMake compilers state
-- return code: 1 …
```
=> cmake: Fix toolchain including unsupported languages

run_meson_command_tests.py
This unbreaks commit 59910c437a81b94c72e3cbdfc2c3612fae576d6e.
It kind of maybe appears to fix something but does break it all quite terribly too. Totally random subdirectories of site-packages/ should certainly not be added to PYTHONPATH regardless of anything else as that may include mesonbuild/, leading to `import ast` finding mesonbuild.ast instead...
The underlying issue here is that egg .pth is not loaded from PYTHONPATH at all, which means depending on versions of e.g. setuptools this test may end up solely testing system-installed meson, or fail entirely.  So we can fix this by manually adding eggs specifically.
=> Unbreak "Fix setuptools 49 test. (fixes #7452)"

ci/ciimage/ubuntu-rolling/install.sh, test cases/frameworks/17 mpi/test.json
This is fixed in Ubuntu rolling now and Bionic wasn't affected to
begin with.
Bug: https://bugs.debian.org/1078026
=> tests: don't skip frameworks/17 mpi for auto/pkgconfig

mesonbuild/backend/vs2010backend.py, test cases/windows/25 embed manifest/DPIAware.manifest, test cases/windows/25 embed manifest/meson.build, test cases/windows/25 embed manifest/prog.c
With introduction of dfd8cfbd8d9c VS compile is broken for cases where /MANIFEST:EMBED linker flag is actually used. The fix keeps the default creation of <EmbedManifest> but adopts the same strategy as e3db7af0ea41, that is to scan the link flags for the embed case to decide state is emit 'true' or 'false' for EmbedManifest.
=> vs2010backend: fix EmbedManifest state when /Manifest:Embed is used

mesonbuild/ast/interpreter.py, mesonbuild/ast/introspection.py, mesonbuild/ast/printer.py, mesonbuild/build.py, mesonbuild/interpreterbase/__init__.py, mesonbuild/interpreterbase/baseobjects.py, mesonbuild/mintro.py, mesonbuild/mparser.py, mesonbuild/rewriter.py, run_mypy.py, test cases/rewrite/1 basic/addSrc.json, test cases/rewrite/1 basic/addTgt.json, test cases/rewrite/1 basic/expected_dag.txt, test cases/rewrite/1 basic/info.json, test cases/rewrite/1 basic/meson.build, test cases/rewrite/1 basic/rmSrc.json, test cases/rewrite/1 basic/rmTgt.json, test cases/rewrite/7 tricky dataflow/addSrc.json, test cases/rewrite/7 tricky dataflow/info.json, test cases/rewrite/7 tricky dataflow/meson.build, test cases/unit/120 rewrite/meson.build, unittests/allplatformstests.py, unittests/rewritetests.py
The rewriter and the static introspection tool used to be very broken, now it is *less* broken.
The most important changes are:
1. We now have `class UnknownValue` for more explicit handling of situations that are too complex/impossible.
2. If you write
```
var = 'foo'
name = var
var = 'bar'
executable(name, 'foo.c')
```
the tool now knows that the name of the executable is `foo` and not `bar`. See `dataflow_dag` and `node_to_runtime_value` for details on how we do this.
To test my work I wrote a script that:
1. `git clone`'s a couple of big projects using meson (e.g. systemd).
3. Checks if the outputs of `meson introspect meson.build --targets` and `meson introspect build_folder --targets` are not contradicting each other.
4. Checks if the output of `meson introspect meson.build …
=> Major rewrite of the rewriter and the static introspection tool

mesonbuild/cargo/interpreter.py
@xclaesse, this is a trivial fix for compilation of glib-macros-0.20.4:
```
error[E0405]: cannot find trait `TryFrom` in this scope
--> ../subprojects/glib-macros-0.20.4/src/clone.rs:22:10
|
22 | impl<'a> TryFrom<&'a Ident> for CaptureKind {
|          ^^^^^^^ not found in this scope
|
= note: 'std::convert::TryFrom' is included in the prelude starting in Edition 2021
help: consider importing this trait
|
3  + use std::convert::TryFrom;
|
```
=> cargo: set edition for build machine as well

mesonbuild/backend/ninjabackend.py, test cases/vala/31 generated ui file subdirectory/meson.build, test cases/vala/31 generated ui file subdirectory/subdir/TestBox.ui.in, test cases/vala/31 generated ui file subdirectory/subdir/meson.build, test cases/vala/31 generated ui file subdirectory/subdir/test.gresource.xml, test cases/vala/31 generated ui file subdirectory/test.vala
The code that adds `--gresourcesdir=` arguments to valac based on the source directories of GResource dependencies was incorrect. It added the current target directory to the source path, but the GResource source directories are already relative to the build directory.
Fixes #14646.
=> Vala: Fix GResource source directories

mesonbuild/cmake/interpreter.py, mesonbuild/cmake/tracetargets.py
These were supported for shared libraries, but for static libraries the link_with property was never populated with `LINK_LIBRARIES` or `INTERFACE_LINK_LIBRARIES`.
Fixes #13101
=> cmake: Fix target_link_libraries against project targets

docs/markdown/Reference-tables.md, docs/markdown/snippets/eld-support.md, mesonbuild/compilers/mixins/clang.py, mesonbuild/linkers/detect.py, mesonbuild/linkers/linkers.py, unittests/allplatformstests.py
Qualcomm opensourced their linker recently [https://github.com/qualcomm/eld](https://github.com/qualcomm/eld)
This PR sets eld as the default linker for Qualcomm's Hexagon compiler.
=> Add eld as default linker for Qualcomm Hexagon compiler

mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/backend/vs2012backend.py, mesonbuild/backend/vs2013backend.py, mesonbuild/backend/vs2015backend.py, mesonbuild/backend/vs2017backend.py, mesonbuild/backend/vs2019backend.py, mesonbuild/backend/vs2022backend.py
This should fix #14668, a regression in 1.8.1.
=> backends: do not look at compilers prior to generate()

mesonbuild/backend/ninjabackend.py, mesonbuild/build.py
Two distinct changes here, both bug fixes, only one is a regression though.
1. This was not updated for the option refactor branch (mypy could have caught this)
2. This never checked target overrides, so of `b_lto` was overridden off it would still expect the name to be .ma not .a
=> Fix tasking compiler after option refactor

mesonbuild/backend/ninjabackend.py
This is required to make sure that the generated .gir file actually contains all the information to be used dynamically.
Valac supports this argument since 0.29.3 released in 2015.
Fixes: #14562
=> vala: Pass --shared-library to valac when generating a .gir file

mesonbuild/compilers/fortran.py
- Currently, I am trying to build SciPy for Windows ARM64 using LLVM toolchain v19.1.5(flang-new+clang-cl). SciPy uses meson build setup for building from source.
- Upon building SciPy with LLVM toolchain v19.1.15 using meson, the build fails due to missing static library "FortranRuntime.lib" 
- Flang 19 and newer no longer require these libraries to be explicitly linked, and their presence causes build failures on Windows ARM64 with missing .lib files.
- This patch updates [language_stdlib_only_link_flags()](https://github.com/mesonbuild/meson/blob/4779abbf3eaf41c2893ef74c4d79f5e894af64d7/mesonbuild/compilers/fortran.py#L635) to conditionally add -lFortranRuntime and -lFortranDecimal only for Flang versions < 19. This change enables successful builds of SciPy for win_arm64 using Flang …
=> Fix Flang stdlib linking for LLVM toolchain versions >= 19

mesonbuild/utils/universal.py, test cases/common/14 configure file/CMakeLists.txt, test cases/common/14 configure file/config7.h.in, test cases/common/14 configure file/prog7.c, unittests/allplatformstests.py
- handles offsets between `#` and `cmakdefine` properly
- `#   cmakedefine bla` is completely legal and supported
- handle empty curly braces properly
- ${} emits nothing, as if the variable is missing
- replace regex based cmake logic with proper parser
- its not really possible to implement the cmakedefine stuff properly with regex
=> cmake preprocessing fixes

docs/markdown/Gnome-module.md, mesonbuild/modules/gnome.py, test cases/frameworks/7 gnome/gdbus/meson.build, test cases/frameworks/7 gnome/meson.build
gdbus-docgen supports reStructuredText output since 2.71.1 and markdown since 2.75.2, allow to simply generate it.
=> modules/gnome: Allow to generate markdown and reStructuredText dbus doc

mesonbuild/ast/interpreter.py, mesonbuild/interpreterbase/__init__.py, mesonbuild/interpreterbase/baseobjects.py, test cases/rewrite/7 tricky dataflow/addSrc.json, test cases/rewrite/7 tricky dataflow/info.json, test cases/rewrite/7 tricky dataflow/meson.build, test cases/unit/120 rewrite/meson.build, unittests/rewritetests.py
Without this PR, the rewriter and the static introspection tool crash if `meson.build` contains something like
```meson
if false
foo = not_defined
endif
```
or
```meson
if false
message(not_defined)
endif
```
While it could be argued, that you should not write stuff like this, it raises a `MesonBugException` without this PR, which we have to fix.
Fixes #14667
=> AstInterpreter: Fix crash when dead code references variables that are never assigned

mesonbuild/backend/backends.py, test cases/common/282 test args and depends in path/libs/a/lib_a.c, test cases/common/282 test args and depends in path/libs/a/lib_a.def, test cases/common/282 test args and depends in path/libs/a/meson.build, test cases/common/282 test args and depends in path/libs/b/lib_b.c, test cases/common/282 test args and depends in path/libs/b/lib_b.def, test cases/common/282 test args and depends in path/libs/b/meson.build, test cases/common/282 test args and depends in path/libs/meson.build, test cases/common/282 test args and depends in path/meson.build, test cases/common/282 test args and depends in path/test.c
Add directories in PATH for `depends` like we do for `args`
Fixes https://github.com/mesonbuild/meson/issues/4668
=> Test serialization fixes for macOS, Windows

mesonbuild/compilers/mixins/pgi.py
Based on reports from the users, PGI compilers need an explicit "-o -" on the command line to emit preprocessed output on stdout.  Override the methods in the PGICompiler mixin to add it when output goes to stdout but not when output goes elsewhere.
Fixes: #8400 
Fixes: #13216
=> compilers: pgi: fix preprocessing arguments

.github/workflows/os_comp.yml, mesonbuild/coredata.py, mesonbuild/environment.py, mesonbuild/interpreter/dependencyfallbacks.py, mesonbuild/interpreter/interpreter.py, mesonbuild/msetup.py, mesonbuild/options.py, test cases/common/223 persubproject options/meson.build, test cases/common/223 persubproject options/test.json, test cases/common/247 deprecated option/test.json, unittests/machinefiletests.py, unittests/optiontests.py, unittests/platformagnostictests.py
Global (non-per-subproject) have their own place in the hierarchy of sources for subproject options.
Fixes: #14690.
=> options: global cmdline options must override default_options in subprojects

mesonbuild/modules/gnome.py
I ran into GStreamer's CI being overwhelmed by a 5k long command line to g-ir-scanner. This will help bypass the limitation.
See https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/532
See #6710
(Marking as draft until the upstream MR is merged.)
=> gnome.generate_gir: Use rspfiles on Windows when possible

docs/markdown/snippets/swift_cxx_interoperability.md, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/xcodebackend.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/swift.py, test cases/swift/10 mixed cpp/main.swift, test cases/swift/10 mixed cpp/meson.build, test cases/swift/10 mixed cpp/mylib.cpp, test cases/swift/10 mixed cpp/mylib.h, test cases/swift/11 mixed objcpp/main.swift, test cases/swift/11 mixed objcpp/meson.build, test cases/swift/11 mixed objcpp/mylib.h, test cases/swift/11 mixed objcpp/mylib.mm
Integrating Swift into C++/Objective-C++ codebases is now supported as of Swift 5.9. This PR creates two new test cases and updates the Ninja and Xcode backends to take advantage of this.
Right now, the new test cases only handle calling C++/Objective-C++ functions from Swift. Calling Swift methods from C++/Objective-C++ is still being worked on.
=> Add Swift/C++ interoperability support

mesonbuild/compilers/fortran.py, mesonbuild/compilers/mixins/gnu.py, test cases/fortran/23 preprocess/main.f90, test cases/fortran/23 preprocess/meson.build
Fixes #14695 
This fixes preprocessing in fortran where code uses the concatenation operator. It also fixes preprocessing when compiling with ifx.
Note on the testing:
- ~The test is currently failing as I don't now how to check the output of the compiled program via the project tests.~
- Is it possible to add ifx as a compiler for this test to avoid a regression on this?
Any help or pointers for these notes would be appreciated!
=> compilers-fortran: Fix preprocessing when fortran uses concat operator

mesonbuild/dependencies/misc.py
The check is currently broken as atomic_flag_clear is a macro, not a function. Change it to test linkage instead.
Also test if atomics work with 64-bit types. On certain platforms like MIPS, external libatomic is needed.
=> test 64-bit types for atomic

docs/markdown/Builtin-options.md, docs/yaml/functions/project.yaml, mesonbuild/ast/introspection.py, mesonbuild/interpreter/interpreter.py, mesonbuild/msetup.py, mesonbuild/options.py, unittests/optiontests.py
At least the code becomes (mostly) simpler, as it's now able to handle toplevel and subproject options more uniformly.
Fixes: #14728 
Fixes: #14729
=> Options fixes :'(

mesonbuild/cmake/tracetargets.py
Currently, when using frameworks on MacOS systems, Meson will send the appropriate flags to the linker but fails to pass flags to the compiler, resulting in the headers not being found for the included frameworks.
This patch adds the required "-F{framework}" flag to the compiler options, so that the compiler can find the headers of included frameworks.
See: https://github.com/mesonbuild/meson/issues/14641
=> Add -F compiler flag for included MacOS frameworks

mesonbuild/dependencies/qt.py
The use of `os.path.join` is inserting `\` into the compile_args, which is wrong since qmake outputs `/` even on Windows, and in fact it causes pkgconfig files that depend on qmake dependencies to have `\` path separators, which get resolved as escape sequences.
Use `Path.as_posix()` to avoid this.
=> qt dependency: Don't insert backslashes into cflags on windows

docs/yaml/functions/get_option.yaml, mesonbuild/environment.py, mesonbuild/interpreter/interpreter.py, mesonbuild/mconf.py, test cases/unit/69 cross/crossfile.in, test cases/unit/69 cross/meson.build, test cases/unit/69 cross/nativefile.in, unittests/allplatformstests.py
- allow retrieving build options with `get_option('build.c_args')`
- include `build.` prefix in `meson configure` output
- allow setting build options in machine files with a `build.` prefix (it's deprecated but should not assert)
Fixes: #14788
Fixes: #14789
=> Small option fixes for cross compilation

run_meson_command_tests.py
The test does not actually fail, but the test runner seems to think that if _anything_ gets printed to stderr, that is a failure.
https://nibblestew.blogspot.com/2019/04/an-important-message-for-people.html
=> Add encoding parameter to fix CI.

mesonbuild/coredata.py
We do not use the machine in the dependency key, which means now we could have collisions between host and build dependencies.
=> Fix dependency cache no longer using the correct machine

docs/markdown/Build-options.md, mesonbuild/options.py, unittests/optiontests.py
Meson 1.8.x makes it possible to adjust the value of a yielding option with a subproject-specific augment.  This was an undocumented change  which was (voluntarily) undone in commit eae4efa72 ("options: resolve yielding options at the time they are added", 2025-07-13).
Since it is useful, try to preserve it by reimplementing yielding options: store a link to the parent project option, and undo it if `set_option` overrides it.
Because UserOption lookup now never checks `yielding`, this avoids the issue from #14774 too.
=> Restore 1.8.x behavior of yielding options

docs/markdown/Builtin-options.md, docs/markdown/snippets/rust-dynamic-std.md, mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/rust.py, mesonbuild/linkers/linkers.py, test cases/rust/1 basic/meson.build, test cases/rust/1 basic/test.json
As a first step towards fixing #8828, allow linking Rust bin crates with dynamic libstd.
staticlib crates cannot yet do this, but this can be extended later on; in the meanwhile, this PR creates the API with a minimal implementation.
=> rust: allow linking with dynamic libstd

mesonbuild/backend/ninjabackend.py
This works around an issue in which meson provides absolute paths to rustc, but rustc may do its own dependency resolution and add `-l` flags for the same libs, causing a failure to link. See https://github.com/mesonbuild/meson/issues/14622.
=> Always add libdirs to rustc command

mesonbuild/options.py, unittests/optiontests.py
Ensure that valobj.yielding is cleared for options in the toplevel project. Add a testcase.
This happened due to a misindentation of a statement. `set_from_configure_command` is correct in that it always assigns to `opt.yielding`, `add_project_option` must do the same.
=> fix yielding options in the toplevel project

ci/ciimage/fedora/install.sh, ci/ciimage/opensuse/install.sh
Build hotdoc from the git repository to work around the build failures resulting from C99 incompatibilities.  The issues are already fixed, but the fix has not made it into a release yet.
=> Hack around hotdoc build failures

docs/markdown/snippets/array-flatten.md, docs/yaml/elementary/list.yml, mesonbuild/interpreter/primitives/array.py, test cases/common/56 array methods/meson.build
This allows users to do two things, flatten potentially nested arrays themselves, and, to safely convert types that may be an array to not an array.
```meson
x = [meson.get_external_property('may_be_array)].flatten()
```
```meson
x = ['a', ['b', 'c']]
assert(x.flatten() == ['a', 'b', 'c'])
```
=> interpreter: Add a flatten() method to arrays

docs/markdown/snippets/swift-parse-as-library.md, mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/swift.py, test cases/swift/14 single-file library/main.swift, test cases/swift/14 single-file library/meson.build, test cases/swift/14 single-file library/singlefile.swift, test cases/swift/15 main in single-file library/main.swift, test cases/swift/15 main in single-file library/meson.build, test cases/swift/15 main in single-file library/module.modulemap, test cases/swift/15 main in single-file library/program.c, test cases/swift/15 main in single-file library/program.h, test cases/swift/16 main in multi-file library/main.swift, test cases/swift/16 main in multi-file library/meson.build, test cases/swift/16 main in multi-file library/module.modulemap, test cases/swift/16 main in multi-file library/more.swift, test cases/swift/16 main in multi-file library/program.c, test cases/swift/16 main in multi-file library/program.h, test cases/swift/8 extra args/lib.swift, test cases/swift/8 extra args/main.swift, test cases/swift/8 extra args/meson.build
swiftc adds a main function consisting of top-level statements to objects generated by a swiftc invocation with a single input file, leading to duplicate symbols when linking the final executable (in case of a static library). This argument prevents this from happening, apply it to library targets automatically when the single file is not called main.swift (in order to preserve the behavior if wanted).
=> Add -parse-as-library to Swift library targets

docs/markdown/Fs-module.md, docs/markdown/snippets/fs_suffix.md, mesonbuild/modules/fs.py, test cases/common/220 fs module/meson.build
When iterating over a list of files, it can be convenient to check suffixes. You could already do `fs.name(file).endswith('.txt')`, but `fs.suffix(file) == '.txt'` is just that tiny bit nicer. We also get the invariant `fs.name(file) == fs.stem(file) + fs.suffix(file)`.
=> Add suffix function to the fs module

mesonbuild/build.py, test cases/vala/32 valaless vapigen/clib.c, test cases/vala/32 valaless vapigen/clib.h, test cases/vala/32 valaless vapigen/meson.build, test cases/vala/32 valaless vapigen/test_clib.c
Dependencies should be able to provide headers in its sources, even tho the target which uses the dependency may not use the language that header is for.
A specific example is vala, where C and Vala dependencies share the same name, so in meson they ought to share the same dependency object in order to provide a Vala and/or C dependency depending on who is using it. Doing so right now however fails, if the project of the dependency user doesn't list vala in its used languages, even tho they might just be interested in the C part of the dependency.
=> build/process_compilers: Skip throwing error for headers

run_meson_command_tests.py
In `run_meson_command_tests.py`. Replace it with `pip install .`.
Fixes #14522.
=> Replace deprecated setup.py install command

mesonbuild/modules/pkgconfig.py, test cases/common/283 pkgconfig subproject/meson.build, test cases/common/283 pkgconfig subproject/simple.c, test cases/common/283 pkgconfig subproject/simple.h, test cases/common/283 pkgconfig subproject/subprojects/simple2/exports.def, test cases/common/283 pkgconfig subproject/subprojects/simple2/meson.build, test cases/common/283 pkgconfig subproject/subprojects/simple2/simple2.c, test cases/common/283 pkgconfig subproject/subprojects/simple2/simple2.h, test cases/common/283 pkgconfig subproject/test.json
When giving a dependency object as requires, allow to use the dependency from a subproject (that is an InternalDepdency).
=> modules/pkgconfig: Resolve dependencies in case of an internal dependency

mesonbuild/wrap/wrap.py
Add and test basic support for sftp in wrap-file. The functionality depends on the "sftp" cli tool being installed, and fails with a helpful message if it is not. 
This solution requires any credentials to be supplied in the url, or some other
means of authentication (such as an identity file configured for the
user) to be used.
Mainly for testing purposes, "source_identityfile" can be used to point
out an identity file. Also mainly for testing purposes, "source_hostkey"
can be used to specify a trusted public key for the host.
The test sets up a temporary local ssh server using generated keys (committing them yields complaints from GitGuardian).
=> Support sftp in wrap file

docs/markdown/Commands.md, docs/markdown/snippets/meson-format-stdin-editorconfig.md, mesonbuild/mformat.py
Fixes #14423. Fixes #14538. Fixes #14539.
- Fix parent paths recursion
- Add argument for source file path when reading from stdin
=> Fixes for meson format from stdin using editor config

mesonbuild/dependencies/detect.py, mesonbuild/interpreter/interpreter.py, mesonbuild/interpreter/kwargs.py, mesonbuild/interpreter/type_checking.py, mesonbuild/modules/python.py
This is the second reduced series from https://github.com/mesonbuild/meson/pull/13995.
This small series the function annotations are brought in line with the existing typed_kwargs call, and the dependency kwargs are moved to a shared location so the python dependency can share them.
This also attempts to handle one of the issues that has vexed me about this work, which is keeping a single source of truth for the IR classes. The interpreter provides defaults for all arguments, all the time. We also have defaults in the IR initializers, which means there's a moving source of truth (just look at `CustomTarget`). I've attempted to solve this by using the shared `DEPENDENCY_KWS` to fill in default values for dependency, which gives us a single source of truth. It does lead to a bit of ugly …
=> Share dependency implementation between `dependency` and `python.installation.dependency`

mesonbuild/build.py, test cases/rust/20 rust and cpp/meson.build, unittests/allplatformstests.py
The introspection interpreter sometimes produces targets with no source files; BuildTarget will then pick a random compiler, according to the order in clink_langs.
According to the comment in sort_clink, clink_langs are supposed to list languages from *lowest* to highest priority.  However, process_compilers_late() process clink_langs in straight order and returns the first language; which is the one with lowest priority.
This became visible with the addition of Rust to clink_langs, because Rust has limitation on the names of library targets, but the bug existed before.
Fixes: e49f2f7283e1d9f18e2f5f54647c07287cd70339
=> build: fix introspection interpreter issue when project selects Rust

mesonbuild/compilers/cpp.py
a16ec8b0fb6d7035b669a13edd4d97ff0c307a0b changed the threshold to 17 for Apple Clang, but it needs to be 16 instead.
Bug: https://github.com/mesonbuild/meson/issues/14440
Bug: https://github.com/mesonbuild/meson/issues/14856
=> cpp: handle Apple Clang deprecation of hardening macro in old too

mesonbuild/build.py, test cases/unit/58 introspect buildoptions/meson.build
Fixes another problem with running "meson configure" on Mesa. While "meson configure" never worked on Mesa prior to 1.9.0, this particular issue is a regression.
Cc: @Volker-Weissmann 
Cc: @dlundqvist
Related: #14840
=> rewriter: fix UnknownValues in build targets

mesonbuild/backend/ninjabackend.py, test cases/rust/27 objects/lib1-dylib.rs, test cases/rust/27 objects/meson.build
Fix my misunderstanding of the code before commit aede231ef ("ninjabackend: pass objects to generate_rust_target from non-Rust sources", 2025-07-29).
Object files were added by get_rust_compiler_deps_and_args() to both the main target and the doctest command lines:
```
objs, od = self.flatten_object_list(target)
for o in objs:
args.append(f'-Clink-arg={o}')
deps.append(o)
```
therefore they now need to be passed as the final argument of get_rust_compiler_deps_and_args() for both command lines as well. Failure to do so causes problems building doctests when the main target has objects as well.
Add a regression test as well.
Fixes: #14897
=> ninjabackend: pass objects to doctests

mesonbuild/modules/gnome.py
This is an alternative to #14929, that retains the ability for gir generation during cross compilation.
I did validate, that this manages to properly build `subprojects/gstreamer/gst/Gst-1.0.gir`, where as a checkout of 97c4e9d did fail with `ModuleNotFoundError: No module named 'giscanner._giscanner'`; it might be a good idea for @amyspark to check that it works too.
If this were merged instead of #14929, we'd still need the fix from #14865 in order to prevent unexecutable `ExternalExecutables` from being created due to mismatching architectures.
See #14908
=> Avoid gobject-introspection dependency except if g-ir-scanner is from subproject

mesonbuild/mformat.py
The group_arg_value option allow to put --key and its value on the same line on multiline arguments. However, when the options is `--`, it is an argument separator, and should not be grouped with the following argument.
=> format: do not group '--' arg

mesonbuild/mformat.py, test cases/format/1 default/indentation.meson
Force multiline arguments when there is a trailing comma. This is the behavior of muon.
Fixes #14721.
=> mformat: force multiline arguments with comma

mesonbuild/scripts/rustdoc.py
--crate-type is accepted by recent versions of rustdoc, but it
is not used by it and not listed in the documentation[1].
Remove it for compatibility with old versions of Rust.
[1] https://doc.rust-lang.org/rustdoc/command-line-arguments.html
=> rustdoc: skip --crate-type option

mesonbuild/modules/external_project.py, mesonbuild/scripts/externalproject.py
If an error occurs during an autoconf subproject call on CI, then only "See logs: < path to log> " is printed - which makes it a bit hard to analyze the problem. With this PR, the full content of the log file is printed instead.
=> Print external project logfile on CI systems

test cases/common/32 has header/meson.build
Can be tested with adding `-stdlib=libc++` to C++ flags.
```
In file included from /usr/include/c++/v1/stdio.h:93:
In file included from /usr/include/c++/v1/__config:14:
In file included from /usr/include/c++/v1/__configuration/abi.h:15:
/usr/include/c++/v1/__configuration/platform.h:35:7: error: function-like macro '__has_include' is not defined
35 | #  if __has_include(<features.h>)
|       ^
/usr/include/c++/v1/__configuration/platform.h:48:5: error: function-like macro '__has_include' is not defined
48 | #if __has_include(<picolibc.h>)
|     ^
1 warning and 2 errors generated.
'
```
=> test cases/common/32 has header: disable undef with libcxx

docs/markdown/Installing.md, mesonbuild/modules/gnome.py
I don't really know anything about these vala vapi files but I suspect this is the correct install tag for this file.
=> gnome: Add missing install tag for vapi .deps file

mesonbuild/backend/vs2010backend.py, mesonbuild/cmake/interpreter.py, mesonbuild/cmake/toolchain.py, mesonbuild/compilers/detect.py, mesonbuild/compilers/mixins/visualstudio.py, mesonbuild/envconfig.py, unittests/failuretests.py
Hi all,
This PR is to enable compatibility between ccache and MSVC. ccache has been for a long time compatible with MSVC (since 4.6) but when using debug mode, the /Z7 flag must be passed instead of /Zi. See https://ccache.dev/releasenotes.html#_ccache_4_6.
Some questions arise:
- should we check that ccache >= 4.6 before accepting the entry?
- is there a corresponding sccache version we should check for?
I verified Meson made 100% cachable builds with the GStreamer monorepo:
```ini
[options]
libnice:tests = disabled
libnice:examples = disabled
libnice:gupnp = disabled
openh264:tests = disabled
pygobject:tests = false
python = disabled
libav = disabled
ugly = enabled
bad = enabled
devtools = enabled
ges = enabled
rtsp_server = enabled
sharp = disabled
rs = disabled
gpl = enabled …
```
=> compilers: Enable out-of-the-box MSVC compatibility with ccache

mesonbuild/dependencies/pkgconfig.py, run_project_tests.py, run_tests.py
Add `extra_paths` to cache keys for `PkgConfigInterface` and `PkgConfigCLI` instances, to avoid incorrectly reusing an instance with a different `extra_paths` value, see:
https://github.com/mesonbuild/meson/pull/14657#discussion_r2320623799
=> pkgconfig: Fix class cached to be keyed on extra_paths

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/utils/universal.py, test cases/rust/27 objects/lib1-dylib.rs, test cases/rust/27 objects/meson.build
If a dependency includes object files, they have to be added to the doctest. However, NinjaBackend was not running flatten_object_list on the doctest.
=> rust: let doctests pick objects from dependencies

mesonbuild/dependencies/cuda.py
#fix https://github.com/mesonbuild/meson/issues/14981
It adds a new function in the cuda target:  `_detect_target_path`.
And it will search the SBSA target path correctly on `aarch64` machines.
Same logic as https://github.com/NVIDIA/cuda-samples/blob/3f1c50965017932fc81e6d94a3fc9e04c105b312/cmake/toolchains/toolchain-aarch64-linux.cmake#L18 
Todo:
=> cuda: Add support for sbsa-linux target

mesonbuild/compilers/mixins/gnu.py
I was hitting this error when using the 1.8.3 release, but for some reason I don't hit this error if I use the latest commit
anyone knows why this would happen?
=> Add eld in GnuLikeCompiler

mesonbuild/scripts/env2mfile.py, unittests/internaltests.py
As with many compilers and other tools relevant to cross-compiling, an executable prefixed with the host architecture's GNU architecture tuple might or might not exist, but if it does exist, we can be quite confident that it's the appropriate executable to use for that host architecture.
Vala's vapigen tool reads GIR XML files that can vary between architectures (for example `GLib-2.0.gir` and `GstAudio-1.0.gir` contain constants that take architecture-specific values), so on Debian it needs to search an architecture-specific location. Accordingly, the `valac (>= 0.56.18-3)` package provides a `${DEB_HOST_GNU_TYPE}-vapigen` script which wraps the vapigen binary and sets appropriate search paths.
Bug-Debian: https://bugs.debian.org/1116552
=> env2mfile: Use a cross vapigen on Debian if available

mesonbuild/backend/ninjabackend.py, test cases/rust/13 external c dependencies/foo.h, test cases/rust/13 external c dependencies/meson.build
If any dependency has "sources" in it, the file from the dependency might end up in the rustc command line.
=> rust: fix detection of main file

mesonbuild/cmake/generator.py
If a given project uses a generator expression that meson does not support it will change the outcome and potentially result in wrong behavior, the user should be aware of that so they can deal with it.
=> cmake: warn about unknown generator expressions

mesonbuild/utils/universal.py
in python boolean subclasses integer so `isinstance(True, int)` passes
this has the unintended side-effect of inserting `True` and `False` during preprocessing.
Raising an exception would break backwards compatibility and could harm projects that make use of this.
Message can very likely be improved.
=> deprecate variable substitution with boolean values

mesonbuild/compilers/asm.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/cs.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/cython.py, mesonbuild/compilers/d.py, mesonbuild/compilers/detect.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/java.py, mesonbuild/compilers/mixins/clike.py, mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, mesonbuild/compilers/rust.py, mesonbuild/compilers/swift.py, mesonbuild/compilers/vala.py, mesonbuild/dependencies/base.py
The goal is to reduce code duplication, and allow each language to implement as little as possible to get good checking. The main motivation is that half of the checks are fragile, as they add the work directory to the paths of the generated files they want to use. This works when run inside mesonmain because we always have an absolute build directory, but when put into run_project_tests.py it doesn't work because that gives a relative build directory.
This work was based on #14758, in which I realized that the implementation of sanity_check for Cuda was less than ideal. This is still not fully ideal, as there's a lot of duplication with `compiles`, but the amount of work required to make `compiles` generic enough for this is large, and I really want to get back to other things, so an …
=> compilers: refactor sanity checking code

mesonbuild/scripts/vcstagger.py
Instead of printing it out into the terminal, among other meson messages.
This is in response to https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/37706
which wrapped the `git` into a whole multi-line `python` call just to do exactly
what this PR does: not show an irrelevant error when building from a tarball.
/cc @dcbaker @eli-schwartz is this something that would be ok to merge into meson, or was there a reason to print that error in the upstream code, and we should instead work around it inside our project?
=> vcstagger: suppress errors when running vcs_tag() outside of a vcs clone (eg. tarball)

mesonbuild/ast/introspection.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/compilers/detect.py, mesonbuild/compilers/mixins/clike.py, mesonbuild/compilers/mixins/emscripten.py, mesonbuild/coredata.py, mesonbuild/dependencies/boost.py, mesonbuild/dependencies/pkgconfig.py, mesonbuild/dependencies/python.py, mesonbuild/environment.py, mesonbuild/interpreter/interpreter.py, mesonbuild/modules/gnome.py, mesonbuild/modules/hotdoc.py, mesonbuild/modules/python.py, mesonbuild/modules/rust.py, mesonbuild/options.py, unittests/allplatformstests.py, unittests/datatests.py, unittests/linuxliketests.py, unittests/optiontests.py
Remove deadcode in coredata.py and options.py after all the options refactoring and cleanup.
Related: #15064
=> Remove dead code related to options

docs/yaml/functions/_build_target_base.yaml
Which have existed for a *long* time, but are only documented in the Vala docs.
=> docs: Add vala_header, vala_vapi, and vala_gir to build_target docs
