mesonbuild/interpreter.py
PR #1955 added implib to known_exe_kwargs, but since PR #2001 it needs to be
in exe_kwargs as well, to avoid 'WARNING: Passed invalid keyword argument
"implib"' when it is used.
=> Fix warning when executable(implib:) is used

mesonbuild/compilers/compilers.py, test cases/common/112 has arg/meson.build
Somewhere around version 3.5.0, clang added
-Wignored-optimization-argument.
We can't add -Werror=ignored-optimization-argument without breaking older
clang (because it would trip unknown-warning-option itself), so collapse
the command line into a simple "-Werror".
See also #755
A version of this commit without the test, because I don't expect the test to be accurate forever (someday clang might start supporting -fpeel-loops, or any other currently unsupported flag I might choose) if you prefer: f3374af443742544c92947eeae213ea001fdcd16
=> Fix detection of clang "optimization arguments"

ciimage/Dockerfile, mesonbuild/dependencies/misc.py, test cases/frameworks/1 boost/extralib.cpp, test cases/frameworks/1 boost/meson.build
There are several components in Boost which must be linked with extra
libraries. Boost Log is one of them and in special circumstances needs
linking with boost_log_setup.
http://www.boost.org/doc/libs/1_64_0/libs/log/doc/html/log/detailed/utilities.html#log.detailed.utilities.setup
This fix covers the case when there is no source file corresponding to
the additional library.
=> Find Boost dep when there is an extra lib to link

mesonbuild/mesonmain.py
ref https://github.com/mesonbuild/meson/issues/1962
This has been causing some packaging issues. [A number of VCS packages fail here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=auracle-git) or [manually clean the build directory meaning they lose out on incremental builds](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rofi-git). While this could be handled by skipping the build step if the directory already exists every package I've seen address this opted to remove the existing directory on the assumption incremental builds aren't supported, as has [at least one package management utility](https://github.com/rmarquis/pacaur/issues/714).
The result is virtually the same during interactive use and if there are no objections getting this out as soon as possible would be …
=> Don't error if build directory is already configured and update instructions

mesonbuild/environment.py
This is a small fix for users of older versions of MSVC like me.  As the comment in the patch says, MSVC version is normally printed on stderr (bizarre, right?), but older versions printed on stdout.  This change checks both before giving up.
=> Fix detection of MSVC 2008 version.

mesonbuild/environment.py
This pull request fixes a bug where meson would attempt to run any `cl.exe` found on the path, regardless of whether it was Microsoft's version or not.
The OpenWatcom toolchain, used for vintage projects, provides its own `cl.exe` implementation that has a paged help text, expect user intervention to page through the help text. `meson` idles waiting for the compiler to finish running, which will never occur as the compiler is waiting for input.
My solution is to never attempt to use the watcom `cl.exe` (or POSIX `owcc`) wrapper if they are found on the path; they are buggy and can interfere with other vendors.
With this fix, I was able to generate a ninja file with `cc`, `gcc`, and `msvc` from the visual studio command prompt without error.
=> Check if Watcom version of cl exists in the path and avoid using it.

mesonbuild/backend/ninjabackend.py, mesonbuild/modules/gnome.py, test cases/csharp/2 library/meson.build
Two simple patches:
- First makes sure that we properly set dependency on generated sources (generators and custom targets results)
- The other makes sure that we do not have wrong, extra `shared-library` set in the gir file
=> Patchset to allow using meson for gstreamer-sharp

ciimage/Dockerfile, mesonbuild/backend/ninjabackend.py, mesonbuild/interpreter.py, test cases/csharp/4 external dep/hello.txt, test cases/csharp/4 external dep/meson.build, test cases/csharp/4 external dep/prog.cs
Avoiding warning about it when it is a well known one.
=> Make cs_args a known argument and handle c# external dependencies

mesonbuild/modules/python3.py, test cases/python3/1 basic/meson.build
Include 'platbase' for stripping the prefix for 'platlib' and 'platinclude'.
This is necessary for installing platform-dependant Python modules such as GI overrides.
=> python3: Fix 'sysconfig_path' for platform-dependant paths

mesonbuild/modules/gnome.py, test cases/frameworks/10 gtk-doc/meson.build
The path returned by `gtkdoc_html_dir()` is wrong(tm) (probably a copy&paste error or typo). This PR fixes that.
=> gnome: Fix typo in gtkdoc_html_dir, so it returns the correct path

mesonbuild/modules/gnome.py
This really resolves #1910 by making it also work in cases where asan
and ubsan are used together via "-Db_sanitize=address,undefined".
(Apparently you also need to keep the order "address,undefined", using "undefined,address" is not accepted by meson - maybe this needs a more general refactoring to accept arbitrary combinations of sanitizers, but this PR at least fixes the immediate issue of not being able to use ubsan and asan together in any Meson project that uses GIR)
=> gnome: Ensure gir always works with asan, even if used together with ubsan

test cases/d/3 shared library/meson.build, test cases/d/4 library versions/meson.build, test cases/d/7 multilib/meson.build, test cases/d/8 has multi arguments/meson.build
A while back, the GDC D compiler didn't have shared library support, but that feature is there now for more than a year. That means it's safe to enable these tests now.
This PR also resolves a few typos.
=> Run all D tests if a recent enough GDC is used

ciimage/Dockerfile, docs/markdown/Dependencies.md, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/misc.py, test cases/frameworks/20 cups/cups_prog.c, test cases/frameworks/20 cups/meson.build
libcups has its own cups-config tool rather than using pkg-config.
This adds support for cups-config, based on pcap-config and
sdl2-config implementations.
This change also includes the unit test case and documentation for
cups dependency object implementation, and libcups2 dep to CI image.
One known package that uses libcups and needs this is
gnome-control-center.
=> add support for cups dependencies

docs/theme/extra/templates/extra_head.html
The W3C validator was complaining about that.
=> Removed duplicate title in doc theme.

mesonbuild/modules/gnome.py, test cases/frameworks/12 multiple gir/mesongir/meson.build
This stops g-ir-scanner from trying to search for the pkg-config file for an internal gir, which won't be available.
=> Use include-uninstalled for internal gir deps.

docs/markdown/Reference-manual.md, docs/markdown/snippets/get-supported-arguments.md, mesonbuild/compilers/compilers.py, mesonbuild/interpreter.py, test cases/common/112 has arg/meson.build
Add a helper for the common pattern of:
```
args_to_use = []
foreach arg: candidate_args
if cc.has_argument(arg)
args_to_use += arg
endif
endforeach
```
Replaced with:
`  args_to_use = cc.filter_arguments(candidate_args)`
=> Add Compiler.filter_arguments()

docs/markdown/Unity-builds.md
This was a little confusing for me when I wanted to try it out. Simply passing `--unity` wasn't enough.
=> --unity flag needs {on,off,subprojects} parameter

mesonbuild/scripts/meson_install.py
When the user does not have permissions to run `selinuxenabled`, a `PermissionError` is raised instead of `FileNotFoundError`.
Closes https://github.com/mesonbuild/meson/issues/2257
=> install: Also ignore PermissionError for selinux

mesonbuild/modules/gnome.py
If we don't do that, the traversal of the sources list to generate the sources file for g-ir-scanner is going to explode with a Python backtrace like this one:
```
File "/usr/lib/python3.5/site-packages/mesonbuild/modules/gnome.py", line 463, in generate_gir
gir_filelist.write(os.path.join(srcdir, s) + '\n')
File "/usr/lib/python3.5/posixpath.py", line 89, in join
genericpath._check_arg_types('join', a, *p)
File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
(funcname, s.__class__.__name__)) from None
```
if the sources list contains a list.
This is the result of commit aeaefce81e91232512e0a56ce6a1a83a14c84bb4.
=> gnome: Flatten the sources for generate_gir()

mesonbuild/interpreter.py, run_unittests.py, test cases/unit/2 testsetups/meson.build
Seems to fix the issue...
Got this by adding environment variable (as a string) to a test setup (and by then using the setup).
=> Fix a stack trace caused by environment variables in test setups.

mesonbuild/mesonmain.py
Now it errors out while displaying the possible options
See: https://bugs.python.org/issue25061 for native support
=> wrap-mode: Make the error output more useful

mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, run_unittests.py, test cases/common/138 include order/ctsub/copyfile.py, test cases/common/138 include order/ctsub/main.h, test cases/common/138 include order/ctsub/meson.build, test cases/common/138 include order/meson.build, test cases/common/138 include order/sub4/meson.build
Custom target include dirs must be overridable by target-specific include dirs otherwise in case of header name collisions, the user has no way to override this behaviour. This is happening right now for gtk+ and graphene when graphene is used via a subproject.
=> backends: Add custom target inc dirs before target inc dirs

mesonbuild/mesonlib.py, test cases/common/87 declare dep/entity/meson.build
Otherwise we might end up with wrapper holders in the `Build` object and pickling will then fail, defeating the purpose of the holder objects.
Closes https://github.com/mesonbuild/meson/issues/2211
=> interpreter: Always flatten when unholding arrays

mesonbuild/interpreter.py, test cases/common/48 test args/copyfile.py, test cases/common/48 test args/meson.build, test cases/common/48 test args/tester.c
Caused by #2236. Also add a test for this.
=> Fix regression in test definitions

mesonbuild/mtest.py
Adding it to the end of PATH means that if an installed instance of a DLL
exists, that would be used instead of the built instance.
Compare with run_exe(), which already gets this right.
=> Add Windows extra_paths to beginning of PATH when running tests

docs/markdown/Gnome-module.md, mesonbuild/modules/gnome.py, test cases/frameworks/7 gnome/gdbus/meson.build
Add new 'docbook' argument which generates Docbook documentation for each D-Bus interface. The docbook argument will be used as prefix in `PREFIX`-NAME.xml pattern, and NAME will be replaced by the D-Bus interfaces.
=> gnome: Docbook generation for gdbus_codegen()

mesonbuild/backend/backends.py, mesonbuild/mtest.py
One might run e.g. a verificator or simulator or some other tool on a generated executable. It should run even if the target is cross built because the "command" is native.
=> An external program is never a "cross test".

mesonbuild/mesonlib.py, run_tests.py
A simple patch which allows to run tests on Haiku. Please review.
=> run_tests.py: skip nice() on Haiku. 

tools/cmake2meson.py
These commits fix various issues with cmake2meson, I encountered.
1.: statements in cmake are case-insensitive. 
So, convert statement names to lower-case, so that the comparisons match
2.: comments in multi-line arguments cause a runtime error
```
set(FOO
arg1
arg3
)
```
3.: variable names are converted to lower-case in set statments, but their usage is not
```
set(FOO_SOURCES foo.c bar.c)
add_executable(foo, ${FOO_SOURCES})
```
Before this commit, this would result in 
```
foo_sources = ['foo.c', 'bar.c']
foo_lib = static_library('foo', FOO_SOURCES)
```
=> cmake2meson improvements

test cases/common/159 reserved targets/meson.build
It's not available on Windows. It was passing in the CI because bash tools are available on AppVeyor by default.
=> tests/common/159: Don't try to run 'echo'

docs/markdown/Compiler-properties.md
hotdoc requires a pipe character for the right edge
=> Fix table in Compiler-properties

mesonbuild/backend/ninjabackend.py
Currently the generation of generator() rules make a mystery out of what it is doing during a build. It would be nice if it was a little more informative.
See build steps 1 through 3 as an example:
```
ninja: Entering directory `build'
[1/12] Generating $out
[2/12] Generating $out
[3/12] Generating $out
[4/12] Linking static target libyasm_static.a.
[5/12] Compiling C object 'yasm_app@exe/src_main.c.o'.
[6/12] Compiling C object 'yasm_shared_app@exe/src_main.c.o'.
[7/12] Compiling C object 'yasm_static_app@exe/src_main.c.o'.
[8/12] Linking target libyasm_shared.so.
[9/12] Linking target yasm_app.
[10/12] Linking target yasm_static_app.
[11/12] Generating symbol file 'yasm_shared@sha/libyasm_shared.so.symbols'.
[12/12] Linking target yasm_shared_app.
```
With the provided patch the log …
=> ninja: Generator is more informative on what it is doing.

mesonbuild/build.py, mesonbuild/interpreter.py, test cases/common/146 C and CPP link/meson.build, test cases/common/146 C and CPP link/sub.c, test cases/common/146 C and CPP link/sub.h
Currently meson only considers what compiler/linker were used by a
Target's immediate sources or objects, not the sources of libraries it's
linked with by the link_with and link_whole keywords. This means that if
given 3 libraries: libA which is C++, libB which is C, and libC which is
also C, and libC links with libB which links with libA then linking libC
will be attempted with the C linker, and will fail.
This patch corrects that by adding the compilers used by sub libraries
to the collection of compilers considered by meson when picking a
linker.
This implementation is recursive, since each Target adds it's parent's
dependencies.
=> Consider compilers used in static_library parents

docs/markdown/Build-options.md, docs/markdown/Unit-tests.md
Mesonconf and mesontest is deprecated and all references of it has been replaced with 'meson configure' and 'meson test'
Came across it when i tested on my own computer and saw
> Warning: This executable is deprecated. Use "meson configure" instead.
I am no meson expert by any means, but it seems valid
=> Replaced references to 'mesonconf' and 'mesontest'

mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/interpreter.py, mesonbuild/mesonmain.py, mesonbuild/modules/__init__.py, mesonbuild/modules/gnome.py, mesonbuild/modules/i18n.py, mesonbuild/modules/modtest.py, mesonbuild/modules/pkgconfig.py, mesonbuild/modules/python3.py, mesonbuild/modules/qt4.py, mesonbuild/modules/qt5.py, mesonbuild/modules/rpm.py, mesonbuild/modules/windows.py, mesonbuild/wrap/wrap.py, mesonrewriter.py, msi/createmsi.py, run_unittests.py, setup.cfg, test cases/common/147 mesonintrospect from scripts/check_env.py
Currently, flake8-compliance is being checked by SideCI, which only regression-tests flake8 compliance.  It only ensures that *new*code passes flake8.
That's kind of an F-U to would-be contributors who want to run do a pre-flight test locally before filing the pull request.  They'll get a screenful of messages from flake8, and they'll have to try to weed through those looking for filename/linenumbers that they changed (or, since we're programmers, run flake8 the upstream, run it on our version, and diff the outputs).
Also, this is just a good thing for the codebase.
OK, the title of the PR lied, just a little bit.  I left 5 complaints from flake8 intact.  For most of them, I could just delete the offending line, but I have a feeling that each is actually a subtle bug that might take a …
=> Bring into compliance with flake8

docs/markdown/Reference-manual.md, mesonbuild/compilers/c.py, mesonbuild/dependencies/misc.py, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, run_project_tests.py, test cases/common/42 string operations/meson.build, test cases/frameworks/19 pcap/meson.build
commit c569ea7c97a2cfcf49f7d3c121a39e519b2726f6
str.strip() can now take a positional argument All the specified characters in the specified argument will be stripped. If unspecified, the old behaviour is used. Includes tests.
commit 6f87f94f5bbe25c913c94a4b23ba18feb143abf4
Add a new compiler method: get_return_value()
This method accepts a single function that takes no arguments and returns a single value which can be a value that can be cast to a 64-bit signed integer, or a string, and returns that value.
Mostly useful for running foolib_version() functions that return the currently-available version of libraries.
commit 0ae03d86b7bc836fc35d0fc692937bdb9cbdabe0
dependencies: Add version detection to pcap
--
The `PcapDependency()` changes are untested on macOS (will test that tomorrow), …
=> Fix pcap dependency, str.strip() now takes an argument, add cc.get_return_value()

mesonbuild/wrap/wrap.py
- fix patch archive never download on some case, fix #2359 
- download package to disk and then do sha256sum, fix #2358 
- Using system wide unzip/tar by default #2355
=> Improve mesonbuild/wrap/wrap.py

mesonbuild/compilers/c.py
=> Linker flag for Windows GUI applications was missing on MSVC.

mesonbuild/interpreter.py, test cases/common/114 multiple dir configure file/meson.build, test cases/common/114 multiple dir configure file/subdir/meson.build
We were adding built files to the list of source files to check for regen. We were also not adding source files to regen when `command:` was used.
Fixes #1865
=> configure_file: Fix infinite loop in some cases

docs/markdown/Reference-manual.md, docs/markdown/snippets/custom-target-index.md, mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/build.py, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/modules/gnome.py, test cases/common/161 index customtarget/gen_sources.py, test cases/common/161 index customtarget/lib.c, test cases/common/161 index customtarget/meson.build, test cases/common/161 index customtarget/subdir/foo.c, test cases/common/161 index customtarget/subdir/meson.build, test cases/failing/60 assign custom target index/meson.build
This allows a CustomTarget to be indexed, and the resulting indexed
value (a CustomTargetIndex type), to be used as a source in other
targets. This will confer a dependency on the original target, but only
inserts the source file returning by index the original target's
outputs. This can allow a CustomTarget that creates both a header and a
code file to have it's outputs split, for example.
The larger detail is that it implements the concept of a protocol, which
is borrowed from python terminology for implementing things like
indexing, adding, etc. It adds the index_protocol which the interpreter
will evaluate for any object that has that method.
Fixes #1470
=> Allow CustomTarget's to be indexed

ci/appveyor-install.bat
This reverts commit 92c2bb75195c054dcdeae09f7d42393856a91748.
This is no longer needed, as a patched ninja is now available from the
standard Cygwin package repository, and prevents me from accidentally
breaking CI when changing things in my personal package repository.
=> Revert "Add an additional Cygwin package repo with patched ninja"

mesonbuild/backend/backends.py, mesonbuild/backend/vs2010backend.py, mesonbuild/build.py, test cases/common/145 whole archive/allofme/meson.build, test cases/common/145 whole archive/exe/meson.build, test cases/common/145 whole archive/exe2/meson.build, test cases/common/145 whole archive/meson.build, test cases/common/145 whole archive/shlib/meson.build, test cases/common/145 whole archive/stlib/meson.build, test cases/common/145 whole archive/wholeshlib/meson.build
Currently sources, generated sources, and objects are considered to be
sources for a target, but link_whole should also fulfill the sources
requirement.
Fixes #2180
=> link_whole should be considered a source for targets

docs/markdown/snippets/wrap-svn.md, manual tests/10 svn wrap/meson.build, manual tests/10 svn wrap/prog.c, manual tests/10 svn wrap/subprojects/samplesubproject.wrap, mesonbuild/wrap/wrap.py
The [Wrap dependency system](Wrap-dependency-system-manual.md) now supports [Subversion](https://subversion.apache.org/) (svn).
This support is rudimentary. The repository url has to point to a specific (sub)directory containing the `meson.build` file (typically `trunk/`). However, providing a `revision` is supported.
=> introduce svn wrap support

mesonbuild/interpreter.py, test cases/failing/61 getoption prefix/meson.build, test cases/failing/61 getoption prefix/subprojects/abc/meson.build, test cases/failing/61 getoption prefix/subprojects/abc/meson_options.txt
They are supposed to be sandboxed after all.
=> Prevent projects from grabbing other projects' options.

mesonbuild/backend/backends.py
this handles the case in which `self.get_target_dir(target)` returns an empty string and os.path.join() appends an additional trailing slash
resolves #2336
not sure if this is an acceptable approach, but thought I would submit for comments.
=> backends: avoid extraneous trailing os.path.sep when joining paths

mesonbuild/build.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/dev.py, mesonbuild/interpreter.py, mesonbuild/mesonlib.py, mesonbuild/modules/gnome.py, run_unittests.py, test cases/frameworks/7 gnome/gir/meson.build
Also add a repr() for all objects used by the interpreter, which is needed because in some places we include them in logs and the output is totally unusable otherwise.
=> Fix GNOME gir generation with lists of dependency lists

docs/markdown/Reference-manual.md
Remove the quote before parens
=> docs: Fix typo

docs/markdown/Reference-manual.md
I think this is more understandable like this.
=> Fix typo and clarify library documentation

mesonbuild/dependencies/dev.py
On LLVM < 4.0 this adds linker arguments like -lm, which we don't want.
Related #2442, 2437
=> llvm: don't add --system-libs

mesonbuild/scripts/gettext.py
If the .po file is missing, it leads to installation error, so better give a way for the developer to easily create one from the template.
=> Create the .po file with the `update_po` subcommand if it doesn't exist

test cases/frameworks/15 llvm/meson.build
Needed on Debian Sid since `--system-libs` is no longer used.
=> Add system dependencies for LLVM test.

msi/createmsi.py
I'm using python 32bit on my windows 64bit machine. The `platform` module reports that my system is a 32bit system which it isn't.. With this patch I can create the msi installer.
=> MSI: Find VC redistributable with python 32bit on windows 64bit

docs/markdown/Users.md
I don't know why the link not is rendered as `<a href` at http://mesonbuild.com/Users.html
=> Link to MesonPorting is not rendered as URL

mesonbuild/modules/gnome.py
Otherwise it's not possible to include some .c samples into the documentation
=> Allow to give source files to GtkDoc by respecting the File class

mesonbuild/modules/pkgconfig.py
Without specifying a custom install directory string, get_custom_install_dir() returns True. So for the `Libs` entry I was getting this:
Libs: -L${prefix}/True -lfoo
Now it behaves as expected:
Libs: -L${libdir} -lfoo
=> Error for Libs in package_config function

docs/markdown/Configuring-a-build-directory.md, docs/markdown/IDE-integration.md, docs/markdown/Precompiled-headers.md, docs/markdown/Reference-manual.md, docs/markdown/howtox.md
This updates references to mesonconf to meson configure. Some references (such as older release notes and deprecation warnings) were left in the documentation.
Fixes #2372
=> Update references from mesonconf to meson configure

mesonbuild/dependencies/base.py, mesonbuild/dependencies/dev.py, mesonbuild/environment.py
This is a smaller slice of the functionality in a larger LLVM pull request I sent. I hope these patches can land in the 0.43.1 stable release, as this bug is already being rather annoying for mesa with fast moving dependencies like libdrm.
=> LLVM: Don't add -L<system path> to link args

mesonbuild/modules/qt.py, mesonbuild/modules/qt4.py, mesonbuild/modules/qt5.py
All the code was duplicated between Qt4 and Qt5 modules. 
This makes easier Qt* module evolutions. I'm not sure Qt4 tools detection is still working everywhere.
The QtBaseModule class can now be cleaned(next commits).
Merging this PR will also break other pending Qt related PR.
=> Factorized Qt4 and Qt5 modules in one base class.

mesonbuild/build.py, test cases/failing/66 string as link target/meson.build, test cases/failing/66 string as link target/prog.c
With executable(), if the link_with argument has a string as one of it's
elements, meson ends up throwing an AttributeError exception:
...
File "/home/lyudess/Projects/meson/mesonbuild/build.py", line 868, in link
if not t.is_linkable_target():
AttributeError: 'str' object has no attribute 'is_linkable_target'
Which is not very helpful in figuring out where exactly the project is
trying to link against a string instead of an actual link target. So,
fix this by verifying in BuildTarget.link() that each given target is
actually a Target object and not something else.
Additionally, add a simple test case for this in failing tests. At the
moment, this test case just passes unconditionally due to meson throwing
the AttributeError exception and failing as expected. However, this test
case will …
=> Raise InvalidArguments when trying to link against strings

docs/markdown/Qt5-module.md, docs/markdown/snippets/qt5-moc_extra_arguments.md, mesonbuild/modules/qt.py, test cases/frameworks/4 qt/manualinclude.cpp, test cases/frameworks/4 qt/manualinclude.h, test cases/frameworks/4 qt/meson.build
This commit adds support for an additional `moc_extra_arguments` keyword.
It becomes especially handy, when `moc`-ed sources conditionally provide
`slots`, depending on compile time macros (i.e. defines).
=> Qt5-Module: Add `moc_extra_arguments` keyword support.

mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/interpreter.py, mesonbuild/modules/__init__.py, mesonbuild/modules/gnome.py, mesonbuild/modules/i18n.py, mesonbuild/modules/qt.py, test cases/common/90 identical target name in subproject/meson.build, test cases/common/90 identical target name in subproject/subprojects/foo/meson.build
namespace run_targets by subproject
Currently, run_target does not get namespaced for each subproject,
unlike executable and others. This means that two subprojects sharing
the same run_target name cause meson to crash.
Fix this by moving the subproject namespacing logic from the BuildTarget
class to the Target class.
=> namespace run_targets by subproject

docs/markdown/Dependencies.md, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/misc.py, test cases/frameworks/21 libwmf/libwmf_prog.c, test cases/frameworks/21 libwmf/meson.build
As said in #2542, libwmf does not use pkg-config but its own script libwmf-config.
=> Add LibWmf as a specified dependency, and associated tests.

docs/markdown/Reference-manual.md, docs/markdown/Unit-tests.md, man/meson.1, mesonbuild/mtest.py
`mesontest` is deprecated, and shouldn't be suggested to users anymore.
=> Remove references to `mesontest`

mesonbuild/coredata.py, mesonbuild/optinterpreter.py
set_value() already does a better job at parsing strings, such as
accepting "True" for a boolean.
This fixes issue #2544
=> coredata: Remove parse_string() method

mesonbuild/environment.py, mesonbuild/mesonmain.py
Unfortunately, `time.time` and file timestamps are not guaranteed to be in sync and due to various kernel caches may be different enough to cause rebuilds to fail [1]. This was masked by older ninja versions that could not read sub-second timestamps.
[1] https://travis-ci.org/mesonbuild/meson/jobs/296797872
=> Dump coredata earlier.

syntax-highlighting/vim/indent/meson.vim
I can't think of a reason to always indent twice inside blocks, and it's kind of annoying to have to manually remove them every time.
Cc: @nirbheek, who wrote that code, in case there was some obscure reason I missed :)
=> vim: remove double indent

docs/markdown/Subprojects.md
I copy-pasted from the example and it didn't work, so went to the reference manual and found out it is `dependencies` instead of `deps` (changed in 2c65b1f).
=> Fix use of deps in docs

mesonbuild/compilers/compilers.py
Auto detection was based on parsing gcc's output so we have to
ensure that it is always 'C'.
=> Fix detection of include dirs with gnu compiler and non US locale

docs/markdown/snippets/llvm-static-linking.md, mesonbuild/dependencies/dev.py, test cases/frameworks/15 llvm/meson.build
This fixes a ciritical bug with LLVM, namely that with LLVM < 3.9 we currently statically link, but for >= 3.9 we dynamically link. That's bad. To fix this I've implemented support for the `static` flag so that users can toggle whether they want static or dynamic linking. On top of that this adds logic to properly handle dynamic linking on LLVM < 3.9 (because llvm-config on those versions can't tell you how to dynamically link).
=> LLVM: Fix dynamic vs statically linking.

mesonbuild/interpreter.py, test cases/common/163 includedir subproj/meson.build, test cases/common/163 includedir subproj/prog.c, test cases/common/163 includedir subproj/subprojects/inctest/include/incfile.h, test cases/common/163 includedir subproj/subprojects/inctest/meson.build
`include_directories` did not contain the subproject source directory when performing compiler checks.  This PR adds a test case and a fix.
=> Fix include_directories handling in subprojects for compiler tests

mesonbuild/dependencies/dev.py
So set it as the first versioned config to check for, and add
llvm-config-6.0 to the list of configs.
It's actually been out since September.
=> llvm: llvm 5.0 is released and the current stable

test cases/frameworks/15 llvm/meson.build
I left a hack patch in a pull request for LLVM, and the result is that
LLVM doesn't link with static builds. The real problem that needed 
to be solved is that some distros have pkg-config for tinfo, other's
don't, so the correct solution is to use cpp_compiler.find_library if 
dependency() fails.
=> llvm: fix static linking

mesonbuild/mconf.py, mesonbuild/mesonmain.py, mesonbuild/mintro.py, mesonbuild/mtest.py, mesonbuild/rewriter.py
Taking mconf for instance:
before:
$ meson configure --help
usage: meson [-h] [-D SETS] [--clearcache] [directory [directory ...]]
after:
$ meson configure --help
usage: meson configure [-h] [-D SETS] [--clearcache] [directory [directory ...]]
=> Print correct command in help message

mesonbuild/interpreter.py
Mesa has 4 build systems currently, set our version in a file called
VERSION, and read that in to each build system to simplify the release
process. For meson this is accomplished by using run_command within the
project() function declaration itself, and with meson <= 0.43.0 this
works fine. Commit 1b0048a7022a89f461cf4d01e7cdbf995bab70f5 makes
scripts that are run through run_command a rebuild dependency, but the
attribute used to store that information is set after the project()
command is processed. This breaks mesa.
The solution is to set that list before calling parse_project.
Fixes #2597
=> Interpreter: ensure build_def_files defined before parse_project()

mesonbuild/modules/gnome.py
It is already used by generate_gir(), and allow to fix nicely https://bugzilla.gnome.org/show_bug.cgi?id=786796
=> gnome: Add include_directories parameter to gtkdoc()

mesonbuild/dependencies/misc.py
BOOST_LIBS could become outdated in future versions, which would result
in dependency('boost', modules : [ 'foo' ], required : false) to fail,
although required was set to false. Therefore turn the exception into
log_fail(). If required was set to true, this will still be caught since
is_found remains False.
This also improves logging by printing all invalid module names instead
of only the first one.
I wanted to disable a part of my build using
```
boost_python_dep = dependency('boost', modules : [ 'python3' ], required : false)
if boost_python_dep.found()
endif
```
for Meson versions before 14e7b0af2.
=> Log instead of raise if Boost module invalid

docs/markdown/snippets/prefix-dependent-defaults.md, mesonbuild/coredata.py, mesonbuild/mesonmain.py, run_unittests.py
Rather than requiring a bit of boilerplate in every meson.build, which is
only documented in a comment in mesoncore.py, use sensible defaults for
sysconfdir, localstatedir and sharedstatedir depending on the prefix.
Fixes #1637
=> Make sysconfdir, localstatedir and sharedstatedir defaults depend on prefix

mesonbuild/modules/qt.py, test cases/frameworks/4 qt/main.cpp, test cases/frameworks/4 qt/mainWindow.ui, test cases/frameworks/4 qt/meson.build
This patch sets the --name option for files processed with
rcc. It generates an additional initialization function,
which can be used with static linking.
Signed-off-by: Markus Theil <markus.theil@tu-ilmenau.de>
=> Qt5-Module: add `name` option to rcc

docs/markdown/Reference-manual.md
Assuming I understood it correctly now; for `dependency()` and `subproject()`, the `default_options` argument can override the defaults in the subproject's `meson_options.txt`.
=> docs: fix description of default_options

mesonbuild/dependencies/misc.py, test cases/python3/2 extmodule/meson.build
fixes mesonbuild/meson#2508
My first PR for meson..
=> Enable get_pkgconfig_variable for python3 dependencies (if pkg-config is used)

docs/markdown/Syntax.md
In CommonMark, there are no backslash escapes in code spans, so only two backslashes in the source document are necessary to produce two backslashes in the output document.
=> Fix literal backslash syntax

docs/markdown/howtox.md
When running ninja scan-build you can use the environment variable
SCAN_BUILD to choose the right executable.
=> Documentation: Add note about SCAN_BUILD

docs/markdown/Reference-tables.md
This aligns this table with the set of values tested for by test case
common/140
=> docs: Add 'cygwin' to reference table for .system()

mesonbuild/modules/pkgconfig.py
The `install_dir` parameter of the libraries can also contain the `prefix` path, which creates wrong library paths in the `.pc` file.
This patch detects if `prefix` is contained in the library path and creates a relative path.
Fixes #2469
=> pkgconfig: Handle prefix in library path

mesonbuild/scripts/meson_install.py
This avoids hundres of warnings like:
Warning no default label for /var/tmp/instroot.hUbtYJ/path/to/some/binary
$DESTDIR is usually set to a temporary path, in which case the path is
unknown to selinux. For that case we could just skip the restorecon
calls.  But sometimes it is used with a path to container. In that
case, most of the time, selinux has no context for that path. But we
can't rule that out somebody added custom context rules for the
container. So let's still call restorecon, but silence the warning.
=> Silence failed restorecon calls when $DESTDIR is set

mesonbuild/interpreter.py
Check if the keyword arguments given to dependency are permitted, as is
done with other functions already.
The list of permitted keyword arguments is taken from the documentation.
=> Check keyword arguments for dependency

mesonbuild/mesonlib.py, test cases/common/16 configure file/config5.h.in, test cases/common/16 configure file/meson.build, test cases/common/16 configure file/prog5.c
This should make the replace faster (at least time complexity wise, practice needs timing). Also this avoids recursive substitutions like:
~~~Meson
c = configuration_data()
c.set('a', '@a@@a@')
configure_file(
input : 'evil.in',
output : 'evil',
configuration : c
)
~~~
where file `evil.in` contains `@a@`.
I don't know if any project depends on recursive substitution, but I hope not.
=> Use re.sub instead of replace loop

docs/markdown/snippets/builtin-python.md, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/backend/xcodebackend.py, mesonbuild/dependencies/base.py, mesonbuild/environment.py, mesonbuild/mesonlib.py, mesonbuild/mesonmain.py, mesonbuild/modules/python3.py, mesonbuild/scripts/regen_checker.py, msi/createmsi.py, run_project_tests.py, run_tests.py, run_unittests.py
When using the MSI installer version, Python might not be available on the current system (or it might be the wrong version). Thus add functionality to run Python scripts with the embedded interpreter.
This is not finished yet. I need to fix all places where `sys.executable` is being used. Just putting this here to run through CI first and to gather comments.
=> Add possibility to run Python scripts with current interpreter

mesonbuild/mesonlib.py, test cases/common/16 configure file/config6.h.in, test cases/common/16 configure file/meson.build, test cases/common/16 configure file/prog6.c
This attempts to address the issues with escaping in configuration files mentioned in #2667.
Specifically,
- The escape character is removed from the output (`\@var@` -> `@var@`)
- Two escapes before `@` inserts a literal `\`
- Escaped `@` no longer prevents next variable from working (`\@random@var@`)
=> Improve escaping in configuration files

mesonbuild/mesonlib.py
Otherwise Python will try to use string decode on the configured file and fail if it contains characters that can't be mapped to the current encoding.
=> configure_file: Compare difference in binary mode

mesonbuild/mparser.py, test cases/common/42 string operations/meson.build
Handle newline escape before double backslash to allow `\\n` to work. There's probably a prettier way to do this.
=> Fix escaping of newlines in string literals

mesonbuild/mesonmain.py
Currently passing a bad combo or array option, providing a non-boolean
to a bool arg, or a host of other things can cause an traceback from a
MesonException, don't do that.
Fixes #2683
=> Don't print traceback when options are invalid

docs/markdown/Dependencies.md, docs/markdown/Reference-manual.md, docs/markdown/snippets/config-tool-variable-method.md, mesonbuild/dependencies/base.py, mesonbuild/dependencies/dev.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/ui.py, mesonbuild/interpreter.py, run_unittests.py, test cases/common/165 config tool variable/meson.build, test cases/frameworks/16 sdl2/meson.build, test cases/frameworks/19 pcap/meson.build, test cases/frameworks/20 cups/meson.build, test cases/frameworks/21 libwmf/meson.build
What I want is to bet able to get the includepath from LLVM. What ended up happening was a lot of refactoring to get there.
This series adds a new ConfigToolDependency class, which acts as a share base class for for config tool dependencies like llvm, wxwidgets, and gnustep. It also allows this class to be used in factory type constructors (like cups and pcap). Among the features this adds is unified argument detection, support for multiple version comparisons, and a unified config-tool method name.
This is based on my previous llvm patches (that are waiting for merge already), because this code allows the LLVMDependency to be simplified further.
=> Add method to get values from config tool based dependency

mesonbuild/modules/qt.py
Depending on the tool (moc, uic, rcc, lrelease), the Qt version
(4.8, 5.7, 5.9) and the distribution (Fedora, debian,...) it seems you
cannot predict which of -v or -version will be supported.
Signed-off-by: Alexis Jeandet <alexis.jeandet@member.fsf.org>
=> [Qt module] Added workaround for qt tools version detection

mesonbuild/compilers/cpp.py
A package i am porting to meson needs c++98, shouldn't this be enough, or is more required?
=> adding C++98 to versions that meson can support as combo options

mesonbuild/mlog.py
At the moment ANSI output is disabled on Windows. This enables it when the `ANSICON` environment variable is set, which [ConEmu does](https://conemu.github.io/en/AnsiEscapeCodes.html#Environment_variable).
Recent versions of Windows 10 have an option to enable ANSI support in command prompts, but detecting it requires [calling Windows API](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences), so it is a bit more involved.
=> Enable ANSI colors on Windows when ANSICON is set

test cases/frameworks/9 wxwidgets/meson.build
'test cases/frameworks/9 wxwidgets' fails to build with clang on Fedora because it needs C++11 enabled.
Full log:
```
[0/1] Regenerating build files.
Version: 0.44.0.dev1
Source dir: /home/jeandet/Documents/prog/meson/test cases/frameworks/9 wxwidgets
Build dir: /home/jeandet/Documents/prog/meson/test cases/frameworks/9 wxwidgets/build
Project name: wxwidgets test
Native C++ compiler: clang++ (clang 4.0.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found wx-config: /usr/bin/wx-config-3.0 (3.0.3)
Wxwidgets version 3.0.3 does not fullfill requirement >=5
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja
[1/2] Compiling C++ object 'wxprog@exe/wxprog.cpp.o'.
FAILED: wxprog@exe/wxprog.cpp.o 
clang++  -Iwxprog@exe -I. …
```
=> [Tests] Minor update for CI on Fedora

mesonbuild/dependencies/base.py, test cases/common/167 external program shebang parsing/input.txt, test cases/common/167 external program shebang parsing/main.c, test cases/common/167 external program shebang parsing/meson.build, test cases/common/167 external program shebang parsing/script.int.in
While finding an external program, we should only split the shebang once since that is what Linux and BSD also do. This is also why everyone uses `#!/usr/bin/env` in their shebangs since that allows you to run an interpreter in a path with spaces in it.
See `man execve` for more details, specifically the sections for interpreter scripts.
Without this, if you install your interpreter in a location with spaces, Meson will mangle the path.
=> dependencies: Fix parsing of shebangs with spaces

docs/markdown/Cross-compilation.md, docs/markdown/snippets/system-wide-cross-files.md, mesonbuild/coredata.py, run_unittests.py
One thing that makes cross compiling with meson a pain is the need for
cross files. The problem is not with cross files themselves (they're
actually rather brilliant in that they allow for a much greater deal of
flexibility than autotools hardcoded paths approach) but that each user
needs to reimplement them themselves, when for most people what they
really want is a cross file that could be provided by their distro, all
they really want is the correct toolchain.
This patch is the first stop to making it easier for distros to ship
their own cross files (and for users to put their's somewhere safe so
they don't get `git clean`ed. It allows the cross files (on Linux and
*BSD) to be stored in home and system paths (~/.local/share/meson/cross,
/usr/share/meson/cross, and …
=> cross: Implement support for loading cross files from system paths

mesonbuild/backend/vs2010backend.py, mesonbuild/backend/vs2017backend.py
This is needed for **Google Test Adapter** to work on VS2017.
Actually, it looks like `buildtype_link_args` always is an empty list so as far as I understand the conditional that I removed was always false before.
The `GenerateDebugInformation` should be in the `Link` segment. At least what I can see from VS2015 and VS2017.
=> VS: Add /DEBUG to linker to generate debug information

docs/markdown/Build-options.md, docs/markdown/snippets/option-array-type.md, mesonbuild/coredata.py, mesonbuild/optinterpreter.py, run_unittests.py, test cases/common/166 array option/meson.build, test cases/common/166 array option/meson_options.txt, test cases/common/47 options/meson.build, test cases/common/47 options/meson_options.txt, test cases/unit/18 array option/meson.build, test cases/unit/18 array option/meson_options.txt
In mesa (using autotools and scons) we take options such as `--enable-dri-drivers=i965,i915,swrast,...`. These options have a *lot* of possible values, so it makes sense to me to carry this pattern over to meson instead of having 30+ options to toggle each driver individually. I'm emulating it with a string type, and splitting, but it's impossible to validate that way.
This option looks just like a combo in meson_options.txt, except that `value` can take a list of options.
On the command line this is passed as a comma separated list of values, with white-space stripped.
=> Add an array type to user options

mesonbuild/compilers/vala.py
As the Vala compiler does not define thread_flags() and
thread_link_flags(), depending on threads in any capacity will cause Meson to
fail.
Fixes #2720.
=> vala: add stubs for thread flag methods

mesonbuild/backend/backends.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, run_unittests.py, test cases/osx/2 library versions/CMakeLists.txt, test cases/osx/2 library versions/meson.build
Basically this steals even more stuff from CMake's implementation:
- pad rpath entry to maximum size
- use absolute paths for rpaths
Still needs to be added:
- version flags (see #2577)
- do the otool magic on install
=> Fix many things have have been slightly broken in OSX

mesonbuild/compilers/c.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/ui.py, mesonbuild/linkers.py, run_tests.py, run_unittests.py, test cases/unit/17 pkgconfig static/meson.build
commit e1f75aa4cdd62706ae9db6f5b416d2dbace8a114:
**dependencies: Convert `/c/foo/bar` paths to `C:/foo/bar`**
MSVC cannot handle MinGW-esque `/c/foo` paths, convert them to `C:/foo`. We cannot resolve other paths starting with `/` like `/home/foo` so leave them as-is so the user gets an error/warning from the compiler/linker.
These paths are commonly found in pkg-config files generated using Autotools inside MinGW/MSYS and MinGW/MSYS2 environments. Currently this is only done for PkgConfigDependency.
commit 79850d991981145fe5271e44fae94afcdade5f5f:
**find_library: Prefer .dll.a and .lib over .dll for shared**
We can't know if the `.lib` is a static or import library, but that's a problem in general too. The only way to figure out if a specific file is an import or a static library is to …
=> Various MSVC library search fixes

mesonbuild/interpreter.py, test cases/common/42 string operations/meson.build
Currently `format_string()` replaces all occurrences of each placeholder in turn. This can lead to wrong results like:
~~~Meson
message('@@0@@ @@1@@'.format(1, 2))
message('@0@'.format('@1@@1@', '@2@@2@', '@3@@3@', 'Meson'))
~~~
This also adds an error if a placeholder index is out of range in the format string -- I don't know if this is a good idea, or if a warning would be better.
=> Fix string format recursive replace

mesonbuild/dependencies/base.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/ui.py, mesonbuild/interpreter.py, mesonbuild/modules/gnome.py, run_unittests.py, test cases/linuxlike/1 pkg-config/meson.build
pkg-config enables to define variables by using the `--define-variable` option. This allows some packages to redefine relative paths, so files can be installed in the same relative paths but under prefix.
This code tries to solve the problem with some GNOME packages, where they generate `D-Bus` services, `systemd` units, `gio` modules, etc.. All of these have in common that the paths where those files have to be located, can be checked on their correspondant `pc` files. However, although those paths are relative to some defined variables, they are pointing to paths in the system, which may cause some issues on installation.
=> dependencies: Allow pkg-config to define variables

mesonbuild/dependencies/misc.py
If many binary packages are installed, pick the one built with the correct
toolset. Fixes #2532
=> Boost: Pick correct version

mesonbuild/backend/backends.py, test cases/common/166 custom target subdir depend files/copyfile.py, test cases/common/166 custom target subdir depend files/meson.build, test cases/common/166 custom target subdir depend files/subdir/dep.dat, test cases/common/166 custom target subdir depend files/subdir/foo.c.in, test cases/common/166 custom target subdir depend files/subdir/meson.build
This is an attempt to fix #2633.
I can't get the unit tests to run locally (looks like it fails due to meson not being on same drive as temp directory), so opening a PR to see what CI says.
=> Fix path for str arguments to depend_files

docs/markdown/Reference-manual.md, mesonbuild/interpreter.py, test cases/common/171 not-found dependency/meson.build, test cases/failing/67 dependency not-found and required/meson.build
Document dependency('', required:false) usage.
Avoid emitting 'Dependency  found: NO'.
=> Document and improve not-found dependency objects (2nd try)

mesonbuild/mesonmain.py, mesonbuild/scripts/commandrunner.py
When trying to run a program and the program is not found mention the error cause explicitly in the error message.
Catch if executing a program fails due to file permissions and raise a proper error. This fixes #2733.
Should meson check for more errors when trying to execute a program and generally fail more gracefully?
=> Improve error handling when failing to execute program.

mesonbuild/mintro.py, run_unittests.py, test cases/common/169 array option/meson.build
c9351ce30c03d107279090da7825096951a705d3 introduced the type as `array`, so mintro should expose it under the same name.
(while at it, rename test 169 to be coherent)
Note that there's one last `stringarray` reference in the code, at [run_unittests.py:1635](https://github.com/mesonbuild/meson/blob/master/run_unittests.py#L1635), which is an unused function. Didn't dig into it more, but I'm guessing there's a call missing from somewhere?
=> Fix `array` type name

docs/markdown/snippets/get_unquoted.md
Grammar is still a bit fractured, but I'm not entirely sure what it's trying to say.
=> Fix typo in release note snippet for get_unquoted

docs/markdown/Reference-manual.md
=> Remove warning about install_subdir() removing target tree

mesonbuild/dependencies/base.py, run_unittests.py
Using `NotImplementedError` throws an ugly traceback to the user which does not print the line number or any other information making it impossible to figure out what's causing it.
Also override it for internal dependencies because `self.name` is `"null"` for them.
Reported by @1ace on IRC.
=> dependencies: Don't use NotImplementedError for invalid methods

.appveyor.yml, mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/build.py, mesonbuild/dependencies/misc.py, test cases/python3/4 custom target depends extmodule/blaster.py, test cases/python3/4 custom target depends extmodule/ext/lib/meson-tachyonlib.c, test cases/python3/4 custom target depends extmodule/ext/lib/meson-tachyonlib.h, test cases/python3/4 custom target depends extmodule/ext/lib/meson.build, test cases/python3/4 custom target depends extmodule/ext/meson.build, test cases/python3/4 custom target depends extmodule/ext/tachyon_module.c, test cases/python3/4 custom target depends extmodule/meson.build
Currently, we only consider the build depends of the `Executable` being run when serializing custom targets. However, this is not always sufficient, for example if the executable loads modules at runtime or if the executable is actually a python script that loads a built module.
For these cases, we need to set `PATH` on Windows correctly or the custom target will fail to run at build time complaining about missing DLLs.
=> custom target: Consider all build depends while serializing

docs/markdown/Dependencies.md, docs/markdown/Reference-manual.md
Meson is able to redefine variables when retrieving them from `pkg-config` dependencies since #2663 was merged.. However, the documentation is missing.
This patch adds documentation for this feature.
=> docs: Add documentation to dependency variables

mesonbuild/compilers/c.py
Use LC_ALL=C in CCompiler.get_library_dirs() to fix wrong results with non English locales. This solution is related to #2564.
Fixes #1945
=> Use LC_ALL=C in CCompiler.get_library_dirs

docs/markdown/Gnome-module.md, mesonbuild/modules/gnome.py
Fixes issue #2770
* mesonbuild/modules/gnome.py (GnomeModule.compile_schemas): Allow the
depend_files kwarg.
* docs/markdown/Gnome-module.md: Add docs for new kwarg (and the only
other one that is permitted).
=> Enable re-compilation of GNOME gschema files if they have changed.

data/syntax-highlighting/vim/syntax/meson.vim
This should have been added in 0.44.0 and wasn't.
=> vim: Add warning function to list of builtins

mesonbuild/dependencies/base.py, mesonbuild/dependencies/dev.py, run_unittests.py
This series fixes inconsistent use of `mlog` methods in the `ConfigToolDependency` class compared to other dependency classes (like `PkgConfigDependency`). It also fixes LLVM printing `config-tool` instead of `LLVM` when searching for that dependency.
=> Small cosmetic cleanups for ConfigTool dependencies and LLVM

mesonbuild/dependencies/dev.py
Because TravisCI adds git-20170101 (or so) to the end of the LLVM
version they install in their default images.
Fixes: #2786
=> dependencies: Also strip git version from llvm version

mesonbuild/scripts/coverage.py
Exclude /usr/lib/llvm-*/include/ from coverage. This is the include directory used by LibClang and LibTooling
=> Exclude llvm/clang lib headers from test coverage

docs/markdown/snippets/if-release.md, mesonbuild/compilers/compilers.py
When set, NDEBUG will be automatically defined for for release builds but
not for other build types.
=> Allow value 'if-release' for b_ndebug project option.

mesonbuild/coredata.py
Array options can receive duplicated values, which can produce errors if case those duplicated values make processing some elements twice when they are expected to be processed only once.
=> Remove duplicated values in array options

mesonbuild/dependencies/misc.py
--libs only gives libs to link with not flags and link path when necessary.
To reproduce the bug, just build "test cases/frameworks/20 cups"  on FreeBSD.
=> [Dependencies] Add --ldflags to cups-config invocation

mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/cs.py, mesonbuild/compilers/d.py, mesonbuild/compilers/fortran.py, mesonbuild/environment.py, mesonbuild/interpreter.py
Fixes issue #2762.
Add full_version variable to class Compiler and selected subclasses. It is passed as named parameter. For selected compilers the first line of `CC --version` is passed to full_version.
When the full_version is given it is printed as an additional version information.
This feature is currently only added to limited set of compilers.
=> Add more version information to compiler

mesonbuild/compilers/compilers.py, run_unittests.py, test cases/unit/11 build_rpath/meson.build, test cases/unit/11 build_rpath/prog.cc
This change should fix linking with clang++ on linux when install_rpath is set.  The problem seems to be that clang expands `-Wl,-rpath-link,` to ['-rpath-link'] instead of ['-rpath-link',''].  This means that the next argument gets eaten by `-rpath-link`, and the next argument happens to be `-lstdc++'.
We avoid this by refusing to add an argument if the path contains only whitespace.
Fixes #2814
=> Fix linking with clang++ on linux if install_rpath.

mesonbuild/modules/gnome.py, test cases/frameworks/10 gtk-doc/doc/foobar-docs.sgml, test cases/frameworks/10 gtk-doc/doc/meson.build, test cases/frameworks/10 gtk-doc/include/generate-enums-docbook.py, test cases/frameworks/10 gtk-doc/include/meson.build
gnome's gtkdoc function does not support content files which are not strings. However, there are situations where files generated by other targets might be needed.
=> gnome.gtkdoc: Add support for non string based content files

mesonbuild/interpreter.py, run_unittests.py, test cases/common/173 default options prefix dependent defaults/meson.build
=> Update prefix-dependent defaults when project(default_options:) changes prefix

mesonbuild/compilers/compilers.py, test cases/objc/6 c++ project objc subproject/master.cpp, test cases/objc/6 c++ project objc subproject/meson.build, test cases/objc/6 c++ project objc subproject/subprojects/foo/foo.m, test cases/objc/6 c++ project objc subproject/subprojects/foo/meson.build
Otherwise we will try to use the objc compiler when linking projects with both objc and C++.
Technically we should use the objc++ linker when doing this, but on most (all?) systems the objc++ linker is `c++`, which is the same as the C++ linker.
Closes https://github.com/mesonbuild/meson/issues/2468
=> compilers: prefer C++ over objc in clink_langs

mesonbuild/environment.py, run_unittests.py
Earlier it would exit with a traceback:
UnboundLocalError: local variable 'out' referenced before assignment
=> compilers: Fix error when objc/objc++ compilers are not found

mesonbuild/compilers/compilers.py
My attempt to fix #2834.
`need_threads` are ignored if the compiler doesn't support `thread_flags`.
=> Ignore threads if not supported by the compiler

mesonbuild/backend/vs2010backend.py, mesonbuild/mesonmain.py
When Visual Studio invokes the REGEN target, only the
VisualStudioVersion environment variable is set and VSINSTALLDIR left
unset. The version checker did not like this state of affairs.
Fixes #2848
=> Fix Visual Studio version detection for the `vs` backend

test cases/windows/5 resources/prog.c
Currently, this test only tries to load a predefined icon, so the resource
compilation and linking can be completely removed from the meson.build and
it still passes.
Change to try to load the icon contained in the resources we compile.
=> Fix test cases/windows/5 resources

mesonbuild/interpreter.py, run_unittests.py, test cases/unit/20 subproj dep variables/meson.build, test cases/unit/20 subproj dep variables/subprojects/failingsubproj/meson.build, test cases/unit/20 subproj dep variables/subprojects/somesubproj/meson.build
If a dep is not found on the system and a fallback is specified, we have two cases:
1. Look for the dependency in a pre-initialized subproject
2. Initialize the subproject and look for the dependency
Both these require version comparing, ensuring the fetched variable is a dependency, and printing a success message, erroring out, etc.
Now we share the relevant code instead of duplicating it. It already diverged, so this is a good thing.
As a side-effect, we now log fallback dependencies in the same format
as system dependencies:
```
Dependency libva found: YES
Dependency libva found: YES (cached)
```
```
Dependency glib-2.0 from subproject subprojects/glib found: YES
Dependency glib-2.0 from subproject subprojects/glib found: YES (cached)
```
=> intrp: Consolidate subproject dep checking and logging

mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/mlog.py, mesonbuild/mparser.py, run_unittests.py, test cases/unit/20 warning location/conf.in, test cases/unit/20 warning location/meson.build
Consolidate warning location formatting, and wire it up in a few more places.
I ended up absorbing the final full-stop into the location formatter, and moving the "This will be an error in future Meson releases." note onto a separate line, to avoid the formatter getting hugely complex, but maybe that's not the best idea.
Groundwork for #2854
=> Consolidate warning location formatting

data/macros.meson
false || { rc=$?; echo $rc; exit $rc } || :
Exits current shell without possibility to prevent that.
=> rpm: print testlog from subshell

ci/appveyor-install.bat, mesonbuild/dependencies/misc.py, run_project_tests.py, test cases/frameworks/1 boost/extralib.cpp
Fix `dependency('boost')` on Cygwin, broken in PR #2824
=> Fix dependency('boost') on Cygwin

mesonbuild/build.py, test cases/common/171 not-found dependency/meson.build, test cases/common/171 not-found dependency/sub/meson.build
Fix BuildTarget.add_deps() to handle class Dependency
Extend test case to cover uses of the not-found dependency object
Fixes #2872
=> Fix a problem when anyone actually tries to use a non-found dependency

mesonbuild/mesonlib.py
ArchLinux meson package installs `wraptool` to `/usr/bin`, so when I try to run it:
```
> wraptool list
File "/usr/bin/wraptool", line 17, in <module>
from mesonbuild.wrap import wraptool
File "/usr/lib/python3.6/site-packages/mesonbuild/wrap/wraptool.py", line 22, in <module>
from .wrap import API_ROOT, open_wrapdburl
File "/usr/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 22, in <module>
from ..mesonlib import Popen_safe
File "/usr/lib/python3.6/site-packages/mesonbuild/mesonlib.py", line 61, in <module>
meson_command = python_command + [detect_meson_py_location()]
File "/usr/lib/python3.6/site-packages/mesonbuild/mesonlib.py", line 28, in detect_meson_py_location
raise RuntimeError(c_fname)
```
That's because `detect_meson_py_location()` …
=> Fix meson location detection from other meson tools

mesonbuild/environment.py
They now are published by the D Language Foundation, and not Digital
Mars. Therefore, their signature has changed slightly.
(We can not check for 'DMD', because that string appears in every
compiler version output to denote the frontend version used by the
compiler).
It would be awesome if this fix could also be added to a recent point release of Meson, to get it out into the wild quickly (it broke quite a few project's CI).
=> d: Detect recent DMD compilers

mesonbuild/interpreter.py
The previous change disallowed any subdirectories for subproject dirs,
and therefore broke a couple of projects making use of that.
This change still prevents people from setting subproject dirs that are
not in the project's source tree, while allowing to specify any path
within the project's directory again.
This fixes the regression described in https://github.com/mesonbuild/meson/issues/2719
=> Allow subproject dirs in subdirectories in the source tree again

mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py
=> Fix MSVC backend crashes when `c_pch` or `cpp_pch` is not an array

mesonbuild/dependencies/base.py
~~~
somelib = dependency( 'somelib', required : false, static : true )
~~~
If the library is found but the static libraries are not, the build process fails even though the dependency is optional. This fixes it.
=> Don't fail if we find an optional dependency but not the required information

mesonbuild/modules/gnome.py, mesonbuild/scripts/gtkdochelper.py
These are patches needed to get GNOME in JHBuild works properly on FreeBSD. They are not specific to any operating system, but it is much likely to get build failure caused by these bugs on FreeBSD than on GNU/Linux distributions.
=> Fix -L order, LDFLAGS, LD_LIBRARY_PATH issues in GNOME module

mesonbuild/scripts/meson_exe.py
The output may be a binary data stream, not subject to any locale
encoding. This avoids any encoding errors that might arise as a result.
Also fixes github issue #2868.
=> Avoid worrying about encodings when capturing child program output

data/syntax-highlighting/emacs/meson.el
Add some missing statements to list of keywords
Derive from prog-mode, so any prog-mode hooks are run
Automatically use this mode for meson.build files
[ci skip]
=> A few small improvements to meson.el

mesonbuild/dependencies/misc.py
Otherwise `dependency('boost', modules : [ 'foo' ], required : false)` would wrongly fail (for the case where foo is valid, but not found).
See my previous PR for the invalid case: #2578
=> Log instead of raise if Boost library not found

mesonbuild/dependencies/base.py
I'm not sure this is a good idea, but at the moment it seems a bit too easy
to write something like `dep.get_pkgconfig_variable('inculdedir:')` (sic) and
not notice it's not doing anything useful.
=> Warn about using non-existent pkgconfig variables

mesonbuild/dependencies/base.py, mesonbuild/dependencies/dev.py
It came up today that someone could add some new suffix to what `llvm-config --version` returns. Which is true. So let's not play wack-a-mole anymore, a regex will be much more robust for stripping unwanted suffixes.
=> Make ConfigTool version suffix stripping robust

mesonbuild/modules/pkgconfig.py, run_unittests.py, test cases/common/51 pkgconfig-gen/dependencies/exposed.c, test cases/common/51 pkgconfig-gen/dependencies/internal.c, test cases/common/51 pkgconfig-gen/dependencies/meson.build, test cases/common/51 pkgconfig-gen/meson.build
Currently only not found deps implicitly pulled from a Library object
are ignored. We should also ignore not found deps passed directly to
generate() method.
This makes the unit testing more complicated because libfoo pkgconfig
dependency cannot be found when generated from the within the same
meson.build.
This is a more complete fix for issue #2911
=> pkgconfig: Also ignore not found deps passed directly to pc generator

docs/markdown/Reference-tables.md
The possessive form of "its" does not contain an apostrophe.
=> Fix typo in reference tables

mesonbuild/compilers/c.py, mesonbuild/compilers/cpp.py
The reference manual of meson says `has_argument` method of a compiler object can be used to check whether a compiler flag is supported, but, unfortunately, some projects use it to check linker arguments and they are probably not aware of the wrong results caused by their wrong usage.
Here is a simple example:
```meson
project('test', 'c', 'cpp')
cc = meson.get_compiler('c')
cxx = meson.get_compiler('cpp')
cc.has_argument('-Wl,--hello-world')
cxx.has_argument('-Wl,--verbose')
```
When we use Clang to configure the project, tests always fail.
```
Version: 0.45.0.dev1
Native C compiler: clang50 (clang 5.0.1 "clang version 5.0.1 (tags/RELEASE_501/final)")
Native C++ compiler: clang++50 (clang 5.0.1 "clang version 5.0.1 (tags/RELEASE_501/final)")
Compiler for C supports …
```
=> Print warning when linker arguments are passed to has_argument

docs/markdown/snippets/config-tool-cross.md, mesonbuild/dependencies/base.py
This allows for much easier cross compiler configuration for tools like
LLVM. This patch does honor the 'native' keyword, and falls back to
searching PATH if the binary name is not specified.
I'd be fin with either removing the fallback behavior, or marking it as
deprecated.
Fixes #2921
=> dependencies: Allow setting config-tool binaries in cross file

mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/mesonmain.py, mesonbuild/mlog.py, mesonbuild/mparser.py, run_unittests.py
Examples:
meson.build:2:0: ERROR: Dependency is both required and not-found
meson.build:4: WARNING: Keyword argument "link_with" defined multiple times.
These are already matched by the default compilation-error-regexp-alist in
emacs.
Also:
Don't start 'red' markup until after the \n before an error
Unabsorb full-stop at end of warning with location from mlog.warning()
Update warning_location test
Closes #2854
=> Report warning/error locations in a format IDEs may already know how to parse

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/backend/xcodebackend.py, mesonbuild/build.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/fortran.py, mesonbuild/environment.py, mesonbuild/interpreter.py, mesonbuild/mesonlib.py, mesonbuild/mintro.py, mesonbuild/modules/qt.py, mesonbuild/mtest.py, mesonbuild/scripts/gettext.py, mesonbuild/scripts/meson_install.py, mesonbuild/wrap/wraptool.py
According to [Python documentation](https://docs.python.org/3/library/os.path.html#os.path.split) `dirname` and `basename` are defined as follows:
```python
os.path.dirname() = os.path.split()[0]
os.path.basename() = os.path.split()[1]
```
For the purpose of better readability `split()` is replaced by appropriate function if only one part of returned tuple is used.
=> Use os.path: basename() and dirname() instead of split()

mesonbuild/interpreterbase.py, test cases/common/140 get define/meson.build
This has some breakage potential for existing projects. Should we deprecate instead?
=> Comparing objects of different type is an error. Closes #2870.

mesonbuild/mtest.py
This has been nagging me for a while as I have several long running tests that don't get killed properly when `ctrl-c` is pressed. Please let me know if you'd like anything changed.
=> mtest: catch ctrl-c and properly kill the child processes. Fixes #2281

docs/markdown/Icestorm-module.md, docs/markdown/snippets/fpga.md, docs/sitemap.txt, mesonbuild/interpreter.py, mesonbuild/modules/unstable_icestorm.py, test cases/fpga/1 simple/meson.build, test cases/fpga/1 simple/spin.pcf, test cases/fpga/1 simple/spin.v
This is an alternative approach to FPGA as compared to #2088.
Why a completely different thing? There are several reasons:
- FPGA toolchains are very different as opposed to C compilers which are mostly uniform, defining a "common UI" is trickier
- thus start with a UI for one toolchain and see if that can be expanded
- IceStorm was chosen because it is a 100% free toolchain so we can do CI testing
The main goal here was to come up with how you would specify FPGA projects with the minimal amount of work. In this case:
- user specifies only project name, Verilog sources and constraint file
- we automatically generate synthesis and bitstream
- also add run targets to flash the result and run timing analysis
There are no simulation targets because it is not clear how they work. Since they …
=> IceStorm FPGA experiment

mesonbuild/backend/ninjabackend.py, mesonbuild/interpreter.py, mesonbuild/scripts/meson_install.py
- Pass exclude_files and exclude_directories relative to src_dir,
same as specified by user and documented in public install_subdir().
- Make do_copydir() interface similar to do_copyfile():
install src_dir contents to dst_dir.
- Remove src_prefix/src_dir code, it adds confusion and duplicates arguments.
Use single src_dir parameter instead.
- Make callers specify that src_dir contents should be installed
under dst_dir/basename(src_dir) if necessary.
- Use os.path.relpath() instead of string manipulations on paths.
- Add documentation to do_copydir(): specify types and add usage example.
=> Refactor and simplify install_subdir()

cross/ubuntu-armhf.txt, docs/markdown/snippets/rust-cross.md, mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/rust.py, mesonbuild/environment.py, mesonbuild/interpreter.py, test cases/rust/4 polyglot/meson.build
This patch is largely modeled on the relatively-straightforward code for Fortran cross-compilation, so there might be some intricacies missing.
Also, it's hard to follow what's going on with cross-compilation in the test suite (when I try to invoke it, I just get a bunch of `Generating the build system failed.`), so this has only been tested on my actual projects. I did add the appropriate binary to the cross file that's used for the tests, though.
=> Add cross-compilation support for `rustc`

mesonbuild/build.py, mesonbuild/mesonlib.py
Android's loader doesn't handle shared library versioning so this avoids adding a suffix to the filename or soname for Android hosts.
In particular this let us avoid modifying all of our shared_library() declarations to be like:
```
if compiler.get_define('__ANDROID__') != ''
lib = library('dlib', [ 'dlib/all/source.cpp' ],
cpp_args: defines,
dependencies: deps)
else
lib = library('dlib', [ 'dlib/all/source.cpp' ],
version: '19.7.0',
cpp_args: defines,
dependencies: deps)
endif
```
I haven't looked at creating unit tests yet but can do if this change seems reasonable.
I was guessing I'd add a `'test cases'/android/` directory, which would be considered if running on linux and an `arm-linux-androideabi-clang` toolchain can be found.
Would also need a unit test based on readelf for checking …
=> RFC: Don't version shared libraries for Android

test cases/frameworks/1 boost/linkexe.cc
With the headers from cygwin-devel-2.10.0-1, getpagesize() is not prototyped
unless an appropriate feature test macro is defined.
Future work: investigate if this needs to be defined by
BoostDependency.get_compile_args() or in Boost.
=> Fix boost test on cygwin

mesonbuild/scripts/meson_install.py
Print full destination path in 'Installing subdir ...' message,
including DESTDIR, consistent with other installation functions.
Use separate dst_dir and full_dst_dir variables to avoid mixing up
the order in the future and make code more readable.
Closes #3006.
=> Fix install_subdir() installation message

docs/markdown/Reference-manual.md, mesonbuild/dependencies/base.py, mesonbuild/modules/gnome.py, test cases/linuxlike/1 pkg-config/meson.build
Also use that to squelch the warning for internal uses which handle the
variable missing case (just gnome at the moment)
A follow up to PR #2914
=> Add dep.get_pkgconfig_variable(default:)

docs/markdown/Reference-manual.md, mesonbuild/compilers/c.py
After PR #2662, running test case common/125 shared module/ on Cygwin gets
me:
$ ninja -C _build
ninja: Entering directory `_build'
[7/7] Linking target prog.exe.
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld: warning: --export-dynamic is not supported for PE+ targets, did you mean --export-all-symbols?
Also, fix doc for correct version of first apperance.
Future work: Notwithstanding the hint that ld gives, these options are not
equivalent, and it's not clear we should be using it here:
--export-all-symbols is the default behaviour, and if the exports are
restricted by explicit annotations or a .def file, this option might be
overriding that...
=> Don't use --export-dynamic on Cygwin

data/syntax-highlighting/vim/syntax/meson.vim, docs/markdown/Generating-sources.md, docs/markdown/Reference-manual.md, docs/markdown/Release-notes-for-0.38.0.md, docs/markdown/_Sidebar.md, docs/markdown/i18n-module.md
I clicked a broken link, and that annoyed me enough to fix all of them.
BTW it would be probably pretty good idea to nuke all pages from https://github.com/mesonbuild/meson.wiki to ensure they return 404, and disappear from various web search indexes.
=> Re-link remaining github wiki urls to mesonbuild.com site

mesonbuild/wrap/wrap.py
The '+' and 'U' cases should not happen normally because we don't run any git commands if the subproject directory exists and contains a meson build file. However, if the user accidentally messed up the subproject checkout to a version that had no build files, we would error out with an assertion.
=> wrap: Handle more submodule status cases

mesonbuild/compilers/compilers.py
The `/DEBUG` flag is always used with MSVC to get debugging information (#684), but it also disables the[ `REF` and `ICF` linker optimisations](https://docs.microsoft.com/en-gb/cpp/build/reference/opt-optimizations) that MSVC enables by default in release builds.
Patch enables these explicitly for buildtypes `release` and `minsize`.
=> Enable default linker optimisations in MSVC release and minsize builds

mesonbuild/dependencies/base.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/ui.py, test cases/common/174 dependency factory/meson.build
Return a PkgConfgDependency object from custom dependency detection which uses pkgconfig. This allows get_pkgconfig_variable() to work correctly on the result.
Return a ConfigToolDependency subclass object from custom dependency detection which uses a config tool.  This allows get_configtool_variable() to work correctly on the result.
Closes #2905
=> Fix dependency object types returned by custom dependency detection

docs/markdown/Configuration.md
Before, each example used a different variable name making them more difficult to understand for a novice.
I am happy to use a different name (e.g. `cdata`) if you prefer.
=> Use the same name for the conf_data variable

mesonbuild/mtest.py
Setting MALLOC_PERTURB_ to a non-zero value is fine for regular test cases. It helps catching bugs, but also comes with some runtime overhead.
This overhead is noticeable for benchmarks when compared to running them directly instead of through Meason.
Therefore, MALLOC_PERTURB_ is not touched for benchmarks.
closes #3034
=> Do not set MALLOC_PERTURB_ for benchmarks

docs/markdown/Gnome-module.md
This adds an example to the documentation for using GResource with the GNOME module
=> Add an example for gresource

mesonbuild/mesonmain.py
Since c2a5ac39, MesonApp.generate() closes the logfile before returning,
which means that when invoked by mesonmain.run(), any MesonException is not
logged there.
MesonApp.generate() does not appear to have any other users I can find.
This somewhat reduces the diagnostic value of the logfile.
This also interacts badly with running project tests in CI, as _run_tests
chooses to report the logfile contents, rather than stdout, for the
configure step, and it thus doesn't report any configure error which caused
a test failure.
=> Ensure any generation error appears in the logfile and thus in CI output

docs/markdown/Build-options.md
Do not think this is mentioned anywhere in docs. Modified mesion_options.txt in subprojects manually until I finally figured out what to do by looking at output of "meson configure".
=> Document how to set options in subprojects

docs/markdown/Running-Meson.md, man/meson.1, mesonbuild/environment.py, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/mesonmain.py, run_project_tests.py, run_unittests.py, test cases/common/19 comparison/meson.build, test cases/unit/21 exit status/meson.build
PR #2527 suggests "making failing tests more strict about failing
gracefully".
To achive this, make meson exit with distinct exit statuses for meson errors
and python exceptions, and check the exit status is as expected for failing
tests.
I can't see how to write a test for this, within the current framework.
You can test this change by reverting the fix (but not the test) from commit
1a159db8 and verifying that 'test cases/failing/66 string as link target'
fails.
=> Verify that failing tests are failing with an error, not a python exception

mesonbuild/backend/ninjabackend.py, mesonbuild/mesonlib.py, run_unittests.py, test cases/vala/8 generated sources/meson.build
We missed one particular edge-case in #2413: when the generated vala file is inside --basedir, the path is not just the basename.c
Since this case can never happen in a project test, this includes a unit test for the same.
Closes #815
=>  vala: Fix path of C file with generated Vala files

mesonbuild/modules/gnome.py, run_unittests.py, test cases/frameworks/7 gnome/meson.build, test cases/frameworks/7 gnome/resources/meson.build
Also add a unit test that will test all codepaths for old Glib tools versions.
Closes https://github.com/mesonbuild/meson/issues/2860
=> gnome: Fix depend_files listing for compile_resources

mesonbuild/compilers/c.py, mesonbuild/dependencies/base.py, run_unittests.py, test cases/frameworks/7 gnome/meson.build, test cases/unit/17 pkgconfig static/foo.pc.in
A hard error makes this feature useless in most cases since a static library usually won't be found for every library, particularly system libraries like -lm. Instead, warn so the user can provide the static library if they wish.
This feature will be expanded and made more extensible and more usable in the future.
Closes https://github.com/mesonbuild/meson/issues/2785
=> pkgconfig deps: Warn when a static library isn't found

mesonbuild/backend/backends.py
Extend build rpath generation to simple pkg-config dependencies that only consist of a absolute path to a shared library. This is very useful when using .pc files in a development prefix.
=> Generate build rpath for pkg-config dependencies consisting of a one absolute path

mesonbuild/mlog.py
As written in PR #2856, this code isn't quite right.
An ArgumentNode object can evaluate as False (if it's arguments attribute is
an empty sequence).
If that happens, we then try to hand the location kwarg down to print(),
rather than removing it, which causes an invalid keyword argument exception.
This failure can be seen e.g. when generating for gnome-twitch (See [1])
[1] https://travis-ci.org/jon-turney/meson-corpus-test/jobs/343017109
=> Handle a warning location which evaluates to False

docs/markdown/Generating-sources.md
I found the `extra_args` parameter of `generator.process() ` very useful, and made use of it in my generators.
This required adding `'@EXTRA_ARGS@'` into the 'arguments' parameter in the definition of `generator()`. Even though this is somewhat documented in the reference manual, I think it would be easier to find and use if this was also mentioned in the Manual section on this topic.
So I added a paragraph with an example about how to make generators that accept these optional extra arguments. I tried to also describe the substitution mechanism in a bit more detail, as I understood them from #481 and the related code.
Suggestions for improvements, and corrections of any inaccuracies are welcome!
=> Improve the documentation of @EXTRA_ARGS@

test cases/csharp/4 pkgconfig/meson.build, test cases/csharp/4 pkgconfig/test-lib.cs
This allows C# projects to use pkgconfig.
=> Use dependency link arguments in C# targets

mesonbuild/dependencies/base.py, run_project_tests.py, test cases/frameworks/1 boost/meson.build, test cases/frameworks/10 gtk-doc/meson.build, test cases/frameworks/11 gir subproject/meson.build, test cases/frameworks/12 multiple gir/meson.build, test cases/frameworks/13 yelp/meson.build, test cases/frameworks/15 llvm/meson.build, test cases/frameworks/16 sdl2/meson.build, test cases/frameworks/19 pcap/meson.build, test cases/frameworks/19 pcap/pcap_prog.c, test cases/frameworks/20 cups/meson.build, test cases/frameworks/4 qt/meson.build, test cases/frameworks/6 gettext/installed_files.txt, test cases/frameworks/6 gettext/meson.build, test cases/frameworks/7 gnome/meson.build, test cases/frameworks/8 flex/meson.build, test cases/frameworks/8 flex/prog.c
Always run all framework tests on all platforms, but allow them to be skipped, when not running under CI for linux.
This should:
- make framework tests more useful in a non-CI environment, where all the prereqs might not be installed, as tests are allowed to be skipped
- run applicable framework tests on platforms other than linux
- preserves the original intent of having framework tests run under CI be required to pass, not get skipped
=> Always run all framework tests on all platforms

docs/markdown/snippets/rust-private-disambiguation.md, mesonbuild/backend/ninjabackend.py, test cases/rust/7 private crate collision/installed_files.txt, test cases/rust/7 private crate collision/meson.build, test cases/rust/7 private crate collision/prog.rs, test cases/rust/7 private crate collision/rand.rs
When building a Rust target with Rust library dependencies, an
`--extern` argument is now specified to avoid ambiguity between the
dependency library, and any crates of the same name in `rustc`'s
private sysroot.
Includes an illustrative test case.
=> Fix Rust compiler-private library ambiguity

mesonbuild/dependencies/dev.py
Debian has 7svn in their experimental repo, and FreeBSD has 6.0.r2 in
their ports.
=> llvm: Add configs for freebsd 6.0 and debian 7svn

docs/markdown/Adding-arguments.md, docs/markdown/Reference-tables.md
I couldn't find these in the docs. Managed to guess it for C#, but guessing alone isn't a good thing. :)
=> [skip ci] docs: Add reference table for language args parameter names

docs/markdown/index.md
Currently the website doesn't seem to contain any info on projects using Meson. 
A build system lives or dies by the people who are willing to use the project so I've added a small "Projects using Meson" section to the "Community" section of the website.
I'm sure this list could be greatly improved, you should be promoting your success stories!
=> Adding a "Projects using Meson" to Community section

run_project_tests.py, test cases/frameworks/10 gtk-doc/meson.build
Enable 'test cases/frameworks/10 gtk-doc' if gtkdoc version is 1.26 or
later.
Old versions of gtkdoc-scan also output the version to stdout rather than
stderr, so be sure to handle that...
Follow up to #3060
=> Enable 'test cases/frameworks/10 gtk-doc' for gtkdoc >= 1.26

docs/markdown/snippets/test-setups.md, mesonbuild/backend/backends.py, mesonbuild/interpreter.py, mesonbuild/mtest.py, run_unittests.py, test cases/unit/13 testsetup selection/main.c, test cases/unit/13 testsetup selection/meson.build, test cases/unit/13 testsetup selection/subprojects/bar/bar.c, test cases/unit/13 testsetup selection/subprojects/bar/meson.build, test cases/unit/13 testsetup selection/subprojects/foo/foo.c, test cases/unit/13 testsetup selection/subprojects/foo/meson.build
The main change is to allow subprojects to use their own versions of identically named test setups. E.g. if the main project and a subproject both have a test setup called `valgrind` but with incompatible options, this change will allow one to invoke tests with `--setup valgrind` option that will make meson use the `valgrind` test setup from the correct projects.
The other major change is the addition of project specifier in the setup selection argument.
I.e.:
`--setup somesetup` -> Use test setup `somesetup` from the same project from where the to-be-executed test is read from. If a (sub)project has tests defined but no test setup called `somesetup` meson will print an error about that.
`--setup someproject:somesetup` use the `somesetup` test setup from `someproject` for _all_ executed …
=> Improve test setup selection.

docs/markdown/Reference-manual.md, docs/markdown/Subprojects.md
Also added 2 links to subprojects page from reference manual.
Closes #2766
Assigning @jpakkane for review since it was his explanation and I believe it should be his decision whether we should include this verbatim.
=> Added "Why must all subprojects be inside a single directory?" to Subprojects page

.travis.yml
Since [1], python3 is now an alias for python, so installing it, rather than
upgrading it, will fail.
It also seems that homebrew can't do this upgrade without breaking python2, so
uninstall and reinstall python2 (and mercurial which depends on it) to work
around that problem.
[1] https://brew.sh/2018/01/19/homebrew-1.5.0/
=> Fix OSX CI with current homebrew

mesonbuild/mtest.py
The test setup's timeout_multiplier doesn't currently get taken into use properly.
=> Fix test setup's timeout_multiplier handling.

docs/markdown/Reference-tables.md
Missing ending pipe was causing it to fail to render. See below;
=> Fixing broken language arguments table [skip ci]

mesonbuild/mconf.py
Reading the code I came to the conclusion that only boolean values are made lower case and the new code reflects this. I can't think of other values but please do let me know if there are.
Now all array options with string in them retain their case properly.
edit: Added several cleanups, pep8. Can split this off into another PR if needed.
=> mconf: re-implement print_aligned fixes #3149

docs/markdown/Generating-sources.md
There was a syntax error in the example I have submitted in my previous PR. This fixes it.
I have only noticed it now, when I saw it deployed on the website, with syntax highlighting.
=> Fix a syntax error in an example in 'Generating sources'.

docs/markdown/snippets/improved-meson-init.md, mesonbuild/minit.py, run_unittests.py
This adds the possibility to generate a meson.build file completely automagically for the simple case of a single C or C++ executable. You might get things to build just by saying "meson init -b".
Since this is my first contribution, feedback is very welcome.
(The previous pull request https://github.com/mesonbuild/meson/pull/3146 was from the wrong branch, this should be better.)
=> Add generation of meson.build files from existing sources to "meson init"

.travis.yml, mesonbuild/dependencies/ui.py, run_unittests.py
Enable linux-like unit tests on all posix-like platforms
This reveals a few problems with `dependency('qt4|5', method: 'qmake')` on osx and cygwin, so fix those as well.
=> Enable linux-like unit tests on all posix-like platforms

docs/markdown/Reference-manual.md, docs/markdown/snippets/compiler-object-run_command.md, mesonbuild/interpreter.py, run_unittests.py, test cases/unit/23 compiler run_command/meson.build
Sometimes it is needed to run the current compiler with specific options
not to compile a file but rather to obtain additional info. For example,
GCC has several -print-* options to query it about the paths to
different libraries and development files. One use case is to get the
location of development files for GCC plugins, which is not easily
obtainable by other means:
gcc -print-file-name=plugin
For this purpose, it would be convenient if the compiler object returned
by meson.get_compiler(lang) could be used in run_command() directly.
This commit implements it.
Signed-off-by: Evgenii Shatokhin <eshatokhin@virtuozzo.com>
=> Allow passing a compiler object to run_command()

docs/markdown/Reference-manual.md, docs/markdown/snippets/declare_dependency-link_whole.md, mesonbuild/build.py, mesonbuild/dependencies/base.py, mesonbuild/interpreter.py, mesonbuild/modules/gnome.py, test cases/common/145 whole archive/exe3/meson.build, test cases/common/145 whole archive/exe4/meson.build, test cases/common/145 whole archive/meson.build, test cases/common/145 whole archive/sh_func2_dep_func1/meson.build, test cases/common/145 whole archive/sh_func2_transdep_func1/meson.build
Additionally
- Removed unnecessary unpacking of link targets `BuildTarget.process_kwargs()`.
- Refactored of 'common/145 whole archive' test case because it was extremely hard to follow.
- Added test cases verify that `link_whole` works directly and as transitive dependency.
This partially covers #3046 
Due to a lot of renames in test case refactoring it might be easier to review test case changes commit by commit.
=> Add declare_dependency() link_whole parameter

mesonbuild/mesonlib.py
Starting from 8fc424418720da4ef61bde9348f4cc1a149d1cb2, tests
failed on my system (python 3.6 arch) because
shutil.which('meson.py') returns 'meson.py', not './meson.py'.
Refactor that codepath by using os.path.isabs instead of
"m_dir == '.'", also remove the adjacent comment because
it doesn't make much sense.
=> mesonlib: fix meson detection (again)

docs/markdown/Reference-manual.md
* The example for executable()'s install_dir: should use join_paths()
* Clarify how to use directory options which are potentially not prefix
relative
This is mentioned in https://github.com/mesonbuild/meson/issues/1637 and see
also https://patchwork.freedesktop.org/patch/200373/ for an example of this
usage, and the possible confusion that can arise.
=> doc: Tweak text about get_option('foodir') in reference manual [skip ci]

mesonbuild/backend/ninjabackend.py, test cases/common/180 generator link whole/export.h, test cases/common/180 generator link whole/generator.py, test cases/common/180 generator link whole/main.c, test cases/common/180 generator link whole/meson.build, test cases/common/180 generator link whole/pull_meson_test_function.c
This test covers usage of generated files in static_library that is later linked into shared_library.
This test is flaky because dependencies are not set correctly. Tests are not robust because the only way I found to trigger this reliably is building with `-j20`. But it randomly fails at least in specific test case so it might be good enough.
5th test is what actually fails, all the rest is just a verification that something very similar works fine.
I copied `build.ninja` below, the difference between 4th and 5th tests is that I replaced `link_with` with `link_whole`, and dependency on header file disappeared. Since header file is created by generator and dependency does not exist, ninja will not necessary execute generator before trying to compile `main.c.o`, and this will manifest in …
=> Get generated headers from link_whole_targets as meson does for link_targets

setup.py
This instructs tools like pip that meson requires python 3.5 or greater,
so if one tries to install on an older version pip will fall back to an
older version of meson.
This won't fix 0.45 since it's already in the wild (unless someone wants
to delete and re-upload the version on pypi). But it should fix future
versions.
=> setup.py: set the python_requires field

mesonbuild/backend/xcodebackend.py, run_project_tests.py
Most of the tests still fail, but at least this tries to run them instead of just bailing out up front. Also switching the default backend to ninja on OS X for run_project_tests.
=> Fix xcode backend to run "meson test" instead of a nonexistent script.

mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/interpreter.py
Currently the coverage will include both system sources and subproject sources. I updated the calls to `lcov` to remove source files that are not of interest to the current project.
=> Exclude subprojects when doing coverage

mesonbuild/interpreter.py
Move call to print_nested_info down into do_subproject()
So we don't print info about possible subproject promotion unless subproject
failure is due to directory non-existence
And we do do that for subproject('foo'), as well as for dependency(fallback:
['foo', ...])
See #3095
=> Show info about possible subproject promotion when appropriate

run_unittests.py
Fix a typo in ac256cb6 preventing soname unit tests from running
=> Fix typo preventing soname unit tests from running

docs/markdown/Feature-autodetection.md, docs/markdown/Unit-tests.md, mesonbuild/backend/ninjabackend.py, mesonbuild/environment.py, mesonbuild/scripts/coverage.py, run_unittests.py
gcovr 3.1 changed the meaning of the -r/--rootdir option so includes a fix for that.
gcovr 3.0 added html report support so adding that as a fallback to lcov & genhtml (from 3.1 to keep things simple)
=> Support gcovr >= 3.1 and add gcovr html report as fallback

mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, run_unittests.py, test cases/linuxlike/9 compiler checks with dependencies/meson.build, test cases/unit/23 non-permitted kwargs/meson.build
This can help future generations avoid mistakes like this:
https://github.com/xkbcommon/libxkbcommon/commit/edb1c662394578a54b7bbed231d918925e5d8150
To avoid breaking builds, this is currently just a warning. After sufficient time has passed this can hopefully become a hard error, similarly to the already-existing `permittedKwargs` warnings.
=> Warn if non-permitted keyword arguments are given to compiler methods

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, run_unittests.py, test cases/common/182 identical target name in subproject flat layout/foo.c, test cases/common/182 identical target name in subproject flat layout/main.c, test cases/common/182 identical target name in subproject flat layout/meson.build, test cases/common/182 identical target name in subproject flat layout/subprojects/subproj/foo.c, test cases/common/182 identical target name in subproject flat layout/subprojects/subproj/meson.build
Fixes the bug with flat layout and identical target names in subprojects.
Without this change directories are not created with subproject prefix
and they can collide.
Also use double blank line in run_unittests.py according to
https://www.python.org/dev/peps/pep-0008/#blank-lines.
This is a preparation for #2861
=> Use target.get_id() instead of concatenating basename and type_suffix at call site

.appveyor.yml
Split command to avoid "The input line is too long." error.
Also use --needed for pacman to not reinstall already installed packages.
Github did not allow me to reopen #3244 👎 which I closed to experiment in my own repository with ~10 force pushes.
=> Fix appveyor failures: do not use PowerShell since it triggers NativeCommandError if pacman prints to stderr

README.md
Intentionally not setting [skip ci] to check that it works.
- Renamed `Owners` team to `Core` since github complains about `Owners` being misleading, it became a role and team has no effect. `Core` also gives full administrative access to Appveyor.
- `jpakkane@gmail.com` is added as Appveyor administrator directly, without team management. This will prevent accident lockout in case of github misconfiguration.
- `Contributors` team is added, it provides `Contributor` role in Appveyor, it allows to start and stop builds only. This is the way to allow people to start/stop builds without giving privileges to break something else.
- [Rolling builds](https://www.appveyor.com/docs/build-configuration/#rolling-builds) feature is enabled, but for pull requests only. If you push new commit to PR it …
=> Replaced appveyor account by mesonbuild

docs/markdown/Project-templates.md
In minit docs: `meson test --help` -> `meson init --help`
=> Project-templates.md: Fix help command name [skip ci]

mesonbuild/compilers/compilers.py, test cases/common/183 as-needed/config.h, test cases/common/183 as-needed/libA.cpp, test cases/common/183 as-needed/libA.h, test cases/common/183 as-needed/libB.cpp, test cases/common/183 as-needed/main.cpp, test cases/common/183 as-needed/meson.build
`-Wl,-dead_strip_dylibs` is the analogue of `-Wl,--as-needed` on macOS.
=> Add -Wl,-dead_strip_dylibs support

mesonbuild/modules/pkgconfig.py, run_unittests.py, test cases/common/51 pkgconfig-gen/dependencies/meson.build, test cases/unit/24 pkgconfig usage/dependee/meson.build, test cases/unit/24 pkgconfig usage/dependee/pkguser.c, test cases/unit/24 pkgconfig usage/dependency/meson.build, test cases/unit/24 pkgconfig usage/dependency/pkgdep.c, test cases/unit/24 pkgconfig usage/dependency/pkgdep.h, test cases/unit/24 pkgconfig usage/dependency/privatelib.c
Do not add private dependencies of shared libraries. Pkg-config leaks them out with `--cflags` and thus requires that all dependency dev libraries are installed when using this. That should not be required. If the thing to be installed is a static library, the dependencies are added because there is no other way.
This will fail in CI because the old tests verifying pkg-config output obviously no longer work. @sarum9in  and @xclaesse, you seemed to be the last persons to touch these. Could you check out what should be the correct way to fix those? Thanks.
=> Fix pkg-config dependencies leaking out (debbug 892956)

mesonbuild/optinterpreter.py
Making the option unusable with messages like: `Invalid kwargs for option use_orc: "yield"`
=> options: s/yiel/yield/ typo

mesonbuild/mtest.py
Otherwise unit tests fail on windows when they output some
non-ascii data, see the python trace [here](https://ci.appveyor.com/project/nyorain/dlg/build/1.0.51/job/5at83tuynh77lj60) for example (the project includes a unit tests that outputs some weird utf-8 chars).
This was just a fix i found that worked, not sure if hard coding it is actually a good idea. But on the other hand this is already done at multiple places in meson so it should not really give anybody problems.
=> Open mesontest logfiles using utf-8

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/compilers.py, run_unittests.py, test cases/common/185 ndebug if-release enabled/main.c, test cases/common/185 ndebug if-release enabled/meson.build, test cases/common/186 ndebug if-release disabled/main.c, test cases/common/186 ndebug if-release disabled/meson.build, test cases/unit/25 ndebug if-release/main.c, test cases/unit/25 ndebug if-release/meson.build
Co-authored-by: David Seifert <soap@gentoo.org>
This reveals a bug with `b_ndebug=if-release`. This feature was introduced in #1896 but it never worked and never was tested.
Currently `compilers.get_base_compile_args()` does not have target context, e.g. `buildtype`. The problem is `if-release` depends on target settings, particularly `buildtype`.
So the question is
- Do we want `compilers.get_base_compile_args()` to be independent from target options?
- Do we want to keep abstraction-breaking `if-release` at all? Probably yes because users like it. But it never worked...
- Could it be that it should be `c_ndebug` option which can depend on target?
=> Fix b_ndebug=if-release silently not working

docs/markdown/Cross-compilation.md
The target platform of cross compiler is the host platform of the project being built.
CC @eternaleye
=> docs: fix one 'target' that should be 'host'

mesonbuild/compilers/compilers.py
Few Intel compiler fixes based on errors in [CI](https://hephaistos.lpp.polytechnique.fr/teamcity/viewType.html?buildTypeId=mesonbuild_FedoraIntel&guest=1)
=> Few Intel compiler fixes

docs/markdown/Reference-manual.md
Clarifies that `test()` can take an external program and removes statement that `executable()` ignores unknown files. See #3283.
=> Update test() in Reference Manual

.appveyor.yml, .travis.yml, skip_ci.py
Closes #3294
Since this code does not skip CI for direct commits, only pull requests, code coverage should not be affected.
Tested manually.
Commit to master, everything is built normally:
- https://github.com/sarum9in/meson/commit/28576ad0d0f14cde36576e0b7d780aa9ff9db451
- https://travis-ci.org/sarum9in/meson/builds/357160287
- https://ci.appveyor.com/project/sarum9in/meson/build/79
Pull request, documentation only, skipped (~45s per build, yay!):
- https://github.com/sarum9in/meson/pull/11
- https://travis-ci.org/sarum9in/meson/builds/357160403
- https://ci.appveyor.com/project/sarum9in/meson/build/78 
Documentation-only merge, everything is built normally:
- https://github.com/sarum9in/meson/commit/1c33b0489f17c239511a27c5f026be184df7357c
- …
=> Skip CI for documentation-only pull requests

mesonbuild/modules/pkgconfig.py
Whilst working on the Reproducible Builds effort [0], we noticed
that meson creates non-reproducible pkgconfig files as it iterates
over Python sets.
This was originally filed in Debian as #892515 [1].
[0] https://reproducible-builds.org/
[1] https://bugs.debian.org/892515
=> Make the generated pkgconfig files reproducible.

mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, test cases/common/138 include order/inc1/hdr.h, test cases/common/138 include order/inc2/hdr.h, test cases/common/138 include order/meson.build, test cases/common/138 include order/ordertest.c
Here @tp-m mentioned aboud bug with reversed order. This patch will fix this bug.
https://github.com/mesonbuild/meson/pull/2975
=> Fix bug include_directories(['p1','p2']) add -Ip2 -Ip1 (reversed order)

mesonbuild/mconf.py, mesonbuild/mintro.py, mesonbuild/mtest.py, mesonbuild/rewriter.py, mesonbuild/scripts/meson_exe.py
Might help with #3290.
Scripts not converted yet because they are always run in a fresh process.
=> Always build parser objects anew to avoid leaking old data.

mesonbuild/modules/pkgconfig.py, test cases/d/3 shared library/meson.build
Fairly self-explanatory, and seems to be a regression in 0.45.
Passing in None here shouldn't be an issue, because `versions` has no dependency on build_to_src anyway.
=> Don't crash when using d_module_versions for pkg-config

docs/markdown/Cross-compilation.md
This adds the information needed to prevent misunderstandings like that one I fixed in #3281.
=> docs: Expand on compiler vs compilee build host and target

docs/markdown/Pkg-config-files.md
typo: seems that configure_files doesn't exists, maybe you mean configure_file here. [skip ci]
=> Update Pkg-config-files.md [skip ci]

docs/markdown/Users.md
Showcases a number of projects that are not shown in the existing list.
=> Add link to `meson` github topic

mesonbuild/scripts/gtkdochelper.py
The GTK-Doc commands output was never printed, except in case of error.
So there was no way to see the warnings.
https://github.com/mesonbuild/meson/issues/2396
=> gtkdochelper: print warnings

mesonbuild/backend/ninjabackend.py, mesonbuild/scripts/coverage.py
As noted in issue #2953 there is some confusion among the coverage targets, some use meson --internal and some do not  and they don't even run the same commands.
So this is an effort to consolidate them, I liked the separation of having a separate coverage.py script so moved the legacy targets to also use the standalone script.
ninja coverage -> generate all possible reports (text, xml, html)
depending on gcovr and/or lcov/genhtml availability.
ninja coverage-html -> generate only html report
ninja coverage-xml -> generate only xml report
ninja coverage-text -> generate only text report
Make all targets phony, the old legacy rules where just annoying as
you would have to remove the old report before being able to generate
a new one.
ninja coverage succeeds if it can generate at least one …
=> Use standalone coverage script for legacy targets

mesonbuild/modules/gnome.py
The `gtkdoc` function in the `gnome` module is able to use generated files as content files, but the path to these is wrong in the used command line.
This should fix half of the problem from issue #3317, because it also involves #2909 that should also be fixed by #3189.
=> gnome.gtkdoc: Fix generated files used as content files

docs/markdown/Reference-manual.md, docs/markdown/snippets/both-libraries.md, mesonbuild/backend/backends.py, mesonbuild/build.py, mesonbuild/coredata.py, mesonbuild/interpreter.py, mesonbuild/modules/pkgconfig.py, mesonbuild/modules/python3.py, test cases/common/189 bothlibraries/libfile.c, test cases/common/189 bothlibraries/main.c, test cases/common/189 bothlibraries/meson.build, test cases/common/189 bothlibraries/mylib.h
Also support default_library='both' to make library() build both shared
and static.
Closes #484
=> Add both_library() to build both shared and static library

mesonbuild/compilers/c.py, mesonbuild/interpreter.py, test cases/common/142 compute int/config.h.in, test cases/common/142 compute int/meson.build, test cases/common/142 compute int/prog.c.in
Copy the algorithm used by autoconf.
It computes the upper and lower limits by starting at [-1,1] and
multiply by 2 at each iteration. This is even faster for small numbers
(the common case), for example it finds value 0 in just 2 compilations
where old algorithm would check for 1024, 512, ..., 0.
=> Remove arbitrary [-1024,1024] limit in cross_compute_int()

docs/markdown/Reference-manual.md, mesonbuild/interpreter.py, mesonbuild/mesonlib.py, test cases/common/16 configure file/config7.h.in, test cases/common/16 configure file/meson.build, test cases/common/16 configure file/prog7.c
The added format argument for configure_file allows to specify the kind of file that is
treated. It defaults to 'meson', but can also have the 'cmake' value to treat config.h.in
files in the cmake format with #cmakedefine statements.
=> add support for cmakedefine in configure_file()

mesonbuild/modules/gnome.py, test cases/frameworks/7 gnome/installed_files.txt, test cases/frameworks/7 gnome/mkenums/meson.build
When using gnome.mkenums_simple() we end up installing the generated
C source file alongside the C header file, if `install_header` is set
to True. This is caused by mkenums_simple() acting as a wrapper for
mkenums() without template files; mkenums() won't be able to know if
we're generating the header or the source, and will use the presence
of `install_header` as the deciding factor as to whether the generated
file should be installed.
When generating the C source file, we should always unset the
`install_header` option to False, just like mkenums() expects.
Closes #3373
=> Never install the glib-mkenums generated C source

mesonbuild/compilers/vala.py
Fixes "warning: --output and -o have no effect when -C or --ccode is set"
get_always_args() adds -C which is already disabling the direct compilation
ability of valac for which -o is used.
=> vala: Don't pass -o and -C at the same time

mesonbuild/build.py
When getting dependencies, we don't need to get the same dependencies and
dependency chains multiple times. If library a depends on x, y and z, and
library b depends on a, then we should not have to iterate through x, y and
z multiple times. Pruning at the stage of scanning the dependencies leads
to significant time savings when running meson
=> Prune unneeded transitive dependencies

mesonbuild/build.py
when flattening the chained dependencies of an object, we don't need to
create any new internal dependencies if all the fields to be added to it
are empty.
For projects with a lot of libraries and dependency objects this can lead
to noticeable performance improvements.
=> don't create unneeded internal dependency objects

mesonbuild/compilers/compilers.py, run_unittests.py
If paths are absolute the order of search directories is not relevant as the path is already resolved.
This fix is likely to be related to #3071.
=> Deduplicate dependencies resolved to absolute paths

mesonbuild/interpreter.py, mesonbuild/mlog.py
When looking at some builds with subprojects, I found it dificult to see where subproject output starts and ends, so I wrote this, which adds a visual indication of subproject depth in the console output.
WIP because I'm not sure if this is useful, if it should be optional, and if this is how it should look.
This makes the simplifying assumption that `mlog.log()` is never used with the `end` keyword.  I'm not sure that allowing that to take the same keywords as `print()` is really helping things (where `sep` is probably the only currently existing one which is useful) or just making it more complex.
=> Indicate subproject depth in console output [WIP]

mesonbuild/mesonlib.py
Fixes #3364
Uses popen_safe_legacy on systems where locale.getpreferredencoding isn't UTF-8 because this results in errors otherwise.
See this for reference:
https://stackoverflow.com/questions/29546311/popen-communicate-throws-unicodedecodeerror
=> Fix encoding bug on Windows

mesonbuild/modules/pkgconfig.py, run_unittests.py
This was introduced in 8efd940.
=> pkgconfig module: Fix regression that Requires.private is generated as 'Q, t, 5, C, o, r, e' instead of Qt5Core.

mesonbuild/dependencies/base.py
This halves the configure time in gst-build, the aggregate of all GStreamer repositories.
We can't do this to Popen_safe because we can't be sure that other programs have no side-effects and will always return the same output for the same arguments and environment.
=> PkgConfigDependency: Cache the output of pkg-config

docs/markdown/Reference-manual.md, docs/markdown/Unit-tests.md, mesonbuild/mtest.py
closes #3368.
I was trying to understand the syntax to be used and I realized that with the following `meson.build`
```
project('project_name', ...)
test('test_name', executable, suite: 'suite_name')
```
the correct syntax is
```
meson test --suite project_name:suite_name
```
which seemed a bit odd to me for the case of a unique project. So I extended a bit the functionality such that I can also run
```
meson test --suite suite_name
```
I also added the documentation of the keyword `suite` for the `test()` function (as I understood it)
closes https://github.com/mesonbuild/meson/issues/1674
=> improve suite of meson test

docs/markdown/Gnome-module.md, mesonbuild/modules/gnome.py, test cases/frameworks/7 gnome/gdbus/meson.build
The development version of `glib` (2.55.2) has acquired support for [generating gdbus header and source code files separately](https://bugzilla.gnome.org/show_bug.cgi?id=791015).
This PR allows dependencies to be more fine grained on those targets depending only on the header, which is needed for [some](https://bugzilla.gnome.org/show_bug.cgi?id=789877#c16) [ports](https://github.com/mesonbuild/meson/issues/2893#issuecomment-355856606).
=> gnome: Split header and code targets in gdbus_codegen()

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, run_unittests.py, test cases/unit/26 guessed linker dependencies/exe/app.c, test cases/unit/26 guessed linker dependencies/exe/meson.build, test cases/unit/26 guessed linker dependencies/lib/lib.c, test cases/unit/26 guessed linker dependencies/lib/meson.build, test cases/unit/26 guessed linker dependencies/lib/meson_options.txt
The linkers currently do not support ninja compatible output of
dependencies used while linking. Try to guess which files will be used
while linking in python code and generate conservative dependencies to
ensure changes in linked libraries are detected.
This generates dependencies on the best match for static and shared
linking, but this should not be a problem, except for spurious
rebuilding when only one of them changes, which should not be a problem.
Also makes sure to ignore any libraries generated inside the build, to
keep the optimisation working where changes in a shared library only
cause relink if the symbols have changed as well.
=> ninjabackend: Try to guess library dependencies for linker invocation.

mesonbuild/backend/ninjabackend.py, run_unittests.py, test cases/unit/29 cross file overrides always args/meson.build, test cases/unit/29 cross file overrides always args/test.c, test cases/unit/29 cross file overrides always args/ubuntu-armhf-overrides.txt
This way they override all other arguments. This matches the order of link arguments too.
Note that this means `-I` flags will come in afterwards and not override anything else, but this is correct since that's how toolchain paths work normally too -- they are searched last.
Closes https://github.com/mesonbuild/meson/issues/3089
Supersedes https://github.com/mesonbuild/meson/pull/2996
=> cross: Add compiler cross_args after normal args

docs/markdown/Compiler-properties.md
This adds important information for function detection on macOS, which requires the correct header to be used when detecting a function, else results can be misleading and report a function as available even though it is not.
=> Docs: Mention important macOS caveat about function detection

mesonbuild/compilers/compilers.py
GNU LD does not use soname when linking a PE/COFF binary, so it makes no
difference, but it breaks when using the llvm linker (lld), which does
not support the soname flag when building PE/COFF binaries for Windows.
Fix #3179
=> Do not use -soname when linking with GCC for mingw/cygwin

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cs.py, mesonbuild/compilers/d.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/java.py
This patch exploits the information residing in ltversion to set the
-compatibility_version and -current_version flags that are passed to the
linker on macOS.
This PR contains part of the patch found in #2577
=> Add macOS linker versioning information

mesonbuild/compilers/c.py, test cases/common/112 has arg/meson.build
GCC does not print a warning or error for unknown options if the options
are to disable warnings. Therefore, when checking for options starting
'-Wno-', also check the opposite enabling option.  This fixes the case
where e.g.  -Wno-implicit-fallthrough is incorrectly reported as supported
by gcc 5.4.
=> fix checks for gcc disable warning flags

docs/markdown/snippets/openmp-dependency.md, mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/fortran.py, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/misc.py, mesonbuild/linkers.py, test cases/common/190 openmp/main.c, test cases/common/190 openmp/main.cpp, test cases/common/190 openmp/main.f90, test cases/common/190 openmp/meson.build
Unfortunately, it seems like every compiler (mostly Fortran ones) use a different flag for OpenMP. This works similarly to the thread dependency which stores the various inconsistent flags in each compiler.
The problem though is that, like the thread dependency, it just assumes that OpenMP is supported. I'm not exactly sure how old the compilers are that don't support it though (at least gcc 4.2+, Intel 12+). Also, what to do about other languages like Vala or D?
=> Add an OpenMP dependency.

manual tests/2 multiwrap/meson.build
Hi,
The variable name in the wrap meson build appears to be png_dep and not pngdep and the fallback will fail on my ubuntu 17.10.
=> fix fallback variable name

ciimage/Dockerfile, docs/markdown/Python-module.md, docs/markdown/snippets/python-module.md, docs/sitemap.txt, docs/theme/extra/templates/navbar_links.html, mesonbuild/interpreter.py, mesonbuild/modules/python.py, run_unittests.py, test cases/python/1 extmodule/blaster.py, test cases/python/1 extmodule/ext/meson.build, test cases/python/1 extmodule/ext/tachyon_module.c, test cases/python/1 extmodule/meson.build, test cases/python/1 extmodule/meson_options.txt
This is the second attempt at supporting python 2 in meson, see https://github.com/mesonbuild/meson/pull/3194 for context.
The test is a unit test so that we can check behaviour with various python names.
=> Implement a generic python module

docs/markdown/snippets/d-options-for-meson-setup.md, mesonbuild/coredata.py, mesonbuild/interpreter.py, mesonbuild/mconf.py, mesonbuild/mesonmain.py
The first three patches are some nice cleanups in this area I already had, but the last is the bread and butter of this PR. Basically let's not have different arguments for `meson` and `meson configure`
=> Accept -D for meson level options durring initial configuration

docs/markdown/Reference-manual.md, docs/markdown/snippets/partial-dependencies.md, mesonbuild/dependencies/base.py, mesonbuild/interpreter.py, test cases/common/191 partial dependency/declare_dependency/headers/foo.c, test cases/common/191 partial dependency/declare_dependency/headers/foo.h, test cases/common/191 partial dependency/declare_dependency/main.c, test cases/common/191 partial dependency/declare_dependency/meson.build, test cases/common/191 partial dependency/declare_dependency/other.c, test cases/common/191 partial dependency/meson.build, test cases/frameworks/1 boost/meson.build, test cases/frameworks/1 boost/partial_dep/foo.cpp, test cases/frameworks/1 boost/partial_dep/foo.hpp, test cases/frameworks/1 boost/partial_dep/main.cpp, test cases/frameworks/1 boost/partial_dep/meson.build
There had been talk some time ago about having the ability to create dependencies that only had cflags, or only had libs. I need this for mesa, currently the proposed work around is to call pkg-config using `find_program` and `run_command`, but really all we want is to be able to do something like:
```meson
dep_vdpau = dependency('vdpau').sub_dependency(compile_args : true)
```
I've tried to create a mechanism that is flexible enough to cover a lot of use cases. Some of them don't make sense to me, but I've included them for completeness.
This pull is missing documentation, but I'd like to wait until I have some feedback that this is an acceptable approach before writing that.
=> Partial dependencies

docs/markdown/Reference-manual.md, docs/markdown/snippets/test-depends.md, mesonbuild/backend/backends.py, mesonbuild/interpreter.py, test cases/common/188 test depends/gen.py, test cases/common/188 test depends/main.c, test cases/common/188 test depends/meson.build, test cases/common/188 test depends/test.py
Closes #3310 
This implementation adds dependees to `all` the same way as current `exe` and `cmd_args` are added.
If we decide to rework this later and make test dependencies more granular, code is located at the exact same place as other related code so this will be part of change.
=> Add test(depends) keyword parameter

manual tests/2 multiwrap/subprojects/libpng.wrap
1.6.17-6 has a bug with missing -lm linking on ArchLinux.
See https://github.com/mesonbuild/libpng/pull/7
=> Update 'manual tests/2 multiwrap' libpng dependency to 1.6.34

mesonbuild/modules/gnome.py
The `install` parameter that is present in the `permittedKwargs` annotation is wrong. The correct parameter name, which is also consistent with the rest of functions in the `gnome` module, is `install_dir`.
=> gdbus_codegen: Fix install_dir parameter

mesonbuild/compilers/c.py
compile() method already does it so links() and compiles() shouldn't do
it too. This fix regression introduced in 3d91a08b.
Closes #3431
=> CCompiler: Do not call to_native() twice

mesonbuild/backend/ninjabackend.py
Once we calculate the generated headers for a target we can cache them to
speed up future calls for that target.
=> cache the generated headers for each target

mesonbuild/modules/pkgconfig.py, run_unittests.py
The fix for Requires generation in #3406 missed a second code path with the same
problem.
Passing a pkgconfig dependency to requires would produce Q, t, 5, C, o,r, e'
instead of 'Qt5Core'.
This was introduced in 8efd940.
=> regression: pkgconfig module: Fix Fix regression in Requires.private generation.

mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/base.py, mesonbuild/interpreter.py, test cases/unit/27 forcefallback/meson.build
Otherwise, we will fail if we could not setup a subproject for an optional fallback dependency.
This involves the creation of a new dummy NotFoundDependency.
=> Don't fail on not-required not-found deps in forcefallback mode

mesonbuild/backend/ninjabackend.py
Otherwise, it produces a duplicate `FORTRAN_DEP_HACK` rule, which causes an error in ninja.
=> Fix Fortran dep hack when cross-compiling.

mesonbuild/backend/ninjabackend.py
The entire subdirectory was getting duplicated, which was exceeding the max path limit in Python on Windows and causing build failures.
Example:
subprojects/gst-plugins-bad/gst-libs/gst/uridownloader/subprojects@gst-plugins-bad@gst-libs@gst@uridownloader@@gsturidownloader-1.0@sha/subprojects/gst-plugins-bad/gst-libs/gst/uridownloader/gsturidownloader-1.0-0.dll.symbols
This path is too long and opening it will cause a `FileNotFoundError` on Windows.
=> ninja backend: Fix shared library symbols path

mesonbuild/modules/gnome.py
Checking the pkg-config file to confirm tool versions is a hack, and should eventually be replaced with checking the actual versions of the tools.
This is needed to build glib on Windows with the new override_find_program functionality. It's a pessimistic assumption, but it won't break the module since it runs `find_program()` on the needed tools anyway.
=> gnome: If pkg-config is not found, assume glib is 2.54

run_project_tests.py
Debian package building fails without this.
=> Explicitly open log files in utf-8.

run_project_tests.py
Maybe now the Debian package builder will be satisfied.
=> If printing debug printing fails, try again in pure ASCII.

docs/markdown/snippets/install_umask.md, mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/coredata.py, mesonbuild/mconf.py, mesonbuild/scripts/meson_install.py, run_unittests.py, test cases/common/12 data/meson.build, test cases/common/66 install subdir/meson.build, test cases/unit/24 install umask/datafile.cat, test cases/unit/24 install umask/meson.build, test cases/unit/24 install umask/myinstall.py, test cases/unit/24 install umask/prog.1, test cases/unit/24 install umask/prog.c, test cases/unit/24 install umask/sample.h, test cases/unit/24 install umask/subdir/datafile.dog, test cases/unit/24 install umask/subdir/sayhello
So this patch set introduces a new built-in option `install_umask` which can be used to define the permissions of files in the install tree.
It defaults to `022`, which is the typical option expected on install, executables and directories get mode `0755` and data files get mode `0644`.
It can be changed by users, using `meson --install-umask=...`, or by projects, setting it on the `default_options` of their `project()` call.
The umask can be disabled by setting `install_umask=none`, in which case the previous behavior of copying the same permissions from the build or source tree are preserved.
Also introduced a unit test to check the behavior of this feature. The unit test simulates the case where a tree is checked out with umask `002`, then the build and install steps are done with …
=> Introduce install_umask to determine permissions of files in install tree. Default it to 022

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/c.py
Meson still produces quite a lot of duplicated linker arguments for e.g. gtk+. Limits the impact of those to the runtime by removing those from the working lists for dependency guessing.
This reduces total runtime of meson for a gtk+ based test case from around 37 seconds to around 8.
=> Optimize dep guessing

mesonbuild/coredata.py, mesonbuild/environment.py, mesonbuild/mconf.py, mesonbuild/mesonmain.py, run_unittests.py, test cases/unit/30 command line/meson.build
Noticed this regression while working on #3473, I'm working on a larger refactoring of the command line parser, but this could already be merged, IMO.
=>  --warnlevel got renamed to --warning-level

mesonbuild/interpreter.py, mesonbuild/mconf.py, test cases/common/181 initial c_args/meson.build
When passing more than one -Dc_args it should override the value
instead of appending. This is how all other options works.
Value should be split on spaces using shlex just like it does with
CFLAGS environment variable.
Fixes #3473.
=> Fix setting c_args and friends from command line

msi/createmsi.py
We are taking some shortcuts here. The WiX documentation says that you
should keep the Product GUID the same for "small and minor" upgrades
but change it for major ones. These are not defined in any way and a
change of version number might, or might not, warrant a guid
update. For simplicity we will always regenerate the Product GUID.
Again we find that naming things is difficult since "product" in
everyday language would mean "the application/library/software" and
all different versions of it. In MSI installer terminology it means
something vague between the two.
https://www.firegiant.com/wix/tutorial/upgrades-and-modularization/
=> Always generate a new Product GUID. Closes #2485.  [skip ci]

mesonbuild/dependencies/misc.py
* Currently `required : true` is implicitly assumed, making
optional use of OpenMP not possible.
It would be nice if we could get this in for 0.46.1 as a bug fix.
@QuLogic
=> Allow `required : false` for OpenMP dependency

docs/markdown/Pkg-config-files.md
I had a hard time finding the pkg-config module page, as there is another page about the pkg-config file. 
I added a link from http://mesonbuild.com/Pkg-config-files.html to http://mesonbuild.com/Pkgconfig-module.html.
I hope its easier to find now.
=> Added reference to pkg-config module page in the docs.

README.md
Python 3.5 has been required since 0538009d30c0.
=> Update minimum python version in README.md

mesonbuild/dependencies/dev.py
Fixes this issue:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897174
=> No longer require duplicate gtest header install.

mesonbuild/modules/gnome.py, test cases/frameworks/7 gnome/gdbus/meson.build
The new --body and --header args are broken because they do not allow the use of --output-directory to set the correct `#include "foo.h"` line in `foo.c`. The changes in the gdbus test case show this.
Disabled till this can be fixed in glib.
Closes https://github.com/mesonbuild/meson/issues/3488
=> gnome: Disable usage of new --body and --header args

mesonbuild/compilers/compilers.py, mesonbuild/mesonlib.py
As originally discovered in [eog](https://bugzilla.gnome.org/show_bug.cgi?id=795546) we need to append an extra flag to correctly handle `$ORIGIN` on OpenBSD too.
=> add linker flag to handle $ORIGIN on OpenBSD

mesonbuild/modules/gnome.py
The fix has landed upstream, and will be in the next glib stable release. I have verified that it fixes the problem described in #3488 and that the `frameworks/7 gnome` test passes now.
=> gnome: Update minimum glib version for gdbus-codegen

mesonbuild/modules/gnome.py, test cases/frameworks/7 gnome/mkenums/meson.build
Otherwise, when you use a File target, the value will be the full path to the header from the build root, which is not what anyone wants.
=> gnome: Use the header basename for #include in mkenums_simple

mesonbuild/interpreter.py, test cases/common/198 args flattening/meson.build
It seems that some projects relied on the previously buggy
behaviour of accepting a 2-element list as the single argument
to configuration_data.set().
Special-case this behaviour, and emit a deprecation message.
=> args flattening: preserve configuration_data.set behaviour

mesonbuild/mintro.py, mesonbuild/modules/gnome.py, mesonbuild/scripts/gtkdochelper.py, run_unittests.py, test cases/frameworks/10 gtk-doc/doc/meson.build
commit 14a75d3a027c3337c35dae04831d686e715113c6:
gnome.gtkdoc: Allow passing file objects as xml_files
If we pass a source files() object, we will look for it in the build
directory, which is wrong. If we pass a build files() object (from
configure_file()), we will find it in the build directory, and then
try to copy it on top of itself in gtkdochelper.py getting a
SameFileError.
Add a test for it, and also properly iterate custom target outputs
when adding to content files.
commit ec7c87d2a487f727ec33c21edfd550e62e94ee6a:
gnome.gdbus_codegen: Fix output file list for docbook custom targets
We were setting it to a totally wrong name, while the output of gtkdoc
is very predictable.
Also add a test for it, and fix a bug in meson introspect found while
adding the test.
The test will only …
=> gnome: some gtk-doc and gdbus-codegen issues

mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, test cases/vala/24 export dynamic shared module/app.vala, test cases/vala/24 export dynamic shared module/meson.build, test cases/vala/24 export dynamic shared module/module.vala
Need to generate a vapi and a header, and then use that in the shared module. Needed for GNOME games.
Closes https://github.com/mesonbuild/meson/issues/3538
=> vala: Fix shared_module linking with export_dynamic executable

mesonbuild/mesonlib.py
The value in cross files is free-form, and people expect to be able to (correctly) set it to `ios`.
Our machinery treats `for_darwin()` to mean "for either ios or macos".
=> for_darwin: Also accept system='ios' in cross files

mesonbuild/compilers/c.py, mesonbuild/compilers/fortran.py, test cases/fortran/10 find library/gzip.f90, test cases/fortran/10 find library/main.f90, test cases/fortran/10 find library/meson.build
This fixes #2043 and allows Fortran projects to link against external libraries. It leverages many of the `CCompiler` class methods while still only inheriting directly from `Compiler`.
My original implementation just had the `FortranCompiler` class inheriting from the `CCompiler`, as they share many similar characteristics (indeed, Fortran is listed under `clike_langs`). Obviously, however, the syntax is completely different, so I disabled several methods which were only relevant to the true C-like languages (i.e. checking for headers, defines, symbols, types, etc.). This design instead uses the `CCompiler` methods where relevant (primarily for compiler / linker options) to avoid code duplication but still allows for implementing Fortran-specific methods as well as any potential further …
=> Add support for finding libraries in Fortran projects

mesonbuild/modules/windows.py
If rescomp is not found its command is None and that make meson print
backtrace instead of displaying the error message.
=> Windows: Fix exception when windres is not found

mesonbuild/interpreter.py
We print the meson version, and the project name, but it would be nice to print the project version as well. It's good to have in build logs, and it's useful for when the project version comes from a script.
=> Print project version

run_project_tests.py, test cases/failing test/1 trivial/main.c, test cases/failing test/1 trivial/meson.build
There was a bug when searching for tests that fail at `meson test`. I added a trivial test to prove that it works.
=> Enable running tests that fail at 'meson test'

mesonbuild/backend/backends.py, mesonbuild/environment.py, mesonbuild/mesonmain.py, mesonbuild/scripts/depfixer.py
commit 5e72325d698aeddef04202b92a5411498bef38e3:
depfixer: We no longer run this as a script
commit c404fc1a7881781a9b47aa5d687b74e43021426f:
depfixer: Run install_name_tool only once while deleting rpaths
commit cbf85c843b83698099001eb02fd9db5531ab37c1:
backends: Use a set while gathering RPATHs
commit 1677c61409b55fd80c499626cdedbfb568c70874:
backends: Simplify loop getting rpaths for bundled libs
No functionality changes
commit 102b86235440a049dc4fe0f605b78de046a05c31:
backends: Also accept dylibs while finding RPATHs
=> Misc rpath bugfixes

docs/markdown/Syntax.md, docs/markdown/snippets/integer-base.md, mesonbuild/mparser.py, test cases/common/68 number arithmetic/meson.build, test cases/failing/76 int literal leading zero/meson.build
Simplify support for alternate bases using `int(..., base=0)` which auto-detects it using the standard Python syntax for numbers.
Octal numbers are useful to specify permission bits and umasks.
Binary numbers are not super useful... But considering we get them for free, let's allow them here too.
Add octal and binary number to a test case. Also update docs and add a snippet for release notes.
=> Add support for octal and binary int literals

docs/markdown/Running-Meson.md
When reading the docs, after the first tutorial, the "Running Meson" page explains how `ninja install` installs build targets.
It obviously doesn't work on the tutorial example since there is no target marked for installation. This can be a frustrating experience for new users not aware of Meson default install policy.
This pull request add a remark about tagging targets as installable and a link to the "Installing" doc.
=> Make install doc less surprising for new users

mesonbuild/mtest.py
OpenBSD's getpgid(2) fails with EPERM (PermissionError) because the
test is in a different session: https://man.openbsd.org/getpgid
Use p.pid as the process group ID, because setsid() created a process
group with the same ID as the process.  See setsid(2) manuals:
- FreeBSD: https://www.freebsd.org/cgi/man.cgi?query=setsid
- illumos: https://illumos.org/man/setsid
- Linux: http://man7.org/linux/man-pages/man2/setsid.2.html
This change fixes 'manual tests/8 timeout' on OpenBSD.  To verify this
change, one must run the manual test.  For example,
$ cd 'manual tests/8 timeout'
$ meson build
$ ninja -C build test
It should report that the test timed out, and not show
PermissionError.
Fixes https://github.com/mesonbuild/meson/issues/3569
=> Don't call getpgid() when killing a test.

mesonbuild/compilers/compilers.py
Raising StopIteration from a generator has been deprecated with Python 3.5 and is now
an error with Python 3.7: https://docs.python.org/3.8/library/exceptions.html#StopIteration
Just use return instead.
Fixes #3622
=> Don't raise StopIteration in generators, no longer allowed with Python 3.7. Fixes #3622

meson.py, mesonbuild/dependencies/base.py, mesonbuild/mesonlib.py, mesonbuild/mesonmain.py, mesonbuild/scripts/commandrunner.py, run_cross_test.py, run_project_tests.py, run_tests.py, run_unittests.py
This branch contains two commits:
- One fixes up two tests that are erroneously being skipped (I happened to hit this while debugging through the tests for this change)
- The other allows meson to handle exe wrappers and makes the meson.py detection logic much more robust (more details in the commit description).
=> mesonlib: handle meson exe wrappers

mesonbuild/build.py
This is never going to be useful, and the error message now points people to what they might be expecting: use the default value for this platform.
=> Don't accept an empty string for name_suffix:

docs/markdown/Reference-manual.md, docs/markdown/snippets/compiler_check_header.md, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/interpreter.py, test cases/common/200 check header/meson.build, test cases/common/200 check header/ouagadougou.h
This checks not only for existence, but also for usability of the header, which means it does a full compilation and not just pre-processing or __has_include.
Fixes https://github.com/mesonbuild/meson/issues/2246
The tests are copied from the `has_header()` checks (and modified for usability checks, which means some tests are now false instead of true), and also add the clang `intrin.h` header check reported in the original issue.
=> New compiler method: check_header

docs/markdown/Reference-tables.md
this adds a few more architectures to the list we guarantee. This list was helpfully compiled by a few mesa and gentoo people for me. This should be helpful, particularly since I've seen builds using `arm64` instead of `aarch64` in the wild.
=> [skip ci] Update cpu families

docs/markdown/Reference-manual.md
This series simply deduplicates information between the reference manual and reference tables by pointing the manual to the tables. There are a couple of small cleanups as well.
=> [skip ci] docs: cross reference tables from manual

meson.py, mesonbuild/environment.py, mesonbuild/mesonlib.py, mesonbuild/mesonmain.py, mesonbuild/scripts/regen_checker.py, run_meson_command_tests.py, run_project_tests.py, run_tests.py, run_unittests.py
Instead of using fragile guessing to figure out how to invoke meson, set the value when meson is run. Also rework how we pass of meson_script_launcher to regenchecker.py -- it wasn't even being used
With this change, we only need to guess the meson path when running the tests, and in that case:
1. If MESON_EXE is set in the env, we know how to run meson for project tests.
2. MESON_EXE is not set, which means we run the configure in-process for project tests and need to guess what meson to run, so either
- meson.py is found next to run_tests.py, or
- meson, meson.py, or meson.exe is in PATH
Normally you would invoke meson in the following ways:
1. meson is installed, and mesonbuild is available in PYTHONPATH:
- meson, meson.py, meson.exe from PATH
- python3 -m mesonbuild.mesonmain
- …
=> Set the meson command to use when we know what it is

mesonbuild/build.py, mesonbuild/coredata.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/ui.py, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/mesonlib.py, mesonbuild/modules/gnome.py, mesonbuild/modules/i18n.py, mesonbuild/modules/pkgconfig.py, mesonbuild/modules/python.py, mesonbuild/modules/qt.py, mesonbuild/modules/unstable_icestorm.py, mesonbuild/modules/unstable_simd.py, mesonbuild/optinterpreter.py
It may be only a WIP, but it's a working WIP for #3022.
EDIT : I consider the work finished.
The idea is to use these decorators when adding a new feature into Meson. They check if the user-defined target meson version is compatible with the used features.
Usage:
@FeatureNew('the supernew feature', '0.48.0')
@permittedKwargs({ 'argument' })
def supernew_feature_function(args, kwargs):
…
or:
@permittedKwargs({ 'oldargument', 'newargument' })
def newarguments_feature_function(args, kwargs):
if 'newargument' in kwargs:
FeatureNew('newargument in feature', '0.47.0').use()
…
I also added the `called_features_report()` to both `Feature*` classes to report all used features.
* I don't know a better design than the `@decorator() / decorator().use()` hack. If you do, please let me know.
* The …
=> Add FeatureNew and FeatureDeprecated, to alert the user of bad meson_version

docs/markdown/Windows-module.md, docs/markdown/snippets/windows-resources-dependencies.md, mesonbuild/modules/windows.py, run_unittests.py, test cases/windows/5 resources/res/meson.build
This is the change suggested in #2815, with tests and documentation added.
Fixes #2789 (duplicate #2830)
=> Add a depend_files: keyword to windows.compile_resources() 

docs/markdown/Reference-manual.md, docs/markdown/snippets/install_mode-extended.md, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/interpreter.py, mesonbuild/mesonlib.py, mesonbuild/scripts/meson_install.py, run_project_tests.py, run_unittests.py, test cases/common/201 install_mode/config.h.in, test cases/common/201 install_mode/data_source.txt, test cases/common/201 install_mode/foo.1, test cases/common/201 install_mode/installed_files.txt, test cases/common/201 install_mode/meson.build, test cases/common/201 install_mode/rootdir.h, test cases/common/201 install_mode/runscript.sh, test cases/common/201 install_mode/stat.c, test cases/common/201 install_mode/sub1/second.dat, test cases/common/201 install_mode/trivial.c
This PR makes it possible to pass any target that can be installed (such as `executable()`, libraries, headers, man pages and custom/generated files) and `install_mode` keyword attribute, that can be used to customize the mode of the installed files and optionally user/group ownership.
This makes it possible to install compiled executables as setuid/setgid binaries, which wasn't really easy to accomplish before this change...
It should also mitigate the effects from enforcing a default umask on the installation, since by using install_mode developers can now control the exact mode they wish to have for installed files, giving them full control over it while still keeping useful default behavior.
**NOTE**: This PR changes the behavior of how `install_mode` behaves on rules like …
=> Extend install_mode to all installable targets

mesonbuild/mesonlib.py
Meson would return a message like:
```
ERROR:  ('#mesondefine does not contain exactly two tokens: %s', '#mesondefine _WIN32_WINNT /* Define for Windows 7 APIs. */')
```
which does not seem is intended. This PR corrects the string formatting used, so the error message now will look like:
```
ERROR:  #mesondefine does not contain exactly two tokens: #mesondefine _FILE_OFFSET_BITS 64
```
=> Fix #mesondefine token error message formatting

mesonbuild/backend/ninjabackend.py, test cases/windows/12 exe implib/meson.build
Install the implib into the default import lib directory if an explicit install_dir: is given, but the value happens to be the same as the default.
=> Install implib where expected if default install_dir: is explicitly given

docs/markdown/Reference-manual.md, docs/markdown/snippets/custom-target-depends.md, docs/markdown/snippets/windows-resources-dependencies.md, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/interpreter.py, mesonbuild/modules/windows.py, run_unittests.py, test cases/windows/13 resources with custom targets/res/meson.build, test cases/windows/13 resources with custom targets/res/myres.rc.in, test cases/windows/5 resources/prog.c
As mused on in #2789, this enhances the custom target for invoking the Windows resource compiler so that a depfile is generated by the preprocessor.
This is currently only implemented when using binutils `windres` , and not when using MSVC's `RC`.
=> Generate a preprocessor depfile for Windows resource compilation

mesonbuild/dependencies/ui.py
debugoptimized builds building against Qt would ultimately link against
both the debug and non-debug msvcrt, ntdll, etc libraries which causes
crashes in weird places and is very much not recommended by Microsoft.
This changes the selected Qt library(ies) correctly to not uses the
debug variants for debugoptimized builds.
=> dependencies/qt: fix debugoptimized builds with qt

mesonbuild/mintro.py, run_unittests.py
```py
File "meson.py", line 29, in <module>
sys.exit(mesonmain.main())
File "mesonbuild/mesonmain.py", line 411, in main
return run(sys.argv[1:], launcher)
File "mesonbuild/mesonmain.py", line 320, in run
return mintro.run(remaining_args)
File "mesonbuild/mintro.py", line 234, in run
list_installed(installdata)
File "mesonbuild/mintro.py", line 72, in list_installed
for path, installdir, aliases, unknown1, unknown2 in installdata.targets:
ValueError: too many values to unpack (expected 5)
```
=> meson introspect: Fix --installed argument

docs/markdown/Builtin-options.md, docs/markdown/snippets/bitcode_support.md, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/compilers/compilers.py, mesonbuild/interpreter.py, run_unittests.py
Normally, people would just pass `-fembed-bitcode` in `CFLAGS`, but this conflicts with `-Wl,-dead_strip_dylibs` and `-bundle`, so we need it as an option so that those can be quietly disabled.
=> Add a new option for building with Apple bitcode support

mesonbuild/dependencies/ui.py
This reverts commit 0045d95a16be18092adfb40a9a5df944bcb99aea.
`<jeandet>` nirbheek, it seems 0045d95a16be18092adfb40a9a5df944bcb99aea is really wrong, I've tested on Ubuntu.  While writing this line I was thinking that you can't have Qt without a working qmake in the path. On Ubuntu you have that qtchooser stuff which is misleading.
=> Revert "really switch to qmake automatically if pkg-config fails"

mesonbuild/environment.py
Hi,
For Visual Studio 2008, the envvar 'Platform' is not defined even on x64 build environments, so we need to check 'BUILD_PLAT' instead, so that we can detect x64 builds properly and not fall into problems that may result.
I understand that this is an old toolset, but this is done as we need to support Python 2.7.x, which is built with Visual Studio 2008 on Windows, at least the official binaries from www.python.org.
=> Properly Detect Build Platform on Visual Studio 2008

mesonbuild/scripts/gettext.py
Without this, building a module in a Flatpak app manifest that is a
newer version of a module already present in the Flatpak runtime will
fail. (The Flatpak file system is a bunch of hard links to readonly
files, which can be replaced but not written to.)
This instead creates a temporary file in the same directory as the
destination (to avoid cross-device renaming errors) and atomically
renames the temporary file to the destination, replacing it instead of
rewriting it as shutil.copyfile() would do.
=> gettext: Install .mo files atomically

mesonbuild/backend/backends.py, mesonbuild/compilers/c.py, mesonbuild/compilers/fortran.py
These are also in https://github.com/mesonbuild/meson/pull/3691, but do not depend on it.
commit c9e1fb2e96f22e8f0cef538be76372599a8d415c (HEAD -> nirbheek/find_library_fixes, origin/nirbheek/find_library_fixes)
Author: Nirbheek Chauhan <nirbheek@centricular.com>
Date:   Tue Jun 5 17:54:45 2018 +0530
find_library: Add a cache for library searching
Otherwise we can end up searching for the same library tens of times,
because pkg-config does not de-duplicate -lfoo args before returning
them.
We use -Wl,--start-group/end-group, so we do not need to worry about
ordering issues in static libraries.
commit 39da01cc3ce1915afe0baa3435a35dd89dc68f53
Author: Nirbheek Chauhan <nirbheek@centricular.com>
Date:   Tue Jun 5 17:50:12 2018 +0530
backends: Don't hardcode system library paths
Lookup the …
=> Misc library search fixes

mesonbuild/mintro.py, run_unittests.py
A new custom_install_mode element was added in 05c43cdcd
(It makes our meson build fail with meson master: https://ci.gstreamer.net/job/GStreamer-master-meson/2778/console)
=> mintro: Fix introspecting installation paths

mesonbuild/coredata.py
e.g. 'meson x86_64-w64-mingw32 --cross-file x86_64-w64-mingw32' currently
fails with an IsADirectoryError exception.
Cross files must be files, so when searching, only accept a candidate path
which is an existing file, not just an existing path.
=> Refine cross file checking to ignore directories

docs/markdown/Configuration.md, docs/markdown/Reference-manual.md, docs/markdown/snippets/configure_file_encoding.md, mesonbuild/interpreter.py, mesonbuild/mesonlib.py, test cases/common/16 configure file/config8.h.in, test cases/common/16 configure file/meson.build, test cases/failing/79 non ascii in ascii encoded configure file/config9.h.in, test cases/failing/79 non ascii in ascii encoded configure file/meson.build
meson should not make the assumption that all files are encoded in utf-8 or isolatin1 when passed to configure_file. The new keyword will allow the user to provide the encoding for the the input and output file. It will default to utf-8 so all current code will keep working.
In #1542 people suggest to detect the encoding. This may work for some file but in the end this is nothing more than an educated guess. Meson should not guess if it can ask the user.
Fixes #1542
=> Add file encoding to configure_file

meson.py
https://github.com/mesonbuild/meson/pull/3654#discussion_r194225267
=> meson.py: sys.path requires str, not pathlib.Path

mesonbuild/compilers/compilers.py, test cases/vala/25 extract_all_objects/meson.build, test cases/vala/25 extract_all_objects/prog.vala, test cases/vala/26 vala and asm/meson.build, test cases/vala/26 vala and asm/prog.vala, test cases/vala/26 vala and asm/retval-arm.S, test cases/vala/26 vala and asm/retval-x86.S, test cases/vala/26 vala and asm/retval-x86_64.S, test cases/vala/26 vala and asm/symbol-underscore.h
Because vala is not listed in clike_langs, is_source(fname) is returning False for Vala source files.  Therefore, extract_all_objects() is completely empty for Vala programs.
This had been fixed before but it regressed, so I'm also adding a new testcase (slightly hackish, but effective).
Fixes #791
=> vala: fix extract_all_objects() result

.travis.yml, run_tests.py
There is a lot of overhead for each travis job, because docker pull
takes 3 minutes. Each cross test takes 3-4 minutes.
To make things worse, sometimes Dockerhub is slow and docker pull takes
longer than 3 minutes.
=> run_tests: Run all cross tests together

docs/markdown/Build-options.md, mesonbuild/backend/vs2010backend.py, mesonbuild/coredata.py
Implements "startup project" in visual studio using a new backend specific option `backend_startup_project`.
The target specified will be the first project listed in the solutions file and therefore become the main entrypoint (default executable) for the solution. 
Fixes #3448
=> Implements Visual studio startup project

mesonbuild/dependencies/ui.py
The windows Qt installer doesn't ship with suffixed versions of the qt
tools.
=> modules/qt: check for un-suffixed moc,rcc,uic on windows

mesonbuild/modules/gnome.py, mesonbuild/scripts/gtkdochelper.py
All paths in CFLAGS are relative to build_root, so current directory must be there when invoking gtkdoc-scangobj.
This seems to be enough to fix the build of gobject doc. The only side effect I know is `<module>-scan.c` file is created in `build_root` instead of `abs_out`, I don't think it's a big deal, but `gtkdoc-scangobj` could be modified to write that file in `output_dir`, I think it should like all other files it creates.
However, gio doc still fails, because it pass `gobject_typesfile : 'gio.types'` where gobject pass `gobject_typesfile : join_paths(meson.current_source_dir(), 'gobject.types')`. I think the correct syntax to use is `gobject_typesfile : files('gio.types')` and that works.
=> gtkdoc: Run gtkdoc-scangobj command from build directory

mesonbuild/mtest.py, test cases/failing test/2 signal/main.c, test cases/failing test/2 signal/meson.build, test cases/failing test/3 ambiguous/main.c, test cases/failing test/3 ambiguous/meson.build, test cases/failing test/3 ambiguous/test_runner.sh
When a test fails due to a signal (e.g., SIGSEGV) it can be somewhat
mysterious why the test failed. Also, even when a test fails due to a
non-zero exit status it would help if the exit status was reported. This
augments the result string to include the non-zero exit status or
signal number and name.
Resolves #3642
=> Report exit status or signal that killed the test

docs/markdown/Build-options.md, docs/markdown/Reference-manual.md, docs/markdown/snippets/feature_options.md, mesonbuild/coredata.py, mesonbuild/interpreter.py, mesonbuild/optinterpreter.py, test cases/common/203 feature option/meson.build, test cases/common/203 feature option/meson_options.txt, test cases/common/204 feature option disabled/meson.build, test cases/common/204 feature option disabled/meson_options.txt
Many projects need a tristate option, often named `enabled`, `disabled` and `auto`.
- `enabled` means the feature must be built, and if dependencies are missing it should abort.
- `disabled` means the feature must not be built even if dependencies are found.
- `auto` means the feature should be built only if dependencies are found, skip it otherwise.
This could already be achieved with a combo option:
```meson
opt = get_option('feature')
if opt == 'required'
dep = dependency('foo', required: true)
elif opt == 'not-required'
dep = dependency('foo', required: false)
else
dep = Disabler()
endif
app = executable('app', 'main.c', dependencies : [dep])  
```
But it is much nicer to do:
```meson
dep = dependency('foo', required: get_option('feature'))
app = executable('app', 'main.c', …
```
=> Add tristate user option

test cases/nasm/1 configure file/meson.build
We were hitting the problem described by:
https://stackoverflow.com/questions/43367427/32-bit-absolute-addresses-no-longer-allowed-in-x86-64-linux
See the first answer for a detailed explanation
Fixes https://github.com/mesonbuild/meson/issues/3707
=> nasm test: use -fno-pie -no-pie

mesonbuild/compilers/compilers.py, mesonbuild/interpreter.py
Raise an InterpreterError for a clean error message if get_define is not supported by the compiler.
Fixes #3731
=> Test if compiler supports get_define.

docs/markdown/Reference-manual.md, docs/markdown/snippets/deprecate_build_always.md, mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/interpreter.py
Setting `build_always` should just mark the target so that it is always
considered out-of-date. It should not automatically be added to the
default targets.
One can still set `build_by_default` to also have this behaviour.
fixes #1942
=> No longer build `build_always` targets by default

mesonbuild/modules/gnome.py
If you give the result of `gdbus_codegen` only one file is added to the list when all should be added
Helps to fix #3655
=> generate_gir: Add all the files provided by the CustomTarget

mesonbuild/coredata.py, run_unittests.py
It used to be non-fatal warnings but recent command line refactor made
it fatal. It looks like GNOME continuous would break with this change.
To avoid delaying upcoming 0.47.0 release adoption, let's downgrade this
back to warning for now and reconsider after the release.
=> Downgrade unknown option from exception to warning

mesonbuild/backend/ninjabackend.py
I checked the original commit, and that space should be there.
=> ninjabackend: Obvious typo, missing space

docs/markdown/Reference-tables.md, mesonbuild/environment.py, run_unittests.py
A first draft for issue #3751.
Maintain a list in the source of known CPU families, and validate:
1. The documentation matches
2. The detected cpu_family is listed
3. The specified cpu_family in the cross file is listed
If (2) or (3) fail, warn the user.
The commit messages do need work, this is more for feedback that the direction is good.
=> Validate cpu_family (#3751)

mesonbuild/scripts/gtkdochelper.py
The helper is told what CC to use already, but doesn't pass it to gtkdoc-scangobj.
=> gtkdochelper: pass CC to gtkdoc-scangobj

data/com.mesonbuild.install.policy, docs/markdown/Installing.md, docs/markdown/snippets/install_command.md, mesonbuild/backend/ninjabackend.py, mesonbuild/mesonmain.py, mesonbuild/minstall.py
*Not finished yet.*
Make installing a top level command that can be invoked with `meson install`. This allows us to add more functionality to the install command in the same way as we did to the test command. In a similar way you can tell the install command to not rebuild before running the install for those who really know what they are doing.
The primary use case is something like `meson install --only-changed` or something like that, which checks each file to be copied, and only does the copy if the target is either non-existing or is older than the file to be copied.
=> Made install a top level Meson command.

cross/armclang.txt, docs/markdown/Reference-tables.md, docs/markdown/snippets/armclang-cross.md, mesonbuild/compilers/__init__.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/environment.py
- The changes include support for cross-compiling C and C++ code with ARMCLANG.
- 'armlink' is used as linker internally, so the path to armlink should be set in the user environment PATH variable before running meson.
- Building shareable libraries is not supported with current implementation.
- The PIC support related options are expected to be added by user explicitly.
- The current implementation doesn't have support for compiling assembly files with arm syntax and only supports gnu syntax.
- The 'target' compiler command line option is required to be set for running the sanity check, so passing this option from cross-file, cross/armclang.txt.
The changes tested on Windows with ARM compiler version 6.5(MDK 5.21).
The attached files are the cross test results obtained from running the …
=> Added ARMCLANG compiler support for C/C++

mesonbuild/interpreter.py, mesonbuild/mesonmain.py
This is my suggestion on how to make it more obvious that a change of the default value did not change the current value.
Prints something like below if cpp_std is changed to c++11 but was c++14 before.
```
Option cpp_std is: c++14 [default: c++11]
```
Fixes #3734
=> Print default option values that don't match the current value

mesonbuild/backend/ninjabackend.py, mesonbuild/linkers.py
ninja chokes when building FFmpeg's static libraries, as the
command line can be larger than 32000.
This was disabled on purpose in #1649, but the rsp syntax was
different: this commit makes it so the options and output file
are still passed on the command line, gcc-ar didn't work
otherwise.
@nirbheek , no test was added as part of the commit that disabled this, can you maybe check whether this still breaks the original case? If so, we'll need to find another solution, incrementally building the archive file could be one but I'm wary of the potential performance hit.
=> ArLinker: Use response files on Windows

mesonbuild/mesonmain.py, msi/createmsi.py
Seems to work for me. I created an installer of this version, which [can be downloaded from here](https://www.dropbox.com/s/cv77i0l38ha8i88/meson-0.47.0.1-TRIAL-64.msi?dl=0). **Note**: use that only for testing this bug, it's not supported for any other use.
=> Fix glib build when using MSI installer. Closes #3762.

docs/markdown/Reference-manual.md
We mention this is equivalent to setting both build_by_default and
build_always_stale in the release note, and in the warning emitted when it's
used, but not in the reference manual.
=> Refine documentation for build_always [skip ci]

mesonbuild/dependencies/base.py
The name splitting was wrong and would incorrectly handle folders
with two dots, like `Foo.framework.dSYM` and treat this as `Foo` instead
of `Foo.framework`, which would lead to meson detecting dSYM bundles
as frameworks and try to use those like a framework, which is wrong.
Fix #3793
=> Fix ExtraFrameworkDependency framework detection

docs/markdown/Build-options.md, docs/markdown/snippets/empty-array-opts.md, mesonbuild/coredata.py, run_unittests.py
Currently the former will be parsed as `['']`, while the latter is parsed
as `[]` in python. This makes for some obnoxious special handling
depending on what the user passes. This is even more obnoxious since for
string type arguments this doesn't require special handling.
=> Options: treat array option -Dopt= and -Dopt=[] as equivalent

mesonbuild/compilers/d.py
Hi!
The comment in the patch describes the issue already, basically.
The LDC D compiler has a `-link-defaultlib*` flag to change standard library linking behavior, and users in some occasions want to add that flag manually to `link_args`. The automatic GCC/Clang --> LDC/DMD flag rewriting code thinks the defaultlib flag is for linking a library though (it starts with `-l` afterall...), so incorrectly prepends a `-L`.
This patch prevents the issue from happening and makes Meson not touch this special flag in case it gets passed to LDC.
=> d: Don't fail if -link-defaultlib is manually added to the LDC link args

data/syntax-highlighting/emacs/meson.el
I don't know what was the reasoning behind the creation of `meson-comment-dwim`.
The functionality is already provided/mapped by `comment-dwim` if you setup `comment-start` and `comment-end` correctly. Also other functions like `comment-kill` will work as expected instead of raising an error:
```
Debugger entered--Lisp error: (error "No comment syntax defined")
signal(error ("No comment syntax defined"))
error("No comment syntax defined")
comment-normalize-vars()
kill-comment(nil)
```
Also provide a `FEATURE`  footer to prevent:
```
(require 'meson)
*** Eval error ***  Loading file /usr/share/emacs/site-lisp/meson.el failed to provide feature ‘meson’
```
=> Emacs: correctly setup Emacs `comment-start` and `comment-end`

mesonbuild/compilers/c.py
When find_library is used to find dependencies, meson checks all paths for
libraries with all prefixes that could match. This means that when we are
compiling with -m32 on a 64-bit system, meson will find 64-bit libraries and
assumes that they will work. Naturally that is not the case.
The obvious fix is to do a test link against those libraries, but the extra
wrinkle here is that we need to do a "whole link" so as to test the static
libs. A check with gcc+ld on linux shows that unless there are unresolved
symbols from the main.c file, the static library is never checked so we avoid
the error from an incompatible library.
=> fix find_library when cross-compiling 32-bit on 64-bit systems

mesonbuild/interpreter.py, test cases/common/171 not-found dependency/meson.build, test cases/common/171 not-found dependency/subprojects/trivial/meson.build, test cases/common/171 not-found dependency/subprojects/trivial/trivial.c, test cases/failing/80 subproj dependency not-found and required/meson.build
Also adjust documentation so we don't appear to recommend writing
dependency('', fallback: ['subproject', 'dep']) over
subproject('subproject').get_variable('dep').
Also extend a test case to cover this.
=> Fix handling of dependency('', fallback: ['subproject', 'dep'])

mesonbuild/build.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/ui.py, mesonbuild/interpreter.py, mesonbuild/modules/windows.py, run_unittests.py, test cases/unit/12 cross prog/meson.build
This is accepted by all other binaries in the cross file. With this
change, we also don't check whether the specified command exists at
configure time, but that's probably a feature anyway.
Fixes https://github.com/mesonbuild/meson/issues/3737
=> Allow command lists for find_program cross file overrides

mesonbuild/dependencies/base.py, mesonbuild/dependencies/boost.py, mesonbuild/dependencies/dev.py, mesonbuild/modules/gnome.py, test cases/frameworks/22 gir link order/fake-gthread/fake-gthread.c, test cases/frameworks/22 gir link order/fake-gthread/fake-gthread.h, test cases/frameworks/22 gir link order/fake-gthread/meson.build, test cases/frameworks/22 gir link order/get-prgname/get-prgname.c, test cases/frameworks/22 gir link order/get-prgname/get-prgname.h, test cases/frameworks/22 gir link order/get-prgname/meson.build, test cases/frameworks/22 gir link order/meson-sample.c, test cases/frameworks/22 gir link order/meson-sample.h, test cases/frameworks/22 gir link order/meson.build
This is a follow-up of https://github.com/mesonbuild/meson/issues/1718 and https://github.com/mesonbuild/meson/pull/1932. It fixes appstream-glib gir generation failure and gst-plugins-base gtk-doc build error for me in JHBuild on FreeBSD.
When an older version of the library being built is installed in the
same prefix as external dependencies, we have to be careful to construct
the linker or compiler command line. If a -L flag from external
dependencoes comes before a -L flag pointing to builddir, it is possible
for the linker to load older libraries from the installation prefix
instead of the newly built ones, which is likely to cause undefined
reference error.
Since the order of dependencies is not significant, we cannot expect
internal dependencies to appear before external …
=> gnome: Distinguish between internal and external linker flags

mesonbuild/build.py, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/mesonlib.py, mesonbuild/modules/__init__.py, mesonbuild/modules/python.py, mesonbuild/modules/python3.py, run_unittests.py
The decorators now handle correctly the kwargs.
I'm not really fond of the dummy function
```
+        def build_target_decorator_caller(self, node, args, kwargs):
+            return True 
```
But it's required to comply to the `_get_callee_args`. Or else we should duplicate the `@FeatureNewKwargs` between all the build targets.
=> Feature fixes

mesonbuild/compilers/c.py
Rather than storing in the cache of search paths the full list returned
from the compiler and having each call ignore the non-existent ones, remove
from the list all non-existent ones before returning to the caching function.
=> prune nonexistent dirs from library search path

docs/markdown/Users.md
libmodulemd is a GObject Introspected C library using meson to build and generate gtk-doc HTML.
=> Add libmodulemd to the Users list

mesonbuild/compilers/c.py, test cases/common/146 C and CPP link/foo.cpp, test cases/common/146 C and CPP link/foobar.c
Paths provided to us by the user or by pkg-config can be (and must be)
assumed to be usable since they might not be usable standalone.
Closes https://github.com/mesonbuild/meson/issues/3832
=> find_library: Only run link test on system dirs

mesonbuild/minstall.py
If run `meson install` with an unprivillaged user, polkit will ask for password.  But then `meson` would complain:
meson install: error: unrecognized arguments: /home/xry111/gnome-3.28/epiphany-3.28.1/build
Add `-C` option to the meson command with `pkexec` to fix this issue.
=> Fix pkexec command for installation via polkit

docs/markdown/Reference-manual.md, run_unittests.py
commit d11c91ef4d0b0dfec103be0499a2fce4906744af
run_unittests.py: Test that empty cdata subst are actually done
Improved test for https://github.com/mesonbuild/meson/issues/3826
commit a846db065b7e0aeb1cbe1095f0f8d4924c3e2c63
meson.add_install_script: Move notes section up [skip ci]
The notes section of add_install_script somehow got separated, which
meant that no one reads it anymore.
Also rephrase it a bit to clarify that scripts *MUST* handle DESTDIR
correctly to mirror what Meson does, and how.
=> run_unittests.py: Test that empty cdata subst are actually done

mesonbuild/modules/gnome.py, test cases/frameworks/10 gtk-doc/doc/meson.build, test cases/frameworks/10 gtk-doc/installed_files.txt
Causes the value to be expanded to current source directory.
Fixes https://github.com/mesonbuild/meson/issues/3829
=> gnome.gtkdoc: Don't treat install_dir as a file option

docs/markdown/Reference-tables.md, mesonbuild/environment.py
Instead of exposing the endianness in the CPU family, canonicalise the CPU
family to just "ppc64" to match MIPS (which is also bi-endian).
Part of the work for #3842.
=> Canonicalise 64-bit PowerPC CPU families to "ppc64"

mesonbuild/build.py, mesonbuild/coredata.py, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/mesonlib.py, mesonbuild/mlog.py, mesonbuild/modules/gnome.py, run_unittests.py, test cases/common/16 configure file/meson.build
commit fbcf852f626ed10ae5060b3b9b55c626e72002e5
Print a more usable message when a subproject fails to configure
Instead of just printing the message in the exception, if it's
a MesonException, also print the file and the line number. If it's an
unknown exception, print the entire traceback so that we can pin-point
what the Meson bug causing it is.
commit 6d57f131d5a42c92538c10fffacedebbe93c7c3b
Raise a MesonException when substituting an invalid value
Avoids throwing a traceback. Also, warn when setting such a value.
commit 3ea8d05ce8d568f813f6f7704d565727adf1c446
Add new method: mlog.deprecation()
Instead of constructing it manually, use a helper.
=> More usable subproject error messages

docs/markdown/Reference-manual.md, mesonbuild/dependencies/base.py, mesonbuild/interpreter.py, test cases/common/146 C and CPP link/meson.build
For some reason this was missing, but it should've always existed since `cc.find_library()` returns an object that is internally an ExternalDependency instance.
@jpakkane I'm thinking we should add this to the stable release even though it's a new feature because it's a really simple one that should've already existed. What do you think?
=> Add missing method on external library object: type_name()

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/c.py, mesonbuild/compilers/fortran.py, mesonbuild/mesonlib.py, run_unittests.py
commit e75f43a87e86051f927c462dce30a31a189ecbc3
find_library: Fix manual searching on OpenBSD
On OpenBSD, shared libraries are called libfoo.so.X.Y where X is the
major version and Y is the minor version. We were assuming that it's
libfoo.so and not finding shared libraries at all while doing manual
searching, which meant we'd link statically instead.
See: https://www.openbsd.org/faq/ports/specialtopics.html#SharedLibs
Now we use file globbing to do file searching, and pick the first one
that's found.
Closes https://github.com/mesonbuild/meson/issues/3844
commit 06e87d19bea88e5c74c9eec0e37d5b58d1321749
get_library_naming: Use templates instead of suffix/prefix pairs
This commit does not change functionality, and merely sets the
groundwork for a more flexibly naming implementation. …
=> Fix searching of shared libraries on OpenBSD

mesonbuild/compilers/c.py, run_unittests.py
We need to pick the library with the highest version, which is what the OpenBSD linker also does.
https://github.com/mesonbuild/meson/issues/3570#issuecomment-403638752
CCing: @kernigh and @ajacoutot
=> find_library: Validate and sort globbed shared library files

docs/markdown/Continuous-Integration.md
Merge it or not, after a lot of fiddling around and finally getting it to work I just wanted to get it out there.
=> docs: adds a non-docker travis example

mesonbuild/compilers/cpp.py
'c++17' and 'gnu++98' were concatenated due to a missing comma
=> Avoid concatenating two options in list

docs/markdown/snippets/configure_file_overwrite_warning.md, mesonbuild/interpreter.py, run_unittests.py, test cases/common/16 configure file/meson.build, test cases/common/16 configure file/subdir/meson.build
If two calls to configure_file write to the same output file, print a warning. The warning contains the line number of the first call and the line number of the current call.
Fixes: #3714
=> Check if calls to configure_file write to the same output file.

docs/markdown/Reference-tables.md, mesonbuild/environment.py
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> mesonbuild: Recognise risc-v architecture

mesonbuild/modules/python.py
Meson tries to find the interpreter path through the "py" launcher on Windows in all
cases which breaks if meson is run under MSYS2 and an official CPython is installed as well.
MSYS2 Python doesn't install a py launcher which results in meson finding the system one instead
even though python2/python3 is in PATH.
Always check if the interpreter name is in PATH before falling back to checking the py launcher.
=> python.find_installation: only try to find python with the py launcher if it isn't in PATH

mesonbuild/modules/gnome.py
asan must be first in ldflags and this order was lost in cb36add970d448f8b4ace7e4dc6028e5441bccd7
So this is the most simple solution of just putting it first in internal_ldflags (maybe not ideal).
See https://github.com/mesonbuild/meson/issues/2117#issuecomment-408560838
=> gnome: Fix building gir with asan again

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/compilers/c.py, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/base.py, mesonbuild/environment.py, mesonbuild/interpreter.py, mesonbuild/mesonlib.py, mesonbuild/mtest.py, mesonbuild/scripts/meson_exe.py, run_tests.py, run_unittests.py, test cases/unit/35 exe_wrapper behaviour/broken-cross.txt, test cases/unit/35 exe_wrapper behaviour/meson.build, test cases/unit/35 exe_wrapper behaviour/meson_options.txt, test cases/unit/35 exe_wrapper behaviour/prog.c
commit a4f729013c0eb4db1eb551046e74ed617c58717e
cross: Be more permissive about not-found exe_wrapper
We used to immediately try to use whatever exe_wrapper was defined in
the cross file, but some people generate the cross file once and use
it for several projects, most of which do not even need an exe wrapper
to build.
Now we're a bit more resilient. We quietly fall back to using
non-exe-wrapper paths for compiler checks and skip the sanity check.
However, if some code needs the exe wrapper, f.ex., if you run a built
executable using custom_target() or run_target(), we will error out
during setup.
Tests will, of course, continue to error out when you run them if the
exe wrapper was not found. We don't want people's tests to silently
"pass" (aka skip) because of a bad CI setup.
Closes …
=> Be more permissive about not-found exe_wrapper

mesonbuild/modules/gnome.py, mesonbuild/scripts/gtkdochelper.py
gtkdoc-scangobj has a --run argument that specifies a wrapper to be used when
executing the GObject scanner.  Typically this can be libtool but it is also
useful in cross-compilation environments.
This patch adds support for this argument to the gtkdochelper so that tools
using the helper can pass --run.
=> scripts/gtkdochelper: add support for --run

docs/markdown/Reference-manual.md, docs/markdown/snippets/custom_target_console_pool.md, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/interpreter.py
Ninja buffers all commands and prints them only after they are complete. Because of this, long-running commands such as `cargo build` show no output at all and it's impossible to know if the command is merely taking too long or is stuck somewhere.
To cater to such use-cases, Ninja has a 'pool' with depth 1 called 'console', and all processes in this pool have the following properties:
1. stdout is connected to the program, so output can be seen in real-time
2. The output of all other commands is buffered and displayed after a command in this pool finishes running
3. Commands in this pool are executed serially (normal commands continue to run in the background)
This feature is available since Ninja v1.5
https://ninja-build.org/manual.html#_the_literal_console_literal_pool
=> custom targets: Add a 'console' kwarg for long-running commands

mesonbuild/dependencies/boost.py
Boost discovery for MSVC is unable to handle Boost versions >1.64. In Boost versions 1.65+, an architecture tag was added to the abi. This pull request checks for the special case of Boost >1.64 using MSVC compiler and then adds the appropriate arch tag to the abi.
=> Updated boost discovery to handle version >= 1.65 for MSVC

.travis.yml
Since [1], OSX builds on travis fail with:
Error: Refusing to uninstall /usr/local/Cellar/python/3.6.5_1
because it is required by gdal, numpy, postgis, which are currently installed.
Furthermore, python3 is now installed in the image.
Revise #3163
[1] https://blog.travis-ci.com/2018-07-19-xcode9-4-default-announce
=> Fix .travis.yml for updated OSX image

docs/markdown/Reference-manual.md
check_header method was added in compiler object in version 0.47. Documentation needs to be updated for this.
=> Clarify version for check_header, fixes #3974

__main__.py, run_meson_command_tests.py
0a035de removed main from meson.py breaking the call from __main__.py.
This causes zipapps to fail, since the call to meson.main() obviously does not work.
Copy the invocation from meson.py fixes this issue.
=> Fix __main__.py for zipapp to work

mesonbuild/scripts/gtkdochelper.py
The code was adding the library paths to LD_LIBRARY_PATH, but that
doesn't work on Windows where they need to be added to PATH instead.
Move the environ handling into gtkdoc_run_check() and add paths to PATH
instead of LD_LIBRARY_PATH when on Windows.
This fixes the gtk-doc build for glib on Windows
(in case glib isn't installed already)
=> gtkdoc: set PATH on Windows when executing gtkdoc-scangobj. Fixes #3307

mesonbuild/interpreter.py
get_pkgconfig_variable() takes a 'default' keyword
=> Fix missing permitted kwarg

mesonbuild/mesonlib.py
I got a backtrace when I had a cpp file in a c project. I think it is better to print a nice error message.
before:
```
File "/home/niklas/git/meson/mesonbuild/mesonmain.py", line 351, in run
app.generate()
File "/home/niklas/git/meson/mesonbuild/mesonmain.py", line 117, in generate
File "/home/niklas/git/meson/mesonbuild/mesonmain.py", line 166, in _generate
intr.backend.generate(intr)
File "/home/niklas/git/meson/mesonbuild/backend/ninjabackend.py", line 224, in generate
self.generate_target(t, outfile)
File "/home/niklas/git/meson/mesonbuild/backend/ninjabackend.py", line 472, in generate_target
obj_list.append(self.generate_single_compile(target, outfile, src, False, [], header_deps))
File …
```
=> Prints error message instead of backtrace on fail

data/syntax-highlighting/vim/syntax/meson.vim, mesonbuild/interpreter.py, run_unittests.py
Needs a `mock` kwarg to Interpreter to not do any parsing of build files, but only setup the builtins and functions.
Also consolidate the documentation and data tests into one class.
I noticed this a while ago, and decided to write a test for it while I was sufficiently annoyed by it :smile:
=> Test that vim syntax highlighting is up-to-date

mesonbuild/compilers/c.py, mesonbuild/dependencies/base.py, mesonbuild/mesonlib.py, run_unittests.py
We were searching the library paths in the reverse order, which meant that we'd pick libraries from the wrong prefix.
Closes https://github.com/mesonbuild/meson/issues/3951
=> PkgConfigDependency: Fix library path search order

mesonbuild/interpreter.py, test cases/common/176 subproject nested subproject dirs/contrib/subprojects/beta/meson.build, test cases/common/176 subproject nested subproject dirs/meson.build
Otherwise we get an error while checking the subproject version:
Uncomparable version string 'none'.
If the dependency was found as a not-found dependency in the
subproject and is not required, just take it.
=> Don't check version for fallback not-found dependency

mesonbuild/backend/backends.py, mesonbuild/compilers/c.py, mesonbuild/minstall.py, test cases/common/125 shared module/installed_files.txt, test cases/common/125 shared module/meson.build, test cases/common/125 shared module/nosyms.c
commit 9abbf2b37082435e1d176c260bdd278cf802e72a
msvc: Don't add dynamic link args, they're ignored
And they print a linker warning about unknown args.
commit 91a528ac19eb4cef48f7933ee7467a487adfb9f7
Don't require an import library for shared modules
Shared modules may be resource-only DLLs, or might automatically
self-initialize using C constructors or WinMain at DLL load time.
When an import library is not found for a shared module, just print
a message about it instead of erroring out.
=> Dont require implib for shared modules at install time

.appveyor.yml
Appveyor CI gets backlogged for several hours at a time with the most
trivial of usage. Nuke it. It can be re-added if people really need it
and are willing to sponsor extra jobs on Appveyor.
=> appveyor.yml: Nuke VS 2010 CI configuration

mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/dependencies/base.py, run_unittests.py
`-lc` `-lm` and `-lpthread` are special linker arguments that should never
be resolved to on-disk libraries.
Closes https://github.com/mesonbuild/meson/issues/3879
=> PkgConfigDependency: Don't try to resolve internal compiler libs

mesonbuild/dependencies/base.py, mesonbuild/dependencies/boost.py, mesonbuild/dependencies/dev.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/ui.py, run_unittests.py
Motivated by the observation in #3095 that currently, we don't report if a dependency was not found before trying a fallback subproject.
(at the moment, if a dependency isn't found, `find_external_dependency()` either (i) logs that it wasn't found, if it is not required, or (ii) raises an exception, if it is required (that exception being held by `func_dependency()` while it checks if a workable fallback exists))
This is hard to fix straightforwardly because, at the moment, the `ExternalDependency`-derived constructor called by `find_external_dependency()` is responsible for reporting success or raising an exception if not found, but required.
This patch series consolidates that reporting and checking in `find_external_dependency()`.
This enables always logging the result of the …
=> Consolidate reporting the result of a dependency check

.appveyor.yml, mesonbuild/mesonmain.py, run_meson_command_tests.py, setup.py
Thanks to Rafael Rivera for the suggestion
Fixes https://github.com/mesonbuild/meson/issues/1877
=> Install meson.exe as the entrypoint on Windows

docs/markdown/Gnome-module.md, docs/markdown/snippets/generate_gir_multiple_libraries.md, mesonbuild/modules/gnome.py, test cases/frameworks/7 gnome/gir/meson-sample2.c, test cases/frameworks/7 gnome/gir/meson-sample2.h, test cases/frameworks/7 gnome/gir/meson.build, test cases/frameworks/7 gnome/gir/prog.py
This addresses #3688 , some significant refactoring is done in a first commit, and the functionality implemented in the second.
=> gnome.generate_gir: refactor and allow passing multiple libraries

mesonbuild/environment.py, mesonbuild/linkers.py
The ARM's AR linker does not support rsp files. So, a separate Linker class is added for ARM compiler.
=> Adding a new AR Linker Class for the ARM Compiler.

mesonbuild/interpreter.py, test cases/common/175 yield/meson.build, test cases/common/175 yield/meson_options.txt, test cases/common/175 yield/subprojects/sub/meson.build, test cases/common/175 yield/subprojects/sub/meson_options.txt
Earlier, we would replace the subproject option with the parent
project's option, which is incorrect if the types are not the same.
Now we retain the subproject's option and print a warning. It's not
advisable to issue an error in this case because subproject option
yielding is involuntary for the parent project (option names can match
because of coincidences).
=> Fix yielding when subproject option type is different

run_meson_command_tests.py
Closes https://github.com/mesonbuild/meson/issues/4047
=> meson_command_tests: Don't pass pathlib.Path to open [skip appveyor]

.gitignore, docs/markdown/Builtin-options.md, docs/markdown/snippets/buildtype_toggles.md, mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/cs.py, mesonbuild/compilers/d.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/rust.py, mesonbuild/compilers/swift.py, mesonbuild/compilers/vala.py, mesonbuild/coredata.py, run_unittests.py, test cases/common/126 llvm ir and assembly/meson.build
The current setup of a couple of different build types is a bit limiting. Ideally you'd want to toggle the optimization levels and "debugness" independent of each other. Some people might want to do releases with `-O2` and others with `-O3` for example.
This is a very rudimentary fix showing how a small fraction of this would be done. The full setup would go something like this:
- optimization gets its own option, with values as shown in this MR
- debug gets a boolean switch
- buildtype gets a new value of `custom`
- setting `buildtype` sets also the value of the other two to match current behaviour
- optimization and debug can be set to any value combinations
- if the combination exactly matches some current build type, the value of `builtype` is set to that, otherwise it is set to …
=> Convert buildtype to optimization and debug options

mesonbuild/minstall.py, run_unittests.py, test cases/common/199 install_mode/installed_files.txt, test cases/common/199 install_mode/meson.build
Other fixes for #3914 to ignore setting the ownership and mode for broken symlinks after install.
Unfortunately the best way to do this was to cause some stdlib code duplication, because we need to be able to use `os.chown` with `follow_symlinks` set to `False`, but `shutil.chown` does not support this.
In fact, in general I think we should just never to try to set the ownership of a linked file, as this might be pointing outside the install path (while it's correct to set it only to the link itself), and probably at the same time the same should be for the file-mode of linked files.
=> Fix broken symlinks install when using install_umask or install_mode

test cases/common/195 check header/meson.build
linux/if.h can't be included directly because of a bug:
https://lore.kernel.org/patchwork/patch/762406/
Closes https://github.com/mesonbuild/meson/issues/4053
=> tests/check header: Use linux/socket.h instead of if.h [skip appveyor]

.travis.yml, mesonbuild/dependencies/base.py, run_unittests.py
These weren't caught by the CI because we have pkg-config on it, and these were testing non-pkg-config codepaths. The unity build on macOS now doesn't have pkg-config to ensure that the codepath is tested.
=> Fix various small test failures on macOS

test cases/d/10 d cpp/libfile.d
It is undefined behaviour to call D I/O functions without initializing D runtime first. Simplify the test so it will work in all platforms.
Fixes #4049, also required for #3981.
=> Remove dependency to D runtime in mixed language tests

mesonbuild/compilers/cpp.py
* GCC 4.8 and Clang 3.2, 3.3, 3.4 only understand
`-std={c,gnu}++1y` for enabling C++14 dialects.
GCC 4.8 is especially important as it is the basis
of RHEL/CentOS 7.
@nirbheek as discussed
=> Remap -std=c++14 dialect names for older compilers

mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py
- Use Maximum Optimization (Favor Size) for `minsize`.
- Enable Function-Level Linking so unused code can be omitted.
With `minsize` on x86 this reduces the size of a statically linked Vala
compiler binary from 5 MB down to just 2.3 MB.
The addition of `/O1` next to `/Os` is because these two options are
distinct in Visual Studio's GUI:
I also verified the impact of different switches for `minsize`:
=> compilers: Reduce sizes of MSVC linked binaries

mesonbuild/wrap/__init__.py
We where currently printing the list as WrapMode.<name>, while what we
wanted is just the name. This made --help slightly confusing.
This changes --help command from printing:
--wrap-mode {WrapMode.default,WrapMode.nofallback,WrapMode.nodownload,WrapMode.forcefallback}
to:
--wrap-mode {default,nofallback,nodownload,forcefallback}
Fixes issue #4067
=> help: Fix printing list of wrap mode

ghwt.py, manual tests/4 standalone binaries/build_windows_package.py, mesonbuild/wrap/wrap.py
a trivial patch for solving issue #4087 .
it would be better if we had using os.environ for setting thin behaviour details.
and it doesn't save from "Slow HTTP DoS attack".
but it's pretty better than nothing :-) ..
=> using urlopen() with explicit timeout

mesonbuild/modules/windows.py
Remove some spurious calls to the format() function, left by mistake after
c2f37853
=> Remove some spurious calls to the format() function

mesonbuild/environment.py
This will reject `ldmd` and `gdmd`. They are versions of `ldc` and `gdc`, respectively, that use `dmd`'s frontend. Right now they are being wrongly detected as `ldc`/`gdc`. Even if we fixed that, thay are not fully compatible with `DmdDCompiler` so that would need to be patched as well. As we discussed in the IRC, there's no point in adding support for them as they are simply frontends.
=> d: disallow dmd frontends (ldmd and gdc)

mesonbuild/interpreter.py, run_unittests.py, test cases/common/206 subproject with features/meson.build, test cases/common/206 subproject with features/meson_options.txt, test cases/common/206 subproject with features/nothing.c, test cases/common/206 subproject with features/subprojects/auto_sub_with_missing_dep/meson.build, test cases/common/206 subproject with features/subprojects/disabled_sub/lib/meson.build, test cases/common/206 subproject with features/subprojects/disabled_sub/lib/sub.c, test cases/common/206 subproject with features/subprojects/disabled_sub/lib/sub.h, test cases/common/206 subproject with features/subprojects/disabled_sub/meson.build, test cases/common/206 subproject with features/subprojects/sub/lib/meson.build, test cases/common/206 subproject with features/subprojects/sub/lib/sub.c, test cases/common/206 subproject with features/subprojects/sub/lib/sub.h, test cases/common/206 subproject with features/subprojects/sub/meson.build
Allowing to use the new "feature" option type and allowing not to fail
on subproject if it is not necessary to fail.
By default subprojects are "required" so previous behaviour is not
changed.
Fixes #3880
=> Add a `required` argument to `subproject`

docs/markdown/Reference-manual.md, docs/markdown/Reference-tables.md, docs/markdown/snippets/distscript.md, mesonbuild/build.py, mesonbuild/interpreter.py, mesonbuild/scripts/dist.py, run_unittests.py, test cases/unit/35 dist script/meson.build, test cases/unit/35 dist script/prog.c, test cases/unit/35 dist script/replacer.py
The only open question here is subprojects. I made it a hard error currently for maximum future flexibility. But what should it do? For example if your subproject is not a part of the master project (i.e. a monorepo) then you don't want the scripts run. But if it is you do.
=> Add support for custom dist scripts.

mesonbuild/environment.py
Fix how the `DC` env var is handled in #4085.
=> Fix wrong behaviour in #4085

mesonbuild/compilers/compilers.py, run_unittests.py
Treat it the same as `-lfoo` by deduping and adding to `--start/end-group`
Reported at https://gitlab.gnome.org/GNOME/glib/issues/1496
We don't do any advanced transformation for MSVC or de-dup because this is a very rare syntax.
=> CompilerArgs: -Wl,-lfoo is also a valid way to pass a library

mesonbuild/compilers/compilers.py, test cases/osx/2 library versions/meson.build
* Currently, RPATHs coming from dependencies and
`build_rpath` provided by the user might contain
the same path. Apple's `install_name` tool is
allergic to providing the same argument twice
when removing RPATHs:
`error: install_name_tool: "-delete_rpath /usr/lib" specified more than once`
@nirbheek
=> Deduplicate build-tree RPATHs on macOS

docs/markdown/Reference-manual.md, docs/markdown/snippets/shared_library_darwin_versions.md, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/d.py, run_unittests.py, test cases/osx/2 library versions/installed_files.txt, test cases/osx/2 library versions/meson.build
We now use the `soversion` to set `-compatibility_version` and `-current_version` by default. This is the only sane thing we can do by default because of the restrictions on the values that can be used for compatibility and current version. This is also what cmake does.
Users can override this value with the `darwin_versions:` kwarg, which can be a single value or a two-element list of values. The first one is the compatibility version and the second is the current version.
Fixes https://github.com/mesonbuild/meson/issues/3555
Fixes https://github.com/mesonbuild/meson/issues/1451
~~TODO: docs and tests~~
CCing @SoapGentoo @ePirat
=> Improve support for macOS dylib versioning

mesonbuild/modules/gnome.py, run_unittests.py
The regression was introduced in my recent refactoring of
that method (8377ea4).
This commit simply restores the ordering of the generated
scan_command, ensuring `-lasan` and other internal linker
flags come before `--library` or `--program`
=> gnome: fix generate_gir when linking with libasan

ciimage/Dockerfile, mesonbuild/compilers/d.py, mesonbuild/dependencies/base.py, test cases/failing/85 dub libray/meson.build, test cases/failing/86 dub executable/meson.build, test cases/failing/87 dub compiler/meson.build
fixes #4032: meson now checks properly for the compiler used to compile dub dependencies
fixes #3568: applied the following patch https://paste.debian.net/1039317/
meson now adds flags for native dependencies required by dub modules
meson now checks for the D version implemented by the compiler used to build dub dependencies (execpt gdc which doesn't support this)
=> dub: enhance dependency handling

docs/markdown/Continuous-Integration.md
Also add, how to make meson find Qt5 & Boost
Additional question: Should the `https://www.dropbox.com/s/cyghxjrvgplu7sy/ninja.exe?dl=1` link continue to be used or be replaced by `https://github.com/mesonbuild/cidata/raw/master/ninja.exe` which is used by the appveyor file of this repository?
=> Update appveyor example [skip ci]

mesonbuild/dependencies/dev.py
@jpakkane I've added pkg-config support to GTest and GMock over a year ago (https://github.com/google/googletest/commit/8604c4adac40573f806cfadae44e22f8dfaf212a). For our enterprise codebase and for distributions it makes building and CIs so much easier if we can just use GTest and GMock with pkg-config instead of a hard-coded source path and a raw `find_library` mechanism.
=> GTest & GMock pkgconfig fallback

mesonbuild/wrap/wrap.py
Otherwise, git fiddles with the cmd.exe console's color behaviour and disables it, which causes it to stop interpreting ANSI color codes outputted by meson for colored output.
Effectively, as soon as any subproject is initialized, cmd.exe goes nice coloured output to ugly raw ANSI codes. Example
```
Version: 0.48.0.dev1
Source dir: C:\projects\repos\gst-build.git
Build dir: C:\projects\repos\gst-build.git\build
Project name: All GStreamer modules
Project version: 1.15.0.1
Native C compiler: cl (msvc 19.00.24215.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program uname found: NO
Found pkg-config: C:\Python36-32\Scripts\pkg-config.EXE (0.28)
Dependency libavfilter found: NO
Looking for a fallback subproject for the dependency …
```
=> wrap: Redirect git's stdin to DEVNULL

docs/markdown/snippets/i18n_variable_substitution.md, mesonbuild/modules/i18n.py, test cases/frameworks/6 gettext/data/meson.build, test cases/frameworks/6 gettext/data/test2.desktop.in, test cases/frameworks/6 gettext/installed_files.txt
Previously it wasn't possible to use twice `@BASENAME@` as output in `i18n.merge_file` as the targets would then be named `@BASENAME@_merge`
=> i18n: respect variable substitution for the target name when merging translations

mesonbuild/dependencies/dev.py
Fix fallback code for older (<= 3.8) llvm versions to not be dependent
on readdir() order.
Fixes #4102
=> llvm: fix build flags with older llvm versions

docs/markdown/Reference-manual.md, mesonbuild/interpreter.py, test cases/common/50 subproject subproject/meson.build, test cases/common/50 subproject subproject/subprojects/c/meson.build
Fixes:
meson.build:6:0: ERROR:  Uncomparable version string 'unknown'.
This was previously partially fixed in a8694f4b, which only fixed it
for cached fallback dependencies.
=> Test + fix for not-found dependency fallback version comparison

docs/markdown/snippets/fatal_warnings.md, mesonbuild/mesonmain.py, mesonbuild/mlog.py
This makes any warning message printed by meson raise an exception,
intended to be used by CI and developpers to easily catch deprecation
warnings and other potential issues.
=> Add --fatal-warnings command line option

mesonbuild/compilers/d.py
Fixes linking errors with DMD which slipped through the recent mixed D/C++ test change.
=> D: Fix linking errors with static D libraries on Windows

mesonbuild/backend/backends.py, mesonbuild/compilers/d.py
All the linker related arguments are now handled via '-Wl,' in meson, so the argument translation function knows how to deal with those arguments properly. I also decided to split the OS specific translation logic to different functions, so it's more readable.
I also reverted the change related to static library handling introduced in #4084, because it also affects source and object files and not just library files, and provided alternative way to deal with this: static library files can also be passed to compiler without -L, but in case the user really wants to pass the files to linker, the extra -L is omitted. This should supersede the fix provided in #4080.
Thanks to @ljmf00 I also managed to fix the remaining OSX issues, which are also included here. Some of the test cases still fail, …
=> D: Various improvements to argument translation

docs/markdown/Reference-manual.md, docs/markdown/Reference-tables.md, docs/markdown/snippets/function_attributes.md, mesonbuild/compilers/c.py, mesonbuild/compilers/c_function_attributes.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/interpreter.py, test cases/common/204 function attributes/meson.build
It's fairly common on Linux and *BSD platforms to check for these
attributes existence, so it makes sense to me to have this checking
build into meson itself. Autotools also has a builtin for handling
these, and by building them in we can short circuit cases that we know
that these don't exist (MSVC).
The Intel C Compiler is interesting, it appears that on Linux it has
support for `__attribute__`, but not on windows. Though I didn't test it,
this is based on what google says.
This isn't nearly all of the attributes that GCC supports, but it is all
the attributes that autotools has built in rules for.
=> Add method to check for GCC function attributes

docs/markdown/Windows-module.md, mesonbuild/modules/windows.py
Always honour any windres setting in cross-file (we can't be compiling with
msvc, but this should apply when cross-compiling using gcc or clang)
Always honour WINDRES environment variable
Otherwise look for the resource compiler which is part of the same toolset
as the C or C++ compiler.
Add some commentary on why the conventions for compiled resource file
extensions differ between RC and windres
Also don't try to report non-existent path when we couldn't find the
resource compiler.
=> Improve windows resource compiler executable selection

test cases/frameworks/16 sdl2/meson.build
The OSX framework does not ship with `sdl2-config` et al so skip the tests.
=> Skip some SDL tests when using an OSX framework version.

mesonbuild/backend/backends.py, mesonbuild/build.py
EFL starts to use meson its main repository has 1037 build targets, and i giant list of generated files. The generation of the ninja files took about 1:10 min, after those three commits, we are down to 20 sec.
=> Performance optimize mesons ninja generation

docs/markdown/Quick-guide.md
On Deban, and assuming now on Ubuntu as well, pip3 is only available after installing the python3-pip package. For that case explicitly specified the package during the system installation.
=> Quick Guide add step for python3-pip install

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, run_unittests.py
This improves the backend generation time for gst-build from 7.4s to 6.6s. This is probably all the low-hanging fruit we can get, further improvements will probably require refactoring, moving to `pathlib.Path` or reimplementing `CompilerArgs`:
```
222045    0.551    0.000    1.324    0.000 compilers.py:666(__iadd__)
3691    0.230    0.000    0.885    0.000 ninjabackend.py:99(write)
233560    0.441    0.000    0.701    0.000 posixpath.py:75(join)
882    0.141    0.000    0.636    0.001 backends.py:509(generate_basic_compiler_args)
256301    0.248    0.000    0.576    0.000 compilers.py:562(_can_dedup)
37369    0.035    0.000    0.466    0.000 compilers.py:652(extend_direct)
74650    0.067    0.000    0.431    0.000 compilers.py:641(append_direct)
158153    0.089    0.000    0.405    0.000 …
```
=> Sprinkle functools.lru_cache() in a few more places

mesonbuild/mesonmain.py
Allows to manually reconfigure a project the same way backends would do
(e.g. ninja reconfigure). This has the advantage that new options can be
set using "meson setup --reconfigure -Dfoo=bar" and solve situations
where a project cannot be reconfigured because new options has been
added with the wrong default value.
Fixes #3543.
=> mesonmain: Add --reconfigure argument

mesonbuild/environment.py, mesonbuild/linkers.py
Fallback to using D compilers as static linkers when no suitable static linker were found.
This should fix the linker detection issues in msys2 and cygwin environment discovered with #4158.
=> D: Fix linker detection when static linker is missing

mesonbuild/mesonlib.py, run_unittests.py
Fix the special handling of `>=0.nn` constraints in `project(meson_version:)` for feature checks when the constraint version contains spaces
=> Fix incorrect feature check warning

mesonbuild/compilers/d.py, mesonbuild/dependencies/base.py, mesonbuild/environment.py
Windows 32-bit targets were handled incorrectly, as 'x86' has different meaning on DMD and DUB while building on Windows. This also improves the error messages in dependency detection for wrong architecture and when the dub package was not built.
This should fix the remaining issues detected in #4158
=> D: Improve target architecture handling

docs/markdown/Wrap-dependency-system-manual.md, docs/markdown/snippets/wrap_clone_recursive.md, mesonbuild/wrap/wrap.py
This causes Meson to clone the repo with the `--recursive` flag, pulling all of the submodules automatically.
=> Add 'clone-recursive' option for git wraps (to handle submodules)

mesonbuild/compilers/d.py
Otherwise these arguments would get the `-l` treatment.
=> D: Fix some compiler arguments not getting passed through properly

mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/environment.py, run_unittests.py, test cases/common/204 function attributes/meson.build, test cases/unit/6 std override/meson.build, test cases/unit/6 std override/prog98.cpp
@jpakkane @nirbheek this fixes most of the glaring bugs of GCC and ICC on macOS. The biggest problem is `has_function` on GCC, which still fails to find `alloca`, due to its tricky status as a compiler intrinsic.
=> Fix GCC & ICC on macOS

mesonbuild/compilers/d.py
D compilers are configured to have highest priority when chosing linker
for targets mixing C/C++/D code and before this change meson would fail
to configure gtest target that uses D library as a dependency.
=> Implement thread linker args for D compilers

docs/markdown/Pkgconfig-module.md
Almost every keyword documented here takes this form:
- `foo` bar
with no comma after the keyword. Make `filebase` consistent, and fix a
comma splice.
Fix 'Arbitraty' typo in `libraries` documentation.
=> Pkgconfig-module.md: fix typos [skip ci]

docs/markdown/Gnome-module.md, mesonbuild/modules/gnome.py
There are two issues regarding compiler flags used in one of the steps of `gtkdoc` that executes `gtkdoc-scangobj`.
* compiler arguments from dependencies are ignored.
* there is no way to append custom compiler arguments.
These two commits fixes these both issues.
=> Fix gtkdoc cflags

run_unittests.py
-It tests both Qt4 and Qt5 detection -> qtdependency_pkgconfig_detection
-It doesn't need to skip test if Qt4 isn't found and if Qt5 isn't, the meson.build file already skips the test.
-The regex was outdated and since skipped because of Qt4 not found, it is silently broken for a long time.
https://hephaistos.lpp.polytechnique.fr/teamcity/viewLog.html?guest=1&buildId=34008&buildTypeId=mesonbuild_Fedora&tab=buildLog&_focus=760&state=555#_state=555
https://travis-ci.org/mesonbuild/meson/jobs/429212554#L661
=> Fix broken unit test qt5dependency_pkgconfig_detection

mesonbuild/dependencies/ui.py, run_unittests.py
On Arch Linux the wxgtk3 package doesn't provide wx-config.
=> Also check wx-config-gtk3 when looking for wxWidgets

docs/markdown/Python-3-module.md, docs/markdown/snippets/deprecated_python3_module.md
The new 'python' module is a superset of its features, keeping both is
confusing.
Closes #4168.
=> Doc: Deprecate python3 module [skip ci]

mesonbuild/backend/xcodebackend.py
Xcode now works for at least simple projects.
- Fixes exception when calling `meson build --backend=xcode`
- Fixes some typos and other minor indentation little issues when generating project.pbxproj file
=> Fix `build --backend=xcode`

docs/markdown/Syntax.md
The "if" statement only covers a small set of the possible ways in
which conditionals can be written, since it leaves the use of
"and", "or" and "not" to the "Logical Operations" section. However,
this is likely to be of interest to those reading about "if" statments,
so move the "logical operations" section up to immediately follow it.
This change also puts in the use of the "!=" operator in the example
to widen the variety of combinations shown.
=> syntax guide: move logical ops section beside if statement [skip ci]

mesonbuild/mesonlib.py
The use of ABC classes (like MutableSet) directly from collections is 
deprecated and inpython 3.8 the aliases in collections will be dropped 
and only the ones in collections.abc will remain. collections.abc has 
existed since python 3.3, so there is no backwards compatibility risk.
=> mesonlib: use collections.abc for abc types

docs/markdown/Reference-manual.md
Thanks to PR #3483, set_variable can be used to assign array values.
However, the fact that it cannot be used for arrays before 0.46.1 needs
a mention in the documentation, since otherwise users can get unexpected
dependencies on later meson versions.
=> clarify old behaviour of set_variable in documentation

mesonbuild/compilers/compilers.py
The ARMCC and ARMCLANG compiler classes didn't have get_optimization_args, get_debug_args functions which were being called from ninjabackend.
=> Added functions - get_optimization_args, get_debug_args in ARMCC and ARMCLANG classes.

mesonbuild/dependencies/dev.py
It appears that debian has changed their naming scheme. This might
require revisiting in the future to add llvm-config-7.0 if debian
decides to do that.
=> dependencies/llvm: Add LLVM 7

run_unittests.py
This makes the error go away but not sure if it is the correct fix.
=> Use only basename part in test. Closes #4237.

mesonbuild/mesonmain.py
This is a regression in Meson 0.48.0, commit 674ae46, Meson used to
exit(0) when running setup command in a builddir already configured.
Changing to exit(1) breaks some build tools that does "meson builddir
&& ninja -C builddir".
Closes #4247.
=> Return code 0 when builddir is already configured

mesonbuild/environment.py
When reading the endian from a cross file, validate that the value is either
'big' or 'little'.
=> environment: validate endian value from cross file

mesonbuild/compilers/c.py
GNU binutils ld silently ignores -rpath flags when targeting windows
(and it is already commented within ninjabackend.py that rpath as
concept doesn't exist on windows), and build_rpath_args in
VisualStudioCCompiler also returns an empty array. Therefore skip
this flag altogether.
This fixes linking with lld in MinGW mode, which doesn't support the
rpath flag.
=> Don't add rpath linker flags when building for MinGW

mesonbuild/environment.py
Without this, when one of Meson's parent directories contains
"python", unexpected option "-u" will be passed to Meson.
Fixes #4248
=> environment: Use os.path.basename() when checking mesonlib.meson_command

mesonbuild/compilers/c.py
Using the -pthread argument is not needed with clang when compiling for
darwin, and it results in the warning:
warning: argument unused during compilation: '-pthread'
=> Do not use -pthread with clang for darwin

mesonbuild/backend/backends.py
The end result of that was that when building some gir files in `gst-build` I was getting missing symbols because we were picking the system wide libgstXXX.so library:
```
FAILED: subprojects/gst-plugins-base/gst-libs/gst/video/GstVideo-1.0.gir
/usr/bin/g-ir-scanner -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/lib/libffi-3.2.1/include --no-libtool --namespace=GstVideo --nsversion=1.0 --warn-all --output subprojects/gst-plugins-base/gst-libs/gst/video/GstVideo-1.0.gir '--add-init-section=extern void gst_init(gint*,gchar**);g_setenv("GST_REGISTRY_DISABLE", "yes", TRUE);g_setenv("GST_REGISTRY_1.0", "/home/thiblahute/devel/hotdoc/gnome-devel-docs/build/subprojects/gst-plugins-base/gir_empty_registry.reg", …
```
=> Normalize some path to avoid failling at checking if a path is a system path

docs/markdown/Qt5-module.md, mesonbuild/modules/qt.py
Just like https://github.com/mesonbuild/meson/pull/2529 adds moc_extra_arguments, ui_extra_arguments would be useful to override translator function (hello gettext/i18n).
Will close #4177
=>  Add support for uic_extra_arguments to qt5

mesonbuild/modules/gnome.py
When passing static libraries to `gtkdoc`, they are also appended as shared libraries to `ldflags`, which makes the process to fail.
This has been changed to only append shared libraries to `ldflags`.
Fixes #3935
=> gnome.gtkdoc: Fix static library ldflags

docs/markdown/Reference-tables.md
Autotools will add endianess to the name of the architecture in some
cases (such as ppc64le vs ppc64) meson doesn't do this. It's worth
noting this in the documentation.
=> docs: Add note to cpu_family table about endianess [skip ci]

mesonbuild/backend/xcodebackend.py, test cases/common/14 configure file/meson.build
Hello,
I am trying to fix `test cases/common/14 configure file` when run with `meson build --backend=xcode` 
This case tests that generated .h files are included in header search path (as a compiler flag) when compiling the source code. In Xcode it looks like fixing this is trivial as adding: 
```
SYSTEM_HEADER_SEARCH_PATHS = "/path/to/build/dir/here";
``` 
for each target build configuration. (In `generate_xc_build_configuration`)
Is there a flag or array of generated files path I can look to decide whether add or not `SYSTEM_HEADER_SEARCH_PATHS` for a particular target? I think I should check since it would not be correct to *always* add build folder to the header search path. 
BTW: It looks like not only header files can be created with …
=> Xcode does not include configured files in its header search path

mesonbuild/modules/windows.py
Determine the type of the Windows resource compiler by looking at it's output, not it's name
An alternative solution of #4294
This is slightly more conservative that current code, as it now raises an error if we can't determine the argument type of the resource compiler, rather than just falling into some else clauses...
=> Determine the type of the Windows resource compiler by looking at its output, not its name

mesonbuild/scripts/meson_exe.py
Fixed the lack of stdout being displayed when not in capture mode for meson_exe (meson --internal exe)
This was stopping me seeing important program output for a set of custom_target() steps on windows
=> No stdout from `meson --internal exe` generated by custom_target() when not in capture mode

mesonbuild/mconf.py, mesonbuild/mesonlib.py, mesonbuild/mesonmain.py, mesonbuild/minit.py, mesonbuild/minstall.py, mesonbuild/mintro.py, mesonbuild/msetup.py, mesonbuild/mtest.py, mesonbuild/rewriter.py, mesonbuild/wrap/wraptool.py, run_project_tests.py, run_tests.py
This has the adventage that "meson --help" shows a list of all commands,
making them discoverable. This also reduce the manual parsing of
arguments to the strict minimum needed for backward compatibility.
=> Use a single ArgumentParser for all subcommands

docs/markdown/Reference-manual.md, mesonbuild/interpreter.py, mesonbuild/scripts/dist.py, test cases/unit/35 dist script/meson.build, test cases/unit/35 dist script/replacer.py
`meson.add_dist_script`, introduced in #3906, did not accept any arguments other than script name. Since all other `meson.add_*_script` methods do accept args, this makes the dist script accept them as well.
Closes: https://github.com/mesonbuild/meson/issues/4262
=> Make custom dist scripts accept arguments.

mesonbuild/backend/backends.py
Meson 0.48.0 some validation for using compiled binaries in custom
targets and generators, which is nice. It didn't take into account
though that as long as the OS is the same, some architectures support
running a related architecture natively (x86_64 can run x86 natively,
for example).
This patch introduces a new method to the Backend base class,
can_execute_host_binaries. It attempts to check that the build machine
is capable of running binaries targeting the host architecture, and
allows them to be used in generators and custom targets.
Fixes #4254
=> backends: allow running host arch binaries on compatible build machines

mesonbuild/modules/i18n.py, test cases/frameworks/6 gettext/data/data3/meson.build, test cases/frameworks/6 gettext/data/data3/test.desktop.in, test cases/frameworks/6 gettext/data/meson.build, test cases/frameworks/6 gettext/installed_files.txt
using state.subdir will cause / to be inserted into the target name.
Replace them with __ to future-proof it.
Signed-off-by: Marty E. Plummer <hanetzer@startmail.com>
=> i18n: replace path separator with @

test cases/frameworks/6 gettext/data/data3/meson.build
File "data/data3/meson.build" makes Meson create a target
that contains a path separator.
=> Fix a comment in "test cases/frameworks/6 gettext"

mesonbuild/interpreter.py, run_unittests.py, test cases/common/14 configure file/meson.build
Fixes Issue #4323.
The check to see if a call to configure_file() overwrites the output of
a preceding call should perform the substitution for the output file
before doing the check.
Added tests to ensure the proper behaviour.
=> Substitute output file then check for conflict.

mesonbuild/interpreter.py, test cases/failing/90 subproj not-found dep/meson.build, test cases/failing/90 subproj not-found dep/subprojects/somesubproj/meson.build
When using a subproject as fallback for a required dependency, we should
check if the dependency object we get from the subproject is found.
=> dependency variable from subproject could be not-found

docs/markdown/Users.md
Starting with Juno release, all native vala programs/libs use Meson as build system.
[See blog post](https://medium.com/elementaryos/all-aboard-the-meson-future-hype-train-2b6c478b6b9e) and [official docs](https://elementary.io/docs/code/getting-started#the-build-system).
=> Add ElementaryOS

mesonbuild/compilers/d.py
As discussed on IRC.
Some people want to pass static libraries directly to the linker, which currently does not work for DMD and LDC due to the to-GNU flag translation.
This patch expands the translation list to accommodate for this scenario as well.
=> d: Allow static library to be passed with -L to dmd/ldc

mesonbuild/backend/xcodebackend.py
- Adds support for assembly filed in xcode
- Passes arguments from function `add_project_arguments()` to project
- Fixes `test cases/common/138 c cpp and asm/`
=> More fixes for Xcode: assembly files and add_project_arguments()

mesonbuild/modules/gnome.py
It is possible for compiler flags to include special characters, such as
double quotes which are needed to define macros with -D options. Since
gtkdoc-scangobj uses shlex.split to split arguments passed to --cc,
--ld, --cflags, --ldflags into lists, we can safely use shlex.quote to
properly quote arguments for these options.
This fixes gtk-doc build failure for at-spi2-core.
```
Running custom install script '/home/lantw44/gnome/devinstall/bin/meson --internal gtkdoc --sourcedir=/home/lantw44/gnome/source/at-spi2-core --builddir=/home/lantw44/gnome/build/at-spi2-core --subdir=doc/libatspi --headerdirs=/home/lantw44/gnome/source/at-spi2-core/atspi@@/home/lantw44/gnome/build/at-spi2-core/atspi --mainfile=libatspi-docs.sgml --modulename=libatspi --mode=auto --scanargs=--rebuild-types …
```
=> gnome: Quote arguments passed to gtkdoc-scangobj

mesonbuild/scripts/coverage.py
lcov branch coverage are disabled by default.  So branch
coverage has to be enabled for every stage to make them work.
Fixes https://github.com/mesonbuild/meson/issues/4319
=> coverage: fix lcov branch coverage generation

mesonbuild/modules/gnome.py, test cases/frameworks/7 gnome/resources/res3.txt
This avoids the problem of generated files with the same name as something in source
existing and using the wrong file.
May want to add a test for this.
=> gnome.compile_resources: Put dependency directories before current source dir

docs/markdown/Reference-tables.md, test cases/common/137 get define/meson.build
GNU hurd returns "GNU" as it's system, I think we should lower it, since
no other operating system uses capital letters, even though some of them
properly do (Linux, FreeBSD, etc).
Hurd can't run the project tests because it lacks the primitives to run `concurrent.futures`, half the tests that do run don't pass because `sendmmsg` is a stub, and I really don't care about the rest. This test does pass now. And hurd is in the system table.
=> Add gnu hurd to *_machine information

mesonbuild/backend/backends.py, mesonbuild/interpreter.py, mesonbuild/mesonlib.py
This just fixes the places which are hit by test cases in a simple-minded way.  There are several other uses of `os.path.relpath()`, which might be suspect.
Closes #3239
=> os.path.relpath() can fail on Windows

run_cross_test.py, run_meson_command_tests.py, run_project_tests.py, run_tests.py, run_unittests.py
Add an option to fail fast for the tests. `--failfast` is already an option in the built-in `unittest` module of python. I simply extended the other test runners to also support it.
=> Add option to fail fast in tests

mesonbuild/compilers/c.py, run_unittests.py
Occasionally darwin libraries can be .so rather than .dylib e.g. tensorflow_cc.so
=> Added .so to list possible darwin dynamic library suffixes

mesonbuild/environment.py
This is a domain-specific validation not tied to the surface syntax, so it belongs here in the pipeline.
=> Move some cross file parsing validition to MachineInfo

mesonbuild/scripts/depfixer.py
@nirbheek @jpakkane This is needed to prevent bioconda failures, which come about because bioconda has `-Wl,-rpath,/some/lib/dir` in its `LDFLAGS` where `/some/lib/dir` is also contained in pkg-config files and is consequently added by Meson for its build tree. On calling `ninja install`, `install_name_tool` is called with two identical `-delete_rpath` arguments, which `install_name_tool` rejects. The solution here is not optimal, but it's still better than the status quo.
=> Do not try to remove duplicate RPATH entries on macOS

mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py
* This helps with reproducibility on macOS in the same way
`$ORIGIN` improves reproducibility on Linux-like systems.
* This makes the build-tree more resilient to users injecting
rpaths via `LDFLAGS`. Currently Meson on macOS crashes when
a build-tree rpath and a user-provided `-Wl,-rpath` in
LDFLAGS collide, leading to `install_name_tool` failures.
While this still does not solve the root cause, it makes
the occurrence much less likely, as users will generally
pass absolute `-Wl,-rpath` arguments into Meson.
=> Use relative build-tree RPATHs on macOS

run_unittests.py
Without commit 3a8911a07fd120b6d06b00e0743cab8c2d980923 the newly added test `test_duplicate_rpath` in `DarwinTests` would fail. Example:
https://travis-ci.org/mesonbuild/meson/jobs/441412556
@nirbheek the test as requested, which fails without commit 3a8911a07fd120b6d06b00e0743cab8c2d980923. Could we get 3a8911a07fd120b6d06b00e0743cab8c2d980923 into 0.48.1? So we can upgrade the toolchain we use in conda.
=> Add macOS test for duplicate `-delete_rpath` handling

mesonbuild/backend/ninjabackend.py
Hi!
Since Meson 0.48, any definition including e.g. a vcs_tag line like this:
`vcs_tag(command: ['git', 'describe', '--dirty=+', '--tags'], input: 'VERSION.in', output: 'VERSION')`
fails to build with errors like:
```
ldc2 -I=girtod@exe -I=. -I=.. -I=../source/ -I= -enable-color -wi -g -d-debug -of='girtod@exe/source_girtod.d.o' -c ../source/girtod.d
```
This bug has been in the code since forever, but is now exposed because for whatever reason, the LDC D compiler backend was changed to use `=` between a compiler flag and its value.
This results in build failures like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910443, but I have also seen this issue on other occasions.
This patch fixes the regression by testing whether the `target_dir` of a custom target is empty before including …
=> Regression fix: Don't try to import empty-string custom target include dirs

.gitattributes, ci/azure-steps.yml
Avoid platform eol normalization as check_format() in project_tests checks
for unix-style line endings.
Indicate .png files are binary so we don't try to normalize them on
check-in.
=> Use .gitattributes to override autocrlf=true

mesonbuild/environment.py
The AIX linker decided to have a capital `U` in the help message, but other than that for all intents and purposes it's just the same interface as the binutils ar.
I figured that this was better than a `err.lower().startswith('using')` and grouping it together with macOS.
=> Added basic detection for AIX linker

docs/markdown/Installing.md, docs/markdown/Reference-manual.md, docs/markdown/snippets/manpage_compression.md, mesonbuild/backend/backends.py, mesonbuild/minstall.py, run_unittests.py, test cases/common/10 man install/installed_files.txt, test cases/common/196 install_mode/installed_files.txt, test cases/common/49 custom install dirs/installed_files.txt
Remove the code responsible for implicitly compressing manpages as .gz
files.  It has been established that manpage compression is a distro
packager's task, with existing distros already having their own
implementations of compression.
Fixes #4330
=> Remove implicit compression of man pages

mesonbuild/compilers/compilers.py
Should help with systemd bug #10430.
=> Keep absolute rpaths to libraries outside the build dir.

mesonbuild/backend/ninjabackend.py
When running MSVC on linux via wine, the PDB output doesn't work - allow disabling it.
=> Skip creating a PDB file if a debug build hasn't been requested

docs/markdown/snippets/add_release_note_snippets_here, mesonbuild/compilers/cpp.py, test cases/windows/17 cpp17/main.cpp, test cases/windows/17 cpp17/meson.build
As of right now, we have to use this silly hack https://github.com/ubsan/ublib/blob/master/meson.build#L17, so I decided to add C++17 support.
Mostly based on #2836
=> add cpp_std support for MSVC

docs/markdown/Python-module.md, docs/markdown/Reference-manual.md, docs/markdown/snippets/disabler.md, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/modules/python.py, test cases/common/164 disabler/meson.build
When dependency(), find_library() or find_program() return a not-found
object and use_disabler is true, they return a Disabler object instead.
=> Add 'disabler' argument to functions returning not-found objects

docs/markdown/Qt5-module.md, mesonbuild/modules/qt.py, test cases/frameworks/4 qt/meson.build
There's moc_extra_arguments for moc, and uic_extra_arguments for uic, but there isn't one for rcc.
=> module-qt: add rcc_extra_arguments to pass extra arguments to rcc

mesonbuild/compilers/c.py
For PE/COFF it is not possible to allow undefined symbols, so do not
try to use the option to do so.
While gcc ld silently ignores it, this is not the case for the llvm
linker.
Fix #4415
=> compilers/c: Fix allow undefined link arg for PE/COFF

mesonbuild/compilers/compilers.py
Armclang linker support output symdef file which containing the global symbol definitions from the output image that can be treat as static library and linked to other image.  Usually I use it to build BSP or redboot or sharelib image for bare metal MCU
=> add implib support for ArmclangCompiler

.appveyor.yml
First do VS2017 since it is the most likely to break. Cygwin
is last because it is the slowest.
=> Reorder appveyor test runs

mesonbuild/compilers/cpp.py, test cases/frameworks/1 boost/meson.build
We do this with `cpp_std=vc++NM` - `vc++` does not add `/permissive-`, while `cpp_std=c++NM` adds `/permissive-`.
=> add support for `/permissive-`

mesonbuild/compilers/compilers.py
This allows using the imperfect profiles generated by multithreaded
programs. Without the argument, GCC fails to load them.
Clang just ignores the argument AFAICT.
Fixes https://github.com/mesonbuild/meson/issues/2159
=> get_base_compile_args: Add -fprofile-correction to -fprofile-use

mesonbuild/interpreter.py, mesonbuild/mlog.py
It is a common idiom to look for a function or a specific type or a header in various locations/libraries, and it can be confusing to see the (seemingly) identical compiler check being done multiple times.
Now we print the dependencies being used when a compiler check is run
Before:
Checking for function "fbGetDisplay": NO
Checking for type "GLeglImageOES": YES
Checking for function "asinh": YES
After:
Checking for function "fbGetDisplay" with dependency egl: NO
Checking for type "GLeglImageOES" with dependencies glesv2, gl: YES
Checking for function "asinh" with dependency -lm: YES
=> Print dependencies being used for compiler checks

docs/markdown/Reference-manual.md, docs/markdown/snippets/pathdivision.md, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, test cases/common/116 pathjoin/meson.build
Python pathlib does this as well as the C++ filesystem library. So why not us?
Division by zero error message improvement is complimentary.
=> Make string division do path joining

mesonbuild/backend/backends.py, mesonbuild/mesonlib.py
EFL has meanwhile grown into its almost final size. A few stats:
Targets: 1655 
Custom targets: 3678
Installed header files: 2736
With this patch it takes ~11 sec. on a laptop to configure. Which is great, autotools takes about 50 sec.
However there are 2 more things that can be done at some point. we spent about 2 sec. in `write` a cached string with the content that gets flushed into a file at once might be better here, and safe another second or so. Additionally there are a big number of calls to `get_target_dir` which could be optimized and investigated at some point.
=> Performance optimize the ninja generator another time

mesonbuild/dependencies/base.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/platform.py, mesonbuild/dependencies/ui.py
As noted in https://github.com/mesonbuild/meson/pull/3657#issuecomment-393964084, specialized dependency detectors often don't correctly consider if we are looking for a cross or native dependency.
Fix this in the obvious places I found in reviewing them.
=> Pay better attention to if cross-compiling in dependency detectors

mesonbuild/dependencies/base.py
As mentioned in https://github.com/mesonbuild/meson/issues/4407#issuecomment-433107200, if `dependency('boost')` fails, the error message is 'Dependency "boost" not found, tried' (sic).
Similar to line 1451 above, suppress reporting the tried methods returned by `log_tried()`, if the list is empty (as is the case with boost)
=> Cosmetic fix to failed required dependency reporting

docs/markdown/Compiler-properties.md, docs/markdown/Reference-manual.md, docs/markdown/Reference-tables.md, docs/markdown/snippets/compiler_argument_syntax.md, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/interpreter.py, test cases/common/206 argument syntax/meson.build
Some compilers try very had to pretend they're another compilers (ICC
pretends to be GCC and Linux and MacOS, and MSVC on windows), Clang
behaves much like GCC, but now also has an MSVC like build.
This method provides a way to determine what the compiler behaves like,
which is useful for differentiating two compilers that have the same
name but take different arguments on different platforms, as well as for
grouping compiler checks
=> Add new compiler.get_argument_syntax method

mesonbuild/modules/gnome.py
Bad news, g-ir-scanner is completely broken for anyone not using libtool (not giving it a .la file)
1. It currently puts the "-L" after the "-l", so the paths are ignored. So currently, all ".gir" files generated by meson are built against the system library... unless the library is in the "root" of the build (it puts -L. as the first argument to gcc). The only reason that that this currently works is that the order of arguments is ignored for rpaths.
2. Enable it for static libraries, it's really not more broken than dynamic ones.
3. We should us the full path to avoid confusion, I made it for static libraires (as dynamic ones "work" with a little luck). 
4. But it should probably be done for all libraries once the below merge request is merged into g-i and a release is made and meson …
=> Fix gir generation for static libraries

mesonbuild/dependencies/base.py, run_unittests.py, test cases/unit/46 native dep pkgconfig var/cross_pkgconfig.py, test cases/unit/46 native dep pkgconfig var/cross_pkgconfig/dep_tester.pc, test cases/unit/46 native dep pkgconfig var/meson.build, test cases/unit/46 native dep pkgconfig var/meson_options.txt, test cases/unit/46 native dep pkgconfig var/native_pkgconfig/dep_tester.pc
When trying to cross-compile mesa on an aarch64 system, I noticed some
strange behavior. Meson would only ever find the wayland-scanner binary
in my host machine's sysroot (/mnt/amethyst):
Native dependency wayland-scanner found: YES 1.16.0
Program /mnt/amethyst/usr/bin/wayland-scanner found: YES (/mnt/amethyst/usr/bin/wayland-scanner)
It should be finding /usr/bin/wayland-scanner instead, since the
wayland-scanner dependency is created as native. On closer inspection,
it turned out that meson was ignoring the native argument passed to
dependency(), and wuld always use the pkgconfig binary specified in my
toolchain instead of the native one (/usr/bin/pkg-config):
Native dependency wayland-scanner found: YES 1.16.0
Called `/home/lyudess/Projects/panfrost/scripts/amethyst-pkg-config …
=> Don't use host pkg-config for native dependencies

mesonbuild/build.py, run_project_tests.py, test cases/common/122 shared module/installed_files.txt, test cases/common/122 shared module/meson.build, test cases/common/207 install name_prefix name_suffix/installed_files.txt, test cases/common/207 install name_prefix name_suffix/libfile.c, test cases/common/207 install name_prefix name_suffix/meson.build, test cases/common/25 library versions/installed_files.txt, test cases/common/25 library versions/lib.c, test cases/windows/7 dll versioning/installed_files.txt, test cases/windows/7 dll versioning/meson.build
Creating a PR as requested by https://github.com/mesonbuild/meson/pull/4436#issuecomment-435052937
This fixes:
* `name_prefix:` didn't effect the implib filename (causing the pkgconfig bug observed in #4436, and also potential implib filename collision if libraries which only differed in `name_prefix:` were used)
* no implib was generated if both `name_prefix:` and `name_suffix:` were specified
I think there's still a theoretical possibility of implib filename collision between libraries which only differ in having a `name_prefix:` matching the (platform-dependent) default and `name_prefix:` absent.
Unfortunately, writing tests involved (ab)using the `installed_files.txt` /`platform_fix_name` mechanism excessively, which I'm not very happy with.  Perhaps that needs to be extended in a …
=> Fix naming of implib when name_prefix/suffix is used

docs/markdown/Reference-manual.md, docs/markdown/snippets/test_setup_is_default.md, mesonbuild/build.py, mesonbuild/interpreter.py, mesonbuild/mtest.py, run_unittests.py, test cases/unit/47 testsetup default/envcheck.py, test cases/unit/47 testsetup default/meson.build
add_test_setup_default() may be used to define a setup that will
be used by default unless another setup is specified with --setup.
Since the "test env" overwrites the "setup env", some environment
variables should be defined in the setup and not in the test. In such
cases the use of --setup becomes mandatory for setting up a correct
environment, which is a bit tidious. Allowing a setup to be used by
default makes this much more convenient.
See issue #4430
=> Add add_test_setup_default()

mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/d.py, mesonbuild/compilers/fortran.py, mesonbuild/interpreter.py
Because we need to inherit them in some cases, and python's
keyword-or-positional arguments make this really painful, especially
with inheritance. They do this in two ways:
1) If you want to intercept the arguments you need to check for both a
keyword and a positional argument, because you could get either. Then
you need to make sure that you only pass one of those down to the
next layer.
2) After you do that, if the layer below you decides to do the same
thing, but uses the other form (you used keyword by the lower level
uses positional or vice versa), then you'll get a TypeError since two
layers down got the argument as both a positional and a keyword.
All of this is bad. Fortunately python 3.x provides a mechanism to solve
this, keyword only arguments. These arguments cannot be based …
=> compilers: Use keyword only arguments for compiler interfaces

run_meson_command_tests.py
Since the last appveyor image update which also included a msys2 update
test_meson_installed() fails for the msys2 mingw jobs complaining that
the install path isn't included in PYTHONPATH.
It complains that "site-packages\" isn't included in "site-packages" ignoring
that the separator should be ignored here. Work around the issue by making
sure that the path set as PYTHONPATH always ends with os.sep.
=> tests: fix test_meson_installed after the recent appveyor image update

mesonbuild/backend/vs2010backend.py
For each regular VS project add the 'meson.build' file that describes the corresponding target, so it can be accessed easily from the IDE.
(inspired by GYP)
=> Add 'meson.build' to VS project files.

mesonbuild/backend/vs2010backend.py
Right now a single 'test_guid' is used for RUN_TESTS, for REGEN, for all run targets and all custom targets. This forces VS 2017 to offer to "save changes" in those projects even if you only open the solution (with VS-generated unique GUIDs).
=> Fix ProjectGuid values in VS projects.

docs/markdown/Native-environments.md, docs/markdown/snippets/native_files.md, docs/sitemap.txt, mesonbuild/coredata.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/ui.py, mesonbuild/environment.py, mesonbuild/interpreter.py, mesonbuild/modules/python.py, mesonbuild/modules/python3.py, mesonbuild/modules/qt.py, mesonbuild/modules/qt4.py, mesonbuild/modules/qt5.py, mesonbuild/modules/windows.py, mesonbuild/msetup.py, run_tests.py, run_unittests.py, test cases/unit/46 native file binary/meson.build, test cases/unit/46 native file binary/meson_options.txt
This is the start of adding config files to meson. I have to admit that I'm not horribly motivated to do anything beyond a binaries section, which would be analogous to the binaries section in a cross file, but for native builds. This is not complete, but I'm hoping to get some feedback on whether this looks like the approach we want to use or not. I really need this or something like it to have a good way to override which llvm-config binary to use in a given build, as it's one the of the few things holding up dropping autotools from mesa. If this looks good I'll keep overriding binaries and writing tests.
=> native file support

mesonbuild/compilers/c.py, mesonbuild/compilers/c_function_attributes.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/fortran.py, mesonbuild/dependencies/misc.py, run_unittests.py, test cases/common/204 function attributes/meson.build, test cases/fortran/9 cpp/meson.build
This not so little series goes a long way to getting ICC on Linux and MacOS up to snuff. On my local system there are only two tests left that don't pass in our test suit, the C++ and Fortran mixed test, and protocol buffers. Both of which are out of my depth to fix.
There are a few changes in this series that have bigger implications than it might first appear, one of those changes is the use of keyword only arguments, which solves a real problem in my series, but also is one that others will run into as meson's Compiler class hierarchy continues to become more complicated. The other is my attempt to fix the b_lundef option on Mac, which may or may not be completely correct.
=> ICC fixes for Linux and MacOS

mesonbuild/modules/gnome.py
Although `gtkdoc` [function has support for `c_args` argument](https://github.com/mesonbuild/meson/pull/4192), it produces warning messages due to missing string in the permitted arguments list.
=> gnome.gtkdoc: Fix missing permitted `c_args` argument

test cases/frameworks/17 mpi/meson.build
While this isn't solved everywhere, this seems reasonable to disable it.
On Fedora 28 we get : 
```unresolvable R_X86_64_64 relocation against symbol `mpi_fortran_argv_null_'```
=> -Wl,--as-needed seems to break easily with mpi/fortran

docs/markdown/Gnome-module.md
Although the `namespace` parameter was implemented in 0.37, its documentation is still missing.
It has been added to the `gtkdoc`'s  documentation.
=> docs: Add missing `namespace` parameter documentation

mesonbuild/minstall.py
do_copyfile() already takes the decision to delete or preserve them.
Also do not append a confusing '.' in log messages that finish by a file
path.
=> minstall: Do not delete dst files when installing a directory

mesonbuild/modules/pkgconfig.py, run_unittests.py, test cases/unit/48 pkgconfig csharp library/meson.build, test cases/unit/48 pkgconfig csharp library/somelib.cs
this adds support for generating pkgconfig files for c#.
The difference to c and cpp is that the -I flag is not known to the c#
compiler, but rather the -r flag which is used to link a .dll file into
the compiled library.
However this opens the question of validating which pkgconfig files can
be generated (depending on the language).
This implements #4409.
=> pkgconfig: add support for pkgconfig generation for c#

docs/markdown/Reference-tables.md, docs/markdown/Running-Meson.md
Currently this is only partially documented in the quick-start guide,
include this in the main docs and document all the environment
argumens used.
=> [skip ci] Document CFLAGS and friends in main docs

mesonbuild/wrap/wrap.py
This might be the case on a minimal container, for example.
=> Fix subproject initialization without git installed.

mesonbuild/dependencies/ui.py
=> dependencies/ui: Fix qt compiler detection when bindir is set

mesonbuild/build.py, run_unittests.py
Fixed-size hash makes paths shorter and prevents doubling of path length
because of subdir usage in target id: `subdir/id` would generate
`subdir/{subdir-without-slashes}@@id` target otherwise.
Closes #4226.
=> Use first 7 letters of sha256 for subdirectory part of target id

docs/markdown/IDE-integration.md, docs/markdown/snippets/buildopts_section.md, mesonbuild/mconf.py, mesonbuild/mintro.py, run_unittests.py
This adds the new key `section` to each build option when running `meson introspect --buildoptions`. This allows IDEs to group the build options into the same sections as `meson configure`. This change should not break any existing code since only one key was added.
=> Added 'section' key to buildoptions introspection

mesonbuild/dependencies/base.py
=> Fixed unbound cmvers variable

ci/azure-steps.yml
azure doesn't support [skip ci], so do nothing, rather than failing when
we detect a PR which should have [skip ci], but didn't get skipped.
=> azure: ignore PRs which should be skipped for ci

mesonbuild/interpreter.py, run_unittests.py
Add testcase for, and fix `meson introspect --target-files` for a custom target, broken since 0.26.0 (PR #225)
For a CustomTarget, sources is a list of filenames as strings, not File objects.
Closes #2783
=> Fix 'meson introspect --target-files' for a custom target

docs/markdown/Build-options.md
So people could quickly see it without scrolling page.
=> Add meson version required to use option type

data/syntax-highlighting/vim/README, data/syntax-highlighting/vim/ftplugin/meson.vim, data/syntax-highlighting/vim/indent/meson.vim
The vim syntax indentation rules stored in indent/meson.vim set the
local shiftwidth and softtabstop variables. As the file is loaded last,
after ~/.vim/after/ftplugin/meson.vim (when present), this prevents
overriding the default values for shiftwidth and softtabstop in a local
configuration.
Fix this by setting shiftwidth and softtabstop in ftplugin/meson.vim
instead (as done by the python indentiation rules in upstream vim for
instance) to allow local overrides.
Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
=> syntax-highlighting: vim: Allow overriding shiftwidth and softtabstop

mesonbuild/scripts/coverage.py
summary from stdout is often used by Automated builds to show build details
The --print-summary option was added to gcovr in v3.2, since html output
was added only in 3.1, limitting support to 3.2 won’t be a big deal.
--print-summary is not enabled for text/xml report generation as it will
result in meson not supporting any gcovr version less than 3.2.
=> coverage: Print summary after gcovr html generation

mesonbuild/modules/pkgconfig.py
If a project generates a single pc file but multiple shared libraries
with dependencies on each other, the generated pc name will be used to
generate a Requires.private dependency, which means the project will
depend on itself. This breaks at least some versions of pkg-config
(0.27 in RHEL7) which cannot handle the recursion and error out.
When adding the dependency using the pc name, check that it's not
on the project itself.
Fixes #4583
=> pkgconfig: do not generated dependency on itself

mesonbuild/environment.py
After we make this work consistently, we can try to abstract the new pattern.
As with #4580, splitting out easy bits of #4445 while I don't know what to do test hanging with that.
CC @dcbaker
=> Use more `environment.default_*` for consistency

docs/markdown/Pkgconfig-module.md, docs/markdown/snippets/pkgconfig_break.md, mesonbuild/build.py, mesonbuild/modules/pkgconfig.py, test cases/common/48 pkgconfig-gen/dependencies/custom.c, test cases/common/48 pkgconfig-gen/dependencies/meson.build
When a library 'foo' has a public dependency 'bar', foo.pc will be
generated with something like this:
bar_dep = dependency('bar', fallback : ['bar', 'bar_dep'])
libfoo = library('foo', dependencies : bar_dep)
pkg.generate(libfoo, libraries : bar_dep)
In the subproject we will typically have this (not using pkg.generate):
libbar = library('bar')
bar_dep = declare_dependency(link_with : libbar)
configure_file(input : 'bar.pc.in', output : 'bar.pc', ...)
When the 'bar' dependency is built as subproject, libraries from
InternalDependency were not processed. If we process them,
then libbar.generated_pc is suddenly set to 'foo', which will cause any other
pc file generated to have 'Required : foo' for the 'bar' dependency. To
fix that 2nd issue, we set generated_pc only on the main lib passed …
=> pkgconfig: Also pull InternalDependency.libraries

mesonbuild/backend/vs2010backend.py, mesonbuild/environment.py
This was partially suggested in #3872.
This way complete set of environment variables is saved for the VS backend and used to call the regenerate script in the REGEN project. That fixes the problem, where we first run Meson from some VS command prompt and after regeneration of the solution the old values for Platform and SDK version are lost.
The suggestion in #3872 was "the current-best solution we've got is that we add support in Meson for automatically searching for VS installations and extracting the env: #2622".
But I can't see how this will help in case of using one of VS command prompts. I think that if you run Meson from some VS command prompt the next regenerations from the IDE should use the same environment.
Another approach would be to read only some env variables, like …
=> Save environment for REGEN project.

mesonbuild/environment.py
```
commit b2807e49e3915a3e43a48c4932798aa298fadf77
Fix detection with VS 2017, and fix a bug in detection on VS 2008
Starting with VS 2017, `Platform` is not always set (f.ex., if you use
VsDevCmd.bat directly instead of vcvars*.bat), but `VSCMD_ARG_HOST_ARCH`
is always set, so try that first.
```
This one should definitely go into 0.49.0.
```
commit 51abb4c6ff22c85a0dee050388f7d01d2c86b2a2
Reorganize cpu detection code to be more consistent
Use a single point of exit for the detect_cpu* functions, and factor
out the compiler define code into a helper function.
```
```
commit 724aae5149096ded799d27ac7c41376c322e3ef7
Correctly detect 32-bit arm userland on 64-bit arm
This is the same case as 32-bit x86 on x86_64.
Closes https://github.com/mesonbuild/meson/issues/4586
```
These two could …
=> Various arch detection fixes.

mesonbuild/dependencies/base.py
https://github.com/mesonbuild/meson/pull/4444#issuecomment-442996375
before:
```
...
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Found CMake: NO
Dependency foo found: NO (tried pkgconfig)
meson.build:4:0: ERROR:  Dependency foo not found: CMake not found.
```
after:
```
...
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Found CMake: NO 
Dependency foo found: NO (tried pkgconfig)
meson.build:4:0: ERROR:  Dependency "foo" not found, tried pkgconfig
```
=> Don't blame absent cmake for all missing dependencies

mesonbuild/modules/python.py
None is not iterable so it would trigger a TypeError later when link_args are
passed on to CompilerArgs.extend_direct().
I found this issue when using gst-build with Meson 0.48.2 installed for Python 3.7.
=> modules/python: Do not override link_args with None largs

mesonbuild/interpreterbase.py
Yo dawg! We heard U don't like kwargs in kwargs, so we made it
impossible to put kwargs in your kwargs so now you can't kwargs with
your kwargs.
=> Error out if kwargs dict contains a kwargs entry.

run_unittests.py
Dunno if this is the correct thing to do, but this error is blocking the 0.49.0 release.
=> Skip if a suitable D alternative is not found.

run_tests.py
Currently `run_tests.py` determines the backend to use only by checking if `msbuild` [is installed](https://github.com/mesonbuild/meson/blob/master/run_tests.py#L263). However, it is also possible to install `msbuild` [on Linux](https://aur.archlinux.org/packages/msbuild-stable/) to build VS C# projects (like KSP mods). In this case `run_tests.py` will try to use the `vs` backend, which always fails because visual studio itself is not installed.
=> Only autodetect 'vs' backend on windows

mesonbuild/modules/pkgconfig.py, run_unittests.py, test cases/unit/50 pkgconfig static link order/meson.build
Since `_process_libs` appends the lib's dependencies this list already,
the final return value of `_process_libs` will end up after its
dependencies, which is the wrong way around. (The lib must come first,
then its dependencies)
The easiest solution is to simply pre-pend the return value of
`_process_libs` rather than appending it, so that its dependencies come
after the library itself.
Closes #4091.
=> pkgconfig: Fix link order of library dependencies

docs/markdown/Reference-tables.md
View https://mesonbuild.com/Reference-tables.html#compiler-and-linker-flag-environment-variables.
=> Reformat Compiler and linker flag table [skip ci]

mesonbuild/compilers/compilers.py
This is a classy compiler.
In mesa I ran into an issue where the following would be ignored even though it was unsupported:
`-target-cpu=sandybridge`
It would raise the 10158 error because icc does apparently support (though it doesn't document) a `-target` flag.
=> compilers/icc: Add even more diag-errors to actually error on

mesonbuild/dependencies/ui.py
We previously didn't require it so we shouldn't silently start doing so.
Fixes #4654
=> dependencies/ui: Don't require lrelease for qt

mesonbuild/interpreter.py
It is possible that the subproject has been downloaded already, in that
case there is no reason to not use it. If the subproject has not been
downlaoded already it will fail do_subproject().
=> Allow fallback in nodownload mode

mesonbuild/msetup.py
As would happen if someone tried to manually call meson --wipe on a
directory configured with a version < 0.49.0
=> msetup: Give a nice error message if cmd_line.txt cannot be read

mesonbuild/dependencies/ui.py
This resolves a couple of different bugs with qt5 for macos. At least the second patch (with the Fixes tag) should be pulled for 0.49.1
=> Qt macos fixes

mesonbuild/mesonlib.py, mesonbuild/msetup.py, run_unittests.py
This seems to be related to deleting the current working directory.
Simply deleting all of the trees inside the build directory instead
seems to fix it. This only appears with some combination of generated
targets, running the test case against say "1 trivial" doesn't show the
bug.
See this mesa bug: https://bugs.freedesktop.org/show_bug.cgi?id=109071
=> msetup: Fix callig meson --wipe inside a build directory

mesonbuild/mintro.py, run_unittests.py
This bug occurs for the project tests `test cases/common/145 custom target multiple outputs` and `test cases/vala/7 shared library`. Here targets with multiple outputs are generated, of which, not all are installed. This crashes the `--targets` introspector.
How to reproduce:
- in meson root:
- run `./meson.py "test cases/common/145 custom target multiple outputs" tmp`
- then `./meson.py introspect --targets tmp` will crash
=> mintro: Bug fix for determine_installed_path for multiple target outputs

docs/markdown/Reference-manual.md, docs/markdown/snippets/find_library_header.md, mesonbuild/interpreter.py, test cases/common/209 find_library and headers/foo.h, test cases/common/209 find_library and headers/meson.build
A library without its headers is often useless, so it is common to check them together.
This is based on top of PR https://github.com/mesonbuild/meson/pull/4658.
=> find_library: Add 'has_headers' kwarg

mesonbuild/backend/ninjabackend.py
=> compile pch .h file as c++-header when building a c++ target

mesonbuild/build.py, test cases/failing/92 missing pch file/meson.build, test cases/failing/92 missing pch file/prog.c
Previously, the configuration worked fine, but the compiler raised an error. Now, we explicitly check for the existence of files and print a useful error message if they do not exist.
It would probably be cleaner if PCH files would be treated as `File` and not as `str`, but I didn't want to dig too deep into each backend and change this all over the place.
=> fail configuration if PCH files do not exist

data/macros.meson
This effectively reverts 92219a2739ea69fa617cca74517b68ed5e1bcb7d.
Back in the day, meson test would not print the logs on failure. But it now
does that automatically, for the failed test. Printing all logs is annoying because
it results in exteremely long output in some packages.
Example output:
```
+ /usr/bin/ninja test -v -j4 -C x86_64-redhat-linux-gnu
ninja: Entering directory `x86_64-redhat-linux-gnu'
[0/1] /usr/bin/meson test --no-rebuild --print-errorlogs
1/16 test-script.sh                          OK      46.23 s
...
14/16 test-casync                             FAIL     1.17 s (exit status 1)
15/16 test-cautil                             OK       0.00 s
16/16 test-util                               OK       0.01 s
Ok:                   15
Expected Fail:         0
Fail: …
```
=> rpm: remove manual printing of error logs on failure

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/coredata.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/ui.py, mesonbuild/environment.py, mesonbuild/interpreter.py, mesonbuild/modules/gnome.py, mesonbuild/modules/python.py, mesonbuild/modules/python3.py, mesonbuild/modules/windows.py, run_tests.py, run_unittests.py
Continuing what #4338 started. ~~So ignore this until that is merged.~~
Simply put, this gets rid of `environment.cross_info`. Information is instead stored in `environment.binaries` (the `BinaryTable` class has instances now), `environment.machines` as was already done, and `environment.properties`. All of these are `PerMachine` containers, paving the way for a rebased #4010 completely merging cross and native code paths.
In particular the binary lookup code has begun to be consolidated with this, using the same function to assist with looking up in either the cross file or environment variables. There's a lot more consolidation to be done however, that this enables. More net-negative commits on the way!
N.B: `self.environment.is_cross_build() and …
=> Parsing of cross file upfront, and store in cross-agnostic data structures

mesonbuild/modules/pkgconfig.py, run_unittests.py, test cases/common/48 pkgconfig-gen/dependencies/meson.build
This is a regression introduced by 2cbf7caf5, generated pkg-config files
have many duplicated '-pthread' flags.
=> pkgconfig: Fix flag deduplication

mesonbuild/mparser.py, test cases/common/210 line continuation/meson.build
The documentation states: "In other cases you can get multi-line
statements by ending the line with a \." but that seems to never have
worked.
Closes: #4720
=> parser: Fix line continuation outside of (), [] or {}

mesonbuild/coredata.py, mesonbuild/mconf.py, mesonbuild/minstall.py
Without this, e.g. in test case `common/63 install subdir` it raised `TypeError: unsupported format string passed to NoneType.__format__` when using `meson configure` to list the configuration.
Do we need a test for this?
=> fix meson configure exception when install_umask is not an int

docs/markdown/Creating-OSX-packages.md
The docs mentioned that there is an error in a [linked Stack Overflow answer](https://stackoverflow.com/questions/1596945/building-osx-app-bundle). That error has been fixed, so the warning is no longer needed.
=> docs: An error in an external link has been fixed

mesonbuild/coredata.py, mesonbuild/interpreter.py, mesonbuild/mconf.py, mesonbuild/msetup.py
Also, options are now responsible for providing a suitable printable
representation of their value instead of handling this at the caller.
=> use same code for printing options in mconf and msetup

mesonbuild/mesonmain.py, mesonbuild/munstable_coredata.py
This adds a hidden option to dump the current otherwise hidden peristant state in coredata.dat.
This interface is unstable as meson has no compatibility promises about coredata.dat and i tried to make sure that the interface says so both as text message and by nameing the option `unstable-coredata`.
Example output with ninja backend (vs backends have a lot of guids not shown in this case):
```
$ meson.py unstable-coredata _build
This is a dump of the internal unstable cache of meson. This is for debugging only.
Do NOT parse, this will change from version to version in incompatible ways
Cached native compilers:
c:
Id: gcc
Command: ccache cc
Full version: cc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Detected version: 6.3.0
Detected type: <CompilerType.GCC_STANDARD: 0>
cpp:
Id: gcc
Command: …
```
=> Add new meson.py unstable-coredata subcommand to show the hidden state.

mesonbuild/backend/ninjabackend.py
Since trying to use a Clang based -cross-file.txt for cross compiling Windows binaries from Linux I found that Meson was using `is_windows()` to imply that `cmd` should be used as the shell for ninja commands and also since many of the paths in the cross-file were something like:  `/mnt/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/lib/x64` I also found some more places where Meson wasn't adding escape characters for the shell.
=> Allow cross compiling for Windows under cmd.exe or Bash

mesonbuild/compilers/c.py
Enables the use of werror option when using the CCRX compiler
=> Add get_werror_args for CCRX C compiler

mesonbuild/interpreter.py
`need_cross_compiler = is_cross_build()`, so the condition is always false.
=> Remove spurious case in interpreter

mesonbuild/mintro.py
It is no longer needed either.
=> `environment.cross_info.need_cross_compiler()` doesn't exist

mesonbuild/environment.py
Native ar and cross ar are not the same!
=> Fix finding the static linker for native compiler in cross build

docs/markdown/Porting-from-autotools.md, docs/markdown/Quick-guide.md, docs/markdown/Reference-tables.md, docs/markdown/howtox.md
If we can't get rid of CFLAGS and friends, we can at least do our best to discourage people from using them.
=> Discourage the use of env variables like CFLAGS [skip ci]

mesonbuild/interpreter.py
Fix a typo in an error message (mentions the wrong method), noticed while working on some nearby code...
=> Fix a typo in an error message

docs/markdown/snippets/introspect_breaking_format.md, mesonbuild/mintro.py, run_unittests.py
This is a followup PR to #4547. This PR introduces the format changes to the introspection API discussed in the original PR.
Most notably the `filename` and `install_filename` keys in the targets introspection are now always lists and all file paths are now absolute.
cc: @textshell
=> mintro: Changes to the introspection API

docs/markdown/Reference-manual.md, mesonbuild/interpreter.py, test cases/common/14 configure file/meson.build, test cases/failing/91 invalid configure file/meson.build
If a configure_file has an install_dir set, the supported install
argument is ignored, while this should have actually higher priority
than the install_dir itself.
Add test to verify this.
Fixes #3983
=> interpreter: obey to the install argument in configure_file

mesonbuild/mintro.py
This change removes the necessity to load any serialized meson structures for runtime introspection. Instead, the information in `meson-info.json` is used to acquire the source directory and the introspection format version.
This has the advantage that the meson version does not have to match exactly, for the introspection API to work.
cc @textshell
=>  mintro: Check meson-info.json version instead of loading coredata 

mesonbuild/astinterpreter.py, mesonbuild/dependencies/base.py, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/mlog.py, mesonbuild/modules/python.py, run_unittests.py, test cases/common/170 dependency factory/meson.build, test cases/unit/20 subproj dep variables/meson.build, test cases/unit/20 subproj dep variables/subprojects/nestedsubproj/meson.build, test cases/unit/20 subproj dep variables/subprojects/nestedsubproj/subprojects/subsubproject.wrap
While working on dependency fallbacks and overrides, I found that code should be cleaned first. This is a big PR, I tried to split in many small commits.
=> Refactor dependency code

.gitignore, tools/cmake2meson.py
Many CMakeLists.txt have nested/complex if like
```cmake
if(A AND NOT(B OR C))
```
which with the current release `tools/cmake2meson.py` errors with:
```
File "~/meson/tools/cmake2meson.py", line 306, in <module>
c.convert()
File "~/meson/tools/cmake2meson.py", line 273, in convert
self.write_entry(outfile, t)
File "~/meson/tools/cmake2meson.py", line 232, in write_entry
line = 'if %s' % self.convert_args(t.args, False)
File "~/meson/tools/cmake2meson.py", line 158, in convert_args
if i.tid == 'id':
AttributeError: 'list' object has no attribute 'tid'
```
The changes in this PR allow such if statements to pass through to `meson.build` draft.
Also, I used Python &ge; 3.5 intrinsic `pathlib.Path` for cleaner code, and ability to specify paths with `~`, which is not possible in the current …
=> tools/cmake2meson.py: allow nested/complex if statement

mesonbuild/mesonmain.py, mesonbuild/mtest.py
When python sees an invalid character in a filename for the current locale, instead of clobbering it, it saves is as an invalid codepoint called a surrogate.  We need to explicitly instruct the encoder to write those out as-is. In the JSON file, we replace them instead to produce valid json.
Fixes #4718
=> Replace surrogates with valid codepoints to print env

mesonbuild/coredata.py
I noticed a couple of bugs in the wipe/reconfigure code, over the last couple of days. First I noticed that between 0.49 and now the code wouldn't function due to the removal of data structures from our internal representation. Then I noticed while trying to test a fix that of the coredata.dat file was empty (ie, created by touch) there would be an error. Then I noticed that native files are serialized into the cmd_line.txt either, when I was writing a script to convert cmd_line.txt into a command line that could be fed back to meson.
=> Cmd line file fixes

docs/markdown/Reference-manual.md, docs/markdown/Release-notes-for-0.50.0.md, mesonbuild/backend/backends.py, mesonbuild/build.py, test cases/common/209 custom target build by default/docgen.py, test cases/common/209 custom target build by default/meson.build
A custom_target, if install is set to true, will always be built by
default even if build_by_default is explicitly set to false.
Ensure that this does not happen if it's set explicitly. To keep
backward compatibility, if build_by_default is not set explicitly and
install is true, set build_by_default to true.
Fixes #4107
=> custom_target: do not let install override build_by_default

test cases/unit/17 prebuilt shared/patron.c
This caused test failures while backporting meson to an old runtime environment.
=> tests: Don't return an undefined value from main()

run_unittests.py
While backporting Meson to an embarrassingly old runtime environment using a backported Python 3.5, I found that some tests failed.
One failure mode that's easy to fix is that subprocess.run() didn't get the encoding parameter until 3.6.
=> run_unittests: Use Python 3.5-compatible subprocess invocation

docs/markdown/Continuous-Integration.md, docs/markdown/Creating-Linux-binaries.md
This replaces the use of the deprecated backtick syntax with the `$()` syntax.
=> docs: Use modern shell constructs

mesonbuild/dependencies/dev.py
Debian has already pushed llvm-9 into experimental
=> dependencies/llvm: add debian's llvm-9

mesonbuild/coredata.py, run_unittests.py
Our builddir ABI is stable across minor (stable) releases, so there is no need to force a wipe. We already release pretty often, no need to force people to wipe twice as often.
We should definitely ship this change in the minor release.
=> coredata: Only reject a load if major version differs

mesonbuild/dependencies/base.py
In recent change, dependency('foo') does not return a not-found
PkgConfigDependency any more, but a NotFoundDependency object. This
creates a regression in gst-build that does
dependency('foo').get_partial_dependency() causing Meson to raise an
exception.
=> NotFoundDependency: Implement partial_dependency()

mesonbuild/mesonlib.py, run_unittests.py
In some cases (see #4817) it's helpful if the output file uses the
same newlines as the input file without translating them to the
platform defaults.
open() by default recognizes all newline styles and translates them
to "\n" and then to the platform default when writing.
Passing "" to "newline" disables the translation and lets us pass through
the original newline characters.
=> configure_file: preserve newlines of the input file. Fixes #4817

mesonbuild/dependencies/data/CMakeLists.txt
Since this fixes an Ubuntu / Debian specific issue related to multiple versions of the same library, it is almost impossible to make a test case for this. The only thing I can think of is installing `zlib1g:i386` in the docker image.
=> Try multiple CMAKE_LIBRARY_ARCHITECTURE (fixes #4812)

mesonbuild/backend/vs2010backend.py
E.g. target `py3hi` (from test case 55) could not be run without errors, because the quotes were messed up.
=> vs: escape embedded quotes of run targets

mesonbuild/interpreter.py
Previously, the default option string was compared to the actual project
option that has been converted to the proper type. This lead to messages
like 'Option x is: true [default: true]'.
Fixes #4806.
=> fix non-default option printing

mesonbuild/backend/vs2010backend.py, test cases/common/13 pch/c/pch/prog.h
Somehow, the VS backend chokes when you add header guards to PCH files.
This can be fixed by always using the basename of the PCH header instead of the relative path, which is also what the ninja backend does.
=> vs: fix PCH

mesonbuild/backend/backends.py, mesonbuild/backend/vs2010backend.py, mesonbuild/compilers/__init__.py, mesonbuild/compilers/compilers.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/ui.py, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/mesonlib.py, mesonbuild/mesonmain.py, mesonbuild/minstall.py, mesonbuild/modules/pkgconfig.py, mesonbuild/mparser.py, mesonbuild/wrap/wrap.py, run_unittests.py, test cases/common/53 custom target/depfile/dep.py
Python 3.7 throws numerous pep8 warnings due to Python 3.8 syntax deprecations.
These changes make a `flake8` run have zero warnings with Python 3.7 and flake8 3.6.0
=> PEP8 for Python 3.7

mesonbuild/dependencies/base.py, mesonbuild/environment.py
First, I noticed there was a dangling use of now-removed cross_info in the CMake lookup. No tests had caught this, but it means that CMake deps were totally broken. \[It also meant that CMake could not be specified from a native file.]
In a previous of mine PR which removed cross_info, I overhauled finding pkg-config a bit so that the native and cross paths were shared. I noticed that the CMake code greatly resembled the pkg-config code, so I set about fixing it to match.
I then realized I could refactor things further, separating caching, finding alternatives, and validating them, while also making the validations less duplicated. So I ended up changing pkg config lookup a lot too (and CMake again, to keep matching).
Overall, I think I have the proper idiom for tool lookup now, repeated …
=> Overhaul pkg-config and CMake lookup, fixing the latter

mesonbuild/modules/pkgconfig.py
When using pkg.generate(mylib, library : publicdep) it is pretty clear
we don't want to associate publicdep to this generated pkg-config file.
This fix unavoidable deprecation warning when glib is built as
subproject and the parent project (e.g. gst-build) generates a
pkg-config file that depends on glib-2.0.pc on a platform where libintl
is itself built as subproject (e.g. Android).
=> pkgconfig: Avoid deprecation warning when using new syntax

mesonbuild/modules/gnome.py
Both of these need to link to their respective libraries to build.
=> Add tsan and ubsan to g-ir-scanner workaround.

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/c.py, mesonbuild/environment.py, mesonbuild/mesonlib.py, run_tests.py, run_unittests.py
macOS provides the tool `lipo` to check the archs supported by an object (executable, static library, dylib, etc). This is especially useful for fat archives, but it also helps with thin archives.
Without this, the linker will fail to link to the library we mistakenly 'found' like so:
`ld: warning: ignoring file /path/to/libfoo.a, missing required architecture armv7 in file /path/to/libfoo.a`
~~Fixes a bunch of pkg-config related regressions on macOS, including https://github.com/mesonbuild/meson/issues/4728.~~
=> find_library: Check arch of libraries on Darwin

mesonbuild/dependencies/base.py
This is a regression from previous releases and breaks existing build files, such as GStreamer. The proper fix is in master (#4857), but we cannot backport that since it is a complete rewrite of the framework detection.
=> (for 0.49) deps: Don't reject cross usage of extra frameworks

mesonbuild/ast/interpreter.py, run_unittests.py
Simple test case to ensure that all functions in the real interpreter are also known to the "fake" interpreter. Also added the currently missing functions.
=> Ensure that func dicts provide the same set of functions

mesonbuild/compilers/vala.py
Because Vala is only generating .c files, it's up to the C compiler to deal with this.
=> vala: Support position-independent executables

docs/markdown/Cuda-module.md, docs/sitemap.txt, mesonbuild/build.py, mesonbuild/environment.py, mesonbuild/modules/unstable_cuda.py, test cases/cuda/3 cudamodule/meson.build, test cases/cuda/3 cudamodule/prog.cu
As the CUDA support is beginning to take shape, I'd like to offer the following contributions, which I've been so far carrying around in external scripts I've been calling out to from Meson proper.
1) The NVCC compiler version detection is worse than it could be; It reports for instance `10.0` when it could report `10.0.130` instead. The patch is simple.
2) Unfortunately the current CUDA support does not allow me to pass arguments to `nvcc`, so I added the keyword `cuda_args:`.
3) The NVCC compiler also accepts a large number of architecture flags to allow one to compile fat binaries (a binary for an enumerated set of compute capabilities). [The CMake logic to generate them](https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA/select_compute_arch.cmake) from a list of compute …
=> CUDA support improvements

mesonbuild/modules/__init__.py, mesonbuild/modules/gnome.py
Instead of generating a c file that gets compiled,
directly create object file with ld.
See https://gitlab.gnome.org/GNOME/glib/issues/1489
=> gnome.compile_resources: Add ld binary method

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cs.py, mesonbuild/compilers/d.py, mesonbuild/compilers/java.py, mesonbuild/coredata.py, mesonbuild/environment.py, mesonbuild/interpreter.py, mesonbuild/mconf.py, mesonbuild/mintro.py, mesonbuild/modules/gnome.py, run_tests.py, run_unittests.py
Never access `environment.properties` downstream. Instead use coredata.compiler_options.<machine>. This brings the cross and native code paths closer together, since both now use that.
https://github.com/mesonbuild/meson/pull/4772 builds on this to further remove a bunch of conditional code now that the underlying mechanism is the same. It has some CI failures though hence why I didn't do that low-hanging fruit as part of this PR.
----
Command line options are interpreted just as before, for backwards compatibility. Doing so does introduce some funny conditionals to keep the `build` and `host` `compiler_options` in the native case. In the future, I'd like to change the interpretation of command line options so
- The logic is cross-agnostic, i.e. there are no conditions affected by …
=> Go through coreutils.compiler_options.{build.host.target}

azure-pipelines.yml
msys2 now has ninja 1.9.0 which includes the timestamp fixes
=> ci/msys2: use the msys2 ninja

mesonbuild/dependencies/base.py
Fixes #4886.
For example, some packages has some custom configurations on dub config, and instead of `library` its the configuration name:
(generated builds)
=> Fix meson not detecting dub packages with different compilers and arch

mesonbuild/mtest.py
If the global gdb option of mesontest is disabled (e.g. not set '--gdb') and the gdb option of test_setup is enabled (e.g. add_test_setup('mygdb', gdb : true) and use '--setup=mygdb'), an exception will be thrown.
```
File "/home/jin/Downloads/meson/mesonbuild/mesonmain.py", line 114, in run
File "/home/jin/Downloads/meson/mesonbuild/mtest.py", line 805, in run
return th.doit()
File "/home/jin/Downloads/meson/mesonbuild/mtest.py", line 555, in doit
self.run_tests(tests)
File "/home/jin/Downloads/meson/mesonbuild/mtest.py", line 715, in run_tests
self.drain_futures(futures)
File "/home/jin/Downloads/meson/mesonbuild/mtest.py", line 731, in drain_futures
self.process_test_result(result.result())
File …
```
=> mtest: Don't use thread executor when enabled gdb in test_setup

mesonbuild/backend/ninjabackend.py
This PR handles the variety of `use` syntax defined by Fortran 2003.
Previously it handled only Fortran 90/95 `use` syntax, which I think is an unintentional bug because Fortran 2003 `use` syntax is widely used for some time.
reference: https://www.ibm.com/support/knowledgecenter/en/SS3KZ4_9.0.0/com.ibm.xlf111.bg.doc/xlflr/use.htm
=> BUGFIX: handle Fortran 2003 "use" syntax

mesonbuild/backend/ninjabackend.py
This allows non-ASCII characters to be ignored in Fortran code. Modules can't have UTF8 names, but comments or with care character variables could be non-ASCII. 
This appears to have simply been an oversight that it was omitted. I didn't get an error until I was running on CentOS, this fixes it.
=> BUGFIX: ignore non-ascii Fortran characters

mesonbuild/backend/vs2010backend.py
Previously, this was only added to C/C++ targets, but not for others.
Thus, if you'd change a setting through `meson configure`, this was not picked up, e.g. the install target said it was up-to-date and when force rebuilding it, it also did not use the new settings until the build dir was manually reconfigured.
Note: This is not ready to be merged, yet. If you currently change a setting with `meson configure`, the REGEN target gets invalidated. However, the INSTALL target still says it's up-to-date and does not do anything. We probably have to add an internal file as input to the meta-targets to be sure they are run if REGEN was triggered.
=> vs: add reconfigure checks for each target

mesonbuild/mesonlib.py
* correct missing `@` on lru_cache decorator
* add type hinting for QA and to help gradual transition to more efficient & robust pathlib.Path vs. os.path(str)
* use modern / efficient subprocess.run(timeout) to avoid hangs
=> BUGFIX: correct missing @ before lru_cache, type hint, syntax efficiency

mesonbuild/compilers/compilers.py, mesonbuild/compilers/fortran.py, mesonbuild/dependencies/misc.py, test cases/common/190 openmp/main.f90, test cases/common/190 openmp/meson.build
The unit test for Fortran OpenMP was not actually run previously, and upon enabling, was failing due to omissions in Meson.
This is now corrected and tested.
also added some type hints.
=> BUGFIX: Fortran openmp

mesonbuild/compilers/cuda.py, test cases/cuda/4 shared/main.cu, test cases/cuda/4 shared/meson.build, test cases/cuda/4 shared/shared/kernels.cu, test cases/cuda/4 shared/shared/kernels.h, test cases/cuda/4 shared/shared/meson.build
Also adds test case for shared library linking.
Closes #4912, at least on Linux. The future 0.50.0 does not yet claim to
support CUDA on systems other than Linux and backends other than Ninja.
=> Fixes for CUDA compiler shared library linking.

docs/markdown/Dependencies.md, docs/markdown/snippets/coarray.md, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/misc.py, test cases/fortran/13 coarray/main.f90, test cases/fortran/13 coarray/meson.build
Another feature for HPC Fortran use cases that CMake does not yet have.
Enables Fortran 2008/2018 language intrinsic Coarray feature.
https://en.wikipedia.org/wiki/Coarray_Fortran#Examples
=> Fortran 2008/2018 Coarray support

mesonbuild/backend/ninjabackend.py
In addition to MSVC, which was worked around previously, GCC also does not list includes from the PCH in the depfile by default, unless `-fpch-deps` is given. I think it's best to stay safe and not rely on any particular behavior from the compiler here.
Fixes #4905
=> ninja: Always treat PCHs as an implicit dependency

mesonbuild/interpreter.py
Need to search based off of `cross_comp`, not `comp`.
Fixes #4822
=> Fix cross static linker lookup
