mesonbuild/meson

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, mesonbuild/compilers/swift.py, mesonbuild/compilers/vala.py, mesonbuild/coredata.py
After #4626, a bunch of cross-specific conditional code is no longer needed, and corresponding native-specific code always used. This PR removes the former and unconditions the latter. I made it a separate PR mainly for CI purposes, but also in case people prefer smaller changes at a time.
Also, there was a little kerfuffle around CPP flags. CPPFLAGS but not CFLAGS are used for some tests, but `<lang>_args` in the cross file is always used for tests, as if they were language-specific CPPFLAGS. We should resolve this, say in a newer version of #3916 that should delete code, but this PR sticks with the current behavior for now.
=> Dedup `compiler_option` access

mesonbuild/backend/vs2010backend.py
This shows dependencies clearly in the 'references' view of VS and properly
propagates the dependencies when building a single vcxproj with msbuild.
=> vs: use project references in vcxproj instead of the sln file

mesonbuild/ast/interpreter.py, mesonbuild/ast/introspection.py, mesonbuild/rewriter.py, run_unittests.py, test cases/rewrite/1 basic/addSrc.json, test cases/rewrite/1 basic/info.json, test cases/rewrite/1 basic/rmSrc.json, test cases/rewrite/2 subdirs/addSrc.json, test cases/rewrite/2 subdirs/info.json, test cases/rewrite/3 kwargs/add.json, test cases/rewrite/3 kwargs/delete.json, test cases/rewrite/3 kwargs/info.json, test cases/rewrite/3 kwargs/meson.build, test cases/rewrite/3 kwargs/remove.json, test cases/rewrite/3 kwargs/set.json
This PR adds support for rewriting select `kwargs` of the `project()`, `dependency()` and build target functions (`executable()`, `library()`, etc.).
Kwargs of these functions can be set and removed. If the kwarg is a list, elements can also be added and removed.
Again, no docs because this feature is still in beta :smiley:
=> rewriter: Add support for kwargs modification

mesonbuild/mconf.py
Purely visual fix to limit the size of the `Possible Values` column in the `configure` output. This patch makes the output easier to read for options with many possible choices (especially `cpp_std`).
=> mconf: Limit the line length of the choices column

docs/markdown/snippets/generator_with_multiple_outputs_4760.md, mesonbuild/backend/ninjabackend.py
This resolves ticket #4760 where a generator w/ multiple output nodes printed an empty string to the console (i.e. `Generating ''.`). This issue can be seen in the existing `meson-test-run.xml` logs on master (`test cases/common/90 private include/`). The issue becomes apparent when the generator has many input files and may take several minutes to complete. During this time, the user has minimal feedback as to what the build system is doing.
This commit will log the input source file that triggered the ninja rule to be executed. The ninja rule executing the generator will now print `Generating from: '<input source file>'` when there are multiple outputs from a single generator rule.
Alternatively, we could log all of the source files being generated from each input source file or a …
=> Fix console log from generator with multiple output nodes

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/compilers.py
This does two things:
* On windows GCC-like compilers, the subsystem is always explicitly specified (either `-mwindows` or `-mconsole`). MSVC is already explicit.
* The `gui_app` linker flags are now added after those mandated by external dependencies. This is because some misguided libraries (such as SDL) think that hijacking `main()` and forcing `-mwindows` in link flags is clever. We must unconditionally override such misuses to let gui_app work as intended.
=> Improve handling of gui_app

mesonbuild/compilers/d.py
Hi!
Apparently some pkg-config files use the GCC `-isystem` flag for their include directories (e.g. krb5-gssapi).
Since D code often links to C libraries, we need to translate this flag somehow if the DMD or LDC compiler is used, so the flag should either be dropped entirely, or translated.
This patch translates it to `-I`, which LDC and DMD can understand, and which is likely the less error-prone solution compared to just dropping the include directive entirely.
=> d: Translate the -isystem flag for LDC and DMD

docs/markdown/snippets/extract_objects-file-arg.md, mesonbuild/build.py, test cases/common/23 object extraction/meson.build
Passed strings are converted to Files, but passing a File directly wasn't supported yet. This PR adds that support.
=> Allow File arguments in extract_objects() arguments

docs/markdown/Reference-manual.md
As promised in #4950, here is some extra detail in the documentation for `extract_objects()`.
It wasn't clear to me what notation to use for the arguments: I went with `(source1, source2, ...)` but I also saw `(list_of_sources)` and `(list_of_sources, ...)` used. Are there subtle differences between these, or is there a lack of consistent notation for function arguments?
=> Clarify in docs the argument types extract_objects() accepts

mesonbuild/mesonlib.py
Fix library directory detection on FreeBSD. FreeBSD uses /usr/local/lib, /usr/lib and /lib for libraries, regardless of architecture and platform. Ensure that even if, as an example, /usr/lib64 exists, don't use it as the default_libdir() and don't suggest it as a directory to look for shared libraries in.
=> fix default library path handling on FreeBSD

mesonbuild/backend/vs2010backend.py
This allows to view the build step in VS and reuses the same concept that
we use for run targets instead of maintaining two different behaviors.
=> vs: use CustomBuild instead of CustomBuildStep for custom targets

docs/markdown/Cuda-module.md, mesonbuild/compilers/cuda.py, mesonbuild/modules/unstable_cuda.py
Assorted changes:
- Sanity check of NVCC compiler is modified to also detect and enumerate GPU compute capabilities, which the compiler collects and returns.
- Fixes for #4961, with credits to @jml1795 for `-Werror`'s solution.
- Rename `Volta+Tegra` to the apparently more-official `Xavier`.
- Updates to CUDA module documentation.
=> CUDA fixes

docs/markdown/Reference-manual.md
Fixes https://github.com/mesonbuild/meson/issues/4916
=> docs: compiled() only works with compiler.run() results

azure-pipelines.yml, ci/install-dmd.ps1
The package has been moved from python3-pip to python3N-pip where N is 5, 6, 7. We use Python 3.5, so let's use that.
=> azure-pipelines: Fix cygwin and vs2015x86ninja CI failures

mesonbuild/environment.py
It seems this was erroneously coppied in `54b6afa67`.
=> Remove redundant definition of `cflags_mapping`

mesonbuild/ast/introspection.py, test cases/unit/53 introspect buildoptions/main.c, test cases/unit/53 introspect buildoptions/meson.build
This fixes a crash in the introspection interpreter when a variable is provided for a target name. In this case, the name can not be resolved.
=> mconf: Fixed crash for variables in targets (closes #4960)

mesonbuild/backend/ninjabackend.py, test cases/fortran/4 self dependency/meson.build, test cases/fortran/4 self dependency/src/selfdep_mod.f90, test cases/fortran/7 generated/prog.f90
Fixes https://github.com/mesonbuild/meson/issues/4974
Uses absolute file path instead of relative file path for better reliability.
=> Fortran: handle self-referential files

docs/markdown/Generating-sources.md
By using private_dir_include() instead of enumerating headers in sources
of declare_dependency. Much more convenient, especially when there are
many headers.
Found out about this by reading #4638. It is not documented anywhere as
far as I can tell.
=> Improve declare_dependency() example in Generating-sources.md [skip ci]

mesonbuild/rewriter.py, run_unittests.py, test cases/rewrite/3 kwargs/defopts_delete.json, test cases/rewrite/3 kwargs/defopts_set.json, test cases/rewrite/3 kwargs/remove_regex.json
With this PR, it is possible to set and delete project default options from the `meson.build`.
Again, beta feature --> no docs 😃. I will do separate PR for docs and a sensible CLI.
With #4929 and this PR, all features I originally wanted to implement are implemented. Are there other obvious parts, where the rewriter could be useful (especially for IDE integration, cc @textshell)?
=> rewriter: Set and delete project default options

mesonbuild/rewriter.py
This patch makes the dict iterations in the rewriter deterministic (by sorting them), which is appaerently neccessary for different python versions/platforms. This fixes the current Azure cygwin CI issues.
=> rewriter: Sort dict iterations to fix unit tests

mesonbuild/compilers/compilers.py, mesonbuild/coredata.py, mesonbuild/envconfig.py, mesonbuild/environment.py, mesonbuild/interpreter.py
You can look at each commit for more details, but the short story is two things:
1. `environment.py` imports to many modules. If we separate the configuration types (few dependencies) vs configuration defaulting logic (many dependencies), we can break up modules, and break up the implicit import cycles that already exist (type annotations would make them clear). It's a true separation of concerns.
2. Config file and environment variable code paths for compiler options were too far apart. Prior, we at least made everything go through compiler options and not config files directly. The next step is this: making sure those options are initialized in one place.
CC @dcbaker
=> Move around config file classes

azure-pipelines.yml, ci/azure-steps.yml
The CI currently fails for all `vs2017` jobs because Python 2 instead of Python 3 is used.
=> azure: Fix python3 in vs2017 tasks

docs/markdown/snippets/introspect_projectinfo_subprojects_dir.md, mesonbuild/ast/introspection.py, mesonbuild/mintro.py, run_unittests.py
This allows applications interfacing with Meson (such as IDEs) to know about an overridden subproject directory.
=> mintro: Add subproject_dir to --projectinfo

mesonbuild/mparser.py, test cases/common/113 ternary/meson.build
Currently there ar ea number of cases where a ternary cannot be used, as arguments to functions or in lists, for example. This is just because their representation in the parser doesn't fulfill all of the interfaces it needs to.
@jpakkane, I think it might be good to get this in 0.50 if possible.
=> Fix ternary in thing

mesonbuild/mparser.py, mesonbuild/rewriter.py
Remove the manual parsing of meson in the rewriter, in favor of detecting the end of a node in `mparser.py`.
=> rewriter: Use mparser to detect the end of some nodes

docs/markdown/Reference-manual.md, docs/markdown/Unit-tests.md, mesonbuild/backend/backends.py, mesonbuild/interpreter.py, mesonbuild/mtest.py, run_unittests.py, test cases/common/212 tap tests/meson.build, test cases/common/212 tap tests/tester.c, test cases/failing test/4 hard error/main.c, test cases/failing test/4 hard error/meson.build, test cases/failing test/5 tap tests/meson.build, test cases/failing test/5 tap tests/tester.c
This series lets Meson handle the TAP protocol for tests. TAP output is parsed and converted into a pass/fail/skip outcome which is then checked against `should_fail`. In addition, errors in the test itself, such as TAP parsing errors, are treated as a hard error outcome that cannot be overridden by `should_fail`.
For now, it only supports outputting the results on a per-`test()` level; the outcomes of each TAP-level testcase are recorded in the standard output but not e.g. in the JSON test results. However, this pull request introduces the required language changes and parsing support, so that further improvements can go in on top.
=> Add initial TAP test support

docs/markdown/IDE-integration.md, docs/markdown/snippets/introspect_deps_no_bd.md, docs/markdown/snippets/introspect_targets_no_bd.md, mesonbuild/ast/__init__.py, mesonbuild/ast/introspection.py, mesonbuild/ast/postprocess.py, mesonbuild/mintro.py, mesonbuild/rewriter.py, run_unittests.py, test cases/unit/52 introspection/meson.build
This PR uses the changes introduced in the rewriter PR's to also provide introspection information without a build directory for targets and dependencies. I am not sure how useful the `--targets` introspection will be, but the information was basically already there, so I added it.
@ignatenkobrain I think you wanted something similar to this dependency introspection in the IRC?
Since this affects the introspection API: cc @textshell
=> mintro: Introspect targets and deps without a build directory

data/shell-completions/bash/meson, data/shell-completions/zsh/_meson, mesonbuild/mesonmain.py, mesonbuild/mtest.py
Haven't had time to try and get the list of options to complete `-D`, but I'll try and add that as a follow up when I get the time.
Also left to do: `meson configure`, `meson test`, `meson introspect`.
=> Add completion scripts for Bash and Zsh

docs/markdown/Python-module.md, docs/markdown/snippets/python-path-method.md
Since this method was not included in 0.46-00.49 we should document that.
=> docs: document that the .path() method for Python is new in 0.50 [skip ci]

docs/markdown/Pkgconfig-module.md, mesonbuild/modules/pkgconfig.py
The documentation for this change was left out of its implementation in commit b4aee4675afd9f9f4a36aea628bab4249d7addbc and was later documented in commit f831c05b553d876a08dcf46478161b60b4e693c4 as if it had always existed.
This caught me out in https://github.com/linuxmint/cinnamon-menus/pull/27#issuecomment-470255359 as I tried to use "libraries" on its own to get around the lack of 0.46.0 availability, however that also meant "version" did not work either.
=> pkgconfig.generate: add FeatureNew and documentation for implict version

mesonbuild/modules/hotdoc.py
The same way as we set '--sources-top-dirs' for gi
=> hotdoc: Set gi-c-source-root

mesonbuild/compilers/c.py, run_unittests.py
We need to account to the possible prefixes (empty or 'lib').
This allows both to work:
cc.find_library('foo')
cc.find_library('libfoo')
=> Fix _get_patterns on OpenBSD

mesonbuild/environment.py
We need to match the "clang --version" output on OpenBSD:
$ clang --version | head -1
OpenBSD clang version 7.0.1 (tags/RELEASE_701/final) (based on LLVM 7.0.1)
=> environment: support OpenBSD in detect_objc_compiler

mesonbuild/compilers/compilers.py
OpenBSD does not link libc into shared libraries by default to avoid binding
libraries to specific libc majors. So prevent passing "-Wl,--no-undefined" or
"-zdefs" when linking (those options have always suffered false positives on
this operating system).
=> GnuLikeCompiler: don't set b_lundef by default on OpenBSD

test cases/common/137 get define/meson.build
Same as with NetBSD, OpenBSD doesn't provide a ZLIB_VER_MAJOR but has
ZLIB_VERSION instead.
=> test: fix "get define" on OpenBSD

mesonbuild/dependencies/base.py, run_unittests.py, test cases/unit/58 pkgconfig relative paths/pkgconfig/librelativepath.pc
This pull request adds a patch made by @nirbheek to handle relative paths in pkgconfig files and the specific unit test.
=> Relative paths pkgconfig

mesonbuild/environment.py
The purpose of this change is to improve the maintainability of Meson module mesonbuild/environment.py by defining the regular expression used in search_version()
with a compiled verbose regular expression with line comments. This change should not
affect Meson functionality in any way.
Note: This is my very first PR of any kind on Github. All constructive advice is welcome.
=> Fix Issue 5020 With Verbose RE Definiton in search_version

mesonbuild/msubprojects.py, mesonbuild/wrap/wrap.py
* If clone-recursive is specified, populate submodules only after the specified revision/branch has been checked out. Fixes #4996
* Update submodules recursively on `meson subprojects update`
=> Fix git wraps with submodules

docs/markdown/Reference-manual.md, docs/markdown/snippets/find_library_static.md, mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/c.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/vala.py, mesonbuild/dependencies/base.py, mesonbuild/interpreter.py, run_unittests.py, test cases/linuxlike/14 static dynamic linkage/main.c, test cases/linuxlike/14 static dynamic linkage/meson.build, test cases/linuxlike/14 static dynamic linkage/verify_static.py
This patch allows the build file author to enforce static or dynamic linkage. I've found this to be necessary when the two versions are not equivalent.
AFAIK there are not really any naming standards when it comes to libraries on Windows. But from my experience it is more common to prefix the static version with 'lib' and not have any prefixes for the dynamic library. This patch therefore changes the order of the prefixes so that dynamic libraries are found first which seem to be the case already on other platforms.
=> Add static as keyword to find_library

mesonbuild/build.py
We've done this for coredata, just build builddata. There's some other data files, and really it would be nice to share a single serializer/deserializer pair for all of them.
This also doesn't cause an automatic rebuild, which should also be fixed, but it does
Fixes #5056
=> build: Handle EOFError and AttributeError like coredata

run_unittests.py
This is less hacky, and also prepares the way for #4010.
CC @dcbaker
=> Avoid module patching in `test_find_library_patterns`

run_unittests.py
OpenBSD doesn't have any support for the compiler sanitizers yet.
While this may change in the future, better fix test suite run in "failfast"
mode for now. This can be revisited once (if) we get support in the future.
* clang 7.0.1
$ make CFLAGS=-fsanitize=address foo
cc -fsanitize=address   -o foo foo.c
cc: error: unsupported option '-fsanitize=address' for target 'amd64-unknown-openbsd6.5'
* gcc 4.2.1
*** Error 1 in /tmp (<sys.mk>:85 'foo')
$ make CC=gcc CFLAGS=-fsanitize=address foo
gcc -fsanitize=address   -o foo foo.c
cc1: error: unrecognized command line option "-fsanitize=address"
* gcc 8.2.0
$ make CC=egcc CFLAGS=-fsanitize=address foo
egcc -fsanitize=address   -o foo foo.c
ld: error: unable to find library -lasan
collect2: error: ld returned 1 exit status
=> compilers: -fsanitize is not supported on OpenBSD

run_unittests.py
Similar to https://github.com/mesonbuild/meson/pull/5067
This part was missed in my previous commit.
=> compilers: -fsanitize is not supported on OpenBSD (second pass)

mesonbuild/build.py
Since the "-l<lib>" flags in the build.ninja file are passed in
"--start-group"/"--end-group" flags, there should be no need to have any
library listed twice, even if there are circular dependencies. Therefore we
can eliminate duplicates. For speed, rather than deduplicating at the end
of the process, it's faster to not add the duplicate flags in the first
place.
This should help fix #2150
=> do not duplicate external dependencies in list

run_project_tests.py
These don't work and no one has fixed them. When I've tried to
download dmd for windows I can't get a valid installer from their
website. Let's at least turn the CI green.
=> tests: disable Dlang tests on windows

mesonbuild/modules/i18n.py
@permittedKwargs() is basically copying the logic of CustomTarget,
but it is not actually up to date, leading to warnings on perfectly
valid values such as 'build_by_default'.
Use CustomTarget.known_kwargs instead, and only append the specific
kwargs of i18n.merge_file().
Fixes #5079
=> i18n: Use CustomTarget.known_kwargs at permittedKwargs()

mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, run_unittests.py, test cases/unit/55 dedup compiler libs/app/app.c, test cases/unit/55 dedup compiler libs/app/meson.build, test cases/unit/55 dedup compiler libs/liba/liba.c, test cases/unit/55 dedup compiler libs/liba/liba.h, test cases/unit/55 dedup compiler libs/liba/meson.build, test cases/unit/55 dedup compiler libs/libb/libb.c, test cases/unit/55 dedup compiler libs/libb/libb.h, test cases/unit/55 dedup compiler libs/libb/meson.build, test cases/unit/55 dedup compiler libs/meson.build
commit 8b065530f6aeebb8ad0af2c58a91c06db82d6491:
```
compilers: Try harder to dedup builtin libs
-ldl, -lm, -lpthread should always be de-duplicated, no matter what.
Closes https://github.com/mesonbuild/meson/issues/2150
```
commit a17ee513c46a1b6913c724a38504805e2a8e5f3b:
```
compilers: Update comment about library search patterns
```
Closes #2150
=> compilers: Try harder to dedup builtin libs  

docs/markdown/Users.md
Add the libcamera project as a user of Meson.
=> Add libcamera to Users.md [skip ci]

azure-pipelines.yml, ci/azure-steps.yml
It looks like BOOST_ROOT is now set in the azure v2017 image (relevant change seems to be [1], pre-installing boost)
Remove BOOST_ROOT from the environment to prevent attempting to use a boost which is incompatible with the compiler.
[1] https://github.com/Microsoft/azure-pipelines-image-generation/pull/732
=> azure: Unset BOOST_ROOT for Cygwin, MSYS2 and clang-cl

mesonbuild/dependencies/misc.py, mesonbuild/modules/python.py
For dynamic linking, some mingw releases don't link
correctly with pythonXX.lib in all cases.
This patch forces mingw to link against
pyhthonXX.dll instead of the .lib file, which has
a better compatiblity.
Note that msys 1.0 old platform is detected
as windows instead of 'mingw'
=> dependencies: fix Python linking for windows+mingw

mesonbuild/compilers/c.py, mesonbuild/environment.py, mesonbuild/linkers.py, test cases/windows/5 resources/res/meson.build
Closes #4463.  Supersedes #4040.
=> Fix linking when cross-compiling and a windows resource is first object

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/c.py, mesonbuild/compilers/fortran.py, mesonbuild/dependencies/base.py, mesonbuild/interpreter.py, mesonbuild/mesonlib.py, run_unittests.py
This patch creates an enum for selecting libtype as static, shared,
prefer-static, or prefer-shared. This also renames 'static-shared'
with 'prefer_static' and 'shared-static' with 'prefer_shared'. This is
just a refactor with no behavioral changes or user facing changes.
=> replace library type strings with an enum

docs/markdown/snippets/multiple-cross-files.md, mesonbuild/backend/backends.py, mesonbuild/coredata.py, mesonbuild/environment.py, mesonbuild/msetup.py, mesonbuild/munstable_coredata.py, run_unittests.py, test cases/unit/57 native file override/crossfile2
Allow multiple --cross-file options, just like multiple --native-file options
are allowed.  The use-case for this is a centralised cross file for the
compiler, and then a cross file setting project-specific options.
Change coredata.cross_file (string) to coredata.cross_files (list of strings),
and update users appropriately.  Apart from the search path logic which is
untouched, the logic mostly mirrors coredata.config_files.
Also update run_unittests as it constructs a fake Environment so needs to set a
list-of-strings now.
Fixes #3518.
=> Support multiple --cross-file options

mesonbuild/dependencies/base.py
Whenever a non-executable Python script is found by find_program, currently Haiku and Windows replace a python3 from the shebang line with the one that was used by Meson.  Extend this behavior to POSIX systems so that it is easy to test a program with multiple Python versions.
Currently this is particularly important for generators, because they don't allow files in the arguments and thus you cannot do something like `generator(pymod.find_installation(), ..., arguments: [files('myscript.py'), ...])`. With this patch you can just do `generator(find_program('myscript.py'), ...`.
=> find_program: use Meson's Python3 for non-executable Python scripts

mesonbuild/envconfig.py
The cross-file cleanup meant this function is no longer used, so remove it.
=> envconfig: remove unused parse_datafile()

docs/markdown/Kconfig-module.md, docs/markdown/snippets/kconfig.md, docs/sitemap.txt, mesonbuild/interpreter.py, mesonbuild/modules/unstable_kconfig.py, run_project_tests.py, test cases/kconfig/1 basic/.config, test cases/kconfig/1 basic/meson.build, test cases/kconfig/2 subdir/.config, test cases/kconfig/2 subdir/dir/meson.build, test cases/kconfig/2 subdir/meson.build, test cases/kconfig/3 load_config files/dir/config, test cases/kconfig/3 load_config files/dir/meson.build, test cases/kconfig/3 load_config files/meson.build, test cases/kconfig/4 load_config builddir/config, test cases/kconfig/4 load_config builddir/meson.build
Add kconfig integration such that existing projects can use the ".config" file from a kconfig system to conditionally compile in or out features.
The code is an updated version of the original submission in pull request #1617. Compared to the original, it uses the dictionary objects that have since been introduced in meson, and it lets you pass the input as a file object. This makes for a more flexible and easier to use API.
=> Kconfig Module

ci/azure-steps.yml
Following up on https://github.com/mesonbuild/meson/pull/4376#issuecomment-430021383, apparently the [fix has been deployed](https://developercommunity.visualstudio.com/content/problem/350007/build-from-github-pr-fork-error-tf400813-the-user-1.html), so PRs can now publish their logs as build artifacts.
=> Revert "azure: Don't try to publish logs from fork"

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/c.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/misc.py
Currently we specialcase OpenMP like we do threads, with a special
`need_openmp` method. This seems like a great idea, but doesn't work
out in practice, as well as it complicates the opemp
implementation. If GCC is built without opemp support for example, we
still add -fopenmp to the the command line, which results in
compilation errors.
This patch discards that and treats it like a normal dependency,
removes the need_openmp() method, and sets the compile_args attributes
from the compiler.
Fixes #5115
=> dependencies/openmp: Don't special case OpenMP

mesonbuild/interpreter.py, test cases/failing/95 vala without c/meson.build, test cases/vala/2 multiple files/meson.build
Move check for 'vala' appearing without 'c', so it applies to `add_languages()` as well as `project()`.
Noticed while looking into #2392 .
=> Disallow add_languages('vala') without 'c'

mesonbuild/environment.py, mesonbuild/interpreter.py
This function is used just once. It also seems all policy and no
mechanism (it raises, it calls the same function to do all the work
twice in an uninteresting way). This makes it seem to be as a good
candidate for inlining.
environment and coredata are woah fully intertwined and this doesn't fix
that, but at least it makes it easier to follow.
=> Inline check_compilers

mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/rust.py, test cases/rust/5 polyglot static/meson.build
One of the tests does not run because it ends up using Rust's stdlib dynamically and it is not in PATH by default. Instead it is hidden deep inside the `.rustup` dir somewhere. Copying it manually to the build dir makes it work but is an awful solution.
=> Fix setup so test suite runs with rustc + MSVC. Closes: 5099

data/macros.meson
'if-release' does not catch buildtype=plain, so we need to do this.
=> rpm: Always set b_ndebug to true

mesonbuild/environment.py
Historically on BeOS the intel platform was named "BePC", and we kept this in Haiku.
=> Properly detect 'bepc' as 'x86' CPU for Haiku

mesonbuild/environment.py
I found this in issue #3405:
> We specify other program overrides with envvars (CC et al). I guess we would use NINJA for this at least until "native file" support materialises.
I am not sure what is "native file support", anyway this pull request adds support for NINJA.
=> Support a NINJA environment variable

mesonbuild/mtest.py
This will make verbose output nicer, since it will not interleave the test
stdout/stderr and the test results.
=> do not use Executor if only one process was requested

mesonbuild/dependencies/base.py
It was a mistake in retrospect to not make this deprecated in the
first place, so let's do that. When cross files were new we needed
this as a way to specify a llvm-config binary, since it could be
passed via PATH overrides.
=> dependencies/configtool: Deprecate falling back to path

docs/markdown/snippets/preproc-flags.md, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/coredata.py, mesonbuild/munstable_coredata.py, run_unittests.py
I recall that @jpakkane never wanted this, but @nirbheek did, but then @nirbheek changed his mind.
I am fine either way except for the cross inconsistency that exists today: There is no `c_preproc_args` or similar one can put in the cross file, so no way to replicate the effect of `CPPFLAGS` during cross compilation.
Closes #4272
CC @dcbaker
=> Don't collect preprocssor flags separately from compiler flags

mesonbuild/interpreter.py
On Windows, program on a different drive than srcdir won't have an expressible relative path; cmd_path will be absolute instead and shouldn't get added into build_def_files.
This should fix https://gitlab.freedesktop.org/gstreamer/gst-build/issues/8 and similar issues.
=> Fix run_command() with command on a different drive

mesonbuild/scripts/gettext.py
If POTFILES.in exists, then it will have come from autotools, in which case it is explicitly the file passed to xgettext -f, and the POTFILES file itself is generated by autotools as a proxy file which eventually gets inlined into the final Makefile as a variable "POTFILES = ......"
In this case, attempting to use POTFILES as the input file will simply result in syntax errors and the inability to find files with a literal trailing " \" in the name. Usually POTFILES will not exist at all, and we would fallback on POTFILES.in, but if the source tree happens to be dirty, this would result in errors. Since it's never going to be right to use it, we can just do the right thing from the start and carry on.
=> gettext: prefer POTFILES.in if it exists

docs/markdown/Builtin-options.md
- Added missing universal options.
- Split options in `directories` and `core` groups.
- Sorted alphabetically some of the groups.
- Removed `cross-file` from options, since it's not an option.
=> [Docs] Built-in options page cleanup (fixes #5165)

docs/markdown/Reference-manual.md, mesonbuild/dependencies/base.py, test cases/common/189 partial dependency/declare_dependency/meson.build
There is a bug in the `partial_dependency` method of `declare_dependency` that manifests when a subdependency (one added through the `dependencies` keyword) has attributes that the parent doesn't. In these cases the partial dependency will not have the attributes from the subdependencies.
In looking at that I realized that the implementation for `dependency` ignores the `sources` and `includes` arguments, which it shouldn't.
Since the first bug would have been found by type annotations, I've added those as well.
=> Bug fixes in get_partial_dependency

docs/markdown/Reference-manual.md
The environment() function was added in 0.35.0 (which contains a2e7ebc5,
containing the actual addition)
=> docs: Document when environment() was added

mesonbuild/environment.py
OpenBSD uses arm64 as identifier for the 64-bit ARM architecture.
Refs #1578.
Hopefully fixes an OpenBSD build error in dav1d https://code.videolan.org/videolan/dav1d/issues/268. OpenBSD `uname -m` returns 'arm64'.
=> detect 'arm64' as aarch64 CPU family

docs/markdown/snippets/sanity-check.md, mesonbuild/compilers/c.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, mesonbuild/compilers/swift.py, mesonbuild/compilers/vala.py, run_project_tests.py, run_unittests.py, test cases/common/177 initial c_args/meson.build, test cases/common/177 initial c_args/test_args.txt
Previously cross, but not native, external args were used. Then in
d451a4b the cross special cases were
removed, so external args are never used.
This commit switches that so they are always used. Sanity checking works
just the same as compiler checks like has header / has library.
Fixes #5086 for master bug not suitable for 0.50.
=>  Sanity check with external args

test cases/failing/85 gtest dependency with version/meson.build
If gtest is patched to have a pkg-config file, that will report the version, so force the 'system' method to be used when we are exercising that an unknown version doesn't satisfy any version constraint.
Closes #5153
=> Fix 'failing/85 gtest dependency with version' test to fail on Arch

mesonbuild/ast/interpreter.py, mesonbuild/ast/introspection.py, run_unittests.py, test cases/unit/55 introspection/meson.build, test cases/unit/55 introspection/meson_options.txt
This PR fixes some introspection crashes related to unresolved function nodes. I think this should go into 0.50.1, since this a pure bugfix PR.
=>  mintro: Fix crash when required is a function (closes #5177)

ci/install-dmd.ps1, mesonbuild/compilers/d.py, run_project_tests.py
Fixes the linker errors and re-enables the D tests for AppVeyor.
=> d: Fix linker errors with shared libraries on Windows

mesonbuild/scripts/symbolextractor.py
If we change a symbol size (e.g. array) in a .c file that is a part of
.so, executables that use it are not re-linked resulting in a runtime
error:
"Symbol xyz has different size in shared object, consider re-linking"
Adding symbol sizes to .symbol files fixes this issue.
=> Add symbol sizes to .symbols files

mesonbuild/dependencies/misc.py, test cases/frameworks/17 mpi/is_broken_ubuntu.py, test cases/frameworks/17 mpi/main.f90, test cases/frameworks/17 mpi/meson.build
The MPI dependency() allows MSMPI with Fortran, which in general does not work, except for Intel Fortran. This PR enacts that restriction to avoid false-positive "MPI Found" on Windows with incompatible compiler+MPI.
=> BUGFIX: Microsoft MPI is only compatible with Intel Fortran

ciimage/Dockerfile, docs/markdown/Dependencies.md, docs/markdown/snippets/gpgme-config.md, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/misc.py, test cases/frameworks/27 gpgme/gpgme_prog.c, test cases/frameworks/27 gpgme/meson.build
GPGME does not support pkg-config so we need config-tool support if we do not want projects like Almanah and Seahorse to parse the values manually.
=> Add gpgme-config support

mesonbuild/mtest.py
TAP needs to process the test stdout even if --verbose is passed. Therefore mtest has to capture it to a separate temporary file. If --verbose was passed, stdout is printed at the end for consistency with non-TAP tests; in the future, each test point could be printed in verbose mode by parsing the TAP output on the fly.
=> mtest: fix TAP with --verbose

mesonbuild/coredata.py, mesonbuild/dependencies/base.py, mesonbuild/msetup.py, mesonbuild/optinterpreter.py, run_cross_test.py, run_unittests.py, test cases/unit/55 pkg_config_path option/extra_path/totally_made_up_dep.pc, test cases/unit/55 pkg_config_path option/meson.build
This creates a new command line option to store pkg_config_path into,
and store the environment variable into that option. Currently this
works like the environment variable, for both cross and native targets.
=> dependencies: Add command line option for pkg_config_path

docs/markdown/Subprojects.md, docs/markdown/snippets/subproject-foreach.md, mesonbuild/msubprojects.py
Sometimes it is convenient to run an arbitrary command (e.g. 'git diff')
on all subprojects.
Add a 'meson subprojects foreach' command to take care of that.
For this command the common argument 'subprojects' does not make sense,
so only add '--sourcedir' and cover the case of a missing
options.subprojects in run().
If there is interest in this new command I will update the docs too.
The name `foreach` has been suggested by @xclaesse 
Thanks, Antonio
=> Add 'meson subprojects foreach' command

docs/markdown/snippets/introRemovedTargetFiles.md, mesonbuild/mintro.py, run_unittests.py
I think we can now remove the deprecated `--target-files` introspection API for meson 0.51.0. As far as I know, no projects are using this API anyway.
CC @textshell
=> mintro: removed deprecated --target-files API

docs/markdown/Reference-manual.md
Since this is targeting the 0.50.1 bugfix release.
we'll only need this if the partial dependency fixes get pulled into 0.50.1
=> docs: Change 0.51 to 0.50.1 [skip ci]

mesonbuild/environment.py, run_unittests.py, test cases/unit/58 identity cross/build_wrapper.py, test cases/unit/58 identity cross/host_wrapper.py, test cases/unit/58 identity cross/meson.build, test cases/unit/58 identity cross/stuff.h
This defines 'is_cross_build()` in terms of whether we have a cross
file, not whether `build_machine == host_machine`.
This should only be used in 0.50.*. The better fix for master is #4010,
which keeps the existing `is_cross_build()`, but allows separate
compilers targetting the build and host machine in all cases. These
points in the direction of Meson being agnostic to whether the build is
a cross build, and `is_cross_build()` just being a convenience for the
user.
Fixes #5102
=> Fix build = host cross builds for 0.50.*

mesonbuild/msetup.py, test cases/common/144 mesonintrospect from scripts/check_introspection.py, test cases/common/144 mesonintrospect from scripts/meson.build
All files must be written before running postconf scripts or they can't do introspection. Also, update the test to _actually check_ that introspection is working.
This broke in 0.50.0 and should probably be backported. @nirbheek
=> Fix introspection in postconf scripts

mesonbuild/build.py, mesonbuild/interpreter.py, run_unittests.py, test cases/unit/59 test env doesn't stack/meson.build, test cases/unit/59 test env doesn't stack/script.py
Warn when someone tries to use append() or prepend() on an env var
which already has an operation set on it. People seem to think that
multiple append/prepend operations stack, but they don't.
Closes https://github.com/mesonbuild/meson/issues/5087
=> interpreter: Warn when environment() ops are overriden

docs/markdown/Reference-manual.md
As a newcomer to the Meson build system, I found the documentation of the `library()` function to be a bit misleading. Eventually I found what 'user option' referred to after digging through the docs.
This just adds a link back to the page that describes the options that are referred to in this paragraph.
--
Closes #5260
=> [skip ci] Link to builtin options from `library()` function description

docs/markdown/Dependencies.md, docs/markdown/snippets/gpgme-config.md, mesonbuild/dependencies/misc.py, test cases/frameworks/27 gpgme/meson.build
Since gpgme 1.13.0, pkg-config files are available and this is the preferred way to detect the dependency. Without this, projects that wish to generate pkg-config files that Requires.private on gpgme, now have their custom dependency() fallbacks overridden with an incorrect configtool dependency.
=> fix gpgme support by preferring pkg-config where possible

mesonbuild/dependencies/misc.py
Shaderc finally added pkg-config files. This patch makes pkg-config the primary way to find shaderc, and smooths out the oddities of the way they've done their pkg-config files.
=> Shaderc pkg config

mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/build.py, run_unittests.py
If find_program() returns a file from the source directory, anything that uses it should add the file to the dependencies, so that they are rebuilt whenever the script changes. Meson generally handles this right, but not in generators.
=> Script found by find_program() does not end up in dependencies

mesonbuild/compilers/c.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, mesonbuild/compilers/swift.py, mesonbuild/compilers/vala.py
Builds with Meson 0.50.0 fail in this special case:
[binaries]
c = '.../arm-unknown-linux-uclibcgnueabi/bin/arm-unknown-linux-uclibcgnueabi-gcc'
...
[binaries]
exe_wrapper = 'qemu-arm-static'
...
[properties]
c_link_args = ['-static']
...
The sanity check output is not a static binary, as it used (and expected to be)
with Meson < 0.50.0. The crosstool-ng built uClibc is not present in the
build machine's /lib, so the sanity check fails.
This bug was introduced in d451a4bd97f827bb492fd0c0e357cb20b6056ed9.
This partially reverts that for `0.50.*`. master will instead always use
this flags in cross and native alike for consistency as per #5128.
Fixes #5086.
=> compilers: respect cross-file flags in sanity checks [0.50.* only]

mesonbuild/coredata.py, run_unittests.py, test cases/unit/50 std remains/meson.build, test cases/unit/50 std remains/prog.c
Will make a `0.50` hotfix cherry-pick if this looks good. CC @jpakkane @dcbaker @nirbheek.
=> Fix `-Dc_std=...` not affecting cross compilation. Closes #5097. [0.50.* only]

mesonbuild/munstable_coredata.py
In 0.50 `meson unstable-coredata` throws exceptions because the coredata format changed a bit. Fix that.
=> munstable_coredata: Fix exception (for 0.50.1)

test cases/failing/96 dependency not config-tool/96 unknown config tool/meson.build
This failed with an exception with 0.49. Fixed by c0166355, but add a test case to ensure it doesn't regress.
Report on IRC:
> 2019-04-13 20:50:57     mitigate        I need to put a dependency on "ecl", which comes with /usr/bin/ecl-config. I tried putting in a: ecl_dep = dependency('ecl', method: 'config-tool').  but it with an index out of range error in pkg_exc dependencies/base.py. Is it expected to work out of the box like this?
=> Add a test case for dependency(method:'config-tool') with an unknown name

mesonbuild/interpreter.py, run_unittests.py
Also add a test for it so we don't regress this in the future.
Closes https://github.com/mesonbuild/meson/issues/5281
Closes https://github.com/mesonbuild/meson/issues/3480
@jpakkane @ignatenkobrain do you think we can get this into old versions of Debian/Ubuntu/Fedora so that people get helpful error messages?
=> interpreter: Check the meson version before parsing options

mesonbuild/coredata.py
As per https://github.com/mesonbuild/meson/pull/5171#issuecomment-477950012
Regrouped built-in options in two sorted groups: directory options and core options (same as in [Builtin-options.md](https://github.com/mesonbuild/meson/blob/master/docs/markdown/Builtin-options.md))
=> Updated meson --help output

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, run_unittests.py
A pack of updated to Elbrus compiler support (was broken since commit 386e5b8 and probably other commits).
Output of `./run_unittests.py`: 
```
kaguya /usr/src/meson # ./run_unittests.py
......s...............s......s.........................................................................s....s........../tmp/tmp_tgws5xi/meson-private/sanitycheckobjc.m: file not recognized: Формат файла не распознан
...ss.......s.s.s.s.......ss..sss......................................................s.....s.......s.s..s...........s......sssssssssssssss
----------------------------------------------------------------------
Ran 259 tests in 774.007s
OK (skipped=37)
kaguya /usr/src/meson #
```
=> Update lcc support

mesonbuild/coredata.py, mesonbuild/environment.py, run_unittests.py
Currently they're forced to absolute paths when they're stored in the
coredata datastructure, then when they're loaded we de-absolute path
them to check if they're in the system wide directories. This doesn't
work at all, since the ninja backend will generat a dependency on a
file that is in the source directory unless the path was already given
as absolute. This results in builds being retriggereed forever due to
a non-existant file.
The right way to do this is to figure out whether the file is in the
build directory, is absolute, or is in one of the system paths at
creation time, and store that path as absolute if it is outside the
build directory, or relative if it is within (so that a source
directory can be moved). Then the code that reads the file and the
code that generates the …
=> coredata: store cross/native files in the same form they will be used

docs/markdown/Creating-releases.md, mesonbuild/scripts/dist.py
This makes more sense as the default for me, as it's not half-way, but it might be personal.  I understand that recursive submodules only happen in a small fraction of projects.
Tested, seems to work for me, but I can't claim to understand meson well.
=> dist: recurse into git submodules

docs/markdown/snippets/xtensa-toolchain.md, mesonbuild/environment.py
From (almost) all points of view, the Xtensa toolchain can be treated as
a regular GCC toolchain.
This patch adds very basic support so that, at least, meson does not
fail when trying to use "xt-xcc" (which makes it possible to use it
without problems).
=> Add support for the Xtensa toolchain

mesonbuild/compilers/compilers.py
When the '-Wl,-rpath-link' option refers to several folders, we can
either use one single entry, like this:
-Wl,-rpath-link,/path/to/folder1:/path/to/folder2:/path/to/folder3
...or we can use multiple entries, like this:
-Wl,-rpath-link,/path/to/folder1
-Wl,-rpath-link,/path/to/folder2
-Wl,-rpath-link,/path/to/folder3
Because the '-rpath-link' requires full folder paths, using the one
single entry option can result in a very long argument.
While this shouldn't be a problem, at least *one* toolchain (the latest
version of the Tensilica toolchain for Xtensa processors) segfaults when
using arguments that are too long.
Because other toolchains might be affected and because using multiple
entries instead of a very long one doesn't seem to have any drawback,
this patch changes the arguments …
=> Use individual entries for '-Wl,-rpath-link'

mesonbuild/compilers/fortran.py
With dependencies specifed, mode='compile' causes it to ignore the link
arguments and thereby always fails.
Fixes: #5306
=> fortran: fix compile.links() when passing dependencies

mesonbuild/ast/interpreter.py, mesonbuild/ast/introspection.py, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/interpreter.py, mesonbuild/mesonmain.py, run_unittests.py
This isn't safe given the way python implements default arguments.
Basically python store a reference to the instance it was passed, and
then if that argument is not provided it uses the default. That means
that two calls to the same function get the same instance, if one of
them mutates that instance every subsequent call that gets the default
will receive the mutated instance. The idiom to this in python is to use
None and replace the None,
```python
def in(value: str, container: Optional[List[str]]) -> boolean:
return src in (container or [])
```
if there is no chance of mutation it's less code to use or and take
advantage of None being falsy. If you may want to mutate the value
passed in you need a ternary (this example is stupid):
```python
def add(value: str, container: …
```
=> Don't use mutable types as default arguments

mesonbuild/ast/interpreter.py, mesonbuild/ast/introspection.py, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, test cases/unit/55 introspection/meson.build
This PR adds basic string processing functionality to the `AstInterpreter`. This should cover most use cases. This should also resolve #5286. I am not sure if this should go into 0.50.2 or 0.51.0.
PS: @Akaricchi your taisei project really is an excellent integration test 😄
=> ast: Add basic string operation support for AstInterpreter (fixes #5286)

mesonbuild/environment.py
Hi,
From the commit message:
<i>The cl.exe from Visual Studio 2010 and earlier report '80x86', not 'x86', for the architecture that the compiler supports.  So, we ought to check for that as well to see whether we are building for 32-bit x86.</i>
This will fix issue #5189 when building GLib on Visual Studio 2010 and earlier.
=> environment.py: Fix architecture detection on older MSVC

mesonbuild/modules/cmake.py
Directly use `CMAKE_ROOT` instead of parsing `_INCLUDE_FILE` in the CMake module. This should be supported on all platforms and less error-prone.
=> cmake: Use CMAKE_ROOT instead of _INCLUDE_FILE (closes #5218)

mesonbuild/envconfig.py, mesonbuild/mesonlib.py, mesonbuild/mlog.py
Mostly this is just type annotations, but there are a few fixes in here to correct situations that work, but are not strictly type correct. I picked these two as a starting point as they're relatively contained and relatively simple.
You can verify these with `mypy --follow-imports=silent --strict $module`. There is one warning in envconfig about using an untyped function from another module, but other than that this is clean. If there's interest I'll create a CI job to run against modules as they become fully typed so that we can ensure that the type safety isn't broken.
=> Fully annotate the envconfig and mlog modules

data/macros.meson
Previously, this called out to the %ninja_test macro to run the
tests, but that limits us to only the arguments that ninja can
understand. In particular, it is not possible to add a test
timeout multiplier (such as is sometimes needed when building for
slow architectures such as armv7hl). With this patch, it will be
possible to specify `%meson_test -t 5` in the RPM spec file
without needing to patch the sources to extend the timeouts,
making life easier for packagers.
Related: https://github.com/mesonbuild/meson/issues/2037
Signed-off-by: Stephen Gallagher <sgallagh@redhat.com>
=> RPM Macros: Use `meson test` for %meson_test

docs/markdown/Syntax.md, mesonbuild/mparser.py, test cases/common/185 escape and unicode/meson.build
Document that unrecognized escape sequence behaviour is similar to python, not C.
See also #3188
=> consistent invalid escape sequence behaviour

docs/markdown/Builtin-options.md
I forgot to add these when I added the `vc++` flags in #4403.
=> Add vc++ cpp_std flags to the documentation

docs/markdown/Reference-manual.md, docs/markdown/snippets/link_language.md, mesonbuild/build.py, mesonbuild/compilers/fortran.py, run_project_tests.py, test cases/fortran/14 fortran links c/clib.c, test cases/fortran/14 fortran links c/f_call_c.f90, test cases/fortran/14 fortran links c/meson.build
As noted in the snippet, there are cases where there is a need to specify the language of the linker.
Meson's auto-detection doesn't always work, particularly where the main program is in Fortran.
A test case is added for this.
This works for GCC, Intel, Flang/Clang and PGI compilers at least for that test case.
I also added missing link argument for PGI compiler (BUGFIX)
=> per-target manual specification of link_language

mesonbuild/envconfig.py, mesonbuild/mesonlib.py
To (hopefully) work around a bug in old versions of python 3.5 (at least
as late as 3.5.2, but before 3.5.5).
Fixes #5326
=> mesonlib: Make typing.Type calls into strings

mesonbuild/munstable_coredata.py, run_unittests.py
On master `meson unstable-coredata` throws exceptions because the coredata format changed a bit. Fix that.
For 0.50 an additional fix is needed because `external_preprocess_args` was removed since then on master which also changed. See #5271
=> munstable_coredata: Adapt to coredata changes.

mesonbuild/envconfig.py
We're carrying this patch from when we were enabling running meson inside a MinGW environment.  I'd appreciate someone who actually uses Windows to verify this is correct!
=> envconfig: mingw is also Windows

mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/d.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/vala.py, mesonbuild/coredata.py, mesonbuild/dependencies/boost.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/ui.py, mesonbuild/interpreter.py, mesonbuild/modules/unstable_simd.py
This patch caches the results of compilers.compile() in coredata instead of a class variable. This way, the cached values can be used during reconfiguration. This improves the reconfiguration time significantly (5 seconds on my system for gst-build).
Some changes to the internal API where necessary to print the `(cached)` string. In fact, this refactor makes up the vast majority of the changes. In case the user feedback (`(cached)`) is not necessary, these changes can be easily reverted.
(Re)configure times for gst-build with the current master:
```
../meson/meson.py build  15.99s user 4.40s system 106% cpu 19.216 total
../meson/meson.py --reconfigure build  13.14s user 3.22s system 106% cpu 15.426 total
```
And here are the times with this patch:
```
../meson/meson.py build  15.57s user …
```
=> Cache compilers.compile() in coredata

mesonbuild/dependencies/base.py, mesonbuild/dependencies/data/CMakeListsLLVM.txt, mesonbuild/dependencies/dev.py, setup.py, test cases/common/161 config tool variable/meson.build, test cases/frameworks/15 llvm/meson.build, test cases/unit/47 native file binary/meson.build
This PR adds support for finding the LLVM framework with CMake. It also includes some generalizations for the base CMake dependency class to provide extensibility.
The `static` keyword isn't supported / is ignored because it is not really possible to tell CMake to find the static or shared version of a library.
This PR should fix #4861 and #4802
CC @dcbaker
=> CMake llvm dependency backend

mesonbuild/interpreter.py, test cases/failing/97 custom target install data/Info.plist.cpp, test cases/failing/97 custom target install data/meson.build, test cases/failing/97 custom target install data/preproc.py
While converting something to meson, I (mistakenly) wrote something like:
```meson
preproc = find_program('preproc.py')
t = custom_target('Info.plist',
command: [preproc, '@INPUT@', '@OUTPUT@'],
input: 'Info.plist.cpp',
output: 'Info.plist',
)
install_data(t)
```
and was rewarded with:
```
File "/wip/meson/mesonbuild/mesonmain.py", line 127, in run
File "/wip/meson/mesonbuild/msetup.py", line 240, in run
app.generate()
File "/wip/meson/mesonbuild/msetup.py", line 158, in generate
File "/wip/meson/mesonbuild/msetup.py", line 187, in _generate
intr.run()
File "/wip/meson/mesonbuild/interpreter.py", line 3847, in run
super().run()
File "/wip/meson/mesonbuild/interpreterbase.py", line 407, in run …
```
=> Fix an assertion exception when misusing install_data

docs/markdown/Reference-manual.md, docs/markdown/snippets/target-type-shared-module.md, mesonbuild/interpreter.py, test cases/common/122 shared module/meson.build, test cases/common/184 bothlibraries/meson.build, test cases/common/3 static/meson.build, test cases/common/4 shared/meson.build, test cases/common/93 default library/meson.build
Allow `build_target()` to be called with `target_type: 'shared_module'`. Not having this looked like an oversight. 
Fixes https://github.com/mesonbuild/meson/issues/5342
=> add support for "target_type: 'shared_module'" in build_target()

mesonbuild/modules/pkgconfig.py
Hello. I encountered a UnicodeEncodeError exception when I tried to build [```munit```](https://github.com/nemequ/munit/blob/master/meson.build) on my PC today:
```
File "E:\vcpkg\downloads\tools\meson\meson-0.50.0\mesonbuild\mesonmain.py", line 122, in run
File "E:\vcpkg\downloads\tools\meson\meson-0.50.0\mesonbuild\msetup.py", line 245, in run
app.generate()
File "E:\vcpkg\downloads\tools\meson\meson-0.50.0\mesonbuild\msetup.py", line 163, in generate
File "E:\vcpkg\downloads\tools\meson\meson-0.50.0\mesonbuild\msetup.py", line 193, in _generate
intr.run()
File "E:\vcpkg\downloads\tools\meson\meson-0.50.0\mesonbuild\interpreter.py", line 3812, in run
super().run()
File …
```
=> Force pkgconfig to UTF-8

run_unittests.py
pkg-config(1) on OpenBSD is not the one from freedesktop.org and hence has
subtle differences (which don't impact real usage). The meson test fails
because white space between operators are stripped by our pkg-config:
$ grep Require /usr/local/lib/pkgconfig/xmlsec1.pc
Requires: libxml-2.0 >= 2.8.0 libxslt >= 1.0.20
$ pkg-config --print-requires xmlsec1
libxml-2.0>=2.8.0
libxslt>=1.0.20
=> unittests: adapt pkg-config test for OpenBSD

mesonbuild/compilers/cpp.py
For backwards-compatibility purposes, this allows `cpp_eh='a'|'s'|'sc'` on gcc-style compilers, resulting in normal exceptions. @jon-turney pointed out on #5348 breaks older users who use old-style `cpp_eh`, so instead of making it an error, this PR makes it a warning.
This PR is not necessary, but if it might be helpful, please merge :)
=> Allow MSVC-style `cpp_eh` for backwards-compatibility purposes

mesonbuild/modules/gnome.py
I have been having trouble building graphene due to a bug in this file. This should fix it enough to get graphene building, but I think there are other places where an OrderedSet is used in dangerous ways.
Reproduce by trying to build graphene 1.8.2 (including docs) while CFLAGS contains `--param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=3072`
edit: Graphene is this project https://ebassi.github.io/graphene/
=> Do not filter out repeated cflags (gnome.gtkdoc)

mesonbuild/coredata.py, mesonbuild/dependencies/base.py, mesonbuild/envconfig.py, mesonbuild/environment.py, mesonbuild/interpreter.py, mesonbuild/mesonlib.py, run_tests.py, run_unittests.py
Meson itself *almost* only cares about the build and host platforms. The
exception is it takes a `target_machine` in the cross file and exposes
it to the user; but it doesn't do anything else with it. It's therefore
overkill to put target in `PerMachine` and `MachineChoice`. Instead, we
make a `PerThreeMachine` only for the machine infos.
Additionally fix a few other things that were bugging me in the process:
- Get rid of `MachineInfos` class. Since `envconfig.py` was created, it
has no methods that couldn't just got on `PerMachine`
- Make `default_missing` and `miss_defaulting` work functionally. That
means we can just locally bind rather than bind as class vars the
"unfrozen" configuration. This helps prevent bugs where one forgets
to freeze a configuration.
CC @dcbaker @jpakkane
=> Make `PerMachine` and `MachineChoice` have just `build` and `host`

mesonbuild/compilers/clike.py, run_unittests.py
It was using ':' as a path separator while GCC uses ';' resulting in bogus
paths being returned. Instead assume that the compiler uses the platform native
separator.
The previous splitting code still worked sometimes because splitting
"C:/foo;C:/bar" resulted in the last part "/bar" being valid if "\<DriveOfCWD\>:/bar"
existed.
The fix also exposes a clang Windows bug where it uses the wrong separator:
https://reviews.llvm.org/D61121 . Use a regex to fix those first.
This resulted in linker errors when statically linking against a library which
had an external dependency linking against system libs.
Fixes #5386
=> Fix path splitting in get_compiler_dirs() with GCC/clang on Windows. Fixes #5386

mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/environment.py, mesonbuild/interpreter.py, mesonbuild/modules/cmake.py, mesonbuild/modules/windows.py
A step on the way to sorting out #2392.
Closes #4771.
=> Remove compilers from build object

mesonbuild/coredata.py, mesonbuild/dependencies/base.py, mesonbuild/environment.py, mesonbuild/interpreter.py, mesonbuild/mconf.py, mesonbuild/mintro.py, mesonbuild/modules/rpm.py, mesonbuild/munstable_coredata.py
When a user changes the pkg_config path they expect meson 
to actually search for the deps again with the new path and not
just return deps from the cache.
=> coredata: add pkg_config_path to depedency cache key

mesonbuild/optinterpreter.py
Added to 0.50.2 just in case we get one.
=> Reserve build_ prefix in option names.

mesonbuild/modules/gnome.py
We are emitting a static string, so use that shortcut function to
intern it, which will save one allocation.
=> gnome: use g_intern_static_string() for enum/flags type names

docs/markdown/Dependencies.md, docs/markdown/Reference-manual.md, docs/markdown/snippets/dependency_get_variable_method.md, mesonbuild/dependencies/base.py, mesonbuild/interpreter.py, test cases/common/219 dependency get_variable method/meson.build
This provides a new method to the Dependency class that simplifies dependencies that can be found multiple ways, and provides a way to get arbitrary variables from cmake based dependencies. Each dependency type as a keyword argument that can be passed for it's type.
As a follow up we may want to deprecated the `get_*type*_variable` methods in favor of this generic one.
Fixes #4957
=> Dependency.get_variable method

docs/markdown/Installing.md, docs/markdown/Porting-from-autotools.md, docs/markdown/Reference-manual.md, docs/markdown/Release-notes-for-0.49.0.md, docs/markdown/Syntax.md, docs/markdown/Vala.md
Update docs to reflect 0.49 `/` path joiner instead of join_path(), which is cleaner and more natural syntax akin to `pathlib.Path`.
=> DOCS: use / instead of join_paths()

docs/markdown/Users.md
Mesa's primary home is now in the Freedesktop GitLab instance. The cgit repo is just a mirror.
=> docs/Users: update Mesa link [skip-ci]

mesonbuild/dependencies/dev.py
It turns out that llvm-config on windows can return such wonderful
output as `-LIBDIR:c:\\... c:\\abslute\\path\\to\\lib.lib`, which was
all fine and dandy when we were blindly passing it through, GCC/MinGW
ignored it and MSVC understood it meant `/LIBDIR:`; however, after we
added some code to validate linker arguments, and we have some code
before the validation that tries to remove posix style -L arguments,
resulting in IBDIR:..., which doesn't validate.
This patch fixes up the output of llvm-config so that -LIBDIR: is
replaced by the the link libdir argument of the compiler, via the
compiler/linker method for getting that.
Fixes #5419
=> dependencies/llvm: Fixup bad output from llvm-config on windows

docs/markdown/Feature-autodetection.md, man/meson.1, run_project_tests.py
ccache’s web site is now located at https://ccache.dev.
Bonus: Use the preferred capitalization “Ccache” instead of “CCache”.
=> Update to new ccache URL and preferred capitalization

mesonbuild/mintro.py
The host environment could change between the time "meson setup" produces intro-tests.json, and the time "meson test" is run. Including it only adds clutter to the introspection data.
=> do not include host environment in test/benchmark introspection data

mesonbuild/mesonlib.py
Fix for #5285.  Handles x86 / x86_64 case
=> BUGFIX default platform for get_library_dirs #5285

docs/markdown/Wrap-best-practices-and-tips.md
Error introduced in commit 8e403e08ac2907214c044c804ee5eef6a45e0ff9
=> doc: fix typo [skip ci]

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/environment.py
Before this commit meson took on my laptop ~30-40 sec. now we are down to ~20-25 sec..
Those numbers are from building EFL with meson. We are working a lot with generated sources, which are added as source to dependencies, hence we have a big number of include directories, and custom targets.
=> performance optimize meson

mesonbuild/rewriter.py, test cases/rewrite/3 kwargs/delete.json
Currently, default_options uses "" for the kwargs id, however, this is incorrect and it must be "/". Additionally, this error won't be ignored in the future with "--skip" (this is why the tests were passing, and this wasn't detected earlier).
=> rewriter: Fix that default_options would not set the correct id

mesonbuild/dependencies/base.py, run_unittests.py, test cases/unit/61 cmake parser/meson.build, test cases/unit/61 cmake parser/prefix/lib/cmake/mesontest/mesontest-config.cmake
There is a rather nasty/annoying bug in the cmake parser (described in the bug linked) that breaks using cmake on windows in basically every case. I've added a big mean test case and fixed at least enough to make this work for me (mesa + llvm on windows), however, there may be more cases that need fixing.
Fixes #5435
=> Cmake lexer spaces in args

mesonbuild/compilers/c.py
ICL didn't get updated when the name field was removed for the Option types, and is broken without this fix.
=> compilers/c: Fix removal of name from Combo options for ICL

mesonbuild/scripts/yelphelper.py
When the media file for a specific language doesn't exist we try to symlink
it to the C one. If symlinking fails we need to fall back to copying the C
one like in the non-symlink case.
The fallback code path didn't set the source so this always failed.
Also check if the C fallback exists before trying to symlink/copy, otherwise
we crash if C isn't the first lang we try.
=> gnome.yelp(): Fix media symlink fallback path

mesonbuild/backend/vs2010backend.py
The RuntimeLibrary (MT, MTd, MD, MDd) property was not set correctly in the project generated by the vs2010 backend. According to the [example file](https://docs.microsoft.com/en-us/cpp/build/reference/project-files?view=vs-2019) provided by Microsoft it should be in ItemDefinitionGroup/ClCompile and the examples are consistent from vs2015 to vs2019, I don't know about vs2010.
=> Moved RuntimeLibrary property to ItemDefinitionGroup/ClCompile

docs/markdown/Reference-manual.md
Not a series problem, but annoys me that that it's in the builtin
section when it's a returned object.
=> docs: compiler objects are returned [skip ci]

mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py
Fixes the broken armclang cross tests,
- Reverts back the change done to Armclang compiler class as part of PR 4010. Armclang supports only cross-compilation.
- Removes the name field from Combo Option, 'cpp_eh', for Armclang Cpp compiler. Related to PR 5388.
=> Armclang cross test failure fixes

docs/markdown/Python-module.md, docs/markdown/snippets/python_find_installation_modules.md, mesonbuild/modules/python.py, test cases/python/5 modules kwarg/meson.build
This adds a new method for querying the availability of third party
python modules available. This is designed to provide information in
the configuraiton log while providing the familiar dependency
interface within meson itself.
Fixes #2377
=> modules/python: Add a find_module method

mesonbuild/compilers/compilers.py, mesonbuild/environment.py
Fixes #5351
I make no promises this is the best way to make Meson work on Solaris (or, as in my case, OpenIndiana). However, this does work for me. You could argue the addition to *mesonbuild/environment.py* should also include a `is_sunos()` in the condition but I think that is being overly prescriptive.
=> Solaris fixes

mesonbuild/dependencies/misc.py
this is why static languages rock
=> dependencies/shaderc: fix exception caused by typo

mesonbuild/compilers/clike.py
Currently meson does not write the outcome of this test to the log
file which makes debugging wrong outcomes of this incredibly tedious.
=> compilers: Add logging for symbol prefix test

docs/markdown/Reference-manual.md
=> Reference-manual.md:add missing equal sign in "both_libraries" section

mesonbuild/environment.py
i86pc may be either 32-bit or 64-bit, so use existing compiler checks
to determine if it should return 'x86' or 'x86_64'.
Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
=> Canonicalize 'i86pc' return from platform.machine() for Solaris

docs/markdown/Quick-guide.md
per IRC discussion, the wheel package isn't required but reduces
harmless warnings.
=> Quick_guide.md:add deps to apt command, python-setuptools and wheel

mesonbuild/cmake/__init__.py, mesonbuild/cmake/client.py, mesonbuild/cmake/executor.py, mesonbuild/cmake/interpreter.py, mesonbuild/cmake/traceparser.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/dev.py, test cases/cmake/1 basic/subprojects/cmMod/CMakeLists.txt, test cases/cmake/2 advanced/subprojects/cmMod/CMakeLists.txt, test cases/cmake/3 advanced no dep/subprojects/cmMod/CMakeLists.txt
This PR basically moves most of the CMake detection/parsing code from the dependency module into the CMake module. This change reduces the complexity of the `CMakeDependency` class and makes reusing the parser in the future much easier.
=> CMake code refactor

test cases/common/196 install_mode/meson.build
The corresponding *unit tests* are already skipped because they've been placed in `LinuxlikeTests`, but the project test is currently failing for me on Windows due to a missing `cp` executable.
=> Skip `196 install_mode` project test on Windows

mesonbuild/backend/ninjabackend.py, test cases/fortran/12 submodule/a3.f90, test cases/fortran/15 include/inc1.f90, test cases/fortran/2 modules/comment_mod.f90, test cases/fortran/2 modules/meson.build, test cases/fortran/2 modules/mymod.f90, test cases/fortran/2 modules/prog.f90, test cases/fortran/2 modules/stuff.f90, test cases/fortran/8 module names/test.f90
in response to #5513, tests for Fortran module name with inline comment.
The Fortran regex patterns for module, submodule and include were not correct--they could not tolerate inline comments.
1. apply fix to regex in ninjabackend.py
2. add inline comment tests for Fortran use, module, submodule, include
3. fix syntax error (unrelated, just saw it)
4. fix type hinting in the function (unrelated, just saw it)
Fixes #5513
=> BUGFIX: Fortran: use, module, submodule with inline comment

mesonbuild/environment.py
This uses the fix as suggested in issue 5491, which it also fixes.
Fixes #5491
=> environment: Fix detection of Microsoft cl.exe with non English locales

mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, run_unittests.py, test cases/osx/7 bitcode/libbar.mm, test cases/osx/7 bitcode/libfile.c, test cases/osx/7 bitcode/libfoo.m, test cases/osx/7 bitcode/meson.build, test cases/osx/7 bitcode/vis.h
We were setting the base options for the Objective-C compiler manually, due to which options such as `b_bitcode` and `b_ndebug` were not getting set at all.
The base options here are the same as for C code with the Clang compiler, so just use the same inherited list.
Also expand the bitcode test to ObjC and ObjC++ so this doesn't happen again.
=> compilers: Fix bitcode and other options for objc code

mesonbuild/backend/ninjabackend.py, test cases/fortran/12 submodule/child.f90, test cases/fortran/12 submodule/parent.f90, test cases/fortran/2 modules/mymod.f90
Due to the number of issues had with Fortran regex, I have created a repo just to test Fortran regex as used in Meson Ninja backend: https://github.com/scivision/fortran-parse-python
Based on that, these new regex handle more cases of interest for Fortran Meson users.
=> BUGFIX: Fortran module regex handle more edge cases

run_project_tests.py
Using too many processes actually slows down the test. In this case, on WIndows the test wallclock time is faster by factor nearly 2, by not multiplying CPU count by 2 for max_workers in ProcessPoolExecutor.
The speedup is apparent with Ninja 1.8.2 and 1.9.0 at least
=> windows run_project_test speedup by 2

mesonbuild/coredata.py, mesonbuild/environment.py, mesonbuild/msetup.py, run_unittests.py
In some cases a cross/native file may be a pipe, such as when using bash
process replacement `meson --native-file
<([binaries]llvm-config='/opt/bin/llvm-config')`, for example. In this
case we copy the contents of the pipe into a file in the meson-private
directory so we can create a proper ninja dependency, and be able to
reload the file on --wipe/--reconfigure. This requires some extra
negotiation to preserve these native/cross files.
Fixes #5505
=> coredata: Correctly handle receiving a pipe for native/cross files

docs/markdown/snippets/select_run_project_tests.md, run_project_tests.py
this PR adds an optional `--only test(s)` option to run_project_tests.py. 
Individual tests or a list of tests from run_project_tests.py can be selected like:
```
python run_project_tests.py --only fortran
python run_project_tests.py --only fortran python3
```
This assists Meson development by only running the tests for the portion of Meson being worked on during local development, particularly with slow compilers like Intel.
Intel compilers take over 3 *hours* to run all Meson tests, while with this `run_project_tests.py --only fortran` the Fortran tests take just a couple *minutes*
---
Added type hinting relevant to this change
---
improved the `gather_tests()` [algorithm](https://github.com/mesonbuild/meson/compare/master...scivision:only_test#diff-d9f7c80135592b1a61e38f3133a89499R438) …
=> add optional `--only test(s)` option to run_project_tests.py.

run_unittests.py
VS and virus scanners complain when generating executables
in temporary directories.
=> Keep all build dirs inside the source tree.

mesonbuild/backend/backends.py
calling this function too ~60 sec. before, now 0.000435 sec.
=> meson: add cache for getting options

run_unittests.py
Since it hangs and causes azure to time out.
=> run_unitests: Skip the native_file_is_pipe test on cygwin

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/fortran.py, mesonbuild/dependencies/misc.py, mesonbuild/environment.py, mesonbuild/interpreter.py, run_project_tests.py, test cases/fortran/10 find library/meson.build, test cases/fortran/13 coarray/meson.build, test cases/fortran/6 dynamic/meson.build
After #5331 , Intel Fortran compiler `ifort` on Windows works and passes the Fortran tests from run_project_tests.py.
Implementing this was mainly a matter of 
* adding one [forgotten argument](https://github.com/mesonbuild/meson/compare/master...scivision:icl_ifort?expand=1#diff-64440ffbb1d8b859bdc6286f6a9c38c0R274)
* making sure the ifort compiler made .obj files in the test [build directory](https://github.com/mesonbuild/meson/compare/master...scivision:icl_ifort?expand=1#diff-64440ffbb1d8b859bdc6286f6a9c38c0R72)
* straighten out [logic for detecting Ninja for ifort on Windows](https://github.com/mesonbuild/meson/compare/master...scivision:icl_ifort?expand=1#diff-d9f7c80135592b1a61e38f3133a89499R565)
* type hinting
* fix typo for PGI, just happened to see that.
=> Add ifort on Windows

test cases/fortran/16 openmp/main.f90, test cases/fortran/16 openmp/meson.build
Unit tests specifically for Fortran OpenMP, adding / complementary to `common/190 openmp` but allowing use on Windows and with non-GNU compilers.
Enabling future more complete testing of non-GNU Fortran compilers with OpenMP, such as Flang that are targeting OpenMP to help ensure we have the correct compiler flags.
We may not want to do this in `common` because it encumbers testing with array of C / C++ compliers.
The distinction of these integration tests is:
* common: test OpenMP with as wide array as feasible of C / C++ / Fortran compilers, not testing Fortran on Windows because of usual inter-compiler difficulties on Windows
* fortran: test OpenMP with as wide array as feasible of Fortran compilers, including Windows, even more compilers than tested in common.
---
The underlying …
=> CI: Fortran-specific OpenMP tests

docs/markdown/Cross-compilation.md, docs/markdown/snippets/pkg_config_enhancements.md, mesonbuild/dependencies/base.py
In some cases it may be necessary to set PKG_CONFIG_SYSROOT_DIR, like
when you've mounted a host architecture system in an arbitrary path.
Meson will now check the cross files for a [properties]:sys_root
variable and set the PKG_CONFIG_SYSROOT_DIR environment variable based
on that variable.
=> dependencies/base: Set PKG_CONFIG_SYSROOT_DIR from cross file

docs/theme/extra/templates/navbar_links.html
The link to the `SourceSet` module is missing in the navigation bar.
=> docs: Fix link to SourceSet module in the navbar

mesonbuild/build.py, mesonbuild/compilers/clike.py, mesonbuild/compilers/compilers.py
Note: we should consider also disabling linking (and running) in this
case even if `exe_wrapper` is set as it's entirely possible that
additional source code from the project is needed for a link to succeed
even if `exe_wrapper` is set.
This comes down to `self._get_basic_compiler_args()` not including `self.get_compile_only_args()` and `sanity_test_impl()` not using `self.compile()` (which pulls in `self.get_compile_only_args()` based on mode).
Fixes #5496
=> sanitycheckc: avoid linking sanitycheckc when cross compiling

run_unittests.py
`VCToolsVersion` is not always set, and MS docs recommend getting the info from a file (https://devblogs.microsoft.com/cppblog/finding-the-visual-c-compiler-tools-in-visual-studio-2017/)
=> Fix faling test_msvc_toolset_version test

docs/markdown/Release-notes-for-0.48.0.md, docs/markdown/snippets/add_arguments_cross.md, mesonbuild/interpreter.py, test cases/common/21 global arg/meson.build, test cases/common/21 global arg/prog.c
This further simplifies behavior to match the "build vs host" decision
we did with `c_args` vs `build_c_args`. The rules are now simply:
- `native: true` affects `native: true` targets
- `native: false` affects `native: false` targets
- No native flag is the same as `native: false`
I like this because you don't even have to know what "build" and "host" mean to understand how it works, and it doesn't depend on whether the overall build is cross or not.
CC @dcbaker 
Fixes #4933
=> `add_{global,project}_{,link_}arguments`: simply native flag behavior

run_unittests.py
Skip finding a .py script w/o extension on Windows if `.PY` isn't in `PATHEXT`; closes #4355
=> Fix failing test_find_program test (Windows-only)

mesonbuild/backend/backends.py
There are two problems with this:
- It has false positives when the code that trips it is conditional and
no run on cross.
- It confuses users who never wrote any `native` flags and don't care
about cross.
Fixes #5509
=> Remove build host mixing warning on native

mesonbuild/mintro.py, run_unittests.py
Adds the directory and its install destination to the introspection.
=> mintro: Add installed subdirs introspection (fixes #5556)

mesonbuild/compilers/clike.py
There is an error when compiling with -Werror=return-type. Non void
functions must return valid values.
=> Return zero in cross_sizeof

mesonbuild/envconfig.py
A compiler or other tool with an empty string as name does not make
sense as it anyway can not be used and causes a failure later in
parse_entry.
Fix #5451
=> env: Do not return empty tool env vars

mesonbuild/compilers/clike.py, mesonbuild/compilers/compilers.py, mesonbuild/environment.py
On my machine (where defender ATP is enabled and the meson build directory is excluded, but %TMP% is not) this PR improves glib configure performance by >5x (from 171.13 seconds to 29.71 seconds).
see #5418 for more details on the performance issues.
=> Improve performance with windows defender ATP

mesonbuild/compilers/clike.py, run_unittests.py
This is #5483 with the unit tests fixed.
Fixing this uncovered a problem. If you do `-Dc_args=-Dfoo="bar"` the quote signs go away. Thus you can't pass string definitions through the command line. Dunno what should be done about it.
=> Fix compiler flags not used for some tests

mesonbuild/environment.py
PGI compilers were broken by typo in 32e827dcdc451e1c5
=> BUGFIX: typo from 32e827dcdc451e1c5 broke PGI compilers

mesonbuild/envconfig.py
Handles additional cases from #5601 on Linux, Windows, etc.  For example, assuming environment variable CC is of interest:
```sh
CC=" "
CC=""
CC=''
CC="                          "
```
and the like are handled.
fixes #5451
=> check that compiler name is not blank or empty

mesonbuild/coredata.py
allow the installation prefix to be specified with `~`, which is more OS-agnostic than users fiddling with $HOME, %userprofile% for `meson setup --prefix=~/.local` to work on Windows, Linux, etc.
CMake *et al* allow ~ in prefix.
=> allow meson setup --prefix=~

mesonbuild/compilers/clike.py, mesonbuild/compilers/compilers.py
avoid a harmless but annoying error messages on non-gnu-compilers
=> move Gnu-specific feature '--print-search-dirs' to GnuLikeCompiler

mesonbuild/compilers/cpp.py
Meson currently throws a KeyError when specifying c++latest as the std version with MSVC.
=> Fix (v)c++latest with MSVC

run_unittests.py
We can't rely on `py` always being available in `PATH`, use `sys.executable` which is the real path to Python 3.
=> unit tests: Fix CI failures in NativeFileTests

.travis.yml, ci/azure-steps.yml, ciimage/Dockerfile, run_project_tests.py, run_tests.py, run_unittests.py
Pytest is still not required, it is only used if it is available.
OSX tests have been left to be run with `unittest`. It could be any other one as well, but Windows is the slow and I already uploaded an image with pytest to dockerhub.
=> Run tests in paralled with pytest when installed

mesonbuild/ast/printer.py, mesonbuild/ast/visitor.py, mesonbuild/cmake/data/run_ctgt.py, mesonbuild/cmake/interpreter.py, mesonbuild/cmake/traceparser.py, run_meson_command_tests.py, setup.py, test cases/cmake/8 custom command/main.cpp, test cases/cmake/8 custom command/meson.build, test cases/cmake/8 custom command/subprojects/cmMod/CMakeLists.txt, test cases/cmake/8 custom command/subprojects/cmMod/cmMod.cpp, test cases/cmake/8 custom command/subprojects/cmMod/cmMod.hpp, test cases/cmake/8 custom command/subprojects/cmMod/cp.cpp, test cases/cmake/8 custom command/subprojects/cmMod/cpyBase.cpp.am, test cases/cmake/8 custom command/subprojects/cmMod/cpyBase.hpp.am, test cases/cmake/8 custom command/subprojects/cmMod/main.cpp
With this PR, most CMake subprojects that use `add_custom_command` are supported. Due to the limitations of the CMake introspection API, the CMake trace parser is used for extracting all the relevant information. To execute the actual commands a wrapper python script is used to replicate most of the `add_custom_command` functionality with `custom_target`.
=> CMake subprojects add_custom_command support

ciimage/Dockerfile, mesonbuild/dependencies/boost.py, test cases/frameworks/1 boost/meson.build, test cases/frameworks/1 boost/python_module.cpp, test cases/frameworks/1 boost/test_python_module.py
This is an attempt to close #4288
As mentioned in #4288 Boost.Python libraries are not detected anymore as the version number of the python installation to which the boost libraries where compiled is included in the naming. Thus, we can not look for 'boost_python' or 'boost_python3' anymore, but need to include the major and minor python version number as a suffix. 
To make the detection of Boost Python libraries flexible, we now firstly look for available Boost modules and check afterwards whether or not the requested modules are (in-)valid. This enables us to check against detected and known modules.
However, as the version number of python is now included, one could think about introducing a version check here as well. 
I tested the patch on Fedora 30 with a custom installation of …
=> Adapting Boost Python library detection to Boost >= 1.67

mesonbuild/compilers/clike.py
On MSCV, linker arguments must follow after compiler arguments, separated by /link. The routine VisualStudioLikeCompiler.linker_to_compiler_args did exist to handle this, but it was not used consistently. This patch addresses all missing cases that I encountered, specifically then use of LDFLAGS for find_library and for sanity_check (addresses #3629)
=> Fix MSVC /link argument ordering

mesonbuild/cmake/executor.py, test cases/linuxlike/13 cmake dependency/cmake/FindSomethingLikeZLIB.cmake
Finding some CMake dependencies currently fails because the C and C++ compilers aren't set correctly (just a placeholder file is used). This works in most cases but fails as soon as the compiler is required in the dependency finding process (such as the CMake try_compile function).
=> cmake: Fix dependencies with try_compile (closes #5605)

mesonbuild/compilers/d.py
This is the #5369 fix I've been using.
=> Ignore -D* and -fstack-protector* args for D compilers

.flake8, docs/markdown/Contributing.md, mesonbuild/mlog.py, mypy.ini, run_project_tests.py, setup.cfg, setup.py
Helping modernize Meson packaging
* Begin modernizing Meson install metadata per PEP 390 [using `setup.cfg` with setup.py](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files) (available since Dec 2016).
* Moved flake8 content to dedicated [standard .flake8 file](https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations)
* added [mypy.ini](https://mypy.readthedocs.io/en/latest/config_file.html) for some good defaults as Meson continues to introduce type hint checks
setup.py can be reduced to 4 lines with future PRs--I thought I'd introduce gradually with "safe" metadata fields only in case of unexpected issues. 
I use setup.cfg on hundreds of repos with setup.py a one-liner: `import setuptools; setuptools.setup()` …
=> ENH: metadata PEP390 setup.cfg

mesonbuild/compilers/c.py, mesonbuild/mesonlib.py, run_unittests.py
Fixes #5539
tested on Linux and Windows, Clang 6.0.0 and 8.0.0
Also with Intel C compiler.
Cleaned up c_stds test in run_unittests.py so that's it's readable, correct and deduped.
=> add clang c_std=c18 alias

run_unittests.py
Seems to cause the umask tests to fail:
https://github.com/mesonbuild/meson/pull/5546#issuecomment-509666523
WIP: let's see if this actually works.
=> unit tests: Don't keep builddirs inside source tree on Cygwin

mesonbuild/optinterpreter.py
`build_something` seems to be a somewhat common option name in projects.
=> No need to reserve build_ because we use build. instead.

mesonbuild/compilers/c.py, mesonbuild/compilers/mixins/clike.py
Error example:
```
Code:
#include <locale.h>
int main () {
/* If it's not defined as a macro, try to use as a symbol */
#ifndef LC_MESSAGES
LC_MESSAGES;
#endif
}
Compiler stdout:
Compiler stderr:
In file included from /usr/include/locale.h:25,
from /tmp/tmpep_i4iwg/testfile.c:2:
/usr/include/features.h:382:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
|    ^~~~~~~
/tmp/tmpep_i4iwg/testfile.c: In function 'main':
/tmp/tmpep_i4iwg/testfile.c:8:9: error: control reaches end of non-void function [-Werror=return-type]
8 |         }
|         ^
cc1: some warnings being treated as errors
```
=> Fix missing return statements that are seen with -Werror=return-type.

docs/markdown/Gnome-module.md, docs/markdown/snippets/gtkdoc.md, mesonbuild/modules/gnome.py, test cases/frameworks/10 gtk-doc/doc/foobar1/foobar-docs.sgml, test cases/frameworks/10 gtk-doc/doc/foobar1/meson.build, test cases/frameworks/10 gtk-doc/doc/foobar2/foobar-docs.sgml, test cases/frameworks/10 gtk-doc/doc/foobar2/meson.build, test cases/frameworks/10 gtk-doc/doc/foobar3/foobar-docs.sgml, test cases/frameworks/10 gtk-doc/doc/foobar3/meson.build, test cases/frameworks/10 gtk-doc/doc/foobar4/foobar-docs.sgml, test cases/frameworks/10 gtk-doc/doc/foobar4/meson.build, test cases/frameworks/10 gtk-doc/doc/meson.build
This runs gtkdoc-check in meson tests.
=> gtkdoc: Add 'check' kwarg

docs/markdown/Reference-manual.md, docs/markdown/snippets/shared_module_defs.md, mesonbuild/build.py, test cases/windows/9 vs module defs generated/subdir/meson.build
Like shared libraries, modules may have vs_module_defs.
=> Accept vs_module_defs for modules

docs/markdown/IDE-integration.md, mesonbuild/mintro.py, run_unittests.py
This reverts the changes to the `section` key for the
buildoptions and moves the machine choice into it's
own `machine` key.
With this commit the __undocumented__ breaking change
to the introspection format (introduced in 0.51.0) is
reverted and a new key is added instead.
cc: @textshell
=> mintro: Fix section key in buildoptions

mesonbuild/dependencies/base.py, test cases/linuxlike/13 cmake dependency/cmake/FindImportedTarget.cmake, test cases/linuxlike/13 cmake dependency/meson.build, test cases/linuxlike/13 cmake dependency/testFlagSet.c
Fix that empty strings were processed in the dependency, due to generator expressions, etc.
=> cmake: Fix empty -D due to empty strings (closes #5522)

mesonbuild/dependencies/base.py, test cases/cmake/10 cmake_module_path/cmake/FindSomethingLikePython.cmake, test cases/cmake/10 cmake_module_path/meson.build
* the cmake_module_path test was only for Linux, now it is cross-platform, looking for Python3, which is inherently guaranteed to be available
* cleaned up CMakeLists.txt generation by using pathlib.Path instead of string, while staying Python 3.5 compatible
=> Quality/test: OS-agnostic cmake_module_path unit test

azure-pipelines.yml
CMake 3.13.1 isn't the latest point release for CMake 3.13, but 3.14.5 is the latest point release currently available in Cygwin for CMake. 
Since CMake server used to communicate with external programs like Meson changed in CMake 3.14 to file-based API, maybe good to keep beyond that in case we need to use it.
=> CI: azure cygwin cmake 3.14.5

mesonbuild/compilers/vala.py
Currently '--debug' is always emitted for Vala regardless of the build type.
From what I can see this has been introduced by https://github.com/mesonbuild/meson/pull/3489 and it does not look like the intended behavior (I could be wrong of course).
=> ValaCompiler: only emit '--debug' in debug build.

run_unittests.py
It's better to quickly skip when the network is unavailable or slow.
=> unit tests: Use a timeout for tests that use the network

run_unittests.py
Also, always run pytest using the module format to ensure that we're
always using the Python interpreter selected by the user.
Fixes issue reported in https://github.com/mesonbuild/meson/pull/5621#issuecomment-513034198
=> unit tests: Check whether pytest-xdist is available

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/compilers.py, mesonbuild/mesonlib.py, mesonbuild/wrap/wrap.py, setup.py
This is just something fun and small I wrote because people were complaining that meson took too long with GStreamer's thousands of targets on Windows.
commit e075ddca4af18ec90ddf5d6696679dd207abe49e:
```
ninja backend: Add optional progress bar in generate()
With, f.ex., gst-build, this step can take 8-20 seconds depending on
your CPU and disk speed. I was looking at speeding that up, but the
ways I could see would've involved heavy refactoring of the backend
generation, and would not have solved the core problem of no feedback.
Now we have pretty (optional) progress bars!
```
commit b1600771d90cf267503402d0fd57faad921a0532:
```
compilers: Clarify a docstring in CompilerArgs
```
=> Add optional progress bar when generating build.ninja

mesonbuild/dependencies/base.py, run_project_tests.py, run_tests.py, test cases/linuxlike/13 cmake dependency/cmake_pref_env/lib/cmake/cmMesonTestDep/cmMesonTestDepConfig.cmake, test cases/linuxlike/13 cmake dependency/meson.build, test cases/linuxlike/13 cmake dependency/setup_env.json
With this PR, the meson dependency backend reads the `CMAKE_PREFIX_PATH`, used internally by CMake and adds it to the CMake command line and the internal preliminary CMake search path.
This PR also includes a general update to `run_project_tests.py` to additional environment variables from an `setup_env.json` file.
=> cmake: Read CMAKE_PREFIX_PATH environment variable (closes #5666)

ci/azure-steps.yml
pip warns about being out of date and powershell interprets that as an error because reasons.
Found in https://github.com/mesonbuild/meson/pull/5687#issuecomment-514268525
=> ci: Fix failures in vs2019 jobs on Azure

.travis.yml, test cases/common/122 shared module/module.c, test cases/common/122 shared module/prog.c
commit 676cc0934b75b9f428f86399d70a178aa31500d4:
```
.travis.yml: Fix cross-mingw test failures
Run docker with seccomp:unconfined, since otherwise we're blocked from
calling CreateToolhelp32Snapshot() inside the cross-mingw tests,
specifically `common/122 shared module`.
```
commit 539bdee7ec9bbb3e84b17c7f5fc431a8f8f27b7e:
```
tests/122 shared module: More verbose logging
So we know why the syscalls failed.
```
=> Try to fix cross mingw travis failure

docs/markdown/IDE-integration.md
The new meson plugin will be included in [KDevelop 5.4](https://www.kdevelop.org/news/kdevelop-5380-released), so adding it to the IDE-Integration docs.
=> Added KDevelop to the docs [skip ci]

azure-pipelines.yml
commit 97103e4fb0735e7ad7e8e1a7ddef4d1fba6f947a:
```
ci/cygwin: Don't need a special step to install cmake
```
commit 956489d3399e3c7717360c0880eab29f8561e8c3:
```
ci/cygwin: Install pytest-xdist for unit tests
The job is taking too long and timing out, use pytest-xdist to speed
up unit tests. Speeds it up on my system from 20 min to 8 min.
Still much slower than native windows: vs2017-x64 takes 3.5 min with
pytest-xdist.
```
=> Try to fix cygwin timeouts

docs/markdown/Reference-manual.md, docs/markdown/Syntax.md
I didn't see a documented method to convert integers to strings. Now this is documented.
=> DOC: note that number can be converted to strings

mesonbuild/mtest.py
When configuration fails, the error contained a vestigial "$" like
> ERROR: Directory $'/home/vsts/work/1/b' does not seem to be a Meson build directory.
This removes that $ and generally cleans up via use of pathlib.Path and subprocess.run
=> remove vestigial $ from test error msg

mesonbuild/compilers/fortran.py, mesonbuild/dependencies/misc.py, test cases/fortran/13 coarray/meson.build
This adds project_tests for Flang compiler that should have been added when it was originally added to Meson.
All Fortran project_tests now pass with Flang.
=> Flang: Fortran project_tests fixes

mesonbuild/compilers/cpp.py, mesonbuild/compilers/mixins/pgi.py, test cases/common/13 pch/c/meson.build, test cases/common/13 pch/cpp/prog.cc, test cases/common/13 pch/generated/meson.build, test cases/common/13 pch/meson.build, test cases/common/13 pch/mixed/meson.build, test cases/common/13 pch/withIncludeDirectories/meson.build
Precompiled headers (PCH) for PGI has not been working since I added PGI compilers.
I simply omitted this feature previously. 
his PR adds PCH for PGI C++ only (as that's all PGI works with for PCH).
PGI compilers support precompiled headers for C++ only.
The common/13 pch test passes if run manually with no spaces in the build path AND #include "prog.hh" is added to prog.cc.
This is distinctive from how other compilers work, and since PGI is not nearly as popular a compiler, I opted to simply skip the PCH test rather than rework the whole test system to accommodate PGI's less-robust PCH behavior.
However, since Meson run_project_tests.py makes temporary build directories
with spaces in each test, PGI --pch_dir can't handle this and fails.
So we **skip common/13 pch test** for PGI despite …
=> PGI:  cpp_pch precompiled headers functionality

mesonbuild/compilers/mixins/intel.py, run_project_tests.py, run_tests.py, test cases/fortran/2 modules/meson.build
From what I can see with `git bisect`, with intel-cl/ifort the Fortran project tests didn't work till now (skipped or failed at various points in history). 
To make them work needed encouraging the run_tests to use ninja instead of msvc for intel-cl in general.
also, in general fixed --failfast for run_project_tests so that it actually quit on the first failing test. Before it would say aborting but just keep going.
cleaned up the project_tests install file checks, using pathlib.Path instead of os.path.
=> tests: Intel-cl fixes for Fortran

docs/markdown/Unit-tests.md, mesonbuild/mtest.py
Document the `meson test` behavior for **multiple testnames** or **multiple suites**--this was not clear before.
PEP8 the test logic.
=> DOC: meson test: multiple --suite 

mesonbuild/compilers/mixins/clike.py, mesonbuild/compilers/mixins/pgi.py, mesonbuild/dependencies/misc.py, test cases/common/190 openmp/meson.build, test cases/common/223 source set realistic example/meson.build, test cases/fortran/13 coarray/meson.build, test cases/fortran/14 fortran links c/meson.build, test cases/fortran/6 dynamic/meson.build
* Linux: all tests pass except the skipped "13 coarray"
* Windows: all tests pass except skipped: 6 (dynamic lib on non-Gfortran Windows takes peculiar non-standard Fortran syntax), 9 (can't mix compilers on Windows), 10 (zlib not on windows), 13 coarray
OpenMP is included right in the PGI compiler.
```sh
FC=pgfortran CC=pgcc CXX=pgc++ python run_project_tests.py --only fortran
```
=> PGI: correct Fortran so that Fortran run_project_tests.py pass

mesonbuild/cmake/interpreter.py, mesonbuild/cmake/traceparser.py, test cases/cmake/9 header only/main.cpp, test cases/cmake/9 header only/meson.build, test cases/cmake/9 header only/subprojects/cmMod/CMakeLists.txt, test cases/cmake/9 header only/subprojects/cmMod/include/cmMod.hpp
This PR adds support for INTERFACE libraries for CMake subprojects by extending the trace parser.
However, since INTERFACE libraries regularly use generator expressions, this PR doesn't really fix #5634. CMake generator expressions will be handled in a separate PR.
=> CMake: Support INTERFACE libraries

docs/markdown/snippets/kconfig_enhancements.md, mesonbuild/modules/unstable_kconfig.py, test cases/kconfig/4 load_config builddir/meson.build
At configure time, kconfig should learn to read configure_file()
WIP until tests are added, and perhaps FeatureNew checks?
=> Allow kconfig to read from built files

mesonbuild/dependencies/misc.py
A bug was accidentally introduced in #5734 dfa52469d7dac6f
The search for OpenMP header should stop on the first file found, or a spurious warning is emitted in general.
=> BUGFIX for #5734 dfa52469d7dac6f: OpenMP: stop searching when openmp headers are first found

mesonbuild/coredata.py
Otherwise having an output directory matching the name of the cross file
in the current working directory will cause an error. This patch instead
collects any invalid names and prints them along with the error message
when no valid file can be found.
Fixes #5640
=> coredata: Ignore directories when searching for cross/native files

docs/markdown/Users.md
Aravis project is now using meson as its build system.
=> Add aravis to meson users

mesonbuild/cmake/__init__.py, mesonbuild/cmake/generator.py, mesonbuild/cmake/traceparser.py, test cases/cmake/10 generator expressions/main.cpp, test cases/cmake/10 generator expressions/meson.build, test cases/cmake/10 generator expressions/subprojects/cmMod/CMakeLists.txt, test cases/cmake/10 generator expressions/subprojects/cmMod/include/cmMod.hpp
Add support for a few select [generator expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html) to handle some common cases (for instance in header-only libraries). This basic framework can be extended to implement even more functions in the future if necessary.
=> CMake: Basic generator expression support

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/scripts/meson_exe.py, test cases/common/185 escape and unicode/file.py
Using `capture: true` with `custom_target` makes "ninja -v" less than useful since the command line is completely hidden from the user. It would be nice if `meson --internal exe` knew to print the command line itself; unfortunately support for a `NINJAFLAGS` command line variable, which would pass -v down to `meson --internal exe`, was rejected.
Instead, this pull request makes `meson_exe` able to create an `ExecutableSerialisation` object from the command line, and uses this new invocation method for the common case of `capture: true` in custom targets and generators.  The code around `ExecutableSerialisation` needs some refactoring in order to support this, which in turn enables simplification of the `meson_exe` script.
=> Show command line in `ninja -v` for `capture: true` custom targets and generators

mesonbuild/modules/gnome.py, mesonbuild/scripts/gtkdochelper.py
This will allow using gtk-doc as a subproject instead of having to
install it on the system. It also has the side effect of failing at
configuration time with a proper message if gtkdoc is not installed,
instead of failing at build time with a python backtrace.
=> gtkdoc: Use find_program() to get gtkdoc tools

mesonbuild/compilers/compilers.py
Do not set -Wl,-headerpad_max_install_names when compiling on OSX for
another platform. It causes linker issues.
=> Fix cross compilation on OSX

mesonbuild/environment.py
Fixes #5766
FreeBSD aarch64:
```
Build machine cpu family: aarch64
Build machine cpu: aarch64
```
FreeBSD amd64:
```
Build machine cpu family: x86_64
Build machine cpu: x86_64
```
FreeBSD armv6:
```
Build machine cpu family: arm
Build machine cpu: armv6
```
FreeBSD armv7:
```
Build machine cpu family: arm
Build machine cpu: armv7
```
FreeBSD i386:
```
Build machine cpu family: x86
Build machine cpu: i386
```
FreeBSD mips64:
```
Build machine cpu family: mips64
Build machine cpu: mips64
```
FreeBSD powerpc64:
```
Build machine cpu family: ppc64
Build machine cpu: powerpc64
```
=> Detect cpu_family() and cpu() via MACHINE_ARCH on BSDs (similar to config.guess)

mesonbuild/interpreter.py, mesonbuild/msetup.py
Build and target info is confusing in that case. However still log that
information, as it is useful in case something slips out of sync and
needs to be debugged.
=> Print only host platform info in some cases during native builds

mesonbuild/msetup.py, run_tests.py
I think this makes more sense by matching how build comes before host.
Native builds are also more common than cross builds.
=> Put native file before cross file in options list

mesonbuild/modules/gnome.py
GLib does not currently use override_find_program() for this tool
because it is compiled and would not work in cross build. But this
prepares Meson for when/if GLib will rewrite it in Python.
See https://gitlab.gnome.org/GNOME/glib/issues/1859.
=> gnome: Use find_program() to get glib-compile-resources

mesonbuild/interpreter.py
It is often desirable to use ~ for home directory in -D compilation args.
Why the transform to pathlib.Path and back to str? Because this is one of many
places where the list(map(str,..))) will be eliminated upon Python 3.6 being
minimum Meson Python requirement.
=> expand tilde ~ in '-Dfoo=~/mylib'

mesonbuild/interpreter.py, mesonbuild/modules/gnome.py
When g-ir-scanner is overriden, we can't call it at configure time
but we know what options are avalaible (as it started using meson
after checked options where added) so do not try to call it to retrieve
the version as it will fail.
Also see https://github.com/mesonbuild/meson/issues/3442
=> gnome: Handle overriden g-ir-scanner

mesonbuild/compilers/mixins/ccrx.py
The CCRX linker requires libs to be linked with the `-lib=` prefix. This is working for internal static libraries but external dependencies go through a different code path.
I've added as part of the `unix_args_to_native`, I've added detection of libraries (`.lib` or `.a`) to prefix them with `-lib=` if they don't have it already.
Feel free to suggest a better way at fixing this if any 😃
=> Fix CCRX linking external dependencies

mesonbuild/interpreter.py
Dunno what the `..` was there for, but it seems to hardcode an assumption about the location of the build dir relative to src dir.
=> Rerun configuration for all potential input files. Closes #5809.

mesonbuild/linkers.py
Before python 3.5.4 typing didn't have the NoReturn type, use a string
to forward declare it.
aside: I can't wait to be able to use python 3.7's
__future__.annotations and not have to deal wit hthis anymore.
Fixes #5822
=> Fix type annotations in linkers for python < 3.5.4

mesonbuild/dependencies/base.py
This fixes that meson currently ignores explicit libraries in `INTERFACE_LINK_LIBRARIES`.
No test case this time because I actually don't know how to write one for this specific use case. Adding one would basically require an actual library that uses `-pthread`.
=> cmake: fix missing -lpthread (fixes #5821)

mesonbuild/cmake/executor.py
Fixes #5827 
dependency() calls crash if too old CMake (like 2.8) is present on a system, as is typical of HPC / CentOS systems.
There was just a line of code out of place, which is fixed here.
=> cmake:correct logic for too old cmake

docs/markdown/Using-with-Visual-Studio.md, mesonbuild/backend/backends.py, mesonbuild/backend/vs2015backend.py, mesonbuild/backend/vs2017backend.py, mesonbuild/backend/vs2019backend.py, mesonbuild/interpreter.py
This little series fixes ICL (which was broken by a refactor), and adds support for using clang-cl and icl for the visual studio backend.
@jon-turney, don't know if you're interested or not.
=> Vs backend compiler selection

run_tests.py, test cases/fortran/13 coarray/meson.build
More robust detection of Intel compilers in Windows was needed, as provided in run_tests:_using_intelcl()
also, runtime check for test cases/fortran/13 coarray was added as in general, the MPI stack needs to be exercised to verify Fortran coarrays can be used, especially for dynamically linked MPI such as Intel-Cl
=> Intel-Cl tests: increase robustness of Windows Intel compilers detection

docs/markdown/Reference-manual.md, docs/markdown/Unit-tests.md, mesonbuild/backend/backends.py, mesonbuild/interpreter.py, mesonbuild/mintro.py, test cases/common/224 test priorities/meson.build, test cases/common/224 test priorities/test.sh
Tests are sorted by decreasing priority (default: 0) and started in that order. This enables us to start tests that should run before others even though they are specified later in the meson.build file.
Note that this only affects **start order**, everything else depends on how many tests are run in parallel and how long they take to finish.
There are two issues here:
- there's a test case, but I don't know how to check for the correct ordering of the tests.
- this was a bit too easy, so I'm wondering whether I forgot something crucial :) It does work with my libinput tests.
Fixes #5581
=> Add test priorities to force test start order

mesonbuild/environment.py
The regex was incorrect, so it was matching 'ARM64' with 'ARM'.
Make the regex more specific so that it matches:
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27031.1 for x64
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27031.1 for x86
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27031.1 for ARM64
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.30319.01 for 80x86
```
etc.
=> environment: Fix detection of MSVC arch on arm64

mesonbuild/envconfig.py
These patches just make the MachineInfo.is_<os>() methods behave the same as the mesonlib.is_<os>() methods.
I think in the long term we should just do away with the mesonlib.is_<os> methods and use the MachineInfo classes, since they'll always be accurate for cross compiling.
=> This is just a few small cleanups to the MachineInfo class

mesonbuild/mesonlib.py, mesonbuild/mtest.py, mesonbuild/scripts/meson_exe.py
The size of WINEPATH is limited (1024 [until recently]), we
can very easily reach that limit, and even the new one (2048) so
try to keep path as small as possible by using the shortPath
version of paths.
Also assert that we do not reach the new hard limit.
And avoid having duplicates in the list of path.
[until recently]: https://bugs.winehq.org/show_bug.cgi?id=45810
=> wine: Try to get the short paths when generating WINEPATH

mesonbuild/backend/ninjabackend.py
Hi,
This adds a small test for scan-build presence on the build machine before generating the scan-build target. I've taken the same approach as was done for the clang-format target.
This way, meson is not  proposing a target that cannot be run.
Best regards,
=> ninjabackend: do not generate scan-build target if it cannnot be run

mesonbuild/compilers/compilers.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/d.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/mixins/gnu.py, mesonbuild/compilers/swift.py, mesonbuild/environment.py, mesonbuild/linkers.py, run_unittests.py
on Windows clang uses link.exe or lld-link.exe. It cannot (at least in my testing) use ld.lld (even though it installs it) because it has hardcoded arguments that ld.lld doesn't understand (-nologo, for example).
To fix this I've pulled `-Wl,` and similar out of the linkers as hardcoded values, and instead passed the value into the linkers at creation time. This has some additional nice affects like making the D and cuda compilers a little cleaner
=> Fix plain clang on windows

mesonbuild/backend/ninjabackend.py
Python 3.8 requires a flattened list here, Python 3.8 does not like:
```python
subprocess.Popen([['foo'], 'bar'])
```
but is of course fine with 
```python
subprocess.Popen(['foo'] + ['bar'])
```
fixes #5831
=> flatten list to subprocess.Popen, necessary for Python 3.8

.travis.yml, azure-pipelines.yml, ci/azure-steps.yml, run_tests.py
Also move away from pkg-config and ninja hosted on my server. Will move ninja over once Ubuntu starts shipping 1.9.0
commit 2ce98516cb299b01412009ec13c8c6c4b3879226:
```
azure: Download pkg-config.exe from meson cidata
```
commit f0fb29c641a62a2bd0aef21f8d7bea2d07e91255:
```
azure: Bump to upstream ninja v1.9 release
```
commit 835178b170635f92a868e0ac4c16dc1581f0e598:
```
tests: Detect ninja v1.9 and disable timestamp hack
The high-res timestamp PR by QuLogic was merged in v1.9, so we can
switch back to upstream ninja.
```
commit 2d9848337f30f1407d52dfc66333cd7e277901fd:
```
travis/macos: Use brew ninja and upgrade to v1.9.0
```
commit 9875c4764e3779a306266b5b224bcc9e59662eba:
```
azure: Workaround MSYS2 PCH test failures
Compiler version is hard-coded so that we remember to revisit this …
```
=> Workaround msys2 azure PCH test failures

docs/markdown/Pkgconfig-module.md, mesonbuild/modules/pkgconfig.py
Without this, if one creates a 'threads' dependency and passes it to 'requires' in generate(), the else error clause will be executed.
The threads library (i.e: pthreads) is correctly added to libs.private already if it is a dependency of a built library.
Also fix typo.
=> Handle case of dependency('threads') in 'requires'

mesonbuild/compilers/cuda.py, mesonbuild/environment.py, mesonbuild/linkers.py
CUDA compiling is currently broken since meson can't properly find the CUDA linker.
This adds a CUDA linker and a special case for determine the linker when we are using a CUDA compiler.
Fixes issue #5870
=> Add a CUDA linker object

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/mixins/islinker.py, mesonbuild/coredata.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/misc.py, mesonbuild/envconfig.py, mesonbuild/environment.py, mesonbuild/linkers.py, mesonbuild/mesonlib.py, mesonbuild/modules/gnome.py, mesonbuild/modules/pkgconfig.py, mesonbuild/mtest.py, mesonbuild/scripts/gtkdochelper.py, mesonbuild/scripts/scanbuild.py, run_tests.py, run_unittests.py
Closes #5726. Note that `shlex.quote`/`shlex.split` are still used for building/parsing `MESONINTROSPECT` path (it's [documented behavior](https://mesonbuild.com/Reference-manual.html) *and* `scripts/commandrunner.py` depends on it).
=> mesonlib.split_args/quote_arg/join_args

man/meson.1
In msetup the two positional arguments build-dir and source-dir
are added to the argument parser in this order.
This also affects the help message.
This order is different from the order given in the man page.
Therefore it is switched around in the man page to make it consistent
with the help message.
As the code automatically decides which directory contains what, this
change is only cosmetic. Both argument orders should be valid.
Signed-off-by: Fabian Bläse <fabian@blaese.de>
=> man: Make argument order of setup command consistent with help message

mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/mixins/pgi.py, mesonbuild/environment.py, mesonbuild/linkers.py, run_project_tests.py
The new linker layout by dcbaker made finding and fixing these issues easier--these issues generally existed since PGI was added months ago.
Before this, PGI Windows C programs were not buildable (I had previously focused on Fortran-only projects for PGI where these bugs were not invoked).
* corrected use of internal PGI-specific functions and methods (some bugfixes)
* added PGIStaticLinker
* added that PGI on Windows has an `ar`-like wrapper for Link/Lib
* allowed several `common` tests to Skip instead of Fail when C++ compiler not available, such as PGI for Windows
PGI's solution for those needing to use C++ with PGI on Windows appears to be to have the user convert C++ code to C (!)
PGI's Windows custom shell environment does not accommodate MSVC.
=> PGI compiler fixes

mesonbuild/dependencies/base.py, run_unittests.py, test cases/unit/63 rpath-link secondary/app/app.c, test cases/unit/63 rpath-link secondary/app/meson.build, test cases/unit/63 rpath-link secondary/libA/liba.c, test cases/unit/63 rpath-link secondary/libA/liba.h, test cases/unit/63 rpath-link secondary/libA/meson.build, test cases/unit/63 rpath-link secondary/libB/libb.c, test cases/unit/63 rpath-link secondary/libB/libb.h, test cases/unit/63 rpath-link secondary/libB/meson.build
@nirbheek Revert my fix commit and the test case will fail on current `master`
=> Add `-Wl,-rpath-link` for secondary dependencies

mesonbuild/backend/backends.py, run_unittests.py, test cases/unit/68 static archive stripping/app/appA.c, test cases/unit/68 static archive stripping/app/appB.c, test cases/unit/68 static archive stripping/app/meson.build, test cases/unit/68 static archive stripping/lib/libA.c, test cases/unit/68 static archive stripping/lib/libA.h, test cases/unit/68 static archive stripping/lib/libB.c, test cases/unit/68 static archive stripping/lib/libB.h, test cases/unit/68 static archive stripping/lib/meson.build
Stripping static archives without more fine-grained options (e.g. `-g`) leads to failures such as
ld: libfoo.a: error adding symbols: archive has no index; run ranlib to add one
because GNU strip removes *every* symbol in a static archive by default. Given that static archives are not final build artifacts (unlike executables and shared libraries), stripping them gains little and only causes more edge case failures.
* Gentoo's portage only strips debug information:
https://github.com/gentoo/portage/blob/86f211e3a552753eb945670a39c1a3b14c3c3bd1/bin/estrip#L322
* Fedora also only strips debug information:
https://github.com/rpm-software-management/rpm/blob/e9c13c6565cf4782d1f73255ee9144dd9bd2aca7/scripts/brp-strip-static-archive#L18
* Debian also only does some very light stripping: …
=> Fix static archives stripping

mesonbuild/mconf.py, run_unittests.py
This fix also includes a small test to ensure that `meson configure` does not crash. The correctness of the build options is already checked with `test_introspect_buildoptions_without_configured_build`.
=> mconf: Fix meson configure crash (fixes #5909)

mesonbuild/backend/ninjabackend.py, mesonbuild/environment.py, mesonbuild/scripts/scanbuild.py
Hi,
This is a follow-up to the issue raised by @lantw44 during PR https://github.com/mesonbuild/meson/pull/5857
It uses the way meson looks for a scan-build candidate when executing the target as a test for scan-build presence when generating the scan-build target.
I moved the code logic the `mesonbuild/environment.py` and call the same function in both places.
This way, if meson is able to find a scan-build binary (not necessarily named `scan-build`, eg.`scan-build-8.0`) it will propose the scan-build target.
This commit only addresses the regression introduced in the linked commit and does not change the behavior for the other llvm-tools like `clang-format`. I will do the same work later if this solution works for everyone.
Best regards,
=> uniform scan-build detection process

mesonbuild/modules/pkgconfig.py, run_unittests.py, test cases/common/47 pkgconfig-gen/dependencies/meson.build
The main library must come before extra libraries, because they are
likely to be dependencies of the main library that get promoted from
private to public. This was causing static link issues with glib-2.0.pc.
=> pkgconfig: Fix ordering of public libraries

mesonbuild/compilers/mixins/clike.py
CrossNoRunException is in compilers module, not mesonlib.
How to reproduce: run a compiler object `.run()` object while cross-compiling and making sure you don't have a exe_wrapper set.
Result: you get a meson crash:
> [… some huge backtrace …]
>   File "/home/jehan/.local/lib/python3.7/site-packages/meson-0.51.999-py3.7.egg/mesonbuild/compilers/mixins/clike.py", line 374, in run
>    raise mesonlib.CrossNoRunException('Can not run test applications in this cross environment.')
> AttributeError: module 'mesonbuild.mesonlib' has no attribute 'CrossNoRunException'
This commit fixes it, and you get just a nice meaningful error as expected, instead:
> meson.build:365:0: ERROR: Can not run test applications in this cross environment.
=> mesonbuild: fix exception name.

mesonbuild/mtest.py, run_unittests.py
According to http://testanything.org/tap-specification.html
"Any output line that is not a version, a plan, a test line, a
diagnostic or a bail out is considered an “unknown” line. A TAP parser
is required to not consider an unknown line as an error"
(glib gtest can generate empty lines - we may want to ignore only
empty lines)
Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>
=> mtest: TAP: ignore unhandled input lines

ciimage/Dockerfile, docs/markdown/Dependencies.md, docs/markdown/Release-notes-for-0.52.0.md, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/misc.py, run_project_tests.py, test cases/frameworks/29 blocks/main.c, test cases/frameworks/29 blocks/meson.build
This allows easily enabling the blocks clang extension.
libblocksruntime-dev will need to be added to CI.
=> Add blocks dependency

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/mixins/clike.py, mesonbuild/environment.py, mesonbuild/linkers.py, mesonbuild/mesonlib.py, test cases/cuda/6 std/main.cu, test cases/cuda/6 std/meson.build, test cases/cuda/7 static vs runtime/main.cu, test cases/cuda/7 static vs runtime/meson.build, test cases/cuda/8 release/main.cu, test cases/cuda/8 release/meson.build, test cases/cuda/9 optimize for space/main.cu, test cases/cuda/9 optimize for space/meson.build
Also fixes #5890. One test (`test cases/cuda/2 split`) still fails on Windows, skipping it for now.
=> CUDA support on Windows (ninja backend only)

mesonbuild/interpreter.py
Currently, the normal `DepdendencyHolder` is used for all dependencies, including `InternalDependency`. Thus the `InternalDepdendencyHolder` is unused.
=> remove InternalDepdendencyHolder

mesonbuild/coredata.py, mesonbuild/msetup.py
It can be useful to know what options have been passed to the command
line, excluding default values.
Closes: #5956
=> Print user defined options in meson-log.txt

mesonbuild/environment.py
Versioning of executables is not related to the operating system kernel.
It is possible for a Linux distribution to support multiple versions of
LLVM in a way similar to FreeBSD. For example, on Debian, you can use
'apt install clang-tools-7' to install the versioned 'scan-build-7'
executable without bringing the unversioned 'scan-build' into the
environment. Therefore, we should not skip the version list on Linux.
It also makes it consistent with the behavior of llvm dependency, which
does not change the search list depending on the operating system.
This commit also fixes the version suffix for Debian. Debian stops using
the minor version number on the executable after version 7, so it should
be 'scan-build-7', not 'scan-build-7.0'.
This is a follow-up of …
=> environment: Don't make special case for scan-build on Linux

docs/markdown/Reference-manual.md
This PR came from this discussion:
https://github.com/mesonbuild/meson/issues/5964
Just clarifying the syntax of the project() function.
=> Clarify the list of languages is optional for project()

mesonbuild/environment.py
Affects the latest version of the llvm-mingw toolchain
=> Fix GNU-like LLD being misdetected as MSVC-like LLD

mesonbuild/backend/backends.py, mesonbuild/mtest.py
as long as the cross file says we don't need one.
Fixes a regression in 0.51.x
=> Allow running tests for cross compiles without an exe_wrapper

docs/markdown/Wrap-dependency-system-manual.md, docs/markdown/snippets/depth.md, mesonbuild/wrap/wrap.py
This allows cloning subprojects shallowly.  It works recursively for a
subproject's submodules in case `clone-recursive` is set to `true`.
=> Add support for `depth` option in wrap-git

mesonbuild/backend/ninjabackend.py, mesonbuild/dependencies/dev.py, mesonbuild/environment.py, mesonbuild/scripts/clangformat.py
This pull request depends on https://github.com/mesonbuild/meson/pull/5937.
Currently we have two copies of the list of LLVM versions in Meson: one is for `llvm-config` and the other one is for `scan-build`. It should be better to move them to a common place, so they won't become out of sync. This pull request also make `clang-format` use the list, so `clang-format` installed with alternative names can now be found.
=> Move the list of LLVM versions to a common place

docs/markdown/Reference-manual.md, docs/markdown/snippets/configure_file_enhancements.md, mesonbuild/depfile.py, mesonbuild/interpreter.py, run_unittests.py, test cases/common/14 configure file/generator-deps.py, test cases/common/14 configure file/meson.build
In qemu, minikconf generates a depfile that meson could use to
automatically reconfigure on dependency change.
Note: someone clever can perhaps find a way to express this with a ninja rule & depfile=. I didn't manage, so I wrote a simple depfile parser.
=> Add depfile to configure_file()

docs/markdown/snippets/static_link.md, mesonbuild/build.py, mesonbuild/modules/pkgconfig.py, run_unittests.py, test cases/unit/69 static link/lib/func1.c, test cases/unit/69 static link/lib/func10.c, test cases/unit/69 static link/lib/func11.c, test cases/unit/69 static link/lib/func12.c, test cases/unit/69 static link/lib/func14.c, test cases/unit/69 static link/lib/func15.c, test cases/unit/69 static link/lib/func16.c, test cases/unit/69 static link/lib/func2.c, test cases/unit/69 static link/lib/func3.c, test cases/unit/69 static link/lib/func4.c, test cases/unit/69 static link/lib/func5.c, test cases/unit/69 static link/lib/func6.c, test cases/unit/69 static link/lib/func7.c, test cases/unit/69 static link/lib/func8.c, test cases/unit/69 static link/lib/func9.c, test cases/unit/69 static link/lib/meson.build, test cases/unit/69 static link/meson.build, test cases/unit/69 static link/test1.c, test cases/unit/69 static link/test2.c, test cases/unit/69 static link/test3.c, test cases/unit/69 static link/test4.c, test cases/unit/69 static link/test5.c
This is a subset of https://github.com/mesonbuild/meson/pull/3939. I tried to split it in small commits with explicit test case. I also verified that this fix static link against glib when reverting the workaround they merged: https://gitlab.gnome.org/GNOME/glib/issues/1536.
=> Fix usage of uninstalled static libraries

azure-pipelines.yml, mesonbuild/modules/python.py, run_unittests.py
This can't really be tested fully yet, because libboost-python depends on Python 2 dev packages. You can't install just the Python 3 version. The cleanups should be useful on their own, though, and the timeline should go roughly like:
- merge this for now, can remove explicit build-dep to `libpython2-dev`, though it will still be installed by the `libboost-python` package
- once Debian kills Python 2 support from `libboost-python`, update our setup to match
- delete py2 support (eventually, once all distros kill it)
Maybe we can delete py2 support sooner if nobody is using our Python build support any more, but I don't know how we could find that out other than breaking things and waiting for people to file bugs.
=> Make Python 2 tests optional(er) to prepare for py2 purge in Debian.

mesonbuild/dependencies/base.py
Most iOS apple system frameworks do not have a Versions directory in them at all.
Fixes the following traceback:
```
...
File "/Users/matt/Projects/cerbero/build/build-tools/lib/python3.7/site-packages/meson-0.51.999-py3.7.egg/mesonbuild/interpreter.py", line 3063, in func_dependency
d = self.dependency_impl(name, display_name, kwargs)
File "/Users/matt/Projects/cerbero/build/build-tools/lib/python3.7/site-packages/meson-0.51.999-py3.7.egg/mesonbuild/interpreter.py", line 3110, in dependency_impl
dep = dependencies.find_external_dependency(name, self.environment, kwargs)
File "/Users/matt/Projects/cerbero/build/build-tools/lib/python3.7/site-packages/meson-0.51.999-py3.7.egg/mesonbuild/dependencies/base.py", line 2142, in find_external_dependency
d = c()
File …
```
=> dependencies: account for frameworks without a Versions directory

docs/markdown/Unit-tests.md, docs/markdown/snippets/add_gdb_path.md, mesonbuild/mtest.py
When using the '--gdb' argument of meson test the executed binary can
now be specified with '--gdb-path'.
Closing: #4373
=> mtest: add gdb_path option

mesonbuild/cmake/interpreter.py, mesonbuild/compilers/compilers.py, test cases/cmake/2 advanced/subprojects/cmMod/CMakeLists.txt, test cases/cmake/3 advanced no dep/subprojects/cmMod/CMakeLists.txt
Fixes that also "../libinternalLib.so.1.2.3" is detected and used with `link_with`.
=> cmake: fix detection of libraries with .so version

mesonbuild/linkers.py
Pass search dirs as `['-L/some/path']` not `['-L', '/some/path']`
=> Fix split -L argument

run_unittests.py
`pkg-config` is not installed on BSDs by default. If running within a clean environment:
```
==================================================== FAILURES ====================================================
______________________________________ LinuxlikeTests.test_noncross_options ______________________________________
[...]
Version: 0.52.0
Source dir: /wrkdirs/usr/ports/devel/meson/work/meson-0.52.0/test cases/unit/51 noncross options
Build dir: /wrkdirs/usr/ports/devel/meson/work/meson-0.52.0/tmp5fv03k8_
Project name: std_remains
Project version: undefined
C compiler for the host machine: clang (clang 9.0.0 "FreeBSD clang version 9.0.0 (tags/RELEASE_900/final 372316) (based on LLVM 9.0.0)")
C linker for the host machine: lld 9.0.0
Host …
```
=> Skip test_noncross_options and test_static_link if pkg-config is missing

mesonbuild/environment.py
This is the value returned on Solaris 11.
Fixes #6006
=> environment: Detect sun4u as sparc64

mesonbuild/backend/backends.py, mesonbuild/build.py, mesonbuild/minstall.py, run_unittests.py, test cases/common/206 install name_prefix name_suffix/installed_files.txt, test cases/d/5 mixed/installed_files.txt, test cases/windows/7 dll versioning/installed_files.txt
On Windows, make sure the introspect command lists all Program database
(PDB) files containing debugging information that Meson will install.
=> Fix *.pdb files missing in meson introspect --installed output

.gitignore, mesonbuild/compilers/__init__.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/cs.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/d.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/java.py, mesonbuild/compilers/mixins/arm.py, mesonbuild/compilers/mixins/ccrx.py, mesonbuild/compilers/mixins/clang.py, mesonbuild/compilers/mixins/elbrus.py, mesonbuild/compilers/mixins/gnu.py, mesonbuild/compilers/mixins/intel.py, mesonbuild/compilers/mixins/pgi.py, mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, mesonbuild/compilers/rust.py, mesonbuild/compilers/swift.py, mesonbuild/compilers/vala.py, mesonbuild/environment.py, mesonbuild/linkers.py, mesonbuild/munstable_coredata.py, run_project_tests.py, run_unittests.py
This series deletes the CompilerType enum, and replaces it with a reference of the relevant `MachineInfo`. This has a couple of nice properties, namely that the MachineInfo is more accurate than the CompilerType info is, and second that it allows us to use `MachineInfo.is_os()` instead of `mesonlib.is_os()`, the former is safe for cross compiles while the later isn't.
=> Remove compiler type

mesonbuild/compilers/fortran.py, mesonbuild/environment.py
fixes regression for systems with nvcc installed--perhaps why not previously caught on CI.
Just a simple typo--missing a positional argument to CudaCompiler()
0c22798b1ad4678abb205280060175678a790c4a is the first bad commit 
```sh
python run_project_tests.py
```
File "meson\mesonbuild\environment.py", line 1066, in detect_cuda_compiler
return CudaCompiler(ccache + compiler, version, for_machine, is_cross, exe_wrap, host_compiler=cpp_compiler,
linker=linker)
TypeError: __init__() missing 1 required positional argument: 'info'
* any system with Cuda / nvcc
* Intel-Cl
=> BUGFIX: environment.py CudaCompiler and Intel-Cl

mesonbuild/compilers/c.py
Commit ff4a17dbef08a1d8afd075f57dbab0f5c76951ab modified the version
requirements wrongly. AppleClangC should be the one with higher version
numbers. Exchange them to fix the check.
=> compilers: Fix version requirements for ClangC and AppleClangC

mesonbuild/interpreter.py
fixes #6000 due to #5768 
The idea is that end-users want to specify an array of directories to search by default
without an if/elif stack. It's obvious that Unix absolute paths are not absolute on
Windows, so silently discard Unix absolute paths here for Windows instead of raising
exception.
As noted in #6000 discussion, Python on Windows has the errant behavior 
```python
os.path.isabs('/') == True  # incorrect but perhaps legacy-maintaining logic for Windows
```
when it should be  on Windows:
```python
pathlib.Path('/').is_absolute() == False
```
=> path interpreter--silently discard invalid Unix relative paths on Windows

data/syntax-highlighting/vim/ftplugin/meson.vim
Vim can automatically comment and format comments. Set the necessary
variable to enable that feature.
See `:help format-comments` for more information.
=> syntax-highlighting: vim: set comment string

mesonbuild/compilers/c.py, mesonbuild/compilers/cpp.py
Without the fix, this happens due to incorrect argument order:
```
File "/data/git/meson/mesonbuild/mesonmain.py", line 129, in run
File "/data/git/meson/mesonbuild/msetup.py", line 245, in run
app.generate()
File "/data/git/meson/mesonbuild/msetup.py", line 159, in generate
File "/data/git/meson/mesonbuild/msetup.py", line 176, in _generate
intr = interpreter.Interpreter(b)
File "/data/git/meson/mesonbuild/interpreter.py", line 2110, in __init__
self.parse_project()
File "/data/git/meson/mesonbuild/interpreterbase.py", line 397, in parse_project
self.evaluate_codeblock(self.ast, end=1)
File "/data/git/meson/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
raise e
File …
```
=> Fix emscripten C compiler initialization

run_unittests.py, test cases/unit/71 cross/crossfile.in, test cases/unit/71 cross/meson.build, test cases/unit/71 cross/meson_options.txt
A build with a cross file should always be identified as a cross build, even if
the host and build machine are identical.  This was the case in 0.50, regressed
in 0.51, and is fixed again in 0.52, so add a test case to ensure it doesn't
regress again.
=> Add test case to verify identity cross builds

mesonbuild/compilers/c.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/mixins/emscripten.py
The problem here is that emcc is sensitive to the output suffix, so Meson's assumption that `exe`/`obj` is always fine doesn't hold up. In the case of unknown suffix it just emits a wasm object without linking. This makes stuff like `cc.has_function` return `true` for pretty much everything.
I also took the opportunity to move some copypasted code into a mixin.
This PR is based on #6042, so that should go in first.
=> Emscripten: fix false positives in linking tests

test cases/common/1 trivial/meson.build
since 0.52 is indeed now required for this test case.
=> test cases/1 common: update meson_version>=0.52 for is_disabler

mesonbuild/mintro.py
The lack of newlines in the print() statement for this error causes the result
to be jumbled and hard to read:
```
$ ./meson.py introspect
Current directory is not a meson build directory.Please specify a valid build dir or change the working directory to it.It is also possible that the build directory was generated with an oldmeson version. Please regenerate it in this case.
```
Add newlines so the message is more readable:
```
$ ./meson.py introspect
Current directory is not a meson build directory.
Please specify a valid build dir or change the working directory to it.
It is also possible that the build directory was generated with an old
meson version. Please regenerate it in this case.
```
=> Add missing newlines to "meson introspect" error

test cases/frameworks/17 mpi/main.cpp, test cases/frameworks/17 mpi/meson.build
The MPI test logic was a bit excessive about skipping, especially for Windows as it was before Intel-Cl was supported in Meson.
Instead of *carte blanche* skipping most Windows tests, we check if MPI `links()`.
=> MPI: don't excessively skip Windows test cases, which can hide real problems

mesonbuild/backend/xcodebackend.py
Fixes #6035 no 32-bit project warning in MacOS Catalina Xcode 11.1
Would like someone familiar with Xcode to verify nothing breaks by this slight change.
=> xcode 64 bit for catalina

data/syntax-highlighting/vim/ftplugin/meson.vim, data/syntax-highlighting/vim/indent/meson.vim, data/syntax-highlighting/vim/syntax/meson.vim
Add a license header before getting them in the Vim runtime.
=> syntax-highlighting: vim: add license header

docs/markdown/Precompiled-headers.md
The documentation already contains an example for PCH but misses the
to show the content of the PCH files and how to create them.
With this commit exactly this is exlained.
=> Documentation: Extend example for precompiled headers

mesonbuild/compilers/mixins/elbrus.py
Some new changes to keep Elbrus compiler support up to date (actually those of library and include file paths).
Unit tests are ok:
```reisen /usr/src/meson/meson # ./run_unittests.py
pytest-xdist not found, using unittest instead
........s...................s.......s...............................................................................s.....s........../usr/src/meson/meson/tmp3l8433aj/meson-private/sanitycheckobjc.m: file not recognized: Формат файла не распознан
/usr/src/meson/meson/tmp3l8433aj/meson-private/sanitycheckobjc.m: file not recognized: Формат файла не распознан
...ss.......s.s..sss............sss.......................................................s.....s........s..s..s..s........s........ssssssssssssssssss …
```
=> Some fixes for Elbrus compiler

mesonbuild/mdist.py
Source of patch:
http://lists.busybox.net/pipermail/buildroot/2019-October/262990.html
http://code.bulix.org/gdxcu4-914360
Fixes https://github.com/mesonbuild/meson/issues/6012
=> mdist.py: import lzma only when needed

run_unittests.py, test cases/python/4 custom target depends extmodule/meson.build, test cases/python3/2 extmodule/meson.build, test cases/python3/4 custom target depends extmodule/meson.build
I could not determine the cause or replicate it on my machine because VS2015 can't be obtained easily. :(
=> Disable extension module tests with Python 3.8 and VS2015.

mesonbuild/cmake/interpreter.py, test cases/cmake/13 system includes/main.cpp, test cases/cmake/13 system includes/meson.build, test cases/cmake/13 system includes/subprojects/cmMod/CMakeLists.txt, test cases/cmake/13 system includes/subprojects/cmMod/cmMod.cpp, test cases/cmake/13 system includes/subprojects/cmMod/cmMod.hpp, test cases/cmake/13 system includes/subprojects/cmMod/sysInc/triggerWarn.hpp
Meson should override all common warning flags from CMake and rely on the project-wide warning settings instead. This way projects that add `-Werror` in the `CMakeLists.txt` won't trigger hard to fix compilation errors (see #6079).
Note: This is not a proper fix for #6079, since it doesn't solve the underlying problem of handling the system include directories.
=> cmake: Blacklist more compiler warning flags

mesonbuild/cmake/__init__.py, mesonbuild/cmake/client.py, mesonbuild/cmake/common.py, mesonbuild/cmake/fileapi.py, mesonbuild/cmake/interpreter.py, mesonbuild/cmake/traceparser.py, run_project_tests.py
The file API will automatically be used when CMake >= 3.14
is detected. This new API is meant as a replacement for the
now deprecated CMake server API.
The new API (mostly) provides the same information in a
different format. Thus only a slight bit of refactoring was
necessary to implement this new backend.
=> cmake: Add CMake file API support

mesonbuild/backend/backends.py, test cases/unit/69 static link/lib/func17.c, test cases/unit/69 static link/lib/func18.c, test cases/unit/69 static link/lib/func19.c, test cases/unit/69 static link/lib/meson.build
When a static library link_whole to a bunch of other static libraries,
we have to extract all their objects recursively. But that could
introduce duplicated objects. ar is dumb enough to allow this without
error, but once the resulting static library is linked into an
executable or shared library, the linker will complain about duplicated
symbols.
=> Remove duplicated object files in static libraries

mesonbuild/compilers/d.py, mesonbuild/environment.py
The optlink linker is slowly getting phased out now since DMD ships with the LLVM linker, so it can be used when Visual Studio is not installed.
LLVM and MSVC linker fails to translate `get_allow_undefined_args` properly which was causing issues, and the last refactor also dropped `-shared` flag for shared library builds.
=> d: Fix various linking issues

test cases/fortran/17 add_languages/meson.build, test cases/fortran/18 first_arg/meson.build
Help ensure more of the core functional syntax of Meson is supported with a Fortran compiler.
For example, PGI is broken with regard to these tests.
=> tests: add fortran-specific compiler checks

mesonbuild/interpreter.py, mesonbuild/mesonlib.py
Fixes #5844
avoids spilling Python traceback by raising Meson exception.
meson.build MWE
```meson
project('test-npe')
pythonmod = import('python')
python = pythonmod.find_installation('NotAnExistingModuleABC123', required: false)
run_command(python, '-v')
```
=> interpreter: raise Meson exception when non-found module is used anyway

mesonbuild/minstall.py, run_unittests.py
This patch fixes an issue with multiple entries per installed file in the install-log.txt file. Multiple entries are annoying when running the uninstall target since they causes error messages, see issue #4499.
(This is my first contribution to an open source project, so please be gentle ;-))
=> Fix for issue #4499, multiple entries per file in install-log.txt

docs/markdown/Reference-manual.md
Signed-off-by: Matthew Weber <matthew.weber@rockwellcollins.com>
=> docs: clarify --default-library is for internal libraries

README.md, docs/markdown/Quick-guide.md, pyproject.toml, setup.cfg, setup.py
should fix https://github.com/mesonbuild/meson/issues/6117 by ensuring setuptools is present in a PEP-standard way.
=> Ensure setuptools via PEP508/518 pyproject.toml

docs/markdown/snippets/new_meson_project_templates.md, mesonbuild/minit.py, mesonbuild/templates/cpptemplates.py, mesonbuild/templates/ctemplates.py, mesonbuild/templates/dlangtemplates.py, mesonbuild/templates/fortrantemplates.py, mesonbuild/templates/objctemplates.py, mesonbuild/templates/rusttemplates.py, run_unittests.py, setup.py
built upon #6112 
Modularized internal implementation of `meson init` and adds Rust, Fortran, D, etc. and makes it easier to add more languages for templates
Modernizes the Python 2 style to Python3 in minit.py
=> Minit templates modularization

mesonbuild/compilers/fortran.py, mesonbuild/environment.py
fixes several fortran compilers:
* PathScale
* PGI
* Flang
* Open64
* NAG
broke in commit 0c22798
=> bugfix: fortran compiler assertionerror from 0c22798

mesonbuild/dependencies/base.py
Under Windows, the colon ':' is used after the drive letter.
So, the colon should not be used as a list separator or for splitting,
otherwise it could lead to paths in `CMAKE_PREFIX_PATH` with a
semicolon ';' between the drive letter and the rest of the path, e.g:
`-DCMAKE_PREFIX_PATH=C;/foo/bar`
instead of
`-DCMAKE_PREFIX_PATH=C:/foo/bar`
=> Fix split of CMAKE_PREFIX_PATH under Windows

mesonbuild/modules/pkgconfig.py
Hey,
FreeBSD uses ${PREFIX}/libdata/pkgconfig as default pkgconf search path for non-base libraries, so I think it would be appropriate for Meson to default to that directory too. This commit makes necessary changes for this.
=> Change default pkgconfig directory on FreeBSD

docs/markdown/Dependencies.md, docs/markdown/snippets/cuda_dependency.md, mesonbuild/compilers/cuda.py, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/cuda.py, mesonbuild/mesonlib.py, test cases/cuda/10 cuda dependency/c/meson.build, test cases/cuda/10 cuda dependency/c/prog.c, test cases/cuda/10 cuda dependency/cpp/meson.build, test cases/cuda/10 cuda dependency/cpp/prog.cc, test cases/cuda/10 cuda dependency/meson.build, test cases/cuda/10 cuda dependency/modules/meson.build, test cases/cuda/10 cuda dependency/modules/prog.cc, test cases/cuda/10 cuda dependency/version_reqs/meson.build, test cases/cuda/10 cuda dependency/version_reqs/prog.cc, test cases/cuda/11 cuda dependency (nvcc)/meson.build, test cases/cuda/11 cuda dependency (nvcc)/modules/meson.build, test cases/cuda/11 cuda dependency (nvcc)/modules/prog.cu, test cases/cuda/11 cuda dependency (nvcc)/version_reqs/meson.build, test cases/cuda/11 cuda dependency (nvcc)/version_reqs/prog.cu, test cases/cuda/12 cuda dependency (mixed)/kernel.cu, test cases/cuda/12 cuda dependency (mixed)/meson.build, test cases/cuda/12 cuda dependency (mixed)/prog.cpp
Native support for compiling and linking against the CUDA Toolkit using the `dependency` function: 
```meson
project('CUDA test', 'cpp', meson_version: '>= 0.52.0')
exe = executable('prog', 'prog.cc', dependencies: dependency('cuda'))
```
The `version` and `modules` keywords may be passed to request the use of a specific CUDA Toolkit version and/or additional CUDA libraries, correspondingly:
```meson
dep = dependency('cuda', version : '>=10', modules : ['cublas'])
```
Note that explicitly adding this dependency is only necessary if you are using CUDA Toolkit from a C/C++ file or project, or if you are utilizing additional toolkit libraries that need to be explicitly linked to.
=> dependency('cuda') support

mesonbuild/dependencies/base.py, run_unittests.py
Previously meson would incorrectly handle a dependency as found even though one of the calls to either `pkg-config --libs` or `pkg-config --cflags` failed, which can lead to surprising build failures.
Additionally the exception would use stdout which does not contain anything helpful about the failure.
=> Fix pkgconfig error handling

data/syntax-highlighting/vim/syntax/meson.vim
since 'cpo' is global, use `set` instead of `setlocal`.
Reported-By: Bram Moolenaar <Bram@vim.org>
Signed-off-by: Liam Beguin <liambeguin@gmail.com>
=> syntax-highlighting: vim: fix setting cpo

azure-pipelines.yml, mesonbuild/minit.py, mesonbuild/msetup.py, mesonbuild/mtest.py, tools/ac_converter.py, tools/boost_names.py, tools/dircondenser.py
Initial demonstration of using type annotation checking in Meson. We have a lot of type annotation sprinkled into Meson, let's start using it. As we add more annotation and fix thereby-discovered corner cases, we can add more directories and files to the type checker.
=> CI: add initial type annotation checking

mesonbuild/modules/pkgconfig.py
=> pkgconfig: only check import_filename for shared libraries

docs/markdown/FAQ.md
Make FAQ entry about linking failing on Windows with MSVC more easily discoverable by including keywords LNK1181 and linking.
=> docs: Mention error LNK1181, linking for MSVC

mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/interpreter.py, test cases/common/54 run target/meson.build
This way we can easily check that we only provide builtin targets such
as clang-format if the user has not provided their own.
=> Store run target names in build.

docs/markdown/howtox.md
Meson doesn't currently provide a very helpful message when trying to generate a coverage report with clang, and in fact just silently fails for 2 of the 3 reports.  Ideally Meson would support coverage with llvm-cov, or provide a more helpful error message.  Until then, it seems it would be helpful to at least put a warning in the documentation.
=> Document lack of clang support [skip-ci]

docs/markdown/snippets/add_dictionary_variable_key.md, mesonbuild/interpreterbase.py, mesonbuild/mparser.py, test cases/common/228 add dict variable key/meson.build, test cases/failing/97 add dict non string key/meson.build, test cases/failing/98 add dict duplicate keys/meson.build
Hi,
I'd like to contribute this change which allows adding a dictionary entry using string variable as key, in addition to using string literal as key.
Example:
dict = {}
key = 'myKey'
dict += {key : 'myValue'}
=> Adding dictionary entry using string variable as key.

mesonbuild/scripts/depfixer.py
Meson should not try to fix rpath on both EXE and DLL when cross compile.
=> Prevent install_name_tool to run on EXE when cross compile on OSX

mesonbuild/cmake/interpreter.py
Previously, warnings generated in CMake were not logged because CMake sends them to stderr alongside the trace information. With this PR, only real trace lines are sent to the trace parser and
all other lines in stderr are logged as warnings.
This should probably classify as a bugfix, but I am not 100% sure if it is OK to include this in 0.52.1.
=> cmake: Log warnings in CMakeLists.txt

README.md
A new Meson user may not realize how easy it is to get Ninja via
pip install ninja
=> doc: readme note that can get ninja via  pip install ninja [skip ci]

mesonbuild/coredata.py, run_unittests.py, test cases/unit/34 command line/meson_options.txt
Previously if a user tried to pass a command line build
option that contained a '%' character the command line
parser assumed that there was string interpolation to be
done. As there is no sense in such a scenario no code
provides any input for the interpolation. This then leads to
a failure.
In this commit we specifically override the defaults in
ConfigParser and set interpolation to None, which disables
command line build option interpolation.
Fixes #6157
=> coredata: CmdLineFileParser no longer interpolates strings.

docs/markdown/Rewriter.md
Probably dating back to the former mesonrewriter command?
Fixes commit d4fe805a51d5
In some corner cases, "rewriter" could be mistaken as a positional
argument.
=> docs: fix non-existent "meson rewriter" command in examples [skip ci]

mesonbuild/environment.py
Nix uses absolute paths to compilers in Nix store with Meson. Those store paths contain a hash, which can contain short strings like `icl`, resulting in incorrectly matching the compiler.
See https://github.com/NixOS/nixpkgs/issues/73417#issuecomment-554077964
cc @dcbaker who introduced `icl` in https://github.com/mesonbuild/meson/pull/5331, @Ericson2314
=> environment: Only check compiler basename for compiler name

mesonbuild/interpreter.py
When run_command() first parameter is a compiler object, keep additional
exelist values as arguments.
This fixes #6174.
=> Issue #6174: run_command() with compiler object behind ccache fails.

mesonbuild/scripts/commandrunner.py
Some commands, notably gdb, use ctrl+c themselves to perform actions
without exiting. Instead of making meson exit and thus, kill the
subprocess, ignore the KeyboardInterrupt and continue waiting for
the child.
=> commandrunner: Forward KeyboardInterrupt to command

azure-pipelines.yml, docs/markdown/Fs-module.md, mesonbuild/modules/fs.py, test cases/common/227 fs module/meson.build
* add type annotation and type checking for fs module
* use pathlib.Path instead of os.path for more robust, clear code
* deduplicate functions
* use *Path*.expanduser() to allow use of `~` for home directory
* add `fs.replace_suffix()` to modify filename suffix--file need not exist
* add `fs.hash()` to compute file hashs including MD5, SHA256, ...
* add `fs.samefile()` to determine if two filenames refer to the same file (incl. symlinks)
=> fs module; make more robust, dedupe code, add method, add type anno & check

docs/markdown/IDE-integration.md, docs/markdown/snippets/introspect.md, mesonbuild/dependencies/base.py, mesonbuild/interpreter.py, mesonbuild/mintro.py, mesonbuild/mlog.py, run_unittests.py
With this PR, dependency versions are also logged for cached dependencies. Additionally, the `(cached)` and dependency version are now highlighted to help users identify potential caching issues.
The dependency version is now also visible in the introspection API.
This PR should resolve #6181.
=> Better dependency logs

.github/workflows/lint_mypy.yml, .github/workflows/unusedargs_missingreturn.yml, azure-pipelines.yml
Free up Azure resources and only run when Python code is changed for MyPy and Pylint, using GitHub Actions.  In general Actions will let us better cover Meson's particular features such as dependencies without overburdening general CI and the docker image.
=> lint+mypy: move to github actions

mesonbuild/compilers/fortran.py
It would be very challenging if not futile to make `has_function` work for Fortran.
The `meson.get_compiler('fortran').links()` works very well instead.
As a reference, CMake's [check_fortran_function_exists](https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/CheckFortranFunctionExists.cmake) is completely broken in general.
This change raises a useful MesonException instead of giving bizarre errors as Meson does now on invoking
```meson
meson.get_compiler('fortran').has_function('sin')
```
=> fortran: note there is no has_function for Fortran

mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/coarrays.py, mesonbuild/dependencies/misc.py, test cases/fortran/13 coarray/meson.build
now the Fortran coarray dep finding uses pkg-config as well as cmake, since pkg-config was added to coarrays package opencoarrays.
Put dependency in its own file for clarity
=> dep: Fortran Coarrays-enhance finding by use Pkg-config & CMake

mesonbuild/compilers/fortran.py
also, find intel-cl submodule .smod name pattern. this would fix
intermittent failures of ninja to resolve submodule file dependencies.
This makes for warning_level=3 that Intel, Gfortran and PGI all force `implicit none` on all source code, a good build practice (but not feasible for old legacy code).  Not every compiler can do this, so I just enabled it for those that can.
=> fortran: sync implicit-none args for intel,pgi,gfortran

mesonbuild/compilers/d.py, mesonbuild/environment.py, mesonbuild/interpreter.py
Since version 9.1, GCC provides support for the D programming language.
Thus it is easy to build a cross-compiler for D, such as aarch64-unknown-linux-gnu-gdc.
However to cross-compile a Meson project using D, using a cross build
definition such as the following is not enough:
```
[binaries]
d = '/path/to/aarch64-unknown-linux-gnu-gdc'
exe_wrapper = '/path/to/qemu-aarch64-static'
[properties]
needs_exe_wrapper = true
[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'cortex-a53'
endian = 'little'
```
Indeed, "exe_wrapper" is not be taken into account. Build will fail
with:
```
Executables created by D compiler /path/to/aarch64-uknown-linux-gnu-gdc are not runnable.
```
This patch fixes this by reworking:
- detect_d_compiler() to properly get exe_wrapper and D compilers and …
=> [RFC] Fix cross-compilation of D programs

mesonbuild/interpreter.py, mesonbuild/mesonlib.py, test cases/common/14 configure file/dumpprog.c, test cases/common/14 configure file/meson.build
set_quoted() makes the value into a double-quoted string, so let's
assume C-style string, in particular with newlines as "\n".
Also take care of remaining newlines in dump_conf_header(). C or nasm
macros expect single-line values so if the value was multi-line, we
would end up with broken syntax. Appending a backslash at each end of
line make them concat into a single line in both C and nasm format
(note: multi-line macros in nasm are actually possible apparently but
use another format not outputted by current meson code). Also note that
the replacement is done at the end only when dumping the conf as a
header because we cannot assume anything about the format when replacing
variables from an input file (in this case, it should be the dev
responsibility).
----------
This was a result of …
=> Have set() and set_quoted() of configuration object work with newlines.

mesonbuild/modules/unstable_cuda.py
CUDA Toolkit 10.2 was released. Add its corresponding table entry in the minimum driver version table.
=> Add table entry for CUDA Toolkit 10.2.89.

mesonbuild/compilers/compilers.py
On OpenBSD, libexecinfo is not n internal library and should be
detected with find_library().
This should fix https://github.com/mesonbuild/meson/issues/5432
=> openbsd: execinfo is not a compiler lib

.github/workflows/lint_mypy.yml, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/mpi.py, mesonbuild/linkers.py, mesonbuild/mesonlib.py
Improve finding MPI, particularly for Intel compilers with Intel MPI, most of all on Windows where Intel MPI could not be found this way previously.
Use cases include:
* IntelMPI: Windows @ Intel-cl
* IntelMPI: Linux @ intel
* OpenMPI: Linux @ gcc
* OpenMPI: MacOS @ gcc
* MS-MPI: Windows @ cl
=> dep: MPI make work for intel-cl and improve robustness

docs/markdown/Builtin-options.md, docs/markdown/Configuring-a-build-directory.md, docs/markdown/snippets/fortran_std.md, mesonbuild/compilers/fortran.py, test cases/fortran/19 fortran_std/legacy.f, test cases/fortran/19 fortran_std/meson.build, test cases/fortran/19 fortran_std/std2003.f90, test cases/fortran/19 fortran_std/std2008.f90, test cases/fortran/19 fortran_std/std2018.f90, test cases/fortran/19 fortran_std/std95.f90
Like `c_std` and `cpp_std` but for Fortran. Only Gfortran and Intel Fortran have usable support for this option. The other compilers ignore this option.
=> Add `fortran_std` project option

mesonbuild/dependencies/ui.py
Hi,
When building gtk master for 32-bit Windows using Visual Studio 2015, I found that Meson did not detect the correct arch for the Vulkan libraries as I am running a x64 version of Windows, which resulted in the result being 'x86_64' when passing an empty set into environment.depect_cpu(), which caused linking to fail due to mixing 32-bit object files with x64 .lib's.
To fix this, use environment.detect_cpu_family() on the self.env.coredata.compilers.host that we already have, so that we will link to the correct 32-bit Vulkan .lib.
Please note that this does not attempt to fix looking for Vulkan on ARM/ARM64 Windows as it seems that Microsoft does not allow Vulkan drivers on Windows-on-ARM systems, hence it seems that there is no Vulkan SDK that supports ARM/ARM64 development.
With …
=> dependencies/ui.py: Fix Vulkan detection on Windows

mesonbuild/cmake/data/run_ctgt.py, mesonbuild/cmake/interpreter.py, test cases/cmake/2 advanced/installed_files.txt, test cases/cmake/3 advanced no dep/installed_files.txt, test cases/cmake/5 object library/subprojects/cmObjLib/CMakeLists.txt, test cases/cmake/6 object library no dep/subprojects/cmObjLib/CMakeLists.txt
Better handle target names for the generated CMake subproject targets. Additionally, avoid conflicts in the outputs of custom targets.
Related issues: #6208
=> cmake: Uniform target name handling and custom target fixes

mesonbuild/build.py, test cases/common/215 link custom/custom_stlib.py, test cases/common/215 link custom/lib.c, test cases/common/215 link custom/meson.build
t.pic won't be defined. We can only hope it has been built with -fPIC.
Linker will complain otherwise any way.
t.extract_all_objects_recurse() won't be defined. We could support this
case by extracting the archive somewhere and pick object files.
=> Fix link_whole with a custom target

test cases/frameworks/4 qt/main.cpp
Finding all the dependencies missing from my Fedora system to run the whole
test suite was relatively quick - except for this one.
=> tests: add clues to find missing private/qtobject_p.h

lgtm.yml
LGTM is currently giving spurious errors since LGTM is defaulting
to Python 2 for Meson.
=> ci: lgtm: configure for Python 3

mesonbuild/modules/qt.py
When lrelease-qtN is missing, upgrade the error message from the
cryptic:
meson.build:75:4: ERROR: Tried to use not-found external program in "command"
to the meaningful:
meson.build:75:4: ERROR: qt.compile_translations: lrelease-qt5 not found
Issue found and tested with "test cases/frameworks/4 qt/"
=> modules/qt.py: friendlier "lrelease-qtN not found" error message

.github/workflows/frameworks.yml, .github/workflows/lint_mypy.yml, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/hdf5.py, mesonbuild/dependencies/misc.py, test cases/frameworks/25 hdf5/meson.build
This addresses various real-world problems with HDF5 pkg-config, including
* hdf*.pc with package versions as part of the filename
* malformed hdf*.pc missing the commonly-used HDF5 HL module
Prior to this PR, HDF5 finding only worked OK on Linux, but not on Mac or Windows.
HDF5 finding should now on systems including:
* MacOS
* Linux
* Windows (MSYS2)
Why isn't CMake included in the search? It needs to be able to use `find_package(HDF5 COMPONENTS ...)` which doesn't seem possible at the moment.  Specifically, the `extra_args` to Cmake is for the command line, which doesn't appear to work for COMPONENTS.
This will be for a future PR that will enhance finding numerous dependencies via CMake.
=> HDF5: improve MacOS and Windows finding

mesonbuild/msubprojects.py
Same fix as e7b25018c4715e538234d4ba51e32194b4757388, was accidentally missed when this code was rewritten.
=> wrap: Redirect stdin to DEVNULL (again)

mesonbuild/linkers.py, test cases/osx/8 pie/main.c, test cases/osx/8 pie/meson.build
The linker implementation split up introduced a regression: since the
AppleDynamicLinker subclass doesn't expose PIE support, builds using
that feature just plainly fail.
Add back support for it using the default and supported -pie flag.
=> linkers: AppleDynamicLinker supports -pie.

mesonbuild/environment.py
Make it work regardless of MSVC output language
Fixes #6128
=> Fix regular expression for MSVC target arch detection

mesonbuild/build.py
Be more explicit about the --wipe command requiring to be executed from the source dir.
=> improve error message when old version detected

mesonbuild/cmake/data/run_ctgt.py, mesonbuild/cmake/interpreter.py, test cases/cmake/8 custom command/subprojects/cmMod/CMakeLists.txt, test cases/cmake/8 custom command/subprojects/cmMod/cmMod.cpp, test cases/cmake/8 custom command/subprojects/cmMod/cp.cpp, test cases/cmake/8 custom command/subprojects/cmMod/cpyNext.cpp.am, test cases/cmake/8 custom command/subprojects/cmMod/cpyNext.hpp.am
This PR refactors the old output_target_map, which was a
raw dict, into it's own class. This makes the access to
the map more uniform and robust (at the cost of more lines
of code).
Additionally relative paths to the build directory are
now also tracked for outputs. This is neccessary to
corretcly distingluish files with the same name, that are
in different directories.
=> cmake: Make output_target_map more robust (fixes #6208)

docs/markdown/Continuous-Integration.md
Just an update to CI Continuous Integration page because I think it would help people can install both Meson and Ninja using `pip install meson ninja`, this should make CI YAML files easier to read.
CircleCi example is added to provide a new option for Meson build projects when choosing a CI provider.
=> Update CI Continuous Integration page and add CircleCi example [skip ci]

mesonbuild/mparser.py, test cases/common/228 add dict variable key/meson.build
Fixes PR #6166 and more specifically commit 4e460f04f3b2 that tried to
make sure the type of a key variable is a string but checked the type of
the value instead. Extends test common/228's limited coverage,
its only test case had (surprise) a string value. Also avoid reserved
python keyword 'dict' and potentially confusing string 'key'.
Implements #5231 for real.
=> mparser.py: actually check the type of key variable, not its value

mesonbuild/modules/fs.py
Just fixing errors found by LGTM by adding raise at the start of MesonExceptions in your file system module before it became an issue.
=> Add raise at the start of MesonException

mesonbuild/compilers/fortran.py, mesonbuild/compilers/mixins/intel.py
This puts appropriate default options across buildtype for Intel and
Intel-Cl compilers, for C, C++ and Fortran. Prior to this PR, the
behavior of Intel compilers vs. GNUlike was not the same, in
particular, debug traceback available by default for GNUlike compilers
was not present with Intel compilers.
=> intel/intel-cl: use expected buildtype options

mesonbuild/build.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/mixins/elbrus.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/cuda.py, mesonbuild/dependencies/dev.py, mesonbuild/interpreter.py, mesonbuild/mesonlib.py, mesonbuild/wrap/wrap.py, setup.cfg
This should eliminate all but 3 warning categories in LGTM (`Similar function`, `Conflicting attributes in base classes` and `__init__ method calls overridden method`).
As a bonus, the last commit fixes the pytest warning by ensuring that only classes derived from `unittest.TestCase` are considered test classes.
=> LGTM fixes, round 2

mesonbuild/msubprojects.py
The 'output' field of the subprocess.CalledProcessError exception is
valid only when subprocess.check_output() is called, trying to access it
after calling subprocess.check_call() results in an unwanted exception
when commands return non-zero exit code, e.g.:
-----------------------------------------------------------------------
```
$ meson subprojects foreach false
Executing command in ./subprojects/sqlite-amalgamation-3250100
-> Not downloaded yet
Executing command in ./subprojects/gstreamer
File "/home/ao2/meson/meson/mesonbuild/msubprojects.py", line 177, in foreach
subprocess.check_call([options.command] + options.args, cwd=repo_dir)
File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
raise CalledProcessError(retcode, cmd) …
```
=> Fix 'meson subprojects foreach' when command returns non-zero exit code

mesonbuild/build.py, mesonbuild/compilers/compilers.py, mesonbuild/linkers.py, run_unittests.py
This cleans up a few things I noticed from the recent lgtm changes that are either incorrect, or were correct and simpler before the changes.
=> Fix lgtm cleanup problems

docs/markdown/Reference-manual.md, docs/markdown/Unit-tests.md
This default behavior can have surprising and time-consuming outcomes.
I was wondering why certain tests using several external, fixed libraries
would fail only with Meson and not with CMake or manual runs.
The root cause was that mtest.py enables MALLOC_PERTURB_ by default, which is
surprising--a topic for another Issue/PR.
This default behavior is documented with workarounds.
=> mtest: document default MALLOC_PERTURB_=1..255 behavior

manual tests/1 wrap/main.c, manual tests/10 svn wrap/prog.c, manual tests/11 wrap imposter/meson.build, manual tests/11 wrap imposter/subprojects/zlib.wrap, manual tests/12 wrap mirror/meson.build, manual tests/12 wrap mirror/subprojects/zlib.wrap, manual tests/3 git wrap/prog.c, manual tests/4 standalone binaries/myapp.cpp, manual tests/5 rpm/main.c, manual tests/6 hg wrap/prog.c, manual tests/8 timeout/sleepprog.c, mesonbuild/modules/rpm.py, mesonbuild/wrap/wrap.py
In my opinion, we should not fall back to http:// from the SSL HSTS WrapDB URL, **for systems that have Python SSL** as that is controverting the point of HSTS + SSL.
For systems that do not have Python SSL, they continue to work with a
colored mlog.warning instead of only a stderr console print.
Also, attempt to stop masquerade URLS containing wrapdb.mesonbuild.com.evil.stuff.com
=> wrap: working to improve security

ghwt.py, tools/ac_converter.py
Simply update Python2 syntax to Python3 syntax in `ghwt.py`, main benefit would be less %s symbols mixed in with {} and .format
=> Update Python2 syntax to Python3 syntax in ghwt.py

mesonbuild/wrap/wrap.py, mesonbuild/wrap/wraptool.py, tools/ac_converter.py
Simply update Python2 syntax to Python3 syntax in Wrap, main benefit would be less `%s` symbols mixed in with `{}` and `.format`
=> Update Python2 syntax to Python3 syntax in Wrap 

docs/genrelnotes.py, tools/ac_converter.py
Simply update Python2 syntax to Python3 syntax in `genrelnotes.py`, main benefit would be less `%s` symbols mixed in with `{}` and `.format`
=> Update Python2 syntax to Python3 syntax in genrelnotes.py

mesonbuild/coredata.py
Fixes #6291 by catching on bad option format
```sh
meson build -Darr=['a','b']
```
should be replaced by `-Darr=a,b`
=> catch improper command line option

run_project_tests.py
It's better to use argparse choices option to check for validity of --only option before going through part of the lengthy script startup process.
Note: I drastically shortened this PR as the "incidental" type annotation refactoring ended up being for another PR.
Speedup: 20x faster to error if non-existent `--only foo` is specified
=> run_project_tests: --only uses argparse choices

docs/markdown/Vala.md
Summary: Add brief description of configuring Vala's preprocessor via the add_project_arguments() function.
I'm learning Vala and had difficulty in configuring Meson to define preprocessor symbols.  Setting the language to 'c' was not obvious to me.
=> Documentation for configuring Vala's preprocessor via Meson

mesonbuild/interpreter.py
Blacklist /dev paths, this fix infinite reconfigure when /dev/stdout is
redirected to a file.
Fixes: #6315.
=> run_command: Do not add dependency on /dev/stdout

mesonbuild/cmake/executor.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/data/CMakeLists.txt, mesonbuild/dependencies/misc.py, mesonbuild/mesonlib.py, test cases/cmake/14 fortran threads/meson.build, test cases/frameworks/1 boost/meson.build, test cases/frameworks/2 gtest/meson.build, test cases/linuxlike/13 cmake dependency/meson.build
In general, CMake uses `project(... LANGUAGE ...)` to make CMake's internals work for non-C languages. To this point, CMake use from Meson has worked for many C/C++ Meson projects because of CMake's assumption of C-language when `project()` is not specified in CMakeLists.txt.
However, general Meson language use of CMake needs CMakeLists.txt `project(... LANGUAGE ...)` to find the library and all arguments needed to link/compile/include. This includes OpenCoarrays 2.8 at least. In that case, COMPILER_LANGUAGE generator is used to select compiler arguments. A standalone example is this CMakeLists.txt at the bottom of this note.
---
this is  just to demonstrate CMake alone using generators instead of if()/elseif() for language-dependent behavior
```cmake
cmake_minimum_required(VERSION 3.7) …
```
=> cmake: add project(... LANGUAGE ...)

docs/markdown/Cross-compilation.md
Meson's documentation about cross-compilation made me finally understand
why the typical confusion about machine names. Thanks, but let's make it
even better. Don't wait until the very end of the section to reveal the
most important information: that machine names are relative. For
suspense we already have TV shows; spill the beans much earlier.
Also fix the first, simplest cross-compilation example: target is
irrelevant.
=> docs: explain cross-compilation names sooner [skip ci]

mesonbuild/cmake/executor.py
probably something to consider making a default for mesonlib/Popen_safe() in general, 
but at least for cmake/executor, using 
```python 
ret = subprocess.run(..., universal_newlines=False, ...)
stdout = ret.stdout.decode(errors='ignore')
```
instead of Popen_safe() avoids Meson crash/traceback when a `dependency(..., method: 'cmake')` search goes wrong, and the compiler or Cmake feed back binary garbage not suitable for .decode() implicit in mesonlib/Popen_safe()
That is, this change allows Meson to simply note the dependency as "not found" instead of crashing Meson.
=> Cmake: popen_safe(..., errors='ignore')

mesonbuild/dependencies/base.py
access(2) tests for X_OK that return true do not always guarantee that
the file is executable.  Instead check the stat(2) mode bits explicitly.
This fixes any builds or installs executed as root on Solaris and
illumos that contain non-executable scripts.
=> dependencies: Fix executable file test on Unix.

ci/azure-steps.yml, docs/markdown/Cross-compilation.md, docs/markdown/Native-environments.md, docs/markdown/howtox.md, docs/markdown/snippets/linker_override.md, mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/mixins/gnu.py, mesonbuild/compilers/mixins/visualstudio.py, mesonbuild/compilers/rust.py, mesonbuild/envconfig.py, mesonbuild/environment.py, mesonbuild/linkers.py, run_project_tests.py, run_unittests.py
This approach is a little different than the previous approach I used of trying to pass all of the arguments passed as <lang>flags to the linker invocation, instead it adds an LD environment variable and an `ld` entry in the cross/native files for setting the linker. This is nice because it allows us to abstract linker selection across different compilers, especially in cases were the compiler doesn't invoke the linker.
There is one drawback to this, which is it doesn't properly handle clang's `--target` argument. That is a much harder problem to solve (and worth solving I think). But will require reworking the way meson sets up compilers and adds command line interfaces. This provides a 99% solution, and doesn't require ripping up the guts of how we add compilers.
This PR still needs to …
=> Add a way to select the dynamic linker meson uses

docs/markdown/Dependencies.md
The example is meant for wxWidgets not Shaderc.
=> docs: Fix wrong example for shaderc dependency [skip ci]

test cases/fortran/20 buildtype/main.f90, test cases/fortran/20 buildtype/meson.build
this can find issues with non-default build options. 
Another PR will be forthcoming to fix what I discovered with this test.
=> ci fortran: add case where buildtype=release and warning_level=3

docs/markdown/IDE-integration.md, docs/markdown/snippets/introspect.md, mesonbuild/mintro.py, run_unittests.py
The protocol is needed for an external test runner to parse the output correctly.
=> mintro: include test protocol in introspection data

mesonbuild/compilers/c.py, mesonbuild/compilers/cpp.py, mesonbuild/mlog.py, run_tests.py, run_unittests.py
Mostly I hate that the CI log is completely full of "ninja < 1.9" warnings, but there's other cases where we messages multiple times when it's not useful. Adding a single tested method for this makes more sense than doing it ad hoc in multiple places.
=> mlog: Add a log_once method and start using it

.github/workflows/lint_mypy.yml, mesonbuild/compilers/mixins/intel.py
intel compiler's defaults are different enough from MSVC and GNU
that it's necessary to set specific defaults for Intel compilers.
This corrects/improves behaviors initially addressed in  #6275,
which introduced some duplicated/conflicting arguments.
Specifically, prior to this PR, unintended behavior included:
* Intel-Cl: optimization was still enabled on `debug` builds
* Intel: clashing -O2 -O3 release arguments unintentionally overriding and duplicated -O0 on debug
on this PR, I was more careful to manually inspect build.ninja across `buildtype` to verify the intended arguments were sent, considering the unique defaults of Intel compilers distinct from GNU/MSVC.
=> intel/intel-cl: bugfix: handle arguments in intel-specific way

test cases/cmake/5 object library/main.cpp, test cases/cmake/5 object library/meson.build, test cases/cmake/5 object library/subprojects/cmObjLib/CMakeLists.txt, test cases/cmake/5 object library/subprojects/cmObjLib/libA.cpp, test cases/cmake/5 object library/subprojects/cmObjLib/libB.cpp, test cases/cmake/6 object library no dep/main.cpp, test cases/cmake/6 object library no dep/meson.build, test cases/cmake/6 object library no dep/subprojects/cmObjLib/CMakeLists.txt, test cases/cmake/6 object library no dep/subprojects/cmObjLib/libA.cpp, test cases/cmake/6 object library no dep/subprojects/cmObjLib/libB.cpp
test cases/cmake/{5,6} are OK with Windows using GCC, since that doesn't link with link.exe, so don't skip that case. 
code quality edits to the tests themselves to avoid compile warnings or failures.
restarted this since #6324 got messed up re: Github, it kept wanting to include prior unrelated commits in the PR.
=> ci cmake: Windows link.exe skip due to symbol issues

mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/cs.py, mesonbuild/compilers/cuda.py, mesonbuild/compilers/d.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/java.py, mesonbuild/compilers/mixins/visualstudio.py, mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, mesonbuild/compilers/rust.py, mesonbuild/compilers/swift.py, mesonbuild/compilers/vala.py, mesonbuild/coredata.py, mesonbuild/environment.py, mesonbuild/linkers.py
Here's a new version, built on top of #6207, because I need so much of the machinery to make this work anyway. It will have the same bugs as 6207 does for the moment but I have tested using both `-fuse-ld=gold` and `--target` with clang and that works.
=> Pass options to linker detection

data/syntax-highlighting/vim/syntax/meson.vim, docs/markdown/Reference-manual.md, docs/markdown/snippets/summary.md, mesonbuild/ast/interpreter.py, mesonbuild/interpreter.py, run_unittests.py, test cases/unit/74 summary/meson.build, test cases/unit/74 summary/subprojects/sub/meson.build, test cases/unit/74 summary/subprojects/sub2/meson.build
This has been requested multiple times in the mesa/xorg community, and
apparently in the GStreamer community as well.
This allows a configuration summary to be printed at the end of the configuring phase.
For example:
```meson
sec1 = {'driver' : 'foobar', 'OS' : 'Linux', 'API' : 1.7}
...
sec2 = {'driver' : 'dive comp', 'OS' : 'Minix', 'API' : 1.1.2}
...
sec3 = {'with' : {'mesa' : true, 'gbm' : false}}
summary(
{'Backend' : 'OpenGL'},
'Server' : sec1,
'Client' : sec2,
'Misc' : sec3,
)
```
Which would print something like:
```txt
Configuration Summary:
Backend = OpenGL
Server:
driver = foobar
OS = Linux
API = 1.7
Client:
driver = dive comp
OS = Minix
API = 1.1.2
Misc:
with = {'mesa : true, 'gbm' : false}
```
Fixes #757
=> Add a summary() function for configuration summarization

mesonbuild/dependencies/base.py, run_unittests.py
When there is more than one path in PKG_CONFIG_PATH. It is almost always
preferred to find things in the order specified by PKG_CONFIG_PATH
instead of assuming pkg-config returns flags in a meaningful order.
For example:
/usr/local/lib/libgtk-3.so.0
/usr/local/lib/pkgconfig/gtk+-3.0.pc
/usr/local/lib/libcanberra-gtk3.so
/usr/local/lib/pkgconfig/libcanberra-gtk3.pc
/home/mesonuser/.local/lib/libgtk-3.so.0
/home/mesonuser/.local/lib/pkgconfig/gtk+-3.0.pc
PKG_CONFIG_PATH="/home/mesonuser/.local/lib/pkgconfig:/usr/local/lib/pkgconfig"
libcanberra-gtk3 is a library which depends on gtk+-3.0. The dependency
is mentioned in the .pc file with 'Requires', so flags from gtk+-3.0 are
used in both dynamic and static linking.
Assume the user wants to compile an application which needs both …
=> PkgConfigDependency: Sort -L flags according to PKG_CONFIG_PATH

mesonbuild/linkers.py
PE DLLs don't work like elf or mach-o, there's no way to define symbols
at run time, they must all be defined as import or export at link time.
As such there's no value in being able to have undefined symbols in
MSVC, nor does meson expose an option to change them
Fixes: #6342
=> linkers: Remove get_allow_undefined_args from link.exe

docs/markdown/Fs-module.md, mesonbuild/modules/fs.py, test cases/common/227 fs module/meson.build
is_samepath better reflects the nature of this function--that files
and directories can be compared.
Also, instead of raising exceptions, simply return False when one
or both .is_samepath(path1, path1) don't exist. This is more
intuitive behavior and avoids having an extra if fs.exist() to go
with every fs.is_samepath()
=> fs: rename samefile => is_samepath

docs/markdown/Compiler-properties.md, docs/markdown/Reference-manual.md, docs/markdown/Reference-tables.md, docs/markdown/snippets/get_linker_id.md, mesonbuild/compilers/compilers.py, mesonbuild/interpreter.py, test cases/common/31 compiler id/meson.build
add method
```meson
meson.get_compiler(...).get_linker_id() 
```
this can be useful for if/elif where linker behaviors must be considered.
E.g. linking between languages where a particular linker may be known to fail,
rather than doing if/elif on operating system and compiler.get_id(), as in #6347
Since many compilers can choose from multiple linkers in an OS-dependent way, and linker errors can be confusing to end users, this allows program developers using Meson to handle corner cases in ways not previously possible, with more obvious if/elif.
instead of
```meson
if meson.host_machine() == 'windows' and comp.get_id() != 'gcc'
```
now:
```meson
if comp.get_linker_id() != 'link'
```
which signals to meson.build readers more specifically what the if/elif logic is at first glance.
=> add compiler.get_linker_id() method

mesonbuild/dependencies/coarrays.py, mesonbuild/dependencies/hdf5.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/mpi.py, mesonbuild/dependencies/scalapack.py, test cases/fortran/13 coarray/meson.build, test cases/frameworks/25 hdf5/meson.build, test cases/frameworks/26 netcdf/meson.build, test cases/frameworks/30 scalapack/meson.build
this refactors the following dependencies to use the Meson dependency(..., 'methods': ...) properly. Before, these dependencies were not able to use methods, which is a deficiency.
* coarray
* mpi
* hdf5
* netcdf
An upcoming PR that increases the power of CMake to find dependencies in general depends on having Meson methods implemented properly for dependencies as done here.
=> dependencies: refactor {coarray,mpi,hdf5,netcdf} to use dependency(.., methods: ...)

mesonbuild/dependencies/base.py
fixes bug introduced by #6228 -- not checking length of string before indexing. With certain pkgconfig files, say MSYS2 HDF5, there are zero length strings passed. This causes Python traceback to be emitted as Meson crashes.
In any case, before indexing a string from the world, the length should be checked.
=> bugfix: check len before index re #6228

mesonbuild/dependencies/misc.py
late merge request: This fixes an obvious error I made in #6355 in the logic for finding NetCDF with PkgConfig--I didn't stop the search if NetCDF was found with PkgConfig. This causes intermittent failures in finding NetCDF for Fortran, and was probably behind the NetCDF CI failures.
i.e. without this simple fix, 0.53.0 is *worse* than 0.52 for NetCDF
=> bugfix: netcdf pkgconfig stop if found

mesonbuild/cmake/interpreter.py, mesonbuild/cmake/traceparser.py, test cases/cmake/16 threads/main.cpp, test cases/cmake/16 threads/meson.build, test cases/cmake/16 threads/subprojects/cmMod/CMakeLists.txt, test cases/cmake/16 threads/subprojects/cmMod/cmMod.cpp, test cases/cmake/16 threads/subprojects/cmMod/cmMod.hpp, test cases/cmake/16 threads/subprojects/cmMod/main.cpp, test cases/cmake/2 advanced/meson.build, test cases/cmake/2 advanced/subprojects/cmMod/CMakeLists.txt, test cases/cmake/3 advanced no dep/meson.build, test cases/cmake/3 advanced no dep/subprojects/cmMod/CMakeLists.txt
This is necessary for static libraries since the CMake file API does not add link flags here.
=> cmake: Use trace for missing link flags (fixes #6386)

mesonbuild/environment.py
Which wouldn't call the function to detect c_args and friends.
@jpakkane, if we could get this in before 0.53 happens that would be great.
=> environment: Fix detection of icc on macOS

docs/markdown/Wrap-dependency-system-manual.md
Most of the OSes (even counting all Linux distos as one) Meson supports actually do have package managers, and at least some of them are not harder (if not saying opposite) to use than Linux ones.
Here is the state of OSes mentioned on https://mesonbuild.com/Reference-tables.html:
| OS | has package manager? |
| -- | -------------------- |
| cygwin | yes |
| darwin | no |
| dragonfly | yes |
| emscripten | no |
| freebsd | yes |
| gnu | third-party |
| haiku |  no |
| linux |  yes/no |
| netbsd |  yes |
| openbsd |  yes |
| windows | no |
| sunos | yes |
=> [skip ci] Use more up-to-date wording regarding package managers

mesonbuild/dependencies/hdf5.py
A trivial mistake that causes Meson to crash if HDF5 pkg-config files not present.
=> bugfix: hdf5 dependency: make sure variable is always defined

data/syntax-highlighting/vim/ftdetect/meson.vim
wrap files are ini syntax, and vim has support for this via the `dosini`
syntax type.
=> Add .wrap file syntax detection for vim

mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/misc.py, test cases/frameworks/31 curses/main.c, test cases/frameworks/31 curses/meson.build
fixes #6096.
Didn't use CMake because Curses is a real corner-case for CMake that
would require Curses-specific enhancements to Meson's CMake interface.
=> dependency: add curses

mesonbuild/dependencies/base.py, run_unittests.py
On MSYS2 and MSYS, Python reads HOME instead of USERPROFILE, which
gets the path wrong.
Serves me right for not writing a test!!
=> find_program: Always use USERPROFILE instead of HOME

test cases/common/52 custom target/depfile/dep.py, test cases/common/53 custom target chain/my_compiler.py, test cases/common/53 custom target chain/my_compiler2.py, test cases/common/53 custom target chain/usetarget/subcomp.py, test cases/common/99 manygen/subdir/manygen.py, test cases/linuxlike/14 static dynamic linkage/verify_static.py, test cases/unit/11 cross prog/some_cross_tool.py, test cases/unit/11 cross prog/sometool.py, test cases/unit/39 python extmodule/blaster.py, test cases/unit/61 identity cross/build_wrapper.py, test cases/unit/61 identity cross/host_wrapper.py, test cases/windows/8 find program/test-script
The unversioned command is deprecated and removed from some distributions
=> Use python3 in some tests which were still using python

docs/markdown/Reference-tables.md
Commit 1404f404 (#4744) introduced this typo, making the link not jump to the correct section when clicked.
(Perhaps there should be a script in CI that checks for dangling Markdown links?)
=> docs: Fix typo in link

.github/workflows/ci_frameworks.yml, mesonbuild/dependencies/ui.py, test cases/frameworks/4 qt/meson.build, test cases/frameworks/4 qt/meson_options.txt, test cases/frameworks/4 qt/q5core.cpp
Don't fail with 'KeyError: QMAKE_XSPEC' if `qmake -query` doesn't report QMAKE_XSPEC. (Seen with Qt 4.8.7)
=> Fix dependency('qt') crash with old Qt on OSX

azure-pipelines.yml, ci/azure-steps.yml, mesonbuild/backend/vs2010backend.py, mesonbuild/linkers.py, run_unittests.py, test cases/windows/16 gui app/gui_app_tester.py, test cases/windows/16 gui app/meson.build
commit 12cb82307f2016e19a2634a2081a9723acd27319:
```
linkers: Clarify a comment about rspfiles
```
commit 3a05548cdd381b0ad99e29050f73337d8c2fcfb3:
```
linkers: Accept both str and List[str] for _apply_prefix
Simplifies some usage.
```
commit 360e1cdd2350182b0636d2251efe50291f8806dd:
```
vs: Write checksums in PE binaries (DLLs and EXEs)
This is needed for detecting data corruption, and its absence (or
an incorrect value) is also used as a hint by anti-viruses that the
binary may be malware.
Flag is only supported by MSVC `link.exe`, not `lld-link.exe`
```
https://docs.microsoft.com/en-us/cpp/build/reference/release-set-the-checksum
commit e017147d2199a85e1c6664fb8d8f39f32a389e8b:
```
tests: Add a unit test for checksums
Adds a CI dependency on the `pefile` python module.
```
commit …
=> Visual Studio: Write out DLL/EXE checksums

docs/markdown/Cross-compilation.md, docs/markdown/snippets/pkg_config_libdir.md, mesonbuild/dependencies/base.py, mesonbuild/envconfig.py, run_unittests.py
In order to unify the use of sysroot in the cross-file,
the pkg_config_path can now be passed directly in the file.
=> envconfig: add pkg_config_libdir property

cross/linux-mingw-w64-32bit.txt, cross/ubuntu-armhf.txt, docs/markdown/howtox.md, mesonbuild/envconfig.py, mesonbuild/environment.py, run_unittests.py, test cases/linuxlike/15 ld binary/meson.build
The rust code is ugly, because rust is annoying. It doesn't invoke a
linker directly (unless that linker is link.exe or lld-link.exe),
instead it invokes the C compiler (gcc or clang usually) to do it's
linking. Meson doesn't have good abstractions for this, though we
probably should because some of the D compilers do the same thing.
Either that or we should just call the c compiler directly, like vala
does.
This changes the public interface for meson, which we don't do unless we
absolutely have to. In this case I think we need to do it. A fair number
of projects have already been using 'ld' in their cross/native files to
get the ld binary and call it directly in custom_targets or generators,
and we broke that. While we could hit this problem again names like
`cld` and `cppld` are far …
=> environment: Replace LD with <LANG>LD

run_unittests.py
pkgconf automatically prunes "system library paths" from its output. The system library path defaults to the libdir passed to its configure script. On a 64-bit system, this is typically `/usr/lib64`. So, if `-L/usr/lib64` appears in the Libs section, it will be pruned from the output of pkg-config --libs.
The pc files generated for this test contain something like this:
libdir=/usr/lib
Libs: -L${libdir} ...
pkgconf may not consider /usr/lib to be a system library path, so it is not pruned as the test expects. To work around this, override the compiled-in list of paths via the PKG_CONFIG_SYSTEM_LIBRARY_PATH environment variable.
Note that the original `pkg-config` program from freedesktop.org includes `/usr/lib` as a system library path by default. The behavior of …
=> test_pkgconfig_gen_deps: set PKG_CONFIG_SYSTEM_LIBRARY_PATH=/usr/lib

mesonbuild/mesonlib.py, mesonbuild/msubprojects.py, mesonbuild/wrap/wrap.py
commit e1c0ee5ddbd6f0a9455bc98f10f5a1bfc6b98c78:
```
wrap: Use uppercase for global constants
This makes things much clearer and follows PEP8.
```
commit 10f205130e6d68c59e27b30326853c562296477e:
```
wrap: Look for git only once at startup
No need to repeatedly call `shutil.which`.
```
commit 1d366dace68ef241f42d3f6e01e6ca4f46f8efe9:
```
wrap: Always use a wrapper for running git
We need this for the next commit.
```
commit 793fa60f79e82f5fab6743bd96fcd71253484b5f:
```
wrap: Redirect stdin to DEVNULL when calling git
Without this git messes up the console and ANSI colors stop working on
Windows inside cmd.exe. Also add the same to all git calls. 
```
commit 8411b0559dc11fb55c18bcb0252b289b08f40bbe:
```
wrap: Re-set the console mode after calling git
`git submodule update --recursive` …
```
=> Fix git colors on windows again and again

.github/workflows/unusedargs_missingreturn.yml, mesonbuild/cmake/__init__.py, mesonbuild/cmake/interpreter.py, mesonbuild/dependencies/base.py, test cases/linuxlike/13 cmake dependency/cmake/FindSomethingLikeZLIB.cmake, test cases/linuxlike/13 cmake dependency/meson.build
The default behavior for project() is to add the C and CXX languages. Currently, only the C language is added if both c and cpp languages are used in meson.
=> cmake: Always add available languages if no language is specified (fixes #6441)

.github/workflows/os_comp.yml, mesonbuild/build.py, mesonbuild/compilers/compilers.py, run_project_tests.py, run_unittests.py, test cases/cmake/5 object library/main.cpp, test cases/cmake/6 object library no dep/main.cpp, test cases/common/222 source set realistic example/meson.build, test cases/fortran/12 submodule/meson.build, test cases/frameworks/1 boost/meson.build, test cases/frameworks/6 gettext/meson.build, test cases/frameworks/7 gnome/meson.build
Explicitly use the type instead of the string `'NotImplemented'` which still works with Python 3.5.2
Fixes https://github.com/mesonbuild/meson/issues/6427.
=> typing: Fix compatibility with Python 3.5.2

test cases/cuda/11 cuda dependency (nvcc)/version_reqs/prog.cu
Getting the runtime version fails when no devices are present.
=> Fix CUDA test without devices.

docs/markdown/Release-procedure.md
This is highly influenced by the release process that mesa uses and we've had a great deal of success with. It allows normal development to continue while we work out the bugs in stable, while signaling to distros and users that we would like them to start testing.
Fixes #6456
=> docs: Update the release procedure to include release candidates

mesonbuild/interpreter.py, run_unittests.py
When a dependency is required, not found on the system, and its fallback
is disabled with --wrap-mode=nofallback, meson should abort instead of
returning not-found.
=> Fix required dependency() not failing when wrap-mode=nofallback

test cases/common/219 source set configuration_data/all.h, test cases/common/219 source set configuration_data/f.c, test cases/common/220 source set dictionary/all.h, test cases/common/220 source set dictionary/f.c, test cases/common/68 build always/version.h, test cases/common/69 vcstag/tagprog.c
With GCC 10, -fno-common becomes default behavior, meaning that any
subtly-broken code will be broken not so subtly anymore.
This commit changes the linkage to variables declared in headers to
external and, where needed, adds additional definitions in other
compilation units.
=> tests: Prevent multiple-definition of symbols

docs/markdown/Dependencies.md, docs/markdown/Reference-manual.md, docs/markdown/Subprojects.md, mesonbuild/build.py, mesonbuild/dependencies/base.py, mesonbuild/interpreter.py, mesonbuild/modules/gnome.py, test cases/common/218 dependency get_variable method/meson.build
In mesa there's an annoying corner case of using a wrap for llvm (using binary wraps seems to be pretty common on windows), there's no good way to pass the equivalent of cmake or config-tool variables from the subproject to the parent. Currently we call subproject.get_variable() a bunch of times. But this is annoying and requires special casing.
Instead of doing that it would be nice to just be able to add variables to the declare_dependency() object, and query them via `dep.get_variable()` like cmake and config-tool variables.
=> Add ability to set and query arbitrary variables on declare_dependency objects 

mesonbuild/cmake/executor.py, mesonbuild/cmake/interpreter.py, mesonbuild/cmake/traceparser.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/dev.py, run_project_tests.py
This moves most of the execution code from the CMakeInterpreter into CMakeExecutor. Also, CMakeTraceParser is now responsible for determining the trace cmd arguments.
Also, support for `--trace-redirect` is added, which was introduced in [CMake 3.16](https://cmake.org/cmake/help/latest/release/3.16.html#command-line).
=> cmake: Refactor CMakeExecutor and CMakeTraceParser

ghwt.py, mesonbuild/coredata.py, mesonbuild/wrap/wraptool.py
This is what the conceptual model we have always stated for "ini" files, so let's be explicit. The only breakage potential ties to #6517 but as trying to use interpolation does not currently work because of the quotes, this should not break anything that is not already broken.
=> Always disable interpolation for ini parsers.

mesonbuild/compilers/c.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/mixins/elbrus.py, mesonbuild/environment.py, run_unittests.py
There were some code changes in class hierarchy and constructor arguments (e.g. missing `defines`), so support has to be updated.
I wonder, what is that `defines` argument for, and why it was removed from C compilers' constructors, but still remains in C++ compilers' constructors? Somehow it feels like breaking universality.
Also found some problems with ninja (see commit 51ac90a): sometimes subprojects summary goes before project summary, so this breaks that unit test. I have encountered it one time on Intel, and one time on Elbrus, but now everything seems to be ok.
Also I figured out that for successful pass of unit tests, the following stuff should be installed:
* pkg-config >= 0.29 (by default Elbrus has 0.22)
* libgirepository1.0-dev, rustc, gfortran, gobjc (on Ubuntu and other …
=> Elbrus support is broken in 0.53.0, so fixing it

mesonbuild/compilers/c.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/mixins/visualstudio.py
The first patch is some refactoring/cleanup I've wanted to do for a while, while the second fixes the actual bug.
=> Fix debug arguments to Clang-CL

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/backend/vs2015backend.py, mesonbuild/backend/vs2017backend.py, mesonbuild/backend/vs2019backend.py, mesonbuild/backend/xcodebackend.py, mesonbuild/interpreter.py, mesonbuild/mintro.py, mesonbuild/msetup.py
Use the already existing list of buildsystem files in the interpreter, instead of relying on `os.walk()`.
This PR also includes some slight refactoring, to set `self.interpreter` in the constructor of the Backend class.
=> mintro: use interpreter data for buildsystem-files (fixes #6390) 

mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/boost.py, mesonbuild/dependencies/coarrays.py, mesonbuild/dependencies/cuda.py, mesonbuild/dependencies/dev.py, mesonbuild/dependencies/hdf5.py, mesonbuild/dependencies/misc.py, mesonbuild/dependencies/mpi.py, mesonbuild/dependencies/platform.py, mesonbuild/dependencies/scalapack.py, mesonbuild/dependencies/ui.py, mesonbuild/modules/pkgconfig.py, mesonbuild/modules/python.py, run_unittests.py, test cases/frameworks/20 cups/meson.build
This adds a more compact, explict method for dependencies with more than one way to be found, especially when one or more of those methods are standard, built in methods like cmake and pkg-config. Instead of having a special `_factory` method in the dependency, a new generic `DependencyFactory` has been added that can handle many cases, or a specific factory function can be written for more specialized cases. I've included a number of instances of both.
I've converted most instances that make sense, although there are a few more that could use conversion I haven't gotten to: Qt, scalapack, and mpi (maybe a couple of others I forgot about). I haven't had a chance to test this on mac or windows yet, so it may still have some problems.
@scivision, I've touched several of the dependencies …
=> Add a proper dependency factory API for dependencies with more than one discovery method

run_unittests.py
Fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950020
=> Skip ld tests if no compiler installed.

mesonbuild/dependencies/base.py, mesonbuild/dependencies/ui.py
There is a comment saying we do it because we used to do it. But it's
wrong and lead to using system library when cross compiling.
Factor out the code we use to find pkg-config, because it is the same
use-case.
=> Qt5: Do not use system qmake if not specified in cross file

CODEOWNERS
Following proposal in #6485 we would like to delegate maitainership
of parts of the Meson project (modules) to selected volunteers.
=> Add CODEOWNERS file [skip ci]

cross/ccrx.txt, mesonbuild/compilers/c.py, mesonbuild/compilers/mixins/arm.py, mesonbuild/compilers/mixins/ccrx.py, mesonbuild/linkers.py
Fixed Renesas RX Family compiler to work with latest meson, updated cross-file, fixed assembly file use
=> Fix Renesas Compiler

mesonbuild/coredata.py, run_project_tests.py, run_unittests.py, test cases/common/105 testframework options/meson.build, test cases/failing/38 libdir must be inside prefix/meson.build
fixes #6395
The unit tests needed to be updated to accurately reflect Windows path behavior. The prior method was fine for Posix-like filesystems, but conflicted with the distinct behavior of Windows paths respected in Python pathlib. This issue creeps up from time to time as we continue to implement pathlib inside Meson, this is just one step in that transition.
d31cbf6a was just an obvious change for unreachable/dead code I happened across.
I would suggest squashing these commits if desired, either way is fine. I just left them unsquashed to show the various steps needed to remove always-Posix assumptions from the relevant code.
=> Bugfix: sanitize_dir: use pathlib to handle case-insensitive filesystems

.travis.yml, run_cross_test.py, run_project_tests.py, run_tests.py
Refactor and simplify cross-testing in CI:
* Make the crossfile selection part of the CI job configuration (so we can more easily add more CI jobs for different cross-toolchains)
* Make the `platform_fix_name()`  machinery for toolchains which don't have gcc-like filename conventions also apply to cross-toolchain testing
=> Refactor CI cross-testing

docs/markdown/fallback-wraptool.md, ghwt.py
New feature:
- Users may specify a branch to download a specific version of a project.  If a branch is not specified the original behavior remains.  If the specified branch does not exist, the script prints valid branch names and exits with an error.
Bug fixes:
- Subprojects now go to the subproject directory specified in the wrap file (if it exists) instead of always going to the default directory
- Fixed hash report swap if download did not match expected
=> ghwt: allow user to specify branch

docs/markdown/Dependencies.md, mesonbuild/dependencies/dev.py
These are just a few small things I noticed while doing the big dependency API refactor, but that didn't belong in that series.
=> Small cleanups for the LLVM dependency class

mesonbuild/dependencies/misc.py
Otherwise it tries to link with the C bindings and fails. This is why
the test is broken on archlinux.
@mensinda 
@scivision
=> dependencies: netcdf always look for netcdf-fortran for fortran

CODEOWNERS
I volunteer to maintain the AST code.
=> Add mesonbuild/ast to CODEOWNERS [skip ci]

mesonbuild/environment.py
Only detect a compiler as icl if the name is "icl" or "icl.exe"
Fixes #6543
=> environment: Be stricter about detecting icl

mesonbuild/environment.py
Otherwise there's a stack traced caused by use-before-assignment
=> environment: Handle cases of no cs compiler being installed correctly

ci/azure-steps.yml
This fixes the azure failure seen for commit https://github.com/mesonbuild/meson/commit/15ab30383ecc3fe124f3aed8aa5b9ddb1b5bbbc7
=> Don't fail in setup on azure when commit message contains an equals sign

docs/markdown/Pkgconfig-module.md, docs/markdown/snippets/uninstalled-pkgconfig.md, mesonbuild/modules/pkgconfig.py, run_unittests.py, test cases/common/47 pkgconfig-gen/dependencies/main.c, test cases/common/47 pkgconfig-gen/dependencies/meson.build, test cases/common/47 pkgconfig-gen/meson.build
=> pkgconfig: Generate -uninstalled.pc files

mesonbuild/dependencies/base.py
#6586 
fix DubDependency._find_right_lib_path
if default_path is path to library and directory  of lib don't have subdirectory '.dub/build' -> return default_path
=> Fix import dependency from dub

docs/markdown/Fs-module.md, docs/theme/extra/templates/navbar_links.html, mesonbuild/modules/fs.py, test cases/common/227 fs module/meson.build
...more functions that those dev'ing on or for Windows can find handy.
These address issues for those needing to make complex library stacks just work on windows and unix-like systems without mucking around deep inside Meson. 
Specifically:
* expanduser: this allows users to in a cross-platform way specify directories under their home directory. Particularly important where admin/sudo access is not possible. Handy to use with #6161 for example.
* is_absolute: a lightweight check to see if meson.current_source_dir() or meson.source_root() should be prepended, if desired. 
* as_posix: facilitates comparing path strings in a cross platform way, and passing parameters to run_program() that need to be in posix-path forward slashes.
* stem: the last part of the path, dropping the last part of …
=> fs: add methods as_posix, is_absolute, expanduser, stem

docs/markdown/Dependencies.md, docs/markdown/snippets/zlib_system_dependency.md, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/dev.py, test cases/common/228 zlib/meson.build
This adds a system depenedency for zlib, so that platforms that ship zlib as part of the base os (macOS, FreeBSD, and probably other BSDs but I don't have VMs for all of them).  This allows zlib to be found without the use of cmake of pkg-config, which is especially helpful on macOS.
This has been updated on top of #6443
Fixes #2654
=> Add a "system" dependency for zlib

mesonbuild/mdist.py
Debian's `lintian` checker complaints when upstream tarballs contain an
`.hgtags` file.
This excludes `.hg[a-z]*`.  This is mostly consistent with the git
handling in del_gitfiles() which deletes `.git*`.  `hg archive --help` shows
an example of `-X ".hg*"`.  However, instead of `.hg*`, I have used
`.hg[a-z]*` to keep the automatically added `hg_archival.txt`.  This file
may be useful to link the tarball to the Mercurial revision for either
manual inspection or in case any code interprets it for a `--version` or
similar.
This also excludes `.hgignore` and other things like `.hgflow`, which seems
desirable.
Fixes #6575
=> Exclude .hg* from dist tarballs

test cases/python3/3 cython/libdir/meson.build
The Cython generation depends on cstorer.pxd as well, so add that as
dependency.
A detection by cython itself [does not exist](https://github.com/cython/cython/issues/1214).
=> test cases/python3/3 cython: fix dependency files

mesonbuild/minstall.py
When `--only-changed` is passed, we only want to know about files that were newly-installed. Everything else is noise. The full list can always be found in `install-log.txt` anyway. Sample output:
```
ninja: Entering directory `.'
ninja: no work to do.
Preserved 667 unchanged files, see meson-logs\install-log.txt for the full list
```
=> minstall: Make --only-changed less verbose

mesonbuild/interpreter.py, test cases/common/14 configure file/check_file.py
If we always copy files over without timestamps, we're forcing a (probably unnecessary) rebuild. Also include a test for this.
=> configure_file: Also copy timestamps to avoid useless rebuilds

.github/workflows/os_comp.yml, ci/ciimage/fedora/Dockerfile, ci/ciimage/fedora/install.sh, ci/ciimage/opensuse/Dockerfile, ci/ciimage/opensuse/install.sh, run_project_tests.py, test cases/frameworks/20 cups/meson.build
I have tried to fix as many test failures as possible on these images, however, I didn't manage to fix all of them. Specifically the `hdf5`, `netcdf`, `mpi` and `scalapack` tests just won't work on Fedora and OpenSUSE. Unfortunately, I don't know enough about these dependencies to fix them (ping @scivision, @dcbaker).
The docker images are hosted here: https://hub.docker.com/u/mensinda
=> ci: Add Fedora and OpenSUSE images

docs/markdown/Release-notes-for-0.53.0.md, docs/markdown/howtox.md
We missed this in https://github.com/mesonbuild/meson/pull/6457
@jpakkane we will need to regenerate the website after merging this so that the incorrect documentation in the release notes is fixed: https://mesonbuild.com/Release-notes-for-0-53-0.html#generic-overrider-for-dynamic-linker-selection
=> docs: Update documentation about linker selection

mesonbuild/cmake/executor.py
No test, since this would require the absence of a C++ compiler.
=> cmake: Fix crash when no C++ compiler is not installed (fixes #6559)

mesonbuild/linkers.py
When using Clang compiler and MSVC linker (at least), linker arguments in compiler command-line must be passed via `-Wl`, otherwise Clang will reject the entire command with an error like this:
```
clang: @lib/XXX.rsp
clang: error: no such file or directory: '/OPT:REF'
```
=> msvc: add prefix to build type arguments

mesonbuild/mesonlib.py, mesonbuild/mlog.py
Otherwise there's a high likelihood that some program run by us will mess up the console settings and break ANSI colors. F.ex., running `uname` in the Visual Studio 2019 x86 developer prompt using `run_command()` does this.
=> mesonlib: Set stdin to DEVNULL for all programs run by us

mesonbuild/dependencies/base.py, mesonbuild/interpreter.py
This leads to better version parsing. An concrete example use case is
llc. When invoking llc with "--version", the output is
```
LLVM (http://llvm.org/):
LLVM version 9.0.1
...
```
The old version parsing recognizes the dot in the first line as version.
This commit also tries to adapt the two regexes to each other.
Reported-by: Björn Fiedler <fiedler@sra.uni-hannover.de>
=> version parsing: match only when version starts with a number

docs/markdown/Python-module.md, mesonbuild/modules/python.py
Also update the documentation.
Fixes https://github.com/mesonbuild/meson/issues/6470
=> modules/python: Do not error out if positional args are passed

mesonbuild/mdist.py
commit c90cdb1de238f6860688881256694a6a307ebcec:
```
mdist: Don't delete builddir on dist failure
```
Closes https://github.com/mesonbuild/meson/issues/1976
commit 4b0dae15a8ba679c447d94ff6195e837fa78c1a3:
```
mdist: Use windows_proof_rmtree when deleting
```
CC: @matthiasclasen, this is what you were seeing the other day.
=> mdist: Don't delete temporary dist check dirs on failure

mesonbuild/linkers.py
=> Don't pass --allow-shlib-undefined to lld if it's not supported

mesonbuild/linkers.py
There was a particularly old MR merged, from before the typing -> T
standardization in meson.
=> linkers: typing -> T fixup

docs/markdown/Build-options.md, docs/markdown/Reference-manual.md
Following discussion with @xclaesse on IRC.
=> docs: Improve visibility for `.enabled()` etc., add example

docs/markdown/CMake-module.md, mesonbuild/modules/cmake.py, test cases/cmake/1 basic/meson.build, test cases/cmake/9 disabled subproject/meson.build
Otherwise it's impossible to figure out what happened with `cmake.subproject(..., required : false)`. Also, normal subprojects have this, so not having it is very strange.
=> Add .found() method to cmakesubproject

mesonbuild/coredata.py
`meson setup --debug` puts a bool object in cmd_line_options dictionary
that we have to convert to string.
Fixes: #6646
=> coredata: Fix crash when cmd_line_options contains booleans

docs/markdown/Dependencies.md
It should be a `##` heading, not a `###` heading.
Also make heading label consistent with the others.
=> docs: Fix Dub section being inside CMake section

docs/markdown/Pkgconfig-module.md, docs/markdown/snippets/pkgconfig_dataonly.md, mesonbuild/modules/pkgconfig.py, run_unittests.py, test cases/common/47 pkgconfig-gen/installed_files.txt, test cases/common/47 pkgconfig-gen/meson.build
This allows users to disable writing out the inbuilt variables to
the pkg-config file as they might actualy not be required.
https://gitlab.freedesktop.org/wayland/weston/issues/269 is a
great example of this.
Fixes #4011
=> Introduce dataonly for the pkgconfig module

mesonbuild/msubprojects.py
Fixes https://github.com/mesonbuild/meson/issues/6651
=> msubprojects: We return a string from git() now

docs/markdown/Reference-tables.md, mesonbuild/compilers/compilers.py, mesonbuild/environment.py, mesonbuild/linkers.py, run_unittests.py
The documentation leaves out a lot of possible values, and is wrong in a number of cases.
On the other end calling `meson.get_compiler('java').get_linker_id()` would cause an uncaught python exception.
=> Fix `compiler.get_linker_id` and documentation

mesonbuild/compilers/compilers.py, run_unittests.py
`-L` and `-headerpad_max_install_names` are both linker arguments that are commonly passed in CFLAGS too.
Closes https://github.com/mesonbuild/meson/issues/6294
Also remove an unused variable in the unit tests.
=> macOS: Remove more unused linkerlike args

.github/workflows/lint_mypy.yml, .github/workflows/os_comp.yml, azure-pipelines.yml, ci/azure-steps.yml, ci/ciimage/eoan/Dockerfile, mesonbuild/dependencies/boost.py, run_project_tests.py, test cases/frameworks/1 boost/meson.build, test cases/frameworks/1 boost/meson_options.txt, test cases/frameworks/1 boost/test_matrix.json, test cases/frameworks/1 boost/unit_test.cpp, tools/boost_names.py
This PR significantly improves the handling of the boost library tags and also ensures that the found libraries are always compatible (have the same ABI tag). The current setup can also be extended to filter for additional features (static linking with the runtime, etc.).
Additionally, BOOST_ROOT is better supported (it is now guaranteed that all found files belong to a single root directory).
Finally, `boost.py` is now fully annotated (and checked with mypy).
=> boost: System dependency rewrite

tools/cmake2meson.py
cmake2meson would break with cmake statements like "if((A STREQUAL x) AND (NOT (B STREQUAL y)))" because it can't handle such nesting.  The "elseif" handling logic was even more simplistic, whereas it could reuse the if') logic.  This PR takes care of both problems.
=> cmake2meson fix if nesting

ci/azure-steps.yml, docs/markdown/snippets/ninja_version_bump.md, mesonbuild/backend/ninjabackend.py, mesonbuild/compilers/compilers.py, mesonbuild/environment.py, mesonbuild/linkers.py, mesonbuild/scripts/symbolextractor.py, mesonbuild/templates/cpptemplates.py, mesonbuild/templates/ctemplates.py, mesonbuild/templates/cudatemplates.py, mesonbuild/templates/dlangtemplates.py, mesonbuild/templates/fortrantemplates.py, mesonbuild/templates/javatemplates.py, mesonbuild/templates/objcpptemplates.py, mesonbuild/templates/objctemplates.py, mesonbuild/templates/rusttemplates.py, run_tests.py, run_unittests.py, test cases/common/149 recursive linking/3rdorderdeps/meson.build
commit 431283b35dff5b43ecc65fe19ae581b3c6d8b9be:
```
symbolextractor: Correctly filter undefined symbols on macOS
-g is --extern-only and -P is --format=posix. We were missing
--defined-only for some reason, which we pass to `nm` on Linux.
This avoids having to manually filter later.
```
commit 6fe7af58091f0cb9c7a4c41e6f714d5a8e9c9ad7:
```
symbolextractor: Print a warning if required tools not found
Also write out a dummy symbols file if the tool wasn't found or didn't
work instead of just spewing an exception.
```
commit 901bbc36d902c8146482295827e5464070bbf898:
```
symbolextractor: Support passing arguments to tools
This is how we parse all env vars for tools in Meson. Do the same here
too for consistency.
```
commit feb82e0f0f365d66199d697f1d99e109e2c6a700:
```
symbolextractor: Add …
```
=> Implement symbolextractor on windows + some cleanups/fixes

azure-pipelines.yml
This stopped being tested when the VS2015 images were removed from Azure.
=> azure ci: Test x86 Visual Studio builds again (for 0.53)

azure-pipelines.yml
This was dropped when the VS2015 images were removed from Azure.
=> azure ci: Test x86 Visual Studio builds again

mesonbuild/modules/gnome.py
Because GOI must first run and scan a binary when creating .gir files, cross-compilation is quite tricky! Mainly because if the binary is cross-compiled, you would not typically be able to run or scan a cross-compiled binary from the host system. Because of this significant limitation, both Buildroot and Openembedded have decided to use several wrappers of which runs the native scanner using qemu to create the binaries. These wrappers live in the staging directory.
Currently, meson hard-codes the paths of these utilities, which results in cross-compiled environments running the host versions of these tools instead of the wrappers installed in the staging directory.
GObject-introspection provides the appropriate paths to these utilities via pkg-config, so it would be best to use the …
=> gnome.py: Determine g-ir-scanner and g-ir-compiler paths from pkgconfig

mesonbuild/modules/gnome.py
Currently, giscanner and the gicompiler paths are only scanned via pkg-config
if they are first found in the host path.
Add an else statement to fix this oversight.
=> mesonbuild/modules/gnome.py: Fix giscanner and gicompiler logic

run_unittests.py
The old guidance from the python foundation was that "python" should point to 2.x, and that when 2.x EOLs that "python" should go away, that guidance has changed to "python" should now point to either "python2" or "python3". Given that we need to update some tests. This is complicated by the fact that macOS hasn't been updated, it still only has a "python" binary that is python2
I've also tried to update some of the "do you have python2" checks to be more generic.
=> Fix python2 rename

docs/markdown/External-commands.md, docs/markdown/Release-notes-for-0.50.0.md, docs/markdown/Unit-tests.md
We should probably enable fatal warnings
=> doc: fix link warnings

test cases/linuxlike/14 static dynamic linkage/verify_static.py
Update the expected output from nm to match changes in binutils 2.34.
=> Fix 'linuxlike/14 static dynamic linkage' on Cygwin

mesonbuild/environment.py
The 0.53.2 test suite has a new failure:
File "run_project_tests.py", line 1024, in <module>
detect_system_compiler()
File "run_project_tests.py", line 964, in detect_system_compiler
comp = env.compiler_from_language(lang, MachineChoice.HOST)
File "/build/meson/src/meson-0.53.2/mesonbuild/environment.py", line 1565, in compiler_from_language
comp = self.detect_cuda_compiler(for_machine)
File "/build/meson/src/meson-0.53.2/mesonbuild/environment.py", line 1131, in detect_cuda_compiler
linker = CudaLinker(compiler, for_machine, 'nvlink', CudaCompiler.LINKER_PREFIX, [], version=CudaLinker.parse_version())
File "/build/meson/src/meson-0.53.2/mesonbuild/linkers.py", line 963, in __init__
super().__init__('nvlink', *args, **kwargs)
TypeError: __init__() takes …
=> environment: Fix construction of CudaLinker

mesonbuild/environment.py
Mips architectures may have `el` on the end, to differentiate the little
endian from the big endian variants. We don't encode endianness in the
cpu names, so ensure we've stripped that.
Fixes #6655
=> environment: Strip 'el' from the end of mips architectures

mesonbuild/build.py
Actually `get_clink_dynamic_linker_and_stdlibs()` in `mesonbuild/build.py` returns a `Compiler`, but the return value is used in name of `linker` everywhere. Hard to fix further, so I added some comments useful for debugging and refactoring later.
=> Fixed msvc style linker detecting bug on windows.

test cases/failing/19 target clash/meson.build, test cases/failing/71 invalid escape char/meson.build, test cases/failing/81 framework dependency with version/meson.build, test cases/failing/86 dub libray/meson.build, test cases/failing/87 dub executable/meson.build, test cases/failing/88 dub compiler/meson.build
Fix various faiiling-meson tests so they are actually exercising the intended code-paths and failing in the expected way.
A mechanism like that proposed in #6620 is needed to prevent future occurences of this class of problem.
=> Fix various failing-meson tests

.github/workflows/lint_mypy.yml, mesonbuild/mlog.py
There were two things mypy was warning about:
1) it doesn't understand hasattr()
2) It was possible for mlog.{error,warning,deprecation} to get passed
multiple values for the once keyword argument.
=> mlog: fix remaining mypy errors and add to mypy check

mesonbuild/compilers/compilers.py
With this commit, 2 performance bottlenecks are resolved.
- Caching the result of can_compile removes 11s of efl configure time
- Using a lookup dict instead of a list is also speeding the ninja generation up by several seconds. Additionally, using the knowledge if this flag is in pre or post, is shaving off a few seconds of runtime.
Additionally, the usage of --profile-self is fixed in this commit.
=> meson: performance optimize

mesonbuild/coredata.py
As the interpreter reinitialize the coredate builtins, need to call
again libdir_cross_fixup
=> coredata: init_builtins should always call libdir_cross_fixup

.github/workflows/lint_mypy.yml, mesonbuild/ast/interpreter.py, mesonbuild/ast/introspection.py, mesonbuild/ast/postprocess.py, mesonbuild/ast/printer.py, mesonbuild/ast/visitor.py, mesonbuild/cmake/interpreter.py, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/mesonlib.py, mesonbuild/mintro.py, mesonbuild/mparser.py, mesonbuild/optinterpreter.py, mesonbuild/rewriter.py, run_unittests.py
I tried to keep this PR to mostly only adding type annotations and making mypy happy. However, there were some situations where blindly adding types didn't make any sense, and some slight code refactoring was necessary.
The biggest change is that the ArgumentNode now always uses nodes (instead of sometimes nodes and sometimes strings) as the key for kwargs. I wouldn't say that this is ideal, but it is now clearly documented in the type system and mypy will complain if you use it wrong (also I couldn't think of a better solution).
=> types: Annotations for ast, mparser.py, interpreterbase.py

docs/markdown/snippets/cd_arguments_with_init_command.md, mesonbuild/minit.py
Provided a `-C` argument so users can specify the root directory.
=> Adding -C to 'meson init' command

mesonbuild/modules/pkgconfig.py
Deprecation warning was unable to display because of patch
c8f8d58273a40d94c820dccab54a7ae2d948cb8a
=> pkgconfig: Fix deprecation message (fixes #6720)

mesonbuild/compilers/c.py, mesonbuild/compilers/cpp.py
clang-cl is handled as a separate case (ClangClCCompiler), which already
gets c_winlibs from VisualStudioLikeCCompilerMixin.
=> Set c_winlibs/cpp_winlibs for Clang in the same way as for GCC

docs/markdown/Reference-manual.md, docs/markdown/snippets/build_target_older_name.md, mesonbuild/interpreter.py, test cases/common/1 trivial/meson.build, test cases/common/3 static/meson.build
As any child of ObjectHolder might need the name of the object,
provides a method to get name.
This is useful in gst-build to display the plugin name and not
the filename.
=> interpreter: add 'name' method to BuildTargetHolder

docs/markdown/Reference-manual.md, docs/markdown/snippets/override_dependency.md, mesonbuild/build.py, mesonbuild/interpreter.py, run_unittests.py, test cases/common/102 subproject subdir/meson.build, test cases/common/102 subproject subdir/subprojects/sub/lib/meson.build, test cases/common/102 subproject subdir/subprojects/sub/meson.build, test cases/common/102 subproject subdir/subprojects/sub_novar/meson.build, test cases/failing/100 fallback consistency/meson.build, test cases/failing/100 fallback consistency/subprojects/sub/meson.build, test cases/failing/99 fallback consistency/meson.build, test cases/failing/99 fallback consistency/subprojects/sub/meson.build, test cases/linuxlike/5 dependency versions/meson.build, test cases/linuxlike/5 dependency versions/subprojects/fakezlib/meson.build
Similar to meson.override_find_program() but overrides the result of the
dependency() function.
Also ensure that dependency() always returns the same result when
looking for the same dependency, this fixes cases where parts of the
project could be using a system library and other parts use the library
provided by a subproject.
=> Add meson.override_dependency()

run_unittests.py
This PR has the `d` language added to the sample create and run part of the test since it should be tested.  Also added `rust` in detection, and to defined against AppVeyor issues I check to see if the environment is Windows.
=> Update test_templates to add Dlang in sample create and build plus find Rust

mesonbuild/templates/mesontemplates.py, run_unittests.py
Updated `meson.build` generator just in case the user is a Java developer.  Now we can create scripts for classic `executable` and `jar` projects.
Also, update the `test_templates` to reflect this change.
=> Implementation of meson.build jar template

docs/markdown/Builtin-options.md, docs/markdown/Reference-tables.md, docs/markdown/snippets/emscripten_threads.md, docs/markdown/snippets/wasm_ld.md, mesonbuild/compilers/c.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/mixins/emscripten.py, mesonbuild/compilers/mixins/islinker.py, mesonbuild/environment.py, mesonbuild/linkers.py, test cases/wasm/1 basic/hello.c, test cases/wasm/1 basic/meson.build, test cases/wasm/2 threads/meson.build, test cases/wasm/2 threads/threads.c, test cases/wasm/2 threads/threads.cpp
There are some bug fixes for the islinker mixin in here, some bug fixes for emsciprten, and an implementation of thread support for emscripten. I've added a new option to emscripten compilers to set the number of threads in the thread pool. Additionally I've added a proper linker class for wasm-ld, which is both more correct and makes the code cleaner and more robust.
Fixes #6684
=> Emcc linker bugs and improvments

.github/workflows/lint_mypy.yml, mesonbuild/ast/introspection.py, mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/build.py, mesonbuild/compilers/compilers.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/boost.py, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/mesonlib.py, mesonbuild/mlog.py, mesonbuild/modules/__init__.py, mesonbuild/modules/gnome.py, mesonbuild/modules/i18n.py, mesonbuild/modules/pkgconfig.py, mesonbuild/modules/qt.py, mesonbuild/modules/windows.py, mypy.ini, run_unittests.py
This series is mainly aimed at adding type annotations to the mesonlib module, although it does have a few more fixups in it. The biggest change is splitting the unholder functionality out of listify, I've done this because listify is already basically impossible to correctly type, and splitting out the unholdering code makes it much easier.
=> Mesonlib type annotations

docs/markdown/Pkgconfig-module.md, mesonbuild/modules/pkgconfig.py
[why]
Sometimes one want to set the 'Conflicts:' field in .pc files.
This is possible by using the 'conflicts' keyword argument in the
pkgconfig module. The feature is not documented on mesonbuild.org,
though.
But a warning is issued:
WARNING: Passed invalid keyword argument "conflicts".
WARNING: This will become a hard error in the future.
History:
It has been added along with kwarg 'url' with commit
309041918 pkgconfig: Add missing 'URL' and 'Conflicts' entries
Later the kwargs check has been introduced with
80d665e8d Converted some modules.
but both 'url' and 'conflicts' were missing.
With commit
2acf737b pkgconfig: Document url keyword
the 'url' kwarg has been added to the checks, but not 'conflicts'.
[how]
Add 'conflicts' to the allowed kwargs.
Signed-off-by: Fini Jastrow …
=> pkgconfig: Document conflicts keyword

docs/markdown/Builtin-options.md, mesonbuild/coredata.py, run_unittests.py, test cases/common/1 trivial/meson.build
commit 7cd9fcef125a9ad6f7416f647e70155e205c1c9d:
```
coredata: Convert all option parsing to OrderedDict()
This ensures that options are always parsed in the order in which they
were specified on the command-line, even with Python 3.5, and
non-CPython implementations compatible with CPython 3.5 and 3.6.
```
Closes https://github.com/mesonbuild/meson/issues/6742
commit 6ee7450aaf99b24343eb3680457830dea718151b:
```
coredata: Set default options as cmdline args that override each other
The previous code was assuming that options do not depend on each
other, and that you can set defaults using `dict.setdefault()`. This
is not true for `buildtype` + `optimization`/`debug`, so we add
defaults + overrides in the right order and use the options parsing
code later to compute the values.
Includes a …
```
=> Fix some build type option parsing bugs

data/syntax-highlighting/vim/syntax/meson.vim
=> syntax-highlighting/vim: Add `in` as an operator

docs/markdown/snippets/ldc_linker_override.md
I forgot to put this in the d linker cleanups, as I implemented it.
=> docs: Document that ldc now supports linker overriding [skip ci]

mesonbuild/compilers/mixins/clang.py
Clang supports the GCC -Og flag, but --optimization=g is not setting that. This is because Clang is referencing the clike_optimization_args, which does not define a flag for 'g'.
To address this, we'll mimic the GNU options instead of the C-like ones.
Fixes #6619
=> Resolve Clang failure to use -Og with --optimization=g

mesonbuild/interpreterbase.py, mesonbuild/mlog.py
getattr() requires a default (return if missing) value or it raises an
AttributeError. In a few cases I changed hasattr to getattr and didn't
set a default value, so those cases could except. This corrects that.
=> fix conversion of hasattr to getattr

docs/markdown/snippets/ldc_linker_override.md, mesonbuild/compilers/d.py, run_unittests.py
GDC uses the standard `-fuse-ld=` argument that most GCC derivatives do. This adds the necessary tests for the D language, as well as the changes for GDC. This contains the documentation for the ldc change as well, as I simply modified that snippet.
=> Allow setting linker for GDC as well as LDC

azure-pipelines.yml
This reverts commit 5f9dccb9bce957979efa6efea961192a12f76790.
It looks like the MSYS2 bug linked in #5807 has been resolved some time ago, so this workaround is no longer needed.
"Now is later."
=> Revert "azure: Workaround MSYS2 PCH test failures"

.github/workflows/os_comp.yml
rustc 1.42 now dynamically link to libstd so its path is needed in
LD_LIBRARY_PATH.
=> Fix failing rust CI

mesonbuild/compilers/compilers.py, mesonbuild/compilers/d.py
It is expected that on Linux, MacOS, and other Unices that libphobos and the d runtime will be linked dynamically, but on windows they should be linked statically. A number of Linux distros patch the D compilers to do this automatically, but not all of them do, so we should emit the proper arguments.
Fixes: #6786
=> compilers: Link D runtime/libphobos dynamically on !Windows

mesonbuild/compilers/mixins/clike.py
If no exe_wrapper is set in the meson cross file the exe_wrapper
object will be an instance of EmptyExternalProgram.
So, found is True and prorgram is an empty list.
This will cause meson to tun the compiler sanity check because
it checks only for self.is_cross and self.exe_wrapper being
not None.
I ran into that situation while cross compiling for ia32 on a
x64_64 host. The host had no ia32 userspace installed, so the
self test failed.
As workaround I currently set exe_wrapper to 'true'.
Signed-off-by: Richard Weinberger <richard@nod.at>
=> Fix exe_wrapper usage in EmptyExternalProgram case

mesonbuild/backend/ninjabackend.py, mesonbuild/mesonlib.py, test cases/common/203 function attributes/meson.build
This make relative pathes shorter an too give a chance to
de-duplicate -isystem flags just like -I flags.
Fix common test case 203 for OSX build host too.
Related to https://github.com/mesonbuild/meson/issues/2155
=> Use os.path.normpath() for include paths

docs/markdown/Reference-tables.md, docs/markdown/howtox.md, docs/markdown/snippets/linker_environment_variables_match_docs.md, mesonbuild/compilers/mixins/gnu.py, mesonbuild/compilers/mixins/visualstudio.py, mesonbuild/envconfig.py, run_unittests.py, test cases/java/1 basic/meson.build
Currently the linker environment variables only match the docs half the time. This series changes that to match the docs all the time, with the old variables still supported by deprecated.
=> Make linker selection environment variables match docs

mesonbuild/build.py
There's no reason not to, this is just an oversight.
=> Generators can depend on custom targets as well as build targets.

docs/markdown/Dependencies.md, docs/markdown/Reference-manual.md, docs/markdown/snippets/cmake_comps.md, mesonbuild/dependencies/base.py, mesonbuild/dependencies/data/CMakeLists.txt, mesonbuild/dependencies/dev.py, mesonbuild/interpreter.py, test cases/linuxlike/13 cmake dependency/cmake/FindSomethingLikeZLIB.cmake, test cases/linuxlike/13 cmake dependency/meson.build
Salvaged from #6569, since this is still a useful feature for users or other dependency classes.
=> cmake: Add find_package COMPONENTS support

docs/markdown/snippets/termination_signal_for_tests.md, mesonbuild/mtest.py
Since neither SIGKILL nor SIGSTOP can be caught nor ignored it could be useful to terminate a test process via another signal first. Allowing some additional cleanup of a test. 
As an example, I would like to report a backtrace of the current state of a test when it times out as it could help understand an underlying problem. Currently, because the process running the test is terminated via SIGKILL it is not possible to do this.
=> mtest: allow test processes to react on termination

docs/markdown/Native-environments.md
With Meson 0.53.1, this is now out of date. Updating to use the proper ld variables.
=> Update native description to use the new LD variables

docs/markdown/Cross-compilation.md
As of Meson 0.53.1, this is out of date. Example has been updated.
=> Update cross compilation documentation to reference new ld variables

mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/scalapack.py
Basically this breaks down into three cases. An open source version with
compliant PkgConfig, valid CMake, and a Intel implementation that has
completely broken PkgConfig. For the first two cases we can use standard
classes, for the last we can make a subclass of PkgConfigDependency that
handles the special logic.
This doesn't change any of the logic, but it does re-organize it to be
clearer, and make use of the dependency factory API, which makes other
things (like Dependency.get_variable) work.
This is untested with Intel MKL.
=> dependencies: Convert ScaLAPACK to a dependency factory

mesonbuild/interpreter.py, run_project_tests.py, test cases/common/123 cpp and asm/meson.build, test cases/common/127 custom target directory install/docgen.py
A modification to `test cases/common/123 cpp and asm/meson.build` which demonstrates a problem with machine detection:
In the MSYS2 `MSYSTEM=MINGW32` environment (64-bit MSYS2 but with a `i686-w64-mingw32` targeted gcc as `gcc`)  this test fails, as it (incorrectly) tries to build retval-x86_64.S using an x86 compiler.
(See https://github.com/mesonbuild/meson/pull/6512/commits/4cd3015828766fb3bb297ea5a177de62889d7792 for discussion)
I was puzzled for a while why this only reproduced locally but not in CI, but this is due to the fact that it only configures incorrectly the *first* time (in CI, the `meson.build` is touched to force a reconfigure when building.  I assume some information is preserved in CoreData which causes the machine to be detected correctly when reconfiguring?)
I'm not …
=> Redetect machines when languages change

docs/markdown/Dependencies.md, mesonbuild/dependencies/__init__.py, mesonbuild/dependencies/base.py, mesonbuild/dependencies/mpi.py, mesonbuild/dependencies/ui.py, test cases/frameworks/17 mpi/meson.build, test cases/frameworks/17 mpi/meson_options.txt
The main code savings here is the use of the ConfigTool dependency, but this brings the MPI code in line with the way most other dependencies work, plus the code savings is nice.
=> Use DependencyFactory and ConfigToolDependency for MPI

mesonbuild/compilers/mixins/arm.py
ARMCC dependencies are not generated by Meson at the moment causing it to miss changes in dependent files. Allow generation of standard dependency files by armcc.
=> Fix ARMCC dependency generation.

mesonbuild/compilers/__init__.py, run_unittests.py
Just because we are on windows doesn't mean we can use `link`.
This ought to be done better, but this will do for now.
=> Fix linker evn var tests

docs/markdown/howtox.md, docs/markdown/snippets/env_vars_and_cross.md, mesonbuild/backend/backends.py, mesonbuild/cmake/executor.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/mixins/islinker.py, mesonbuild/coredata.py, mesonbuild/dependencies/base.py, mesonbuild/envconfig.py, mesonbuild/environment.py, mesonbuild/interpreter.py, mesonbuild/linkers.py, mesonbuild/modules/python.py, mesonbuild/modules/python3.py, mesonbuild/modules/windows.py, run_unittests.py
PR #6363 makes it so our interpretation of env vars no longer clashes
with Autoconf's: if both Meson and Autoconf would read and env var, both
would do the same things with the value they read.
However, there were still cases that Autoconf would read an env var when
Meson wouldn't:
- Autoconf would use `CC` in cross builds too
- Autoconf would use `CC_FOR_BUILD` in native builds too.
There's no reason Meson can't also do this--if native cross files
overwrite rather than replace env vars, cross files can also overwrite
rather than replace env vars.
Because variables like `CC` are so ubiquitous, and because ignoring them
in cross builds just makes those builds liable to break (and things more
complicated in general), we bring Meson's behavior in line with
Autoconf's.
I can personally vouch …
=> Naturally use env vars a bit more to match Autoconf -- contains #6363

mesonbuild/modules/gnome.py
The 'check' kwarg was added in Meson 0.52.0.
=> gtkdoc: Add missing permitted kwarg

mesonbuild/compilers/mixins/clang.py
This will be a regression in 0.54.0 because we now enforce that gnu
compilers only get gold, bfd, or lld.
=> compilers: Clang can take linkers that are paths

mesonbuild/environment.py
The previous diagnosis (that the wrapper that injects the -target
option to clang caused the issues) doesn't seem right; the issue
was that LLD's MinGW frontend (which is invoked when ld.lld is given
a COFF argument to the -m option) didn't handle the --version argument
before LLD 9.0.0.
This clarifies the diagnosis from #5910 (ping @Akaricchi).
=> Clarify a workaround for older versions of LLD for MinGW

mesonbuild/dependencies/boost.py, test cases/frameworks/1 boost/meson.build
Automatically choose the minor python version, if not specified. Also, log which modules where found and which are missing.
fixes #6844
=> boost: boost_python detection improvements

docs/markdown/Cross-compilation.md, docs/markdown/Machine-files.md, docs/markdown/Native-environments.md, docs/sitemap.txt
Rather than having two separate sections with duplicated information
lets just have one for the common settings, and only document sections
specific to each file in separately
=> docs/markdown: Add a new page with common cross/native file options [skip ci]

mesonbuild/compilers/cpp.py
Should target libc++, not libstdc++.
=> compilers: Fix C++ stdlib flags used for Apple's Clang

mesonbuild/modules/gnome.py, test cases/failing/102 no glib-compile-resources/meson.build, test cases/failing/102 no glib-compile-resources/trivial.gresource.xml
Report an errror if `glib-compile-resources` is missing, rather than a python backtrace.
Before:
```
Program glib-compile-resources found: NO
Found pkg-config: /usr/bin/pkg-config (1.6.0)
File "/wip/meson/mesonbuild/mesonmain.py", line 131, in run
File "/wip/meson/mesonbuild/msetup.py", line 245, in run
app.generate()
File "/wip/meson/mesonbuild/msetup.py", line 159, in generate
File "/wip/meson/mesonbuild/msetup.py", line 192, in _generate
intr.run()
File "/wip/meson/mesonbuild/interpreter.py", line 4359, in run
super().run()
File "/wip/meson/mesonbuild/interpreterbase.py", line 441, in run
self.evaluate_codeblock(self.ast, start=1)
File "/wip/meson/mesonbuild/interpreterbase.py", line 466, in …
```
=> Report an errror if glib-compile-resources is missing

mesonbuild/environment.py
I've combined the two ppc checks into one, since they're not very
complicated and added power machintosh, which is used by PPC macs
running older versions of osx.
Fixes: #6746
=> environment: "power machintosh" is ppc

mesonbuild/compilers/compilers.py
When doing a compile test with a testfile.c, ccache fails since the path is random.
So it's better to disable it, to avoid reporting this as a cache miss.
=> compilers: disable ccache when using temporary source files

mesonbuild/templates/mesontemplates.py
It was generating an extra comma.
Version: 0.54.0
Source dir: /tmp/tmp34halxhe
Build dir: /tmp/tmp34halxhe/build
meson.build:6:15: ERROR: Expecting rparen got comma.
'Foo.java',,
^
For a block that started at 5,3
jar('tmp34halxhe',
^
A full log can be found at /tmp/tmp34halxhe/build/meson-logs/meson-log.txt
Using "tmp34halxhe" (name of current directory) as project name.
Using "tmp34halxhe" (project name) as name of executable to build.
Detected source files: Foo.java
Detected language: java
Generated meson.build file:
project('tmp34halxhe', 'java',
version : '0.1',
default_options : ['warning_level=3'])
jar('tmp34halxhe',
'Foo.java',,
main_class: tmp34halxhe,
install : true)
It was also missing quotes around the main class name.
The Meson …
=> Fix meson_jar_template

docs/markdown/Build-targets.md
Build targets document should address best practices since this is the place where the new users usually get started.
=> docs: Described library command in Build targets section [skip ci]

mesonbuild/templates/cudatemplates.py
Fixes the language arrays in the cuda `meson.build` template.
=> cuda: Fix meson template (fixes #6869)

mesonbuild/backend/vs2010backend.py
Both DebugInformationFormat and BasicRuntimeChecks need to be in clconf
(not type_config) for Visual Studio to recognize them.
Fixes #6699
=> backend/vs: Fix debug information and runtime checks

mesonbuild/mparser.py, test cases/common/230 arithmetic operators/meson.build
The arithmetic operators are now split into two groups:
* The add/sub group: `+`, `-`
* The mul/div group: `*`, `/`, `%`
All operators within the same group are left-associative and have equal precedence. The mul/div group has a higher precedence than the add/sub group, as one would expect.
Previously every operator had a different precedence and was right-associative, which resulted in surprising behavior.
This is a potentially breaking change for projects that relied on the old incorrect behavior.
Fixes #6870
=> mparser: fix precedence of arithmetic operators

docs/markdown/Dependencies.md
[Tested](https://gitlab.com/geri0n/meson-llvm-test) on Ubuntu 18.04, Gentoo, Debian Buster, Feora 31 (Fedora seems to allow only one LLVM version).
=> docs: add LLVM tool section to dependencies

mesonbuild/compilers/mixins/clike.py, test cases/common/39 has function/meson.build
Fixes #6889
This extends/repurposes the existing logic for detecting whether a regular function is implemented as a builtin. If the function's name begins with `__builtin_`, the test will not add an extra `__builtin_` prefix. Many builtins do not have a corresponding prefix-less macro definition, so being able to test for them directly is useful.
=> Make cc.has_function work on GCC/Clang __builtins

mesonbuild/backend/vs2010backend.py
Executables may have an entry point of wmain or wWinMain. These
executables link successfully with ninja. Rather than add more flags to
executable() in meson.build, remove the EntryPointSymbol override. This
makes the vs backend behave more like the ninja backend.
Fixes #6698
=> backend/vs: Fix link of wmain / wWinMain based apps

mesonbuild/dependencies/ui.py, run_unittests.py
`b_vscrt` has existed forever, and is the canonical source for which CRT to link to, and hence whether to use the debug libraries or not.
=> qt dependency: Pick debug libraries based on b_vscrt

mesonbuild/compilers/fortran.py, mesonbuild/compilers/mixins/clike.py, mesonbuild/interpreter.py, test cases/fortran/18 first_arg/main.f90, test cases/fortran/18 first_arg/meson.build
This PR is only **type annotation** and **refactoring**. It adds type hinting primarily for Fortran compilers, and adds additional tests for `.first_supported_argument()` and `.get_supported_arguments()`.
=> CI fortran: first_supported_argument, get_supported_arguments

mesonbuild/dependencies/boost.py
No test case since this requires two boost versions in the image and this is currently not doable with any existing distros.
=> boost: Fix library version (fixes #6899)

docs/markdown/Build-targets.md
Fixing what I forgot to change last time when changing Build target section. Sorry.
The sentence even says "respectively" while listing three targets and the previous sentence has four targets listed, so it's not looking very good.
=> docs: Mention library command as well [skip ci]

docs/markdown/Using-with-Visual-Studio.md, mesonbuild/mcompile.py
commit b7e31ea3d2d825fc22e8aebebb12256707791256:
```
mcompile: Use the current dir if unspecified
With this running `meson compile` inside the builddir actually works,
and you don't have to do `meson compile -C .`
Clearly this was the intent since the option already has `default='.'`
```
commit 88ebd7e616ef594cfc42fb2c3577f00e2e59f8f0:
```
docs: Update Using-with-Visual Studio
Very out of date instructions. We install `meson.exe` now and you
don't need to have `py` in PATH or use `/path/to/meson.py`.
```
=> Fix meson compile from inside the builddir + update old vs docs

mesonbuild/backend/vs2010backend.py
VS2019 has support for ARM64 builds, but Meson can't target them.
=> Fix architecture detection logic for VS backend to allow ARM64

mesonbuild/dependencies/dev.py
Without this, there's tons of log output about finding LLVM, followed by "couldn't find LLVM."
=> Log when ignoring LLVM because dynamic was requested

mesonbuild/mesonlib.py, run_unittests.py
remove useless assert when parsing cmake syntax config files.
tested with openjpeg cmake config files.
=> cmake: support cmake config file syntax

mesonbuild/compilers/mixins/gnu.py, mesonbuild/envconfig.py, mesonbuild/mesonlib.py, mesonbuild/scripts/symbolextractor.py
While meson generally works fine on the Hurd, there are few things that can be fixed/improved.\
This PR:
- adds `is_hurd` functions to be able to recognize when building on the Hurd
- adds Hurd support in symbolextractor, using the same Linux method
- disable the address sanitizer, as not supported there yet
=> Basic changes for the Hurd

docs/markdown/Reference-tables.md
At https://mesonbuild.com/Reference-tables.html#compiler-and-linker-selection-variables, the table is broken and it seems that the only difference with other well-working tables on this page is the semi-column ":" that are present under Language.
=> References-tables.md: repair broken table

docs/markdown/Reference-manual.md
When set to **true** only the last component is used. And throw in two minor
grammatical fixes while we're there.
=> docs: fix the docs for install_subdir's strip_directory

mesonbuild/dependencies/dev.py
Without this change, a VS project generated by Meson for a target which depends on LLVM, when LLVM was found via the CMake dependency, has broken intellisense. This is because the project-wide `ClCompile\PreprocessorDefinitions` node ends up with a set of space-separated preprocessor command line options (e.g. -Dkey=value except for the first entry), rather than a semicolon-separated list of key=value (or just key) entries.
I traced this back to the fact that LLVM sets its `LLVM_DEFINITIONS` variable explicitly to a space-separated list of defines:
> \# We don't want no semicolons on LLVM_DEFINITIONS:
Then CMake's module finder converts `LLVM_DEFINITIONS` to the `PACKAGE_DEFINITIONS` that Meson consumes, which gets parsed as a single command line switch.
The end result is that VS's …
=> Fix VS Intellisense for projects which depend on LLVM found via CMake.

docs/markdown/Reference-manual.md, mesonbuild/build.py, test cases/common/206 install name_prefix name_suffix/meson.build, test cases/common/206 install name_prefix name_suffix/test.json
Fix handling of `library(name_prefix: [])`
c87c42b736197b726f3cca47e92bc836c773085e documents that this is a way to explicitly specify the default (rather than an empty) library name prefix.
I couldn't find any release in which this feature worked, so I'm not sure what the intended mechanism to achieve that was.
Fix it by matching the `name_suffix` behaviour of not setting the relevant attribute of the BuildTarget object in the empty list case, so the default is used.
Add a test.
=> Fix library(name_prefix: [])

mesonbuild/compilers/compilers.py, mesonbuild/compilers/d.py, mesonbuild/compilers/mixins/clike.py, mesonbuild/compilers/mixins/gnu.py
This fixes two related bugs, the first is that GDC should support coverage through gcovr, since it's a GCC compiler. The second is that we don't pass the correct arguments to LDC and DMD to generate coverage. LDC and DMD still don't really work, as they don't generate a coverage format that meson understands, they use .lst files, and we need to pass additional arguments to the test binaries that the compilers add to them to set things like where to write the result files, and whether to merge or replace files.
related to #5669
=> Fix coverage generation with D compilers

docs/markdown/Wrap-dependency-system-manual.md, docs/markdown/snippets/wrap_fallback.md, mesonbuild/wrap/wrap.py, run_unittests.py
It can happen that a server is temporaly down, tarballs often have
many mirrors available so we should be able to add at least one fallback
mirror in wrap files.
=> wrap: Add fallback urls

mesonbuild/interpreter.py
This PR addresses changes needed to properly show the program's name on a `run_command` error message. See issue https://github.com/mesonbuild/meson/issues/6969
=> Show proper program's name on run_command error message

docs/markdown/Builtin-options.md
Using meson version `0.53.2` prefix defaulted to `/usr/local`, not `/usr/local/` (note the trailing slash)
=> Corrected prefix path default in documentation.

test cases/common/93 selfbuilt custom/meson.build
By building the generator for the build machine always, and only for the
host machine if an exe_wrapper is available. This makes sense to me as
generally you are going to build the generator for the build machine,
not the host machine, but testing on the host machine makes sense too.
=> tests/common/93: Fix cross building when no exe_wrapper is available

mesonbuild/compilers/c_function_attributes.py, test cases/common/203 function attributes/meson.build, test cases/common/203 function attributes/meson_options.txt, test cases/common/203 function attributes/test.json
Which has changed the way it handles gnu_inline in C++.
=> compilers: Update gnu_inline test to work correctly with Clang >= 10

mesonbuild/dependencies/base.py
These three commits fix linking of system libraries when declared as dependencies of CMake targets we pick up as Meson dependencies. In particular, when linking Clang into Mesa via CMake, we were dropping all of the system library dependencies such as `ole32` and `uuid` … except if Meson was executed from the source directory, in which case we would retain `version` as a bare argument (since the Mesa source root has a file called `VERSION`), which would get passed through to the linker without a suffix qualification and fail the build.
This PR attempts to do something more reasonable with system-library dependencies under Windows.
cc @dcbaker @jenatali
=> Fix CMake Windows system library deps

mesonbuild/cmake/data/preload.cmake, mesonbuild/cmake/interpreter.py, mesonbuild/cmake/traceparser.py, test cases/cmake/18 skip include files/main.cpp, test cases/cmake/18 skip include files/meson.build, test cases/cmake/18 skip include files/subprojects/cmMod/CMakeLists.txt, test cases/cmake/18 skip include files/subprojects/cmMod/cmMod.cpp, test cases/cmake/18 skip include files/subprojects/cmMod/cmMod.hpp, test cases/cmake/18 skip include files/subprojects/cmMod/fakeInc/CMakeLists.txt, test cases/cmake/18 skip include files/subprojects/cmMod/fakeInc/cmModInc1.cpp, test cases/cmake/18 skip include files/subprojects/cmMod/fakeInc/cmModInc2.cpp, test cases/cmake/18 skip include files/subprojects/cmMod/fakeInc/cmModInc3.cpp, test cases/cmake/18 skip include files/subprojects/cmMod/fakeInc/cmModInc4.cpp
With this change meson now supports the [`HEADER_FILE_ONLY`](https://cmake.org/cmake/help/latest/prop_sf/HEADER_FILE_ONLY.html) source file property. It was necessary to fall back to the CMake trace, since the old CMake server API does not expose this information.
Ping @line0
=> cmake: Do not compile explicit header files

mesonbuild/compilers/c_function_attributes.py, mesonbuild/compilers/mixins/clang.py, mesonbuild/compilers/mixins/clike.py, mesonbuild/compilers/mixins/gnu.py
The warning is due to a change in behaviour in Clang 10 and newer:
https://releases.llvm.org/10.0.0/tools/clang/docs/ReleaseNotes.html#c-language-changes-in-clang
This was already fixed for clang++, but not for clang for some reason. It was also fixed incorrectly; by adding `extern` instead of moving from `-Werror` to `-Werror=attributes`.
Should fix the remaining failure in the CI (msys2 clangx64ninja):
```
Compiler stderr:
D:\a\1\s\b 14fe268f30\meson-private\tmplco6n27n\testfile.cpp:1:23: error: 'gnu_inline' attribute without 'extern' in C++ treated as externally available, this changed in Clang 10 [-Werror,-Wgnu-inline-cpp-without-extern]
inline __attribute__((gnu_inline)) int foo(void) { return 0; }
^
1 error generated.
Compiler for C++ supports function attribute gnu_inline: NO 
test …
```
=> compilers: Silence warning about gnu_inline with clang

mesonbuild/backend/backends.py, mesonbuild/backend/ninjabackend.py, mesonbuild/backend/vs2010backend.py, mesonbuild/build.py, mesonbuild/compilers/c.py, mesonbuild/compilers/compilers.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/fortran.py, mesonbuild/coredata.py, mesonbuild/environment.py, mesonbuild/interpreter.py, mesonbuild/mconf.py, mesonbuild/mintro.py, mesonbuild/rewriter.py, run_tests.py, run_unittests.py
A current rather untyped storage of options is one of the things that
contributes to the options code being so complex. This takes a small
step in synching down by storing the compiler options in dicts per
language.
Future work might be replacing the langauge strings with an enum, and
defaultdict with a custom struct, just like `PerMachine` and
`MachineChoice`.
=> Compiler options per lang

docs/markdown/Cross-compilation.md
Also note that meson doesn't use `el` on the end of the cpu_family to
mark endianness, that the endian field needs to be set appropriately.
=> docs/cross-compilation: Note appropriate values for cpu_family [skip ci]

mesonbuild/scripts/gtkdochelper.py
Hi,
This attempts to update gtkdochelper.py so that we might be able to use it to generate gtk-doc documentation on cmd.exe consoles (i.e. for Visual Studio builds).
This attempts to do so by:
*  Prepend the python executable in the command line to call the various gtk-doc tool scripts on Windows, since cmd.exe consoles do not support shebang lines.
* (suggestions welcome) The print() line at line 77 could choke with ```UnicodeEncodeError``` as Windows cmd.exe consoles may not be in a code page that does this encoding well.  Work around this by just ignoring this error.  Interestingly, if there is an error while running the tool scripts, the error output does work as expected.
=> gtkdochelper.py: Allow use on Windows cmd.exe consoles

.editorconfig, .github/workflows/os_comp.yml, azure-pipelines.yml, ci/ciimage/arch/install.sh, ci/run.ps1, ci/travis_install.sh, data/test.schema.json, docs/markdown/Contributing.md, run_project_tests.py, run_unittests.py, test cases/frameworks/16 sdl2/meson.build, test cases/frameworks/16 sdl2/meson_options.txt, test cases/frameworks/16 sdl2/test.json, test cases/frameworks/17 mpi/test.json
This adds a schema for the json format we use in the framework tests, and a unittest which runs the schema against the tests (using the jsonschema python module). This also adds a couple of matrix options for some of the framework tests so we can test all of the different methods of discovering those dependencies.
This schema is also useful for IDE users, as it can be used for error checking and auto completion. With VSCode for example, I can get both.
I suspect that this has a chicken and egg problem with the CI images.
=> project test junit schema + a few more uses

mesonbuild/cmake/interpreter.py, mesonbuild/dependencies/base.py, setup.cfg
This is a small but significant change, in particular it changes meson to use setuptools pkg_resource for finding data files. This is important because pkg_resource understands all of the odd corner cases of where python might install data files in different cases (ziplib, wheel, egg, running from the directory, etc). We already have a dependency on setuptools for it's entrypoint functions (and to install meson at all), so this isn't a new dependency, but it is another place we depend on setuptools.
Fixes #6801
=> Fix resource file finding

mesonbuild/cmake/executor.py
On some systems the binary 'cmake' for version 3 is named 'cmake3',
therefor printing its version number prints:
'cmake3 version X.Y.Z' instead of 'cmake version X.Y.Z'
This '3' digit in the middle breaks the regular expression
extracting the version number.
The following fix permit both way to work and the regexp to
match the proper version number.
Signed-off-by: Alexandre Lavigne <alexandre.lavigne@scality.com>
=> Issue: 7009: CMake/Centos7 Unable to find CMake even though it is installed

mesonbuild/compilers/mixins/clike.py
`mesonlib.darwin_get_object_archs()` only accepts a string argument so convert it.
This is a showstopper on macOS because the call in `darwin_get_object_archs()` to [`Popen_safe`](https://github.com/mesonbuild/meson/blob/a33f20b9a4e2e0ecf08f251be290bffd0d31a92d/mesonbuild/mesonlib.py#L531) then fails with a `TypeError`.
=> compilers: darwin_get_object_archs: fix type issue

mesonbuild/cmake/traceparser.py
I noticed the existing reg_start pattern wouldn't allow the following case to pass:
['C:/Program', 'Files', '(x86)/folder/include']
The new reg_start allows for spaces in the first folder, or in the first folder after the drive.
=> Adjust regex to handle cases such as C:/Program Files/

ci/ciimage/arch/install.sh, ci/ciimage/eoan/install.sh, ci/ciimage/fedora/install.sh, ci/ciimage/opensuse/install.sh, data/schema.xsd, docs/markdown/snippets/junit_result_generation.md, mesonbuild/mtest.py, run_unittests.py
JUnit is a widely supported (and mostly standard) test result format. A number of services can consume it directly or with standard plugins. Gitlab and jenkins are two common consumers of this format.
This adds a dependency on lxml for unittests (but not to run meson), to validate the generated XML against the JUnit schema.
=> mtest: Generate JUnit results for tests

docs/markdown/Reference-manual.md, docs/markdown/snippets/find_program.md, mesonbuild/interpreter.py, mesonbuild/modules/python.py, test cases/common/201 override with exe/meson.build, test cases/common/201 override with exe/subprojects/sub/meson.build
- ExternalProgramHolder has path() method while CustomTargetHolder and
BuildTargetHolder have full_path().
- The returned ExternalProgramHolder's path() method was broken, because
build.Executable object has no get_path() method, it needs the
backend.
- find_program('overriden_prog', version : '>=1.0') was broken because
it needs to execute the exe that is not yet built. Now assume the
program has the (sub)project version.
- If the version check fails, interpreter uses
ExternalProgramHolder.get_name() for the error message but
build.Executable does not implement get_name() method.
=> find_program: Fixes when the program has been overriden by executable

mesonbuild/interpreter.py
If the dependency is a special dependency which takes modules, the modules get cached separately and probably reference different pkg-config files. It's very plausible that we have multiple dependencies, using different modules. For example:
```
Run-time dependency qt5 (modules: Core) found: YES 5.14.2 (pkg-config)
Dependency qt5 skipped: feature gui disabled
```
Obviously this makes no sense, because of course we found qt5 and even used it. The second line is a lot more readable if it shows this:
```
Dependency qt5 (modules: Widgets) skipped: feature gui disabled
```
Similar confusion abounds in the case where a module is found in the cache -- which module, exactly, has been found here:
```
Dependency qt5 found: YES 5.14.2 (cached)
```
Rewrite the dependency function to *consistently* …
=> dependency: log cached or skipped dependencies with reference to modules

mesonbuild/interpreter.py
Potential fix for: https://github.com/mesonbuild/meson/issues/7029#issue-606367289
Changes the error message for  `test()` so it now reports the expected and actual number of parameters.
=> Clarified error message for test().

docs/markdown/IDE-integration.md
The Meson CMake Wrapper project is currently unmaintained.
=> Meson Cmake Wrapper unmaintained

mesonbuild/msetup.py
When wiping a build tree with --wipe, every entry in the build directory
is removed with mesonlib.windows_proof_rmtree() for directories and
mesonlib.windows_proof_rm() for other files. Symlinks to directories are
considered directories, resulting in the former being called. This
causes an exception to be raised, as the implementation calls
shutil.rmtree(), which isn't allowed on symlinks.
Fix this by using mesonlib.windows_proof_rm() for symlinks.
Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
=> Fix symlink deletion with --wipe option

docs/markdown/Syntax.md
My main motivation for this is that I wanted to lookup Meson grammar to use something similar for my own DSL project, but there was no formal definition to be found. I argue having such a formal definition could prove useful in the future as a reference when working on the parser component.
This is all still WIP, but I wanted to share the current status with you here to hopefully get some early feedback.
The grammar is expressed in EBNF, but I found there is no universally agreed upon syntax for EBNF, so here the same syntax Python uses for its grammar description is used.
Expression precedence was taken from C++ and I'm 99% sure that the same precedence rules apply in Meson, but that is a thing I have to check conclusively.
Most of the TODOs and FIXMEs are more hints to me, and will …
=> Document formal Meson grammar

docs/markdown/Reference-manual.md, docs/markdown/snippets/link_language_all_targets.md, mesonbuild/build.py, run_unittests.py, test cases/common/232 link language/c_linkage.cpp, test cases/common/232 link language/c_linkage.h, test cases/common/232 link language/lib.cpp, test cases/common/232 link language/main.c, test cases/common/232 link language/meson.build
It turns out the `link_language` field basically doesn't work at all, more than that if it did actually work it would work on more than just executable (which is all it was supposed to work on). As it is there are a couple of legitimate reasons to use this on libraries, namely libraries written in !C (C++ for example), that have C linkage, and the project wants to enforce that.
This series adds tests for the bug, fixes the bug, and remove the broken warning about using `link_language` in non-executables. It also updates the docs to explain when and why you would want to use it.
At least the first 4 patches are candidates for 0.54,though we might as well pull the whole thing in.
Fixes: #6453
=> Link language in libraries

mesonbuild/dependencies/boost.py
This should be fine since we extract the specific library defines automatically.
=> boost: Do not set BOOST_ALL_DYN_LINK (fixes #7056)

docs/markdown/Reference-manual.md, docs/markdown/snippets/add_foo_script_type_additions.md, mesonbuild/interpreter.py, test cases/common/104 postconf with args/meson.build, test cases/common/56 install script/customtarget.py, test cases/common/56 install script/meson.build, test cases/common/56 install script/myinstall.py, test cases/common/56 install script/src/exe.c, test cases/common/56 install script/src/meson.build, test cases/common/56 install script/src/myinstall.py, test cases/common/56 install script/test.json, test cases/common/56 install script/wrap.py, test cases/unit/35 dist script/meson.build
Currently the add_*_script methods accept strings and only strings, which is pretty annoying. This series aims to be comprehensive in what types they accept. For all of them, the script parameter should be able to take the output of `find_program` (or equivalent), and the inputs should be able to be `files`, or `configure_files`, as those should be available by the time the script runs. For add_install_script we should additionally be able to use built executables as the script, and be able to take build targets and custom targets (and indexes of custom targets) as inputs.
I've chosen not to support generators, I don't really think it makes sense to do so, but maybe other people will disagree.
Fixes: #1234
Fixes: #3552
Fixes: #6175
=> Allow meson.add_*_script to take additional types

mesonbuild/coredata.py
It's not a boolean, so let's avoid initializing it to invalid choices followed by assigning it valid ones.
=> coredata: init IntegerOption choices to the correct value

mesonbuild/coredata.py, run_unittests.py, test cases/unit/75 subdir libdir/meson.build, test cases/unit/75 subdir libdir/subprojects/flub/meson.build
The original commit caused a regression: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959708
This revert fixes the issue but brings back the original problem. If a proper fix is not made soon, this needs to go in.
=> Revert cross fixup

docs/markdown/Reference-manual.md, docs/markdown/Unit-tests.md, docs/markdown/snippets/gtest_protocol.md, mesonbuild/backend/backends.py, mesonbuild/build.py, mesonbuild/interpreter.py, mesonbuild/mintro.py, mesonbuild/mtest.py, run_unittests.py, test cases/frameworks/2 gtest/meson.build
GTest is a pretty common format in the C/C++ world. It's also a pretty powerful test framework, able to give more detailed results than you get from just the exitcode. In particular it can output JUnit xml. Since we now have support for JUnit xml generation ourselves we can inject such arguments, then consume the resulting JUnit and put it in our own XML.
=> Add support for Gtest as a test protocol

mesonbuild/envconfig.py
The comment for this code is correct, but the code itself isn't. The way
it's implemented in a cross compile we don't look at PKG_CONFIG_PATH at
all.
Fixes: #7062
=> envconfig: Always honor PKG_CONFIG_PATH

mesonbuild/modules/gnome.py
This is useful when one needs to force meson to use wrappers for cross compilation.
=> Allow overriding g-ir-scanner and g-ir-compiler binaries.

docs/markdown/Precompiled-headers.md
a give target -> a given target
Fixes: #7081
=> docs/Precompiled-headers: minor spell check. [skip ci]

mesonbuild/linkers.py
They are not meaningful and cause emscripten to spew warnings. See also https://github.com/emscripten-core/emscripten/issues/11076
=> Do not pass rpath flags to wasm-ld

mesonbuild/build.py, test cases/common/233 link depends indexed custom target/foo.c, test cases/common/233 link depends indexed custom target/make_file.py, test cases/common/233 link depends indexed custom target/meson.build
This change will allow indexed custom targets to be used in link_depends fields.
=> Allow indexed custom target to be used in executable's depends.

mesonbuild/modules/python.py
As stated by the doc, default to install python sources to purelib
location, as they should not depend on platform.
This also fixes discrepancy between get_install_dir() and
install_sources() locations.
=> python: install_sources() should default to pure, following the doc

docs/markdown/Dependencies.md, docs/markdown/snippets/config_tool_no_cross_path.md, mesonbuild/dependencies/base.py, test cases/frameworks/21 libwmf/meson.build
The system tool is always the wrong thing to use and cause hard to debug
issues when trying to link system libraries with cross built binaries.
The ExternalDependency base class already had a method to deal with
this, used by PkgConfigDependency and QtBaseDependency, so it should
make things more consistent.
=> ConfigToolDependency: Don't fallback to system tool when cross compiling

mesonbuild/compilers/mixins/clike.py
has_function() tries to link an example program using the function
to see if it is available, but with clang on 64bit Windows this
example always already failed at the compile step:
error: cast from pointer to smaller type 'long' loses information
long b = (long) a;
This is due to long!=pointer with LLP64
Change from "long" to "long long" which is min 64bit and should always
fit a pointer. While "long long" is strictly a C99 feature every
non super ancient compiler should still support it.
=> Fix has_function() for clang on 64bit Windows

mesonbuild/compilers/compilers.py, run_unittests.py
fixes-up 33fbc548ab74e79280d2f57b2cd499d14c1f1e91
fixes #6294
=> macos: Remove framwork linkerlike args

mesonbuild/build.py
in tree like dep structures with a lot of source: declarations, this can
result in a lot of presure on the source list. this saves ~3s out of 9s
in the interpretor stage in efl build.
=> interpretor: Do not add dependencies if we already have them

mesonbuild/dependencies/boost.py, mesonbuild/mesonlib.py
No test since this is highly system-specific. I will try to reproduce this with a Gentoo OS Comp test in the future.
=> boost: Try finding libraries with the matching arch (fixes #7110)

mesonbuild/compilers/fortran.py
__has_include is not accepted as a pre-processor directive in Fortran
code since GCC 10.
Closes https://github.com/mesonbuild/meson/issues/7017
=> gfortran: Fix has_header implementation with GCC 10

mesonbuild/dependencies/ui.py
Now follows ios and other platform directory layouts.  Moves from
separate android_$arch directories to every library containing a _$arch
suffix.  e.g. libQt5Core_x86.a in a single directory.
cc @nirbheek
=> ui/qt: use new directory layout for qt on android

mesonbuild/cmake/interpreter.py
```
File "mesonbuild/cmake/interpreter.py", line 293, in postprocess
'Unknown {}_std "{}" -> Ingoring. Try setting the project'
IndexError: Replacement index 2 out of range for positional args tuple
```
=> cmake: Fix string substitution index error

mesonbuild/coredata.py, run_unittests.py
test_cross_libdir() was broken because we were passing `--libdir=lib` when invoking meson.
We didn't notice that https://github.com/mesonbuild/meson/issues/6115 broke because of this.
With the second commit in this PR, this fixes https://github.com/mesonbuild/meson/issues/6115.
=> unit tests: Fix broken test_cross_libdir test

docs/markdown/Cross-compilation.md, docs/markdown/Reference-manual.md, docs/markdown/snippets/can_run_host_binaries.md, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, run_project_tests.py, test cases/common/36 tryrun/meson.build, test cases/common/93 selfbuilt custom/meson.build, test cases/unit/36 exe_wrapper behaviour/meson.build, test cases/warning/1 version for string div/test.json
the name `has_exe_wrapper` doesn't really describe what the function does, what it really does is check if an exe_wrapper is required, and if it is, whether there is one. `can_run_host_binaries` is much more descriptive of what the function actually checks. This doesn't remove has_exe_wrapper, just makes it an alias to can_run_host_binaries.
I've also made a small change to the semantics of the language, in that can_run_host_binaries is documented as returning `true` on host == build (native) compilation.
Related: https://github.com/mesonbuild/meson/issues/6865
=> Rename has_exe_wrapper to can_run_host_binaries

mesonbuild/dependencies/boost.py
This should fix #7126, but I am unable to test it.
=> boost: always use compiler include paths

mesonbuild/backend/vs2010backend.py
The ninja backend only uses the debug C runtime for 'debug', not for
'debugoptimized'.
The ninja backend always uses the DLL C runtime for all configurations.
The documentation matches the ninja backend.
Make the visual studio backend follow the documentation (and the precedent
set by the ninja backend).
Split out from #7109 .
=> backend/vs: Fix b_vscrt=from_buildtype for debugoptimized

docs/markdown/howtox.md
@jon-turney suggested this, and it makes more sense to me as well.
=> Docs: Make the suggested use for the not-found dependency better

mesonbuild/cmake/interpreter.py
This was helpful while debugging CI failure on the 0.54 branch due to
a difference in the structure of self.env.coredata.compiler_options:
https://github.com/mesonbuild/meson/runs/674391139
https://travis-ci.org/github/mesonbuild/meson/jobs/686982807
The change that went into 0.54 was: https://github.com/mesonbuild/meson/commit/477947a53ac0d83532ac9cf42b850d321d5cf58b
=> cmake: Print supported stds when warning

ci/travis_install.sh, test cases/failing/34 dependency not-required then required/test.json
We need to test both "have pkg-config" and "don't have pkg-config" pathways on macOS, which is why pkg-config was only installed in one branch based on `--unity=on/off`.
This broke in https://github.com/mesonbuild/meson/pull/6913.
=> travis/macos: Restore the old pkg-config behaviour

mesonbuild/scripts/symbolextractor.py
This will almost always change and cause a relink of everything. Our
other symbol extractor implementations do not store this either. We
only need to store the size of data objects, since that necessitates
a relink due to copy relocations.
Drastically reduces the amount of relinking required in gstreamer and
gtk on Linux.
~~This is a very safe and obvious fix, so I'm marking it for the stable release.~~
=> symbolextractor: Do not store the size of code objects

mesonbuild/compilers/cpp.py
Call to CPPCompilers initilisation function was missing the info parameter during ArmClangCPPCompiler initialisation
=> Fix ArmClangCPPCompiler initialisation

msi/createmsi.py
If the files in mesonbuild/dependencies/data aren't present when meson.exe runs after being installed by the msi, meson will crash if it tries to find a dependency with cmake. This commit adds those files in the installer.
=> Add cmake files to msi package.

mesonbuild/compilers/d.py
GDC uses the standard gnu arguments, all we needed to do is expose that. DMD doesn't have PGO AFAICT, and LDC2 needs some additional plumbing.
=> compilers/d: Enable pgo for GDC

mesonbuild/backend/backends.py, mesonbuild/backend/vs2010backend.py, run_unittests.py
The output name is guaranteed to be unique already so use that for the priv dir. Originally I though about using `.priv` suffic, but this one is shorter. Collision probability is low, as `,p` is an uncommon thing to have in your output file name.
=> Build private directory name from output file name.

mesonbuild/compilers/c.py, mesonbuild/compilers/cpp.py, mesonbuild/compilers/fortran.py, mesonbuild/compilers/mixins/clang.py, mesonbuild/compilers/objc.py, mesonbuild/compilers/objcpp.py, mesonbuild/environment.py
Simmilar to gcc, the list of pre-processor defines can be fetched with
`-dM -E` option. The way cpu_family is determined on linux relies on
this list.
Fixes incorrect value of cpu_family on linux, when crosscompiling:
```
CC="clang -m32" meson ./build
```
Signed-off-by: Yevhenii Kolesnikov <yevhenii.kolesnikov@globallogic.com>
=> compilers: add fetching of define list for clang

run_project_tests.py, test cases/failing/100 fallback consistency/test.json, test cases/failing/101 no native compiler/test.json, test cases/failing/102 subdir parse error/test.json, test cases/failing/103 invalid option file/test.json, test cases/failing/104 no lang/test.json, test cases/failing/105 no glib-compile-resources/test.json, test cases/failing/36 pkgconfig dependency impossible conditions/test.json, test cases/failing/67 subproj different versions/test.json, test cases/failing/84 gtest dependency with version/test.json, test cases/failing/98 fallback consistency/test.json
A follow-up to #6620, this adds the expected output for tests added since that work was started, and makes it mandatory to have expected output for failing-meson and warning-meson tests, so it will (hopefully) get added for new tests when they are added.
=> Make the expected output check mandatory for failing-meson and warning-meson tests

mesonbuild/build.py, mesonbuild/interpreter.py, mesonbuild/interpreterbase.py, mesonbuild/mesonlib.py, mesonbuild/modules/gnome.py, mesonbuild/modules/pkgconfig.py, mesonbuild/optinterpreter.py, run_unittests.py
This little series was meant to mainly replace a number of `mlog.deprecation` calls with `FeatureDeprecated`, along the way I did a little cleanup.
Suggested by @mensinda
=> Use FeatureDeprecated (and other cleanups)

run_project_tests.py
The current logs are unreadable because all text printed by failing meson logs gets spammed to stdout.
=> Remove stray print call.

docs/markdown/IDE-integration.md, docs/markdown/snippets/introspect.md, mesonbuild/ast/__init__.py, mesonbuild/ast/interpreter.py, mesonbuild/ast/printer.py, mesonbuild/ast/visitor.py, mesonbuild/mintro.py, mesonbuild/mparser.py, run_unittests.py, test cases/unit/57 introspection/meson.build
Adds the `--ast` command to `meson introspect` to dump the raw meson AST as JSON.
=> mintro: AST JSON printer

mesonbuild/backend/ninjabackend.py
Use --internal script call to call delwithsuffix when cleaning up the gcno and gcda files in a coverage enabled build. Otherwise, meson will crash when running from an MSI installation.
=> Use --internal script call for cleaning gcno and gcda files

mesonbuild/mcompile.py
- Replaced backend divination code with coredata parsing (`meson compile` should be used only with meson configured folders anyway).
- Extracted backend specific code to separate functions.
- Improved(?) error message when invoked on non-configured directory.
=> mcompile: replaced backend divination code + cleanup

mesonbuild/compilers/compilers.py
Renaming .ino files is not an option when working with projects that must use the IDE. Meson should allow their use with the C++ compiler.
=> Recognize Arduino .ino files as C++ files

mesonbuild/backend/ninjabackend.py, test cases/common/226 include_type dependency/main.cpp, test cases/common/226 include_type dependency/meson.build, test cases/common/226 include_type dependency/pch/test.hpp
Always convert `CompilerArgs` to the native in `add_item`. This should not hurt for compilers that don't need it and prevents bugs like #7167 in the future.
=> ninja: Always use to_native on CompilerArgs (fixes #7167)
