mesonbuild/meson

- install_meson.py
> install: install rpm macros if RPM bin in system. Closes #56

- modules/gnome.py
- modules/rpm.py
- test cases/frameworks/7 gnome/gir/meson.build
- test cases/frameworks/7 gnome/installed_files.txt
> modules/gnome: auto-set gobject-introspection directories and install gir

- modules/gnome.py
- test cases/frameworks/7 gnome/gir/meson.build
> modules/gnome: add support for multiple include for Gir. Closes #69

- modules/rpm.py
> modules/rpm: trivial style fixes

- run_tests.py
> tests: use name as class name

- run_tests.py
> tests: add time property

- run_tests.py
> tests: add skipped tests

- modules/gnome.py
- test cases/frameworks/7 gnome/gir/meson.build
> modules/gnome: make program name as optional argument. Closes #76

- modules/gnome.py
> modules/gnome: join 2 isinstance

- modules/gnome.py
> modules/gnome: add support for include dirs with GIRs

- authors.txt
- optinterpreter.py
While test driving meson my team had trouble with misspelled options values, especially for combo options. This should help clear things up.
> Better error messages for user options

- interpreter.py
The current message function can only print strings which made it a bit difficult to debug build files that had many branching options. 
This new message function can print the base types of the language: strings, ints, arrays and arrays thereof.
Call | Output
----- | ---------
`message('Hello')` | Hello
`message(5)` | 5
`message(['Hello', 5])` | ['Hello', 5]
> Make the message() function able to print out user defined types.

- meson.py
To ensure that people will not confused that something won't work.
Related: https://github.com/miit-pm/RWD/pull/1#issuecomment-102607931
> introduce check python version in meson.py

- test cases/vala/4 config/config.vapi
- test cases/vala/4 config/meson.build
- test cases/vala/4 config/prog.vala
> tests: add negative test against #117

- compilers.py
- interpreter.py
- test cases/common/83 has type/meson.build
> add has_type method

- dependencies.py
> don't print twice about not found dependency. Closes #128

- dependencies.py
- modules/gnome.py
With these two commits my Gir gets built with no hassle :)
> Fix library introspection

- dependencies.py
> dependencies: Undefined variable 'required'. Closes #154

- dependencies.py
> dependency: Undefined variable 'type_string'. Closes #156

- compilers.py
> compilers: fix can_compile. Closes #189

- dependencies.py
- ninjabackend.py
- test cases/vala/5 target glib/GLib.Thread.vala
- test cases/vala/5 target glib/meson.build
> vala: add support for --target-glib

- interpreter.py
- test cases/common/89 add language/meson.build
- test cases/common/89 add language/prog.c
- test cases/common/89 add language/prog.cc
Make it possible to add languages dynamically. One use case for this is adding Objective C support only in OSX and not force it on e.g. Windows where it is not used.
> Added the add_languages function.

- backends.py
- compilers.py
- cross/ubuntu-armhf.txt
- cross/ubuntu-faketarget.txt
- cross/ubuntu-mingw.txt
- environment.py
- interpreter.py
- meson.py
- ninjabackend.py
- test cases/common/26 endian/meson.build
- test cases/common/31 find program/meson.build
- test cases/common/38 run program/meson.build
- test cases/common/55 file grabber/meson.build
- test cases/common/59 object generator/meson.build
- test cases/objc/2 nsstring/meson.build
- test cases/prebuilt object/1 basic/meson.build
This patchset makes the cross compilation work properly. It adds:
- the concept of build, host and target
- full canadian cross support
- target-only builds that use the host compilers (for compiling a cross-compiler)
It has only been tested with the unit tests, not with actual projects. I don't have those handy. It would be nice to get feedback from actual cross compilation people before merging this.
> Cross compilation

- data/macros.meson
> macros.meson: simplify RPM macros by using expand

- build.py
- interpreter.py
- mesonintrospect.py
- ninjabackend.py
- test cases/common/90 identical target name in subproject/bar.c
- test cases/common/90 identical target name in subproject/meson.build
- test cases/common/90 identical target name in subproject/subprojects/foo/bar.c
- test cases/common/90 identical target name in subproject/subprojects/foo/meson.build
Make it possible to have top level targets with the same name in subprojects. Fixes #222.
> Fix introspection

- backends.py
- build.py
- interpreter.py
- ninjabackend.py
- test cases/common/49 subproject/installed_files.txt
- test cases/common/49 subproject/meson.build
- test cases/common/49 subproject/subprojects/sublib/meson.build
Supersedes the first depmanifest MR.
> Add version numbers to projects and generate a dep manifest.

- backends.py
- compilers.py
- coredata.py
- meson.py
- mesonconf.py
Proposal for new togglable warning level. Roughly:
Level 1: -Wall
Level 2: -Wall -Wpedantic
Level 3: Absolutely everyting (-Weverything on Clang)
> Added warning level option.

- cross/iphone.txt
- environment.py
- ninjabackend.py
Created iphone cross file and made it possible to specify compile and link args in the cross file.
> Add cross arguments

- authors.txt
- dependencies.py
This adds .dylib detection (was hardcoded to .so lib detection) to BoostDependency.
> BoostDependency dylib detection added.

- ninjabackend.py
Windows has very small command line character limit so use rspfiles instead.
> Use rspfile on Windows

- data/macros.meson
> rpm macros: export *FLAGS

- authors.txt
- meson.py
- mesonconf.py
- mesonlib.py
this accommodates passing big configuration to meson and mesonconf where the command line maximum length is too low
> Added support for extended command line to overcome OS command line length limitation.

- dependencies.py
- modules/gnome.py
> gnome: Link against dependencies when building the gir files

- mesonbuild/backend/backends.py
- test cases/common/107 postconf/postconf.py
- test cases/common/108 postconf with args/postconf.py
> pass meson source and build dirs as env variables for postconf scripts

- test cases/common/50 subproject options/subprojects/subproject/meson.build
Fixes a copy-paste error in the test error message.
> fix test error message

- authors.txt
- mesonbuild/interpreter.py
- test cases/common/42 string formatting/meson.build
Some more string functions which I found missing.
> Add more string funcs: to_upper(), to_lower(), contains() and underscorify()

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
This fixes a bunch of stuff with generators in the vs2010 backend, especially how paths are handled.
Also, it adds support for `@EXTRA_ARGS@`.
> vs2010: fix generators, support @EXTRA_ARGS@

- mesonbuild/backend/vs2010backend.py
Adds support for private include dirs.
> vs2010: support private include dirs

- mesonbuild/backend/vs2010backend.py
Add all files in `extra_files` to the project to make them visible in the IDE.
> vs2010: add extra_files to project

- mesonbuild/backend/vs2010backend.py
> vs2010: fix transitive dependencies

- mesonbuild/environment.py
- run_tests.py
This brings a big speedup as currently the limiting factor is running Meson rather than source compilation.
> Run tests in parallel

- mesonbuild/backend/vs2010backend.py
The /D switch strips any quotes except when they are escaped.
Fixes test case 104.
> vs2010: replace " with \" in /D command line args

- mesonbuild/environment.py
- run_tests.py
This properly fixes parallel `meson` unit tests on Windows.
> Windows parallel test

- run_tests.py
Instead of printing the test name and the status on two successive lines, only print a single line for succeeded tests and two lines for failed tests.
This makes the output less verbose, yet easier to scan for failed tests.
Before:
> Running test: test cases/common/1 trivial
> Success
> Running test: test cases/common/2 cpp
> Success
> Running test: test cases/common/3 static
> Success
> Running test: test cases/common/4 shared
> Success
> Running test: test cases/common/5 linkstatic
> Fail: Compiling source code failed.
> Running test: test cases/common/6 linkshared
> Success
> Running test: test cases/common/7 mixed
> Success
After:
> Succeeded test: test cases/common/1 trivial
> Succeeded test: test cases/common/2 cpp
> Succeeded test: test cases/common/3 static
> Succeeded test: test …
> simplify unit test output

- mesonbuild/scripts/meson_test.py
> Fix a bug (typo) seen when printing the logs from failed tests.

- mesonbuild/environment.py
Without this it's really hard to debug why no compilers could be detected by Meson; especially in the cross-compilation case
> On failure, print exceptions encountered while searching for compilers

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
This fixes test case 103 for the `vs2010` backend.
> vs2010: fix many gen test case

- mesonbuild/compilers.py
- test cases/common/43 has function/meson.build
Fixes https://github.com/mesonbuild/meson/issues/530.
> cc.has_function: Also detect implementations and redefinitions by a provided header

- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/interpreter.py
- mesonbuild/mesonmain.py
- mesonbuild/modules/i18n.py
- mesonbuild/scripts/gettext.py
- mesonbuild/scripts/meson_install.py
- test cases/frameworks/6 gettext/meson.build
- test cases/frameworks/6 gettext/po/intltest.pot
- test cases/frameworks/6 gettext/po/meson.build
Should probably make gettext use the standard primitives rather than having a custom item as it increases the workload of backend developers. Not yet done because it turned out to be a bit more work than expected.
> Moved gettext into i18n module.

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- test cases/common/59 object generator/meson.build
- test cases/common/59 object generator/prog.c
- test cases/common/59 object generator/source3.c
Also fixed the `59 object generator` test case to test for this.
> vs: fix generators that use indexed output replacements (like @OUTPUT0@)

- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/vs2015backend.py
- mesonbuild/coredata.py
- mesonbuild/mesonmain.py
- run_tests.py
> Implement vs2015 backend

- mesonbuild/dependencies.py
- mesonbuild/interpreter.py
- mesonbuild/mesonlib.py
- test cases/linuxlike/5 dependency versions/meson.build
- test cases/linuxlike/5 dependency versions/subprojects/somelib/meson.build
- test cases/linuxlike/5 dependency versions/subprojects/somelibnover/meson.build
- test cases/linuxlike/5 dependency versions/subprojects/somelibver/meson.build
Add various tests for versioned dependency checking
interpreter: Compare the version of a cached dependency() before using it
interpretor: Correctly check the version of a fallback dependency
interpreter: Set declare_dependency version from the project version if missing
mesonlib: Fix typo in version_compare error
Also reuse subproject-based fallback dependencies
interpreter: Check if subproject version is defined before comparing
> Several fixes to how versioned dependencies are handled + tests

- mesonbuild/backend/ninjabackend.py
- test cases/linuxlike/6 subdir include order/meson.build
- test cases/linuxlike/6 subdir include order/prog.c
- test cases/linuxlike/6 subdir include order/subdir/glib.h
Fixes #604. Also includes a linuxlike test for the same (needs glib-2.0 as a pkg-config dep).
> Add subdir includes before external dep includes

- mesonbuild/compilers.py
Otherwise the changes ripple upstream and modify extra_args in the callee
> compilers: Copy extra_args whenever we modify it

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers.py
Ninja redirects stdout/stderr so by default GCC thinks it is not talking to a terminal.
> Enable colored output with GCC.

- mesonbuild/backend/ninjabackend.py
> ninja: Remove duplicated if check

- mesonbuild/coredata.py
I was working on using tuples for default values everywhere instead of lists so we get immutability for free, and these were useful in figuring out what needed fixing.
Will finish and post that patch later; probably after our next release.
> coredata: Descriptive parser exceptions for UserStringArrayOption

- mesonbuild/dependencies.py
- mesonbuild/interpreter.py
Also cleans up the `__init__` function of `PkgConfigDependency` a little bit.
> Various fixes that improve errors and logging around pkg-config dependencies

- mesonbuild/backend/ninjabackend.py
- mesonbuild/environment.py
- test cases/common/8 install/installed_files.txt
- test cases/common/8 install/meson.build
Same as #656 but without metaprogramming.
> Fix library directory handling

- mesonbuild/interpreter.py
> interpreter: Print what subproject dir could not be found

- test cases/common/86 same basename/meson.build
- test cases/common/86 same basename/sub/meson.build
This reverts 15ab984d8e2cf396be385d7515f72561c3cbaaa2
Also see #459
> test common/86: Move static library back

- mesonbuild/dependencies.py
I think this just got lost along the way.
> 'name' needs to be 'self.name' in DependencyException

- authors.txt
- mesonbuild/modules/pkgconfig.py
EDIT: Oh just noticed there is another PR for using context managers so removed that commit from here
> Minor pkgconfig module cleanups

- mesonbuild/dependencies.py
> Prefer pkg-config to sdl2-config.

- mesonbuild/build.py
- mesonbuild/interpreter.py
- mesonbuild/scripts/meson_test.py
- test cases/common/48 test args/envvars.c
- test cases/common/48 test args/meson.build
Allowing user to extend an existing path instead of overriding it
> Add a new 'environment' object to be used to build test environment

- mesonbuild/interpreter.py
So user can activate/deactivate features based on it.
> Add a meson.version() method returning the version of meson in use

- mesonbuild/compilers.py
Fixes https://github.com/mesonbuild/meson/issues/242
> compilers: Fall back to -pedantic with older GCC

- mesonbuild/backend/backends.py
It was making a trivially incorrect check
> ninja: Fix checking of exe_wrapper for CustomTargets

- mesonbuild/backend/ninjabackend.py
- test cases/vala/8 generated source/installed_files.txt
- test cases/vala/8 generated source/meson.build
- test cases/vala/8 generated source/src/config.vala.in
- test cases/vala/8 generated source/src/meson.build
- test cases/vala/8 generated source/src/test.vala
- test cases/vala/8 generated source/tools/meson.build
Want to verify that it fails on the CI. The next commit will be a patch to fix this.
> Add a vala test for generated sources in subdirs

- mesonbuild/compilers.py
There is no test for this here, but one has been added to the unittest branch.
> Set soname with clang properly.

- mesonbuild/modules/gnome.py
Previously `install_dir` was entirely ignored and there is also a use-case for having separate install_dirs for each output.
Honestly removing `install_dir` seems reasonable but it was already documented API.
> gnome.generate_gir(): Fix install_dir and add install_dir_gir and install_dir_typelib

- mesonbuild/interpreter.py
- test cases/common/1 trivial/meson.build
This broke in 6590b7221e1e3a30b33a6b74b380ee5a2b24d7ef and we didn't have a test for it.
Once the CI verifies that it fails, I will add commits that fix it.
> Test arrays in languages for the project() method

- mesonbuild/interpreter.py
- test cases/common/119 pathjoin/meson.build
Let's see what the Windows build slave thinks of it.
> Created path_join function.

- test cases/vala/11 mixed sources/bar.vala
- test cases/vala/11 mixed sources/foo.c
- test cases/vala/11 mixed sources/meson.build
It is numbered to follow #634.
> Add a Vala test case for mixed sources

- mesonbuild/build.py
- mesonbuild/compilers.py
- mesonbuild/interpreter.py
- run_unittests.py
Default to it being on as it is less surprising.
> Add an option to select if static libraries are built with -fPIC.

- mesonbuild/modules/gnome.py
I hit this all the time, seems harmless to just handle it.
> gnome: Avoid unhandled exception

- mesonbuild/modules/i18n.py
- mesonbuild/scripts/gettext.py
Some projects use this to allow using local its files
> gettext: Add ability to set GETTEXTDATADIRS

- authors.txt
- mesonbuild/modules/pkgconfig.py
- test cases/common/51 pkgconfig-gen/meson.build
Prepend instead of appending a space so that we never end with a trailing space.
> Improvements for the pkgconfig module

- mesonbuild/dependencies.py
- mesonbuild/interpreter.py
- mesonbuild/modules/gnome.py
- test cases/linuxlike/1 pkg-config/meson.build
Needs #861 to be fully usable.
> Can query pkg-config variables from the system. Closes #726.

- mesonbuild/modules/gnome.py
> gnome: Fix building gobject-introspection with sanitizer

- mesonbuild/modules/i18n.py
- mesonbuild/scripts/gettext.py
~~Will need to be rebased for #916 but still~~ open for comments.
> gettext: Add update-po target

- mesonbuild/environment.py
- run_unittests.py
> The regex to detect version numbers needs to be a bit more complex.

- mesonbuild/interpreter.py
- test cases/common/120 subdir subproject/meson.build
- test cases/common/120 subdir subproject/prog/meson.build
- test cases/common/120 subdir subproject/prog/prog.c
- test cases/common/120 subdir subproject/subprojects/sub/meson.build
- test cases/common/120 subdir subproject/subprojects/sub/sub.c
- test cases/common/120 subdir subproject/subprojects/sub/sub.h
I haven't found any necessary reason in the code for this restriction.
> Allow subproject declarations in subdirectories

- mesonbuild/modules/i18n.py
- mesonbuild/scripts/gettext.py
This should be more reliable than hardcoded positions.
@tp-m can you verify it fixes your issue from #918
> gettext: Use argparse to handle arguments

- mesonbuild/backend/ninjabackend.py
Remove spurious closing bracket at end.
> ninjabackend: fix error message

- .travis.yml
Going to add more things to see how they work out and whether the time taken is reasonable.
> travis.yml: Run tests against both gcc and clang

- authors.txt
- contributing.txt
- mesonbuild/interpreter.py
Just a few minor things, a change of word on the contributing file and
use the exist_ok parameter on a makedirs call.
> Minor adjusts

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/mesonmain.py
- mesonbuild/mlog.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/pkgconfig.py
- mesonbuild/modules/qt4.py
- mesonbuild/modules/qt5.py
- mesonbuild/modules/rpm.py
- mesonbuild/scripts/yelphelper.py
Prepends the string with 'WARNING:' in ANSI yellow.
Closes https://github.com/mesonbuild/meson/issues/961
Looks quite nice. :)
> Implement mlog.warning and use it everywhere for warnings

- mesonbuild/scripts/scanbuild.py
> Can specify scan-build executable with an environment variable.

- mesonbuild/mesonmain.py
> Create target directory if it does not exist. Closes #935.

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/modules/gnome.py
I only tested the Ninja backend but it worked well.
> gnome: Use depfile support of recent glib-compile-resources

- mesonbuild/scripts/gtkdochelper.py
Also, only add it if it's defined.
Closes #1020
> scripts/gtkdochelper: ignore_headers is a list

- mesonbuild/compilers.py
- mesonbuild/interpreter.py
- test cases/common/37 has header/meson.build
Fixes #1026 
The test is a placeholder because I want to test if it works on Windows.
> cc.has_header: Allow specifying a prefix for headers

- test cases/common/95 dep fallback/meson.build
- test cases/common/95 dep fallback/subprojects/dummylib/meson.build
Tests https://github.com/mesonbuild/meson/issues/975
> tests: Optional fallback subprojects can fail

- mesonbuild/compilers.py
We currently pass cross-compiler options to the native compiler too and when cross-compiling from Windows to Linux, `options` will contain Linux-specific options which doesn't include `c_winlibs`.
The proper fix is to allow cross-info files to specify compiler options and to maintain both cross and native compiler options in `coredata`, but that will have to be done after the 0.36.0 release.
Also fixes a typo in MinGW `cpp_winlibs` option setting.
Closes #1029
> Hotfix for cross-compilation from Windows to Linux

- mesonbuild/dependencies.py
- mesonbuild/environment.py
Also convert a few other generic `except Exception`s to be more specific
Closes #1088
> Always catch PermissionError while looking for Ninja

- mesonbuild/backend/backends.py
- mesonbuild/build.py
- test cases/common/25 object extraction/lib2.c
- test cases/common/25 object extraction/meson.build
Closes #1097 
Also fixes the test so it exposes that bug.
> Only check for unity compat when doing unity builds

- mesontest.py
> Some fixes in mesontest

- mesonbuild/modules/gnome.py
Otherwise it will just fail on windows
> gnome: Properly search for programs

- mesontest.py
This is basically the same as #1124 without the part about rebuilding.
> mesontest misc fixes

- mesonbuild/backend/ninjabackend.py
- mesontest.py
Only supporting ninja backend for now.
> mesontest: Rebuild tests before running them when needed

- mesonbuild/modules/gnome.py
- test cases/frameworks/7 gnome/installed_files.txt
- test cases/frameworks/7 gnome/resources/meson.build
- test cases/frameworks/7 gnome/resources/resources.py
> gnome.compile_resources(): Add ability to output gresource bundles

- mesonbuild/modules/gnome.py
When generating the .gir file we need g-ir-scanner to link the
introspector binary against the right dependencies, for that
we used to use the --library option but this has a special meaning
and the libs passed in there end up being the ones in the .gir file
itself, which is not what we want.
A new --extra-library option is beeing added in goject-introspection
(https://bugzilla.gnome.org/show_bug.cgi?id=774625) to handle our use case
(ie. not using libtool which allows g-ir-scanner to know about those)
and we should make use of it.
Fixes #981
> Use (still to be added) g-ir-scanner --extra-library option to specify libraries the scanner needs to link with (but not concider 'main libraries')

- mesonbuild/modules/i18n.py
- mesonbuild/scripts/gettext.py
- Fix LINGUAS changes not being picked up
- Make empty languages acceptable
Fixes #1127
> i18n: Improve language handling

- mesonbuild/modules/gnome.py
- mesonbuild/scripts/gtkdochelper.py
This was the minimum to match glib's autotools usage and get it building.
> gnome: Various improvements to gtkdoc

- syntax-highlighting/vim/syntax/meson.vim
Also put them on one line each for easy updates.
> syntax-highlighting: Update list of builtin functions

- mesonbuild/modules/gnome.py
Without libtool it is our job to ensure local libraries are picked up.
> gnome.gtkdoc(): Include -rpath for gtkdoc-scangobj

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers.py
- test cases/common/130 no buildincdir/include/header.h
- test cases/common/130 no buildincdir/meson.build
- test cases/common/130 no buildincdir/prog.c
> Only add build dir inlude directives if the corresponding dir exists.

- .mailmap
> mailmap: add couple of aliases

- mesonbuild/interpreter.py
- mesonbuild/wrap/wrap.py
This reverts commit 541dd92ef7a10b0f657f3c8532ffb71a8d921f54, reversing
changes made to 155617e539a9aeccda6bd186398123b9d5521ed4.
> Revert "Merge pull request #1145 from AlexandreFoley/wrap-fix"

- mesonbuild/modules/gnome.py
This avoids searching for gobject-introspection multiple times which is displayed multiple times too:
```
Program g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
Native dependency gobject-introspection-1.0 found: YES 1.50.0
Native dependency gobject-introspection-1.0 found: YES 1.50.0
Native dependency gobject-introspection-1.0 found: YES 1.50.0
Native dependency gobject-introspection-1.0 found: YES 1.50.0
```
Also don't use `dependencies` as a module name since it is commonly used as a variable name too. Instead, directly import the classes that we use from that module.
> gnome: Re-use gobject-introspection-1.0 pkg-config dependency

- mesonbuild/scripts/commandrunner.py
- mesonbuild/scripts/delwithsuffix.py
- mesonbuild/scripts/depfixer.py
- mesonbuild/scripts/dirchanger.py
- mesonbuild/scripts/gtkdochelper.py
- mesonbuild/scripts/meson_exe.py
- mesonbuild/scripts/meson_install.py
- mesonbuild/scripts/regen_checker.py
- mesonbuild/scripts/scanbuild.py
- mesonbuild/scripts/symbolextractor.py
- mesonbuild/scripts/vcstagger.py
- mesonbuild/scripts/yelphelper.py
- mesonbuild/wrap/wraptool.py
> Remove shebangs on files inside module

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/coredata.py
- mesonbuild/mesonmain.py
- mesonbuild/scripts/cleantrees.py
- run_project_tests.py
This will catch things like #1220
I will add a commit that fixes this next.
> run_project_tests.py: Also do ninja clean on tests

- mesonbuild/dependencies.py
We were storing the pkg-config path on the class as a static variable -- `PkgConfigDependency.pkgbin`. When regenerating via Ninja, the found-deps were all cached in a pickled coredata, so if you had a statement that does `dep.get_pkgconfig_variable()`, it would raise an exception because the static class variables were per-meson-invocation.
To fix this, we store the pkg-config binary as both a class variable and an instance variable.
This is a 0.37 regression. It always worked fine in the previous release because we were only storing whether we had found the pkg-config path on the class and directly pass 'pkg-config' as a string to Popen instead of the found-external-program.
```
File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/meso …
```
> Store pkg-config path on the instance too

- authors.txt
- mesonbuild/mesonlib.py
as a second part of
https://github.com/mesonbuild/meson/issues/1085
> configure_file: Use utf-8 to write configured file

- syntax-highlighting/vim/indent/meson.vim
- syntax-highlighting/vim/syntax/meson.vim
I don't use vim so I have no idea if this works. Comments welcome.
> Vim syntax highlighting fixes. Closes #1241.

- mesonbuild/build.py
- mesonbuild/interpreter.py
- mesonbuild/modules/qt4.py
- mesonbuild/modules/qt5.py
- mesonbuild/modules/windows.py
It also means we can start accepting other types if needed by changing one location rather than 8.
> Add Generator.process_files to reduce code duplication.

- mesonbuild/scripts/scanbuild.py
> Use the correct directory for scan-build command.

- mesonbuild/compilers.py
- mesonbuild/environment.py
> fix for cross-builds targeting macosx

- mesonbuild/backend/backends.py
- run_unittests.py
Includes a unit test for the same.
Closes #1062
> serialise_executable: Name the data file deterministically

- mesonbuild/backend/ninjabackend.py
> backends/ninja: remove unused variable

- mesontest.py
Main change being that the ninja target "test" and mesontest now behave more similarly.
> Some mesontest related improvements.

- test cases/common/126 llvm ir and assembly/meson.build
Related to https://github.com/mesonbuild/meson/pull/1289 and https://github.com/mesonbuild/meson/issue/1287
> tests/common/126: Also skip unsupported CPUs here

- mesontest.py
Before:
Test summary: 1 OK, 0 FAIL, 0 SKIP, 0 TIMEOUT
After:
OK:         1
FAIL:       0
SKIP:       0
TIMEOUT:    0
> More readable total statistics.

- mesonbuild/mintro.py
We don't just blindly trust that, we check if `meson-private` exists in there. If not, we error out with a readable error.
Also fix running with backends other than Ninja by not assuming that install.dat is always available.
> mintro.py: Assume the current dir is a builddir if not specified

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers.py
- test cases/common/134 generated llvm ir/copy.py
- test cases/common/134 generated llvm ir/main.c
- test cases/common/134 generated llvm ir/meson.build
- test cases/common/134 generated llvm ir/square.ll.in
- test cases/common/135 generated assembly/copy.py
- test cases/common/135 generated assembly/main.c
- test cases/common/135 generated assembly/meson.build
- test cases/common/135 generated assembly/square-arm.S.in
- test cases/common/135 generated assembly/square-x86.S.in
- test cases/common/135 generated assembly/square-x86_64.S.in
- test cases/common/135 generated assembly/symbol-underscore.h
- test cases/frameworks/4 qt/meson.build
> Fix llvmir and assembly

- mesonbuild/mintro.py
The prefix has been recently added to the install data
> Fix mesonintrospect --installed

- mesonbuild/interpreterbase.py
- test cases/common/67 foreach/meson.build
If the index is out of range, the fallback value is used. Includes a test.
Closes #1337
> interpreter: Implement array.get(index, fallback)

- mesonbuild/coredata.py
- mesonbuild/mesonlib.py
- run_tests.py
- run_unittests.py
> Add our own implementation of os.path.commonpath

- mesonbuild/dependencies.py
- mesonbuild/interpreter.py
Going to add a test here first, then a fix for #1366.
> Cross-compilation fixes for pkg-config dependencies

- mesonbuild/modules/gnome.py
> gnome: Do not use gir specific `--extra-lib` to generate gtkdoc args

- syntax-highlighting/vim/syntax/meson.vim
New function: add_test_setup()
> Update vim syntax highlighting

- mesonbuild/environment.py
Fixes C and C++. Will fix the rest once CI has gone through one round.
> Fix compiler detection + cross when envvar not set.

- mesonbuild/modules/rpm.py
> rpm: Fix missing parenthesis and quotation mark

- mesonbuild/environment.py
> Fix undefined variables in ObjC/C++ detection

- mesonbuild/modules/gnome.py
> gnome.gdbus_codegen: Use --output-directory when available

- mesonbuild/mparser.py
- test cases/common/40 logic ops/meson.build
> fix logic operations

- .appveyor.yml
- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/vs2017backend.py
- mesonbuild/coredata.py
- mesonbuild/mesonmain.py
Adds a backend for VS2017, which partially implements #1390.
I will add auto detection of the VS version, soon.
> VS2017 backend

- mesonbuild/backend/ninjabackend.py
See #1485 for test case; I assume there are no performance test cases at the moment. Without running the profiler, speeds are little bit better than I said before (averaged over 10 runs):
* master 80f870c: 18.05±0.05s
* ~~Use an `OrderedDict` when deduping d07b22f: 3.52±0.05s (×5.12±0.07)~~
* Use a `list`+`set` 128e2a6: 3.52±0.07s (×5.12±0.10)
* With a cache for basic compiler args ~~6d9d268~~ 11f8d4a: 2.52±0.04s (×7.16±0.13)
Profile now looks like this:
You can make a _very_ small improvement (2.52±0.03s (×7.17±0.08)) by replacing `arg.startswith(prefixes)` with `arg[:2] in prefixes` in the `_can_dedup`/`_should_prepend` functions, but this assumes that all prefixes are 2 characters.
The caching is only based on global/subproject information; if the cache were made from all target …
> Compiler args performance enhancements

- .appveyor.yml
- mesonbuild/interpreter.py
See also: https://github.com/mesonbuild/meson/pull/1346#issuecomment-289446412
> Fix dep typo + reduce appveyor tests

- mesonbuild/interpreter.py
- test cases/common/95 dep fallback/meson.build
Closes https://github.com/mesonbuild/meson/issues/1474
> Allow not-required not-found dependencies in subprojects

- mesonbuild/interpreter.py
- test cases/common/16 configure file/generator-without-input-file.py
- test cases/common/16 configure file/installed_files.txt
- test cases/common/16 configure file/meson.build
> configure_file: make input arg optional if command is used

- test cases/linuxlike/11 runpath rpath ldlibrarypath/lib.c
- test cases/linuxlike/11 runpath rpath ldlibrarypath/lib1/meson.build
- test cases/linuxlike/11 runpath rpath ldlibrarypath/lib2/meson.build
- test cases/linuxlike/11 runpath rpath ldlibrarypath/main.c
- test cases/linuxlike/11 runpath rpath ldlibrarypath/meson.build
For details, see: https://github.com/mesonbuild/meson/issues/1383
> Test whether runpath/rpath override LD_LIBRARY_PATH

- .appveyor.yml
- mesonbuild/backend/vs2010backend.py
- run_cross_test.py
- run_project_tests.py
- run_tests.py
- run_unittests.py
Initial commits lay the groundwork for this, but don't run it on anything except Ninja yet.
> Run unit tests on more backends

- mesonbuild/backend/ninjabackend.py
- mesonbuild/environment.py
- test cases/windows/7 mingw dll versioning/installed_files.txt
> Fix shared module installation directory on Windows

- mesonbuild/interpreter.py
Closes https://github.com/mesonbuild/meson/issues/1600
> install scripts: Actually check if it was found

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/build.py
- run_unittests.py
- test cases/common/22 header in file list/prog.c
- test cases/common/64 custom header generator/meson.build
+ fix `depend_files:` in custom targets on VS
+ pretty-print all XML in vcxproj files
> Test that build and custom targets are rebuilt on changes

- mesonbuild/backend/ninjabackend.py
- test cases/vala/7 shared library/installed_files.txt
- test cases/vala/7 shared library/lib/meson.build
- test cases/vala/9 gir/installed_files.txt
- test cases/vala/9 gir/meson.build
For generated headers, vapis, and GIRs.
https://github.com/mesonbuild/meson/pull/1469#issuecomment-292814000
> vala: Allow installation into default directories

- mesonbuild/dependencies.py
... based on the compiler object
This addresses issue #1569
The other dependencies probably need to be updated as well...
> dependencies: boost: use system include flag for header includes

- test cases/frameworks/5 protocol buffers/meson.build
> tests: skip protocol buffers test if deps are not found

- mesonbuild/modules/gnome.py
Might not actually fix #1648. This is a random stab in the dark, basically.
> Stricter evaluation of deps. Closes #1648.

- mesonbuild/backend/ninjabackend.py
- mesonbuild/environment.py
- run_unittests.py
Tests https://github.com/mesonbuild/meson/issues/1646
> Fix LTO + static libraries on GCC and Clang

- authors.txt
- mesonbuild/wrap/wrap.py
These changes seem to work well enough.
> wrap: submodule fixes

- mesonbuild/backend/ninjabackend.py
Not actually tested, please verify that this works. Thanks.
> Replace cmd line arguments on install scripts. Closes #1681.

- data/macros.meson
With ability to change it if needed.
> rpm: pass --wrap-mode=nodownload to %meson

- docs/markdown/Vala.md
Cover installation using the `install_dir` array and the additional arguments for specifying the C header, VAPI and GIR names.
> Update Vala documentation with most recent changes

- docs/markdown/howtox.md
.. and remove an obsolete wiki home link at the bottom of the page
> howtox.md: fix header hierarchy

- docs/markdown/Dependencies.md
This is the documentation for the feature added in b89af8b
> deps: boost: add some documentation about environment variables

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
Once this is merged we can start adding `assert(isinstance(x, File))` to every thing that _should_ be a file.
> Kill RawFile dead!

- run_project_tests.py
If tests fail in CI systems you can't log into, the information is lost. Currently happening in Debian reproducible build machines (only on arm32).
> Store and print test logs of executed projects.

- docs/markdown/Reference-manual.md
- docs/markdown/Release-notes-for-0.41.0.md
- mesonbuild/interpreter.py
- test cases/common/73 vcstag/meson.build
two doc fixes, one to bail out early if the kwargs don't contain the required bits
> fixes for vcs_tag

- docs/markdown/Release-notes-for-0.41.0.md
- mesonbuild/backend/ninjabackend.py
- test cases/common/149 special characters/check_quoting.py
- test cases/common/149 special characters/installed_files.txt
- test cases/common/149 special characters/meson.build
The first commit pulled out of #1434; should fix #1643.
> ninja: Fix quoting newlines and $

- mesonbuild/build.py
> Make name_suffix keyword known to binaries

- docs/markdown/Reference-manual.md
> docs: how to make find_program() search additional directories

- mesonbuild/backend/vs2010backend.py
> vs: surround project guid with '{}'

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers.py
It will likely conflict with #954 as `generate_basic_compiler_args` already deal with global arguments.
> Use 'generate_basic_compiler_args' for Vala targets

- docs/markdown/Reference-manual.md
note: lacking a windows machine, I'm not sure the windows part of the test works
> two doc fixes

- docs/markdown/Release-notes-for-0.41.0.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/compilers.py
- test cases/rust/1 basic/meson.build
This is a bit ugly so alternatives are welcomed but this is functional for now.
> rust: Add rust_args kwarg

- mesonbuild/mconf.py
mesonconf prints build dir information in the order of
'Option' 'Description' 'Current Value' and, optionally, 'Possible Value'.
The Description tends to be longer and push the following values far
right, sometimes way far than fits in the full screen size of a
terminal on a FullHD monitor.
Experienced users know which options they want to change without
looking at the description string however they need to check the
current values for sure.
This patch moves the description to the last column.  Now mesonconf
prints options in the following order:
'Option' 'Current Value' 'Possible Value' 'Description'
To implement this, mainly print_aligned() is modified.  The second
argument of the function is changed from
- array of array of string to
- array of dict with 'name', 'descr', 'value', and …
> mesonconf: reorder output columns

- docs/markdown/Overview.md
I am not sure what word was meant to be written, but I think _should_ is suitable.
> Change repeated word

- docs/markdown/Reference-manual.md
- mesonbuild/build.py
- test cases/common/152 link depends custom target/foo.c
- test cases/common/152 link depends custom target/make_file.py
- test cases/common/152 link depends custom target/meson.build
- test cases/windows/11 vs module defs generated custom target/meson.build
- test cases/windows/11 vs module defs generated custom target/prog.c
- test cases/windows/11 vs module defs generated custom target/subdir/make_def.py
- test cases/windows/11 vs module defs generated custom target/subdir/meson.build
- test cases/windows/11 vs module defs generated custom target/subdir/somedll.c
Allow vs_module_defs to use a custom_target
Add a test and update documentation
> Allow vs_module_defs to use a custom_target

- .appveyor.yml
- .coveragerc
- .gitignore
- .travis.yml
- README.md
- ci/appveyor-install.bat
- ci/appveyor-test.sh
- ci/run-in-cygwin.bat
- docs/markdown/Release-notes-for-0.41.0.md
- run_tests.py
Let's see if this works without me setting up anything; then we'll see if it's useful...
> Enable code coverage

- contributing.txt
- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2015backend.py
- mesonbuild/backend/xcodebackend.py
- mesonbuild/build.py
- mesonbuild/mesonmain.py
- mesonbuild/scripts/depfixer.py
- mesonbuild/scripts/dist.py
- mesonbuild/wrap/wrap.py
After submitting a pull request and then to get 80 warnings from the Flake8 CI I thought it would be helpful to include something about Flake 8 in the contributor documentation.
> Add Flake8 to contributor docs

- docs/markdown/Adding-arguments.md
- docs/markdown/Comparisons.md
- docs/markdown/Compiler-properties.md
- docs/markdown/Creating-Linux-binaries.md
- docs/markdown/Reference-manual.md
- docs/markdown/Subprojects.md
Destination is the Markdown filename.
> docs: Fix broken page links

- docs/markdown/Syntax.md
> Document that user-defined functions and methods are unsupported

- docs/markdown/Reference-manual.md
- docs/markdown/Release-notes-for-0.41.0.md
- mesonbuild/interpreter.py
- test cases/common/16 configure file/basename.py
- test cases/common/16 configure file/file_contains.py
- test cases/common/16 configure file/meson.build
- test cases/common/16 configure file/touch.py
Closes: https://github.com/mesonbuild/meson/issues/1863
> add `capture: true` ability to configure_file()

- mesonbuild/dependencies/dev.py
- mesonbuild/dependencies/ui.py
- test cases/frameworks/9 wxwidgets/meson.build
- test cases/linuxlike/5 dependency versions/meson.build
Also adds a test so that this is catched later.
Closes https://github.com/mesonbuild/meson/issues/1937
> valgrind: Fix __init__ call

- docs/markdown/Gnome-module.md
> docs: Fix version reference

- run_project_tests.py
- run_tests.py
Bold the section names and colourize errors&skips. Also colourize the final count project tests. I though marking every successful test might be a bit much, but it could also be done.
> Add some colour to test output.

- mesonbuild/backend/ninjabackend.py
- test cases/vala/7 shared library/lib/meson.build
Closes https://github.com/mesonbuild/meson/issues/1969
> vala: Only add --use-header for unity builds

- mesonbuild/modules/gnome.py
Fixes #1910 (Please test @hughsie)
> Fix gnome.generate_gir() with address sanitizer

- docs/markdown/Qt5-module.md
When I tried to make a Qt project, it did not work at first, until I actually read the meson code to figure it out.  I hope my improvement helps someone.
> Improve the example by explaining modules

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/c.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/cs.py
- mesonbuild/compilers/objc.py
- mesonbuild/compilers/objcpp.py
- mesonbuild/interpreter.py
I did not search through all the codebase, but it could be worth to use it wherever possible to present languages in a friendly way.
> Add 'Compiler.get_display_language'

- mesonbuild/environment.py
Lists are not hashable.
Closes https://github.com/mesonbuild/meson/issues/1989
> environment: Fix exception when no defines were found

- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cs.py
I wanted to push these two, but #1996 got merged earlier than I have expected.
> More usages of 'get_display_language' and a fix for C#

- mesonbuild/dependencies/misc.py
... not when getting compiler and link arguments
Would be nice to have some tests, but that requires boost in a
non-standard location.
> dependency: boost: only consult environment at initial stage

- mesonbuild/dependencies/ui.py
Fixes issue 1979.
Adds linking to debug libraries on Windows.
> Qt4 support

- docs/markdown/Release-notes-for-0.42.0.md
Per @TingPing's suggestion on the previous PR
> Add changelog for Rust crate-type support

- mesonbuild/build.py
I haven't really encountered a problem with this, it just caught my eye and looked wrong...
> Update args_frozen attribute check.

- mesontest.py
Fixes traceback like:
```pytb
Only ninja backend is supported to rebuild tests before running them.
File "./mesontest.py", line 616, in <module>
sys.exit(run(sys.argv[1:]))
File "./mesontest.py", line 607, in run
th = TestHarness(options)
File "./mesontest.py", line 177, in __init__
self.load_datafile(os.path.join(options.wd, 'meson-private', 'meson_test_setup.dat'))
File "./mesontest.py", line 383, in load_datafile
self.load_tests()
File "./mesontest.py", line 378, in load_tests
with open(self.datafile, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '.../meson/meson-private/meson_test_setup.dat'
```
> Print real error if mesontest used on invalid directory.

- mesonbuild/backend/xcodebackend.py
- mesonbuild/dependencies/ui.py
- mesonbuild/interpreter.py
- mesonbuild/scripts/depfixer.py
- mesonbuild/scripts/vcstagger.py
- tools/ac_converter.py
- tools/cmake2meson.py
I ran the code through the analyzer at lgtm.com. This MR fixes the low hanging fruit.
> Static analyzer fixes

- .appveyor.yml
- .travis.yml
- ci/appveyor-install.bat
- mesonbuild/backend/ninjabackend.py
- mesonbuild/environment.py
- run_tests.py
This reverts commit aab7ada356e02033e4030143cf363d06d975283b, reversing
changes made to e1b24765afd9e7d2d8043a408d69c7ad814d3551.
> Revert "Merge pull request #1931 from centricular/use-patched-ninja"

- mesonbuild/build.py
Caused due to improper call to hasattr.
> Fix of TypeError when using custom target in dependencies

- mesonbuild/compilers/compilers.py
- test cases/common/153 recursive linking/edge-cases/libsto.c
- test cases/common/153 recursive linking/edge-cases/meson.build
- test cases/common/153 recursive linking/edge-cases/shstmain.c
- test cases/common/153 recursive linking/edge-cases/stobuilt.c
- test cases/common/153 recursive linking/edge-cases/stomain.c
- test cases/common/153 recursive linking/meson.build
- test cases/common/153 recursive linking/shnodep/meson.build
Closes https://github.com/mesonbuild/meson/issues/2096
> CompilerArgs: Put start/end-group around shared libs too

- mesonbuild/scripts/meson_install.py
Try to restore the context for SELinux. If we fail on running
'selinuxenabled', quietly ignore the error and continue. If we fail on the
actual restorecon call, we print a message but disable SELinux - chances are
high that if one restorecon fails, others will too and that's likely a system
setup issue.
Fixes #1967
> install: restore the SELinux context on install

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/vala.py
> Vala: enable colored warning and error output

- mesonbuild/scripts/meson_install.py
- mesonbuild/scripts/uninstall.py
If a directory was created during ninja install, remove it again during ninja uninstall
https://github.com/mesonbuild/meson/issues/2032
> Remove created directories on ninja uninstall

- mesonbuild/modules/gnome.py
- test cases/frameworks/7 gnome/gir/meson.build
- test cases/frameworks/7 gnome/resources/meson.build
- test cases/frameworks/7 gnome/schemas/meson.build
Closes https://github.com/mesonbuild/meson/issues/2174
> gnome: Allow passing build_by_default: to some functions

- docs/markdown/Cross-compilation.md
- docs/markdown/Design-rationale.md
- docs/markdown/Gnome-module.md
- docs/markdown/Manual.md
- docs/markdown/Pkgconfig-module.md
- docs/markdown/Python-3-module.md
- docs/markdown/Qt4-module.md
- docs/markdown/Qt5-module.md
- docs/markdown/RPM-module.md
- docs/markdown/Reference-manual.md
- docs/markdown/Reproducible-builds.md
- docs/markdown/Windows-module.md
- docs/markdown/Wrap-best-practices-and-tips.md
- docs/markdown/Wrap-dependency-system-manual.md
- docs/markdown/Wrap-review-guidelines.md
- docs/markdown/i18n-module.md
Also line wrapping around modified args.
> More doc alphabetisation

- mesonbuild/modules/gnome.py
Hi,
On Windows, there is a limit of 8192 characters per command line, which is likely to cause problems for introspection for larger libraries and items where many headers and sources need to be scanned, causing strange errors as the command is either rejected or incomplete.
In order to address this, create a filelist using the sources and headers that we need to scan use the --filelist option of g-ir-scanner that exists for this exact reason.
> modules/gnome.py: Use a filelist for generate_gir() to limit commandline lengths

- run_project_tests.py
Just an experiment to see what would happen. Ninja is probably faster, msbuild might or might not be slower.
> Try to use 2x the number of cores.

- docs/markdown/Gnome-module.md
- mesonbuild/modules/gnome.py
- test cases/frameworks/7 gnome/gdbus/meson.build
This is a bit ugly of a syntax but I think it is the best we can do.
> gnome.gdbus_codegen(): Add annotations keyword

- mesonbuild/mesonlib.py
Fixes #1586
It's not a full package version comparison but being benevolent here shouldn't cause any harm.
> Allow version labels with trailing dots

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/cross_find.md
- mesonbuild/interpreter.py
- run_unittests.py
- test cases/unit/12 cross prog/meson.build
- test cases/unit/12 cross prog/some_cross_tool.py
- test cases/unit/12 cross prog/sometool.py
> Permit overriding find_program from the cross file.

- mesonbuild/mesonmain.py
ref #2163 
ref #1991 
Updated message to tell users to wipe their build directory if they're having issues. Also restructured things a bit. Anything else we'd want in this message?
> Update message for already configured builddir

- msi/createmsi.py
Some minor changes to correctly find python on more systems
> Improve msi

- mesonbuild/mesonmain.py
- mesonbuild/mlog.py
Similar to configure
Closes https://github.com/mesonbuild/meson/issues/2316
> logging: Print location of log file on error

- .appveyor.yml
- .travis.yml
- ci/appveyor-install.bat
- mesonbuild/backend/ninjabackend.py
- mesonbuild/environment.py
- run_tests.py
This reverts commit 5eb64a6f3e47b570f544524ef48dc6ef0e4dce59.
> Let's try QuLogic's ninja patches again.

- mesonbuild/interpreter.py
- run_unittests.py
- test cases/common/47 options/meson.build
- test cases/unit/13 reconfigure/meson.build
> Fix get_option() for base options on reconfigure.

- mesonbuild/build.py
- mesonbuild/compilers/c.py
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/misc.py
- mesonbuild/dependencies/ui.py
- mesonbuild/interpreter.py
- mesonbuild/mesonlib.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/pkgconfig.py
- mesonbuild/modules/qt4.py
- mesonbuild/modules/qt5.py
- mesonbuild/modules/unstable_simd.py
- mesonbuild/modules/windows.py
Hello this PR isn't finished yet.
The idea is to discuss around some refactoring ideas.
First I would like to have some feedback on introducing a simple listify function to remove some 'noisy' code. If it's ok I'll convert more code.
Then maybe a more convenient function would directly parse kwargs, some extract function like this:
```python
def extract(dict_object, keys):
return listify(*[dict_object.get(key,[]) for key in keys ])
```
So it could be called like this:
```
c_pchlist, cpp_pchlist = extract(kwargs,['c_pch', 'cpp_pch'])
```
> Some refactoring, introduction of listify function.

- .appveyor.yml
- mesonbuild/mesonlib.py
Forward ported and tested version of #1482.
> Do not use universal newlines on old Python versions.

- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/build.py
- test cases/common/98 gen extra/meson.build
- test cases/common/98 gen extra/name.l
- test cases/common/98 gen extra/srcgen2.py
> Add @PLAINNAME@ and @BASENAME@ to arguments argument for Generator

- mesonbuild/dependencies/dev.py
- test cases/frameworks/15 llvm/meson.build
Some small cleanups for the LLVM module, mostly these fix small bugs and fix a few tests. There shouldn't be anything too contentious here I hope.
> Llvm cleanups

- mesonbuild/wrap/wrap.py
the behavior of download patch should
keep same as download package.
fix issue: #2384
> Don't download patch archive if already download

- run_tests.py
Will help us figure out the occasional ninja loops we see in our CI:
https://github.com/mesonbuild/meson/pull/2394#issuecomment-333340112
https://travis-ci.org/mesonbuild/meson/jobs/281637736
> tests: Always run ninja with -d explain

- docs/markdown/Gnome-module.md
- mesonbuild/modules/gnome.py
- test cases/frameworks/7 gnome/gir/dep1/meson.build
This is a commonly used flag so lets make it more obvious.
See also hughsie/colord#57
> gnome: Add header kwarg to generate_gir()

- msi/createmsi.py
I have _no_ idea if this works or not. Someone who knows please test & let us know. Probably requires VS2017 to be installed.
I made the install point to INSTALLDIR instead of TARGETDIR since it's the same change I have had to do elsewhere as well.
> Package the Visual C runtime. Closes #2417.

- mesonbuild/optinterpreter.py
- test cases/common/140 get define/meson_options.txt
- test cases/failing/62 bad option argument/meson.build
- test cases/failing/62 bad option argument/meson_options.txt
I keep typoing "value", and this didn't seem like a problem that would be hard to fix. It turns out that even the included test suite has invalid arguments.
> options: Add a permitted_kwargs function

- test cases/frameworks/4 qt/meson.build
- test cases/frameworks/4 qt/plugin/plugin.cpp
- test cases/frameworks/4 qt/plugin/plugin.h
> Fixes Qt4 plugin build and mixed Qt4/Qt5 tests builds.

- data/macros.meson
References: https://bugzilla.redhat.com/show_bug.cgi?id=1500248
> rpm: print test logs on failure

- man/meson.1
- man/mesonintrospect.1
Copy/paste typo in mesonintrospect(1), and remove references to `mesonconf` in meson(1)
> Couple fixes for the man pages

- mesonbuild/dependencies/misc.py
- tools/boost_names.py
> Boost: Jamfile has two syntaxes for boost libraries

- mesonbuild/interpreter.py
Please review and let me know if there is any issue.
> Do not allow escaping the subprojects directory. (Fixes #2306)

- mesonbuild/scripts/regen_checker.py
Fixes #2461
This works for me. I'm pretty sure this isn't the proper way to solve the issue though..
> MSI: Fix regenerate with visual studio

- test cases/common/162 wrap file should not failed/meson.build
- test cases/common/162 wrap file should not failed/src/meson.build
- test cases/common/162 wrap file should not failed/src/subprojects/foo/prog2.c
- test cases/common/162 wrap file should not failed/src/subprojects/prog.c
- test cases/common/162 wrap file should not failed/subprojects/zlib-1.2.8/foo.c
- test cases/failing/63 subproj filegrab/meson.build
- test cases/failing/64 grab subproj/meson.build
- test cases/failing/64 grab subproj/subprojects/foo/meson.build
- test cases/failing/64 grab subproj/subprojects/foo/sub.c
- test cases/failing/65 grab sibling/meson.build
- test cases/failing/65 grab sibling/subprojects/a/meson.build
- test cases/failing/65 grab sibling/subprojects/b/meson.build
- test cases/failing/65 grab sibling/subprojects/b/sneaky.c
> Add a bunch of tests to sandboxing.

- .travis.yml
- ciimage/Dockerfile
- cross/ubuntu-armhf.txt
- run_tests.py
- test cases/frameworks/17 mpi/is_artful.py
- test cases/frameworks/17 mpi/meson.build
This can't be merged until the next Ubuntu release is out because GCC 7 is not in the CI image. Putting this out there just so we don't forget.
> Use GCC 7 for cross compilation tests.

- mesonbuild/interpreter.py
With this, the build will be regenerated if a script, or one of its inputs gets modified.
> run_command: add command and files as build dependencies

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/warning_function
- mesonbuild/interpreter.py
This is a simple implementation for #2405, as always, feedback is welcome.
> interpreter: Add warning function

- docs/markdown/Using-wraptool.md
- docs/markdown/Wrap-dependency-system-manual.md
While reading the documentation I've found this two small things to change.
> Small changes for syntax hightlight

- mesonbuild/scripts/gtkdochelper.py
> gtkdoc: Pass the linker down to gtkdoc-scangobj

- mesonbuild/dependencies/dev.py
f.ex when you don't have the llvm-static package installed, the error message when generating libs is cryptic and uninformative since we discard stderr.
cc @dcbaker
> llvm: Output stderr when generating libs/flags/etc fails

- mesonbuild/scripts/meson_install.py
Locally, this reduces the test suite time from 3m12s to 2m57 or ~7.8%.
Fixes #2596.
cc @chergert
> Coalesce restorecon calls into one.

- mesonbuild/dependencies/base.py
https://en.wikipedia.org/wiki/Batch_file
> Allow cmd script extension on Windows

- .appveyor.yml
Break long line using temporary.
> Fix AppVeyor script

- ciimage/Dockerfile
- docs/markdown/Qt5-module.md
- mesonbuild/dependencies/ui.py
- mesonbuild/modules/qt.py
- test cases/frameworks/4 qt/meson.build
- test cases/frameworks/4 qt/q5core.cpp
- test cases/frameworks/4 qt/qt4core_fr.ts
- test cases/frameworks/4 qt/qt5core_fr.ts
> Add qt translations

- mesonbuild/mconf.py
Not knowing the possible values made me run into [this error](https://github.com/mesonbuild/meson/pull/2390#issuecomment-347227715).
> mconf: print choices of base options

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/if-found.md
- mesonbuild/interpreter.py
- test cases/common/165 subdir if_found/meson.build
- test cases/common/165 subdir if_found/subdir/meson.build
Extracted from the dolphin branch since this is useful on its own.
> Add if_found kwarg to subdir().

- docs/markdown/Reference-manual.md
Followup for 1540e615f13503722f1067c693f3d394218cbd9e.
> docs: note when warning() was added

- mesonbuild/dependencies/misc.py
- test cases/osx/3 has function xcode8/meson.build
I noticed a few things don't work correctly on macOS 10.13 as I've been trying to get mesa building there.
> macos 10.13 fixes

- mesonbuild/mtest.py
When `ninja -C builddir/ test` is run, ninja will change into the build
dir before starting, but `meson test -C builddir/` does not. This is
important because meson does not use (for good reasons) absolute paths,
which means if a test case needs to be passed as an argument a file name
that is part of the build process, it will be relative builddir. Without
changing into the builddir the path will not exist (or worse, point at
the wrong thing), and test will not behave as intended.
To fix this mtest will change directory before starting tests, and will
change back after all tests have been finished.
Fixes #2710
> mtest: Chdir into the build directory before running tests with -C

- mesonbuild/modules/gnome.py
We should always prefer generated files over onces in the source tree else if the same file also exists in the source tree we get strange behaviour where we ignore dependencies and the project has to be built twice to be fully up-to-date.
See: https://bugzilla.gnome.org/show_bug.cgi?id=787677
Closes https://github.com/mesonbuild/meson/issues/2686
> gnome.compile_resources: Prefer generated files over source files

- mesonbuild/mesonlib.py
- test cases/common/166 custom target template substitution/checkcopy.py
- test cases/common/166 custom target template substitution/foo.c.in
- test cases/common/166 custom target template substitution/meson.build
Though I doubt many projects will have enough input/output files and command elements for it to matter, this should make the replace linear.
> Use regex to substitute template strings

- docs/markdown/Disabler.md
- docs/markdown/Reference-manual.md
- docs/markdown/snippets/disabler.md
- docs/sitemap.txt
- mesonbuild/coredata.py
- mesonbuild/interpreter.py
- mesonbuild/interpreterbase.py
- test cases/common/168 disabler/meson.build
Extracted from Dolphin options.
> Created disabler object type

- mesonbuild/compilers/cpp.py
- run_unittests.py
Different implementation of #2489.
> Add C++17 flags to GCC and Clang.

- mesonbuild/scripts/commandrunner.py
Improves further the error handling in commandrunner.py. Restructured
the code so that both calls to subprocess.Popen are covered.
Catch OSError and SubprocessError.
> Check for more errors when executing subprocess.

- docs/markdown/Reference-tables.md
- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/c.py
- mesonbuild/dependencies/base.py
- mesonbuild/linkers.py
- mesonbuild/mesonlib.py
- test cases/common/140 get define/meson.build
This is a few small fixup for the haiku os that I created while working on building mesa. most of these changes are pretty minor, except for the fact that haiku does not have (and does not accept) -pthreads either to the compiler or the linker.
> small fixes for haiku

- docs/markdown/Users.md
> Add Geary to the list of users - will use meson for the next release.

- mesonbuild/backend/backends.py
> Do not extract object for header sources

- docs/markdown/Users.md
now only build system of systemd
> systemd uses meson

- mesonbuild/mesonmain.py
- mesonbuild/optinterpreter.py
- run_unittests.py
- test cases/unit/19 bad command line options/meson.build
- test cases/unit/19 bad command line options/meson_options.txt
- test cases/unit/19 bad command line options/subprojects/one/meson.build
- test cases/unit/19 bad command line options/subprojects/one/meson_options.txt
Mostly because I can neither type nor spell.
> Don't accept unknown command line arguments

- mesonbuild/dependencies/misc.py
- test cases/failing/69 wrong boost module/meson.build
- test cases/frameworks/1 boost/meson.build
> boost: Allow older behavior with a warning

- mesonbuild/scripts/scanbuild.py
Im not sure if the ordering of the exe names is optimal
> The scanbuild script also searches scan-build-X.X exes

- docs/markdown/Project-templates.md
- docs/markdown/snippets/templates.md
- docs/sitemap.txt
- mesonbuild/mesonmain.py
- mesonbuild/minit.py
- run_unittests.py
Need to add C++ projects as well as a unit test that tests that all setups.
> Can create project setups with "meson init"

- .appveyor.yml
- mesonbuild/coredata.py
- mesonbuild/mesonlib.py
- mesonbuild/mesonmain.py
- run_unittests.py
> Bump minimum supported Python from 3.4 to 3.5.

- docs/markdown/Reference-manual.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/compilers/c.py
- mesonbuild/interpreter.py
- test cases/common/125 shared module/meson.build
- test cases/common/156 shared module resolving symbol in executable/meson.build
This complements the `shared_module` feature.
> Add `export_dynamic` argument to `executable`.

- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter.py
> Change handling of not found external programs

- docs/markdown/snippets/deprecations.md
- mesonbuild/interpreter.py
- test cases/common/58 run target/meson.build
- test cases/common/90 identical target name in subproject/meson.build
- test cases/common/90 identical target name in subproject/subprojects/foo/meson.build
A year and a half should be enough.
> Removed two deprecations from 2016.

- docs/markdown/Users.md
This is a very small hello world style project, that I hope is useful
example for people who are getting started with meson.
> docs: Add 'outlier' to users

- run_project_tests.py
This removes the workaround code added in
https://github.com/mesonbuild/meson/commit/52e1b0a3c909
The bug in the MSYS2 Python3 build has been fixed for some time now, see
https://github.com/Alexpux/MINGW-packages/pull/2619
The original commit noted that this might be helpful for OpenBSD, but
that has sem_open support since version 5.5 released 4 years ago:
https://www.openbsd.org/55.html
----
just something I've noticed. If it's preferred to keep the code feel free to close this PR.
> run_project_tests: Remove workaround for missing concurrent.futures.ProcessPoolExecutor support

- docs/markdown/Compiler-properties.md
Signed-off-by: Adam Jackson <ajax@redhat.com>
> docs: Fix some HTML that leaked into the markdown

- mesonbuild/dependencies/misc.py
A few small cleanups for the boost code.
> Clean boost

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/project-license.md
- mesonbuild/interpreter.py
- test cases/common/175 get project license/bar.c
- test cases/common/175 get project license/meson.build
> add meson.project_license() builtin

- mesonbuild/scripts/coverage.py
Cuurently, a set of directories is filtered out from the output based on
the location of system includes on most common linux distro's. This
commit does away with the blacklist and implements a whitelist approach:
only the files inside the source root are shown.
> Remove all files outside the source directory from the coverage report

- docs/markdown/Installing.md
Fixed typo in section Other install commands, typo was in extension of data file
> Fixed typo

- mesonbuild/backend/backends.py
> Don't add rpaths to system libraries

- mesonbuild/backend/backends.py
- test cases/common/15 mixed pch/meson.build
Should I also add something about this to the documentation?
> Fix targets with C and C++ code that use pre compiled headers

- mesonbuild/optinterpreter.py
- test cases/unit/19 bad command line options/subprojects/one/meson.build
Modified an existing test case to reproduce the error.
> Fix subproject prefix handling when checking subproject option validity.

- docs/markdown/Dependencies.md
- docs/markdown/Python-3-module.md
> Add python3 dependency documentation and link it from python3 module

- mesonbuild/wrap/wrap.py
Also be more lenient when doing git checkout, and continue even if it failed.
Closes https://github.com/mesonbuild/meson/issues/3088
> wrap: Fix broken logic when initializing submodules

- mesonbuild/mesonlib.py
Closes https://github.com/mesonbuild/meson/issues/3015
> Support running out-of-tree tests against a meson in PATH

- mesonbuild/compilers/d.py
Older versions of GDC had broken support for the -MQ flag (resulting in
a compiler error). New versions of GDC have this issue fixed (some older
versions received a backport). Starting with GCC 7.1 we can assume
dependency generation to always work reliably.
> d: gdc: Implement proper dependency gen support

- mesonbuild/dependencies/base.py
Also don't resolve `-lfoo` args only when libpaths are defined. `cc.find_library()` also searches in the toolchain directories, and the static library might be there, and remove a stray debug print.
> pkgconfig deps: Add all -L args when using -l args

- docs/markdown/Users.md
> Users.md: Add GNOME Boxes and GNOME Usage

- docs/markdown/Users.md
Add GVfs to the meson users list.
> Users.md: Add GVfs

- mesonbuild/dependencies/ui.py
- test cases/frameworks/9 wxwidgets/meson.build
- test cases/frameworks/9 wxwidgets/wxstc.cpp
> Fix wxwidgets dependency: pass modules to wx-config

- docs/markdown/Reference-manual.md
> Add reference to implicit_include_directories from include_directories()

- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/coredata.py
- mesonbuild/environment.py
- mesonbuild/mconf.py
- mesonbuild/mesonmain.py
- mesonbuild/mintro.py
- mesonbuild/mtest.py
Yours truly introduced this racy bug that can be seen (sometimes) when testing a project that uses some modules (pkgconfig in this case):
```
File "../meson/meson.py", line 26, in <module>
sys.exit(main())
File "../meson/meson.py", line 23, in main
return mesonmain.run(sys.argv[1:], launcher)
File "/home/trhd/Projects/meson/mesonbuild/mesonmain.py", line 288, in run
return mtest.run(remaining_args)
File "/home/trhd/Projects/meson/mesonbuild/mtest.py", line 643, in run
return th.doit()
File "/home/trhd/Projects/meson/mesonbuild/mtest.py", line 419, in doit
self.run_tests(tests)
File "/home/trhd/Projects/meson/mesonbuild/mtest.py", line 553, in run_tests
self.drain_futures(futures)
File "/home/trhd/Projects/meson/mesonbuild/mtest.py", line 569, in …
```
> Fix a data pickling bug.

- meson.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/xcodebackend.py
- mesonbuild/compilers/cpp.py
- mesonbuild/dependencies/ui.py
- mesonbuild/interpreter.py
- mesonbuild/interpreterbase.py
- mesonbuild/minit.py
- mesonbuild/modules/python3.py
- mesonbuild/modules/unstable_icestorm.py
- msi/createmsi.py
- run_unittests.py
- test cases/common/98 gen extra/srcgen3.py
It's kind of annoying to have to pick out the new warnings when running `flake8` locally, miss one and get told about it by the bot, so I tried to fix them all.
These commits are in some sort of order, from most to least trivial :)
> Fix flake8 issues

- mesonbuild/mtest.py
Fixes https://github.com/mesonbuild/meson/issues/3156
> meson test: let gdb handle ^C instead of us

- docs/markdown/Gnome-module.md
> Gnome-module.md: Add information about output files to mkenums()

- ciimage/Dockerfile
This is required to use utf8 filenames.
> Add LANG to Dockerfile

- mesonbuild/dependencies/base.py
Strawberry Perl on Windows ships with a Perl implementation of pkg-config embedded inside a BAT file. True horror of horrors, but people do use it, so search for pkg-config with `ExternalProgram` which has the right Windows-specific cases to deal with that.
Closes https://github.com/mesonbuild/meson/issues/3221
> PkgConfigDependency: Search for pkg-config with ExternalProgram

- docs/markdown/Pkgconfig-module.md
- docs/markdown/snippets/pkgconfig-requires-non-string.md
- mesonbuild/modules/pkgconfig.py
- run_unittests.py
- test cases/common/51 pkgconfig-gen/dependencies/meson.build
- test cases/common/51 pkgconfig-gen/meson.build
Closes #1204, also related to #3128
> Pkgconfig accepts libraries and pkgconfig-dependencies in requires/requires_private parameters

- mesonbuild/backend/xcodebackend.py
This makes test cases common/4 and common/6 pass with the xcode backend.
> Fix shared library building on xcode.

- mesonbuild/scripts/meson_install.py
Fixes:
- http://autobuild.buildroot.net/results/d5dcdfdfab3503fdc387f99e68267972a38c417d
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> Fix FileNotFoundError when restorecon unavailable

- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/interpreter.py
- mesonbuild/mesonlib.py
- mesonbuild/scripts/yelphelper.py
This is used in a number of places, and in some places it is incomplete.
Use a helper to ensure it's used properly.
@nirbheek, I rebased your commit since I believe it is valuable on its own.
> Create a helper for checking if a string has a path component

- docs/markdown/Installing.md
- docs/markdown/Reference-manual.md
- docs/markdown/snippets/install_data-rename.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/interpreter.py
- test cases/common/12 data/installed_files.txt
- test cases/common/12 data/meson.build
- test cases/failing/70 install_data rename bad size/meson.build
Closes #1487
This patch adds `rename` parameter to `install_data()`. If specified, length of rename list must be equal to number of sources. Non-basename `rename` arguments are allowed and they are joined with `install_dir`.
Please take a look on `MesonException('Size of rename argument is different from number of sources')`, I think this error message can be formulated better, looking for suggestions.
> Add install_data() rename parameter

- docs/markdown/Contributing.md
Proposal to spread the merge work to more people. Comments welcome.
> Document the new and improved review guidelines. [skip ci]

- mesonbuild/build.py
> Squash target_type warning for jar targets

- .appveyor.yml
This patch should prevent failing build because of single download failure.
> Retry downloads in Appveyor

- mesonbuild/interpreter.py
- test cases/common/187 subproject version/meson.build
- test cases/common/187 subproject version/subprojects/a/meson.build
Just as pkgconfig dependencies, the subproject dependency might  has a list of versions restrictions
> dependency's wanted version, declared in a subproject, might be a list

- mesonbuild/modules/pkgconfig.py
- run_unittests.py
- test cases/common/51 pkgconfig-gen/dependencies/meson.build
Add required version of dependencies into pc files.
> pkgconfig generator: Add required version

- docs/markdown/Pkgconfig-module.md
- docs/markdown/snippets/pkgconfig-generator.md
- mesonbuild/modules/pkgconfig.py
- test cases/common/51 pkgconfig-gen/dependencies/meson.build
pkg.generate(mylib) should be enough to generate a minimal pc file.
> pkgconfig: Add a simple version of the generator

- mesonbuild/interpreter.py
I think that pointing to documentation in this case is good and might make some users happy.
> Added link to documentation and examples for find_library replacement

- mesonbuild/backend/ninjabackend.py
- test cases/d/6 unittest/app.d
- test cases/d/6 unittest/meson.build
- test cases/d/6 unittest/second_unit.d
- test cases/d/9 features/app.d
- test cases/d/9 features/extra.d
- test cases/d/9 features/meson.build
This fixes issue #3337 and adds regression tests for it.
The culprit was commit ea3b54d40252fcb87eb1852223f125398b1edbdf, see the bug report #3337 for details.
> Regression fix: Ensure that D feature flags get applied to all files

- mesonbuild/interpreter.py
The entry 'subdir_done' is now at its right place.
> Move entry in build_funct_dict to correct position.

- mesonbuild/modules/qt.py
- test cases/frameworks/4 qt/meson.build
- test cases/frameworks/4 qt/subfolder/generator.py
- test cases/frameworks/4 qt/subfolder/main.cpp
- test cases/frameworks/4 qt/subfolder/meson.build
- test cases/frameworks/4 qt/subfolder/resources/stuff4.qrc.in
Added missing sub-folder test
Closes #3324
> [Qt module] Add File object support for generated or not qrc files

- mesonbuild/mintro.py
> introspect: default builddir to . to prevent a crash

- mesonbuild/coredata.py
Implementing set_value() in the base class simplifies the code and
ensure validation is always consistent.
This fix UserIntegerOption.validate_value() not checking min/max value,
and UserArrayOption.validate_value() raising exception because it does
not pass a value for user_input argument of validate() method.
> coredata: UserOption subclasses only need to implement validate_value()

- mesonbuild/compilers/c.py
- mesonbuild/compilers/compilers.py
This caching is only for a single run, so it doesn't help reconfigure. However, it is useful for subproject setups where different subprojects will run the same compiler checks.
The cache is also per compiler instance and is not used for functions that want to read or run the outputted object file or binary.
For gst-build, this halves the number of compiler checks that are run and reduces configuration time by 20%.
We could pickle this cache and reuse it for reconfigure, but we'd have to tell the compiler to generate dependency information, store access times for all those files, and check everything before using the cache the next time.
Unclear if that would always be a net benefit, but I haven't run the numbers. Would love to see someone try ;)
> compilers: Cache compiler checks where we don't want the output

- run_project_tests.py
It checks the build machine for the correct extensions of resulting
binaries, but it should be checking the host machine.
> Fix install checks when cross-compiling.

- docs/markdown/Syntax.md
- docs/markdown/snippets/more-escape-sequences.md
- mesonbuild/mparser.py
- test cases/common/32 multiline string/meson.build
- test cases/common/42 string operations/meson.build
> Remove escaping for triple-quoted strings

- docs/markdown/Python-module.md
- mesonbuild/modules/python.py
This contains https://github.com/mesonbuild/meson/pull/3435 , plus a documentation commit
> modules/python: add some more options around path and config_vars

- test cases/common/132 dependency file generation/meson.build
- test cases/common/22 header in file list/meson.build
- test cases/common/64 custom header generator/meson.build
Fixes commit c8ee45cf15f1a3daefbff519fcb5cc9caa558379.
Fixes #3454.
> Fix syntax error in tests common/22, 64 and 132

- test cases/common/33 try compile/meson.build
- test cases/common/39 tryrun/meson.build
I forgot to revert these two test cases.
> Fix two test cases

- run_unittests.py
- test cases/unit/30 mixed command line args/meson.build
- test cases/unit/30 mixed command line args/meson_options.txt
Just a few tests for the -D/-- cmdline mixing that I wrote when I thought I found a bug, but actually just found a user error :)
I thought that might be usefuly
> Tests for mixing -D and -- options

- mesonbuild/backend/vs2010backend.py
- mesonbuild/coredata.py
- mesonbuild/minit.py
This implements support for visual studio solution directories.
Projects will by default be put into directories that map their sub-directory
name in the source folder.
Fixes: #2524
> Use visual studio solution directories

- run_cross_test.py
- run_project_tests.py
I tried to improve `run_project_tests.py` a little bit. Output is more consistent on Windows now.
> Prettifying some output with pathlib

- mesonbuild/mesonmain.py
Outputs two profile logs: one for the interpreter run and another for the backend-specific build file generation. Both are stored in meson-private in the build directory.
This should help @jeandet create graphs for performance measurement, and should help @textshell test fixes for https://github.com/mesonbuild/meson/issues/3465.
The patch should also apply to Meson 0.45.1.
> New argument: --profile-self for profiling performance

- mesonbuild/mlog.py
This change still relies on the older 'ANSICON' environment check as a fallback, in the event we're on "not Windows 10". (Calling `SetConsoleMode` with unsupported values results in a 0 being returned).
Image showing it working:
This closes #3495
> Add VT100 ANSI escape sequences for Windows 10. Closes #3495 

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/fortran.py
- test cases/d/10 d cpp/cppmain.cpp
- test cases/d/10 d cpp/dmain.d
- test cases/d/10 d cpp/libfile.cpp
- test cases/d/10 d cpp/libfile.d
- test cases/d/10 d cpp/meson.build
- test cases/fortran/9 cpp/fortran.f
- test cases/fortran/9 cpp/main.cpp
- test cases/fortran/9 cpp/meson.build
This will _fail_ in CI with a segfault. The GDC runtime crashes when setting up the gc or something. I could not make it work even by running the commands manually. Reference page on D website [seems to be this one](https://dlang.org/spec/cpp_interface.html).
This should also make it simple to fix combining C++ and Fortran, which is #2685. Possibly even in this same PR once the D issue is fixed.
> Can combine D and C++ in a single target.

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/c.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cs.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/fortran.py
- mesonbuild/compilers/java.py
This reverts commit fa6ca160548d7e8df9c4c724e6c96f5e004e5316.
Closes https://github.com/mesonbuild/meson/issues/3550
> Revert "Add macOS linker versioning information"

- mesonbuild/build.py
- run_unittests.py
- test cases/unit/2 testsetups/envcheck.py
- test cases/unit/2 testsetups/meson.build
>  test setups: Inherit env when using a test setup 

- mesonbuild/interpreter.py
- run_unittests.py
Addresses a couple more infelicities noted in #3095
> Some clarifications to output when using a subproject

- mesonbuild/scripts/meson_install.py
> Wait for a permissions failure before trying to run pkexec

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/run_command_check.md
- mesonbuild/interpreter.py
- test cases/failing/75 run_command unclean exit/meson.build
- test cases/failing/75 run_command unclean exit/returncode.py
> Add 'check' kwarg for run_command

- docs/markdown/Configuration.md
- test cases/failing/75 configuration immutable/meson.build
> Clarify that configuration_data()'s copy is immutable

- mesonbuild/interpreter.py
- test cases/common/202 subproject array version/meson.build
- test cases/common/202 subproject array version/subprojects/foo/meson.build
> Fix meson multiple version constraint error

- docs/markdown/snippets/feature_new.md
- mesonbuild/build.py
- mesonbuild/interpreter.py
- mesonbuild/interpreterbase.py
- mesonbuild/modules/windows.py
* FeatureNew: Print WARNING instead of ERROR
ERROR is reserved for non-zero exit codes. People will probably get confused.
* FeatureNew: add two features that were just merged
* docs: Add a release notes snippet about FeatureNew
CC @Salamandar
> Small fixes and changes to FeatureNew + docs

- mesonbuild/interpreter.py
- run_unittests.py
> Fix options being reset to default on reconfigure

- docs/markdown/Dependencies.md
- docs/markdown/Reference-manual.md
Make a start at document the values for dependency(method:)
> Document dependency(method:) values

- mesonbuild/modules/windows.py
- test cases/windows/16 resource scripts with duplicate filenames/a/meson.build
- test cases/windows/16 resource scripts with duplicate filenames/a/rsrc.rc
- test cases/windows/16 resource scripts with duplicate filenames/b/meson.build
- test cases/windows/16 resource scripts with duplicate filenames/b/rsrc.rc
- test cases/windows/16 resource scripts with duplicate filenames/c/meson.build
- test cases/windows/16 resource scripts with duplicate filenames/c/rsrc.rc
- test cases/windows/16 resource scripts with duplicate filenames/meson.build
- test cases/windows/16 resource scripts with duplicate filenames/rsrc.rc
- test cases/windows/16 resource scripts with duplicate filenames/verify.c
>  Use a unique name for windows resource compilation custom target 

- mesonbuild/scripts/meson_install.py
- run_unittests.py
> Don't add DESTDIR to install_name on macOS

- docs/markdown/snippets/run_command_check.md
- mesonbuild/interpreter.py
- mesonbuild/mesonlib.py
- test cases/common/38 run program/meson.build
`capture: false` means we won't try to read the output at all.
Closes https://github.com/mesonbuild/meson/issues/3364
Will add docs and a release snippet if this is approved.
> run_command: Add new kwarg 'capture'

- mesonbuild/modules/gnome.py
In GLib when running "ninja gio-doc" without doing a full build first,
it won't build libraries and the generated gio-scan.c gets linked
against system libgio instead.
This fix 2 bugs: gtkdoc() was not passing 'depends' variable down to
_get_dependencies_flags(), and many places had 'if depends' which is
False when 'depends' is an empty list and not only when it's None. There
is no reason for that argument to be optional, we always want to collect
dependencies.
> gtkdoc: Fix dependencies not being built before invoking gtkdoc

- mesonbuild/scripts/gtkdochelper.py
> gtkdoc: Use generated types file if there is one

- mesonbuild/dependencies/base.py
> Debug-log pkg-config calls

- mesonbuild/compilers/compilers.py
> implement get_link_whole_for() for IntelCompiler

- .gitignore
> Ignore vim *.swp files [skip ci]

- mesonbuild/interpreter.py
Since we can't detect it in `meson_options.txt`, detect it when the option is used.
> Add a feature-new entry for UserFeatureOption

- mesonbuild/optinterpreter.py
> UserFeatureOption: Default to 'auto' when no value specified

- mesonbuild/wrap/wrap.py
The current wrap files do not support checkout from reviews in Git/Gerrit. This is now included.
> Adding support to checkout from reviews in git/gerrit using commit ids.

- mesonbuild/modules/python.py
* Lookup is now performed according to the following order:
1. use `pkg-config` with `PKG_CONFIG_LIBDIR=LIBPC` from python
2. use plain `PKG_CONFIG_{LIBDIR,PATH}` from the environment
3. try to extract the information from SYSCONFIG
The second step is necessary for relocated python installations
and cross compilation scenarios, where the value of `LIBPC` will
be wrong.
```
Found "python-2.7" via pkg-config lookup in LIBPC (/usr/lib64/pkgconfig)
```
```
"python-2.7" cannot be found in LIBPC (BROKEN/usr/lib64/pkgconfig), this is likely due to a relocated python installation
Found "python-2.7" via fallback pkg-config lookup in PKG_CONFIG_LIBDIR/PKG_CONFIG_PATH
```
```
"python-2.7" cannot be found in LIBPC (BROKEN/usr/lib64/pkgconfig), this is likely due to a relocated python installation …
```
> Make python module more robust

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/visibility.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/compilers/compilers.py
- mesonbuild/interpreter.py
- mesonbuild/minit.py
- test cases/failing build/2 hidden symbol/bob.c
- test cases/failing build/2 hidden symbol/bob.h
- test cases/failing build/2 hidden symbol/bobuser.c
- test cases/failing build/2 hidden symbol/meson.build
I really don't like the choice duplication in this one, but importing compiler stuff to build is even worse. Suggestions welcome.
> Add symbol_visibility keyword argument

- mesonbuild/compilers/cpp.py
- run_unittests.py
I'm sure this is probably not thorough enough, but I thought I'd try to help get the ball rolling. closes #3997
> Add support for c++2a and gnu++2a (closes #3997)

- mesonbuild/minstall.py
- run_unittests.py
Fixes https://github.com/mesonbuild/meson/issues/3914
> install_subdir: Also copy dangling symlinks

- mesonbuild/modules/gnome.py
g-ir-scanner barfs on any flags other than `-D` `-I` and `-U` for cflags and `-L`, `-l` and `--extra-library` for ldflags. In this case, pkg-config dependencies may return `-F` framework flags, which must be filtered out.
Thanks to @havardgraff for reporting. Sorry it took so long to get merged!
> gnome: Filter CFLAGS that are passed to g-ir-scanner

- manual tests/7 vala composite widgets/mywidget.vala
- run_project_tests.py
- test cases/common/106 subproject subdir/prog.c
- test cases/common/106 subproject subdir/subprojects/sub/lib/sub.c
- test cases/common/120 subdir subproject/prog/prog.c
- test cases/common/120 subdir subproject/subprojects/sub/sub.c
- test cases/common/124 test skip/test_skip.c
- test cases/common/126 llvm ir and assembly/square-arm.S
- test cases/common/126 llvm ir and assembly/square-x86.S
- test cases/common/126 llvm ir and assembly/square-x86_64.S
- test cases/common/84 extract from nested subdir/src/first/lib_first.c
- test cases/common/84 extract from nested subdir/tst/first/exe_first.c
- test cases/frameworks/4 qt/manualinclude.cpp
- test cases/nasm/1 configure file/hello.asm
- test cases/unit/14 testsetup selection/main.c
- test cases/unit/14 testsetup selection/subprojects/bar/bar.c
- test cases/unit/14 testsetup selection/subprojects/foo/foo.c
- test cases/vala/10 mixed sources/vala/bar.vala
- test cases/vala/5 target glib/GLib.Thread.vala
- test cases/vala/9 gir/foo.vala
I don't know who keeps adding those in but it stops now.
> Kill tabs dead! For good!

- mesonbuild/compilers/d.py
Required for #3981, should fix #4025.
> Fix D soname arguments for Windows and OSX

- test cases/d/10 d cpp/cppmain.cpp
- test cases/d/10 d cpp/libfile.d
Better fix for #4058 as it was pointed out, it's better to have a good example how the interop should be done properly.
> Improve D mixed language test case

- mesonbuild/compilers/compilers.py
- mesonbuild/coredata.py
> UserArrayOption: Allow duplicates when used as <lang>_args option

- mesonbuild/coredata.py
- mesonbuild/interpreter.py
- mesonbuild/mconf.py
- mesonbuild/mesonmain.py
- mesonbuild/mintro.py
- mesonbuild/mlog.py
- mesonbuild/wrap/wraptool.py
Another smaller subset of PR #3528 that does not introduce new features.
> Command line step2

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/dependency_version.md
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/dev.py
- mesonbuild/dependencies/misc.py
- mesonbuild/dependencies/platform.py
- mesonbuild/dependencies/ui.py
- mesonbuild/interpreter.py
- test cases/common/190 openmp/meson.build
- test cases/failing/81 framework dependency with version/meson.build
- test cases/failing/82 gl dependency with version/meson.build
- test cases/failing/83 threads dependency with version/meson.build
- test cases/failing/84 gtest dependency with version/meson.build
- test cases/frameworks/1 boost/meson.build
- test cases/frameworks/15 llvm/meson.build
- test cases/frameworks/16 sdl2/meson.build
- test cases/frameworks/17 mpi/meson.build
- test cases/frameworks/18 vulkan/meson.build
- test cases/frameworks/19 pcap/meson.build
- test cases/frameworks/20 cups/meson.build
- test cases/frameworks/21 libwmf/meson.build
- test cases/frameworks/4 qt/meson.build
- test cases/frameworks/9 wxwidgets/meson.build
- test cases/python3/2 extmodule/meson.build
>  Apply dependency(version:) check for all dependency types

- mesonbuild/compilers/cpp.py
* The current version matching logic is brittle
with respect to Clang. LLVM and Apple Clang use
slightly different but nowadays overlapping
version ranges. Instead, we now just check whether
the compiler supports the given `-std=` variant
and try its respective fallback instead of
testing version ranges.
> Make `-std=` fallback remapping more robust

- mesonbuild/dependencies/misc.py
Somehow I overlooked this class when adjusting everything else in c59ec874
et seq.
Update Python3Dependency so it has a _factory() method which returns a list
of constructors, depending on the method: kwarg, which integrates better
with the reporting in find_external_dependency()
This ensures the return of a PkgConfigDependency object, if the dependency
is found with pkgconfig, so we don't have to specifically implement
get_pkgconfig_variable() ourselves.
> Modernize Python3Dependency

- mesonbuild/compilers/d.py
Changes arguments which involves file paths like `-of <target>` to `-of=<target>` and moves the commonly used arguments under DCompiler (both DMD and LDC use the DMD frontend so most arguments should remain the same).
> D: Use the documented syntax for various arguments

- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/dev.py
- mesonbuild/dependencies/misc.py
- mesonbuild/dependencies/platform.py
- mesonbuild/dependencies/ui.py
- run_unittests.py
> Dependency formatting tweaks

- mesonbuild/build.py
- mesonbuild/compilers/d.py
- test cases/unit/35 dist script/replacer.py
- tools/dircondenser.py
Not sure why these weren't picked up by Sider.
> Flake8 fixes

- docs/markdown/Python-module.md
- mesonbuild/modules/python.py
- test cases/unit/39 python extmodule/meson.build
- test cases/unit/39 python extmodule/meson_options.txt
> find_installation: Add support for feature option in required kwarg

- mesonbuild/build.py
- test cases/failing/89 link_with custom target/demo.c
- test cases/failing/89 link_with custom target/foo.c
- test cases/failing/89 link_with custom target/lib_generator.py
- test cases/failing/89 link_with custom target/meson.build
> Improve error when trying to link_with a custom_target

- mesonbuild/compilers/c.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cpp.py
Unify common code to prevent more balkanisation in the codebase
> ICC/GCC/Clang ABC refactor

- mesonbuild/compilers/compilers.py
@nirbheek other ideas for fixing the bug?
> Fix setting `-Doptimization` breaking build

- test cases/frameworks/11 gir subproject/installed_files.txt
- test cases/frameworks/7 gnome/installed_files.txt
Omitted from 0fc9a601 (#4170) as these tests are skipped in CI
> Add some more implibs to list of installed files on cygwin

- mesonbuild/environment.py
- mesonbuild/linkers.py
These changes were missing in #4175.
> D: Fix incorrect arch handling in D linkers

- docs/README.md
Hope this change will help other people to generate local documentation faster.
> Update Meson docs README [skip ci]

- mesonbuild/scripts/dist.py
Closes https://github.com/mesonbuild/meson/issues/1977
> dist: Warn if there are uncommitted changes in the repository

- mesonbuild/compilers/c.py
- run_unittests.py
Same as #4286 but with a fix to the macOS test failure.
> Fix pthread

- docs/markdown/D.md
- docs/markdown/Reference-manual.md
- mesonbuild/build.py
- mesonbuild/compilers/d.py
- test cases/d/9 features/app.d
- test cases/d/9 features/meson.build
> D: Add conditional debug compilation flags

- mesonbuild/compilers/c.py
In get_library_dirs() we are trusting the compiler to return a correct
list of directories to search for libraries, based on whether or not
we are compiling 64-bit or 32-bit. Unfortunately, this is often not the
case, as 64-bit libraries often are returned when compiling with -m32 on
a 64-bit OS.
Since system directories do not contain a mix of libraries, the solution
here is to check each directory, by picking a .so file in the directory
and checking whether its 64-bit or 32-bit. If we can't determine if we
want 32-bit or 64-bit, just skip the checks and assume the directory is
good.
> Verify library directories as either 32-bit or 64-bit

- mesonbuild/backend/backends.py
- mesonbuild/build.py
This brings down the overall build time of EFL from 20 sec. down to 13.
> Performance optimize the install part generation

- mesonbuild/environment.py
- mesonbuild/interpreter.py
I took infrastructure improvements from #3689, and expanded upon them, without the controversial user-visible change. Hopefully that makes this more palatable. Taken from commit messages:
1. Centralize description of build, host, and target, machines
Instead of just putting these together in the interpreter, put them together in `environment.py` so Meson's implementation can also better take advantage of them.
2. ~~Use new `env.machines.*` to avoid some `is_cross`~~
~~This is a small example of the `is_cross` removal the previous commit enables.~~
The second commit needs more testing. I've instead included in https://github.com/mesonbuild/meson/pull/4010 which drafts the overall direction I want to refactor things.
> Add `env.machines.*` to start centralization build, host, target information

- docs/markdown/Syntax.md
- docs/markdown/snippets/new_syntax.md
- mesonbuild/interpreter.py
- mesonbuild/interpreterbase.py
- mesonbuild/mparser.py
- test cases/common/17 comparison/meson.build
- test cases/common/64 foreach/meson.build
This adds "in" keyword, which is not backward compatible change.
> Interpreter: Add "in", "not in", "break", and "continue" operators

- mesonbuild/coredata.py
- mesonbuild/interpreter.py
- mesonbuild/msetup.py
- mesonbuild/wrap/__init__.py
- test cases/common/44 options/meson.build
This one started simple but then required a fair bit of work.
> Expose wrap_mode as an option. Closes #4266.

- docs/markdown/Configuration.md
- docs/markdown/Reference-manual.md
- mesonbuild/interpreter.py
- test cases/common/14 configure file/meson.build
- test cases/common/14 configure file/prog9.c
> configure_file: Support taking values from a dict

- .gitattributes
- azure-pipelines.yml
- ci/azure-steps.yml
- run_cross_test.py
- run_project_tests.py
- run_tests.py
- run_unittests.py
- skip_ci.py
- test cases/csharp/1 basic/installed_files.txt
- test cases/csharp/2 library/installed_files.txt
- test cases/frameworks/17 mpi/meson.build
See #4154 
Sample run https://dev.azure.com/admin0564/meson/_build/results?buildId=54&view=logs
> Add Azure pipelines CI

- mesonbuild/scripts/depfixer.py
> depfixer: Do not try to fix rpaths of dlls

- mesonbuild/environment.py
- mesonbuild/mesonlib.py
Trying to break off pieces of #4010.
> Start leveraging MachineInfo with for_* methods

- docs/markdown/Custom-build-targets.md
- docs/markdown/Generating-sources.md
- docs/markdown/Python-3-module.md
- docs/markdown/Reference-manual.md
Just some documentation additions and fixes. There have been several question recently on IRC about this, so I figured it was worth documenting.
> Docs custom target codegen

- mesonbuild/dependencies/base.py
- test cases/frameworks/15 llvm/meson.build
For once it's not llvm-config that's broken.
> LLVM windows fixes

- mesonbuild/wrap/wrap.py
> wrap: Check the directory key is a name and not a path

- mesonbuild/mesonlib.py
Don't make single element tuple
> Fix bug in PerMachine constructor

- mesonbuild/backend/backends.py
- test cases/nasm/1 configure file/meson.build
> extract_all_sources: Also include generated object files

- mesonbuild/mtest.py
as instructed in the python docs, you should not use PIPE here. This can
lead to deadlocks, with massive testsuite output. Which was the case for efl.
For now the output of the tests is redirected into the a temp file, the
content from there can then be used to fill the TestRun structure.
This fixes test running problems in efl.
> test: do not use PIPE

- mesonbuild/modules/gnome.py
Introspecting non-libtool static libraries requires a gir-scanner fix which is only in 1.58.1 or later. This is a follow-up to #4476
> gnome: Require GObject-Introspection 1.58.1 for static libraries

- mesonbuild/environment.py
This gets the ball rolling, and doesn't depend on any of my other PRs in flight.
Progress towards #4332
> Begin to factor out logic for getting binaries

- mesonbuild/backend/ninjabackend.py
- mesonbuild/environment.py
- test cases/java/8 codegen custom target/com/mesonbuild/meson.build
A few fixes for Java targets I noticed with the native-files work.
> Java fixes

- mesonbuild/mtest.py
This makes it clear that there's "passing" tests which actually require
bugfixes in the project, e.g. instead of:
OK:       329
FAIL:       1
SKIP:       0
TIMEOUT:    0
Users now see:
OK:       323
FAIL:       1
XFAIL:      6
SKIP:       0
TIMEOUT:    0
> Report failing and should_fail tests as XFAIL, instead of OK

- test cases/common/152 simd/simd_sse2.c
- test cases/common/152 simd/simd_sse3.c
- test cases/common/152 simd/simd_sse41.c
- test cases/common/152 simd/simd_sse42.c
- test cases/common/152 simd/simd_ssse3.c
- test cases/common/152 simd/simdchecker.c
- test cases/common/152 simd/simdfuncs.h
- test cases/common/152 simd/simdtest.h
> Fix SIMD test

- mesonbuild/modules/hotdoc.py
- test cases/frameworks/23 hotdoc/meson.build
The command we were passing in was wrong.
> hotdoc: Fix has_extensions when several extensions are passed in

- ci/azure-steps.yml
- test cases/common/143 C and CPP link/meson.build
per https://github.com/mesonbuild/meson/pull/4500#issuecomment-438942716, install prerequisites to allow more tests to run
> Enable more tests in Azure

- mesonbuild/dependencies/base.py
- run_unittests.py
I changed the DependencyException in the CMake backend and updated the regex for the unit tests.
> Fixed unit test (see #4549)

- docs/markdown/Subprojects.md
- docs/markdown/snippets/subprojects_cmd.md
- mesonbuild/mesonmain.py
- mesonbuild/mlog.py
- mesonbuild/msubprojects.py
- mesonbuild/wrap/wrap.py
- mesonbuild/wrap/wraptool.py
- setup.cfg
This is inspired by gst-build's git-update script.
> Add 'meson subprojects update' command

- mesonbuild/build.py
- mesonbuild/coredata.py
- run_unittests.py
This isn't a big deal, but IMO makes code and diffs a bit easier to read.
As with #4581, splitting out easy bits of #4445 while I don't know what to do test hanging with that.
CC @dcbaker
> Combine some adjecent imports from same origin 

- docs/markdown/Syntax.md
- docs/markdown/snippets/kwargdict.md
- mesonbuild/interpreterbase.py
- test cases/common/208 kwarg entry/inc/prog.h
- test cases/common/208 kwarg entry/installed_files.txt
- test cases/common/208 kwarg entry/meson.build
- test cases/common/208 kwarg entry/prog.c
- test cases/failing/91 kwarg dupe/meson.build
- test cases/failing/91 kwarg dupe/prog.c
A different take on #3820.
No doc changes yet, will add if this is deemed a suitable approach.
> Can specify keyword arguments with a dict.

- docs/markdown/Getting-meson.md
> docs: fix link to platform install quirks [skip ci]

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/compilers.py
- run_unittests.py
- test cases/unit/49 ldflagdedup/bob.c
- test cases/unit/49 ldflagdedup/meson.build
- test cases/unit/49 ldflagdedup/prog.c
Not sure about the fix, though. Probably needs something smarter.
> Deduplicate export-dynamic and pthread. Closes #4567.

- mesonbuild/backend/vs2010backend.py
If you change only some project in meson.build, only that .vcxproj file will be updated and reloaded.
If you change something not related to VS solution and projects or simply touch the meson.build file, nothing will be reloaded.
> Update VS files only if something changed.

- mesonbuild/modules/gnome.py
This allows coherent relative paths in the gir "source-position"
> gi: Handle new --source-top-dirs argument

- mesonbuild/coredata.py
Otherwise it's easy to forget one. In fact we did forget one: `backend_options` in `validate_option_value`.
> Factor out iterator over options dictionaries

- mesonbuild/interpreter.py
- run_unittests.py
Fix for #4662. Also added a test case.
> Print subproject introspection info again (fixes #4662)

- azure-pipelines.yml
- mesonbuild/compilers/compilers.py
- run_unittests.py
- test cases/common/143 C and CPP link/meson.build
- test cases/common/190 openmp/meson.build
- test cases/common/59 exe static shared/meson.build
- test cases/failing build/2 hidden symbol/meson.build
- test cases/windows/12 resources with custom targets/meson.build
- test cases/windows/5 resources/meson.build
Add support for  *-windows-gnu targeted clang (as provided by MSYS2 or a cross-compiler)
> More clang for Windows support

- docs/markdown/Reference-manual.md
- mesonbuild/interpreter.py
> Add 'required' kwarg in header check functions

- mesonbuild/minstall.py
> print 'Nothing to install.' if nothing was installed

- mesonbuild/backend/vs2010backend.py
- test cases/failing build/3 pch disabled/c/meson.build
- test cases/failing build/3 pch disabled/c/pch/prog.h
- test cases/failing build/3 pch disabled/c/pch/prog_pch.c
- test cases/failing build/3 pch disabled/c/prog.c
- test cases/failing build/3 pch disabled/meson.build
> vs: respect 'b_pch' option

- mesonbuild/modules/rpm.py
Fixes #2202 by simply commenting out `CoreData.ext_libs` and `CoreData.ext_progs`, which were removed from CoreData some time ago. Also refactors a block of code out to a separate method, `__get_required_compilers`.
> rpm: Bring RPM module back in to a working state

- docs/markdown/Reference-tables.md
- docs/markdown/snippets/pgi_compilers.md
- mesonbuild/compilers/__init__.py
- mesonbuild/compilers/c.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/fortran.py
- mesonbuild/environment.py
PGI Fortran compiler support was previously added, this adds PGI C and C++ compiler support.
```sh
CC=pgcc CXX=pgc++ FC=pgfortran meson ..
```
> Add PGI C and C++ compilers

- docs/markdown/snippets/cuda.md
- mesonbuild/compilers/__init__.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cuda.py
- mesonbuild/environment.py
- run_project_tests.py
- test cases/cuda/1 simple/meson.build
- test cases/cuda/1 simple/prog.cu
- test cases/cuda/2 split/lib.cu
- test cases/cuda/2 split/main.cpp
- test cases/cuda/2 split/meson.build
- test cases/cuda/2 split/static/lib.cu
- test cases/cuda/2 split/static/libsta.cu
- test cases/cuda/2 split/static/main_static.cpp
- test cases/cuda/2 split/static/meson.build
This is #3730 rebased, fixed and with better tests.
I'm not sure how we should do the testing on this. The legalese on NVidia's web site seems to indicate that they don't like redistributing it and the package itself does not even install on Ubuntu bionic. There are Cuda packages in universe that work, but they add a gigabyte or so of stuff making the CI image even more bloated than it is currently.
> Add Cuda support

- run_unittests.py
The native file tests were never run on the CI since they were skipped on Windows and also skipped on Linux and macOS since `CC`/`CXX`/etc are always set by the CI.
Also fix test failure on macOS. The test was assuming that because `/usr/bin/gcc` and `/usr/bin/clang` exist on macOS, they must be different compilers. They're not. gcc is just a wrapper around clang, and we correctly detect it as such.
> unit tests: Run native file tests on the CI

- mesonbuild/coredata.py
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/ui.py
- run_tests.py
- run_unittests.py
- test cases/osx/2 library versions/meson.build
- test cases/osx/2 library versions/require_pkgconfig.py
f.ex. https://github.com/mesonbuild/meson/issues/4728, and many more. See commits.
> Several pkg-config fixes on macOS and Windows

- mesonbuild/modules/pkgconfig.py
See: https://github.com/mesonbuild/meson/pull/4630#issuecomment-459235498
> pkgconfig: Only warn about deprecation at a location once

- mesonbuild/interpreter.py
- test cases/common/14 configure file/meson.build
Also add location node for two more deprecations
See: https://github.com/mesonbuild/meson/pull/4489#issuecomment-459246879
> configure_file: Allow setting install_dir: false with deprecation

- mesonbuild/compilers/d.py
> Fix linkage errors due to malformed ninja script

- mesonbuild/backend/ninjabackend.py
- test cases/common/13 pch/generated/gen_custom.py
- test cases/common/13 pch/generated/gen_generator.py
- test cases/common/13 pch/generated/generated_generator.in
- test cases/common/13 pch/generated/meson.build
- test cases/common/13 pch/generated/pch/prog.h
- test cases/common/13 pch/generated/pch/prog_pch.c
- test cases/common/13 pch/generated/prog.c
- test cases/common/13 pch/meson.build
- test cases/common/13 pch/withIncludeDirectories/include/lib/lib.h
- test cases/common/13 pch/withIncludeDirectories/meson.build
- test cases/common/13 pch/withIncludeDirectories/pch/prog.h
- test cases/common/13 pch/withIncludeDirectories/pch/prog_pch.c
- test cases/common/13 pch/withIncludeDirectories/prog.c
Fixes #999, #1415, #2361 and also a msvc PCH staleness issue when using the Ninja backend.
> Fix missing PCH dependencies

- mesonbuild/backend/vs2010backend.py
VS now always considers run, install, and test targets out-of-date, just like ninja does.
> vs: fix up to date checks

- mesonbuild/modules/i18n.py
Add some missing functions having C-format strings to the list.
Signed-off-by: Frediano Ziglio <fziglio@redhat.com>
> i18n: Catch additional GLib functions

- mesonbuild/mesonmain.py
> Fix import path for scripts ran with "meson runpython"

- mesonbuild/build.py
- run_unittests.py
- test cases/common/87 identical target name in subproject/meson.build
- test cases/common/87 identical target name in subproject/subprojects/foo/meson.build
> Allow custom targets with same name in project and subprojects

- run_unittests.py
This makes the testsuite work better with other test runners, like
pytest. This is important because better test runners are very useful to
development (e.g. avoiding running succeeding tests again and again),
even if we want to still support 0 dependency testing of Meson though
keeping the default test runnner working.
CC @nirbheek @dcbaker
> unit tests: Use unittest.skipUnless to simplify main()

- mesonbuild/backend/ninjabackend.py
- test cases/fortran/4 self dependency/meson.build
- test cases/fortran/4 self dependency/subprojects/sub1/main.f90
- test cases/fortran/4 self dependency/subprojects/sub1/meson.build
corrected, generalized self-referential Fortran fix--further refine logic for omitting false dependencies for self-referential Fortran files
closes https://github.com/mesonbuild/meson/issues/4986
> BUGFIX: correct Fortran self-dep logic

- mesonbuild/compilers/cuda.py
- test cases/cuda/5 threads/main.cu
- test cases/cuda/5 threads/meson.build
- test cases/cuda/5 threads/shared/kernels.cu
- test cases/cuda/5 threads/shared/kernels.h
- test cases/cuda/5 threads/shared/meson.build
Fixes issue #4999 @obilaniu Thanks
> Fix nvcc error with threads dependency (4999)

- docs/markdown/Dependencies.md
- docs/markdown/snippets/netcdf.md
- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/misc.py
- run_project_tests.py
- test cases/frameworks/26 netcdf/main.c
- test cases/frameworks/26 netcdf/main.cpp
- test cases/frameworks/26 netcdf/main.f90
- test cases/frameworks/26 netcdf/meson.build
Like HDF5, [NetCDF](https://www.unidata.ucar.edu/software/netcdf/) is a popular archival high performance data format used in HPC and all sorts of applications.
> add NetCDF

- mesonbuild/backend/vs2010backend.py
This is my attempt of rebasing #4483.
> Move the optimization options in the compiler config

- mesonbuild/rewriter.py
- test cases/rewrite/1 basic/addSrc.json
Filter out duplicate source files.
> rewriter: Avoid duplicates

- mesonbuild/ast/introspection.py
- run_unittests.py
- test cases/rewrite/1 basic/addSrc.json
- test cases/rewrite/1 basic/info.json
- test cases/rewrite/1 basic/meson.build
- test cases/rewrite/1 basic/rmSrc.json
- test cases/rewrite/1 basic/rmTgt.json
Correctly handle `src_list1 + src_list2` in the rewriter.
> rewriter: Handle Arithmetic node

- mesonbuild/interpreter.py
Just a missing check I noticed.
> Install header\'s subdir must not be absolute.

- docs/markdown/Style-guide.md
Document the sorting algorithm of #5010.
> docs: Define sorting in Style-guide.md [skip ci]

- docs/markdown/Rewriter.md
- docs/markdown/snippets/rewriter.md
- docs/sitemap.txt
- mesonbuild/ast/interpreter.py
- mesonbuild/ast/introspection.py
- mesonbuild/mesonmain.py
- mesonbuild/mlog.py
- mesonbuild/rewriter.py
- run_unittests.py
- test cases/rewrite/1 basic/addTgt.json
- test cases/rewrite/1 basic/rmTgt.json
- test cases/rewrite/2 subdirs/addTgt.json
- test cases/rewrite/2 subdirs/rmTgt.json
- test cases/rewrite/3 kwargs/add.json
- test cases/rewrite/3 kwargs/defopts_delete.json
- test cases/rewrite/3 kwargs/info.json
- test cases/rewrite/3 kwargs/remove.json
- test cases/rewrite/3 kwargs/remove_regex.json
- test cases/rewrite/3 kwargs/set.json
- test cases/rewrite/4 same name targets/addSrc.json
- test cases/rewrite/4 same name targets/info.json
- test cases/rewrite/4 same name targets/meson.build
- test cases/rewrite/4 same name targets/sub1/meson.build
This is the final PR for the rewriter (at least for now). With this, the rewriter is no longer in beta and should function as advertised (everything else is a bug 😃).
- make sure source files are always relative
- slight code cleanup
- new CLI for the rewriter
- documentation
> rewriter: Add a CLI and docs

- mesonbuild/dependencies/dev.py
@jpakkane, I know we're past feature freeze, but I'm hoping that still might land for 0.50
> llvm: Add llvm-config80 for FreeBSD

- mesonbuild/dependencies/dev.py
- mesonbuild/envconfig.py
Adds support for Fedora 30's new llvm-config format.
> Fedora 30 llvm config

- mesonbuild/modules/__init__.py
- mesonbuild/modules/gnome.py
This reverts commit 59791fc56966901038aaaac23942bc8ac6e11494, reversing
changes made to e26b5a119e0b3f76cc93f65ecf4251dc6d52ecfe.
> Revert "gnome.compile_resources: Add ld binary method"

- docs/markdown/Dependencies.md
- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/misc.py
> [Dude, like, what even is pkg-config lmfao? XD](https://github.com/google/shaderc/issues/392)
— Google Inc. engineers
> Add shaderc dependency lookup logic

- mesonbuild/scripts/vcstagger.py
Dear,
While using meson I encountered a problem where `vcstagger.py` was not able to decode byte `0xc3`
In order to fix it, I wrote this little bug fix
Thanks for this awesome build tool
> Read file as utf8 on python3

- mesonbuild/backend/backends.py
> backends/ninja: Add native files to rebuild dependencies

- mesonbuild/modules/python.py
- test cases/python/1 basic/meson.build
I was in the python module for some other stuff, and noticed this annoying behavior.
> Python module log which python is found

- mesonbuild/dependencies/base.py
Needed for `wx-config` on Windows.
> Use ExternalProgram to find config tools, fix #1423

- mesonbuild/compilers/fortran.py
This fixes a not uncommon corner case for contemporary Windows 10 Fortran users that also use Windows Subsystem for Linux (WSL).
Replicate error:
1. build a Meson Fortran project in WSL
2. build the same project from native Windows without deleting the "build/meson-private" directory
Result: 
Meson hard crashes with OSError at mesonbuild/compilers/fortran.py:sanity_check at `Popen` for running the test executable, because it does not add the .exe extension, and Windows thinks you want to run `/meson-private/foo` instead of `meson-private/foo.exe`
Rather than monkey-patch the .exe extension onto the test executable filename, it seemed better to have Meson cleanup the conflicting WSL executable and proceed to build--at least not crashing Meson altogether.
> BUGFIX: don't crash Meson on bad existing exe file: Fortran sanity check

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/compilers/c.py
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/boost.py
- mesonbuild/dependencies/dev.py
- mesonbuild/dependencies/misc.py
Just a little refactor for now. After this lands I want to make threads support the static keyword.
> Threads is not special

- docs/markdown/Builtin-options.md
> docs: Document pkg_config_path and cross_ options [skip ci]

- docs/markdown/Builtin-options.md
> [docs] Reordered options and fixed a typo [skip ci]

- run_unittests.py
As per https://github.com/mesonbuild/meson/pull/4931#discussion_r273429955
> Added a unit test for built-in options docs

- mesonbuild/interpreter.py
Just some small cleanups I saw when I was in the interpreter module.
> Interpreter cleanups

- mesonbuild/ast/interpreter.py
- test cases/unit/55 introspection/meson.build
I think this should also go into 0.50.1
> mintro: Fix set_variable plus assign bug (closes #5256)

- docs/markdown/fallback-wraptool.md
> docs: update fallback wraptool docs [skip ci]

- azure-pipelines.yml
- ci/azure-steps.yml
- docs/markdown/Configuring-a-build-directory.md
- docs/markdown/Reference-manual.md
- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/vs2019backend.py
The rest of #5064. Includes also the vs2019backend.py file that I for some reason forgot to add to the PR. :man_facepalming:
> Add VS2019 backend CI and docs.

- mesonbuild/compilers/c.py
- run_unittests.py
Also add a test to ensure that we don't forget it in the future.
> vs: Update toolset table for VS 2019

- mesonbuild/mesonmain.py
- mesonbuild/modules/python.py
- msi/createmsi.py
Let me tell you, there's nothing quite like debugging issues that only happen when running a packaged and installed version on Windows.
> Can run argument strings with internal Python. Closes #5217.

- docs/markdown/snippets/xfail.md
- mesonbuild/mtest.py
- test cases/failing test/6 xpass/meson.build
- test cases/failing test/6 xpass/xpass.c
- test cases/linuxlike/14 static dynamic linkage/meson.build
- test cases/linuxlike/14 static dynamic linkage/verify_static.py
An alternative implementation of #4832.
> Report xpass results as failures.

- mesonbuild/rewriter.py
Changed an error message to reflect the actual code
This should go into 0.50.2.
> rewriter: fix error message

- mesonbuild/build.py
- mesonbuild/compilers/cpp.py
- mesonbuild/coredata.py
- mesonbuild/dependencies/base.py
- mesonbuild/envconfig.py
- mesonbuild/environment.py
- mesonbuild/mesonlib.py
- mesonbuild/mintro.py
The big thing is only `PerMachineDefaultable` needs to be optional across the board, not `PerMachine`. \[I later want to make it so that default_missing and friends produce a new object, so we don't store any `PerMachineDefaultable`s, just `PerMachines`. In other words, `PerMachineDefaultable` would be a factory of sorts.]
CC @dcbaker
> Add some type annotations and fix lints

- docs/markdown/snippets/linkcustom.md
- mesonbuild/backend/backends.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/build.py
- test cases/common/216 link custom/meson.build
- test cases/common/217 link custom_i single from multiple/generate_conflicting_stlibs.py
- test cases/common/217 link custom_i single from multiple/meson.build
- test cases/common/217 link custom_i single from multiple/prog.c
- test cases/common/218 link custom_i multiple from multiple/generate_stlibs.py
- test cases/common/218 link custom_i multiple from multiple/meson.build
- test cases/common/218 link custom_i multiple from multiple/prog.c
Based on https://github.com/mesonbuild/meson/pull/5103
Adds ability to use `custom_target[i]` in `link_with` and `link_whole` kwargs.
> Can link against custom_target[i]

- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/boost.py
- mesonbuild/dependencies/dev.py
- test cases/frameworks/15 llvm/meson.build
- test cases/frameworks/2 gtest/meson.build
- test cases/frameworks/3 gmock/meson.build
> Fix sub dependencies

- docs/markdown/Builtin-options.md
- mesonbuild/compilers/cpp.py
- test cases/common/91 default options/meson.build
> add -fno-exceptions if cpp_eh=none is specified

- mesonbuild/msetup.py
the error would occurs when specifying c_winlibs
> fix error when show default config of list

- run_project_tests.py
- test cases/frameworks/18 vulkan/vulkanprog.c
"But surely nobody would indent by having spaces first,
and tabs after that. Right? Right?"
> Better detection of tab indentation.

- docs/markdown/FAQ.md
This is very frequently asked, and I don't know any one place where we document this reasoning.
> FAQ: Add an entry about the library naming scheme with MSVC [skip ci]

- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/dependencies/base.py
- mesonbuild/environment.py
- mesonbuild/interpreter.py
- mesonbuild/mesonlib.py
- mesonbuild/mtest.py
This started out as me thinking "hey mypy can help me fix [this](https://gitlab.freedesktop.org/idr/mesa/-/jobs/298246)!" and ended with me cursing loudly. This code was pretty difficult to follow and had some pretty terrible things (changing the types of attributes silently). I think mtest is a little cleaner now, and the annotations helped my find both the bug I was looking for and a few others that I didn't know where there. So if you've ever questioned the value of type annotations, they're paying off here.
> Mtest annotations and bug fixes

- mesonbuild/compilers/fortran.py
- test cases/fortran/1 basic/meson.build
Just a couple of things I noticed working on ICL support.
> Fortran fixes

- mesonbuild/dependencies/base.py
> Fix dependency found but it isn't a library

- mesonbuild/msubprojects.py
Signed-off-by: Markus Theil <markus.theil@tu-ilmenau.de>
> subproject: fix update_svn

- mesonbuild/cmake/interpreter.py
Now, all source files are ignored that are not part of the language of the target. This is also what CMake does. Additionally, it is now supported to build source files that are generated inside the build directory.
> cmake: Minor fixes to handle some CMake specific behavior

- mesonbuild/environment.py
Works for me, lightly tested.
Fixes #5474
> environment: better xcode 11 clang detection

- mesonbuild/interpreter.py
This ensures that invalid arguments properly cause errors, but doesn't
otherwise change semantics
> Further deduplicate Interpreter native kwarg code

- cross/tvos.txt
- mesonbuild/build.py
- mesonbuild/compilers/compilers.py
- mesonbuild/dependencies/ui.py
- mesonbuild/envconfig.py
There is difference between Apple iOS and tvOS. This patch provides tvOS support.
> tvOS: added support AppleTVOS

- docs/markdown/Builtin-options.md
> docs: Update libdir caveat [skip ci]

- msi/createmsi.py
Cx_freeze has not been updated in a long time and does not
even work with Python > 3.5.
> Switch to using Pyinstaller. Closes #5050.

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/compilers.py
Fixes #5541 and another bug I found after fixing that one.
How would I go about adding a unit test for these bugs? I'm not sure how the cross-compilation unit tests work.
> Fix two errors when cross-compiling with Vala

- mesonbuild/backend/xcodebackend.py
> xcodebackend: Fix iterating compilers after host/build changes

- mesonbuild/modules/windows.py
- test cases/windows/5 resources/res/meson.build
Flatten the windres module arguments list
Fix #5464
> Fix windres module argument flattening

- run_unittests.py
- test cases/frameworks/23 hotdoc/installed_files.txt
Does not fix all cases but it's a start.
> Do not mutate global envvar state in tests

- mesonbuild/compilers/clike.py
- mesonbuild/environment.py
remake pull request rebased on master since a more recent patch reverted the changes
Please squash.
> Make faster w defender atp

- mesonbuild/dependencies/base.py
see https://cmake.org/cmake/help/latest/prop_tgt/IMPORTED_IMPLIB.html
> try IMPORTED_IMPLIB before IMPORTED_LOCATION for cmake dependencies

- man/meson.1
- mesonbuild/mtest.py
As discussed on IRC with @nirbheek
> Change meson test's build failure exit code to 125

- mesonbuild/scripts/meson_exe.py
This should help saves some unnecessary recompilation
> meson: skip captured write if content didn't change

- mesonbuild/compilers/compilers.py
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter.py
- mesonbuild/scripts/dist.py
Just fixes every flake8 warning
> fix all flake8 issues

- run_unittests.py
@TingPing has a repository that contains a grammar for meson which is used by linguist (GitHub), and by many editors such as Atom, VS Code, TextMate, Sublime Text, etc. Add CI so that we notice that the function list in it is out of date, such as https://github.com/TingPing/language-meson/pull/3
It's harder to do this generically for other syntax such as the `in` keyword, but it's better than nothing.
CI will fail till the aforementioned PR is merged.
> unit tests: Test more syntax highlighting data

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/__init__.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/coredata.py
- mesonbuild/linkers.py
- mesonbuild/mesonlib.py
- mesonbuild/modules/gnome.py
This is a bunch of cleanup patches from my work on splitting the linker and compiler representations, none of this has a lot to do with dynamic linkers perse, so I thought we might be able to land this ahead of the dynamic linker stuff so I could stop rebasing it.
> Compiler linker cleanups

- mesonbuild/interpreterbase.py
- test cases/common/164 disabler/meson.build
Fixes #5659
Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>
> meson: handle nested disabler

- docs/markdown/snippets/dist-command.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/mdist.py
- mesonbuild/mesonmain.py
- run_unittests.py
Also some cleanups now that we have 3.5 as the minimum Python version.
> Made dist into a top level command

- run_unittests.py
Allows people to run specific tests and/or enable verbose mode.
> unit tests: Convert unittest args to pytest

- mesonbuild/mdist.py
Fixes https://github.com/mesonbuild/meson/issues/5732
> dist: Pass right build options when configuring dist directory

- mesonbuild/ast/interpreter.py
- mesonbuild/ast/introspection.py
- test cases/unit/55 introspection/meson.build
Since 0.51.2 isn't out yet, this should also be included in it if possible.
> mintro: Fix crash related to the sources kwarg (fixes #5741)

- cross/armclang-linux.txt
- mesonbuild/compilers/mixins/arm.py
I actually did this ages ago but forgot to open a PR. 🤦‍♂
> Make ARM compilers work on Linux.

- docs/markdown/SourceSet-module.md
- docs/markdown/snippets/source_set_enhancements.md
- mesonbuild/modules/sourceset.py
- test cases/common/222 source set realistic example/meson.build
- test cases/common/222 source set realistic example/zlib.cc
> sourceset: add all_dependencies() method

- mesonbuild/mdist.py
It was not obvious that 'meson dist' must be run from build directory.
> dist: Add '-C' option and print better error message

- mesonbuild/backend/ninjabackend.py
Background: [Squish Coco](https://doc.froglogic.com/squish-coco/latest/) is a commercial, cross-platform C/C++ code coverage tool often used in heavily-regulated software industries (medical devices, avionics, etc.). To instrument your code, you have to configure your `PATH` to point to Squish Coco's compiler/librarian/linker wrappers that mimic/redirect to the native toolchain. For the most part, this works transparently, except for the situations when it doesn't ;). This PR addresses one of such situations. 
For some reason, when invoked with `/showIncludes`, Squish Coco's `cl` wrapper outputs the dependency info to `stderr` rather than `stdout`, which trips the current `ninjabackend`'s VS dependency prefix detection code. Checking `stderr` if `stdout` doesn't contain expected output …
> ninjabackend: Squish Coco support (on Windows)

- data/syntax-highlighting/vim/syntax/meson.vim
- docs/markdown/Reference-manual.md
- docs/markdown/Release-notes-for-0.52.0.md
- docs/sitemap.txt
- mesonbuild/ast/interpreter.py
- mesonbuild/interpreter.py
- mesonbuild/interpreterbase.py
- run_unittests.py
- test cases/common/1 trivial/meson.build
- test cases/common/156 index customtarget/meson.build
- test cases/common/163 disabler/meson.build
- test cases/common/2 cpp/meson.build
- test cases/common/3 static/meson.build
- test cases/common/4 shared/meson.build
- test cases/common/52 custom target/meson.build
This is the `is_disabler` part of #5427.
> Add is_disabler function

- mesonbuild/modules/gnome.py
> Revert "gnome: Use find_program() to get glib-compile-resources"

- docs/markdown/Users.md
Add [RxDock](http://www.rxdock.org/) to the list of Users.
> Add RxDock

- test cases/common/156 index customtarget/meson.build
- test cases/common/2 cpp/meson.build
- test cases/common/52 custom target/meson.build
- test cases/common/54 run target/meson.build
- test cases/common/9 header install/meson.build
This is the part of #5427 that fixes handling of disablers being passed to sources.
> Add tests for sources that are disablers.

- mesonbuild/envconfig.py
- mesonbuild/environment.py
- mesonbuild/mesonlib.py
https://mail-index.netbsd.org/pkgsrc-users/2019/08/23/msg029220.html
> Support NetBSD aarch64 and earm.

- mesonbuild/compilers/mixins/gnu.py
- test cases/common/225 include_dir dot/meson.build
- test cases/common/225 include_dir dot/rone.h
- test cases/common/225 include_dir dot/src/main.c
- test cases/common/225 include_dir dot/src/meson.build
- test cases/common/225 include_dir dot/src/rone.c
> Fix gcc include dot

- test cases/common/224 test priorities/meson.build
- test cases/common/224 test priorities/test.sh
- test cases/common/224 test priorities/testprog.py
- test cases/common/54 run target/scripts/script.sh
> Shell script cleanup.

- mesonbuild/ast/interpreter.py
- test cases/unit/59 introspect buildoptions/meson.build
This one was a bit more difficult to fix and required refactoring some of the node resolution logic.
> mintro: Fix resolving nodes in kwargs (fixes #5884)

- docs/markdown/Quick-guide.md
* Updated the content and layout of the quickstart guide for better flow and readability.
* Included Troubleshooting section for Common Issues (#4890)
* TODO: Review final two sections "Using Meson as a Packager, and "Compiling a Meson Project"
> Update Quickstart Guide [skip ci]

- mesonbuild/compilers/objc.py
> fix objc freestanding sanitycheck

- docs/markdown/Reference-tables.md
- docs/markdown/snippets/solaris.md
- mesonbuild/compilers/compilers.py
- mesonbuild/environment.py
- run_unittests.py
- test cases/common/136 get define/meson.build
- test cases/common/162 external program shebang parsing/main.c
This is just a bit of work I did on top of the dynamic linker split work to get illumos working. There are are still failing tests, but this gets us a little closer and canonicalizes the name to use in `*_machine`
> Solaris and Illumos fixups

- mesonbuild/environment.py
llvm-mingw uses a wrapper script to inject (among other things) a `-target` argument into the clang command, which breaks `-Wl,--version`. This confuses Meson into thinking the linker is some unknown version of Apple ld, which breaks builds.
This patch makes it detect and recover from the issue.
Fixes #5910
> Workaround for mingw-llvm linker (lld) misdetection

- mesonbuild/environment.py
- mesonbuild/mesonlib.py
- test cases/common/131 generated assembly/square-x86_64.S.in
- test cases/linuxlike/14 static dynamic linkage/meson.build
Additional fixes for Solaris 11.4 on top of the recent changes from @dcbaker in https://github.com/mesonbuild/meson/pull/5820.
> Solaris fixes

- docs/markdown/IDE-integration.md
Hope I didn't miss any other errors.
> Fix improperly closed backtick in online docs

- mesonbuild/mesonlib.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/i18n.py
A small refactoring to make the code shorter/simpler.
> Caching cleanup

- docs/markdown/Reference-tables.md
- mesonbuild/envconfig.py
Add the CPU family for the MicroBlaze processor.
> Add MicroBlaze CPU family

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/linkers.py
- run_unittests.py
> Correctly handle platform-specific LDFLAGS options (Windows)

- mesonbuild/minstall.py
> Catch NotADirectoryError to fix selinux error

- docs/markdown/External-commands.md
- docs/markdown/Reference-manual.md
- docs/markdown/snippets/env_dict.md
- mesonbuild/interpreter.py
- test cases/unit/69 test env value/meson.build
- test cases/unit/69 test env value/test.py
> environment: Support taking values from dict

- mesonbuild/cmake/interpreter.py
- mesonbuild/cmake/traceparser.py
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter.py
- mesonbuild/modules/cmake.py
I tried to build AOM (https://aomedia.googlesource.com/aom/) as a Meson subproject, and I'm hitting many issues. Here is a patchset of various fixes needed. There are still other issues, notably lack of support for objects library.
> cmake: Various fixes

- docs/markdown/Reference-manual.md
- mesonbuild/interpreter.py
> Correctly warn and document options to benchmarks

- mesonbuild/wrap/wrap.py
Don't manually emulate a partial `git clone` when `depth` option is not used. This keeps `git describe` working as before and generally supports workflows that depend on tags and branches to exist in a wrap downloaded subproject.
This also fixes downloading via git not working at all on CentOS 7 (git version 1.8.3.1).
For the `depth` case use `git clone --branch=... --depth=...` when possible and only fall back to manual emulation wraps that specify a full commit id, because for some reason that does not work with the clone based workflow.
Fixes: #5991 (Regression in wrap support with git)
> wrap: Rework `depth` support for git. (closes #5991)

- mesonbuild/compilers/mixins/gnu.py
updated the ClikeCompiler.has_argument method to parse the stderr of the compiler check
to ensure the compile argument is truely supported by the cpp compiler.
> Fix for issue 5355 compiler.get_supported_argument reports success on unsupported arguments

- mesonbuild/interpreterbase.py
- mesonbuild/mlog.py
Implemented this for fun.
Fixes: #5946
> Make parser errors print relative path to meson.build file

- mesonbuild/interpreterbase.py
- test cases/common/163 disabler/meson.build
> Fix `if not disabler()` case

- mesonbuild/compilers/c.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/mixins/islinker.py
I wanted to rebase #5901 to master, but I accidentally deleted the remote branch instead of force-pushing, so I had to make a new PR. Sorry about that.
> BasicLinkerIsCompilerMixin and Emscripten fixes

- mesonbuild/mconf.py
Also don't print yielding subproject options.
--
When many subprojects are configured (e.g. gst-build), the output is currently a mess. This sorts and align options per subprojects. It also prepare for when we'll have per-subproject builtin options.
> mconf: Group all options per subproject and align all groups

- tools/cmake2meson.py
checked with `mypy --version`  0.740
> cmake2meson: improve exceptions, add type annotations, use argparse

- .travis.yml
- ciimage/Dockerfile
I had to update gcrypt from 11 to 20. Let's see if it works...
> Update Linux CI image to Ubuntu Eoan.

- mesonbuild/mconf.py
- run_unittests.py
Contains commits from both outstanding MRs.
> Option fixing, take 3

- mesonbuild/compilers/mixins/visualstudio.py
- run_unittests.py
Fixes #6101 (with a test), following up #5881.
> MSVC: support -LIBPATH
