mesonbuild/meson

- mesonbuild/backend/ninjabackend.py
- mesonbuild/environment.py
> Ask Ninja to expand rsp files in compile_commands.json

- docs/markdown/Builtin-options.md
- docs/markdown/FAQ.md
- docs/markdown/snippets/nortti.md
- mesonbuild/compilers/cpp.py
Also has a one-commit fix for disabling exceptions with MSVC.
> Add option to disable RTTI

- mesonbuild/compilers/d.py
> Add -L= to soname linker argument, too.

- mesonbuild/wrap/__init__.py
- mesonbuild/wrap/wrap.py
- mesonbuild/wrap/wraptool.py
- test cases/common/91 dep fallback/tester.c
fixes #6130 
MWE to reveal problem / fix (make sure your computer is offline first):
```meson
project('offline')
dep = dependency('aaa', required: false, fallback: ['gtest', 'gtest_dep'])
```
also added type annotation in wrap.py, fixing other import/syntax issues thereby discovered.
To type check just part of Meson, in general do like:
```sh
mypy mesonbuild/wrap --follow-imports=skip
```
> wrap.py: fail gracefully if no internet connection

- mesonbuild/mtest.py
I have had cases where having the start time reported on the stdout of a test could be useful (especially when tests are run in parallel). This patch simply plumbs that data to TestRun and uses it to include it on the `get_log` string representation.
> mesonbuild/mtest: plumb and report a test's start time

- docs/markdown/Fs-module.md
- docs/markdown/snippets/fsmodule.md
- docs/sitemap.txt
- mesonbuild/interpreter.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/fs.py
- test cases/common/227 fs module/a_symlink
- test cases/common/227 fs module/meson.build
- test cases/common/227 fs module/subdir/meson.build
- test cases/common/227 fs module/subdir/subdirfile.txt
- test cases/common/227 fs module/subprojects/subbie/meson.build
- test cases/common/227 fs module/subprojects/subbie/subprojectfile.txt
- test cases/common/227 fs module/subprojects/subbie/subsub/meson.build
- test cases/common/227 fs module/subprojects/subbie/subsub/subsubfile.txt
I figured we'd start simple. I guess there may be cases where people would want the checks to not follow symlinks, but lt should be rare. Let's add those only after someone actually reports needing them.
> Created the filesystem module.

- mesonbuild/linkers.py
Dealt with #6145 
Should I add a test case to verify the bug fixed?
> pass sanitize option to linker on macOS

- docs/markdown/Wrap-dependency-system-manual.md
The current state of this manual can best be described as... confusing. The flow of the page jumps from one topic to the next without ever actually telling you what you can do, so it's almost impossible to keep track of what is supported, while instead going into involved derails about why you'd want to use a wrap, and scattering some (but not all) information throughout the promo material.
The most important changes this rewrite does (aside from turning supported keys into a list of bullet points) is adding documentation for the lead_directory_missing property, and mentioning that wrap-hg and wrap-svn exist. I had to find out all of this by reading the source code implementation, so let's try to save other people the effort.
Other miscellania: as per @jpakkane's comment, take the …
> docs: major revamp of the Wrap format description [skip ci]

- mesonbuild/modules/hotdoc.py
> hotdoc: work around argparse syntax ambiguity

- mesonbuild/environment.py
> Raise an exception if we cannot detect the MSVC compiler target architecture

- mesonbuild/linkers.py
> Enable code coverage using LLVM on macOS Catalina

- mesonbuild/backend/ninjabackend.py
- mesonbuild/cmake/common.py
- mesonbuild/cmake/fileapi.py
- mesonbuild/cmake/interpreter.py
- mesonbuild/interpreter.py
- mesonbuild/mlog.py
- run_project_tests.py
- test cases/cmake/13 system includes/meson.build
With this PR, CMake subprojects will correctly handle system include directories.
> cmake: Handle CMake system include dirs (closes #6079)

- mesonbuild/interpreter.py
Refactor the code inside a common function for consistency.
It's not needed to add dependencies in func_configure_file() because
it's already done in run_command_impl(). Do it only for files from
`input:` in the case some of them does not end up in the command
arguments.
> Simplify list of build def files

- mesonbuild/dependencies/base.py
- mesonbuild/interpreter.py
- test cases/linuxlike/5 dependency versions/meson.build
Also harminize a bit the logged message.
> Fix crash when checking multi version on subproject dep

- mesonbuild/wrap/wrap.py
507cf47507cf47 broke the combination of clone-recursive without depth,
because it passed depth (as None) to git.
To fix this the depth option is now generated once as a list when depth is set
and else set to an empty list and unpacked into the argument this when
needed. This reduces duplication and allows code to work the same for
both cases.
> wrap: Resolver.get_git: Factor out --depth argument generation and make sure not to pass None as parameter

- mesonbuild/cmake/interpreter.py
Previously, warnings genereated in CMake were not logged because
CMake sends them to stderr alongside the trace information. With
this PR, only real trace lines are send to the trace parser and
all other lines in stderr are logged as warnings.
0.52 branch version
> cmake: Log warnings in CMakeLists.txt

- mesonbuild/interpreter.py
- mesonbuild/mesonlib.py
- test cases/common/14 configure file/dumpprog.c
- test cases/common/14 configure file/meson.build
> Revert "Have set() and set_quoted() of configuration object work with newlines."

- mesonbuild/backend/vs2010backend.py
As outlined in this VS forum thread:
https://developercommunity.visualstudio.com/content/problem/234871/cannot-load-project-with-duplicated-project-items.html
Visual Studio cannot open projects files that have duplicated items, for example:
```
<ItemGroup>
<CLInclude Include="glib-enumtypes.h"/>
<CLInclude Include="glib-enumtypes.h"/>
</ItemGroup>
```
So prevent writing duplicated items in the generated .vcxproj files
Fixes issue #6147
> Prevent the presence of duplicated items in .vcxproj files

- docs/markdown/Continuous-Integration.md
CI example docs updates including:
* Travis-CI LTS images have been more up to date in recent time
* update obsolete Travis-CI parameters
* add GitHub Actions example for MacOS, Linux and Windows
* note that AppVeyor also has MacOS and Linux
* correct Appveyor yml syntax
> doc: update travis-CI info and add GitHub Actions example [skip ci]

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/find_program.md
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter.py
- test cases/common/28 find program/meson.build
- test cases/common/28 find program/scripts/test_subdir.py
> find_program(): Add 'dirs' keyword argument

- .github/workflows/lint_mypy.yml
- mesonbuild/mintro.py
It also includes some slight refactoring to make type annotations easier and adds the `mintro.py` to the mypy CI.
> types: Add type annotatins to mintro.py

- mesonbuild/dependencies/base.py
Should make CI go back to green.
> Fix typing import bug.

- mesonbuild/compilers/mixins/gnu.py
Unfortunately, I can't test this code since I don't have an MSYS2 setup, however, this should work from the look of the [compiler output](https://github.com/mesonbuild/meson/issues/6336#issuecomment-565498690). My guess is that the output might not land on `stderr` or that there are special windows characters in the output (windows style newlines for instance).
> default inc dirs: Fix warning on MSYS (fixes #6336)

- msi/createmsi.py
Simply updated the code to conform with Python recommendations based on PyLinter locates in the project.
> Clean MSI generator Try 2

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/summary.md
- mesonbuild/interpreter.py
- test cases/unit/74 summary/meson.build
> summary: Change 'section' to be a kwarg instead of positional

- docs/markdown/Contributing.md
- run_project_tests.py
- test cases/cuda/1 simple/prog.cu
- test cases/cuda/10 cuda dependency/c/prog.c
- test cases/cuda/11 cuda dependency (nvcc)/modules/prog.cu
- test cases/cuda/11 cuda dependency (nvcc)/version_reqs/prog.cu
- test cases/cuda/12 cuda dependency (mixed)/kernel.cu
- test cases/cuda/12 cuda dependency (mixed)/prog.cpp
- test cases/cuda/2 split/lib.cu
- test cases/cuda/2 split/main.cpp
- test cases/cuda/2 split/static/main_static.cpp
- test cases/cuda/3 cudamodule/prog.cu
- test cases/cuda/4 shared/main.cu
- test cases/cuda/5 threads/main.cu
- test cases/cuda/6 std/main.cu
- test cases/cuda/7 static vs runtime/main.cu
- test cases/cuda/8 release/main.cu
- test cases/cuda/9 optimize for space/main.cu
doc how to use cuda tests from Windows, and remove unused arguments from Cuda code (quality/refactor)
> refactor/doc: cuda tests

- cross/armclang-linux.txt
- mesonbuild/compilers/c.py
- mesonbuild/environment.py
Basically #6354 with all the additional patches added.
> Updated linker MR

- mesonbuild/modules/pkgconfig.py
- run_unittests.py
Introduced in https://github.com/mesonbuild/meson/pull/3131
> pkgconfig module: add FeatureNew for requires: dependency('foo')

- mesonbuild/dependencies/base.py
The latest Windows 10 release in May 2019 added zero-sized files that act as stubs which when launched from cmd.exe spawn the Windows Store to install those apps. This also includes python.exe and python3.exe:
https://devblogs.microsoft.com/python/python-in-the-windows-10-may-2019-update/
Unfortunately, `import('python').find_installation('python3')` will then think that python3.exe is available on Windows. Or, worse, if the user has a fresh installation of Windows 10 and then installs the Python 3 using the official installer (not the Windows Store app), we will *still* pickup this stub because it will be first in `PATH`.
Always remove the WindowsApps directory from `PATH` while searching.
First reported at https://gitlab.freedesktop.org/gstreamer/cerbero/issues/223
> find_program: Ignore programs in the WindowsApps directory

- run_tests.py
`get_backend_commands()` doesn't get called when we run tests as
subprocesses, so detect ninja on import. This should speed up CI.
Fixes https://github.com/mesonbuild/meson/issues/5888
> run_tests: Fix detection of ninja 1.9

- docs/markdown/Reference-tables.md
- mesonbuild/envconfig.py
> Add s390 to list of known architectures

- docs/markdown/Users.md
It's worth to list a meson project building a firmware.
> Users.md: add qboot

- docs/markdown/Reference-tables.md
- mesonbuild/envconfig.py
> Add m68k to known cpus for Motorola 68000 series processors

- mesonbuild/environment.py
_guess_linker method
Fixes #6448
> environment: Fix initialization of compilers that don't use a

- mesonbuild/wrap/wrap.py
> wrap: Fix git clone with commit id in revision

- mesonbuild/coredata.py
> mconf: Recommend using --reconfigure when setting unknown options

- docs/markdown/howtox.md
> docs: small cleanups and clarifications to setting the dynamic linker

- mesonbuild/interpreter.py
- run_unittests.py
- test cases/unit/72 summary/meson.build
> summary: Fix empty list case

- README.md
Cleaning the project readme, and untangling Information that are not relevant, added some links to the Meson build system website.  Hopefully, my changes did not make things more confusing.
Thanks.
> Cleaning project readme

- mesonbuild/coredata.py
- run_unittests.py
> Fix prefix dependent option defaults

- docs/markdown/snippets/more_meson_sample_templates.md
- mesonbuild/minit.py
- mesonbuild/templates/cstemplates.py
- mesonbuild/templates/cudatemplates.py
- mesonbuild/templates/javatemplates.py
- mesonbuild/templates/mesontemplates.py
- mesonbuild/templates/objcpptemplates.py
- run_unittests.py
Adding new Meson sample templates for (Cuda, Java, C#, Objective-c++).  Hopefully, I will get green.
> Add new Meson sample templates

- mesonbuild/dependencies/ui.py
A few small cleanups before fixing the actual bug
> Wx widgets static

- mesonbuild/dependencies/ui.py
Sometimes qt can be installed not as framework on MacOS.
For instance, one way to achieve this behaviour is to use 
conan package manager.
Allow falling back to simple library search if framework was
not found. In addition, allow to find the debug version of qt debug
libraries which have "_debug" suffix added to them.
This is an extended version of the previous fix #5111.
Fixes #5091
> depdenencies/qt: Second attempt to allow qt --no-framework on MacOS.

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/per_subproject_builtin.md
- mesonbuild/backend/backends.py
- mesonbuild/coredata.py
- mesonbuild/interpreter.py
- mesonbuild/mintro.py
- test cases/common/229 persubproject options/foo.c
- test cases/common/229 persubproject options/meson.build
- test cases/common/229 persubproject options/subprojects/sub1/foo.c
- test cases/common/229 persubproject options/subprojects/sub1/meson.build
- test cases/common/229 persubproject options/subprojects/sub2/foo.c
- test cases/common/229 persubproject options/subprojects/sub2/meson.build
> Make default_library per-subproject built-in option

- run_project_tests.py
You can't sort TestDefs at the moment. Also, don't do an inplace sort while we're at it.
> run_project_tests: Fix it to actually work

- mesonbuild/msetup.py
- run_unittests.py
Split out from https://github.com/mesonbuild/meson/pull/6565 so it doesn't get lost, plus add a test
> Unbreak --profile-self

- docs/markdown/CMake-module.md
- mesonbuild/cmake/traceparser.py
This is basically #6368, without the refactoring portion. It should be safe to merge this PR once the first CMake RC is out.
Related CMake MRs:
- https://gitlab.kitware.com/cmake/cmake/merge_requests/4169
- https://gitlab.kitware.com/cmake/cmake/merge_requests/4242
> cmake: Add support for the new JSON trace format

- docs/markdown/Builtin-options.md
- docs/markdown/snippets/unitysize.md
- mesonbuild/backend/backends.py
- mesonbuild/coredata.py
- mesonbuild/optinterpreter.py
- run_unittests.py
The first commit refactors the integer option class to make this work.
> Add unity block size option

- docs/markdown/Contributing.md
- run_project_tests.py
Extra stuff I wrote while working on #6620
> Various cleanups and documentation improvements for run_project_tests.py

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/minstall_quiet.md
- mesonbuild/minstall.py
- mesonbuild/scripts/depfixer.py
With these, `meson install` with gst-build on my Windows machine goes from taking 15.3 seconds to 4 seconds. `meson install --only-changed` goes from 11.6 seconds to 0.9 seconds.
Also fixes https://github.com/mesonbuild/meson/issues/4496.
> meson install perf improvements and new option --quiet

- docs/markdown/Reference-manual.md
> docs: Mention `cuda` as supported language [skip ci]

- mesonbuild/cmake/data/preload.cmake
- mesonbuild/cmake/interpreter.py
- mesonbuild/cmake/traceparser.py
- setup.py
- test cases/cmake/8 custom command/subprojects/cmMod/CMakeLists.txt
- test cases/cmake/8 custom command/subprojects/cmMod/cmMod.cpp
- test cases/cmake/8 custom command/subprojects/cmMod/cpyTest.cpp
- test cases/cmake/8 custom command/subprojects/cmMod/cpyTest/CMakeLists.txt
- test cases/cmake/8 custom command/subprojects/cmMod/cpyTest/cpyTest.hpp
- test cases/cmake/8 custom command/subprojects/cmMod/cpyTest/cpyTest2.hpp
- test cases/cmake/8 custom command/subprojects/cmMod/cpyTest/cpyTest3.hpp
- test cases/cmake/8 custom command/subprojects/cmMod/cpyTest/cpyTest4.hpp
Closes https://github.com/mesonbuild/meson/issues/6632
> cmake: Fix dependency loops in custom targets (fixes #6632)

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/summary.md
- mesonbuild/interpreter.py
- mesonbuild/mlog.py
- run_unittests.py
- test cases/unit/72 summary/meson.build
How this looks like with gst-build. Note that it is a 100% automatic summary section, no changes are needed in gst-build to produce that summary.
> Summary improvements

- mesonbuild/build.py
- mesonbuild/mdist.py
- mesonbuild/minstall.py
- mesonbuild/msetup.py
- mesonbuild/msubprojects.py
- mesonbuild/mtest.py
Cherry-picking Python2 % syntax from Meson commands.
> Cherry-picking - (rm python2 % add python3 .format)

- .github/workflows/lint_mypy.yml
- docs/markdown/snippets/meson_compile_command.md
- mesonbuild/mcompile.py
- mesonbuild/mesonmain.py
- run_unittests.py
This is tested working with both msbuild and ninja/samu. Since our xcode
support is pretty much broken I didn't bother.
Fixes #6670
> mesonbuild: Add mcompile command

- docs/markdown/Builtin-options.md
- run_unittests.py
Otherwise you have to hunt through the source code. Specifically, this is defined in `mesonbuild/coredata.py`: `set_buildtype_from_others()` and `set_others_from_buildtype()`
> Document the details of optimization+debug vs buildtype

- mesonbuild/ast/interpreter.py
> ast: Do not resolve dict keys

- mesonbuild/ast/interpreter.py
- test cases/unit/57 introspection/meson.build
> ast: Implement dummy evaluate_notstatement

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/native_compiler_not_required.md
- mesonbuild/build.py
- mesonbuild/compilers/__init__.py
- mesonbuild/compilers/compilers.py
- mesonbuild/interpreter.py
- test cases/common/85 add language/meson.build
- test cases/failing/100 no native compiler/main.c
- test cases/failing/100 no native compiler/meson.build
- test cases/failing/101 no lang/main.c
- test cases/failing/101 no lang/meson.build
- test cases/warning/2 languages missing native/meson.build
Add add_languages(native:)
Split out from #6512.
> Add add_languages(native:)

- docs/markdown/Feature-autodetection.md
- docs/markdown/Unit-tests.md
Should help new users in situations like #6726.
> Document the requirement to run tests before coverage

- mesonbuild/environment.py
> Improve regular expression for MSVC compiler target arch detection

- mesonbuild/environment.py
Dynamic typing sucks!
Fixes #6799
> Fix bogus parameter passed to LLVMDynamicLinker (llvm-mingw regression)

- mesonbuild/minit.py
- mesonbuild/templates/cpptemplates.py
- mesonbuild/templates/cstemplates.py
- mesonbuild/templates/ctemplates.py
- mesonbuild/templates/cudatemplates.py
- mesonbuild/templates/dlangtemplates.py
- mesonbuild/templates/fortrantemplates.py
- mesonbuild/templates/javatemplates.py
- mesonbuild/templates/objcpptemplates.py
- mesonbuild/templates/objctemplates.py
- mesonbuild/templates/rusttemplates.py
- mesonbuild/templates/samplefactory.py
- mesonbuild/templates/sampleimpl.py
I have implemented a Meson template factory so we can add more programming languages and or project types if needed.
> sample factory implementation

- docs/markdown/IDE-integration.md
I think it's about time I added my app to this page.
> Adding Meson-UI to IDE-integration.md [skip ci]

- cross/ubuntu-armhf.txt
- docs/markdown/snippets/skipsanity.md
- mesonbuild/interpreter.py
- mesonbuild/mlog.py
Ping @keith-packard can you test if this fixes your issue?
> Add property to disable compiler sanity checks during cross compilation.

- docs/markdown/Reference-manual.md
Resuming closed PR #6672, start the review there.
Fixes #1949
> docs: why 'ninja test' depends on build_by_default targets [skip ci]

- mesonbuild/compilers/compilers.py
@jon-turney can you test if this fixes the issue?
> Only split linker args with D compilers. Closes: #6845

- mesonbuild/minstall.py
> Do not call restorecon if there are no files to install

- mesonbuild/mtest.py
Remove some weirdness from test output such as extra commas, missing
spaces and way too precise time durations. Also improve the overall
alignment of the output.
An example from a random project with tests:
Old output:
```
18/92 callbacker:unit_tests+fast / UT_callbacker_threads_count_get__uninitialized  OK      0.01884746551513672 s 
[snip]
84/92 callbacker:unit_tests+fast / UT_callbacker_resolve_try_X  OK      0.0040018558502197266 s 
85/92 callbacker:unit_tests+fast / FT_scheduling_order  OK      0.004071474075317383 s 
86/92 callbacker:unit_tests+fast / FT_TYPE_enums_behaviour  OK      0.0039670467376708984 s 
87/92 callbacker / echo-server, no arguments  EXPECTEDFAIL0.0040166378021240234 s 
88/92 callbacker / echo-server, invalid mode  EXPECTEDFAIL0.004080772399902344 s 
89/92 …
```
> mtest: Improve test output formatting.

- .github/workflows/images.yml
- .github/workflows/os_comp.yml
- ci/ciimage/build.py
- ci/ciimage/cuda/image.json
- ci/ciimage/cuda/install.sh
- ci/ciimage/opensuse/install.sh
Also, a small fix for the OpenSUSE image.
> ci: Add CUDA image (Arch based)

- .github/workflows/os_comp.yml
This should fix the CUDA image error
> ci: Fix passing env vars

- mesonbuild/cmake/interpreter.py
- test cases/cmake/17 include path order/main.cpp
- test cases/cmake/17 include path order/meson.build
- test cases/cmake/17 include path order/subprojects/cmMod/CMakeLists.txt
- test cases/cmake/17 include path order/subprojects/cmMod/cmMod.cpp
- test cases/cmake/17 include path order/subprojects/cmMod/incA/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incB/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incC/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incD/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incE/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incF/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incG/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incH/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incI/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incJ/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incL/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incM/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incN/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incO/cmMod.hpp
- test cases/cmake/17 include path order/subprojects/cmMod/incP/cmMod.hpp
I think I went a bit overboard with the test case :smile:.
> cmake: Preserve include directory order (fixes #6959)

- mesonbuild/cmake/data/run_ctgt.py
- mesonbuild/cmake/traceparser.py
- test cases/cmake/8 custom command/subprojects/cmMod/CMakeLists.txt
- test cases/cmake/8 custom command/subprojects/cmMod/genMain.cpp
Fixes an issue with the use of CMake lists and that output redirection did not work.
> cmake: some fixes for add_custom_command

- mesonbuild/backend/backends.py
> backend: Fix file name confilcts by using the complete path

- docs/markdown/IDE-integration.md
> add introspect --buildsystem-files info [skip ci]

- mesonbuild/backend/vs2010backend.py
It is not unheard-of for a project to use pch for C++ but not for C
(because C usually builds fast enough anyway, so it's not worth the
developer overhead of maintaining the pch file).
This code was trying to optimize the vcxproj file size by detecting
"only one language", but it was only looking at the number of
pch-languages defined. This is incorrect when pch is not defined for all
languages in use.
Instead of tweaking the optimization further, remove it. This makes the
vs backend behave more like the ninja backend.
edit: typo fix, remove not remote in the last paragraph.
> backend/vs: Fix build when not all languages have pch

- .github/workflows/images.yml
- .github/workflows/os_comp.yml
- ci/ciimage/bionic/image.json
- ci/ciimage/bionic/install.sh
- ci/ciimage/build.py
- ci/ciimage/opensuse/install.sh
- docs/markdown/Contributing.md
- run_project_tests.py
- test cases/cmake/2 advanced/test.json
- test cases/cmake/3 advanced no dep/test.json
- test cases/frameworks/23 hotdoc/test.json
- test cases/linuxlike/13 cmake dependency/cmVers.sh
- test cases/linuxlike/13 cmake dependency/meson.build
Also includes some documentation fixes and additional options for skipping tests if a tool version is to old.
> ci: Add Ubuntu Bionic image

- .github/workflows/lint_mypy.yml
Pin pylint version to workaround https://github.com/PyCQA/pylint/issues/3524
> CI: pin pylint

- mesonbuild/interpreter.py
- mesonbuild/interpreterbase.py
- test cases/common/163 disabler/meson.build
This should fix any remaining issues in #5922.
> Allow get_variable to still function when the fallback is a disabler.

- docs/markdown/Users.md
See https://github.com/benwaffle/vala-language-server
> docs/Users: add Vala Language Server

- mesonbuild/backend/vs2010backend.py
- run_unittests.py
Fixes `Warning LNK4075: Ignoring '/INCREMENTAL' due to '/RELEASE' specification`
> Fix incremental debug builds in VS

- mesonbuild/environment.py
Naively calling `wasm-ld` is not reliable. The `wasm-ld` in `PATH` may not be the one that Emscripten is actually calling (it depends on Emscripten configuration); it may not even **be** in `PATH` at all, causing configuration to potentially fail.
This patch tricks `emcc` into passing `--Wl,--version` by supplying it with a dummy file to "compile". This does not work for some old Emscripten versions, in which case it'll report "unknown version". It still assumes the linker is `wasm-ld`.
> Improve Emscripten linker version detection

- mesonbuild/compilers/mixins/clike.py
The builtin check had a special case that if a header was provided and
the function wasn't defined, it would ignore the builtin to avoid
non-functional builtins (for example __builtin_posix_memalign in MSYS2).
GCC 10 gained support for __has_builtin() which now skipps this check
and because __has_builtin(__builtin_posix_memalign) returns true the
non functional builtin is now reported as available.
To get the old behaviour back move the special case in front of the actual
availability check.
Fixes #7113
> Fix builtin check in has_function() with GCC 10 on Windows

- mesonbuild/cmake/interpreter.py
No test, since the supported values are highly platform-dependent and CMake also does some magic with `CMAKE_CXX_STANDARD`.
> cmake: Ignore unknown c(pp)? stds (fixes #7104)

- mesonbuild/backend/backends.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/coredata.py
- mesonbuild/environment.py
(Original PR got closed inadvertently whilst updating it, sorry for the noise.)
> Fix outdated cross-compilation checks

- mesonbuild/dependencies/boost.py
This is especially useful for Conan, where only the boost.pc file is provided and manually setting BOOST_ROOT is not a good solution since it is in a private cache directory.
See #5438
No test case since this is very system specific (more precicely Conan specific).
> boost: Try extracting BOOST_ROOT from boost.pc

- mesonbuild/compilers/mixins/arm.py
Modifed buildtypes and armclang compiler flags to match documented results
> Fix armclang buildtype flags

- run_project_tests.py
- test cases/failing/100 fallback consistency/test.json
- test cases/failing/101 no native compiler/test.json
- test cases/failing/102 subdir parse error/test.json
- test cases/failing/103 invalid option file/test.json
- test cases/failing/104 no lang/test.json
- test cases/failing/105 no glib-compile-resources/test.json
- test cases/failing/36 pkgconfig dependency impossible conditions/test.json
- test cases/failing/67 subproj different versions/test.json
- test cases/failing/84 gtest dependency with version/test.json
- test cases/failing/98 fallback consistency/test.json
A lot of stuff is broken, seeing if this was the cause of it.
> Try reverting #7172 

- mesonbuild/cmake/interpreter.py
- mesonbuild/dependencies/base.py
> fix cmake target configuration selection.

- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/clike.py
while investigating #7017 I updated and added some type annotation.
In particular I used distinct variable names at https://github.com/mesonbuild/meson/compare/master...scivision:gfortran10?expand=1#diff-87a7f8e007afba4415d4810302dace30R918 to avoid failing type anno checks.
> add type anno: compilers/clike

- docs/markdown/Unit-tests.md
Just something felt nice to have
> docs/unit-tests: Show a test can have multiple suites

- mesonbuild/dependencies/cuda.py
**Testing**
Tested on NVIDIA TX2 with Ubuntu 16.04 and Python 3.5 with simple meson.build file:
`cuda_dep = dependency('cuda', version : '>=9', modules : ['cudart','cublas','cudnn','curand'])`
Tested unit tests with:
`./run_project_tests.py --only cuda --backend ninja`
- Test 6 std fails for an unrelated issue, probably to do with compiler version, it just doesn't like auto as a function return type
- All others pass
**Changes:**
- Fixed two regex match index operators that don't work with Python 3.5
- Added exception handler around one just to be sure
- Added support for finding ARM linux lib64 folder
> dependencies/cuda: Add support for ARM linux (fixes #7224)

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/compilers.py
This PR overall shaves off 10s from the build time in normal efl, and roughly 2 min. when building a special configuration of efl.
The details for each change are described in the commits themselfs.
> Performance optimize ninja backend

- docs/markdown/Users.md
Le is Machine Learning framework written in pure C which uses Meson as build system.
> docs/users: Add Le Machine Learning library

- azure-pipelines.yml
- docs/markdown/Gnome-module.md
- mesonbuild/backend/backends.py
- mesonbuild/scripts/gtkdochelper.py
Fixes problems building glib documentation as reported at https://cygwin.com/pipermail/cygwin-apps/2020-May/040144.html
Test case in a separate PR #7274, since it also exposes some pre-existing problems.
> glib gtkdoc fixes for Cygwin

- run_project_tests.py
- test cases/cmake/2 advanced/meson.build
- test cases/cmake/2 advanced/test.json
- test cases/cmake/5 object library/meson.build
- test cases/cmake/5 object library/test.json
See also #7307 #7314 #7316
cc @nirbheek
> ci: Use test.json to skip VS2017 azure tests

- docs/markdown/Gnome-module.md
- docs/markdown/snippets/gir_fatal_warnings.md
- mesonbuild/modules/gnome.py
> gnome: Add fatal_warnings kwarg to generate_gir()

- docs/markdown/Project-templates.md
Updated documentation for `meson init`, and added some stuff.
> update Project-templates.md [skip ci]

- mesonbuild/mconf.py
This is a regression introduced by #5489
> mconf: Fix regression when printing all options

- azure-pipelines.yml
- ci/ciimage/arch/install.sh
- ci/ciimage/bionic/install.sh
- ci/ciimage/eoan/install.sh
- ci/ciimage/fedora/install.sh
- ci/ciimage/opensuse/install.sh
- docs/markdown/howtox.md
- docs/markdown/snippets/clang_coverage.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/environment.py
- mesonbuild/scripts/coverage.py
- run_unittests.py
addresses #5652, #6160, and possibly #6691
> coverage: llvm-cov support

- mesonbuild/minit.py
Updated meson init end of generation message to show up to date commands and best practices.
> Update meson init info message.

- docs/markdown/Creating-releases.md
Updated this page to have some relevant info plus added more documentation.
> Update Creating-releases.md [skip ci]

- docs/markdown/Style-guide.md
Added a helpful guideline for naming variables in Meson.
> Update Style-guide.md [skip ci]

- data/macros.meson
- docs/markdown/Commands.md
- docs/markdown/Release-notes-for-0.54.0.md
- mesonbuild/mcompile.py
Closes: https://github.com/mesonbuild/meson/issues/7352
Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>
> mcompile: Add --verbose mode

- mesonbuild/modules/pkgconfig.py
- run_unittests.py
- test cases/common/47 pkgconfig-gen/dependencies/main.c
- test cases/common/47 pkgconfig-gen/meson.build
> pkgconfig: Add missing cflags in uninstalled files

- test cases/frameworks/7 gnome/mkenums/meson.build
> test: fix enum generation for GNOME

- docs/markdown/Wrap-dependency-system-manual.md
- docs/markdown/snippets/implicit_fallback.md
Explicitly document the behaviour of dependency('foo-1.0', required:
false).
> doc: Improve documentation of [provide] section in wrap files

- mesonbuild/compilers/cpp.py
- test cases/windows/17 msvc ndebug/main.cpp
- test cases/windows/17 msvc ndebug/meson.build
> fix msvc not recognising b_ndebug

- mesonbuild/backend/backends.py
- run_unittests.py
Since -Wl,-rpath= is not the only valid rpath ldflags syntax we need to try and match all valid rpath ldflags.
> backends: fix rpath match pattern

- mesonbuild/mtest.py
When running multiple test suites that include large amount of tests we have found that it is more beneficial to (1) report a summary of results at **after** all logs from tests have been written to stdout, and (2) in case of failure report a small summary of only those tests. This could be a subjective topic but I thought we could benefit from easying it out the process spotting failures.
> mtest: report failures and overall summary after test(s) logs

- mesonbuild/build.py
- mesonbuild/modules/pkgconfig.py
- run_unittests.py
- test cases/common/47 pkgconfig-gen/meson.build
- test cases/common/47 pkgconfig-gen/simple5.c
- test cases/common/47 pkgconfig-gen/test.json
See unit tests for the exact scenarios this PR fixes.
> pkgconfig: Fix various corner cases

- docs/markdown/Users.md
> docs/users: Add HarfBuzz [skip ci]

- mesonbuild/coredata.py
- mesonbuild/environment.py
- mesonbuild/interpreter.py
- mesonbuild/optinterpreter.py
- run_unittests.py
I've been getting confused between them and similarly-named other
things, so I figured it was high time to clean this up.
> Capitalize some constants in coredata

- mesonbuild/interpreter.py
- test cases/vala/1 basic/meson.build
> interpreter: Lower case languages before checking if 'c' is in the list

- data/shell-completions/zsh/_meson
> completions/zsh: Add --native-file

- docs/markdown/Style-guide.md
Written a new paragraph that would be better for this part of the document.
> Written a new paragraph for var naming recommendation

- run_unittests.py
- test cases/common/235 custom_target source/meson.build
- test cases/common/235 custom_target source/x.py
Fixed by #7494 without a test, so here's a test.
Extracted from https://github.com/mesonbuild/meson/pull/7539
> Test for spurious warning from get_target_filename

- docs/markdown/Tutorial.md
Clarifications that were observed to be needed when seeing a user try the Tutorial for the first time at:
https://www.twitch.tv/videos/709237047?t=50m20s
> docs: Clarify some FAQs in the Tutorial [skip ci]

- docs/markdown/Users.md
This may be strange but this paper rock scissors game will stick out.
> Add paper rock scissors to Users.md [skip ci]

- docs/markdown/Users.md
Not sure if anyone added anything written in Rust to this list but love to have my game be the first thanks.
> Add owl chess in Users.md

- mesonbuild/interpreter.py
> interpreter: Do not get variable on failed subproject

- test cases/common/157 wrap file should not failed/subprojects/.gitignore
- test cases/common/39 has function/meson.build
- test cases/unit/79 user options for subproject/.gitignore
> tests: fix lchmod check for glibc >= 2.32 (fixes #6784) 

- mesonbuild/scripts/depfixer.py
This should fix #7551 but I have not been able to test it myself.
> Dedup final install rpath.

- mesonbuild/ast/introspection.py
- run_unittests.py
- test cases/unit/83 cross only introspect/meson.build
This should have been part of #6532
> Handle add_languages(native:) in introspector

- CODEOWNERS
I probably know more about that code than anyone else, so I'm probably
the right person to be reviewing stuff in there.
> CODEOWNERS: add dcbaker for compilers and linkers

- mesonbuild/compilers/mixins/emscripten.py
- mesonbuild/linkers.py
- run_mypy.py
- run_unittests.py
There isn't too much to do here, but mypy did notice a bug in the code. So there's that.
> Add type annotations to the linkers module

- mesonbuild/modules/windows.py
Reverts mesonbuild/meson#7745. It did not pass CI.
> Revert "windows: reduce chance of going over path limit in backend/vs"

- docs/markdown/Adding-new-projects-to-wrapdb.md
I got some IRL comments that the existing docs are a bit confusing so I expanded them a bit.
> Improve docs for creating new wraps.

- .pylintrc
- mesonbuild/build.py
- mesonbuild/coredata.py
- mesonbuild/dependencies/scalapack.py
- mesonbuild/mesonlib.py
- mesonbuild/minstall.py
- mesonbuild/modules/qt.py
- mesonbuild/optinterpreter.py
I turned a few of these on in my type-annotations-for-compilers MR, and found a bunch of bugs. The rest are just more good errors I saw scanning the list.
> Even more pylint checking

- data/shell-completions/zsh/_meson
- mesonbuild/mdist.py
I didn't do the rewriter, it's complicated, and I don't think it's actually meant for people to use it on the command line anyway (more for IDEs to call into). There are a few less than optimal completions in here, but I don't really know what I'm doing, just banging on it and reading the docs till it works.
> Add most missing zsh completions

- mesonbuild/cmake/client.py
- mesonbuild/cmake/common.py
- mesonbuild/cmake/executor.py
- mesonbuild/cmake/fileapi.py
- mesonbuild/cmake/generator.py
- mesonbuild/cmake/interpreter.py
- mesonbuild/cmake/traceparser.py
- mesonbuild/dependencies/base.py
- run_mypy.py
This PR fully annotates the meson CMake module. Additionally, there are some minor changes in `run_mypy.py` in the first two commits.
> typing: CMake module

- mesonbuild/mcompile.py
Currently "meson compile" fails to "error MSB4126: The specified solution configuration "debug|x86" is invalid" in 32-bit builds.
> mcompile: fix "meson compile" for 32-bit MSVC build

- tools/boost_names.py
Not sure why mypy is complaining about this now, so I guess it is due to an update?
> typing: fix mypy typing error

- docs/markdown/IDE-integration.md
- docs/markdown/snippets/intro_extra_files.md
- mesonbuild/ast/introspection.py
- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/mintro.py
- run_unittests.py
- test cases/unit/57 introspection/sharedlib/meson.build
- test cases/unit/57 introspection/staticlib/meson.build
- test cases/unit/57 introspection/staticlib/static.h
Add `extra_files` to the target introspection output.
> intro: Add extra_files key to intro output (fixes #7310)

- mesonbuild/modules/gnome.py
> gnome: generate cpp gresource source in cpp projects

- mesonbuild/mtest.py
Fixes: https://github.com/mesonbuild/meson/issues/7903
> Fix gtest invoking while workdir is set

- docs/markdown/Qt5-module.md
- mesonbuild/modules/qt.py
> qt module: fix error message typo, translation qresource accepts qm not ts

- mesonbuild/scripts/symbolextractor.py
This almost the same implementation of OpenBSD, except that FreeBSD version of `nm` have the `-defined-only` option
> symbolextractor: Add FreeBSD support

- mesonbuild/msetup.py
EDIT: This doesn't actually fix #7915, sorry about that. I don't know how to unlink the issue.
I didn't see any other typos in the reporting.
> Fix host machine reporting typo in msetup.py

- mesonbuild/interpreter.py
Point people to the "werror" builtin option.
> add warning for projects with manually specified -Werror

- run_unittests.py
It's a bit odd we have a test for an external project that's not even in
the meson organization. Regardless, the json file was recently replaced
by a cson file. There is an  coffee-script-notation parser in pypi,
but I couldn't get it to work. Just delete the test
> run_unittests: delete test for external syntax highlighting

- .github/workflows/msys2.yml
For the upcoming switch from pkg-config to pkgconf in MSYS2
> Some minor MSYS2 CI fixes

- docs/markdown/Style-guide.md
I'm wondering if there is a case when someone would use the `subproject` method. Other than that I believe this should be close to what is recommended for the Meson build system.
> Dependency recommendation

- run_unittests.py
Here's a few fixups for the unit tests. Mostly these make things more resilient, but there's also a few simplifications in here too.
> Unittest fixups

- mesonbuild/compilers/fortran.py
> compilers/fortran: Add "none" to intel compielrs for standards

- mesonbuild/scripts/gettext.py
> Respect MESON_INSTALL_QUIET in gettext.py

- docs/markdown/Builtin-options.md
- docs/markdown/Configuring-a-build-directory.md
- mesonbuild/compilers/cpp.py
> compilers: add support for c++20/gnu++20

- mesonbuild/minstall.py
> Fix missed imports

- mesonbuild/backend/ninjabackend.py
- mesonbuild/msetup.py
> Ninja backend with Windows network paths does not work using MSVC

- docs/markdown/Getting-meson.md
Rewrapped to 80 columns at the same time.
> Fix last mention of Python 3.5. [skip ci]

- .github/workflows/nonative.yml
- .github/workflows/os_comp.yml
Being tested at https://github.com/mesonbuild/meson/commits/0.56.
> ci: Run github workflows on stable branches too

- docs/markdown/Users.md
Adding some Chicken Libraries packages to the big list of users.
> Add some Chicken-Libraries

- mesonbuild/dependencies/base.py
We currently use `mesonlib.is_osx()`, this isn't correct, as this is for the *build* machine, but we need to check for the machine that we are actually building for. This means that we can try frameworks when we shouldn't (cross compiling from osx -> !osx) and not when we should (cross compiling from !osx -> osx).
During this I added some type annotations, which caused mypy to notice some incorrect annotations in the boost module, as well as a legitimate bug (passing a method instead of the return value of that method)
Fixes # #8165
> Look for macos Framework dependencies when cross compiling

- mesonbuild/mesondata.py
- tools/gen_data.py
glob.glob() is not sorted, despite using shell-style wildcards, and the documentation does not mention this: https://bugs.python.org/issue21748
Recently, it does start mentioning "Whether or not the results are sorted depends on the file system." which does not really get to the heart of the matter...
This is causing fuzz too.
> gen_data.py: even more sorting

- mesonbuild/mtest.py
This pull request extracts the first commits out of #8200, with no visible change other than fixing #8212 and a few other small bugs.
> mtest: cleanups and bugfixes

- docs/markdown/FAQ.md
I added a note in the FAQ about our recent bitchfight.
> Added "How do I use a library before declaring it?" in the FAQ. [skip ci]

- mesonbuild/mesonlib/universal.py
See https://github.com/mesonbuild/meson/pull/8239
> Warn about .C and .H files

- mesonbuild/backend/xcodebackend.py
Add include paths from dependencies
> xcode-backend: fix include paths

- docs/markdown/snippets/buildtyperemains.md
- docs/markdown/snippets/cmake_package_version.md
- docs/markdown/snippets/customtarget_env.md
- docs/markdown/snippets/destdir.md
- docs/markdown/snippets/dist_subproject.md
- docs/markdown/snippets/external_project.md
- docs/markdown/snippets/meson_test_depends.md
- docs/markdown/snippets/meson_test_logs.md
- docs/markdown/snippets/pass_file_to_add_script.md
- docs/markdown/snippets/rewrite_allow_double_slash_project_id.md
- docs/markdown/snippets/rust_std_option.md
- docs/markdown/snippets/rust_test_format_support.md
- docs/markdown/snippets/summary_alignment.md
- docs/markdown/snippets/unstable-rust-module.md
- docs/markdown/snippets/versionfile.md
I noticed some embarrassing grammatical issues in my last pull request, so I decided to go through all the release notes snippets.
> Some copy editing for 0.57 release notes

- docs/markdown/Builtin-options.md
- docs/markdown/snippets/lto_mode.md
- docs/markdown/snippets/lto_threads.md
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/clang.py
- mesonbuild/compilers/mixins/gnu.py
- run_unittests.py
This adds two separate builtin options. I'm not sure how else to solve this, given that we have two separate toggles to add, and we can't break the existing options.
Fixes #7493
Fixes #7820
> Add option for thinLTO

- mesonbuild/environment.py
Fixed typos and reworded some sentences.
Signed-off-by: Ali Alnubani <alialnu@nvidia.com>
> environment: fix typos

- docs/markdown/snippets/install_dry_run.md
- mesonbuild/minstall.py
- run_unittests.py
> minstall: Add --dry-run option

- run_unittests.py
One minor error when already raising an assertion, and some inconsequential code cleanup.
> lint run_unittests.py

- mesonbuild/interpreter.py
- mesonbuild/interpreterbase.py
- mesonbuild/modules/unstable_rust.py
- run_unittests.py
This is just the implementation and one user in the rust module from #8299
> Type checking decorator incremental

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- run_unittests.py
- test cases/common/52 run target/meson.build
More exhaustive version of #8314.
> Fix exe wrapper detection for run targets.

- mesonbuild/linkers.py
The svr4 linker flag causes issues, especially when compiling c++.
Replace `-z` options with the equivalent non-svr4 flags. When using
`-blibpath`, we must be careful to include the default system library
path, or the resulting executables will not be able to find libc.
This patch was suggested by @andreaskem in #7581.
> aix: avoid -bsvr4 flag

- run_unittests.py
- test cases/frameworks/11 gir subproject/meson.build
- test cases/frameworks/12 multiple gir/meson.build
- test cases/frameworks/22 gir link order/meson.build
- test cases/frameworks/28 gir link order 2/meson.build
- test cases/vala/11 generated vapi/meson.build
This will fail at first because I disabled only one as a test.
> Disable failing Cygwin GIR test.

- mesonbuild/backend/ninjabackend.py
- test cases/fortran/9 cpp/main.c
- test cases/fortran/9 cpp/meson.build
This does not fix it yet, only has a test case to run through CI.
> Fix combining C and Fortran. Closes #8377.

- docs/markdown/Users.md
We just replaced Autoconf :) https://github.com/dosbox-staging/dosbox-staging/issues/854
Thank you to all Meson maintainers - this project is awesome!
> docs/users: Add DOSBox Staging

- packaging/createmsi.py
A bunch of random fixes. These are are standalone so the entire thing can be merged with plain rebase.
> Msi builder fixes

- docs/markdown/FAQ.md
Fixes #3234
It seems like this comes up a lot, so I took a stab a writing an FAQ entry explaining our reasoning for why we wont ever have user defined functions/macros. Please review and make suggestions and edits.
> docs/faq: Add a section on user defined functions and macros [skip ci]

- mesonbuild/wrap/wrap.py
> wrap: sha256 digest is not case sensitive

- mesonbuild/modules/pkgconfig.py
> pkgconfig: Add missing permitted kwargs

- docs/markdown/index.md
> Improved a paragraph

- mesonbuild/modules/unstable_cuda.py
Consequent to #8460 and [comments](https://github.com/mesonbuild/meson/pull/8460#issuecomment-789697043). @xclaesse?
> Port CUDA module to new API

- docs/markdown/Reference-manual.md
- docs/markdown/Syntax.md
- docs/markdown/snippets/string_replace.md
- mesonbuild/interpreterbase.py
- test cases/common/36 string operations/meson.build
> Add str.replace() method

- mesonbuild/backend/ninjabackend.py
I took a conservative approach, fixing only what I have observed wrong.
Fixes #8494
> change RSP quote style decision logic

- docs/markdown/Dependencies.md
- mesonbuild/dependencies/__init__.py
I think there are basically two people who understand how all of this fits together, expanding that by writing it down seems useful. Here's my attempt.
> Add some documentation on writing system dependencies

- mesonbuild/interpreter.py
- test cases/common/239 dependency include_type inconsistency/bar/meson.build
- test cases/common/239 dependency include_type inconsistency/meson.build
- test cases/common/239 dependency include_type inconsistency/subprojects/baz.wrap
- test cases/common/239 dependency include_type inconsistency/subprojects/baz/meson.build
- test cases/common/239 dependency include_type inconsistency/subprojects/foo.wrap
- test cases/common/239 dependency include_type inconsistency/subprojects/foo/meson.build
> interpreter: Cache found dependency before converting for include_type

- test cases/common/151 reserved targets/runtarget/echo.py
- test cases/common/151 reserved targets/runtarget/meson.build
- test cases/common/84 identical target name in subproject/meson.build
- test cases/common/84 identical target name in subproject/subprojects/foo/meson.build
- test cases/common/84 identical target name in subproject/subprojects/foo/true.py
- test cases/common/84 identical target name in subproject/true.py
This has been around for years. It started failing now. No idea why.
> Replace Unix shell commands with scripts.

- data/syntax-highlighting/vim/syntax/meson.vim
- docs/markdown/Reference-manual.md
- docs/markdown/snippets/range.md
- mesonbuild/ast/interpreter.py
- mesonbuild/interpreter.py
- mesonbuild/interpreterbase.py
- test cases/common/61 foreach/meson.build
> Add range() function

- docs/markdown/snippets/nopipe.md
- mesonbuild/compilers/fortran.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/interpreter.py
Let's check the time it takes to run this through CI. If there are any performance slowdowns we have to consider more deeply what to do.
> Remove -pipe from default list of args. Closes #8508.

- docs/markdown/Commands.md
- docs/markdown/snippets/devenv.md
- mesonbuild/backend/backends.py
- mesonbuild/modules/gnome.py
This includes and relies on https://github.com/mesonbuild/meson/pull/8547 that should be merged first.
> devenv: Set GI_TYPELIB_PATH and LD_LIBRARY_PATH

- mesonbuild/scripts/depfixer.py
Installing a file with read-only permissions is broken when installing to an arbitrary directory.
This change makes depfixer to temporarily change file permissions of the installed file to work around this.
To reproduce the issue:
meson.build:
```
project('meson_bug', 'c',
version : '0.1',
default_options : ['warning_level=3'])
exe = executable('meson_bug', 'meson_bug.c',
install : true)
touch = find_program('touch')
c = custom_target('foobar target', command : [touch, 'foobar'],
output : 'foobar', install : true, install_mode : 'r--r--r--',
install_dir : get_option('includedir'))
test('basic', exe)
```
meson_bug.c
```
#include <stdio.h>
#define PROJECT_NAME "meson_bug"
int main(int argc, char **argv) {
if(argc != 1) {
printf("%s takes no arguments.\n", argv[0]);
return 1;
}
printf("This …
```
> Fix a file permissions issues in depfixer

- mesonbuild/interpreter.py
These are all standalone commits so this should go in with a rebase.
> Replace custom program lookups with find_program

- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/interpreter.py
commit acb34faff3cb7b488ba71105901320281e69c483
backends: Remove @PRIVATE_OUTDIR_(ABS)@ substitution
It is not documented and does not seems to be used anywhere.
commit c146a14b835af4ccbed90410c0014dd39c8b0547
Remove ConfigureFile and ConfigureFileHolder
They are not used anywhere.
> Remove deadcode

- mesonbuild/compilers/cuda.py
- test cases/cuda/16 multistd/main.cu
- test cases/cuda/16 multistd/meson.build
Silenced mypy with a directive.
> Fixed version of  #8527

- docs/markdown/snippets/customimplicit.md
- mesonbuild/backend/ninjabackend.py
- run_unittests.py
- test cases/unit/94 custominc/easytogrepfor/genh.py
- test cases/unit/94 custominc/easytogrepfor/meson.build
- test cases/unit/94 custominc/helper.c
- test cases/unit/94 custominc/meson.build
- test cases/unit/94 custominc/prog.c
- test cases/unit/94 custominc/prog2.c
> Do not add custom target dir automatically when implicit false.

- mesonbuild/compilers/compilers.py
- mesonbuild/coredata.py
- mesonbuild/environment.py
- run_unittests.py
> Split environment variable and command line cflags (2)

- docs/markdown/Getting-meson_zh.md
I am learning Meson and there is not Meson Chinese manual.so I want to write a Chinese manual.
> add my frist chinese manual --Getting-meson_zh.md

- mesonbuild/backend/xcodebackend.py
> Set debug, optimization and warning flags in Xcode

- mesonbuild/backend/xcodebackend.py
> More Xcode backend fixing

- mesonbuild/backend/vs2010backend.py
Without this, VS >= 16.4 will generate
```
warning MSB8065: Custom build for item "<path>\custom_target.rule" succeeded, but specified output "<path>\outofdate.file" has not been created. This may cause incremental build to work incorrectly.
```
> VS: Disable MSBuild warnings for always-generated targets

- mesonbuild/backend/xcodebackend.py
- test cases/common/209 link custom/meson.build
- test cases/common/210 link custom_i single from multiple/meson.build
- test cases/common/211 link custom_i multiple from multiple/meson.build
- test cases/common/217 custom target input extracted objects/meson.build
Things build and run, but tests are not run. Next I'll add those and then hopefully we can enable the Xcode backend in CI.
> All Xcode common projects "pass"

- mesonbuild/msubprojects.py
- run_unittests.py
Regarding some of @xclaesse comments in previous PR
> Add subprojects purge wrap-git coverage

- mesonbuild/mdist.py
- run_unittests.py
> Fix issue where multiple dist files were not being produced for comma separated formats value

- docs/markdown/Adding-new-projects-to-wrapdb.md
> Document how to run the wrap valídator. [skip ci]

- data/syntax-highlighting/vim/ftplugin/meson.vim
- data/syntax-highlighting/vim/indent/meson.vim
- data/syntax-highlighting/vim/syntax/meson.vim
I was resyncing these with the Vim runtime files and after getting @nirbheek approval I added myself as a maintainer of the file since I'll be keeping these in sync.
Reference: https://github.com/vim/vim/pull/8177
> Vim syntax

- mesonbuild/compilers/mixins/visualstudio.py
> [VisualStudio] deactivate intrinsic functions if no optimizations are requested

- docs/markdown/Reference-manual.md
> doc: Add example how to use devenv

- docs/markdown/Running-Meson.md
Add the `second` to improve readability.
> little punctuation and add a phrase

- docs/markdown/Rust-module.md
Adds a square bracket to create a valid array.
Smallest PR ever?
> doc: Fix array syntax [skip ci]

- run_unittests.py
I had to disable the D template as the error made no sense.
> Fix macOS CI

- mesonbuild/backend/xcodebackend.py
Use a hierarchy instead of a flat list, because the latter is unusable once you have a couple of dozen build targets.
> Rework Xcode project navigation tree

- mesonbuild/mesonmain.py
Got the idea from [setuptools](https://github.com/pypa/setuptools/blob/a5131f0b82e098da6c07a03a47f36f3a52f73fb6/setuptools/msvc.py#L176)
https://github.com/mesonbuild/meson/issues/2622#issuecomment-850486068
Works locally, I have only `Visual Studio Build Tools 2019` installed.
> Find Visual Studio Build Tools 2019 also

- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreterbase.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/cmake.py
- mesonbuild/modules/dlang.py
- mesonbuild/modules/fs.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/hotdoc.py
- mesonbuild/modules/i18n.py
- mesonbuild/modules/keyval.py
- mesonbuild/modules/modtest.py
- mesonbuild/modules/pkgconfig.py
- mesonbuild/modules/python.py
- mesonbuild/modules/python3.py
- mesonbuild/modules/qt.py
- mesonbuild/modules/rpm.py
- mesonbuild/modules/sourceset.py
- mesonbuild/modules/unstable_cuda.py
- mesonbuild/modules/unstable_external_project.py
- mesonbuild/modules/unstable_icestorm.py
- mesonbuild/modules/unstable_rust.py
- mesonbuild/modules/unstable_simd.py
- mesonbuild/modules/windows.py
- Stop subclassing InterpreterObject
- Remove snippet methods
> Modules: Continue refactoring

- mesonbuild/backend/ninjabackend.py
- mesonbuild/linkers.py
Otherwise we get an exception as the method is not implemented.
Fixes #8800
> Only try to get RSP syntax if RSP is supported

- mesonbuild/interpreterbase.py
- mesonbuild/modules/fs.py
- run_unittests.py
This is the obvious compliment to #8299, a way to type check keyword arguments in a declarative manner. The approach is slightly different due to the different requirements, but it still works with a decorator,
```python
@typed_kwargs(
'name_of_function',
KwargInfo('name_of_kwarg', type, required=False, default=type()),
)
```
The principle difference with kwargs is that there are never ordered keyword arguments, additionally they are generally optional, and may have default values. With positional arguments (except variadic arguments in some cases) order matters, and they don't have default arguments (to make things simpler `typed_pos_args` inserts `None` for optional arguments when they are not provided, but this is an implementation detail meant to simplify function implementations). …
> Decorator for type checking keyword arguments

- docs/markdown/Wrapdb-projects.md
- docs/sitemap.txt
- mesonbuild/msubprojects.py
- mesonbuild/wrap/wrap.py
- mesonbuild/wrap/wraptool.py
- tools/regenerate_docs.py
> wrap: Port to v2 protocol

- mesonbuild/dependencies/cmake.py
- run_mypy.py
My goal is to fully annotate the dependencies package. To keep this easy to review I am doing multiple small PRs with one or two modules at a time.
> typing: Fully annotate dependencies.cmake

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/xcodebackend.py
- mesonbuild/build.py
- mesonbuild/cmake/executor.py
- mesonbuild/compilers/c.py
- mesonbuild/compilers/mixins/clike.py
More work is not the same as complete, but it is at least more work.
Most of it is stuff that the semi-automated #8475 didn't catch, though some things seem to just be new instances introduced since then.
> more work on f-strings

- docs/markdown/Fs-module.md
- docs/markdown/snippets/fs-module-accepts-files.md
Add a release notes snippet too!
Because #8611 did not include either one :/
/cc @fischerling
> document the enhancement to the Fs module permitting File arguments

- docs/markdown/Cython.md
- docs/markdown/snippets/first-class-cython.md
> docs: fix issues with the cython docs

- mesonbuild/environment.py
- mesonbuild/mesonmain.py
- run_mypy.py
- run_project_tests.py
- run_single_test.py
- run_tests.py
- run_unittests.py
Includes:
- full type annotation
- now runs *all* tests at once (not only all tests per section)
- optional tqdm progress bar
> Some run_project_tests.py improvements

- mesonbuild/coredata.py
- mesonbuild/mconf.py
> coredata: Invalidate deps cache when changing wrap_mode option

- docs/markdown/Quick-guide.md
See: https://developer.apple.com/xcode/
> Minor capitalization fix in Quick-guide.md

- docs/markdown/Commands.md
- docs/markdown/Gnome-module.md
- docs/markdown/snippets/gnome.md
- mesonbuild/modules/gnome.py
- add update_desktop_database to post_install()
- Set GSETTINGS_SCHEMA_DIR in devenv
> GNOME: small improvement for applications

- mesonbuild/modules/qt.py
`qt.preprocess` dispatches to the individual methods instead of
duplicating all of the logic itself, but this means that it goes through
the type checking, and feature checking a second time. To avoid this we
need to use a private helper method instead.
Fixes #8920
> modules/qt: use _impl private methods to avoid incorrect FeatureNew

- mesonbuild/interpreter/interpreterobjects.py
- run_unittests.py
- test cases/common/93 suites/meson.build
Flattening the suite value is more in-line with the rest of Meson
> Flatten suites

- docs/markdown/Dependencies.md
Some reordering to sections in dependency doc, as suggested in https://github.com/mesonbuild/meson/pull/8888#pullrequestreview-686752028, and some slight polishing while I have it open in an editor.
> Improvements to dependency doc

- mesonbuild/backend/xcodebackend.py
- mesonbuild/cmake/traceparser.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/detect.py
- mesonbuild/compilers/fortran.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/compilers/mixins/islinker.py
- mesonbuild/coredata.py
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/configtool.py
- mesonbuild/dependencies/cuda.py
- mesonbuild/dependencies/misc.py
- mesonbuild/environment.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreter/mesonmain.py
- mesonbuild/interpreterbase/interpreterbase.py
- mesonbuild/linkers/linkers.py
- mesonbuild/mcompile.py
- mesonbuild/mesonlib/universal.py
- mesonbuild/scripts/clangformat.py
- run_project_tests.py
Yet more trawling through the codebase to find `.format(` and convert it over to f-strings.
The presence of commit 15b5613db862e7f29389c34dea48a720a2027893 obviously makes perfect sense here, don't worry...
> Even more f-strings

- mesonbuild/modules/cmake.py
- test cases/failing/116 cmake executable dependency/meson.build
- test cases/failing/116 cmake executable dependency/subprojects/cmlib/CMakeLists.txt
- test cases/failing/116 cmake executable dependency/subprojects/cmlib/main.c
- test cases/failing/116 cmake executable dependency/test.json
> cmake: Improved error message for using dependency for executables

- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
This covers most of the functions that are easy to type check.
> Do some of the easy type checking of in the interpreter

- run_project_tests.py
This should not cause a slowdown in the time it takes to run the tests. If it does, do not merge.
> Remove workaround now that we have a new Ninja.

- docs/markdown/snippets/unknown-options-always-fatal.md
- mesonbuild/coredata.py
- run_unittests.py
> coredata: throw a MesonException on unknown options

- mesonbuild/msubprojects.py
> msubprojects: do not follow symlinks when purging

- docs/markdown/Dependencies.md
Let's document this, I always forget the variable.
@obilaniu @jpakkane
> doc: mention CUDA_PATH in dependency('cuda') [skip ci]

- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/misc.py
- mesonbuild/dependencies/pkgconfig.py
- test cases/frameworks/6 gettext/meson.build
- test cases/frameworks/6 gettext/meson_options.txt
- test cases/frameworks/6 gettext/test.json
> intl dep: support static kwarg

- mesonbuild/interpreter/dependencyfallbacks.py
- unittests/allplatformstests.py
> Fix --force-fallack-for with --wrap-mode=nofallback

- cross/wasm.txt
- docs/markdown/snippets/wasmlibs.md
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/emscripten.py
- test cases/wasm/3 jslib/meson.build
- test cases/wasm/3 jslib/prog.c
- test cases/wasm/3 jslib/somefuncs.js
Tested to work with and needed by https://github.com/godotengine/godot/pull/51153.
> Add support for finding Javascript source libraries with Emscripten.

- mesonbuild/interpreter/interpreter.py
- test cases/python/6 failing subproject/meson.build
- test cases/python/6 failing subproject/subprojects/bar/meson.build
- test cases/unit/72 summary/subprojects/sub2/meson.build
- test cases/unit/72 summary/subprojects/sub2/subprojects/subsub/meson.build
- unittests/allplatformstests.py
> interpreter: Fix holder_map not being updated when subproject fails

- mesonbuild/modules/i18n.py
- mesonbuild/scripts/gettext.py
Don't just create a .PHONY target which runs a script that magically generates files ninja doesn't know about. It results in untracked files, and `meson install` has to run additional commands instead of copying over files, and then cannot track them to uninstall them later.
I'm not even really sure why it was originally done via a proxy script, most likely bad legacy design. This is after all one of the oldest modules...
One side effect of this is that meson doesn't know how to rename build.CustomTarget files on install (only data files are supported?), and every file needs to be installed as "domainname.mo" so it must be named that in-tree too. To prevent clashes, every locale gets its own locale-specific subdirectory.
Once we are doing that anyway, we can output them to the actual …
> i18n: use real build/install targets for gmo files

- ci/run.ps1
See also: https://github.com/mesonbuild/meson/issues/9038#issuecomment-898960933
> ci: Use 32-bit Rust and Python on vs2017 x86

- data/syntax-highlighting/vim/syntax/meson.vim
- docs/markdown/Reference-manual.md
- docs/markdown/snippets/unset_variable.md
- mesonbuild/ast/interpreter.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreterbase/interpreterbase.py
- test cases/common/244 variable scope/meson.build
This should be useful for helping to control variable scope within
Meson. CMake has something similar for controlling scope.
> Add unset_variable()

- docs/markdown/Installing.md
- docs/markdown/Python-module.md
- docs/markdown/Reference-manual.md
- docs/markdown/snippets/install_tag.md
- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/mesonmain.py
- mesonbuild/minstall.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/hotdoc.py
- mesonbuild/modules/i18n.py
- mesonbuild/modules/pkgconfig.py
- mesonbuild/modules/python.py
- mesonbuild/modules/qt.py
- test cases/unit/98 install tag/lib.c
- test cases/unit/98 install tag/main.c
- test cases/unit/98 install tag/meson.build
- test cases/unit/98 install tag/script.py
- unittests/allplatformstests.py
> Add install tags

- docs/markdown/External-Project-module.md
- docs/markdown/snippets/waf.md
- mesonbuild/modules/unstable_external_project.py
- mesonbuild/scripts/externalproject.py
> external-project: Add support for WAF build system

- mesonbuild/backend/backends.py
- mesonbuild/backend/xcodebackend.py
- test cases/common/22 object extraction/check-obj.py
A few regressions and minor tweaks. Can now build [Godot](https://github.com/godotengine/godot/pull/51153).
We should probably consider adding some sort of a CI for the Xcode backend. Sadly it is incredibly slow and not all of the test suite works with it yet (and there does not seem to be many volunteers around to fix it).
> Again some Xcode fixes

- docs/theme/extra/templates/navbar_links.html
Regression in commit be92e3783751b8bf1481dc81635e86b70977698a via #8902
> Fix syntax error that broke the website

- docs/markdown/Syntax.md
force to change line 709 to something kind of non sensical
> Make assignment a statement in Syntax.md

- docs/markdown/i18n-module.md
- docs/markdown/snippets/i18n-return.md
- mesonbuild/modules/i18n.py
Return something useful from i18n.gettext()
Fixes #6227
> I18n return

- docs/markdown/Dependencies.md
- docs/markdown/snippets/iconv-dependency.md
- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/misc.py
Also internally needed by intl, so add that as a proxied dependency instead of coding it manually.
> new custom dependency lookup for iconv

- mesonbuild/backend/backends.py
- test cases/unit/98 install all targets/custom_files/data.txt
- test cases/unit/98 install all targets/meson.build
- unittests/allplatformstests.py
> Fix ignored install_tag kwarg in install_subdir()

- mesonbuild/interpreter/dependencyfallbacks.py
> dependency: If cached version is outdated, look on system again

- mesonbuild/coredata.py
- unittests/allplatformstests.py
- unittests/internaltests.py
> coredata: 0.59.1 -> 0.59.99 is a major version difference

- .pylintrc
- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/cmake/executor.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/d.py
- mesonbuild/environment.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/mesonmain.py
- mesonbuild/mlog.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/pkgconfig.py
- mesonbuild/modules/qt.py
- mesonbuild/modules/unstable_external_project.py
- mesonbuild/scripts/meson_exe.py
- run_mypy.py
Plus a bunch of annotation fixes. Because typing is hard.
> Add type annotations and type checking to meson main

- data/test.schema.json
- docs/markdown/Contributing.md
- mesonbuild/modules/python.py
- run_project_tests.py
- test cases/python/2 extmodule/blaster.py.in
- test cases/python/2 extmodule/ext/meson.build
- test cases/python/2 extmodule/ext/nested/meson.build
- test cases/python/2 extmodule/ext/tachyon_module.c
- test cases/python/2 extmodule/ext/wrongdir/meson.build
- test cases/python/2 extmodule/meson.build
- test cases/python/2 extmodule/test.json
Let's make sure I actually got these cherry-pick conflicts correct...
/cc @nirbheek
> 0.59 backport 9134

- mesonbuild/backend/vs2010backend.py
- mesonbuild/build.py
- test cases/common/144 link depends custom target/meson.build
- test cases/common/226 link depends indexed custom target/meson.build
- test cases/windows/10 vs module defs generated custom target/meson.build
Needs to be split in separate commits.  Might make sense to refactor get_target_deps() first.
Fixes: #1799
> backend/vs: process link dependencies.

- mesonbuild/build.py
- test cases/common/245 custom target index source/code_source.c
- test cases/common/245 custom target index source/copyfile.py
- test cases/common/245 custom target index source/copyfile2.py
- test cases/common/245 custom target index source/header_source.h
- test cases/common/245 custom target index source/main.c
- test cases/common/245 custom target index source/meson.build
> backend/vs: Generate dependencies for CustomTargetIndex for a CustomTarget

- mesonbuild/wrap/wrap.py
There are two possible issues, both of which emit very long messages from git:
- when shallow cloning via depth + a pinned commit we locally init rather than cloning; use an almost-certainly not conflicting dummy branch name
- any time a checkout of a revision is performed, it might not be a branch name, in which case it will be a detached HEAD. By default git is very noisy about this -- it wants you to know what happened and how not to mess up. But wraps aren't per default intended for user editing and development, it's just part of the internal transport which meson uses. So, temporarily squelch this advice. Do not permanently configure the repo like this though, because the user *might* cd in and start developing on the subproject; in this case, any additional git advice they trigger …
> wrap clone: be less noisy when doing automated code checkouts

- mesonbuild/minstall.py
> minstall: Skip ldconfig if not needed

- docs/markdown/Release-notes-for-0.58.0.md
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreter/mesonmain.py
Typo fixes (CustomTaget -> CustomTarget)
> Typo fixes (CustomTaget -> CustomTarget)

- mesonbuild/mcompile.py
> Remove PLATFORM env only if set

- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/vs2017backend.py
- mesonbuild/backend/vs2019backend.py
…h stdcpp version and LanguageStandard_C tag with stdc version in .vcxproj file
>  Fixes .vcxproj for vs2017 vs2019 fixes #6314

- docs/markdown/FAQ.md
This seems to come up fairly often, so having an FAQ entry seems useful.
> FAQ: Add entry about `add_project_link_arguments` and multiple languages

- docs/yaml/functions/find_program.yaml
> Fix markdown formating in find_program.yaml

- mesonbuild/modules/python.py
Using pathlib ensure propre platform specific path handling, such as
case sensitivity.
> python: Better detect when install path is not in sys.path

- mesonbuild/modules/qt.py
We currently enable this only for rcc (where this really really matters) but it can often matter for moc as well, and is just generally more correct.
Really, this should have been added in #7451 too, but I neglected it since the module warned about inaccurate dependencies only for rcc...
> qt module: add depfile support to moc as well

- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/mesonmain.py
- test cases/failing/116 run_target in test/meson.build
- test cases/failing/116 run_target in test/test.json
- test cases/failing/116 run_target in test/trivial.c
- test cases/failing/117 run_target in add_install_script/meson.build
- test cases/failing/117 run_target in add_install_script/test.json
- test cases/failing/117 run_target in add_install_script/trivial.c
Found by @dcbaker  during the review of #9400 ~~(and based on it to avoid conflicts, since it is approved already).~~
> reject run_target in test or install script arguments

- mesonbuild/minit.py
- mesonbuild/templates/mesontemplates.py
- mesonbuild/templates/samplefactory.py
- mesonbuild/templates/valatemplates.py
> Add vala template

- mesonbuild/backend/vs2010backend.py
> Fix vs backend cross compilation regression

- mesonbuild/compilers/d.py
> Use -Oz when optimization=s in ldc2

- mesonbuild/compilers/mixins/c2000.py
I missed a few more places of `-include` and `-define` in the last PR.
> Fix more code which appears copied from CcrxCompiler.

- mesonbuild/mesonmain.py
The interpreter tries to catch any exception and add the latest node information to it, but currently we only used that to print better formatted error messages on MesonException.
Since we should theoretically have that property for most/all exceptions, let's percolate that upward, and message the user that an unexpected traceback was encountered, that it should be reported as a bug, and the helpful information of "how far into parsing this meson.build did we get before erroring out, anyway?"
> report the context, if possible, on python tracebacks

- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/mtest.py
- mesonbuild/scripts/meson_exe.py
These are needed in order to make it cleaner for dataclasses to be implemented.
See #9510
> Function signature cleanup

- mesonbuild/interpreter/interpreter.py
Currently there is a try/except around the function that detects and rejects this, which instead of rejecting it, spawns a warning and continue.
This warning exists because of 'test cases/vala/9 gir/' which passes a vala generated output that isn't a return value (!!!) using string joining with the meson.current_build_dir() function (also !!!) because we officially document this (!!! for a third time) as the only way to make a vala shared library generate a typelib with a custom_command from the automatically generated gir: https://mesonbuild.com/Vala.html#gobject-introspection-and-language-bindings
In #3061 we converted strings to Files, but only if none of them were this vala hack. Due to the precise implementation, we also failed to convert strings to Files if any other error occurred, …
> custom_target: catch and reject input files that do not exist

- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/__init__.py
- test cases/failing/101 no glib-compile-resources/test.json
This used to work, make it work again.
Extend the module state to forward this option as well.
> Allow find_program implementation to run in silent mode

- docs/yaml/builtins/meson.yaml
- mesonbuild/interpreter/mesonmain.py
The current state of affairs is chaotic...
The lack of FeatureNew checks is responsible for https://github.com/jnsh/arc-theme/issues/166
> add_*_script: fix validation and do FeatureNew checks

- docs/markdown/Rust-module.md
> Fix rust module bindgen docs

- mesonbuild/backend/ninjabackend.py
> ninja backend: Fix custom_target() console: kwarg when using env

- mesonbuild/modules/gnome.py
The original attempted fix only allowed configuration to succeed, but not building. It was modeled based on the gdbus-codegen documentation, which states:
```
--annotate WHAT KEY VALUE WHAT KEY VALUE WHAT KEY VALUE
Add annotation (may be used several times)
```
which clearly indicates that gdbus-codegen accepts an --annotate flag that is followed by a multiple of 3 values, despite this not actually working.
The manpage actually contradicts the --help text:
```
--annotate ELEMENT KEY VALUE
Used to inject D-Bus annotations into the given XML files. []
```
... and gives examples that use multiple --annotate flags each with 3 arguments.
To better understand what meson is supposed to do here, we should look at ef52e60936665c982cd17a4a17c2045b445d8e6d, which ported to typed_kwargs. There is …
> gome.gdbus_codegen: fix annotations argument for multiple annotations, harder

- docs/markdown/index.md
Do you also want a link to the mailing list and Discussions on the README, near the IRC section?
> index.md:add link to GitHub Discussions section

- mesonbuild/wrap/wrap.py
- recover from bad downloads by deleting broken contents we just created
- use exponential backoff to try downloading files on error
Fixes #9688
> Wrap download recovery

- mesonbuild/modules/python.py
If the found python returns None from sysconfig.get_config_var('LIBPC') then we cannot (and don't) set PKG_CONFIG_LIBDIR from it. In fact, we can virtually guarantee we won't find a PkgConfigDependency either, because any python that doesn't have a LIBPC is presumably not installed to the system pkg-config directory (maybe it's an isolated relocatable install, maybe it just doesn't have pkg-config support for who knows what reason).
Trying to find one anyway using pkg-config's builtin search paths can unexpectedly succeed, though, by finding a completely unrelated python installation installed to a system location, which isn't the one we are actually building for.
Instead, return early so that we use the system dependency class fallback.
While we are at it, add back the debug messages …
> python module: only find a pkg-config dependency from the found python

- mesonbuild/wrap/wrap.py
I'm using submodules for my subprojects because I prefer how they work over wraps. I also like how meson will automatically checkout any submodules it finds in subprojects.
However, my subproject itself has subprojects, which are also git submodules. For these, meson's current check fails because it is essentially:  
`cd project; git submodule status project/subprojects/top_dep/subprojects/bottom_dep`  
Because the command is run in the project directory, git only checks for the submodule there instead of inside `top_dep`:  
`error: pathspec 'project/subprojects/top_dep/subprojects/bottom_dep' did not match any file(s) known to git`
Uninitialised but present submodules always get an empty directory checked out, so it's safe to just use the submodule directory for the working dir, changing …
> Checkout subproject submodules even when nested

- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/mesonmain.py
- mesonbuild/interpreter/primitives/array.py
- test cases/warning/6 list add/test.json
Incremental progress on getting all Feature warnings to tell the user where the warning came from.
> add location data to various Feature checks

- mesonbuild/modules/pkgconfig.py
This should address some concerns outlined in https://github.com/yhirose/cpp-httplib/pull/1182
> pkgconfig: set libdir only if used

- mesonbuild/interpreter/interpreterobjects.py
> add some forgotten FeatureNew annotations

- data/shell-completions/zsh/_meson
- docs/markdown/Creating-releases.md
- docs/markdown/snippets/dist-allow-dirty-flag.md
- mesonbuild/mdist.py
> implement 'dist --allow-dirty' flag

- mesonbuild/mdevenv.py
Currently it tries to run "cmd" by default in a MSYS2 bash.
Passing "bash" doesn't work since that defaults to WSL and
one has to pass an absolute path to bash instead, and even then
one misses out on the PS1 override.
In case $SHELL is set and the contained path exists prefer it even if
we are on Windows.
To make the PS1 override work we can't use Unix paths in Python since
we might be on Windows, so move the .bashrc check into the temporary
bash script itself.
This makes "meson devenv" work the same under MSYS2 as on Linux.
> devenv: support bash under MSYS2 by default

- CODEOWNERS
- ci/ciimage/arch/install.sh
- ci/ciimage/fedora/install.sh
- docs/markdown/Wayland-module.md
- docs/markdown/_Sidebar.md
- docs/markdown/snippets/wayland-module.md
- docs/sitemap.txt
- docs/theme/extra/templates/navbar_links.html
- mesonbuild/modules/__init__.py
- mesonbuild/modules/unstable_wayland.py
- run_project_tests.py
- test cases/vala/14 target glib version and gresources/test.vala
- test cases/wayland/1 client/main.c
- test cases/wayland/1 client/meson.build
- test cases/wayland/2 server/main.c
- test cases/wayland/2 server/meson.build
- test cases/wayland/3 local/main.c
- test cases/wayland/3 local/meson.build
- test cases/wayland/3 local/test.xml
This module can look for wayland xml files from the wayland-protocols package, and can generate .c and .h files using wayland-scanner.
> Add unstable_wayland module

- unittests/allplatformstests.py
The regex in question causes Python's regex parser to freeze
indefinitely in certain Python versions. That might be due
to a bug or because the re does infinite backtracking and it just
happened to work on earlier implementations.
> Replace freezing regex with plain text operations.

- docs/markdown/Commands.md
- docs/markdown/snippets/env2mfile.md
- mesonbuild/mesonmain.py
- mesonbuild/scripts/env2mfile.py
- tools/regenerate_docs.py
Attempt number two now that the regex backtracking issue has been fixed.
> Add new env2mfile command.

- mesonbuild/modules/gnome.py
In commit 68e684d51f1e469e0d9f4b499ffda15146cad98a the function signature was changed, but several places did not adapt. Additionally, we now totally dropped the in-place update of gtkdoc's sole source of dependencies, but didn't propagate them upward to assign the newly collected dependencies anywhere.
Fixes building gtkdoc with internal dependencies and failing when specified directly (when building the 'all' target with sufficiently random parallelism, deps may be built on time).
Fixes:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008382
https://gitlab.gnome.org/GNOME/libmediaart/-/issues/4
> fix regression in propagating depends in gtkdoc

- mesonbuild/mesonmain.py
> Correctly handle --version argument to runpython

- test cases/cmake/25 assembler/subprojects/cmTest/CMakeLists.txt
> Fix CMake error message

- mesonbuild/cmake/interpreter.py
- mesonbuild/cmake/traceparser.py
- test cases/failing/122 cmake subproject error/meson.build
- test cases/failing/122 cmake subproject error/subprojects/cmlib/CMakeLists.txt
- test cases/failing/122 cmake subproject error/test.json
Implementation of https://github.com/mesonbuild/meson/pull/10152#issuecomment-1086336886
> cmake: Better error message when configuring a CMake subproject fails.

- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/unstable_wayland.py
Reverts mesonbuild/meson#10041
This did not get an approving review, and it did get a disapproving review.
Immediately after I clarified that I still disapprove the PR, it was merged by the original submitter.
@jpakkane
> Revert "wayland: Also lookup scanner in pkgconfig"

- mesonbuild/modules/python.py
This check was erroneously removed in commit c5c02b72e132a03ae0284bdd5e15d1675301a37d
> python module: restore logging for broken python

- docs/markdown/Users.md
Fixed broken link and updated outdated description.
> Update Zrythm entry in Users.md

- .github/workflows/images.yml
- docs/meson.build
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/mesonmain.py
- mesonbuild/modules/qt.py
- mesonbuild/msubprojects.py
- mesonbuild/scripts/__init__.py
- mesonbuild/scripts/itstool.py
- tools/ac_converter.py
- unittests/datatests.py
Just a boatload of random fixes that don't fit into any theme, which I've been carrying locally.
> Misc fixes

- mesonbuild/mdevenv.py
> devenv: Catch FileNotFoundError

- mesonbuild/mcompile.py
> mcompile: Print suggestions when target is ambigous

- mesonbuild/dependencies/boost.py
> dependencies/boost.py: ignore unknown files instead of erroring out on them

- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/modtest.py
- mesonbuild/modules/unstable_icestorm.py
- run_mypy.py
This covers the test module and the icestorm module.
> Add a few easy module typing annotations

- mesonbuild/build.py
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/gnome.py
As requested, here are the non-pkgconfig fixes from the pkg-config typing PR (plus another small one from another branch I have), split out for easier review. Most of thse came from #10108
> Various typing fixes split out from the pkg-config typing PR

- mesonbuild/modules/i18n.py
- mesonbuild/scripts/gettext.py
- correctly check for msgfmt in merge_file() after gettext()
Fixes #10320
- allow NLS to still work with gettext-tiny, even though maintainer targets are broken
/cc @q66
> I18n error paths

- docs/genrelnotes.py
It was already written in the side menu, but better have it in the page
title too.
> Add "in development" in release notes title

- mesonbuild/ast/__init__.py
- mesonbuild/ast/introspection.py
- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/compilers/compilers.py
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/mintro.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/cmake.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/i18n.py
- mesonbuild/modules/qt.py
- mesonbuild/rewriter.py
This is a bit all over the place, I basically took all of the patches that weren't specifically tied to the build cleanup and am offering them as a separate PR. The goal here is to not end up with a 50 patch series that needs review when that series is ready.
> Various fixes from my build target typing series

- mesonbuild/ast/introspection.py
- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/coredata.py
- mesonbuild/dependencies/dub.py
- mesonbuild/interpreter/primitives/string.py
- mesonbuild/linkers/detect.py
- mesonbuild/mdevenv.py
- mesonbuild/mesonlib/universal.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/python.py
- mesonbuild/scripts/env2mfile.py
- mesonbuild/wrap/wraptool.py
> flake8: various fixes

- docs/markdown/D.md
- docs/yaml/functions/_build_target_base.yaml
- docs/yaml/functions/declare_dependency.yaml
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/modules/windows.py
- test cases/d/13 declare dep/meson.build
- test cases/failing/46 pkgconfig variables zero length/test.json
- test cases/failing/47 pkgconfig variables zero length value/test.json
- test cases/failing/48 pkgconfig variables not key value/test.json
Plus misc preparatory cleanup.
>  migrate declare_dependency to typed_kwargs 

- mesonbuild/modules/unstable_cuda.py
Agrees with Release Notes, Section 1.1, Table 3.
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
> Update CUDA Toolkit/driver version table for recent releases

- mesonbuild/environment.py
15 is the current snapshot version, 13 and 14 are released.
> dependencies: update llvm versions

- docs/markdown/Users.md
according to [commit 8a3d169](https://github.com/wxFormBuilder/wxFormBuilder/commit/8a3d1697c819b8a8b41a136a865439b205997ae1)
> Users.md: remove wxFormBuilder

- mesonbuild/build.py
> cuda: don't inject `-lstdc++` when linking

- docs/markdown/snippets/install_sources_preserve_path_arg.md
- docs/yaml/functions/install_data.yaml
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/modules/python.py
- test cases/common/252 install data structured/meson.build
- test cases/common/252 install data structured/pysrc/__init__.py
- test cases/common/252 install data structured/pysrc/bad.py
- test cases/common/252 install data structured/pysrc/bar.py
- test cases/common/252 install data structured/pysrc/foo.py
- test cases/common/252 install data structured/pysrc/meson.build
- test cases/common/252 install data structured/pysrc/submod/__init__.py
- test cases/common/252 install data structured/pysrc/submod/bad.py
- test cases/common/252 install data structured/pysrc/submod/baz.py
- test cases/common/252 install data structured/test.json
- test cases/python/7 install path/meson.build
- test cases/python/7 install path/structured/meson.build
- test cases/python/7 install path/test.json
Based on the new feature in install_headers.
> python module: implement the new preserve_path kwarg for install_sources too

- mesonbuild/mesonmain.py
Hello,
#10567 In this patch, we handle OSError in the topmost level and give a general error message. We could use some guiding if you want a more contextualized message
Regards,
Shay & Omer
> handle OSError exception in run function

- mesonbuild/mesonlib/universal.py
Fixes #10614
Popen object must be created with with `stdin=PIPE` so `Popen.communicate(write)` can send data to the process’s stdin.
> fix Popen_safe write

- mesonbuild/mesonlib/vsenv.py
Sometime people have garbage in their environment and it make meson crash when setting visual studio environment.
With this patch garbage in => garbage out
> Handle garbage in environment more gracefully when setting vsenv

- mesonbuild/mtest.py
- test cases/common/253 long output/dumper.c
- test cases/common/253 long output/meson.build
- unittests/allplatformstests.py
This is a cherry-picked commit from #9930. Fixes #10563 and #10577.
> fix mtest regression

- mesonbuild/dependencies/qt.py
> qt: fix qt tools detection for Qt6.3+ by pkg-config

- mesonbuild/mcompile.py
This command is magical and I hate it. Mostly because it seems people have no clue what it does, and what it doesn't do.
Provide informational messages to the user indicating how it works, e.g. for debugging. Point out if we ran vsenv before shelling out to the backend.
> mcompile: provide user visibility into what actually happens

- mesonbuild/interpreter/interpreter.py
> make add_project_dependencies respect build version of include dirs

- mesonbuild/build.py
- test cases/common/215 source set realistic example/meson.build
- test cases/common/44 pkgconfig-gen/dependencies/dummy.c
- test cases/common/44 pkgconfig-gen/dependencies/meson.build
- test cases/common/44 pkgconfig-gen/meson.build
- test cases/frameworks/28 gir link order 2/samelibname/meson.build
- test cases/unit/52 pkgconfig static link order/meson.build
`bool(self.method)` is always true, even when `bool(self.attribute_used_by_method)` is false... Sigh
> build.py: properly warn when there are no sources

- mesonbuild/ast/printer.py
> Fixed string escaping in AstPrinter

- mesonbuild/mdevenv.py
> devenv: Resolve executable in devenv's PATH

- .mailmap
- data/shell-completions/bash/meson
the current bash completion script will display an error when completing undefined commands.
fix that and rework the top-level a little to reuse function lists.
> bash completion fixes

- mesonbuild/backend/vs2010backend.py
Include paths to different drives as absolute paths
fixes #8329
> Fix including headers from another drive on VS backend

- mesonbuild/backend/vs2010backend.py
This PR adds Visual Studio backend support for cross-compiling to platforms included in the [Microsoft Game Development Kit](https://github.com/microsoft/GDK).
There are 3 flavors of GDK targets (one for PC, one for Xbox Series X|S, and one for Xbox One), but the platforms all share a common naming scheme: `Gaming.<Target>.x64`. We can catch all of these by checking for a target system whose name begins with "Gaming" and setting the platform name accordingly.
An example cross file for the Windows GDK platform would look like:
```
[target_machine]
system = 'Gaming.Desktop.x64'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
```
> Add cross-compile support for Microsoft GDK platforms

- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/primitives/__init__.py
- mesonbuild/interpreter/primitives/string.py
- mesonbuild/mintro.py
- mesonbuild/modules/python.py
- unittests/allplatformstests.py
Cherry-picks:
- e19e9ce6f196f7c127a2668b5df0ada1d50806df
- 3e73d4d77d1d36b15d06c8b3c4a7ee6ad77847b6 with conflicts fixed
> Backport 10652

- .pylintrc
- mesonbuild/arglist.py
- mesonbuild/ast/interpreter.py
- mesonbuild/ast/printer.py
- mesonbuild/backend/backends.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/build.py
- mesonbuild/cmake/common.py
- mesonbuild/cmake/generator.py
- mesonbuild/cmake/interpreter.py
- mesonbuild/cmake/traceparser.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/dependencies/boost.py
- mesonbuild/dependencies/cmake.py
- mesonbuild/modules/cmake.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/hotdoc.py
- mesonbuild/modules/pkgconfig.py
- mesonbuild/modules/rust.py
- mesonbuild/scripts/env2mfile.py
#10767 is a large PR, we're trying to merge it piecemeal. I didn't look at everything, but there's a few commits I've double checked, so let's merge
> Some commits from #10767 that I reviewed

- run_meson_command_tests.py
It was needed on older Debians.
It breaks new Debian.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020567
> Remove installation scheme tweaking hack.

- mesonbuild/dependencies/qt.py
- this fixes #10792
- Qt6EntryPoint(d) replaces qtmain(d) from Qt 4 & 5
- uses the same mechanism: `main: true`
- uses a special mixin class for pkg-config and config-tool dependency calculation
> Add handling Qt6's EntryPoint library.

- mesonbuild/backend/backends.py
First, check if the env program exists. If it does, it is faster than doing it via a python script `basically-env.py` that maybe imports all of mesonbuild.* as a side effect of project structure.
We do not, however, use env for setting up PATH additions, since env can override an environment variable but not extend it. So in that case we still need to wrap the command via python.
By default, all run_targets (at least) are wrapped and now wrap via the `env` program as they export e.g. `MESONINTROSPECT='/usr/bin/meson introspect'`
/cc @xclaesse
> run wrapped-due-to-env commands on unix via the env program

- docs/markdown/snippets/jni_system_dependency_bsd_support.md
- mesonbuild/dependencies/dev.py
> Add BSD support to the JNISystemDependency

- mesonbuild/modules/hotdoc.py
Trivially correct, discussion here: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/2972#note_1586355
> hotdoc: Fix typo in argument

- mesonbuild/compilers/java.py
- mesonbuild/compilers/mixins/islinker.py
* Add missing functions
* Use f-strings
* Fix mismatched parameter names
> Fixup JavaCompiler a bit

- test cases/common/13 pch/linkwhole/lib1.c
- test cases/common/13 pch/linkwhole/lib2.c
- test cases/common/13 pch/linkwhole/main.c
- test cases/common/13 pch/linkwhole/meson.build
- test cases/common/13 pch/linkwhole/pch1/pch_one.h
- test cases/common/13 pch/linkwhole/pch2/pch_two.h
- test cases/common/13 pch/meson.build
Does not contain a fix, but at least has the required test.
> Add regression test for pch link_whole bug.

- mesonbuild/compilers/asm.py
> nasm: Fix get_optimization_args()

- mesonbuild/backend/vs2010backend.py
Use OptionOverrideProxy instead of pure options.
Closes #10393
> Fix options overrides for vsbackend

- mesonbuild/scripts/env2mfile.py
Does not contain the second half of the CMake patch because it was not immediately obvious how to put that in.
> Fixes for Debian crossgen

- mesonbuild/modules/qt.py
This fixes #11038.
Raise an error, if the file element in a resource file has no text.
Includes minor cleanups in the vicinity.
> fix Qt compile_resources on empty <file> element

- mesonbuild/build.py
- mesonbuild/utils/universal.py
We have divergent implementations of loading a pickled *.dat file. The Build class loader has a better error message, and also checks if the file exists. But the generic loader handles TypeError and ModuleNotFoundError. Merge the implementations, and use it for Build as well.
Fixes #11051
> build: use the unified pickle loader to handle more edge cases

- mesonbuild/modules/hotdoc.py
We need to run it as an external command at build time anyway, and we detect it by looking it up as an ExternalProgram. It seems odd to then import it into Meson's python interpreter and run the main function.
Moreover, this errors out when you are running two different pythons, one for Meson and one for hotdoc. For example, when hotdoc is installed normally, but you're testing Meson against a nondefault newer version of python.
> hotdoc module: run hotdoc as an external command during configure

- run_project_tests.py
It was impossible to specify null arguments in the exclude array,
while they were passed properly in the code, they were stringified
while the entries in the options array were just completely removed.
To fix this, do not early stringify the argument name and option
together as that would make it impossible to properly match it to
None without introducing a new special case for the string "None".
So instead they are now kept as tuples and only stringified when
its actually needed.
> test runner: fix excluding null options

- docs/markdown/Code-formatting.md
- docs/markdown/Release-notes-for-0.52.0.md
- docs/markdown/Release-notes-for-0.58.0.md
- docs/markdown/Vs-External.md
- docs/refman/jsonschema.py
- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/environment.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/linkers/detect.py
- mesonbuild/linkers/linkers.py
- test cases/common/62 string arithmetic/meson.build
- test cases/failing/40 custom target plainname many inputs/test.json
- test cases/unit/102 python without pkgconfig/meson.build
> Fix various spelling errors

- mesonbuild/backend/backends.py
When a test executable references a local shared library, make sure that we apply the appropriate $LD_LIBRARY_PATH so that the linker can find it at runtime.
The DT_RUNPATH entry does ensure that the binary references the path to the shared library build, however the RUNPATH list is only searched after $LD_LIBRARY_PATH. So if the user has a shared library of the same name in their $LD_LIBRARY_PATH, this will be the version found and used for running the test. This is bad if you're trying to use Meson to test a shared library you're developing and have installed in a local prefix which is under $LD_LIBRARY_PATH.
Fixes #1635
> tests: Write out LD_LIBRARY_PATH for built shared libraries

- mesonbuild/build.py
- mesonbuild/dependencies/mpi.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/fs.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/i18n.py
- mesonbuild/mparser.py
- mesonbuild/utils/universal.py
- test cases/common/14 configure file/meson.build
- test cases/common/14 configure file/test.json
> Fix broken fs.copyfile install dir

- docs/markdown/Contributing.md
- docs/markdown/Qt6-module.md
- docs/markdown/snippets/devenv.md
- docs/markdown/snippets/rust_bindgen_str_include.md
- mesonbuild/modules/sourceset.py
This PR fixes 3 typos found. It also converts 2 links from http to https.
> Fixing typos

- mesonbuild/dependencies/dev.py
- run_project_tests.py
- test cases/java/9 jni/meson.build
First commit is a cleanup commit.
Second commit will fix https://github.com/mesonbuild/meson/issues/11173.
> JNISystemDependency fixes

- mesonbuild/compilers/mixins/clike.py
Profiling showed that we were spending 25s inside `os.path.realpath()` on Windows while generating compile lines for build.ninja, inside `NinjaBackend.generate()`
The real path for these will not (should not) change during a single meson invocation, so cache all these.
Brings build.ninja generation from 73s to 47s on my machine for the gstreamer monorepo.
In general, `NinjaBackend.generate()` seems to spend a lot of time in simple list add operations on `CLikeCompilerArgs`, so we should do something to optimize that.
The other slowdown is in evaluating things. I tried optimizing something there, but I was totally off-base and it made no difference. The interpreter probably just needs to create fewer objects or something.
I did benchmarking with `pyinstrument`.
> meson: Cache os.path.realpath in CLikeCompilerArgs

- mesonbuild/mesonmain.py
- mesonbuild/msubprojects.py
- mesonbuild/mtest.py
> handling DeprecationWarning etc. in mesonbuild.*

- mesonbuild/compilers/asm.py
- test cases/nasm/2 asm language/meson.build
> Fix nasm language when target has threads as added dependency

- docs/markdown/_include_qt_base.md
"extra_arguments" should be "extra_args"
> fix(docs): Qt compile_moc() parameter error

- mesonbuild/minit.py
> meson init --build should call meson setup and meson compile

- mesonbuild/compilers/cuda.py
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-compilers
> cuda: enable C++20 for CUDA 12

- docs/markdown/Reference-tables.md
- mesonbuild/compilers/c_function_attributes.py
- test cases/common/197 function attributes/meson.build
Remembered that this was missing, so I thought I'd add it real quick.
> add cc.has_function_attribute('vector_size')

- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/mtest.py
- unittests/internaltests.py
And a few other bugs I noticed
> Fix visual studio /utf-8 removal

- docs/yaml/functions/project.yaml
> docs: Add cython to the languages accepted by project()

- mesonbuild/cmake/executor.py
If an re call fails to find a match it returns None. We're not checking that, and crashing.
Fixes: #11376
> cmake: check that `re.search` returned a non-None value

- docs/markdown/snippets/preprocess.md
- docs/yaml/objects/compiler.yaml
- mesonbuild/build.py
- mesonbuild/interpreter/compiler.py
- test cases/common/259 preprocess/bar.c
- test cases/common/259 preprocess/meson.build
It was documented to be supported but only File and str were actually working.
> preprocess: Allow custom_tgt, custom_idx and generated_list

- mesonbuild/compilers/compilers.py
Code moved to detect.py in recent version
> Misleading comment

- docs/markdown/Syntax.md
- mesonbuild/interpreterbase/interpreterbase.py
For instance, when writing `-subdir('a')` or `not subdir('a')`.
Fixes #11225.
> Fix unhandled exception for operations on None value

- docs/markdown/Unity-builds.md
> Improve unity build documentation

- mesonbuild/msetup.py
This can happen from typos, which then confusingly claim that neither build directory has a meson.build file because the implicit . directory was not actually one of the directories. Instead a random command line argument was interpreted as a directory name.
Fixes #11472
> msetup: clarify error message when wrong directories are specified

- mesonbuild/scripts/env2mfile.py
Do not merge yet. This needs some coordination with Debian.
> Env2mfile changes needed for Debian packaging

- docs/markdown/Builtin-options.md
> doc: Be more specific about warning_level option

- mesonbuild/ast/introspection.py
- mesonbuild/build.py
- mesonbuild/rewriter.py
- fix warning about empty sources
- activate vsenv
- add missing command aliases
- fix indentation of kwargs
> Various fixes for rewriter

- docs/markdown/Commands.md
- mesonbuild/mcompile.py
this fixes a bug introduced by #11528
> fix meson compile with alias target

- mesonbuild/modules/cuda.py
> CUDA: make "Ampere" equivalent to SM8.0 + SM8.6

- mesonbuild/backend/ninjabackend.py
> Added restat = 1 to the fortran_COMPILER rule

- mesonbuild/scripts/run_tool.py
Previously, it would raise an exception.
> Fix run_tool() when git is not installed

- mesonbuild/compilers/cpp.py
Possibly also suitable for 1.1.1?
> Add c++23 to the list of C++ standards.

- docs/markdown/Users.md
[GIMP uses meson](https://developer.gimp.org/core/setup/build/)
Note: I'm not from the GIMP project.
> Update Users.md [skip ci]

- .github/workflows/cygwin.yml
- .github/workflows/macos.yml
- .github/workflows/msys2.yml
- .github/workflows/nonnative.yml
- .github/workflows/os_comp.yml
- .github/workflows/unusedargs_missingreturn.yml
- ci/ciimage/common.sh
- ci/combine_cov.sh
The pypi package was suddenly removed. Not the most confidence-inspiring deprecation/migration:
https://about.codecov.io/blog/message-regarding-the-pypi-package/
> ci: Move to the codecov github action

- mesonbuild/compilers/asm.py
> yasm: Fix usage of incompatible optimization flags

- mesonbuild/cmake/common.py
- mesonbuild/modules/cmake.py
- typed_pos_args
- mypy annotations
Not fully done, I just typed up all functions that didn't have them already, and reduced the number of issues by 2/3. There are still incompatibilities I haven't touched. Baby steps. :D
> Cmake module typing

- mesonbuild/dependencies/python.py
> Fix native build on Windows Arm64

- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- unittests/allplatformstests.py
> summary: Add from which subproject each subproject have been called

- mesonbuild/modules/pkgconfig.py
- test cases/common/44 pkgconfig-gen/dependencies/meson.build
- test cases/common/44 pkgconfig-gen/dependencies/test2.c
- test cases/common/44 pkgconfig-gen/inc1/inc1.h
- test cases/common/44 pkgconfig-gen/inc2/inc2.h
- test cases/common/44 pkgconfig-gen/meson.build
- test cases/common/44 pkgconfig-gen/test.json
> pkgconfig: Add include directories from internal deps in -unintalled.pc

- docs/markdown/Builtin-options.md
vc++20 support was added in 012ec7d5b3379b035f1dd1369d74cafd26ff6ab0
> docs: List vc++20 for cpp_std

- ci/run.ps1
- mesonbuild/dependencies/configtool.py
- test cases/frameworks/15 llvm/meson.build
- unittests/pythontests.py
See:
- llvm
#11642
- python2
https://github.com/mesonbuild/meson/pull/11733#issuecomment-1572909430
https://github.com/mesonbuild/meson/pull/11049#issuecomment-1577668311
> CI fixups: python2 in azure, llvm 16 cmake dependency

- mesonbuild/backend/ninjabackend.py
Specifically, when those files can be created by a build rule with one version of meson.build, and created as e.g. a shared_library alias symlink in another version of meson.build, the cleandead command will delete important files just because they don't happen to be created by ninja itself.
Work around this by making a dummy rule that exists solely to insert the files into the build graph to trick ninja into not deleting them.
Closes #11861
> ninja backend: fix cleandead deleting files that meson implicitly creates

- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/xcodebackend.py
Try to improve backends/*.py a bit by slapping on some type annotations where they seem obvious.
> Low effort typing

- mesonbuild/coredata.py
- mesonbuild/mconf.py
- mesonbuild/mdist.py
- run_mypy.py
- mdist.py -- and refactor it for legibility.
- mconf.py
misc updates to coredata.py, just enough to satisfy mconf.
> fully type a few more files

- setup.cfg
> Setuptools metadata tweaks

- docs/markdown/Disabler.md
As you can see, this isn't a very comprehensive pull request. Only a single character is changed. Just fixing some typos.
> Fix typo in Disabler.md

- mesonbuild/compilers/cpp.py
Instead of hardcoding any values, hardcode what we think the most likely implementation is, and check that first. It was pointed out that while for example, Apple only provides libc++ and supports that for xcode, a user could install a custom environment (such as homebrew) which uses it's own copy of libstdc++, and we need to account for that. This means that a library search will be done, but only once and the result will be cached, on all systems.
> compilers/cpp: check libc++ vs libstdc++ harder

- mesonbuild/compilers/detect.py
Cython historically, when asked to print the version and exit successfully, would do so on stderr, which is weird and inconsistent. Recently, it fixed this UX bug by printing on stdout instead:
https://github.com/cython/cython/issues/5504
This then broke meson detection because we assumed it was on stderr due to historically being there:
https://github.com/scipy/scipy/issues/18865
Cython is right, and shouldn't have to revert this reasonable change for backwards compatibility. Instead, check both.
> compilers: detect cython version on stdout for newer cython versions

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/asm.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/fortran.py
- mesonbuild/compilers/mixins/ccrx.py
- mesonbuild/compilers/mixins/clang.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/mixins/compcert.py
- mesonbuild/compilers/mixins/elbrus.py
- mesonbuild/compilers/mixins/emscripten.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/compilers/mixins/intel.py
- mesonbuild/compilers/mixins/islinker.py
- mesonbuild/compilers/mixins/metrowerks.py
- mesonbuild/compilers/mixins/ti.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/compilers/vala.py
- mesonbuild/coredata.py
- mesonbuild/environment.py
- mesonbuild/linkers/linkers.py
- mesonbuild/utils/universal.py
Some of them fix actual bugs or TODOs. Others make pyright/pylance a lot happier.
> Some various type related cleanups

- ci/ciimage/build.py
- ci/ciimage/opensuse/install.sh
- cross/linux-mingw-w64-64bit.txt
- mesonbuild/mtest.py
- test cases/frameworks/27 gpgme/test.json
- test cases/frameworks/5 protocol buffers/meson.build
This is enough to build ubuntu-rolling, but there are still protobuf/llvm issues preventing some other images from building.
> CI updates to successfully rebuild images

- mesonbuild/backend/ninjabackend.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/mintro.py
- mesonbuild/msetup.py
Minus a couple hundred mypy errors in ninjabackend.py
> misc typing mainly for ninjabackend

- mesonbuild/backend/backends.py
On my project, this function was a bottleneck in setup time.
By properly caching it, the cumtime for this function went from 26s to 4.3s when I profiled it.
> Optimize extract_dll_paths in ninja backend

- docs/markdown/snippets/string_format.md
- docs/yaml/elementary/str.yml
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/primitives/string.py
- mesonbuild/interpreterbase/__init__.py
- mesonbuild/interpreterbase/helpers.py
- mesonbuild/interpreterbase/interpreterbase.py
- test cases/common/264 format string/meson.build
- test cases/common/264 format string/meson_options.txt
- test cases/common/264 format string/test.json
Share a common function to convert objects to display strings for consistency.
While at it, also add support for formatting user options.
> Unify message(), format() and fstring formatting

- mesonbuild/interpreter/interpreter.py
- unittests/allplatformstests.py
str() is going to return titlecased "True" which is not how meson works. This is misleading, so use the meson-specific format instead.
> convert booleans in summary function to correct representation

- mesonbuild/dependencies/hdf5.py
- mesonbuild/dependencies/pkgconfig.py
- mesonbuild/dependencies/scalapack.py
- mesonbuild/modules/external_project.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/pkgconfig.py
- mesonbuild/utils/universal.py
- run_tests.py
- unittests/internaltests.py
- unittests/linuxliketests.py
This makes the code cleaner and will allow to have other implementations in the future.
> PkgConfigDependency: Move CLI handling into its own abstraction

- docs/markdown/snippets/compile_werror.md
- docs/yaml/objects/compiler.yaml
- mesonbuild/interpreter/compiler.py
- test cases/common/28 try compile/meson.build
> Compiler: Add werror kwarg to compiles(), links() and run() methods

- mesonbuild/coredata.py
> machine file: Fix crash on empty value 

- mesonbuild/utils/universal.py
- unittests/allplatformstests.py
fixes #11006
tested against https://github.com/Jan200101/cmakedefine-test
some test cases might be missing in this, if anything comes to mind please mention it.
> correct cmakedefine behavior

- mesonbuild/compilers/mixins/clike.py
Simplify and optimize the function. When not on Mac OS, it was iterating two times the list when there were no files in it.
> Optimize CLikeCompiler._get_file_from_list()

- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/modules/hotdoc.py
- mesonbuild/modules/python.py
In the process, discover and fix some monkeypatch crimes committed on held object classes by using better generics.
> Add more typing to hotdoc module

- docs/yaml/objects/feature.yaml
These are much easier to understand at a glance than free-form text.
> docs: Add more feature truth tables

- docs/markdown/snippets/custom_target_description.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/modules/external_project.py
- mesonbuild/modules/fs.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/i18n.py
- mesonbuild/modules/qt.py
- mesonbuild/modules/rust.py
- mesonbuild/modules/windows.py
Allow modules using CustomTarget to modify the command description used by ninja backend. This result in more precise logs when building a project.
> Add more descriptive description to CustomTarget

- docs/markdown/Fs-module.md
- docs/markdown/snippets/fs_relative_to.md
- mesonbuild/modules/fs.py
- test cases/common/220 fs module/meson.build
- test cases/common/220 fs module/subdir/btgt.c
- test cases/common/220 fs module/subdir/meson.build
This reverts commit https://github.com/tristan957/meson/commit/84c8905d527893bedc673e8a036b8b2ec89368b4.
Fixed the cygwin failure...
Because waiting for the original version of this PR or including it in the original revert PR was not good enough :|
> Revert "Revert "Add fs.relative_to()""

- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/__init__.py
- test cases/common/182 find override/meson.build
- test cases/common/182 find override/prog-version.py
- test cases/common/182 find override/subprojects/sub2.wrap
- test cases/common/182 find override/subprojects/sub2/meson.build
- test cases/common/182 find override/subprojects/sub2/prog-version.py
> find_program: Fallback if version mismatch

- docs/markdown/Syntax.md
> Document that dicts can be indexed with []

- docs/markdown/Users.md
> Add trilo xtest to users [SKIP_CI]

- mesonbuild/modules/qt.py
- test cases/frameworks/4 qt/manualinclude.cpp
- test cases/frameworks/4 qt/meson.build
- test cases/frameworks/4 qt/mocdep/meson.build
- test cases/frameworks/4 qt/mocdep/mocdep.h
> qt module: add include_directories to moc compile

- mesonbuild/modules/gnome.py
It was not always using the pkg-config file.
> gnome: Fix glib tool lookup consistency

- docs/markdown/Reference-tables.md
- mesonbuild/environment.py
- mesonbuild/scripts/env2mfile.py
> machine file: Document how to specify compiler paths with spaces

- mesonbuild/compilers/asm.py
- mesonbuild/compilers/mixins/metrowerks.py
Accidentally deleted my old PR's branch (#12241)
I was asked to split the changes into multiple commits, and had to fix some linting errors as well.
> Metrowerks improvements

- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/modules/rust.py
This adds some additional annotations, uses typed_kwargs for rust_dependency_map and then does some cleanups for other rust arguments.
> rust argument type checkingt cleanups

- docs/markdown/Users.md
Adding yet another fossil to the list.. more accurately a trilobite library.
> Adding Trilobite Core to Users.md

- mesonbuild/modules/simd.py
- run_mypy.py
- Add typing
- Port to typed_pos_args/typed_kwargs
- Clean up code
- Add to mypy
> Cleanup the SIMD module

- mesonbuild/msubprojects.py
> msubprojects: Fix crash if wrapdb_version is in bad format

- mesonbuild/_pathlib.py
- mesonbuild/compilers/asm.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/scripts/test_loaded_modules.py
- mesonbuild/scripts/yasm.py
- mesonbuild/utils/universal.py
- add missing imports for future annotations
- fix ninja backend rules containing internal enum reprs
- fix the repr for OrderedSet to actually execute correctly
> misc cleanups

- docs/markdown/Users.md
Adding another library to the user list after testing it out
> Adding Trilobite Data to Users.md [SKIP_CI]

- docs/markdown/Users.md
Adding yet another entry into that list from the Trilobite Project
> Update Users.md [SKIP_CI]

- mesonbuild/interpreter/type_checking.py
Here's a couple of small changes that shouldn't be to controversial
> Type checking for build target fixes

- docs/markdown/Quick-guide.md
Change the shell prompt to '#' to when installing as root.
> docs: Update Quick-guide.md

- mesonbuild/mlog.py
> mlog: Catch OSError when closing pager

- mesonbuild/backend/nonebackend.py
- mesonbuild/backend/xcodebackend.py
- mesonbuild/coredata.py
- run_mypy.py
Mostly backend related. Ensure nonebackend is checked in mypy, reduce number of mypy errors for xcode by about 2/3.
> misc typing fixes

- mesonbuild/backend/ninjabackend.py
- test cases/swift/8 extra args/main.swift
- test cases/swift/8 extra args/meson.build
> Swift: Support `swift_args`

- mesonbuild/backend/vs2010backend.py
This change fixes two usability issues with the genvslite project generation. Unlike when using the full VS backend, under genvslite the `ProjectName` property wasn't being set for generated projects. This means projects end up being named according to the project files, which includes suffixes like "@exe" in the solution, which is undesirable. This change adds the `ProjectName` field in for genvslite projects, to keep the naming consistent with projects under the VS backend.
Additionally, previously under genvslite, no projects were set to build under any solution configuration by default. This is inconvenient, as the user has to manually edit the build settings for each solution configuration before they can compile at the solution level. There was a note in the code to do something …
> Improve project naming and build configuration in genvslite projects

- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/fs.py
- mesonbuild/modules/sourceset.py
- unittests/datatests.py
- unittests/internaltests.py
I was looking through old branches and found a few cleanups that still apply and figured they were worth sending out regardless of the branch they're on.
> A few unrelated cleanups from various branches

- .gitattributes
- data/shell-completions/bash/meson
This adds bash completion to everything that I could think of except for the rewriter.
> Continue fleshing out bash completion script

- .github/workflows/images.yml
- .github/workflows/os_comp.yml
- ci/ciimage/build.py
- ci/ciimage/fedora/install.sh
- ci/ciimage/gentoo/image.json
- ci/ciimage/gentoo/install.sh
- test cases/frameworks/15 llvm/test.json
- test cases/frameworks/25 hdf5/test.json
- test cases/frameworks/5 protocol buffers/meson.build
We may want to consider our own binpkg cache for future to speed things up, in addition to the ones provided by Gentoo's own binhost.
> ci: add Gentoo

- mesonbuild/mtest.py
Oops.
Fixes: 7b7d2e060b447de9c2642848847370a58711ac1c
> Fix comment typo

- mesonbuild/compilers/compilers.py
- mesonbuild/dependencies/cmake.py
- mesonbuild/dependencies/dev.py
- mesonbuild/dependencies/pkgconfig.py
- mesonbuild/dependencies/python.py
- mesonbuild/dependencies/qt.py
- mesonbuild/mesonmain.py
- mesonbuild/modules/dlang.py
- mesonbuild/mparser.py
- mesonbuild/rewriter.py
- mesonbuild/utils/universal.py
- mesonbuild/wrap/wrap.py
Mostly, I was poking around at various things that are None-unsafe (i.e. contain an implicit Optional, typically sentinel values).
> various typing-related fixes

- mesonbuild/modules/cuda.py
- run_mypy.py
> type annotations and typechecking for CUDA module

- mesonbuild/coredata.py
> Fix base options not reconfigurable

- docs/markdown/snippets/test_using_custom_target_executable.md
- docs/yaml/functions/benchmark.yaml
- mesonbuild/backend/backends.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/mtest.py
- test cases/common/273 customtarget exe for test/generate.py
- test cases/common/273 customtarget exe for test/meson.build
> Allow using CustomTarget as test executable

- docs/yaml/objects/external_program.yaml
>  docs: clarify environment variables take only ExternalProgram.full_path()

- mesonbuild/compilers/cuda.py
> cuda: respect host compiler `-Werror`

- mesonbuild/compilers/cpp.py
The previous approach wasn't great because you couldn't control what the detected C++ stdlib impl was. We just had a preference list we tweaked the searched order for per OS. That doesn't work great for e.g. Gentoo with libc++ or Gentoo Prefix on macOS where we might be using libstdc++ even though the host is libc++.
Jonathan Wakely, the libstdc++ maintainer, gave a helpful answer on how to best detect libc++ vs libstdc++ via macros on SO [0]. Implement it.
TL;DR: Use <version> from C++20 if we can, use <ciso646> otherwise. Check for _LIBCPP_VERSION as libstdc++ doesn't always define a macro.
[0] https://stackoverflow.com/a/31658120
> compilers: cpp: improve libc++ vs libstdc++ detection (again)

- docs/markdown/snippets/wayland_stable_prot_version.md
- mesonbuild/modules/wayland.py
> wayland: Stable protocols can have a version

- docs/markdown/snippets/compiler_run.md
- mesonbuild/backend/backends.py
- mesonbuild/compilers/c.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/detect.py
- mesonbuild/compilers/fortran.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/objc.py
- mesonbuild/compilers/objcpp.py
- mesonbuild/compilers/rust.py
- mesonbuild/environment.py
- mesonbuild/interpreter/compiler.py
- test cases/rust/1 basic/meson.build
Those are commits extracted from one of my Rust WIP branches because they can be merged separately.
> compilers: Every compiler can run code

- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/rust.py
This doesn't address all of the concerns in https://github.com/mesonbuild/meson/issues/12962, but most of them.
> compilers: cpp: assertion fixes

- docs/markdown/Users.md
Adding more libraries from my list
> Update Users.md to include more libraries

- mesonbuild/cmake/interpreter.py
`CMAKE` has a notion of build types too and the [standard build types](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) are a reasonable match to a subset of the `meson` build types. If the `meson` build type is set to a type that has a `CMAKE` equivalent and no `CMAKE` build type is set, we can propagate the requested build type.
> cmake: best-effort build type propagation

- mesonbuild/modules/gnome.py
No need to spam about reading the input file.
Fixes: #13119
> Pass --quiet to glib-genmarshal

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/nonebackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/xcodebackend.py
Rather than getting endlessly bogged down trying to fix every single issue all at once (and then realizing that the build module also needs annotations), here the `NinjaRule` class annotated, with some bug fixes
> Additional annotations and cleanups for the Ninja backend

- mesonbuild/compilers/detect.py
If nasm is not defined in cross file binaries we can fallback to build machine nasm.
> nasm: Fallback to native compiler when cross compiling

- docs/markdown/Users.md
NumPy is built with Meson since version 1.26.
> Added NumPy to users

- docs/markdown/Continuous-Integration.md
Enhanced CI Documentation: Updated configuration examples for clarity and readability, ensuring seamless integration with GitHub Actions, AppVeyor, and CircleCI CI. Improved organization and formatting for easier navigation and understanding. PR includes refinements for both Linux and macOS environments, enhancing developer workflow efficiency.
CircleCI experiment based on this: https://github.com/fossil-lib/fscl-xtest-c/blob/main/.circleci/config.yml
AppVeyor experiment based on this: https://github.com/fossil-lib/fscl-xtest-c/blob/main/appveyor.yml
> Updating Continuous-Integration.md

- docs/markdown/Users.md
Updating this to save space for any other users to list their projects.
> unify listing for FSCL

- ci/ciimage/build.py
- ci/ciimage/cuda/install.sh
- ci/ciimage/gentoo/install.sh
- test cases/cuda/17 separate compilation linking/meson.build
> cuda: avoid test failure without GPU available

- mesonbuild/coredata.py
- mesonbuild/environment.py
- mesonbuild/machinefile.py
- mesonbuild/scripts/scanbuild.py
- test cases/unit/116 empty project/expected_mods.json
- unittests/allplatformstests.py
- unittests/machinefiles/constant1.txt
- unittests/machinefiles/constant2.txt
- unittests/machinefiletests.py
- unittests/platformagnostictests.py
Standalone part of the optionrefactor branch.
> Extract MachineFile code to its own file

- mesonbuild/backend/ninjabackend.py
as discussed in https://github.com/mesonbuild/meson/issues/12735:
Instead of invoking javac for every .java file, pass all of the sources for a jar target to a single javac invocation. This massively improves first compilation time and doesn't meaningfully affect incremental builds (it can even be faster in some cases).
The old approach also had issues where files would not always get recompiled even though they should, necessitating a clean rebuild in order to see changes reflected in the build output.
Multiple invocations seem to only make sense if:
- issues with files not getting flagged for rebuild are investigated and fixed
- something like the javaserver buildtool from openjdk sources is used instead of directly spawning javac processes
- the amount of java files per jar is so large …
> java: use single javac invocation per jar

- mesonbuild/msubprojects.py
- mesonbuild/wrap/wrap.py
- unittests/allplatformstests.py
This will simplify creating PackageDefinition objects from Cargo.lock file. It contains basically the same information.
> wrap: Clarify PackageDefinition API using dataclass

- mesonbuild/mformat.py
- test cases/format/1 default/indentation.meson
> mformat: fix else token not correctly indented

- mesonbuild/backend/backends.py
- mesonbuild/utils/core.py
- test cases/common/41 test args/meson.build
This PR fixes issue #12327 by 
1. Creating a test-case that reproduces the issue (tested in isolation only, I did not run the entire test-suite).
2.  Reverting commit 2cb7350d1679fb61826bf4aebfb0f75a9b9103e3 which introduced the issue.
Unfortunately I don't really understand what the original commit was doing, but this revert fixes the issue for me.
> Fix broken env.append

- test cases/linuxlike/1 pkg-config/prog-checkver.c
- test cases/linuxlike/13 cmake dependency/prog-checkver.c
I failed to properly account for the case in which the two string are completely equal.
> Fix the zlib-ng failing tests, for real

- data/shell-completions/zsh/_meson
Fix spelling errors and add missing subcommands to zsh completion.
https://github.com/mesonbuild/meson/issues/13435
> Update zsh completions

- test cases/format/1 default/crazy_comments.meson
- test cases/format/2 muon/crazy_comments.meson
- test cases/format/3 editorconfig/crazy_comments.meson
- test cases/format/4 config/crazy_comments.meson
We have permission to use that file. Fixes #13442.
> Remove reference to GPL in test files

- mesonbuild/wrap/wrap.py
URLError is a subclass of OSError and intermittent server errors can manifest as OSError while reading instead of a URLError while establishing a connection, which will cause the fallback url to be ignored:
```
Looking for a fallback subproject for the dependency gudev-1.0
Downloading libgudev source from https://gitlab.gnome.org/GNOME/libgudev/-/archive/238/libgudev-238.tar.bz2
HTTP Error 404: Not Found
WARNING: failed to download with error: could not get https://gitlab.gnome.org/GNOME/libgudev/-/archive/238/libgudev-238.tar.bz2 is the internet available?. Trying after a delay...
HTTP Error 404: Not Found
WARNING: failed to download with error: could not get https://gitlab.gnome.org/GNOME/libgudev/-/archive/238/libgudev-238.tar.bz2 is the internet available?. Trying after a delay... …
```
> wrap: Use OSError instead of URLError for exception handling

- mesonbuild/ast/interpreter.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/cmake/traceparser.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/mixins/emscripten.py
- mesonbuild/compilers/objc.py
- mesonbuild/compilers/objcpp.py
- mesonbuild/compilers/vala.py
- mesonbuild/coredata.py
- mesonbuild/dependencies/boost.py
- mesonbuild/mformat.py
- mesonbuild/modules/python3.py
- mesonbuild/optinterpreter.py
- unittests/baseplatformtests.py
- unittests/helpers.py
- unittests/linuxliketests.py
- unittests/machinefiletests.py
- unittests/rewritetests.py
- add a bunch of mypy annotations
- take some imports that aren't used except for typing, and move them to TYPE_CHECKING
- fix some broken or redundant logic uncovered by mypy:
- `if func:`
- checking `if isinstance` that can never be false
- use another couple of dataclasses
> random miscellaneous lint fixes

- mesonbuild/mdist.py
- test cases/nasm/1 configure file/meson.build
- make asm tests debuggable
- meson dist for mercurial is actually broken right now, iff you use a non-english locale.
> Test fixups

- mesonbuild/minstall.py
Reverts mesonbuild/meson#13507
Fixes #13519
No unicode, thanks.
> Revert "minstall: update symlink install message presentation"

- mesonbuild/cargo/interpreter.py
It is only required if a Cargo subproject is actually configured.
> cargo: Ignore Cargo.lock if toml implementation is missing

- mesonbuild/mformat.py
- unittests/platformagnostictests.py
> mformat: detect invalid config files

- mesonbuild/mformat.py
- mesonbuild/mparser.py
- test cases/format/1 default/meson.build
- test cases/format/1 default/meson.options
> mformat: better handling of continuation lines

- mesonbuild/machinefile.py
- run_mypy.py
There's not much here to fix, but with a `TypeAlias` we can solve the issue of recursive types.
> Make machinefile.py typesafe

- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/detect.py
Currently, CUDA linking would fail when there are incompatible options in `$LDFLAGS` (see #11234 for example). This PR fixes this using the `_to_host_flags` method of `CudaCompiler`.
Fixes #11234
> Fix LDFLAGS for cuda linking

- docs/yaml/functions/_build_target_base.yaml
- mesonbuild/interpreter/interpreter.py
- test cases/d/9 features/meson.build
Also update the documentation to reflect the accepted types.
Fixes: #12742
> Convert string args to d_import_dirs.

- mesonbuild/cmake/interpreter.py
Written while looking at https://github.com/mesonbuild/meson/issues/13602
> cmake: actually print the cycle in the error message

- mesonbuild/mdist.py
When `meson dist` fails with the error:
```
Dist currently only works with Git or Mercurial repos
```
It is sometimes inaccurate, since a git repo may exist but be nonfunctional. Offer some better guidance in that case.
Fixes: #10866
> mdist: detect pathological git repo cases and show a slightly better error

- test cases/frameworks/25 hdf5/meson.build
> tests: set c++ stdandard to c++11 for hd5f

- docs/markdown/snippets/nvc_now_support_setting_std.md
- mesonbuild/compilers/c.py
- mesonbuild/compilers/cpp.py
> Add options for standard parameter for nvc and nvc++

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/c.py
- mesonbuild/compilers/cpp.py
- unittests/allplatformstests.py
Fixes a few minor formatting and language consistency issues in message strings.
> Clean up inconsistent message strings

- docs/markdown/Users.md
They recently made the switch from Autotools to Meson!
> Add Linux PAM to list of users

- mesonbuild/mdevenv.py
We don't need an extra process in the process tree (specifically the `meson devenv` process itself). Aside for the redundancy, it's actively problematic if you abort a program in the devenv by using CTRL+C, as meson itself will then emit a traceback (KeyboardInterrupt) which is quite ugly.
/cc @xclaesse
> mdevenv: exec directly into the program to run

- mesonbuild/backend/ninjabackend.py
> Building meson-python fails in AIX

- docs/markdown/Users.md
> Remove trailing full stops/periods from entries in list of users

- mesonbuild/compilers/mixins/visualstudio.py
Chunked out from the option refactor branch.
> Add VS preview version.

- mesonbuild/scripts/env2mfile.py
Needed for [this](https://salsa.debian.org/debian/debhelper/-/merge_requests/127#note_553685).
Tagged for 1.6.1. because this should go in the next Debian release.
*Edit*: do not merge until suitability has been agreed with Debian people.
> Add flag to use FOR_BUILD.

- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
The annotations weren't updated to reflect the changes.
> interpreter: fix type issues with vcs_tag updates

- .github/workflows/os_comp.yml
ci: fix Ubuntu Bionic job
Do the same as https://github.com/pytorch/test-infra/pull/5959 and download
an old nodejs to keep Ubuntu Bionic working.
Bug: https://github.com/actions/checkout/issues/1809
Bug: https://github.com/actions/runner/issues/3373
> ci: fix Ubuntu Bionic job

- ci/ciimage/arch/install.sh
- ci/ciimage/fedora/install.sh
- ci/ciimage/opensuse/install.sh
- ci/ciimage/ubuntu-rolling/install.sh
> ci: add qt6 QML libraries in Linux images

- docs/markdown/Builtin-options.md
> docs: clarify behavior of default_both_libraries option

- mesonbuild/backend/ninjabackend.py
> Fix to Meson failed to archive shared libraries in AIX.

- .github/workflows/macos.yml
- mesonbuild/dependencies/python.py
- unittests/pythontests.py
Also fix the relevant tests with Xcode-provided Python, and add a CI job to test it.
See #14169
cc @nirbheek
> Python: fix typo in the inserted workaround for missing RPATH

- mesonbuild/backend/ninjabackend.py
> Actually use return value of SwiftCompiler.get_working_directory_args

- mesonbuild/build.py
- mesonbuild/coredata.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/options.py
Which simplifies some code, and makes updating the types that that we accept easier.
> Add a TypeAlias for option values

- mesonbuild/options.py
- unittests/allplatformstests.py
> Fix reconfiguration on --wipe.

- mesonbuild/msetup.py
- unittests/platformagnostictests.py
> Permit all unknown b_ options.

- mesonbuild/interpreter/interpreter.py
- mesonbuild/options.py
- unittests/optiontests.py
A rework of  #14272.
Closes: #14255.
> Maintain bw compatibility for requesting bad options. Closes: #14255.

- mesonbuild/compilers/swift.py
A default option to pass -swift-version to the compiler. Like rust_std.
> swift: Add lang_version compiler option

- mesonbuild/coredata.py
- mesonbuild/mconf.py
Added by the optionrefactor changes, but not used
> coredata: delete a bunch of unused methods

- docs/markdown/Cross-compilation.md
> doc: fix sentence about cross-compilation.

- .github/FUNDING.yml
- docs/markdown/Contributing.md
- docs/markdown/Donating.md
- docs/markdown/FAQ.md
- docs/markdown/index.md
- docs/sitemap.txt
@mesonbuild/core-maintainers 
Closes: #14262
> docs cleanup: python support policy, donation links

- mesonbuild/backend/xcodebackend.py
- mesonbuild/mparser.py
- mesonbuild/scripts/python_info.py
> Fix typos in comments

- docs/markdown/Builtin-options.md
- docs/markdown/snippets/b_sanitizer_changes.md
- mesonbuild/backend/vs2010backend.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/compilers/mixins/islinker.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/compilers/rust.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/linkers/linkers.py
- mesonbuild/modules/gnome.py
- test cases/unit/125 sanitizers/meson.build
- unittests/allplatformstests.py
- unittests/linuxliketests.py
This is a rebased and fixed version of #12648.
>  b_sanitize as an array

- mesonbuild/linkers/linkers.py
More specifically, the bug had been fixed shortly before we implemented this workaround. It's documented as only necessary for the binutils brand specifically, and was fixed upstream in 2.28. We can avoid producing these arguments at all on newer (post-2016) versions of binutils, so gate this behind a version check.
This can significantly reduce the size of compiler command lines in some cases, as it encodes the full build directory. It also helps that one person who decides to put commas into their build directory name (which `-Wl,...` interprets as multiple arguments, rather than a single directory string).
Bug: https://github.com/mesonbuild/meson/pull/1898
Bug: https://sourceware.org/bugzilla/show_bug.cgi?id=20535
Bug: https://sourceware.org/bugzilla/show_bug.cgi?id=16936
/cc …
> linkers: revert a binutils bug workaround, sort of

- mesonbuild/compilers/detect.py
> mesonbuild/compilers/detect.py: Support Open D ldc and dmd

- mesonbuild/ast/interpreter.py
- mesonbuild/ast/introspection.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreterbase/interpreterbase.py
- unittests/allplatformstests.py
- unittests/datatests.py
This is a series of commit to attempt to cleanup some duplication between the Interpreter, the AstInterpreter, and the IntrospectionInterpreter.
> Refactor interpreter

- mesonbuild/modules/cmake.py
- run_mypy.py
Mostly this was just adding a few asserts for options, and one bug fix from the option refactor
> modules/cmake: Make fully type safe

- ci/ciimage/arch/install.sh
- ci/ciimage/opensuse/install.sh
See https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/BJO756KHSCBPDMXVGFMGPHPUMW4PZK6T/#SLVEVFEFOCT3R5RCSVZPQN3GZSZYAEXL.
> ci: opensuse: drop libSDL2-devel

- .github/workflows/nightly.yml
- setup.py
Closes https://github.com/mesonbuild/meson/issues/14419
> Nightly wheels

- run_mypy.py
See also https://github.com/hauntsaninja/mypy_primer/pull/77
> Make run_mypy.py work in mypy_primer

- docs/markdown/Releasing.md
- docs/markdown/Rust-module.md
- docs/markdown/snippets/android-exe-type.md
- docs/markdown/snippets/c2y.md
- docs/markdown/snippets/objc-cpp.md
- docs/markdown/snippets/stabilized-wayland.md
- docs/markdown/snippets/swift-std.md
- man/meson.1
Add new features to release notes and other minor fixes to the documentation.
> Fixes for 1.8 docs

- mesonbuild/mformat.py
- test cases/format/5 transform/default.expected.meson
- test cases/format/5 transform/muon.expected.meson
- test cases/format/5 transform/options.expected.meson
- test cases/format/5 transform/source.meson
Fixes https://github.com/mesonbuild/meson/issues/14364
> Fix meson format with multi line parenthesized expressions

- mesonbuild/mparser.py
- test cases/failing/95 invalid option file/test.json
> more explicit error message for unrecognized lexer token

- mesonbuild/interpreter/dependencyfallbacks.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/options.py
- test cases/common/281 subproj options/meson.build
- test cases/common/281 subproj options/subprojects/sub/meson.build
- test cases/common/281 subproj options/subprojects/sub/meson_options.txt
- test cases/common/281 subproj options/subprojects/sub2/meson.build
- test cases/common/281 subproj options/subprojects/sub2/meson_options.txt
- test cases/common/98 subproject subdir/meson.build
- test cases/common/98 subproject subdir/subprojects/sub_static/meson.build
- test cases/common/98 subproject subdir/subprojects/sub_static/meson_options.txt
Fixes: #14528
Fixes: #14532
And also fixes an assertion failure that I triggered while writing tests.
> Fix more option regressions

- mesonbuild/utils/universal.py
When git is used with worktrees, `.git` will be a file containing a link to the original repo. Currently, we say that this is not git because `.git` isn't a directory.
> utils: Support VCSs that can have file repodirs

- docs/meson.build
Allows to browse the documentation offline.
> docs: Generate the devhelp file from the documentation

- docs/extensions/refman_links.py
Based on https://github.com/mesonbuild/meson/pull/14707
This makes all the symbols searchable from the .devhelp file.
> docs: Make RefMan create symbols for all the references

- mesonbuild/compilers/cuda.py
CUDA 12.9.0 ships a cccl that supports the new debug macros.
> cuda: enable support for `CCCL_ENABLE_ASSERTIONS`

- mesonbuild/environment.py
- test cases/unit/69 cross/nativefile.in
Fixes: #14789 
for real this time.
> environment: really remove assertion

- mesonbuild/modules/gnome.py
g-ir-scanner is a pair of Python script + pymod, and the latter must be available at any time the script is executed. The changes in the below commit removed the ordering guarantee, breaking GStreamer introspection building on Windows when using the monorepo.
This reverts commit ab57be75148c2faac67dba7877167772410ca5ef.
Fixes #14908
> gnome: Restore dependency of g-ir-scanner on gobject-introspection

- mesonbuild/modules/__init__.py
- mesonbuild/modules/gnome.py
This reverts commit 5e627c9b421a4cebb0e112af6a432fec66640c28.
> Revert "gnome: support generate_gir on cross builds"

- docs/markdown/Adding-new-projects-to-wrapdb.md
@bgilbert I couldn't find what you described in https://github.com/mesonbuild/wrapdb/pull/2206#discussion_r2296506391 in the documentation, so I figured it was worth adding. Let me know if this works, or if mistakenly overlooked it
> Add docs on dependency handling conventions for upstream WrapDB projects

- docs/markdown/snippets/b_msvcrt_clang.md
- mesonbuild/compilers/mixins/clang.py
- mesonbuild/compilers/mixins/clike.py
- unittests/windowstests.py
> compilers: clang: map -Db_vscrt to -fms-runtime-lib

- mesonbuild/mformat.py
- mesonbuild/mparser.py
- test cases/format/1 default/indentation.meson
- test cases/format/5 transform/default.expected.meson
- test cases/format/5 transform/muon.expected.meson
- test cases/format/5 transform/options.expected.meson
- test cases/format/5 transform/source.meson
- Split long expressions in () according to max line length
- Partly revert d028502 . Fixes #14935.
- Fixes #15032.
> format: Fix indentation with parentheses

- mesonbuild/ast/introspection.py
- mesonbuild/coredata.py
- test cases/common/43 subproject options/meson.build
- test cases/common/43 subproject options/subprojects/subproject/meson.build
Fix for #14939, backported to the 1.8 branch
> Option fixes for 1.8.5, with conflicts resolved

- .mypy.ini
- mesonbuild/ast/interpreter.py
- mesonbuild/dependencies/base.py
- mesonbuild/envconfig.py
- mesonbuild/mlog.py
- mesonbuild/modules/cmake.py
- mesonbuild/modules/external_project.py
- mesonbuild/options.py
- mesonbuild/scripts/run_tool.py
- mesonbuild/scripts/symbolextractor.py
- run_project_tests.py
After this, bleeding edge mypy has "only" 6 errors, 3 of which are unused-ignore.
> Mypy cleanups in preparation for 1.18
