- mesonbuild/compilers/mixins/clike.py
Bug: https://bugs.gentoo.org/726524
> Ignore file access errors when scanning .so files in system libdirs

- docs/markdown/Users.md
libeconf is now using meson as its primary/default build system, so we'd like to see ourselves on the meson users list .
> Add libeconf to users.md

- mesonbuild/backend/vs2010backend.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/dependencies/misc.py
Using --backend=ninja with Visual Studio results in many warnings (one for each static library included in an executable). Using --backend=vs2019 results in OpenMP not working.
Fix both of these issues.
Example meson.build file demonstrating these issues:
```meson
project('tmp', 'c')
openmp = dependency('openmp')
libone = static_library('libone', 'fileone.c', dependencies: openmp)
libtwo = static_library('libtwo', 'filetwo.c', dependencies: openmp)
executable('main', 'main.c', link_with: [libone, libtwo])
```
> Fix OpenMP on Visual Studio

- .travis.yml
- azure-pipelines.yml
- ci/travis_script.sh
- docs/markdown/snippets/response-files.md
- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/linkers.py
- run_unittests.py
- test cases/common/145 special characters/arg-char-test.c
- test cases/common/145 special characters/arg-string-test.c
- test cases/common/145 special characters/arg-unquoted-test.c
- test cases/common/145 special characters/meson.build
- test cases/common/234 very long commmand line/codegen.py
- test cases/common/234 very long commmand line/main.c
- test cases/common/234 very long commmand line/meson.build
- test cases/common/234 very long commmand line/seq.py
(This is #5245 rebased to master, with a few fixes, a little quote testing from #7219, and a little rspfile support detection added.  It supersedes the less tidy versions in #7215 and #7227.)
Make ninja backend only use response files when the command line is long enough to need them.
This makes the output of 'ninja -v' useful more often (something like cl @exec@exe/main.c.obj.rsp is not very useful if you don't have the response file to look at; this is helpful when the response file (and/or the VM containing it) has been deleted by the time you get to look at the error) (see also discussion in ninja-build/ninja#1223)
Also, per #271 (comment), writing rsp files on Windows is moderately expensive.
This also prevents rules which aren't used by any build statement from being emitted in the …
> Make ninja backend only use response files when needed, on linux too

- mesonbuild/compilers/compilers.py
MinGW gcc supports _FILE_OFFSET_BITS=64 and we need to set it for
MinGW as well
cc: @nirbheek
> compilers: Add UNIX large file support for MinGW

- mesonbuild/cmake/traceparser.py
Meson 0.54.0 introduced a regression from acc6dbfab7 that affects `dependency()` that uses CMake, even automatically--Meson crashes with traceback at the bottom of this post.
This "fix" has been previously applied in other PRs to other places Meson reads CMake trace--this was just the latest issue introduced.
```
File "meson\mesonbuild\mesonmain.py", line 129, in run
File "meson\mesonbuild\msetup.py", line 245, in run
app.generate()
File "meson\mesonbuild\msetup.py", line 159, in generate
File "meson\mesonbuild\msetup.py", line 192, in _generate
intr.run()
File "meson\mesonbuild\interpreter.py", line 4169, in run
super().run()
File "meson\mesonbuild\interpreterbase.py", line 412, in run …
```
> 0.54 regression: cmake_traceparser: ignore trace parse error

- mesonbuild/minit.py
- mesonbuild/mintro.py
Makes options sorted when displayed via `--help`. 
This is needed for deterministic output for https://github.com/mesonbuild/meson/pull/7217
> Make --help options sorted

- mesonbuild/coredata.py
fixes #7269
test by:
meson.build
```meson
project('foo')
message(get_option('m1'))
```
meson_options.txt
```meson
option('m1', type: 'combo', choices: ['a', 'b'])
```
then do
```sh
meson build -Dm1=c
```
now results in 
> meson.build:1:0: ERROR: Value "c" for combo option "m1" is not one of the choices. Possible choices are: "a", "b".
> tell variable name when erroring on bad combo option

- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/misc.py
- mesonbuild/dependencies/ui.py
This is a holdover from before we had the DependencyFactory. It should
have already been refactored into the initializer, but wasn't for some
reason.
> dependencies: Remove finish_init method

- mesonbuild/dependencies/base.py
- mesonbuild/interpreter.py
Windows has a python3.exe in the WindowsApps directory that either
redirects you to the app store to install python, or dispatches to the
real python3.exe if it's installed. To allow using this python, don't
exclude WindowsApps from path searches (but do order it last), and
ignore any error in resolving the executable path to the dispatcher.
Closes https://github.com/mesonbuild/meson/issues/6927
> Fix python3 installed from the windows app store

- mesonbuild/compilers/compilers.py
- mesonbuild/coredata.py
- mesonbuild/linkers.py
- run_unittests.py
commit 7cc9039fc452fd89c686c5049b38da1e95cb447e:
```
Fix typo in bitcode message
```
commit 3cd2dacde9f4513d192d169e40b67a906df6c982:
```
apple: -headerpad args are ignored when bitcode is enabled
Causes spammy warnings from the linker:
ld: warning: -headerpad_max_install_names is ignored when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES)
```
> apple: -headerpad args are ignored when bitcode is enabled

- docs/markdown/Reference-manual.md
Should be "sources" not "source"
```
../meson.build:162: WARNING: Passed invalid keyword argument "source".
WARNING: This will become a hard error in the future.
File "/usr/local/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 131, in run
File "/usr/local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 245, in run
app.generate()
File "/usr/local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 159, in generate
File "/usr/local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 192, in _generate
intr.run()
File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 4359, in run
super().run()
File …
```
> Correct argument typo in partial_dependency Documentation

- docs/markdown/Gnome-module.md
The documentation of gnome.generate_gir() has duplicated entry for
dependencies parameter. As a fix, this patch removes the entry added
recently.
> docs: remove duplicated entry for gnome.generate_gir() documentation

- mesonbuild/cmake/executor.py
- mesonbuild/dependencies/base.py
- test cases/cmake/7 cmake options/subprojects/cmOpts/CMakeLists.txt
- test cases/cmake/7 cmake options/test.json
> cmake: Subprojects support CMAKE_PREFIX_PATH (fixes #7249)

- docs/markdown/Builtin-options.md
- docs/markdown/Reference-tables.md
I tried to fix the docs when the stuff was added, but it turns out I missed things, as noted by @baryluk in https://github.com/mesonbuild/meson/issues/7284#issuecomment-641641177
CC @dcbaker
> docs: Bring up to date on options per machine

- mesonbuild/mintro.py
This is needed for deterministic output for #7217
> mintro: enforced order for subcommands

- mesonbuild/cmake/executor.py
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/ui.py
Even if the build machine == host machine, we can't use dependencies from the build machine for the host machine. This can happen when using a system to build a new machine image. for example when compiling chromeos. It's completely possible to build an x86_64-linux host for an x86_64-linux build machine, but not have all of the same runtime dependencies. In particular, if meson tries to use cmake from the build machine for host dependencies it will result in trouble.
Fixes: #7276
> Don't try to use build machine dependency finders for host

- mesonbuild/mdist.py
Since we parse `buildoptions.json` to pass options, we end up passing `-Dbuildtype` and also `-Doptimization` and `-Ddebug` which triggers the warning:
`WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug [...]`
Filter out buildtype. It is redundant.
> mdist: Filter out buildtype to avoid warning

- .github/workflows/unusedargs_missingreturn.yml
See: https://github.com/mesonbuild/meson/pull/7306#issuecomment-643606736
> ci: Pin ninja to 1.9.0.post1 for now

- azure-pipelines.yml
- test cases/cmake/2 advanced/meson.build
- test cases/cmake/5 object library/meson.build
These only fail when building with msvc/clang-cl on the VS2017-Win2016
image. See: https://github.com/mesonbuild/meson/issues/7307
Attempt at making https://github.com/mesonbuild/meson/pull/7314 more specific.
> Disable failing cmake jobs on VS2017

- mesonbuild/dependencies/base.py
vcpkg libraries are not found when given cmake_toolchain_file and vcpkg_target_triplet as cmake_args when looking for the dependency because 
the first call to cmake has different arguments. The libraries are found if the first call has same arguments or if the CMakeCache.txt is deleted in call_with_fake_build.
This allows using vcpkg cmake toolchain to find libraries.
```
sqlite_dep = dependency('sqlite3',
modules : ['SQLite::SQLite3'],
method : 'cmake',
cmake_args : [
'-DCMAKE_TOOLCHAIN_FILE=' + meson.get_external_property('vcpkg_root') + '/scripts/buildsystems/vcpkg.cmake', 
'-DVCPKG_TARGET_TRIPLET=' + meson.get_external_property('vcpkg_triplet')
]
)
```
> Use cmake args also when calling get_cmake_info

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- test cases/fortran/7 generated/meson.build
- test cases/fortran/7 generated/mod1.fpp
- test cases/fortran/7 generated/mod2.fpp
- test cases/fortran/7 generated/mod3.fpp
- test cases/fortran/7 generated/prog.f90
Meson 0.54.1 has a regression noted in #7265. This additional test code reveals the issue, but does not fix the issue. This is an important use case that may only break on Windows, but it's good to add this test in general.
> 0.54.1 regression: add library() check for Fortran configure_file()

- docs/markdown/Commands.md
- docs/sitemap.txt
- run_unittests.py
- Added a commands page describing all listed top level meson commands.
- Added a unit-tests that checks that all commands were documented.
Some problems that might need to be solved in this PR or maybe a later PR:
- There's [a page](https://mesonbuild.com/Creating-releases.html#page-description) that describes `ninja dist` which basically does the same as `meson dist`. It can either be removed altogether or amended to use `meson dist` instead of `ninja`.
- This page should be probably integrated in the [overview](https://mesonbuild.com/Running-Meson.html). But I can't think of a good way to do that currently. Overview page also uses ninja as *the way*, should be probably amended.
- `meson install` command links to [a page](https://mesonbuild.com/Installing.html), which again uses `ninja` …
> Added docs for all meson commands + corresponding unit test

- mesonbuild/backend/vs2010backend.py
When changing meson option cpp_eh, it was passed to cl with AdditionalOptions which works but it also resulted in unsuppressable warning "cl : command line warning D9025: overriding '/EHs' with '/EHa'"
> Add exception handling to be also written to the VS project xml

- mesonbuild/environment.py
- run_unittests.py
- test cases/fortran/7 generated/meson.build
* allow testcases/fortran/7generated to pass with IntelCl on Windows--CL-based Windows Fortran compilers generally are easier to use with static linking as shared linking requires special non-standard Fortran syntax just for CL. So like other such Meson Fortran project tests, we default to static linking.
* add a fallback version-finding regex, as Intel has moved to four-digit year-based versions with their new, no-cost [oneAPI compilers](https://software.intel.com/content/www/us/en/develop/tools/oneapi/hpc-toolkit.html).
Example:
```sh
ifort /logo
```
```
Intel(R) Visual Fortran Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 2021.1 Beta Build 20200306
```
```sh
icl
```
```
Intel(R) C++ Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 2021.1 …
```
> Intel compiler enhancements

- docs/markdown/FAQ.md
Fixed code fragment in the "How do I tell Meson that my sources use generated headers?" section in the FAQ.
Now this fragment will work without throwing an error.
Fixes issue  #7317
> Documentation, FAQ.md, generated_headers

- run_cross_test.py
- run_meson_command_tests.py
- run_project_tests.py
- run_tests.py
- run_unittests.py
When building a general Meson project, the Meson version is printed first. I find this very handy, and it would be even more useful to have the Meson version printed at the start of Meson's own run_*test.py scripts, as they can take over an hour to run, so you want to be sure you're testing the intended Meson version. 
I also saw some PEP8 issues including missing import and unused variable that I fixed in the second commit.
* print Meson version at start of each Meson internal run_*tests.py execution.
> run_*test.py: print meson version at start of test

- docs/markdown/Builtin-options.md
- docs/markdown/Subprojects.md
- docs/markdown/snippets/force_fallback_for.md
- mesonbuild/coredata.py
- mesonbuild/interpreter.py
- run_unittests.py
This new command line option allows specifying dependencies for
which to force fallback.
See the documentation for more information
Fixes: #7218
> interpreter: add support for --force-fallback-for

- azure-pipelines.yml
- ci/run.ps1
- test cases/cmake/2 advanced/test.json
- test cases/cmake/5 object library/test.json
It's one of the causes of the cmake test failures, and it's also plaguing the VS2019 jobs now because of the image update.
> ci: Remove PostgreSQL from PATH

- docs/markdown/Commands.md
- docs/markdown/Configuring-a-build-directory.md
- docs/markdown/Continuous-Integration.md
- docs/markdown/Creating-OSX-packages.md
- docs/markdown/Creating-releases.md
- docs/markdown/Cross-compilation.md
- docs/markdown/Design-rationale.md
- docs/markdown/FAQ.md
- docs/markdown/Feature-autodetection.md
- docs/markdown/Gnome-module.md
- docs/markdown/IDE-integration.md
- docs/markdown/IndepthTutorial.md
- docs/markdown/Installing.md
- docs/markdown/Meson-sample.md
- docs/markdown/Project-templates.md
- docs/markdown/Qt5-module.md
- docs/markdown/Quick-guide.md
- docs/markdown/Running-Meson.md
- docs/markdown/Tutorial.md
- docs/markdown/Unit-tests.md
- docs/markdown/Using-multiple-build-directories.md
- docs/markdown/Vs-External.md
- docs/markdown/howtox.md
Replaced direct `ninja` invocations with equivalent `meson` commands.
Reasoning:
- Users don't and shouldn't care about the backend in most cases. It's an implementation detail. One of the most frequent question that I was asked when introducing meson is `what is ninja?`/`is ninja part of the meson?`/`why do I have to invoke ninja/.sln directly?`
- Backend-agnostic meson methods cover 99% of common ninja scenarios (1% being specifying targets(https://github.com/mesonbuild/meson/pull/7181) and backend arguments(https://github.com/mesonbuild/meson/pull/7183)). And most of these methods provide additional functionality not available via direct ninja invocation (most prominent example would be `meson test`).
- Meson should be about meson promotion and not ninja promotion =)
- No one ever …
> docs: replaced ninja with appropriate meson commands [skip ci]

- docs/markdown/Wrap-dependency-system-manual.md
- docs/markdown/snippets/wrap_patch.md
- mesonbuild/wrap/wrap.py
- test cases/common/157 wrap file should not failed/meson.build
- test cases/common/157 wrap file should not failed/subprojects/packagefiles/foo-1.0/meson.build
- test cases/common/157 wrap file should not failed/subprojects/patchdir.wrap
I'm just wondering if we should force patch_directory inside `packagefiles` subdir?
> wrap: Add patch_directory support

- docs/markdown/Syntax.md
Also document that line continuation didn't work before 0.50.
90c9b868b20b11bb089fc5e0c634d5ed76fea0cb fixed it.
> docs: Document string path building with examples

- azure-pipelines.yml
The default timeout is 60 min and we're timing out, but the maximum we can have is 6 hours. Bump it to 120 min for now.
Also workaround MSYS2 update breakage
> ci: Bump the cygwin timeout to 120 minutes, workaround MSYS2 breakage

- mesonbuild/wrap/wrap.py
This lets servers know when they're being used by meson. It also avoids issues where the Independent JPEG Group decided to ban the "Python-urllib" default user agent.
Fixes https://github.com/mesonbuild/libjpeg/issues/9
> wrap: add user agent when downloading files

- docs/markdown/Syntax.md
fixes #7376 
Meson version comparison conventions include:
```meson
'3.6'.version_compare('>=3.6.0') == false
```
It is best to be unambiguous and specify the full revision level to compare.
> docs: version_compare: note it's best to be unambiguous

- docs/markdown/Commands.md
- docs/markdown/snippets/add_compile_backend_arg.md
- mesonbuild/mcompile.py
- run_unittests.py
Adds ability to pass arguments directly to backend build tool:
```
usage: meson compile [--vs-args=args] [--ninja-args=args]
```
These arguments  use the following syntax:
If you only pass a single string, then it is considered to have all values separated by commas. Thus invoking the following command:
```
$ meson compile --ninja-args=foo,bar
```
would set the value to an array of two elements, foo and bar.
If you need to have commas in your string values, then you need to pass the value with proper shell quoting like this:
```
$ meson compile "--ninja-args=['a,b', 'c,d']"
```
> Added ability to pass arguments to backend in `meson compile`

- docs/markdown/Commands.md
- docs/markdown/snippets/add_meson_compile_target.md
- mesonbuild/mcompile.py
- run_unittests.py
Implements and fixes #6740
Target name has the following syntax: `[PATH/]FOO[:TARGET_TYPE]`:
- `compile FOO` - works if there is only a single instance of FOO in introspection, errors out otherwise.
- `compile FOO:TARGET_TYPE` - works if there is only a single instance of FOO in introspection with TARGET_TYPE.
- `compile PATH/FOO:TARGET_TYPE` - always works
PATH - relative path from meson root to the target (e.g `./foo` or `subdir/subdir/foo`).
FOO - target name from meson syntax (e.g. `shared_library('foo', ...)`)
TARGET_TYPE - target type (`shared_library`, `static_library`, `jar`, `run` and etc).
Supported backends: msvs and ninja.
Limitations: 
- msvs: `run_target` is not supported
> Added ability to specify target in `meson compile`

- docs/markdown/Machine-files.md
- docs/markdown/snippets/machine_file_constants.md
- mesonbuild/coredata.py
- mesonbuild/envconfig.py
- mesonbuild/environment.py
- run_unittests.py
Machine files already supports `+` operator as an implementation detail,
since it's using eval(). Now make it an officially supported feature and
add a way to define constants that are used while evaluating an entry
value.
> envconfig: Add [constants] section in machine files

- docs/markdown/Wrap-dependency-system-manual.md
- docs/markdown/snippets/wrap_patch.md
- mesonbuild/wrap/wrap.py
- run_unittests.py
- test cases/unit/78 wrap-git/meson.build
- test cases/unit/78 wrap-git/subprojects/packagefiles/wrap_git_builddef/meson.build
- test cases/unit/78 wrap-git/subprojects/wrap_git_upstream/main.c
It can be useful to have the wrap file track upstream master branch, and provide the meson build system as a patch on top. This avoids having to maintain a git clone.
> wrap: Apply patch even in VCS cases

- docs/markdown/Reference-manual.md
The inconsistency was bugging me forever =)
Strange `*introduced in v0.xx*` placement was confusing as well.
Cleaned up using the following rules:
- All changes that appeared in certain meson versions were marked with `*(since 0.xx.x)*` (instead of `*(added in 0.xx.x)*`, `*in 0.xx*` and etc).
- Kwargs and arguments has the following formatting:
```
- `kwarg1_name` *(since 0.xx.x)*: kwarg1_description.
- `kwarg2_name`: *(since 0.xx.x)* **(deprecated)** kwarg2_description.
```
- Changes that appeared starting from a certain version have the following formatting:
```
*(since 0.xx.x)* Description of changes.
```
- Methods use the following formatting:
```
`method(args)`
*(since 0.xx.x)*
Method description
```
> Cleaned up Reference docs for consistency [skip ci]

- mesonbuild/environment.py
On some systems aarch64 is reported as arm64. Due to mesons
mangling of everything that starts with arm, it would end up being
detected as arm (which implies 32 bit) which is incorrect.
> environment: Correctly detect arm64 as aarch64

- mesonbuild/interpreter.py
Either give the user control over `skip_sanity_check` or print an error why the user is doing something stupid. This PR uses the former approach
> Give user control of option skip_sanity_check

- mesonbuild/dependencies/ui.py
- mesonbuild/interpreter.py
- mesonbuild/modules/qt.py
Simplify the code by using find_program()'s version check code which
also improve logs by making it clear when the program is found but has
wrong version.
> qt: Fix has_tools() when required=False

- mesonbuild/environment.py
- mesonbuild/interpreter.py
Mesa is doing `project(... find_program() ...)` so
environment.wrap_resolver is not defined yet.
> find_program: Do not use fallback when before parsing project()

- mesonbuild/wrap/wrap.py
It is still used by msubprojects.py and cause issues when updating
wrapdb.
> wrap: Add back filename member in PackageDefinition

- mesonbuild/coredata.py
- mesonbuild/mlog.py
- mesonbuild/modules/qt4.py
- mesonbuild/modules/qt5.py
- mesonbuild/modules/windows.py
Some warnings are out of the user's control, such as the RCC QT bug, or the GNU windres bug, or our informational warning about auto-disabling of options when -Db_bitcode is enabled.
Such warnings should not be fatal when --fatal-meson-warnings is passed because there's no action that the user can take to fix it. The only purpose it serves is to prevent people who use those features from using --fatal-meson-warnings.
> Don't make unactionable warnings fatal

- azure-pipelines.yml
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/mixins/islinker.py
- mesonbuild/linkers.py
I made the mistake of always selecting the debug CRT for compiler checks on Windows 4 years ago: https://github.com/mesonbuild/meson/pull/543 https://github.com/mesonbuild/meson/pull/614
The idea was to always build the tests with debugging enabled so that the compiler doesn't optimize the tests away. But we stopped doing that a while ago, and also the debug CRT has no relation to that.
We should select the CRT in the same way that we do for building targets: based on the options.
On Windows ARM64, the debug CRT for ARM64 isn't always available, and the release CRT is available only after installing the runtime package. Without this, we will always try to pick the debug CRT even when --buildtype=debugoptimized or release.
> Fix native builds on Windows ARM64 machines

- mesonbuild/backend/ninjabackend.py
This was missed somehow when the feature was added a few years ago.
> Enable target override_options for llvm-ir

- mesonbuild/modules/qt.py
- mesonbuild/modules/qt4.py
- mesonbuild/modules/qt5.py
Add depfile support to generated targets for Qt >= 5.14.
Move warning into the module init itself, to check if the version is too old before issuing. Also tweak the wording itself, to advise upgrading to a suitable version of Qt5 instead of advising to wait for a Qt bug to be fixed.
> qt module: rcc supports depfiles now, given a recent enough version of Qt5

- run_project_tests.py
- test cases/python/1 basic/meson.build
- test cases/python/1 basic/prog.py
- test cases/python/1 basic/subdir/subprog.py
- test cases/python/2 extmodule/blaster.py
- test cases/python/2 extmodule/meson.build
- test cases/python/3 cython/cytest.py
- test cases/python/3 cython/meson.build
- test cases/python/4 custom target depends extmodule/blaster.py
- test cases/python/4 custom target depends extmodule/meson.build
- test cases/python/5 modules kwarg/meson.build
The "test cases/python" tests were skipping all tests on MSVC.
Now with MSVC and Windows Store Python
```
Succeeded test (without install): test cases/python/1 basic
Skipping: test cases/python/2 extmodule
Skipping: test cases/python/3 cython
Skipping: test cases/python/4 custom target depends extmodule
Succeeded test (without install): test cases/python/5 modules kwarg
```
This is relevant for finding errors with MSVC, particularly for Windows Store Python as in #7400.
Also, tests 2 and 4 were failing with Anaconda Python on Ubuntu 20.04. Now, all 5 tests succeed for this setup.
Long, nested if statements were simplified for clarity.
Setuptools is not always present, but distutils is part of Python stdlib.
As usual, this can be quickly tested by:
```sh
python run_project_tests.py --only …
```
> Python test upgrade

- mesonbuild/environment.py
- mesonbuild/linkers.py
- mesonbuild/scripts/symbolextractor.py
Fixes issues raised by @dcbaker  during review of #7370 and an additional issue (linker version info showing gcc's instead) noticed while testing.
Tested on both Solaris 11.4 & OpenIndiana 2020.04.
> Solaris fixes revisited

- docs/markdown/howtox.md
This header erroneously referred to the dynamic linker while the paragraph talks about
the "link editor." Change the title to account for the difference.
> Replace `dynamic linker` with `linker`

- mesonbuild/wrap/wrap.py
This avoid printing long backtrace by default, the user already has the
output of the git command printed for debugging purpose since we don't
redirect stdout/stderr.
> wrap: Raise MesonException when git command fails

- mesonbuild/backend/ninjabackend.py
This comment was added in 0fbd09609f4, where the case of a forward
slash was added for the case when cross compiling.
> Fix a comment about cross compilation with clang-cl [skip ci]

- mesonbuild/coredata.py
Fixes:
```python
NameError: name 'EnvironmentException' is not defined
```
> coredata: add missing EnvironmentException import

- docs/markdown/Vala.md
`find_library()` accepts a `dirs` argument, not a `dir` argument.
> Fix dirs typo in Vala docs

- mesonbuild/backend/ninjabackend.py
Put it in the log file if necessary. Users don't need to know this. It's very spammy.
> Don't spam about usage of rspfiles to stdout

- mesonbuild/compilers/mixins/visualstudio.py
In every other compilers level 0 maps to no argument at all.
> visualstudio: warning_level 0 should not map to /W1

- mesonbuild/compilers/mixins/gnu.py
want_output gives us the output file. We don't need the file. We just need the compiler stderr, which is always stored.
> compilers: Cache gnu-mixins has_arguments() checks

- .gitignore
- mesonbuild/dependencies/base.py
- run_project_tests.py
No test case, since the bug was not reproducible with any of our current CMake tests and I don't know what specifically with xerces-c caused the deep copy error.
>  deps: Do not deepcopy internal libraries (fixes #7457) 

- mesonbuild/backend/ninjabackend.py
- run_unittests.py
- test cases/common/109 generatorcustom/meson.build
otherwise we are getting errors like:
```
File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mesonmain.py", line 131, in run
File "/usr/local/lib/python3.6/dist-packages/mesonbuild/msetup.py", line 245, in run
app.generate()
File "/usr/local/lib/python3.6/dist-packages/mesonbuild/msetup.py", line 159, in generate
File "/usr/local/lib/python3.6/dist-packages/mesonbuild/msetup.py", line 215, in _generate
intr.backend.generate()
File "/usr/local/lib/python3.6/dist-packages/mesonbuild/backend/ninjabackend.py", line 518, in generate
self.generate_coverage_rules()
File "/usr/local/lib/python3.6/dist-packages/mesonbuild/backend/ninjabackend.py", line 991, in generate_coverage_rules …
```
> ninjabackend: check if target has compiler attribute

- docs/markdown/Builtin-options.md
For some background, I was attempting to do `meson configure --key=value` and `meson configure key=value` (which it says works with `meson build`). I tried using `meson configure -h` but it's so large it's hard to spot the tiny spot at the bottom that mentions this. Finally, I went to Google, clicked a few pages and finally found the answer [at the bottom of this page](https://mesonbuild.com/Configuring-a-build-directory.html). Figured it be helpful to include it here as well to save people some searching.
> Describe syntax of `meson configure` in docs

- mesonbuild/environment.py
arm64 (aarch64) can natively build and run code for armel and armhf architectures (analagously to amd64 and i386). This patch add support for that.
Mark
> Support native armel/armhf builds on arm64 hosts.

- mesonbuild/compilers/mixins/clang.py
- mesonbuild/environment.py
- mesonbuild/linkers.py
Meson calls `path/to/clang++ --version` to guess which build toolchain the
user has picked to build the source code. For the Qualcomm LLVM toolchain,
the output have an unusual output as shown below:
```
clang version 8.0.12
Snapdragon LLVM ARM Compiler 8.0.12 (based on llvm.org 7.0+)
Target: arm-unknown-linux-gnueabi
Thread model: posix
Repository: (ssh://git-hexagon-aus.qualcomm.com:...)
InstalledDir: /pkg/qct/software/llvm/release/arm/8.0.12/bin
```
Another unusual pattern is the output of `path/to/ld.qcld --version`:
```
ARM Linker from Snapdragon LLVM ARM Compiler Version 8.0.12
ARM Linker based on LLVM version: 8.0
```
The Meson logic is modified accordingly so that Meson can correctly
determine toolchain as "LLVM aarch64 cross-compiler on GNU/Linux64 OS".
This is the expected …
> Make meson recognize the Qualcomm LLVM toolchain

- test cases/frameworks/1 boost/meson.build
Since upgrading Boost to version 1.73, this test segfaults on macOS
when dynamically linked. Disable it to keep the rest of the CI
reliable.
Mitigates: #7535
---
Obviously a better solution would be for someone who uses macOS and/or understands Boost to work out why the test is failing and fix it, but I don't fit that description, so this is the best I can do right now.
> tests: Disable Boost extralib test on macOS

- test cases/common/227 fs module/a_symlink
- test cases/common/227 fs module/meson.build
Windows Git users with symlinks have a **constantly Git dirty Meson repo** from
this "a_symlink".  This is true even when the Windows install has Developer Mode and symlinks enabled via Windows group policy.
This change generates a symlink in the build directory when the test is run, instead of tracking the symlink in Git. 
Now, there is no longer a constantly Git dirty Meson project directory on Windows.
While CMake has the native capability to create symlinks, Meson doesn't have this (it's trivially easy to add, but I think I remember a discussion where it wasn't desired?)
> tests/common/227: don't have symlink in Git

- docs/markdown/Release-notes-for-0.55.0.md
Closes https://github.com/mesonbuild/meson/issues/7438
> Document VS backend from_buildtype behaviour change in release notes

- mesonbuild/cmake/executor.py
This is obviously wrong, since on Windows ':' is in the drive letter. Causes us to call cmake with `-DCMAKE_PREFIX_PATH=c;\foo\bar`.
This broke in https://github.com/mesonbuild/meson/pull/7306, CC: @mensinda
> cmake: Do not split CMAKE_PREFIX_PATH with ':' on Windows

- mesonbuild/dependencies/base.py
The `debug` builtin option does not control whether or not the debug CRT is used. Without this fix, when `buildtype=debugoptimized` or when `debug=true` + `b_vscrt=md`, we will try to link to the debug libraries found via cmake while linking with `/release`, which will cause a link failure.
CC: @mensinda
> cmake: Use the DEBUG config when linking to the debug CRT

- mesonbuild/dependencies/ui.py
The compilers_detect function is only used in the qt module, which checks every time before using a specific compiler, if it is found.
e.g.
```
meson.build:10:6: ERROR: MOC sources specified and couldn't find moc-qt5, please check your qt5 installation
```
In fact, the current check means we never even hit this error to begin with, because we previously died on the uninformative error:
```
meson.build:10:6: ERROR: Program(s) ['moc'] not found or not executable
```
which doesn't actually tell the user why this matters, and is all around a waste of time.
Fixes #5582
> qt dependency: do not require all the tools automatically

- test cases/common/234 very long commmand line/codegen.py
- test cases/common/234 very long commmand line/main.c
- test cases/common/234 very long commmand line/meson.build
- test cases/common/234 very long commmand line/name_gen.py
- test cases/common/234 very long commmand line/seq.py
This is needed to fix #7440 and in general to avoid shaky test failures because of exceeding 260 characters for full file name. This is not just for MSYS2, but also for MSVC and other Windows compilers.
260 character limit on Windows for Meson because:
1. Python < 3.6
2. need to modify Windows 10 registry to break 260 character full pathname limit
> common/234: avoid intermittent failure by dynamic path length generation

- mesonbuild/environment.py
- mesonbuild/mesonlib.py
On QNX/x86_64 "uname -m" reports "x86pc" (for both the 32- and 64 bit variants of x86). To see the actual architecture name we need to use "uname -p", like the *BSDs.
> Use uname -p to detect x86_64 on QNX.

- mesonbuild/cmake/interpreter.py
- test cases/cmake/8 custom command/subprojects/cmMod/CMakeLists.txt
- test cases/cmake/8 custom command/subprojects/cmMod/cpyInc.hpp.am
- test cases/cmake/8 custom command/subprojects/cmMod/macro_name.cpp
This is required to make `-include /path/to/custom/target.hpp` work. This setup is used by wxWidgets and this PR is required to use wxWidgets as a CMake subproject.
> cmake: Detect custom command targets in compiler args

- mesonbuild/compilers/c.py
fixes #7554
Dylan, should I be copying over the "winlibs" from get_options in VisualStudioLikeCCompilerMixin? 
Before this change, a trivial meson.build + main.c would issue:
```sh
[1/2] "cl" "-Imain.exe.p" "-I." "-I.." "/MDd" "/nologo" "/showIncludes" "/W2" "/ZI" "/Ob0" "/Od" "/RTC1" "/Fdmain.exe.p\main.c.pdb" /Fomain.exe.p/main.c.obj "/c" ../main.c
[2/2] "link"  /MACHINE:x64 /OUT:main.exe main.exe.p/main.c.obj "/nologo" "/release" "/nologo" "/DEBUG" "/PDB:main.pdb" "/SUBSYSTEM:CONSOLE" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
````
with this change:
```sh
[1/2] "cl" "-Imain.exe.p" "-I." "-I.." "/MDd" "/nologo" "/showIncludes" "/W2" "/std:c11" "/ZI" "/Ob0" "/Od" "/RTC1" …
```
> msvc: enable /std:c11 flag

- mesonbuild/dependencies/hdf5.py
Older versions of hdf5 (e.g. 1.8) don't have a pkg-config `hdf5.pc` file. Meson uses hdf5's `h5cc` binary for `DependencyMethods.AUTO`.
This PR adds the corresponding arguments to respect "static" key in the dependency function for hdf5:
`h5cc -shlib -show` for shared dependencies
`h5cc -noshlib -show` for static dependencies
Currently `-show` shows only static dependencies by default.
Partially addresses #7555. HDF5 static libraries are not distributed with `fPIC`.
> Add h5cc shlib argument to correctly link hdf5 libraries without pkg-config support

- mesonbuild/cmake/executor.py
Without this, `MSVC` and `MSVC_VERSION` won't be set by CMake during platform detection, and the compiler will be an undefined mixture of GNU and MSVC. In particular, find_package(opencv) will fail on Windows when building with MSVC.
> cmake: Fix hard-coded values in fake CMakeLists for MSVC

- mesonbuild/interpreter.py
- run_unittests.py
> interpreter: Don't force fallback when subproject failed to configure

- test cases/common/23 object extraction/meson.build
Issue #5182 (" extract_objects returns duplicate objects") has been fixed.
Add a testcase to ensure it does not regress.
> add testcase for issue #5182

- mesonbuild/backend/ninjabackend.py
- run_unittests.py
Without the parenthesis, the command evaluates to `[]` if `use_llvm_cov` is `False`.
Also fix tests to actually check whether or not coverage reports are generated.
Fixes https://github.com/mesonbuild/meson/issues/7553
> ninjabackend: Fix coverage rule generation

- azure-pipelines.yml
- mesonbuild/interpreter.py
If we can't find a static library, we should say that. It's confusing otherwise.
> find_library: Print type of library not found

- mesonbuild/interpreterbase.py
- test cases/common/235 disabler array addition/meson.build
- test cases/common/235 disabler array addition/test.c
> prevent disabler() object from overwriting arrays

- mesonbuild/interpreter.py
- mesonbuild/minstall.py
- mesonbuild/scripts/gettext.py
- mesonbuild/scripts/yelphelper.py
It's equivalent to copyfile + copystat with the same arguments.
See https://github.com/mesonbuild/meson/pull/7442#discussion_r472228122
> simplify shutil usage by invoking copy2 where appropriate

- mesonbuild/compilers/cpp.py
- run_unittests.py
Since lcc support was introduced into meson, there were lcc 1.24 and lcc 1.25 major versions released, and they support newer C++ standards. This makes meson able to support them.
Also added a little hack that disables one of architecture dependent unit tests (it uses x86 assembler) on non-x86/x86_64 architectures.
`./run_unittests` produced the following results:
* Elbrus-8C, OS Elbrus 5.0-rc2, lcc:1.24.09: 311 passed, 57 skipped in 172.91s (0:02:52)
* i386, Ubuntu 18.04.4 LTS, gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0: 299 passed, 69 skipped in 1174.43s (0:19:34)
* x86_64, Ubuntu 18.04.5 LTS, gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0: 320 passed, 48 skipped in 170.42 seconds
> Add newer C++ stds support for newer Elbrus compilers

- docs/markdown/Qt5-module.md
- docs/markdown/snippets/qt_compile_translations_from_qrc.md
- mesonbuild/modules/qt.py
A common pattern in Qt5 applications is to embed translations in the executable using the qresource system. In this case, the list of translation files is already available in the .qrc file and there's no good reason to duplicate this info in meson.build.
Let compile_translations optionally take a qrc input, in which case it will go straight to generating the relevant translations and rcc-generated .cpp, and directly return the thing users actually care about -- the .cpp for linking.
> qt module: add qresource support to compile_translations

- docs/markdown/snippets/aix.md
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/environment.py
- mesonbuild/linkers.py
- mesonbuild/mesonlib.py
This patch series is enough to get simple AIX builds working with gcc. More complex builds (eg. link_whole) might not even exist in the AIX world, although I admit I didn't look too closely because I don't need those things myself. Support for the xlC compiler and AIX-style fat libraries are intentionally omitted. AIX intentionally not added to the documentation due to these omissions. I'm happy to add a patch that adds AIX to the docs if you like.
I baked both build_rpath and install_rpath in at build time because AIX uses XCOFF (not ELF), so I didn't know if the meson built-in rpath install adjustment would work.
Suggestions for improvement appreciated.
> Add AIX support

- mesonbuild/compilers/mixins/clike.py
- run_unittests.py
This typo happened in https://github.com/mesonbuild/meson/pull/7432 and wasn't noticed because I didn't add a test for it. Rectified now.
If we don't specify the CRT, MSVC will pick `/MT` by default (!?) and link to `libcmt.lib`. This actually *breaks* UWP because `libcmt.lib` is not available by default when building for UWP.
Was noticed here: https://github.com/cisco/libsrtp/pull/505
> Fix typo when fetching buildtype option for compiler checks

- mesonbuild/compilers/d.py
- run_unittests.py
Commit 93c3ec7e introduced a new way to handle deduplication with
compiler args. This resulted in D includes to be reversed.
See #7654
> D: fix include order

- mesonbuild/mcompile.py
The `--verbose` has been added to ninja in 1.9.0 and we pretend that we have compatibility with Ninja 1.7+.
References: https://github.com/ninja-build/ninja/commit/bf7517505ad1def03e13bec2b4131399331bc5c4
> mcompile: use -v instead of --verbose for ninja

- mesonbuild/envconfig.py
- mesonbuild/environment.py
- mesonbuild/mesonlib.py
- mesonbuild/mtest.py
- mesonbuild/scripts/meson_exe.py
- test cases/common/215 link custom/custom_stlib.py
This removes the check for "mingw" for platform.system(). The only case I know
where "mingw" is return is if using a msys Python under a msys2 mingw environment.
This combination is not really supported by meson and will result in weird errors,
so remove the check.
The second change is checking sys.platform for cygwin instead of platform.system().
The former is document to return "cygwin", while the latter is not and just
returns uname().
While under Cygwin it uname() always starts with "cygwin" it's not hardcoded in MSYS2
and starts with the environment name. Using sys.platform is safer here.
Fixes #7552
> Be stricter when detecting Windows/Cygwin

- docs/markdown/Builtin-options.md
The -Doption=value style argument works for all builtin options,
and compiler options passed to meson. And some universal options,
have additional ways to be passed. However, base options (and compiler
options) do not have exactly the same ways of passing as universal
options.
This change adds a few pieces of information, which might get lost,
if the manual is not read serially.
Please See #7633 for reference.
> Clarify the use of -Doption and alternatives for Builtin options passed as arguments [skip ci]

- mesonbuild/cmake/interpreter.py
- test cases/cmake/8 custom command/subprojects/cmMod/CMakeLists.txt
- test cases/cmake/8 custom command/subprojects/cmMod/cpyTest.cpp
- test cases/cmake/8 custom command/subprojects/cmMod/cpyTest/cpyTest5.hpp
Fixes: https://github.com/mesonbuild/meson/issues/7666
Meson will then just assume directories of generated files will appear during build.
> CMake module: Allow paths of generated CMake sources for include directories

- mesonbuild/mcompile.py
This matches `meson test`, and there's really no other meaning that could be attributed to this, since you would call `meson` to get the version, not the `compile` sub-command.
> mcompile: Also support -v for verbose

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
extra_paths only matter for the host machine if using an exe_wrapper.
However, because CustomTarget.for_machine is always MachineChoice.HOST,
they were computed unnecessarily in as_meson_exe_cmdline.
Defer computation of extra_paths until after we have found out if the
custom target executable is really for the host or the build machine,
so that we can use exe_for_machine; for_machine then becomes unused
and can be removed.
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
> backends: do not look for extra paths unnecessarily

- docs/markdown/Builtin-options.md
I seem to have accidentally discovered Meson build-in option `cpp_std` can expect `c++2a` as one of its values. Hopefully, this will help other C++ developers know this can happen.
> Add some forgotten values for "cpp_std" [skip ci]

- mesonbuild/mesonmain.py
- mesonbuild/mlog.py
This will be printed in bold at the end of interactive meson sub-commands that won't be parsed by a program. Specifically: setup, compile, test, and install.
`NOTICE: You are using Python 3.5 which is EOL. Starting with v0.57, Meson will require Python 3.6 or newer`
> Add a notice about Python 3.5 support

- mesonbuild/environment.py
- test cases/cuda/13 cuda compiler setting/meson.build
- test cases/cuda/13 cuda compiler setting/nativefile.ini
- test cases/cuda/13 cuda compiler setting/prog.cu
This fixes the mystery `ERROR:` exception that gets raised when setting `cuda = ` in a cross configuration file.
This resolve the cross-build setup issue described [here](https://github.com/OE4T/meta-tegra/issues/409), and should resolve #5791.  With this change and appropriate flag settings in the CUFLAGS environment variable, cross-building CUDA applications works in a Yocto-based cross-build setup.
> environment: do not raise exception in detect_cuda_compiler

- mesonbuild/interpreter.py
- mesonbuild/interpreterbase.py
- run_unittests.py
- test cases/unit/82 meson version compare/meson.build
when that statement gets evaluated, the interpreter remembers the
version target and if it was part of the evaluation of a `if` condition
then the target meson version is temporally overriden within that
if-block.
Fixes: #7590
> Special case meson.version().version_compare() statement

- mesonbuild/dependencies/base.py
cmake: Don't link DEBUG to CRT when not building with MSVC
is_debug doesn't just control the CRT, it also controls the 'debug
configuration' which is unrelated to the CRT setting on non-MSVC.
Fixes https://github.com/mesonbuild/meson/issues/7631
> cmake: Don't link DEBUG to CRT when not building with MSVC

- mesonbuild/scripts/symbolextractor.py
I can't reproduce this, but it is definitely possible. In this case what we should do is the same as when the tool is not found.
Fixes https://github.com/mesonbuild/meson/issues/7605
> symbolextractor: Handle PermissionError when running tool

- docs/markdown/IDE-integration.md
- docs/markdown/snippets/introspect_test_deps.md
- mesonbuild/backend/backends.py
- mesonbuild/mintro.py
- run_unittests.py
- test cases/unit/57 introspection/cp.py
- test cases/unit/57 introspection/meson.build
Add the paths to the dependencies, as computed by the backend, to the introspection data for tests and benchmarks.  Without this information, IDEs must update the entire build before running any test.  They can now instead selectively build the test executable itself and anything that is needed to run it.
> introspect: add target ids for executable/args/depends to test and benchmark JSON

- mesonbuild/backend/ninjabackend.py
- mesonbuild/environment.py
- mesonbuild/mcompile.py
- mesonbuild/mdist.py
- mesonbuild/minit.py
- mesonbuild/mtest.py
- mesonbuild/scripts/scanbuild.py
This allows the NINJA environment variable to support all the Windows special
cases, especially allowing an absolute path without extension.
Based on a patch by Yonggang Luo.
Fixes: #7659
> environment: use ExternalProgram to find ninja

- docs/markdown/Reference-manual.md
Documentation of most methods mentions method arguments enclosed in parentheses. Two methods are an exception and we fix them here to make the manual more consistent.
> doc: Add missing method arguments

- .github/workflows/ci_frameworks.yml
- .github/workflows/lint_mypy.yml
- .github/workflows/os_comp.yml
The "unused_args" CI .yml was updated in #7689
This just uses the latest Actions recommended by Github and removes redundant variables "CI" that are already global by default now.
> ci: update to use latest recommendations

- mesonbuild/dependencies/base.py
- run_unittests.py
```
Fix picking up tools with args from the env on Windows
This was a regression in https://github.com/mesonbuild/meson/pull/7059.
We do not need to do a full search for all windows special cases. We
only want to check whether the command provided is actually a full
path to a script so we can add the interpreter.
```
Fixes https://github.com/mesonbuild/meson/issues/7645
```
Add some type hints to the ExternalProgram class
```
> Fix searching of tools such as windres via the env on Windows

- mesonbuild/minstall.py
We don't run any further scripts when this happens, so we need to print a big error. The exit code was already correct.
Fixes https://github.com/mesonbuild/meson/issues/7627
The output now looks like:
```
$ /c/projects/meson/meson.git/meson.py install -C _build
ninja: Entering directory `_build'
ninja: no work to do.
Running custom install script 'bash C:/projects/tmp/install-script-subdir/main/subdir/my_module/scripts/install.sh'
I WAS RUN
FAILED: install script 'bash C:/projects/tmp/install-script-subdir/main/subdir/my_module/scripts/install.sh' exit code 1, stopped
```
> minstall: Print a big FAILED when a script fails

- mesonbuild/ast/interpreter.py
- test cases/unit/57 introspection/meson.build
Something like {a: foo} currently stymies the IntrospectionInterpreter and breaks introspection of the source directory.  The fix is just to walk the keys and return a dummy dictionary.
> IntrospectInterpreter: allow dictionaries with nonconstant keys

- run_tests.py
Since 492afe50, detect_ninja() returns a List[str], not a str.
run_project_test.py still happens to work under CI, as we bypass detect_ninja(), but fails when run locally, as we try to exec() that list.
```
Checking that building works...
File "./run_project_tests.py", line 1301, in <module>
check_meson_commands_work(options)
File "./run_project_tests.py", line 1190, in check_meson_commands_work
pc, o, e = Popen_safe(compile_commands + dir_args, cwd=build_dir)
File "/wip/meson/mesonbuild/mesonlib.py", line 1220, in Popen_safe
stdout=stdout, stderr=stderr, **kwargs)
File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
restore_signals, start_new_session)
File "/usr/lib/python3.6/subprocess.py", line 1278, in _execute_child
executable = …
```
> Fix run_project_test.py when not under CI

- mesonbuild/backend/backends.py
- mesonbuild/coredata.py
- mesonbuild/mtest.py
Same as coredata.dat and build.dat loading
Fixes https://github.com/mesonbuild/meson/issues/7613
> mtest: Check version in the test data after loading

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/minstall.py
- mesonbuild/mtest.py
```
mtest: Refactor test data checking
```
```
minstall: Add version field to install data
And check the install data in the same way that mtest checks
serialisation data.
```
Fixes https://github.com/mesonbuild/meson/issues/2354
> minstall: Add version field to install data

- docs/markdown/Subprojects.md
- docs/markdown/snippets/subprojects_update.md
- mesonbuild/mesonlib.py
- mesonbuild/msubprojects.py
- mesonbuild/wrap/wrap.py
Besides refactoring code into smaller functions:
- Makes the --rebase behaviour the default for consistency: it was
already rebasing when current branch and revision are the same, it is
less confusing to rebase when they are different too.
- Add --reset mode that checkout the new branch and hard reset that
branch to remote commit. This new mode guarantees that every
subproject are exactly at the wrap's revision.
- Local changes are always stashed first to avoid any data loss. In the
worst case scenario the user can always check reflog and stash list to
rollback.
Fixes: #7526
> msubprojects: Rework update command

- mesonbuild/backend/backends.py
This reverts commit 8ee1c9a07a3a35e3ed262fbc358fd86c257a966e.
No rationale was given for this change prior to merging. After the fact it was described as desired by distro packagers, however as a distro packager I believe this commit hurts me.
From a distro packaging perspective, we primarily care about one thing: previously building code should still build. Hence, -Werror is bad for our use case. meson handles this via -D werror which is different from -D warning_level and as long as the former is disabled, warnings in the build do not cause harm (but may attract review attention for upstream to fix).
buildtype is a completely unrelated concern, and the intention for =plain is to disable debug or optimization settings that result in codegen differences and thus different built artifacts. …
> Revert "Do not automatically set warning flags if buildtype is 'plain'"

- run_unittests.py
```
unit tests: Don't use pytest when running single tests
On my machine this spawns 24 processes and then runs like the single
test I asked it to run. With this change, running a single test goes
from 7 seconds to less than a second.
```
```
unit tests: Print total time taken for running tests
```
Split out from https://github.com/mesonbuild/meson/pull/7021.
> unit tests: Don't use pytest when running single tests

- mesonbuild/backend/vs2010backend.py
- "Go To Document" action previously only worked on c/cpp files which had the include directories set but it was not possible to move from header to another header.
Fixes same thing as in https://github.com/mesonbuild/meson/pull/7385
> backend/vs: Add include directories to projects as well

- mesonbuild/environment.py
This fixes an issue essentially identical to #6757, except affecting users of the Korean locale (and possibly a different version of MSVC, if the claim in sthagen/meson#64 is to be believed). The fix involves allowing closing parenthesis to terminate the architecture substring, beside space and EOL. The signature line this adds support for is:
```
Microsoft (R) C/C++ 최적화 컴파일러 버전 19.27.29111(x64)
```
> Fix Korean MSVC compiler target arch detection

- mesonbuild/mcompile.py
- mesonbuild/msetup.py
I wrote this to convert `run_tests.get_backend_commands()` over to the new meson wrappers, but that turned out to be harder than I expected, so just splitting this out for now.
> mcompile: Add some basic XCode support

- azure-pipelines.yml
This should use the package database from the installer,
from the release choco provides and result in fewer potential
changes overall.
> CI: don't update MSYS2

- cross/ccomp-armv7a.txt
- docs/markdown/Reference-tables.md
- docs/markdown/snippets/add_compcert_compiler.md
- mesonbuild/compilers/__init__.py
- mesonbuild/compilers/c.py
- mesonbuild/compilers/mixins/compcert.py
- mesonbuild/environment.py
- mesonbuild/linkers.py
Hello Meson developers! I added some basic/preliminary support for the [CompCert C Compiler](https://github.com/AbsInt/CompCert).
The code is essentially a copy of the XC16 code, plus some adaptions.
From my perspective the most questionable behaviour is the automatic filtering of some GCC flags:
CompCert uses GCC as preprocessor, assembler and linker. Hence many GCC flags are supported, but need to be prefixed with a `-WUl,` [linker], `-Wp,` [preprocessor] or `-Wa,` [assembler] for CompCert's driver to pass them to the correct tool.
Since my current objective is to evaluate [picolibc](https://github.com/picolibc/picolibc), I automatically prefix those flags which are used by picolibc's build files.
Additionally, some GCC flags are safe to be ignored by CompCert (such as the …
> Add support for the CompCert C Compiler

- mesonbuild/envconfig.py
It doesn't return (None, None), it returns just None.
> envconfig: fix return type of get_env_var_pair

- mesonbuild/build.py
[This commit (from Aug 2019)](https://github.com/pexip/meson/commit/a58ae49b5fa67a22d4861439db034b03e29b675b#diff-8298ed52ef750c466e88a3a6708d3586R2101) introduced a fix where it's possible to link with custom targets having one of a limited set of file extensions, covering the standard file extensions used by ELF static and dynamic link libraries, PE static and dynamic libs, and Mach-O static libraries.
This PR adds the extension used by MacOS for Mach-O dynamic link libraries (`.dylib`) to the allowed link list; in this way it's possible to link to a custom step producing a dynamic link library on MacOS.
*(PR opened in draft in order to check CI)*
> Fixed MacOS dylib custom targets not marked as linkable

- mesonbuild/compilers/mixins/visualstudio.py
If the architectures are taken from the output of "clang-cl --version",
we need to convert these names into names that the MSVC tools accept
as the -machine: parameter.
> Canonicalize target architectures aarch64/armv* into arm64/arm for MSVC tools

- mesonbuild/modules/windows.py
When building with vs2019 (not ninja), a path length error will be thrown
if the path to a resource file is even remotely deep within the tree.
This is largely because the target name includes the string "Windows
resource for file 'full path'", which is then expanded twice (once for
the .vcxproj itself, and once for IntDir) and added to the full path.
When combined with the tiny path limits on Windows, it is easy to exceed
path limits.
This error is largely avoided by the ninja back-end. Unlike the
vs back-end, the ninja back-end does not use target.get_id() as part of
the project file path, nor does it use target.get_id() as part of
get_target_private_dir().
Example error:
error MSB4184: The expression "[MSBuild]::NormalizePath( …
> windows: reduce chance of going over path limit in backend/vs

- run_tests.py
- run_unittests.py
I noticed a few places where we really should be using mock to handle monkey patching, but we're not and doing it by hand.
> smarter monkey patching in tests

- mesonbuild/backend/ninjabackend.py
With certain cross compilation wrappings of MSVC, the paths use backslashes, but without the leading drive name, so allow the path to start with any path separator.
> Support identifying msvc dependency prefix with a path starting with a backslash

- mesonbuild/compilers/mixins/clike.py
- mesonbuild/linkers.py
Some fixes for #7674:
1. Like with gcc's `ld`, also use the `group_start` code to create a
`--start-group`/`--end-group`
2. xc16 tricked into believing the 'link_whole' was about `--*-group`,
but it should use gcc's `--whole-archive` instead.
3. Not clear what the get_lib_prefix should really do, but for picolibc
it seems I want just `''`.
The problem with picolibc was that the `-l` would be prefixed to a lib
like `picolib/libm/libm.a`. Though of course the `-l` would be necessary
for just a plain `m` (that's what I assumed this would be used for).
I think this might need some clarification from the meson devs ;-)
> Some fixes for CompCert

- test cases/frameworks/1 boost/meson.build
Used to fixes https://github.com/mesonbuild/meson/runs/1152511331
```
2020-09-23T01:25:14.7849070Z
2020-09-23T01:25:14.7849592Z 1/5 Boost linktest      TIMEOUT        30.16s
2020-09-23T01:25:14.7849811Z
2020-09-23T01:25:14.7850027Z --- command ---
2020-09-23T01:25:14.7850281Z 01:24:30 D:\a\1\s\b 125f976e40\linkedexe.exe
2020-09-23T01:25:14.7850561Z -------
2020-09-23T01:25:14.7850693Z
2020-09-23T01:25:14.7850947Z 2/5 Boost UTF test      TIMEOUT        31.15s
2020-09-23T01:25:14.7851141Z
2020-09-23T01:25:14.7851347Z --- command ---
2020-09-23T01:25:14.7851580Z 01:24:30 D:\a\1\s\b 125f976e40\utf.exe
2020-09-23T01:25:14.7851862Z --- stdout ---
2020-09-23T01:25:14.7852065Z Running 1 test case...
2020-09-23T01:25:14.7852441Z
```
Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>
> Fixes meson test timeout on windows

- CODEOWNERS
strangely enough the syntax is:
/foo/* (files in foo, but not in foo/dir/)
/foo/ (files in foo and any subfolder of foo (recursively)
> CODEOWNERS: don't use * [skip ci]

- docs/markdown/Custom-build-targets.md
- docs/markdown/Reference-manual.md
Add a note about the portability of using shell constructs in the custom_target() command.
Even after this change, there's some conflict between these different parts of the documentation, and it's a bit unclear what the intent is.
We say only a single command is _permitted_, but don't do anything to enforce that, and take steps in the ninja backend to make `&&` work as expected (so of course, people end up using it).
https://github.com/mesonbuild/meson/blob/dff40ca259c396568eeb4d05c534781ca148f8e7/mesonbuild/backend/ninjabackend.py#L178-L180
> Improve documentation about using shell in custom_target()  [skip ci]

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/deprecate_source_build_root.md
- mesonbuild/interpreter.py
- mesonbuild/interpreterbase.py
- test cases/common/227 fs module/meson.build
- test cases/common/227 fs module/subdir/meson.build
- test cases/common/227 fs module/subprojects/subbie/meson.build
- test cases/common/227 fs module/subprojects/subbie/subsub/meson.build
Those function are common source of issue when used in a subproject because they
point to the parent project root which is rarely what is expected and is a
violation of subproject isolation.
> Deprecate meson.build_root() and meson.source_root()

- mesonbuild/backend/backends.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/compilers/mixins/visualstudio.py
- Fixed that VS backend does not create pdb files if buildtype=release.
Before VS implicitly added the debug args since they were not specified (/Zi and /DEBUG).
- Fix that it is possible to add debug info with ninja backend with
optimizations.
- Use same optimization flags when specififying buildtype or optimization. Before it was not possible to get e.g. /Ob2 optimization without buildtype=release
> compilers/VS: fix build to use optimization and debug flags

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/scripts/meson_exe.py
- test cases/failing build/5 failed pickled/meson.build
*  Improve the description used with ninja for meson wrapped custom commands
* Make `meson --internal exe --unpickle` report the actual command executed when it fails, which is otherwise invisible (e.g. https://github.com/mesonbuild/meson/pull/3716#issuecomment-395746838)
before
```
$ ninja -C _build
ninja: Entering directory `_build'
[1/1] Generating failure with a meson_exe.py custom command
FAILED: output.txt
/usr/bin/python3 /wip/meson/meson.py --internal exe --unpickle '/wip/meson/test cases/failing build/5 failed pickled/_build/meson-private/meson_exe_false_390bef2b03aeece2173ed5a4efdf9daddc71b21d.dat'
ninja: build stopped: subcommand failed.
```
after
```
$ ninja -C _build
ninja: Entering directory `_build'
[1/1] Generating failure with a custom command (wrapped by meson to capture …
```
> Improve the output for meson wrapped commands

- .github/workflows/ci_frameworks.yml
- docs/markdown/Dependencies.md
- docs/markdown/snippets/hdf5_dependnecy_improvements.md
- mesonbuild/coredata.py
- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/hdf5.py
- test cases/frameworks/25 hdf5/meson.build
- test cases/frameworks/25 hdf5/meson_options.txt
- test cases/frameworks/25 hdf5/test.json
Instead of a mega dependency that does everything, use a dependency
factory for config-tool and pkg-config
> dependencies/hdf5: Convert to a dependency_factory

- azure-pipelines.yml
- docs/markdown/Dependencies.md
- docs/markdown/snippets/curses-dependency-improvements.md
- mesonbuild/dependencies/dev.py
- mesonbuild/dependencies/misc.py
- test cases/frameworks/31 curses/meson.build
- test cases/frameworks/31 curses/meson_options.txt
- test cases/frameworks/31 curses/test.json
Like many other classic unix libraries curses is a portability pain, there's a bunch of slightly different implementations, that are found different ways. Meson already provides abstractions for making other widely available but not always easy to find libraries easier to use.
This adds all of the methods, and is tested on linux. I can test it on illumos/OpenIndiana and FreeBSD later if needed.
This doesn't resolve the fact that users will likely need to know which header they should `#include`. But that's a bigger change to dependencies.
Fixes #7693
> Extend the Curses dependency to use config tools and hand rolled search

- mesonbuild/compilers/mixins/intel.py
Intel compilers on Windows (and the Microsoft C++ compiler) use /Od to disable optimisation, not /O0.
> compilers: Use /Od for no-optimisation flag for Intel windows compilers

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/deprecate_old_variable_methods.md
- mesonbuild/interpreter.py
The get_variable method is able to do everything they do and more,
making it generally more useful. Let's tell people to stop using the old
ones.
> deprecated get_configtool_variable and get_pkgconfig_variable

- docs/markdown/Reference-manual.md
It was slightly wrong, and also made it a bullet point for easier parsing.
> docs: Fixup find_program search path documentation [skip ci]

- mesonbuild/backend/xcodebackend.py
- test cases/common/237 subdir files/meson.build
- test cases/common/237 subdir files/subdir/meson.build
- test cases/common/237 subdir files/subdir/prog.c
I ran into bug #589 recently, and I looked into it and the fix is simple enough: when converting from a `mesonlib.File` object to a string, it didn't take subdirs into account, which is fixed by doing a `os.path.join(s.subdir, s.fname)`. 
I looked through the test case folder and couldn't find anything in `common/` that specifically tested for this (though I might have just missed it, there's a lot of tests in there), so I added a new test for this specific bug. 
This is my first time contributing to meson, please let me know if I did anything wrong :)
> Fix xcode subdir files

- mesonbuild/linkers.py
Projects that specify b_pie=true clutter build logs with the warning:
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
No option is needed to produce PIE binaries because ld64 is making PIE
executables on 10.7 and above by default, as documented in ld(1).
Signed-off-by: Roman Bolshakov <r.bolshakov@yadro.com>
> linkers: Drop -pie on macOS

- docs/markdown/Machine-files.md
- docs/markdown/snippets/machine-files-case-insensitve.md
- mesonbuild/coredata.py
- run_unittests.py
- test cases/common/43 options/meson.build
- test cases/common/43 options/meson_options.txt
This is required to make the various keys in the [user options] section
work the same as they do in the meson_options.txt file, where we don't
have any rules about case sensitivity.
There is some risk here. Someone may be relying on this lower by default
behavior, and this could break their machine files.
Fixes #7731
> machinefiles: Allow keys to be stored case insensitive

- mesonbuild/scripts/clangformat.py
- mesonbuild/scripts/clangtidy.py
- run_unittests.py
- test cases/unit/54 clang-format/dummydir.h/dummy.dat
- test cases/unit/70 clang-tidy/dummydir.h/dummy.dat
Currently the auto-generated `clang-format` target fails when the source directory contains a directory matching one of the `lang_suffixes`, e.g. a directory named `test.h/`. This is due to `pathlib.Path.glob()` not only returning files but also returning directories.
Both `clang-format` and `clang-tidy` fail when handed a directory. This PR explicitly checks if the "file" to check is actually a directory and skips calling `clang-format` and `clang-tidy` for those. Unit tests have been adapted accordingly.
> Never run clang-format / clang-tidy against directories

- mesonbuild/coredata.py
- run_unittests.py
- test cases/unit/84 change option choices/meson.build
- test cases/unit/84 change option choices/meson_options.1.txt
- test cases/unit/84 change option choices/meson_options.2.txt
Currently if you change the `choices` field in the meson_options.txt
file, no update will be done until `meson setup --wipe` is called. Now
if the choices change then the options will be properly merged.
If the currently select value is still valid it is guaranteed to be
kept, if it is now invalid the new default value will be used and a
warning will be printed.
Fixes #7386
> options: Handle updates to choices in options

- mesonbuild/compilers/cpp.py
Intel C++ Compiler 19.1 has C++20 features.
https://software.intel.com/content/www/us/en/develop/articles/intel-c-compiler-191-for-linux-release-notes-for-intel-parallel-studio-xe-2020.html
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
> compilers: Enable C++20 for Intel C++ Compiler.

- mesonbuild/environment.py
Just saying "it failed" is accurate, but not useful to helping someone
figure out why it failed. Giving them the stdout and stderr (like we
might with compilers) should help people resolve the issue.
Fixes: #7173
> environment: provide a more detailed explanation of linker detection failures

- test cases/unit/39 python extmodule/meson.build
It used to ignore the required argument and got fixed to be consistent
with dependency() function.
> Tests: py.dependency() now has required:true by default

- mesonbuild/build.py
- test cases/common/215 link custom/custom_target.c
- test cases/common/215 link custom/custom_target.py
- test cases/common/215 link custom/dummy.c
- test cases/common/215 link custom/meson.build
- test cases/common/215 link custom/outerlib.c
Continuation of #6367, fixes #6365.
I had to implement both `is_internal` and `extract_all_objects_recurse` in the end because they're needed later during execution. It works as is, but I'm not sure it's correct @nirbheek.
The test initially called `echo dummy` as an external command but this fails on windows, so I figured python should be OK instead.
> Custom target link

- mesonbuild/mtest.py
First introduced here: 8da1b29899e795d87f0a4e51adb532119af48727
> mtest: collect failures regardless of colorized console

- docs/markdown/Reference-manual.md
- docs/markdown/Wrap-dependency-system-manual.md
- docs/markdown/snippets/fallback_bool.md
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter.py
- test cases/common/239 dependency allow_fallback/meson.build
- test cases/common/239 dependency allow_fallback/subprojects/foob/meson.build
- test cases/common/239 dependency allow_fallback/subprojects/foob3/meson.build
- test cases/failing/110 no fallback/meson.build
- test cases/failing/110 no fallback/subprojects/foob/meson.build
- test cases/failing/110 no fallback/test.json
Sometimes, distros want to configure a project so that it does not use any bundled library.  In this case, `meson.build` might want
to do something like this, where slirp is a combo option with values auto/system/internal:
slirp = dependency('', required: false)
if get_option('slirp') != 'internal'
slirp = dependency('slirp',
required: get_option('slirp') == 'system')
endif
if not slirp.found()
slirp = subproject('libslirp', ...) .variable('...')
endif
Note that we cannot use "fallback" because the "system" value should never look for a subproject.
This worked until 0.54.x, but in 0.55.x this breaks because of the automatic subproject search.  In fact the desired effect here is backwards compared to the policy of doing an automatic search on `required: true`; instead we only want to do …
> Allow blocking/forcing automatic subproject search

- mesonbuild/scripts/clangtidy.py
by default run_clang_tidy process al file in compile_commands.json but
the file generated has to be esclude like already done from
manual_clangformat
> esclude generate file from clang-tidy processing

- ci/ciimage/.gitignore
- ci/ciimage/arch/install.sh
- ci/ciimage/build.py
- ci/ciimage/fedora/install.sh
- mesonbuild/dependencies/cuda.py
Updates the install scripts to account for changes in Arch and Fedora.
Also fixes the CUDA version detection in absence of a `/path/to/cuda/version.txt` file by looking for `CUDART_VERSION` in `cuda_runtime_api.h`.
Generally, it should be checked before each release that the last scheduled (Sunday night) [CI image builder job](https://github.com/mesonbuild/meson/actions?query=workflow%3A%22CI+image+builder%22) is green. A red job could indicate a failed test run in an up-to-date system.
> ci: fix broken CI images

- docs/markdown/snippets/mtest_test_list_subprojects.md
- mesonbuild/interpreter.py
- mesonbuild/mtest.py
You could always specify a list of tests to run by passing the names as arguments to `meson test`. If there were multiple tests with that name (in the same project or different subprojects), all of them would be run. Now you can:
1. Run all tests with the specified name from a specific subproject: `meson test subprojname:testname`
1. Run all tests defined in a specific subproject: `meson test subprojectname:`
Also forbid ':' in test names. We already forbid this elsewhere, so should not be a big deal.
> mtest: Allow filtering tests by subproject

- docs/markdown/CMake-module.md
- docs/markdown/snippets/cmake_include_type.md
- mesonbuild/interpreter.py
- mesonbuild/modules/cmake.py
- test cases/cmake/1 basic/meson.build
- test cases/common/226 include_type dependency/meson.build
Fixes that `include_type` is ignored for dependency fallbacks and adds the `include_type` kwarg to the CMake subproject `dependency()` method.
> include_type fixup

- docs/markdown/Builtin-options.md
- mesonbuild/backend/vs2010backend.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/mixins/visualstudio.py
I compile my code with the static CRT, to simplify deployment.
I was using `b_vscrt=mt`. I recently tried to add `-D_DEBUG` to my debug builds, but my code failed to link because `mt` does not export all the required symbols. `from_buildtype` is almost what I wanted, except from_buildtype always links with the DLL CRT.
It's not clear if `static_from_buildtype` is the correct way to go about this, but it's a starting point for discussion.
(Note that I snuck in a fix for backend=vs when using `from_buildtype` and `buildtype=debugoptimized` -- meson previously generated MultiThreaded (non-dll), which did not match ninja or the documentation)
> vs: add static_from_buildtype to b_vscrt

- docs/markdown/Pkgconfig-module.md
- docs/markdown/Reference-manual.md
- docs/markdown/snippets/pkg_idep_variables.md
- mesonbuild/interpreter.py
- mesonbuild/modules/pkgconfig.py
- run_unittests.py
- test cases/common/218 dependency get_variable method/meson.build
- test cases/common/47 pkgconfig-gen/meson.build
- test cases/failing/47 pkgconfig variables zero length/test.json
- test cases/failing/48 pkgconfig variables zero length value/test.json
- test cases/failing/49 pkgconfig variables not key value/test.json
Share common code to extract the `variables` kwarg in
declare_dependency() and pkg.generate().
> Fix consistency in variables kwarg

- mesonbuild/compilers/cuda.py
- test cases/cuda/14 cuda has header symbol/meson.build
Header symbol checks for the CUDA compiler are broken (#7825) because the check was taken from the C++ compiler code. This doesn't work because `CPPCompiler` derives from `CLikeCompiler`, which implements C preprocessor checks in `has_header_symbol`, while `CudaCompiler` derives from `Compiler`, whose `has_header_symbol` throws.
This PR fixes these problems by:
- Not calling `super.has_header_symbol` anymore.
- Checking for C preprocessor macros. (with code copied from `CLikeCompiler`)
> compilers/cuda: Fix has_header_symbol check

- mesonbuild/ast/introspection.py
- mesonbuild/compilers/compilers.py
- mesonbuild/coredata.py
- mesonbuild/environment.py
- mesonbuild/interpreter.py
- mesonbuild/mconf.py
- run_unittests.py
- test cases/common/90 default options/meson.build
- test cases/common/90 default options/subprojects/sub1/meson.build
- test cases/common/90 default options/subprojects/sub1/meson_options.txt
This solves spurious warnings I reported in #6597, fix a regression reported in #7573, and make behaviour of PKG_CONFIG_PATH consistent with other env like CFLAGS.
> Refactor handling of machine file options

- mesonbuild/cmake/__init__.py
- mesonbuild/cmake/common.py
- mesonbuild/cmake/interpreter.py
- mesonbuild/dependencies/base.py
To avoid confilcts with the meson CMake logic (especially regarding the changes in #7816) some CMake variables should not be passed by the user (especially not in a `meson.build`). With this PR internally used CMake variables set by the user are ignored and a warning is printed.
> cmake: ignore CMAKE_TOOLCHAIN_FILE and CMAKE_PROJECT_INCLUDE

- mesonbuild/modules/pkgconfig.py
- run_unittests.py
This fixes a regression introduced by
https://github.com/mesonbuild/meson/pull/7488.
InternalDependency's ext_deps previously where simply ignored, but that
PR has effect to add many more public Requires in generated pc files.
> pkgconfig: InternalDependency's ext_deps should be private by default

- mesonbuild/modules/gnome.py
- test cases/failing/105 no glib-compile-resources/test.json
When glib is a subproject we should use glib-compile-resources it
overrides using find_program() in the case it is not installed on the
build machine. With old glib version we have to run
glib-compile-resources at configure time to generate the list of
dependencies, but not when glib is recent enough.
> Fix gnome.compile_resources() when glib is a subproject

- mesonbuild/backend/backends.py
- mesonbuild/build.py
If `static_library` is used for a convenience library (e.g. for link_whole), the library should in principle not need position independent code. However, if the executables that the libraries is linked to are PIE, the non-PIC objects in the static library will cause linker errors. To avoid this, obey `b_pie` for static libraries if either `b_staticpic=false` or they use `pic: false`.
Without this patch, a project that only uses static libraries as convenience libraries cannot use `b_staticpic=false`, because the correct setting would be, so to speak, `b_staticpic=$b_pie`. This causes a massive slowdown on some QEMU benchmarks (up to 20%). We can work it around for now while we still have wrappers upon wrappers around Meson, but in the long run this should be fixed.
But actually, this …
> build: use PIE objects for non-PIC static libraries if b_pie=true

- run_unittests.py
The other invocations below this one also do DEVNULL.
> Remove a status message that leaks to stdout.

- mesonbuild/environment.py
fixes machine detection for
power macintosh systems
> fix typo "machintosh" -> "macintosh"

- docs/markdown/Reference-manual.md
- mesonbuild/build.py
- mesonbuild/interpreter.py
The deprecation message for "gui_app" is appearing for every target
rather than just once, and even if the required version is older
than 0.56.0.  Use @FeatureDeprecatedKwargs to fix both issues.
> switch gui_app deprecation to FeatureDeprecatedKwargs

- mesonbuild/interpreter.py
I noticed this when reviewing #7872
> interpreter: Add missing new feature flag for executable(win_subsystem)

- mesonbuild/modules/pkgconfig.py
This fixes glib-2.0-uninstalled.pc file.
GLib does `extra_cflags : ['-I${libdir}/glib-2.0/include']` because some
of its headers gets installed there. But when used uninstalled that path
makes no sense and pkg-config aborts because ${libdir} is not defined.
This cannot be worked around by GLib because Meson does not allow
setting different `extra_cflags` for -uninstalled.pc, and does not allow
setting libdir in `uninstalled_variables`.
> pkgconfig: Define libdir and includedir in -uninstalled.pc files

- mesonbuild/dependencies/dev.py
- run_project_tests.py
- test cases/frameworks/15 llvm/meson.build
- test cases/frameworks/15 llvm/meson_options.txt
- test cases/frameworks/15 llvm/test.json
> depenencies/llvm: Handle llvm-config --shared-mode failing

- mesonbuild/cmake/data/preload.cmake
- mesonbuild/cmake/interpreter.py
- mesonbuild/cmake/traceparser.py
- mesonbuild/mesondata.py
- test cases/cmake/1 basic/subprojects/cmMod/CMakeLists.txt
- test cases/cmake/1 basic/subprojects/cmMod/cpp_pch.hpp
- tools/gen_data.py
Both commits don't add new functionality and should be OK for 0.56.0
---
cmake: Always create missing includes in build dir
There really isn't any reason to not always create missing
include directories inside the build dir. Just restricting
this to generate generated sources should work in an ideal
world, however, there exists lots of suboptimal CMake code
where this assumption is not always true.
---
cmake: Disable the new (CMake 3.16) PCH support
Subprojects that use the CMake PCH feature will cause
compilation/linker errors. The CMake PCH support
should thus be disabled until this can be properly
translated to meson.
> cmake: some subproject related fixes

- mesonbuild/environment.py
Apparently in some cases swift prints to stderr instead of stdout
> environment: Fix detection of swift linker

- setup.cfg
We have a single giant file for our tests, but a number of files that
match pytest's default discovery globs. To fix that, let's tell pytest
what to do.
This means you can just `pytest` and get the right results. It also
helps IDE's like vscode correctly identify tests.
> setup.cfg: Add pytest discovery args

- mesonbuild/dependencies/ui.py
When finding the Qt compilation tools (moc, uic, rcc, lrelease), the
version strings contain a trailing newline character. This results in a
stray newline in the meson log:
Detecting Qt5 tools
Program /usr/lib64/qt5/bin/moc found: YES 5.14.2
(/usr/lib64/qt5/bin/moc)
Program /usr/lib64/qt5/bin/uic found: YES 5.14.2
(/usr/lib64/qt5/bin/uic)
Program /usr/lib64/qt5/bin/rcc found: YES 5.14.2
(/usr/lib64/qt5/bin/rcc)
Program /usr/lib64/qt5/bin/lrelease found: YES 5.14.2
(/usr/lib64/qt5/bin/lrelease)
Strip the version to avoid this, resulting in a cleaner log:
Detecting Qt5 tools
Program /usr/lib64/qt5/bin/moc found: YES 5.14.2 (/usr/lib64/qt5/bin/moc)
Program /usr/lib64/qt5/bin/uic found: YES 5.14.2 (/usr/lib64/qt5/bin/uic)
Program /usr/lib64/qt5/bin/rcc found: YES 5.14.2 …
> qt: dependency: Strip tool versions from newlines

- mesonbuild/modules/gnome.py
It's an easy mistake to do this:
gir1 = gnome.generate_gir(...)
gir2 = gnome.generate_gir(...
includes: ['GObject-2.0', gir1])
This fails with an error:
ERROR: Gir includes must be str, GirTarget, or list of them.
The issue is that the 'gir1[0]' should be passed instead of 'gir1'.
To make the problem slightly clearly, tweak the error message to be:
ERROR: Gir includes must be str, GirTarget, or list of them. Got TypelibTarget.
> gnome: Tweak error message

- data/syntax-highlighting/vim/syntax/meson.vim
We should do this because:
- Vim 5.8, the last minor release of Vim 5, came out in 2001.
- Even the runtime files maintained in the Vim repository, which are very careful about compatibility, removed Vim 5 support in 2016.
- It means less code paths and less lines of code.
Also I didn't keep the check for `did_meson_syn_inits` because I don't know what exactly that is referring to; there doesn't seem to be a variable with that name in any of the Vim scripts.
> vim: Drop backwards compatibility with Vim 5.

- mesonbuild/wrap/wrap.py
This is a regression introduced in Meson 0.56.0, it was fatal
error when optional dependencies fails to download their fallback
subproject.
> wrap: Fix git exception not catched by interpreter

- .flake8
- .pylintrc
The last instances of
try:
...
except:
...
were removed in bf98ffca. The sideci.yml file was updated, but the
flake8 config still allows this. Ensure that flake8 tests fail if this
questionable construct appears again.
> Bare exceptions are no longer allowed [NFC]

- mesonbuild/modules/pkgconfig.py
This fix a regression caused by
https://github.com/mesonbuild/meson/pull/7837, it wanted to make
InternalDependency's external_deps private but has side effect of making
StatisLibrary's external_deps private too.
It is technically correct to make them private, but Meson used to make
StaticLibrary deps public so they are usable without `pkg-config
--static` when we know there is only a static library available.
Fixes: #7929.
> pkgconfig: Make external deps of static library public

- docs/markdown/Builtin-options.md
Apparently anchor links are case-sensitive and needs to be lowercase in hotdoc.
Prior to this change the anchor links were uppercase so the link did not refer to the anchor tag.
Likely that there are more occurrences around the docs than this, have not looked.
> docs: Fix broken anchor links

- docs/markdown/snippets/rust_std_option.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/rust.py
- test cases/rust/10 language stds/2015.rs
- test cases/rust/10 language stds/2018.rs
- test cases/rust/10 language stds/meson.build
Using the std option, so now `rust_std=..` will work. I've chosen to use
"std" even though rust calls these "editions", as meson refers to
language versions as "standards", which makes meson feel more uniform.
Fixes: #5100
> rust: implement support for --edition

- docs/markdown/Reference-manual.md
- test cases/common/166 get project license/meson.build
Some license identifiers are ambiguous (e.g. "GPL3"). The SPDX license
identifiers avoid this by providing standardized and unique identifiers
(e.g. "GPL-3.0-only" or "GPL-3.0-or-later" for the previous example).
Because SPDX short-form identifiers are also both human- and
machine-readable we should recommend them in the documentation.
More information (advantages, details, etc.) can be found here:
- https://spdx.dev/resources/use/#identifiers
- https://spdx.dev/ids/
Fix #7905.
---
I've also updated the test to ensure the "-2.0" suffix won't cause any issues though this is completely optional as I don't see why it should actually cause any issue (but it seemed like a good idea regardless).
> docs: Recommend to use SPDX license identifiers

- mesonbuild/compilers/c.py
Contains commits cherry-picked from https://github.com/mesonbuild/meson/pull/7862 and https://github.com/mesonbuild/meson/pull/7866
> Fix c_std breakage in 0.56 with msvc and clang-cl for 0.56.1

- mesonbuild/scripts/clangtidy.py
In case clang-tidy is invoked manually, i.e. if run-clang-tidy(.py) is
not found, Meson would not report the return value. This is caused by
ignoring the return value of manual_clangformat() in clangformat()
within mesonbuild/scripts/clangtidy.py.
Even though only more recent-versions of clang-tidy actually report an
non-zero exit code if errors are found, there is no reason Meson
shouldn't simply report any error codes it received from clang-tidy.
Fixes #7948.
> Fix clang-tidy return value reporting

- docs/markdown/snippets/thinlto.md
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/clang.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/compilers/mixins/islinker.py
- mesonbuild/linkers.py
- test cases/common/41 options/meson.build
Dunno if changing the type of `b_lto` is bad or not. In the short term there may be a few issues, but it is "correct" in the long term.
> Add thinlto support. Closes #7493.

- mesonbuild/compilers/compilers.py
When TemporaryDirectory() cleans up on __exit__ it sometimes throws
OSError noting that the dir isn't empty. This happens after the
first yield in this generator and leads to the exception being handled
which leads to a second yield.
contextlib.contextmanager() fails then since the function it wraps is only
allowed to yield once.
Fix this by not yielding again in the error case.
Fixes #7947
> Fix "generator doesn't stop" on Windows

- mesonbuild/dependencies/base.py
- run_unittests.py
- test cases/common/231 external project/libfoo/configure
This fixes building with meson when the POSIX behavior of getopt is used (stopping at the first non-option), such as when GNU libc is used with `POSIXLY_CORRECT=1` defined.
> dependencies: Put pkgconfig options before operands

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/rust.py
rustc has color output, although it's not documented in it's help section. It uses the same values every other compiler does. Also, apply base compiler options to rust targets.
> Add color output support to rust

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/keys_of_configuration_data.md
- mesonbuild/interpreter.py
- test cases/common/14 configure file/meson.build
would be beneficial to iterate over all configuration_data keys. getter function already exists, but not made available to the user
> interpreter: Add get_keys function for configuration_data

- mesonbuild/modules/gnome.py
- run_project_tests.py
- test cases/frameworks/34 gir static lib/meson.build
- test cases/frameworks/34 gir static lib/statichelper/meson-sample.c
- test cases/frameworks/34 gir static lib/statichelper/meson-sample.h.in
- test cases/frameworks/34 gir static lib/statichelper/meson.build
- test cases/frameworks/34 gir static lib/subdir/gir/meson-subsample.c
- test cases/frameworks/34 gir static lib/subdir/gir/meson-subsample.h
- test cases/frameworks/34 gir static lib/subdir/gir/meson.build
- test cases/frameworks/34 gir static lib/subdir/gir/prog.c
- test cases/frameworks/34 gir static lib/test.json
The generate_gir() function previously assumed all library
inputs were in the current build dir. This would fail if they
weren't.
My particular use case for this fix was porting Rhythmbox to Meson. (https://gitlab.gnome.org/GNOME/rhythmbox/-/merge_requests/86). The original build system generates GIR files in the `./bindings/gi` subdir, separately from the actual library files. That doesn't work with Meson. I can work around this by building GIR files along with the libraries but ... I don't see a reason that the other approach should be broken.
> gnome: Handle libraries that are not in the current build dir

- mesonbuild/interpreter.py
The only way to add it via warning_level is top opt in to -Wextra too. But this is often not really desirable, since -Wextra is not stable -- it changes its meaning every compiler release, thus mysteriously adding new warnings. Furthermore, it's not really the same kind of warning -- a pedantic warning is always correct that your code is wrong, but defines wrongness as "not per the portable standard". Unlike -Wextra it doesn't try to judge your code to see if you're doing something that is "often not what you meant", but is prone to false positives.
Really, we need different *kinds* of warning levels, possibly as an array -- not just a monotonically increasing number. But since there's currently nothing flexible enough to specify -Wpedantic without -Wextra, we will just remove the warning …
> Do not warn when -Wpedantic is added as a project argument.

- mesonbuild/backend/ninjabackend.py
due to spaces in paths being escaped with `$ `
closes #7977
> ninjabackend: fix matching of empty strings

- mesonbuild/compilers/c.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/fortran.py
This has a nice effect on code duplication, plus ensures that all compilers expose the {lang}_std option, even if the only option is none. This prevents cases where a project says "I need gnu99" but the compiler doesn't support it, and meson acts like it does.
This also cleans up the options, as some use (incorrectly) `c_std`, when they should use just `std`
> Put the Compiler standard option in the Language mixin

- mesonbuild/compilers/c.py
- test cases/unit/59 introspect buildoptions/meson.build
MS blog post about improved C support: https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/
I have tested this change against some C code that used static_assert, and did not compile previously.
Extends pattern laid out by #7556.
> msvc: enable /std:c17 flag

- mesonbuild/modules/gnome.py
- test cases/frameworks/7 gnome/mkenums/enums.c.in
- test cases/frameworks/7 gnome/mkenums/enums2.c.in
- test cases/frameworks/7 gnome/mkenums/meson.build
- test cases/vala/8 generated sources/dependency-generated/enum-types.c.template
See https://gitlab.gnome.org/GNOME/glib/-/issues/600
`volatile` was previously mistakenly used in GLib to indicate that a
variable was accessed atomically or otherwise multi-threaded. It’s not
meant for that, and up to date compilers (like gcc-11) will rightly warn
about it.
Drop the `volatile` qualifiers.
See also http://isvolatileusefulwiththreads.in/c/.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
> gnome: Drop use of volatile in GLib type functions

- docs/markdown/Getting-meson.md
- mention installing from local sources, not PyPI
- warn against --user installs, which too often screw up users that then cannot install projects because ~/.local won't be in sudo's PYTHONPATH
- advise installing with sudo -- current versions of pip assume --user for you rather than failing with permission errors, which is great unless, like meson, there are compelling reasons to need to install as root
> doc: add much-needed accuracy to pip installation instructions [skip ci]

- mesonbuild/scripts/clangtidy.py
It turns out my first attempt to fix this in 00d5ef3191e5 ("Fix
clang-tidy return value reporting (#7949)") is not sufficient: The
local variable returncode is never updated and stays at 0. This fixes
the returncode calculation.
Fixes: cce172432be3 ("Use run-clang-tidy when available.")
> Fix clang-tidy return value reporting (Part Ⅱ)

- mesonbuild/scripts/clangformat.py
There is no reason why meson should swallow any non-zero exit(/return)
code of clang-format.
> Collect and return clang-format's return code

- mesonbuild/mlog.py
- mesonbuild/mtest.py
Introduced by ba71fde18 ("mtest: collect failures regardless of colorized console", 2020-10-12) in 0.56.0:
```
$ ../../../../meson.py test
ninja: Entering directory `/home/pbonzini/work/upstream/meson/test cases/common/1 trivial/build'
[2/2] Linking target trivialprog
1/1 runtest FAIL           0.00s (exit status 1)
Summary of Failures:
1/1 runtest FAIL           0.00s (exit status 1)
1/1 runtest FAIL           0.00s (exit status 1)
Ok:                 0   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
Full log written to /home/pbonzini/work/upstream/meson/test cases/common/1 trivial/build/meson-logs/testlog.txt
```
> failures are printed twice

- mesonbuild/backend/ninjabackend.py
- mesonbuild/depfile.py
- mesonbuild/interpreterbase.py
- mesonbuild/modules/sourceset.py
- run_unittests.py
The ordering of elements in sets and of keys in dictionaries cannot be relied upon, because the hash values are randomized by Python.  Whenever the processing of `meson.build` or the operation of the backend is affected by this ordering, random changes in the command line can occur and cause ninja to rebuild a lot of files unnecessarily.
This pull request fixes the instances that affect QEMU, and which were causing about 40% of the build to be repeated after `touch ../meson.build` (most of them due to sourcesets).
> Avoid build.ninja changes due to order of hash table iteration

- mesonbuild/mtest.py
This pull request rewrites the SingleTestRunner and TestHarness to use asyncio for subprocesses.
The main advantage is better control on cancellation; with the current code, KeyboardInterrupt was never handled by the thread executor so the code that tried to handle it in SingleTestRunner only worked for non-parallel tests.  Likewise, SIGTERM was not handled and left tests running. (In addition, if the test exited with exit status 0 in response to SIGTERM, it was not marked as a failure).
With this pull request, mtest gains a new `INTERRUPT` TestResult and SIGINT will return it for the oldest-running test. SIGTERM instead will return it for all running tests and will not start any new test. Because a picture is worth a thousand works, here are some Asciinema recordings:
* [sending SIGINT …
> [RFC] mtest: use asyncio instead of concurrency.futures

- docs/markdown/Cuda-module.md
- mesonbuild/modules/unstable_cuda.py
- test cases/cuda/3 cudamodule/meson.build
With much inspiration from CMake's [own logic](https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA/select_compute_arch.cmake).
> Update unstable CUDA Module to support newest toolkits and drivers.

- docs/markdown/Continuous-Integration.md
- docs/markdown/Release-notes-for-0.55.0.md
- docs/markdown/Release-notes-for-0.56.0.md
In most places, we now refer to "builddir/" which is a lot less likely to make people think it is a subcommand which needs to be used
literally.
This is a regression since commit 276d342ebaf859dd53e145ead3e98e2cebb360ab due to the existence of new docs which were added later on, using the wrong form.
> doc: fix confusing use of "build" as a directory argument [skip ci]

- mesonbuild/compilers/compilers.py
- mesonbuild/mesonlib.py
- run_project_tests.py
* Add a variant of TemporaryDirectory that uses windows_proof_rmtree()
* Replace various calls to AutoDeletedDir with TemporaryDirectoryWinProof
* Remove AutoDeletedDir
This was motivated by #7955
> Add a variant of TemporaryDirectory that uses windows_proof_rmtree()

- docs/markdown/snippets/compiler_method_internal_deps.md
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter.py
- test cases/linuxlike/2 external library/meson.build
Allow methods on the compiler object to receive internal dependencies, as long as they only specify compiler/linker arguments or other dependencies that satisfy the same requirements.
This is useful if you're using internal dependencies to add special "-D" flags such as -DNCURSES_WIDECHAR, -D_XOPEN_SOURCE_EXTENDED or -DGLIB_STATIC_COMPILATION.
> compiler: allow non-built internal dependencies as arguments

- test cases/common/119 llvm ir and assembly/square-aarch64.S
Tested on a Raspberry pi 4 running `2020-08-20-raspios-buster-arm64-lite`.
> Add aarch64 assembly test

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/prelink.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/gnu.py
- run_unittests.py
- test cases/unit/87 prelinking/file1.c
- test cases/unit/87 prelinking/file2.c
- test cases/unit/87 prelinking/file3.c
- test cases/unit/87 prelinking/file4.c
- test cases/unit/87 prelinking/main.c
- test cases/unit/87 prelinking/meson.build
- test cases/unit/87 prelinking/private_header.h
- test cases/unit/87 prelinking/public_header.h
This is still fairly WIP and supports only GCC.
> Add prelinking support for static libraries.

- mesonbuild/msubprojects.py
Otherwise it's not possible to share git subprojects via worktrees when creating a worktree of a git repository that uses meson subprojects.
The downside is that the user needs to be careful while adding commits to each tree's index.
> msubprojects: Ignore worktrees when checking out

- mesonbuild/mcompile.py
The ninja path is already logged as part of configure. Logging it
again every time when using meson compile is overly verbose and
doesn't add much value for the user.
> Remove "Found runner: " logging message from meson compile

- docs/meson.build
- mesonbuild/minstall.py
* All the generated "Edit on GitHub" links have a spurious "/"  `https://github.com/mesonbuild/meson//edit/master/docs/builddir/markdown/index.md`
* Installation via pkexec ignores DESTDIR
More details in the commit messages.
> Fixes to doc generation and installation

- docs/markdown/Pkgconfig-module.md
- mesonbuild/interpreter.py
This fix a regression introduced in Meson 0.56.0 when using python 3.5.
Also mention in documentation that using a meson dict does not guarantee
ordering.
Fixes: #8074.
> pkgconfig: Respect variable ordering when passed as list

- .github/workflows/macos.yml
- .github/workflows/msys2.yml
- run_unittests.py
I can't find a supported version for AppleClang, and you need relatively
recent versions of GCC and Clang for -std=c++20 to work.
> unit tests: correctly skip c++20 checks if the compiler doesn't support them

- mesonbuild/compilers/mixins/clang.py
- mesonbuild/environment.py
- mesonbuild/linkers.py
Fixes #8064
This PR adds support for using clang with a non-GNU compatible `lld` instance, which results in correct
host machine identification in cross-compilation scenarios aswell as support for using `lld-link` indirectly
through `clang` by selecting `lld` through `c_ld`.
> Add support for driving lld-link indirectly through clang on Windows

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/clang.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/linkers.py
This is more of a little cleanup amendment to #8071 which moves `get_win_subsystem_args` to the linker side
instead. `get_gui_app_args` is left mostly unchanged as both clang and gcc have special options to handle those two
subsystems directly from the compiler driver.
> Make win_subsystem a linker property

- docs/markdown/Users.md
`libspng` moved from Gitlab to Github. Update the link to point to the new location.
> docs: Update link to libspng [skip ci]

- mesonbuild/linkers.py
lld in gnu like mode (e.g. for mingw) needs these options in
the same for as gnu ld, thus remove the lld specific code bit
and move the code for gnu like options into GnuLikeDynamicLinkerMixin.
This unbreaks linking with lld for mingw targets after
2fb4d1f7512a4ec125883fd65115ab33a5b06b6f.
CC @dcbaker @e820
> Fix the subsystem options for lld in mingw mode

- docs/markdown/snippets/meson_test_depends.md
- mesonbuild/minstall.py
- mesonbuild/mintro.py
- mesonbuild/mtest.py
It is a usual workflow to fix something and retest to see if it is fixed using a particular test.  When tests start to become numerous, it becomes time consuming for "meson test" to relink all of them (and in fact rebuild the whole project) where the user has already specified the tests they want to run, as well as the tests' dependencies.
Teach meson to be smart and only build what is needed for the test (or suite) that were specified.
Fixes: #7473
> mtest: only build what is needed for the tests

- mesonbuild/mlog.py
We really want to have this in the log method as well.
Fixes: #8002
> mlog: make mlog helper take once keyword argument

- mesonbuild/environment.py
We have more than those values, like:
mipsel
mipsel-nf
mips32el
mips33el-nf
mipsisa32r6
mipsisa32r6el
So lets just detect them all.
Sorry I forgot about 64bit and closed https://github.com/mesonbuild/meson/pull/8106
But now it even detects:
mipsisa64r6
mipsisa64r6el
> environment.py: Detect all mips* architectures

- mesonbuild/linkers.py
- mesonbuild/scripts/depfixer.py
Fixes issues with RPATH handling found when updating the Solaris meson packages to 0.56.0.
The first copies code from the GNU linker class to the equivalent code in the Solaris linker class.
The second makes the handling of old rpath entries match that of new rpath entries in depfixer (#8115)
> RPATH fixes

- mesonbuild/mdist.py
The change makes `meson dist` follow the checksum format described at
https://www.gnu.org/software/coreutils/manual/html_node/md5sum-invocation.html#md5sum-invocation
and is compatible with busybox too.
I also removed the print since it doesn't make sense inside a function called
`create_hash`. It also contributes to the unnecessary output when a user runs
`meson dist`. [On my very simple project I get 55 lines of output and a few
warnings](https://0x0.st/iCOM.txt). There are other things we can do to improve
that (like calling `git` with `--quiet`) but this is a start.
I ran `AllPlatformTests.test_dist_git` and
`AllPlatformTests.test_dist_git_script` to test.
> Correct format for meson dist checksum and don't print

- mesonbuild/backend/ninjabackend.py
- mesonbuild/scripts/depscan.py
This will probably fail to the tests, but let's just get this out there for people to test and comment on. So ping all Fortran users, such as @scivision.
The main advantage of this approach is that we can drop all the prescan hacks we have and instead do Fortran automatically and reliably out of the box. I.e. moving module definitions from one file to another should just work without needing to run Meson reconfiguration.
> Extend the C++ module scanner to handle Fortran, too.

- mesonbuild/mesonlib.py
- mesonbuild/mtest.py
This is the next step in the revamping of `mtest`. Taking advantage of asyncio, it adds a progress report that tells the user which tests are running. In order to get there, several preparatory changes are needed:
* a new `TestLogger` class is created, based on `JunitBuilder`, and used as the common superclass for all the available logging mechanisms (text, JSON, JUnit and console)
* the `TestRun` object is created at the time the test is scheduled, so that the same object can be passed to the (new) `TestLogger.start_test` method when the test starts, and to `TestLogger.log` when the test finishes
> mtest: refactor logging and add progress report

- mesonbuild/compilers/d.py
- mesonbuild/environment.py
Fix #8118
If DMD version is `>=2.096`, `-makedeps` switch can be emitted.
For LDC, it checks that the DMD frontend is `>=2.096`.
Kind of difficult to have automated test at the moment because even the current development version of DMD does not yet advertize the `2.096` version.
But according [DMD release policy](https://dlang.org/changelog/release-schedule.html), the PR implementing the change (dlang/dmd#12011 - merged Dec. 2nd 2020) should be in the `2.096` version.
I could however test the feature by tricking the version comparison.
> Implement support of dlang -makedeps switch

- test cases/unit/45 vscpp17/main.cpp
many compilers allow "nodiscard" C++17 feature with pre-c++17 (or no) flags.
The C++17 filesystem typically actually does require -std=c++17 (or that compiler default).
This makes this unit test more representative of C++17 flag support.
We also test an MSVC macro for better coverage.
> unit:cpp17: make C++17 test stricter check

- mesonbuild/backend/vs2019backend.py
It should be "ClangCL" rather than "llvm". Note sure about earlier VS versions, but if it's of any use here's the 1 liner patch I'm running locally.
Here's a snippet from a VS (not meson) created vcxproj with the correct value:
```
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
<ConfigurationType>Application</ConfigurationType>
<UseDebugLibraries>true</UseDebugLibraries>
<PlatformToolset>ClangCL</PlatformToolset>
<CharacterSet>Unicode</CharacterSet>
</PropertyGroup>
```
The toolset drop-down in the UI says "LLVM (clang-cl)" which is maybe where the confusion came from?
Anyway, HTH.
Regards
> VS2019 backend uses wrong name for clang-cl toolset

- CODEOWNERS
- docs/markdown/Reference-manual.md
- docs/markdown/Rust-module.md
- docs/markdown/_Sidebar.md
- docs/markdown/snippets/rust_test_format_support.md
- docs/markdown/snippets/unstable-rust-module.md
- docs/sitemap.txt
- docs/theme/extra/templates/navbar_links.html
- mesonbuild/backend/backends.py
- mesonbuild/interpreter.py
- mesonbuild/modules/unstable_rust.py
- mesonbuild/mtest.py
- run_mypy.py
- test cases/rust/9 unit tests/meson.build
- test cases/rust/9 unit tests/test.rs
- test cases/rust/9 unit tests/test2.rs
This is now ready for review.
The goal here is to add  a place to put some helpers to make rust and meson play nice together. Presumably this would be the place to put cargo integration into meson as well.
What I have right now is a single helper for building rust tests, it takes an existing rust build target, and creates a new executable build target with the same sources and arguments, but adds the `--test` argument, as well as the `--format=pretty` option, and sets the test protocol to `'rust'`. This makes turning on rust unit tests super simple, as the updated test case shows.
I've chosen not to add this as unstable because we're going to start using this in mesa as soon as it lands.
> Add a rust module

- .github/workflows/os_comp.yml
- mesonbuild/cmake/interpreter.py
- mesonbuild/wrap/wrap.py
Fixes: #8161
@nirbheek, @jpakkane: this was the only instance of the new syntax I could fine reviewing the history. It might be worth having a 0.56.2 release after this?
> Dont use python 3.6 annotation syntax

- azure-pipelines.yml
Python3 in Cygwin is now Python 3.8
> ci: Fix pip installation in Cygwin on Azure

- docs/markdown/Commands.md
- docs/meson.build
- run_unittests.py
- tools/regenerate_docs.py
Fixes #8061 and is all-around cleaner IMHO.
> Hotdoc: use template for Commands.md instead of generating the entire file

- mesonbuild/mtest.py
- run_unittests.py
The next part after #8001. Adds:
* to the progress report a clock and, for TAP tests, the number of passed+run subtests.
* to the final test report for TAP tests, the number of subtests that have passed.
[Demo available here](https://asciinema.org/a/LIimxKSIyh8TNwq9U076vq0WU).
> mtest: asynchronous TAP parsing, improved progress report

- ci/ciimage/arch/install.sh
There hasn't been any such package since the original addition of a gtk3 version of wxgtk... back in 2017. The "new" wxgtk2 package provided a virtual provides ever since, so people still depending on "wxgtk" would get the old gtk2 version. This virtual provides got dropped today, resulting in the package being uninstallable.
Resolve the provides to its canonical name, thus making it installable again.
> CI: ciimage: fix arch linux image failing to install wxgtk

- mesonbuild/interpreter.py
- test cases/common/99 subproject subdir/subprojects/sub_implicit/subprojects/subsub/foo.h
- test cases/common/99 subproject subdir/subprojects/sub_implicit/subprojects/subsub/meson.build
- test cases/common/99 subproject subdir/test.json
- test cases/failing/62 subproj filegrab/test.json
- test cases/failing/63 grab subproj/test.json
- test cases/failing/64 grab sibling/test.json
A sub-subproject can be configured directly from
`subprojects/foo/subprojects/bar/` in the case `bar` is in the same git
repository as `foo` and not downloaded separately into the main
project's `subprojects/`. In that case the nested subproject violation
code was wrong because it is allowed to have more than one "subprojects"
in path (was not possible before Meson 0.56.0).
Example:
- self.environment.source_dir = '/home/user/myproject'
- self.root_subdir = 'subprojects/foo/subprojects/bar'
- project_root = '/home/user/myproject/subprojects/foo/subprojects/bar'
- norm = '/home/user/myproject/subprojects/foo/subprojects/bar/file.c'
We want `norm` path to have `project_root` in its parents and not have
`project_root / 'subprojects'` in its parents. In that case we are sure
`file.c` is …
> Interpreter: Fix nested subsubproject detection

- mesonbuild/backend/backends.py
- mesonbuild/cmake/executor.py
- mesonbuild/compilers/__init__.py
- mesonbuild/compilers/c.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cpp.py
- mesonbuild/coredata.py
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/boost.py
- mesonbuild/dependencies/hdf5.py
- mesonbuild/dependencies/mpi.py
- mesonbuild/envconfig.py
- mesonbuild/environment.py
- mesonbuild/linkers.py
- mesonbuild/modules/unstable_external_project.py
- run_unittests.py
Currently, meson reads environment variables in various places, sometimes at configure time, sometimes at runtime, with various behaviors. This series seeks to unify all environment variable handling into a single place, and store them so that they persist across reconfigures. There are a lot of cleanups in here as well, but the end result I think is much nicer than what we had before (and is less code).
> Read and store all environment variables up front

- docs/markdown/Rewriter.md
- docs/markdown/snippets/rewrite_allow_double_slash_project_id.md
- mesonbuild/rewriter.py
- run_unittests.py
- test cases/rewrite/3 kwargs/add.json
- test cases/rewrite/3 kwargs/remove.json
- test cases/rewrite/3 kwargs/remove_regex.json
- test cases/rewrite/3 kwargs/set.json
> Allow '//' as project function id due to git bash path conversion.

- mesonbuild/mesondata.py
- tools/gen_data.py
The current way this works is chaos since the tool might return files in any order and thus shuffle around the order of embedded files. This results in big diffs that cannot be easily reviewed.
Also regenerate the data according to the, going forward, canonical ordering algorithm.
Noticed in #8193
> gen_data.py: sort files when generating mesondata

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/summary_alignment.md
- mesonbuild/interpreter.py
- run_unittests.py
aligning along the left is, I think, what most projects want to do. Aligning along the middle looks subjectively ugly, and objectively prevents me from further indenting an element, e.g.
```
Build information:
prefix                : /usr
sysconfdir            : /etc
conf file         : /etc/myprogram.conf
```
> summary: align left, not align middle

- docs/markdown/snippets/meson_test_interrupt.md
- mesonbuild/mtest.py
The new behavior of interrupting the longest running test with Ctrl-C is useful when tests hang, but not when the run is completely broken for some reason. Psychology tells us that the user will compulsively spam Ctrl-C in this case, so exit if three Ctrl-C's are detected within a second.
> mtest: allow quickly interrupting the test run

- docs/markdown/snippets/msvc_no_zi.md
- mesonbuild/backend/backends.py
- mesonbuild/compilers/mixins/visualstudio.py
The /ZI flag adds in "Edit and Continue" debug information, which will cause massive slowdowns. It is not a flag that should be added by default to debug builds. It is also incompatible with MSVC LTO.
/Zi will still be added.
> Replacement of /ZI with /Zi on MSVC Debug

- docs/markdown/FAQ.md
- docs/markdown/snippets/buildtyperemains.md
- mesonbuild/coredata.py
- mesonbuild/mconf.py
- run_unittests.py
I have had an itch to do this for a long time but now it's finally done. Changing builtype automatically was originally my idea and it turned out not to be a great one. This should make it more sensible. In this way buildtype is more of an "intent for the build" but the exact details (e.g. -O3 instead of -O2) can still be tweaked.
> Keep buildtype the same even if user changes debug and/or optimization.

- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/modules/unstable_rust.py
- test cases/rust/11 generated main/gen.py
- test cases/rust/11 generated main/meson.build
This has lots of caveats, namely that rustc expects all of the sources
to exist in a single tree, not split across two (a build and source)
like meson does. You can use a generated source, but in that case it
must be exclusvively generated sources, in the same directory.
Fixes #8157
> rust: Accept generated sources for main.rs

- mesonbuild/compilers/mixins/emscripten.py
Compiler tests, such as checking for atomics support, could fail
when compiling to WebAssembly multithreaded targets because the
compiler tests got compiled to 'output.wasm'.
Using the '.wasm' suffix in recent versions of emscripten engages
STANDALONE_WASM mode, which disables features that require a JS
runtime like shared memory.
This created false negatives on support of those features when
building a library to be linked into an executable that is not
in STANDALONE_WASM mode.
Changing these to 'output.o' will continue to produce WebAssembly
object files, but they will no longer be configured for standalone
runtime mode.
> Avoid accidental use of STANDALONE_WASM mode on compiler tests

- docs/markdown/snippets/msvc_argument_changes.md
- mesonbuild/compilers/mixins/visualstudio.py
This PR performs some cleanup for the msvc and clang-cl arguments.
* "Disable Debug" (`/Od`) is no longer manually specified for optimization levels {`0`,`g`} (it is already the default for MSVC).
* "Run Time Checking" (`/RTC1`) removed from `debug` buildtype by default
* Maybe an option can be added for msvc-like compilers?
* Clang-CL `debug` buildtype arguments now match MSVC arguments
* There is now no difference between `buildtype` flags and `debug` + `optimization` flags
I removed some redundancy that was in the compile args (`\Od` is used by default, and `\O2` implies `\Ob2`)
> MSVC and Clang-Cl Compiler Argument Cleanup

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/summary_prog_dep.md
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter.py
- mesonbuild/mlog.py
- run_project_tests.py
- run_tests.py
- run_unittests.py
- test cases/unit/73 summary/meson.build
It is common to include in the summary whether a program or dependency was found. Simplify the code that does so, to avoid things such as
prg.found() ? prg.full_path() : false
> Allow passing external program and dependency objects to summary()

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/scripts/depscan.py
- test cases/fortran/21 install static/main.f90
- test cases/fortran/21 install static/main_lib.f90
- test cases/fortran/21 install static/meson.build
- test cases/fortran/21 install static/subprojects/static_hello/meson.build
- test cases/fortran/21 install static/subprojects/static_hello/static_hello.f90
- test cases/fortran/21 install static/test.json
While working on some meson build systems for fortran projects, I've run into a few issues wrt dependency resolution. This PR should fix those issues I believe. There's a test too. 
Basically, some link targets were promoted to `link_whole_targets` when the build target had `install:true`, but `link_whole_targets` was not included in the loop that adds include directories for fortran static libraries. Further, some code-scanning code had file suffix checks that were case sensitive, but `.F90` is a common filename extension for fortran sources.
The projects that I work on make use of generated sources, so that's why the test does it too. This turned out not to be the source of the issues, but I left it in anyway. Hope it's fine.
> Fixes for fortran: Include dirs for link_whole_targets and capital file suffix

- mesonbuild/backend/vs2010backend.py
ARM64EC is a new ARM64 ABI made by Microsoft. The ARM64EC binaries can be loaded in x64 processes on the latest Windows Insider Preview on ARM64, and they don't need to be emulated for the sake of performance.
To support the ARM64EC build target, a new conceptual arm64 cpu type 'arm64ec' is added. The cpu can be specified in cross files like below to generate msbuild solution/vcxproj files with platform set to ARM64EC.
```
[target_machine]
system = 'windows'
cpu_family = 'aarch64'
cpu = 'arm64ec'
endian = 'little'
```
> Add ARM64EC as a new conceptual cpu type of arm64

- docs/markdown/Machine-files.md
Fixes: 1ca17dc853ec ("docs/machine-files: Add a section on data types")
> docs: Fix sentence in Machine-files.md

- mesonbuild/wrap/wrap.py
It doesn't make sense to check for the presence of git every time we use it, but short-circuit any attempt to use a wrap right from the get-go because we are trying to be fancy with submodules.
If git is not installed, simply do not try to figure out whether the wrap is a submodule that can potentially be checked out/updated for the user. Just take it on faith that it isn't one.
Fixes #2623
> do not require git installed in order to use wraps

- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/interpreter.py
- mesonbuild/mdist.py
- mesonbuild/minstall.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/hotdoc.py
- mesonbuild/modules/i18n.py
- mesonbuild/scripts/meson_exe.py
- test cases/common/54 install script/meson.build
- test cases/common/54 install script/prog.c
- test cases/common/54 install script/src/foo.c
- test cases/common/54 install script/src/meson.build
On Windows this would fail because of missing DLL:
```
mylib = library(...)
exe = executable(..., link_with: mylib)
meson.add_install_script(exe)
```
The reason is on Windows we cannot rely on rpath to find libraries from
build directory, they are searched in $PATH. We already have all that
mechanism in place for custom_target() using ExecutableSerialisation
class, so reuse it for install/dist/postconf scripts too.
This has bonus side effect to also use exe_wrapper for those scripts.
Fixes: #8187
> Fix executable as script on Windows

- docs/markdown/snippets/meson_test_logs.md
- mesonbuild/mtest.py
- run_unittests.py
This pull requests includes several improvements to logging. In particular:
* in --verbose mode, the JSON and text file logs now include the output of the tests
* also in --verbose mode, the console log (similar to ninja) does not mix the output of multiple tests that are being run in parallel
* the console log and the text file log employ slightly different formatting, so that each medium gets the best readability
* the error logs for --print-errorlogs are emitted during the first part of the output, and not limited to 10 tests anymore.
> mtest: improvements to logging

- docs/markdown/External-Project-module.md
- docs/markdown/snippets/external_project.md
- mesonbuild/mesonlib/universal.py
- mesonbuild/modules/unstable_external_project.py
- mesonbuild/scripts/externalproject.py
commit 11cfc258fc2cebe6360322f3338741e1d6694525
Author: Xavier Claessens <xavier.claessens@collabora.com>
Date:   Fri Jan 29 10:30:28 2021 -0500
external_project: Add default configure options
commit 6a6323ff096db76b0cd82f13c8f369ac08180ef7
Author: Xavier Claessens <xavier.claessens@collabora.com>
Date:   Fri Jan 29 10:10:37 2021 -0500
external_project: Do not set LD in the env
This was breaking some autotools projects such as libyaml.
commit 46b68d4c83bba705bb520877c7b0bd04c2f8cd5b
Author: Xavier Claessens <xavier.claessens@collabora.com>
Date:   Fri Jan 29 09:29:01 2021 -0500
external_project: Improve logging
Write output of 'make' and 'make install' into log files as well when
not verbose.
> external_project: misc improvements

- mesonbuild/backend/xcodebackend.py
- mesonbuild/build.py
XCode backend current crashes when using custom targets
This is a step forward in fixing the issue.  
Custom targets is not yet supported, 
but at least the xcode backend doesn't crash, and the project file is generated
> XCode backend: resolve crash when using custom targets

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/destdir.md
- mesonbuild/backend/backends.py
- mesonbuild/interpreter.py
- mesonbuild/minstall.py
commit 866c9937d76375b19e2faf24158202f4f32162e1
Author: Xavier Claessens <xavier.claessens@collabora.com>
Date:   Fri Jan 29 15:18:12 2021 -0500
add_install_script: add skip_if_destdir kwarg
It is common, at least in GNOME projects, to have scripts that must be
run only in the final destination, to update system icon cache, etc.
Skipping them from Meson ensures we can properly log that they have not
been run instead of relying on such scripts to to it (they don't
always).
commit e56507415b389a0fa698a7af2d4b87251331739b
Author: Xavier Claessens <xavier.claessens@collabora.com>
Date:   Fri Jan 29 15:14:02 2021 -0500
minstall: Add --destdir command line option
> Some DESTDIR improvements

- test cases/common/37 has function/meson.build
This commit fixes the test that asserts on whether the lchmod() function
should have been detected as available by Meson. It does so by assuming
that on Linux systems not using glibc, the function will be available.
- fix comment about lchmod on Linux: musl has implemented the function
correctly since 2013, so the assumption in the test wasn't correct.
Furthermore, musl doesn't use glibc's stub mechanism.
- fix include to receive __GLIBC__ definition: including almost any
header in glibc will end up defining __GLIBC__, since most headers
include <features.h>. The <gnu/libc-version.h> header was probably
chosen because of its name, but its actual purpose is defining functions
for checking glibc version at runtime (instead of what the binary was
built with), so it isn't necessary to use it. …
> tests/common: fix " 37 has function" test on musl systems.

- mesonbuild/coredata.py
There is a bug concerning the `install_umask` option.
The default value is 0o22 = 18
Without this patch:
This value gets converted to an integer by `validate_value`, then NinjaBackend.get_user_option_args uses str() to converts it to ` -Dinstall_umask=18` and it gets written into build.ninja like that.
```
build meson-scan-build: CUSTOM_COMMAND PHONY
COMMAND = ... -Dinstall_umask=18 ...
```
If you run `ninja scan-build`, then `UserUmaskOption.toint()` tries to convert that to an integer using `int(str, 8)`. This fails:
```
Invalid mode: invalid literal for int() with base 8: '18'
```
This patch fixes this.
Note that this might also be a security vulnerability, because the umask used might not be the umask you wanted. If an attacker can write to the installation, it's probably a …
> bugfix concerning octal umasks

- mesonbuild/modules/unstable_cuda.py
CUDA Toolkits 11.1.1 and 11.2.0 have been released since the last time the module has been updated, but no new compute capabilities. So simply add the two entries as they appear in the official Release Notes, [Table 2](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
> Quick update of table of CUDA Toolkit vs. NVIDIA driver versions

- mesonbuild/backend/xcodebackend.py
Add include paths from dependencies for all languages (c, c++, objc, objc++)
This is a continuation of https://github.com/mesonbuild/meson/pull/8257
> xcode-backend: fix include paths

- docs/markdown/Gnome-module.md
- docs/markdown/snippets/gnome_install_script.md
- mesonbuild/modules/gnome.py
Various GNOME projects have scripts that does similar task, better do it directly in meson. This ensures it's done correctly regarding usage of subprojects and pkg-config. See for example this gtk bug:
https://gitlab.gnome.org/GNOME/gtk/-/issues/3626.
Fixes: #8268
> gnome: Add post_install() method

- docs/markdown/Reference-manual.md
- mesonbuild/build.py
- mesonbuild/interpreter.py
- mesonbuild/mtest.py
- run_unittests.py
- test cases/unit/2 testsetups/meson.build
This new keyword argument makes it possible to run specific test setups only on a subset of the tests.  For example, to mark some tests as slow and avoid running them by default:
add_test_setup('quick', exclude_suites: ['slow'], is_default: true)
It will then be possible to run the slow tests with `meson test --suite slow` (or one could add `add_test_setup('slow')` for symmetry, if so inclined).
> introduce add_test_setup(exclude suites: ...) keyword argument

- docs/markdown/Reference-manual.md
- run_unittests.py
- test cases/common/60 install subdir/meson.build
- test cases/common/60 install subdir/test.json
`install_subdir()` with a non-existing subdir creates the directory in the
target directory. This seems like an implementation detail but is quite useful
to create new directories for e.g. configuration or plugins in the installed
locations.
Let's add a test for it and document it to make this behavior official.
Limitation: it can only create at the install_dir location, trying to create
nested subdirectories does not work and indeed creates the wrong directory
structure. That is a bug that should be fixed separately:
install_subdir('blah',
install_dir: get_option('prefix'))
install_subdir('sub/foobar',
install_dir: get_option('prefix'))
install_subdir('foo/baz',
install_dir: get_option('prefix'))
$ tree ../_inst
../_inst
├── baz
├── blah
└── foobar
Fixes #2904
> Make installing non-existing subdirs a supported feature

- ci/ciimage/arch/install.sh
- ci/ciimage/ubuntu-rolling/install.sh
- docs/markdown/Rust-module.md
- docs/markdown/snippets/unstable-rust-module.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/interpreter.py
- mesonbuild/mesonlib/universal.py
- mesonbuild/modules/unstable_rust.py
- run_project_tests.py
- test cases/rust/12 bindgen/include/other.h
- test cases/rust/12 bindgen/meson.build
- test cases/rust/12 bindgen/src/gen_header.py
- test cases/rust/12 bindgen/src/header.h
- test cases/rust/12 bindgen/src/main.rs
- test cases/rust/12 bindgen/src/main2.rs
- test cases/rust/12 bindgen/src/source.c
- test cases/rust/12 bindgen/sub/meson.build
It's pretty common to want to use bindgen with rust and meson, as bindgen makes writing unsafe wrappers for C libraries really easy. It's uses clang internally, and users need to pass include directories via `-I` arguments. Meson generally discourages this, and prefers `include_directories` instead. This series adds a bindgen wrapper to the rust module, which simplifies this process by simplifying the passing of arguments into bindgen, by correctly handling `include_directories` objects, and by automatically generating and using a depfile.
This is currently based on #8236
> Add a wrapper to the rust module for bindgen

- ci/ciimage/arch/install.sh
- docs/markdown/snippets/qt6_module.md
- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/ui.py
- mesonbuild/modules/qt.py
- mesonbuild/modules/qt6.py
- run_unittests.py
- test cases/frameworks/4 qt/meson.build
This is basically a copy of the Qt5 module but from what I've tried (on 3 related but distinct projects) it seems to work properly.
```
Found qmake: /usr/bin/qmake-qt6 (6.0.0)
Run-time dependency qt6 (modules: Core, DBus, Gui, Network, Widgets) found: YES 6.0.0 (qmake-qt6)
```
Fixes #8056 
I'll see what I can do about tests & docs
edit: Tests are a bit difficult - e.g. `test_qtdependency_pkgconfig_detection` because no pkg-config files seem to be built for Qt6 (by default?). `test_qt5dependency_qmake_detection` could be copy-pasted for qt6.
`docs/markdown/Qt6-module.md` could be a stub referencing Qt5-module.md as everything's literally the same. `docs/markdown/Dependencies.md` can get the "Qt4 & Qt5" header expanded to include Qt6
edit 2: Qt should be found using CMake now as CMake is …
> Add Qt6 module

- mesonbuild/mtest.py
- run_unittests.py
* another deadlock similar to #8212
* avoid printing progress report as `123/-1s` when timeout is disabled
* allow `--wrapper` in combination with `--setup`, if the setup does not define a wrapper.
* avoid that asyncio tasks linger on timeout
* make non-parallel tests emit their output on the fly, similar to ninja console jobs
> mtest fixes for 0.57

- docs/markdown/Release-notes-for-0.57.0.md
Mismatched \` symbol was messing up the formatting.
> docs: Fix typo in release notes

- mesonbuild/minstall.py
In 0.57.0 installation via polkit won't work anymore. `destdir` is
defaulted to an empty string ('') instead of None.  But polkit
installation code incorrectly tests `destdir is None`.
> Fix destdir detection for installation via polkit

- docs/markdown/Builtin-options.md
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cuda.py
- mesonbuild/modules/unstable_cuda.py
- run_unittests.py
This is an extensive rewrite and hopefully hardening of the CUDA NVCC compiler object and its flag handling.
The class method `_to_host_flags()` is entirely rewritten and gains knowledge of the entire `nvcc` argument set in the [official documentation](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html). The method now translates an array of mixed GCC/NVCC or MVSC/NVCC flags into a legal argument set for `nvcc`, exploiting `-Xcompiler` and `-Xlinker` to pass down foreign arguments into the compiler. It does the best it can to take into account and paper over the peculiarities of NVCC argument parsing.
Builds successfully the entire `test cases/cuda` testsuite on my machine (with CUDA Toolkit 10.2).
Related to #8337. @andrzejc, would you like to test out this branch?
> CUDA Compiler Fixes

- mesonbuild/environment.py
- mesonbuild/mesonlib/universal.py
- run_unittests.py
- test cases/unit/90 multiple envvars/meson.build
- test cases/unit/90 multiple envvars/prog.c
- test cases/unit/90 multiple envvars/prog.cpp
Or other language flags that use CPPFLAGS (like CXXFLAGS). The problem
here is actually rather simple, `dict.setdefault()` doesn't work like I
thought it did, I thought it created a weak entry, but it actually is
equivalent to:
```python
if k not in dict:
dict[k] = v
```
Instead we'll use an intermediate dictionary (a default dictionary
actually, since that makes things a little cleaner) and then add the
keys from that dict to self.options as applicable.
Test case written by Jussi, Fix by Dylan
Co-authored-by: Jussi Pakkanen
Fixes: #8361
Fixes: #8345
> Environment: Fix passing envrionment both CPPFLAGS and CFLAGS

- mesonbuild/mconf.py
A predicate in two comprehensions was dropped, in what looks like a
rebase error on my part. With the predicate added things work correctly.
Fixes: #8344
> mconf: only print correct options in the correct sections

- docs/markdown/Reference-manual.md
- mesonbuild/backend/backends.py
- run_unittests.py
- test cases/common/52 run target/check-env.py
- test cases/common/52 run target/meson.build
run_target() does some variable substitutions since 0.57.0. This is a
new behavior, and undocumented, caused by sharing more code with
custom_target(). More consistency is better, so document it now.
custom_target() was doing variable substitution in the past, because it
shared some code with generator(), but that was undocumented. Some
refactoring in 0.57.0 caused it to not replace @CURRENT_SOURCE_DIR@,
@SOURCE_DIR@, and @BUILD_DIR@ anymore. This patch adds back
@CURRENT_SOURCE_DIR@ and document it. It does not add back @SOURCE_DIR@
because it is duplicate with @SOURCE_ROOT@ that has a better name. Also
do not add back @BUILD_DIR@ which is duplicate of @PRIVATE_DIR@, and
not @BUILD_ROOT@ surprisingly, adding to the confusion.
> Substitute @CURRENT_SOURCE_DIR@ in run_target() and custom_target()

- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/clang.py
- mesonbuild/compilers/mixins/islinker.py
- run_unittests.py
Clang has a hand `-Wunused-command-line-argument` switch, which when
turned to an error, gets very grump about `-flto-jobs=0` being set in
the compiler arguments (although `-flto=` belongs there). We'll refactor
a bit to put that only in the link arguments.
GCC doesn't have this probably because, a) it doesn't have an equivalent
warning, and b) it uses `-flto=<$numthreads.
Fixes: #8347
> compilers: Only insert -flto-jobs in clang's link arguments

- mesonbuild/mtest.py
os.path.relpath(f, wd) returns path with \ seperator on Windows, but ninja targets always uses / separator.
See for example https://gitlab.freedesktop.org/ocrete/libnice/-/jobs/7348274.
> mtest: use / as path separator for ninja targets

- run_unittests.py
I noticed a UnicodeDecodeError in the logs for #8332. This should fix it.
> unittests: expect mtest logs to be utf-8

- mesonbuild/backend/backends.py
This is deprecated in Python 3.10.
Instead, acces them from the class.
Fixes https://github.com/mesonbuild/meson/issues/8318
> Don't access other enum members from self

- mesonbuild/compilers/mixins/clang.py
Using `-Xclang -fcolor-diagnostics` provides no advantage to using just `-fcolor-diagnostics` option and sometimes causes problems:
* uncolored diagnostics on Arch Linux: https://bugs.archlinux.org/task/69662
* simple problem with removing flag `-fcolor-diagnostics`:  https://github.com/clangd/clangd/issues/279
This change fixes bug under Arch Linux (clang 11.0.1) where the following setup does not produce colored diagnostics:
* file `foo.c` with contents:
```c
int main() {
return "" * "";
}
```
* file `meson.build` with contents:
```meson
project('foo', 'c')
executable('foo', 'foo.c')
```
Building it with `CC=clang meson setup build && meson compile -C build` does not produce colored diagnostics.
> compilers: clang: Drop -Xclang before -fcolor-diagnostics flag

- mesonbuild/environment.py
- mesonbuild/mesonlib/universal.py
- run_unittests.py
These continue to be ignored as they always have, but no longer raise an
error.
Fixes: #8351
Fixes: #8354
> allow build.b_* options

- mesonbuild/compilers/compilers.py
- test cases/common/237 proper args splitting/main.c
- test cases/common/237 proper args splitting/meson.build
- test cases/common/237 proper args splitting/test.json
The problem, it turns out, is actually rather simple, in order to allow combining link and compile args we were calling listify on them. When we do this, they go into the convertor for the argument type as a list, it sees them as a list and retursn them as-is. This results in not splitting the arguments at all, and we get errors where `"-DFOO -DBAR"` doesn't get split into `['-DFOO', '-DBAR']`. This changes that by doing the combination of compiler and linker arguments (when required) to the values parsed by the `UserOption` class.
Fixes: #8348
> Fix lang args spliiting

- mesonbuild/mtest.py
- test cases/failing test/5 tap tests/meson.build
- test cases/failing test/5 tap tests/tester_with_status.c
Some time between 0.56 and 0.57 the TAP parser broke when a test exits
with a nonzero status.
The TAP protocol does not specify this behaviour - giving latitude to
implementers, and meson's previous behaviour was to report the exit
status gracefully.
This patch restores the old behaviour and adds a regression test
> [TAP] Fix TAP parser when test exits with status

- mesonbuild/compilers/cuda.py
- test cases/cuda/15 sanitizer/meson.build
- test cases/cuda/15 sanitizer/prog.cu
Enables `-Db_sanitize=undefined` and company.
Also serves as a testcase for NVCC comma-shielding: Because the test-case declares `b_sanitize=address,undefined`, the host GCC compiler needs `-fsanitize=address,undefined`, but this stands a danger of being split by NVCC when wrapped with `-Xcompiler=args,args`. Special, already-existing comma-shielding codepaths activate to prevent this splitting.
Closes #8394.
> [CUDA] Bugfix: Forward sanitizer_*_args() methods to host compiler.

- mesonbuild/mcompile.py
meson compile itself doesn't permit GNU-style argument permutation, i.e. TARGET to precede options, so why should we expect ninja to?
And indeed, ninja doesn't document support for this -- but it does accept it anyway, which is confusing and results in people thinking it's "supposed to" work.
However, if `NINJA=samu` then this is in fact enforced. samu does not permit GNU-style argument permutation. As a result, the arguments passed to mcompile are actively re-ordered before being passed to the subprocess, and samu dies with a fatal error.
Fix ordering in mcompile.py and add a comment to warn future readers that the order does, in fact, matter.
> mcompile: make sure arguments are passed in the correct order

- docs/markdown/snippets/permit_generator_customtarget.md
- mesonbuild/backend/vs2010backend.py
- mesonbuild/build.py
- test cases/common/106 generatorcustom/gen-resx.py
- test cases/common/106 generatorcustom/main.c
- test cases/common/106 generatorcustom/meson.build
Hi!
This change permits a `generator` to consume outputs by `custom_target` instead of failing.
This is needed to fix issues like #5693 where a generator created by the Qt module needs to process data that itself was produced in a custom target.
> Allow custom target output to be processed by generators

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/error_msg.md
- mesonbuild/interpreter.py
- run_unittests.py
Seems it got forgotten when that was added to warnings() and message().
Fixes: #8414.
> Support multiple args in error()

- mesonbuild/interpreter.py
- mesonbuild/interpreterbase.py
It doesn't properly declare its dependencies, so objects that inherit from it don't have their `held_object` method properly annotated. This isn't too hard to fix, just some typing.
> Fix ObjectHolder's type annotations

- mesonbuild/backend/ninjabackend.py
- test cases/rust/13 external c dependencies/c_accessing_zlib.c
- test cases/rust/13 external c dependencies/meson.build
- test cases/rust/13 external c dependencies/meson_options.txt
- test cases/rust/13 external c dependencies/prog.rs
- test cases/rust/13 external c dependencies/test.json
Currently, Meson doesn't correctly handle linking Rust with C-linkage external dependencies at all. This is obviously a big problem. This patch addresses that by adding support. Zlib is an excelent choice as it's often available as both static and shared, and it can be found in a bunch of ways (cmake, pkg-config, and system).
> Fix linking Rust with C dependencies

- docs/markdown/Cross-compilation.md
- docs/markdown/Reference-manual.md
- docs/markdown/snippets/deprecated_get_cross_property.md
- mesonbuild/interpreter.py
It's a pure subset of `get_external_property`, and has odd behavior in
host == build configurations. `get_external_property` is clear, and uses
the standard `native : bool` syntax to control host vs build properties
> deprecated `meson.get_cross_property`

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/has_external_property.md
- mesonbuild/interpreter.py
- test cases/common/223 native prop/crossfile.ini
- test cases/common/223 native prop/meson.build
Useful in case of boolean values to distinguish between a boolean
value having been set in the native/cross file and not having been
provided, which can't be achieved by passing a fallback parameter
to .get_external_property().
> meson: add .has_external_property() method

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/summary-accepts-features.md
- mesonbuild/interpreter.py
- run_unittests.py
- test cases/unit/73 summary/meson.build
- test cases/unit/73 summary/meson_options.txt
Currently, if a user wants to print the status of a build option in the `summary()`, they would have do do something like:
```meson
summary({
'feature': get_option('feature').enabled()
})
```
which prints the feature status as a boolean to string:
```
feature: True
```
This patch allows any `UserOption` to be printed in the summary, so:
```meson
summary({
'feature': get_option('feature')
})
```
gives:
```
feature: enabled
```
Another enhancement would be to check for an instance of `UserFeatureOption` and highlight enabled/disabled as green/red like for normal bools.
> Allow printing UserOptions in the summary

- mesonbuild/interpreter.py
- run_unittests.py
- test cases/unit/92 new subproject in configured project/meson.build
- test cases/unit/92 new subproject in configured project/meson_options.txt
- test cases/unit/92 new subproject in configured project/subprojects/sub/foo.c
- test cases/unit/92 new subproject in configured project/subprojects/sub/meson.build
The way the tracking is currently done it works if no new subprojects
are added to a configured build directory. For cases where we want to
add a new subproject, it fails because we don't initialize builtins for
that subproject. This corrects that by checking to see if the subproject
already exists, and if it doesn't initializes the bultins for it.
Fixes: #8421
> interpreter: correctly track whether a subproject is initialized

- mesonbuild/modules/fs.py
This is just a single commit from my larger series to use `typed_pos_args` in all of meson, plus a couple of easy optimizations I saw.
> Use `typed_pos_args` in fs module

- mesonbuild/dependencies/hdf5.py
hdf5's config-tools will not show compile arguments (including the include directory) if called without `-c`. Make sure to get both the compile and link arguments.
This is noticeable if hdf5 is not installed in a global prefix, so the header will not be found without the compile arguments.
> hdf5: get include directory from config-tool

- mesonbuild/backend/ninjabackend.py
- test cases/rust/14 external libm/meson.build
- test cases/rust/14 external libm/meson_options.txt
- test cases/rust/14 external libm/prog.rs
- test cases/rust/14 external libm/rs_math.rs
- test cases/rust/14 external libm/test.json
Previously it was assumed (because of the way meson handles pkg-config
dependencies) that `-l` option would be static. This is not true, `-l`
could be a shared lib as well. So, let's respect that.
Co-Authored-by: Dylan Baker <dylan@pnwbakers.com>
> rust: correctly handle -l link args

- mesonbuild/dependencies/base.py
The output of pkg-config is affected by environment variables.
Currently, the meson log output doesn't provide sufficient information to debug pkg-config issues.
With this change, all the pkg-config environment variables are outputted, including the system env variables, to simplify debugging.
> pkg-config: dump all PKG_CONFIG environment variables to simplify debugging

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/install_man_locale.md
- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/interpreter.py
- mesonbuild/modules/rpm.py
- test cases/common/10 man install/foo.fr.1
- test cases/common/10 man install/meson.build
- test cases/common/10 man install/test.json
Rather than having to manually build the locale aware man paths with
`install_data('foo.fr.1', install_dir: join_paths(get_option('mandir'), 'fr', 'man1'), rename: 'foo.1')`
Support doing
`install_man('foo.fr.1', locale: 'fr')`
> install_man locale support

- run_mypy.py
- run_project_tests.py
- run_single_test.py
- run_tests.py
It's often frustrating to me that if a single test regresses that uses a test.json I have to read the test.json and manually reconstruct that environment. That's silly, we have all the tools in place for this, we can just use them to create a single test runner than parses the test.json with the same logic that the main runner does. This is probably not super useful in CI, but as Meson developer being able to run a single test with its test.json (and even a single case from the test.json) is incredibly useful
> Add a script to run a single meson functional test case (with test.json support)

- mesonbuild/compilers/d.py
I'd like to have the possibility to import files from the build directory (resource files generated with `custom_target`).
The following works:
```meson
executable('my_exe', my_src,
include_directories: include_directories('source'),
d_import_dirs: [
include_directories('views'),
meson.current_build_dir() / 'views',
],
)
```
but is an anti-pattern, and rightfully warned:
```
WARNING: Building a path to the source dir is not supported. Use a relative path instead.
This will become a hard error in the future.
```
Instead I am proposing that `include_directories` have the same behavior in the context of `d_import_dirs` than in the context of adding header (or modules for D) search path: 
- add the path to the source directory (as currently done)
- add the path to the corresponding build …
> d_import_dirs add search path in the build directory

- mesonbuild/mtest.py
- run_unittests.py
Reusing the runners for multiple repeats of the test run gets in the way of the progress report, which stores runners in an OrderedSet. Instead, create a separate SingleTestRunner object for each repeat.
While at it, fix the "duplicate suite" assertion as it can fire with TAP tests and --repeat=N.
Fixes: #8405
> mtest: create separate runners for multiple repeats

- mesonbuild/modules/unstable_external_project.py
The variable `{host}` cannot be successfully expanded.
Using the `@HOST@` parameter, as suggested by the documentation, works.
> external_project: Fix default cross compile parameters

- mesonbuild/compilers/d.py
I've notice that when I add a generated source (with `custom_target`) to a target (e.g; an `executable` or `library`), the D versions specified with `d_module_versions` are not passed anymore to the compiler.
Inspecting the Ninja rules, I see that the D versions are passed to the compiler only for the generated source (which is first in the rules file), but not for the other sources.
I've tracked this down in the Meson code to the `get_feature_args` implementation that pops from `target.d_features`.
Tested to work in my own project.
Fixes: #7140
> fix missing D versions with generated source

- mesonbuild/build.py
- mesonbuild/interpreter.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/fs.py
- mesonbuild/modules/python.py
- mesonbuild/modules/unstable_rust.py
- ModuleState is now a real class that will have methods in the future
for actions modules needs, instead of using interpreter internal API.
- New ModuleObject base class, similar to InterpreterObject, that should
be used by all objects returned by modules. Its methods gets the
ModuleState passed as first argument. It has a `methods` dictionary to
define what is public API that can be called from build definition.
- Method return value is not required to be a ModuleReturnValue any
more, it can be any type that interpreter can holderify, including
ModuleObject.
- Legacy module API is maintained until we port all modules.
In the future modules should be updated:
- Use methods dict.
- Remove snippets.
- Custom objects returned by modules should all be subclass of
ModuleObject to get the …
> Simplify module API

- mesonbuild/mintro.py
- run_unittests.py
`meson introspect --targets` does not take flat layout into account, and this also breaks `meson test` starting with 0.57. This pull request adds a fix and testcase.
This should be included in 0.57.2.
@mensinda, please take a look. Thanks!
> mintro: include the correct target filenames for flat layout

- docs/markdown/Reference-manual.md
Make it easier to understand that this array contains the compiler
command, not arguments to it, and may only have one element.
---
I read past this several times not realising it was `cmd_array()` that would give me the command name.
Please check the new wording is correct for more complex cases - I've only used it for C and Vala.
> docs: Clarify compiler.cmd_array()

- mesonbuild/compilers/compilers.py
The latter is a python built-in exception, the former is a meson
exception.
> compilers: Use EnvironmentException not EnvironmentError

- mesonbuild/ast/interpreter.py
- mesonbuild/interpreter.py
- test cases/failing/112 enter subdir twice/meson.build
- test cases/failing/112 enter subdir twice/sub/meson.build
- test cases/failing/112 enter subdir twice/test.json
For #5209, it's better to have only one place where processed buildfiles are stored.
Added an explicit test for this, since one did not seem to already exist.
> Refactor subdir visitation to track files instead of dirs.

- docs/markdown/Reference-manual.md
- mesonbuild/minstall.py
In commit caab4d3d, the uid and gid arguments passed to os.chown() by
set_chown() were accidentally swapped, causing files to end up with
incorrect owner/group if the owner and group are not the same.
Also update the documentation to better indicate which argument to
install_mode is which.
Signed-off-by: Peter Kjellerstedt <peter.kjellerstedt@axis.com>
> minstall: Correctly set uid/gid of installed files

- mesonbuild/compilers/mixins/visualstudio.py
Without specifying optimization the used optimization depends on vs runtime-library.
With mdd it is /Od but with md it is /O2.
> Add /Od flag to msvc optimization 0 args

- mesonbuild/environment.py
The script dir is never really used since meson --internal handles this. The last remaining use of the raw script dir got removed in commit 522392e7553823e6b3ac38cadc4fbee72eae9540.
> remove unused environment function

- run_meson_command_tests.py
- setup.py
And don't run a pointless test to verify that the hardcoded list has been manually maintained correctly. The same test rules used there can translate directly to find_packages pattern rules.
...
Why do we need this either? find_packages() on its own behaves completely correctly, passing options to it is more explicit but does not actually change anything.
> setuptools: don't hardcode list of modules to install, use find_packages

- docs/markdown/Builtin-options.md
- docs/markdown/snippets/vsasan.md
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/mixins/visualstudio.py
https://devblogs.microsoft.com/cppblog/address-sanitizer-for-msvc-now-generally-available/
> Add address sanitizer support for Visual Studio.

- setup.cfg
- setup.py
We're down to just declaring the data files in python now.
> setuptools: move stuff to declarative cfg if possible

- docs/markdown/Syntax.md
- docs/markdown/snippets/fstrings.md
- mesonbuild/interpreterbase.py
- mesonbuild/mparser.py
- test cases/common/238 fstrings/meson.build
- test cases/failing/113 invalid fstring/meson.build
- test cases/failing/113 invalid fstring/test.json
- test cases/failing/114 invalid fstring/meson.build
- test cases/failing/114 invalid fstring/test.json
This is a little patch to add support for Python-esque format strings to the Meson language. This might be a controversial addition so I don't expect this to be merged as is, but I've purposefully limited this implementation to keep the lexer & parser simple.
The current version allows for the following (as indicated by the test case):
```meson
n = 10
s = 'a string'
message(f'n = {n}, string = {s}')
```
As I said the current version **is restricted** to identity-expressions inside of format strings (`{...}`) but if we decide that we want format strings and that they should support arbitrary expressions I'll lift that restriction.
I'm in favor of this addition as
- Format strings are intuitive, especially for people coming from Python and other languages offering them
- The current syntax …
> Add support for basic format strings

- test cases/rust/15 polyglot sharedlib/adder.c
- test cases/rust/15 polyglot sharedlib/adder.h
- test cases/rust/15 polyglot sharedlib/adder.rs
- test cases/rust/15 polyglot sharedlib/addertest.c
- test cases/rust/15 polyglot sharedlib/meson.build
This will probably fail on Windows and macOS. But those platforms probably don't care about this use case so disabling the test there is an option.
> Add test to build a mixed C/Rust shared library.

- mesonbuild/dependencies/base.py
- run_unittests.py
Previously builds would *potentially* get sammed with messaging at
configure time that duplicate entries in an array would be an error in
the future, and the cause was because the same entries were getting
added over and over to pkg_config_path.p
> Fix duplicate pkg_config_path entries

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cs.py
- mesonbuild/compilers/d.py
- mesonbuild/environment.py
- mesonbuild/linkers.py
Since this really is something about the compilers and linkers themselves, the information should be encoded there.
Fixes  #8502
> Add a method to the Compiler and Linker objects for rsp syntax

- docs/markdown/Commands.md
- docs/markdown/Reference-manual.md
- docs/markdown/snippets/devenv.md
- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/interpreter.py
- mesonbuild/interpreterbase.py
- mesonbuild/mdevenv.py
- mesonbuild/mesonmain.py
- mesonbuild/msetup.py
- mesonbuild/scripts/cmd_or_ps.ps1
- run_mypy.py
- run_unittests.py
- test cases/unit/91 devenv/main.c
- test cases/unit/91 devenv/meson.build
- test cases/unit/91 devenv/subprojects/sub/foo.c
- test cases/unit/91 devenv/subprojects/sub/meson.build
- test cases/unit/91 devenv/test-devenv.py
New method `meson.add_devenv()` adds an [`environment()`](#environment) object
to the list of environments that will be applied when using `meson devenv`
command line. This is useful for developpers who wish to use the project without
installing it, it is often needed to set for example the path to plugins
directory, etc. Alternatively, a list or dictionary can be passed as first
argument.
``` meson
devenv = environment()
devenv.set('PLUGINS_PATH', meson.current_build_dir())
...
meson.add_devenv(devenv)
```
New command line has been added: `meson devenv -C builddir [<command>]`.
It runs a command, or open interactive shell if no command is provided, with
environment setup to run project from the build directory, without installation.
These variables are set in environment in addition to …
> Add `meson devenv` command and meson.add_devenv()

- mesonbuild/coredata.py
When reverting from 0.57 to 0.56, one can see an error like this:
```
File /Users/pm215/src/qemu-for-merges/meson/mesonbuild/coredata.py,
line 1016, in load
obj = pickle.load(f)
ModuleNotFoundError: No module named 'mesonbuild.mesonlib.universal';
'mesonbuild.mesonlib' is not a package
FAILED: build.ninja
```
The reason is that the old version fails to resolve mesonbuild.mesonlib, which is a similar situation to the existing AttributeError check.  Raise a MesonException for ModuleNotFoundError as well, so that reconfiguration proceeds using cmd_line.txt.
> coredata: be more robust on unpickling errors

- mesonbuild/interpreter.py
- run_unittests.py
`get_non_matching_default_options` is checking a string from `project_default_options` against a validated value from `coredata.options`.
Passing the string to validate_value ensures that the comparison is sound; otherwise, `'false'` might be compared against `False`
and a bogus difference is printed.
Would be nice to have in 0.57.2 (QEMU is seeing this now that we can set `b_staticpic` to false in the default options).
> msetup: do not print bogus "Option ... is:" messages

- mesonbuild/modules/unstable_external_project.py
commit 85011f01be75546718fbf8f11d755e449edf2ecf
externalproject: Flatten configure_options kwarg
commit 65b323e4c053fbc258f127ee900ba8df47807914
externalproject: Do not add --includedir by default
Some projects (e.g. OpenSSL) does not support setting include directory
at all.
commit 1174973bd2db35fd13931a802b4ba23fe57bf027
externalproject: Fix error when used from main project
> externalproject: misc stuff

- mesonbuild/interpreter.py
- test cases/common/240 includedir violation/meson.build
- test cases/common/240 includedir violation/subprojects/sub/include/placeholder.h
- test cases/common/240 includedir violation/subprojects/sub/meson.build
- test cases/common/240 includedir violation/test.json
And again we find that if something is possible, no matter how wrong, someone will do it.
> Warn when grabbing internals of subprojects with include_directories.

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/dist_script.md
- mesonbuild/interpreter.py
- mesonbuild/mdist.py
- run_unittests.py
- test cases/unit/35 dist script/meson.build
- test cases/unit/35 dist script/subprojects/sub/dist-script.py
- test cases/unit/35 dist script/subprojects/sub/meson.build
- test cases/unit/35 dist script/subprojects/sub/meson_options.txt
- test cases/unit/35 dist script/subprojects/sub/prog.c
> Allow add_dist_script() in subprojects

- mesonbuild/minstall.py
- run_unittests.py
- test cases/common/8 install/gendir.py
- test cases/common/8 install/meson.build
- test cases/common/8 install/test.json
If a custom_target output is a directory, we install it as a directory, not as a file. And, we try to track subdirectories which are created so uninstalling works. But one directory creation did not go through DirMaker, in the case where the output directory does not have any further subdirectories.
Consolidate on makedirs, since I don't see much point in using os.mkdir right here.
Discovered while investigating https://github.com/DISTRHO/DISTRHO-Ports/issues/83
> minstall: always track meson-created directories

- mesonbuild/coredata.py
- mesonbuild/msetup.py
This fix issue when using --wipe and the machine file was passed as a
pipe and written locally, or when the file was resolved in XDG_DATA_HOME
or XDG_DATA_DIRS.
Fixes: #8560
> cmd_line_file.txt: Use cross/native file path resolved by coredata

- mesonbuild/mtest.py
mtest: timeout if the write side of pipes does not close
If a test program forks a child, the pipes might remain open and `await stdo_task`/`await stde_task` will never complete in `SingleTestRunner._run_cmd()`.
Instead, catch them in TestSubprocess.wait() so that the whole process group is killed and the test times out.
Fixes: #8533
> mtest: timeout tests if they have runaway child processes

- mesonbuild/interpreter.py
- mesonbuild/mlog.py
- run_unittests.py
Meson used to prepend '|' for each nested subproject to distinguish in
the logs where a subproject start and ends. It is more useful to print
the current subproject name.
Also print the call stack when starting a new subproject to better see
which subproject chain leads to to.
--
This is an RFC, I'm not sure this should be the default output, or if we should have a command line option for that?
> RFC: logs: Prepend current subproject name to all messages

- mesonbuild/compilers/mixins/visualstudio.py
- test cases/common/128 generated assembly/meson.build
- test cases/common/128 generated assembly/square-x86.S.in
- test cases/common/128 generated assembly/square-x86_64.S.in
- test cases/common/128 generated assembly/square.def
clang-cl has support for gas-compatible assembly files.
> compilers: clang-cl: Also accept .s files

- mesonbuild/interpreter.py
- run_project_tests.py
- test cases/common/240 includedir violation/meson.build
- test cases/common/240 includedir violation/subprojects/sub/meson.build
- test cases/common/240 includedir violation/test.json
commit 366fa781fd95db80908856f6b75c3214d67b29f5
interpreter: Fix spurious warning in include_directories()
When doing include_directories('.') at the root of the subproject we
should not warn about sandboxing violation.
commit 00020a34de5ef6b0c4d32e60a0b65a75e800ff0c
test.json: Add support for not matching stdout lines
By default expected line must be matched in order. When an expected line
is matched it does not matter if it's matched again later or not.
When defining "count", it means that line must be matched exactly that
many times before matching the next expected line. Once all occurences
have been matched for an expected line, it not must appear any more in
all next lines.
commit 29f700e6b3ff0bb6d8de2142437834c9de291b55
run_project_tests.py: Allow "--only common/240" syntax
> Fix spurious sandbox violation warning

- mesonbuild/mesonlib/universal.py
It looks like when Windows media scanner holds files we can't change
their permission neither.
> windows_proof_rmtree: Also retry os.chmod() part

- mesonbuild/modules/pkgconfig.py
- run_unittests.py
- test cases/common/45 pkgconfig-gen/meson.build
Some variables are reserved because meson set them automatically. But we
are not setting them for dataonly pc files, so there is no reason to
reserve them.
Fixes: #8583.
> pkgconfig: Allow setting prefix in dataonly pc file

- docs/markdown/howtox.md
Replace `meson compile scan-build` with `ninja -C dir scan-build`,
because scan-build target does not work with `meson compile`.
Note about SCANBUILD env variable was not precise enough to describe how
to pass arguments to scan-build - provide an example to make it clear.
Fixes: #7644.
> docs: Provide working instructions for scan-build

- mesonbuild/coredata.py
The host cache had BUILD, which is wrong.
> coredata: Fix dependency cache

- docs/markdown/Subprojects.md
- docs/markdown/snippets/subprojects_update.md
- mesonbuild/msubprojects.py
When using --reset we should guarantee that next reconfigure will pick
the latest code. For wrap-file we have no way to know if the revision
changed, so we have to delete the source tree and extract again.
It is unlikely that user has local changes in non-git subprojects, and
--reset is known to be dangerous.
> msubprojects: wrap-file should be re-extracted with --reset

- mesonbuild/wrap/wrap.py
Otherwise user cannot understand which wrap file is missing or wrong
> wrap: Tell which wrap-redirect file is missing

- docs/markdown/Continuous-Integration.md
Hi, spotted this one while learning Meson.
> docs: change duplicate "**.h" path to "**.c" [skip ci]

- mesonbuild/scripts/meson_exe.py
1. use `locale.getpreferredencoding()` to get encoding name.
`bytes.decode()` assumes `encoding='utf-8'` by default. It is incorrect on my
Windows setup, and causes `UnicodeDecodeError`.
2. use `errors='replace'`.
`bytes.decode()` assumes `errors='strict'` by default. Meson shouldn't crash
if subprocess outputs some garbage that can't be decoded.
`surrogateescape` doesn't work as expected on Windows. On Linux, default
`errors` for `sys.stdout` is `strict`, so `surrogateescape` can't be used there
too (at least until `sys.stdout` is reconfigured).
Fixes https://github.com/mesonbuild/meson/issues/8480
> scripts/meson_exe: fix stdout and stderr decoding

- mesonbuild/compilers/compilers.py
- mesonbuild/environment.py
- run_unittests.py
How this was all working before is a mystery to me. we had
1) a test that was wrong
2) no test for the right behavior
3) then broke the right behavior to fix the test that was implementing the wrong behavior.
For reference, the correct behavior is documented here: https://mesonbuild.com/Reference-tables.html#environment-variables-per-machine
> Fix _FOR_BUILD env variables

- mesonbuild/backend/xcodebackend.py
Create new classes for the primitives Xcode uses and use those instead of outputting lines of text. This makes the code more understandable. While I was there I also fixed some issues in the backend and you can now, for example, run the tests.
> Refactor the Xcode backend

- docs/markdown/Syntax.md
This documents the bool methods to_int and to_string implemented in
[1].
[1]: https://github.com/mesonbuild/meson/blob/a9e9b7c7501a3c8a5984a93879d1f309bf8c72aa/mesonbuild/interpreterbase.py#L1109
> docs: document bool to_int and to_string methods

- mesonbuild/coredata.py
- mesonbuild/environment.py
- run_unittests.py
Currently, there are two bugs (one reported and one I found by inspection):
1) If a native file contains a `[project options]` section, and is used in a cross compile, then it's options will be loaded. This is a bug, only the cross file's `[project options]` should be used
2) If a native file is used in a cross compile, if it defines builtin options that are not allowed for the build machine, then those options will cause an uncaught exception in subprojects.
@nirbheek, I think these are probably worth fixing for 0.57.2 as they're regressions in the 0.57 branch, but I also don't want to hold up the release forever.
> Fix using a cross and native file at the same time

- docs/markdown/Reference-manual.md
By default, the project version is picked.
> docs: document default version for declare_dependency()

- mesonbuild/modules/pkgconfig.py
> pkgconfig: Fix broken paths in -uninstalled.pc on Windows

- mesonbuild/mconf.py
Looking in the right dictionary is pretty useful, actually.
@jenatali
> mconf: print core options for subprojects

- mesonbuild/wrap/wrap.py
When using `wrap-git` with a `revision=` pointing at a branch, and the branch name happens to match the name of a file or folder in the default branch, `meson subprojects download` fails.
I've created a [simple git repository](https://github.com/drmoose/meson-git-checkout-bug) that just contains a folder called `foo` _and_ a branch called `foo`.
To reproduce the bug:
```bash
cd "$(mktemp -d)"
touch meson.build
mkdir subprojects
cat > subprojects/meson-git-checkout-bug.wrap <<EOF
[wrap-git]
directory=meson-git-checkout-bug
url=git@github.com:drmoose/meson-git-checkout-bug
revision=foo
EOF
meson subprojects download
```
The error message from the `meson subprojects download` command is
```
Download meson-git-checkout-bug...
Cloning into 'meson-git-checkout-bug'...
remote: Enumerating …
```
> Add trailing -- parameter to `git checkout` calls.

- docs/markdown/snippets/subprojects_purge.md
- mesonbuild/msubprojects.py
- run_unittests.py
This will help facilitate cache busting in certain situations, and
replaces hand-rolled solutions of writing a length command to remove
various files/folders within the subprojects directory.
> Add 'subprojects purge' command

- mesonbuild/coredata.py
- mesonbuild/interpreter/interpreter.py
- run_unittests.py
- test cases/unit/48 reconfigure/meson.build
- test cases/unit/48 reconfigure/subprojects/sub1/meson.build
We need to konw on rconfigure which options have already bee set not
just for the super project, but also for the subproject. However, using
first_invocation is not sufficient, as a reconfigure could add a new
subpproject that wasn't present before, and we need to initialize that
project's builtins.
> store the list of initializes subprojects in the coredata structure

- mesonbuild/backend/backends.py
- run_unittests.py
- test cases/unit/57 introspection/meson.build
The `meson-info/intro-targets.json` file does not currently show full introspection data for the input sources to custom targets when those sources come from other targets; this makes it impossible for an IDE to fully re-build the dependency graph for those targets. I added a fix for this and some verifications in the unit tests.
> introspection: export all sources for custom targets

- mesonbuild/modules/unstable_cuda.py
Short PR to add the entries for CUDA Toolkits 11.2.2 and 11.3.0, in agreement with the [Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).
> Update CUDA Toolkit driver version table

- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/objc.py
- mesonbuild/compilers/objcpp.py
- run_project_tests.py
This gets rid of compile warnings when running the test suite (see gh-7344), and simplifies the code. Note that `work_dir` in `sanity_check_impl` was incorrect, it was used both to prepend to file names _and_ as `cwd=work_dir` argument to `Popen`. This is fixed here.
Closes gh-7344
Also adds validation for `--only`. This now gives a clear error rather than silently passes for unrecognized categories, like:
```
python run_project_tests.py --only objc  # should be 'objective c'
```
That's just a tiny 2-line usability improvement.
> Use sanity_check_impl for objc/objpp

- mesonbuild/mesonlib/universal.py
- run_unittests.py
I was converting a cmake project to meson, and saw this error message. I could not understand what it meant until reading the meson code - it was not clear to me whether the problem was in the config file, or the meson build file. I think this makes the problem more clear.
> Clarify incorrect configuration format message

- mesonbuild/modules/qt.py
This codepath is reached if a bad path is specified for a qt resource file. The empty list return value is used in two places, both of which unpack to a tuple, which fails, resulting in a python exception and a backtrace written to the console. This change makes the error message look more like meson's other error messages.
> Fix python exception thrown for invalid resource path

- mesonbuild/modules/gnome.py
Cross-compiling and generating gobject-introspection isn't trivial, but
with wrapper scripts that call qemu-user it's perfectly doable[1].
Currently looking up the gobject-introspection pkgconfig is done as a
native dependency, which means in cross-compilation environments this
is not the right paths (wrong library path, for example).
Solve this by generalisiing _get_native_dep() to _get_dep(native) and
asking for the host gobject-introspection instead.
[1] https://git.yoctoproject.org/cgit.cgi/poky/tree/meta/recipes-gnome/gobject-introspection/
> gnome: improve dependency lookup of G-I

- mesonbuild/dependencies/base.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/python.py
commit b44b9437f21398fe6af0767860a75a1e12716a3d
Date:   Thu May 6 09:38:35 2021 -0400
interpreter: Skip not_found_message and include_type in cache id
commit 3d2cbc5c031d0577723c5f783bb704d8cdbe6392
Date:   Thu May 6 09:31:19 2021 -0400
interpreter: 'embed' kwarg is only valid in python module
> Small fix to dependency() kwargs

- mesonbuild/modules/fs.py
- test cases/common/220 fs module/meson.build
- test cases/common/220 fs module/subdir/meson.build
With this change File objects created with the builtin files() function
can be used with the fs submodule like normal strings.
All methods that seem reasonable support FileOrSting arguments.
For example fs.exists() still only takes str arguments because meson
already ensures that File objects do exist when creating them with files().
Te test cases for fs are extended appropriately with tests for File objects.
Fixes #8608.
> modules/fs: support FileOrString arguments

- run_tests.py
- run_unittests.py
Not great, but less terribler.
> Set unittest backend with an argument rather than an envvar.

- mesonbuild/interpreter/interpreterobjects.py
- test cases/common/41 test args/meson.build
- test cases/common/41 test args/tester.py
Turns out listify() flattens by default, but stringlistify() cannot
flatten... How do I realize this only now?
Fixes: #8727
> interpreter: flatten environment() initial values

- test cases/fortran/21 install static/meson.build
- test cases/fortran/21 install static/subprojects/static_hello/meson.build
I didn't see a benefit from explicitly calling platform dependent program vs. using built-in copy method of configure_file(). This makes the test work on Windows, where previously it failed.
> test:fortran:21: fix Windows by using configure_file(copy:)

- mesonbuild/backend/vs2010backend.py
- mesonbuild/compilers/mixins/visualstudio.py
Two commits in this merge request. I'd like feedback on both:
1. Reduce minimum compiler version to 16.9. The version check for 19.29.29917 added in d76345b4beec48484e31110b225c3256d8ba264b refers to an unreleased version (16.10 beta, perhaps?). Was that intentional (ie. is there some fix in the beta that I'm not aware of)? Seems to work in the current "released" version 16.9.4 / 19.28.29914
2. Covert /fstanitize=address to project setting. When I tested this, /fsanitize=address is still being added to "AdditionalOptions". It seems to work as-is, but it would be cleaner if I could remove it from "AdditionalOptions". I'm not quite sure how or where it is being added; pointers would be appreciated.
> Visual Studio Address Sanitizer updates

- docs/markdown/Reference-tables.md
- mesonbuild/envconfig.py
This is to support the relatively new CPU architecture CSky. See https://c-sky.github.io/
> add cpu family csky

- docs/markdown/Pkgconfig-module.md
- docs/markdown/snippets/pkgconfig_var_escaping.md
- mesonbuild/modules/pkgconfig.py
- run_unittests.py
- test cases/common/44 pkgconfig-gen/meson.build
We need to escape space in variables that gets into cflags or libs
because otherwise we cannot split compiler args when paths contains
spaces. But custom variables are unlikely to be path that gets used in
cflags/libs, and escaping them cause regression in GStreamer that use
space as separator in a list variable.
> pkgconfig: Do not escape custom variables

- test cases/vala/2 multiple files/meson.build
I deleted the test that enforced that this failed, but having a test that enforces it passes would be good too.
> vala: Test that adding C manually isn't required

- mesonbuild/mesonmain.py
setup_vsenv() failed for me as:
1. I have VS 2021 and 2017 installed and both in non-standard locations (paths without spaces in them)
2. Meson defaulted to VS 2017 but I use VS 2012 and had called setvars in VS 2012 before calling Meson.
I implemented two additional checks:
- one for the VSINSTALLDIR environment variable
- one that checks for "cl.exe" in PATH when the environment variable OS is Windows_NT
> Better detection of Visual Studio compiler

- azure-pipelines.yml
- run_unittests.py
- test cases/common/127 generated assembly/meson.build
- test cases/common/6 linkshared/cpplib.cpp
- test cases/common/6 linkshared/cpplib.h
- test cases/common/6 linkshared/cppmain.cpp
- test cases/frameworks/11 gir subproject/meson.build
- test cases/frameworks/12 multiple gir/meson.build
- test cases/frameworks/22 gir link order/meson.build
- test cases/frameworks/28 gir link order 2/meson.build
- test cases/vala/11 generated vapi/meson.build
`f76c6b8d0 Fix LTO test on Cygwin`
Disabled in #8381
I'm not sure how/if this ever worked.
`91aeae558 Revert "ci: Disable pytest-xdist on cygwin"`
DIsabled in #7597
python-psutil doesn't seem to be in the dependencies for pytest-xdist anymore.
`2d215d93b Revert "Disable failing Cygwin GIR test."`
Disabled in #8381
This was a problem with the Cygwin `gobject-introspection` package which has been fixed.
`1694e4cec Revert "Disable broken asm test on Cygwin as nobody knows how to fix it."`
Disabled in #8505.
> Re-enable various tests on Cygwin

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/xcodebackend.py
Linking libraries fails. Don't really know why, but an identical CMake project fails in the same way.
> Add swift executable support in Xcode.

- mesonbuild/backend/ninjabackend.py
- test cases/common/137 whole archive/meson.build
- test cases/common/170 generator link whole/meson.build
...Update 2, to be exact, since the Visual Studio linker only gained the
`/WHOLEARCHIVE:` feature since Visual Studio 2015 Update 2.
This checks whether we have the corresponding `cl.exe` which is
versioned at or after Visual Studio 2015 Update 2 before we try to apply
the `/WHOLEARCHIVE:xxx` linker flag.  If we aren't, use built-in methods
in Meson to grab the object files of the dependent static lib's, along
with the objects that were `link_whole:`'ed into them, and feed this
list into the linker instead.
This would make `link_whole:` work on Visual Studio 2015 Update 1 and
earlier, including previous Visual Studio versions.
> ninjabackend.py: Implement `link_whole:` for pre-VS2015

- mesonbuild/modules/gnome.py
- test cases/frameworks/7 gnome/gir/copy.py
- test cases/frameworks/7 gnome/gir/meson.build
We need to pass any generated sources down the CustomTarget
inititalizers so that they will generate a dependency correctly,
otherwise we get race conditions.
> modules/gnome: Correctly handle generated sources for generate_gir

- mesonbuild/build.py
- mesonbuild/coredata.py
- mesonbuild/dependencies/dev.py
- mesonbuild/mesonlib/universal.py
- test cases/common/241 dependency native host == build/meson.build
- test cases/common/241 dependency native host == build/test.json
For structures that are not exposed to the user it is fine to have completely separate build and host structures, but for anything exposed to the user we need to use PerMachineDefaultable. This is because PerMachine is a host/build separated structure, but meson as a language doesn't expose this, it exposes a native/not native interface.
The implication of this is if a user says `native : true`, that has a different meaning in a cross compile than in a !cross compile, whereas build and host do not. So `depencency('zlib', native : true)` in a cross compile (host != build) means find zlib for the build machine, but in a native build (host == build) then it means get zlib for the host machine. To deal with this, data structures exposed to the user use a Defaultable, which in host == build …
> Per-machine caches that are user accessible should use PerMachineDefaultable

- mesonbuild/interpreter/interpreter.py
It was previously an hard error, only permitted since 0.59.0.
> Vala: Add missing FeatureNew() when C is missing

- run_tests.py
I'd imagine all CI machines have been updated by now. If not, the tests will fail.
> Remove HFS workaround as everyone should use APFS by now.

- mesonbuild/mdist.py
This is problematic when we meson is installed in the different 
root(say C:) while building from another root(say D:).
This is how it is done in mesonpep517 and causes problems
because of that.
What I tried was clone https://gitlab.com/thiblahute/mesonpep517 then, run `python -m build -sn`
and this happened (I have removed all extra things to just show the error from meson)
```cmd
H:\mesonstuff\new\mesonpep517>python -m build -sn
Cloning into 'C:\Users\User\AppData\Local\Temp\tmp0isx1sp0\meson-dist\mesonp
ep517-0.2'...
done.
File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\meson
build\mesonmain.py", line 134, in run
File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\meson
build\mdist.py", …
```
> Don't use `os.path.relpath` in dist command

- mesonbuild/cmake/__init__.py
- mesonbuild/cmake/common.py
- mesonbuild/cmake/generator.py
- mesonbuild/cmake/interpreter.py
- mesonbuild/cmake/toolchain.py
- mesonbuild/cmake/traceparser.py
- mesonbuild/coredata.py
- mesonbuild/dependencies/base.py
- test cases/cmake/16 threads/subprojects/cmMod/CMakeLists.txt
- test cases/cmake/23 cmake toolchain/meson.build
- test cases/cmake/23 cmake toolchain/nativefile.ini.in
- test cases/cmake/23 cmake toolchain/subprojects/cmModFortran/CMakeLists.txt
Instead of guessing the internal compiler variables, Meson now runs CMake once to determine what they actually are.
> CMake toolchain file improvements (fixes #8293)

- test cases/common/103 has header symbol/meson.build
On mac this appears to default to c++98, which in turn falls over with
boost that requires at least c++11
> test cases/common/103 has header symbol: set c++ standard

- mesonbuild/build.py
- mesonbuild/dependencies/detect.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreterbase.py
- run_unittests.py
This is a few of the simpler side cleanup sort of patches from #8822, most of these are type annotations, but there is also a change to the `typed_kwargs` decorator to allow safely passing mutable containers as default values in the Kwargs, which is useful for cases were you want the default to be an empty list.
> A few of the basic cleanups and enhancements from the Qt series

- mesonbuild/coredata.py
- mesonbuild/dependencies/coarrays.py
- mesonbuild/dependencies/detect.py
- mesonbuild/dependencies/factory.py
- mesonbuild/dependencies/hdf5.py
- mesonbuild/dependencies/misc.py
- mesonbuild/dependencies/mpi.py
- mesonbuild/dependencies/scalapack.py
- run_mypy.py
This was more complicated than expected...
I replaced some `functools.partial` calls with lambdas because of typing issues: https://github.com/python/mypy/issues/1484
> typing: Fully annotate dependencies.{detect,factory} + some other fixes

- docs/markdown/Cython.md
- docs/markdown/Reference-tables.md
- docs/markdown/snippets/first-class-cython.md
- docs/sitemap.txt
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/compilers/__init__.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cython.py
- mesonbuild/environment.py
- mesonbuild/interpreter/interpreter.py
- run_project_tests.py
- test cases/cython/1 basic/cytest.py
- test cases/cython/1 basic/libdir/cstorer.pxd
- test cases/cython/1 basic/libdir/meson.build
- test cases/cython/1 basic/libdir/storer.c
- test cases/cython/1 basic/libdir/storer.h
- test cases/cython/1 basic/libdir/storer.pyx
- test cases/cython/1 basic/meson.build
- test cases/cython/2 generated sources/configure.pyx.in
- test cases/cython/2 generated sources/g.in
- test cases/cython/2 generated sources/gen.py
- test cases/cython/2 generated sources/generator.py
- test cases/cython/2 generated sources/meson.build
- test cases/cython/2 generated sources/test.py
Okay, I stopped thinking about it and started writing code. This is not complete, there's a fair number of things not done (listed below). Currently, this is just enough to build one trivial test case, but I think it touches all the places that need to be changed, even if there is more work to do. I'm not sure how much more time I'll be able to spend on this, but here's a starting point if someone else wants to take it up.
TODO:
> 1st class Cython language support

- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreterbase.py
- run_unittests.py
This adds two additional keywords to the `KwargInfo` used by `typed_kwargs` (which are the last two I'd planned to add): "validator" and "converter" the first is used to set additional validation constraints (say a function accepts a string that is really an enum and only accepts 3 values). The converter can then be used to convert the Meson DSL value into whatever our implementation actually wants (like an Enum type instead of a string, or bool).
I'm trying to just pick small pieces to add type checking to so that they're easier to review than doing everything all at once.
> Type checking and annotations for the `add_*_arguments functions and helpers

- mesonbuild/modules/unstable_cuda.py
In commit 3340284805b96a4b9b62405f626020276341944c the new ModuleObject API got further updated to hide self.interpreter; at the time, the CUDA module got transferred over to the wrapper which does provide it.
But it works fine without self.interpreter, so let's just use the best base class.
> cuda module: fully buy into new modules API

- docs/markdown/Dependencies.md
Remove tabs I introduced by https://github.com/mesonbuild/meson/pull/8866
Thanks for pointing those out @jon-turney
> markdown/Dependencies:replace tabs with spaces

- .github/workflows/images.yml
- .github/workflows/website.yml
Make workflow steps requiring secrets conditional on the presence of those secrets.
This stops the 'build images' workflow from running and failing on it's weekly schedule in a forked repository, which results in a mail, unless you manually disable that workflow.
(The test has to be written rather indirectly as secrets aren't available to `if`, see actions/runner#520)
> Make workflow steps requiring secrets conditional

- .github/workflows/file_format.yml
- run_format_tests.py
- run_project_tests.py
Split out checking of file format as a separate GitHub workflow, rather than running it as part of the project tests for every platform and toolchain combination in CI, so that this test is not effected by the changed paths constraints which are applied to the project tests.
> CI: Split out file format test as a separate GitHub workflow

- mesonbuild/minit.py
You cannot `str() in str()` and expect it to act like `str() in list()`.
Fixes regression in commit bbc2745dccc40761989a3e1efbe5a69eea0bc77e
Unbreaks #6573
Fixes #8872
> minit: do not misdetect files suffixed as "" or named "." or "c" or "s" as c#

- mesonbuild/environment.py
Both LLVM 11 and 12 are stable releases. Note that FreeBSD changes the
way to version LLVM executables in LLVM 10.
> environment: Add LLVM suffixes for 11 and 12

- mesonbuild/backend/ninjabackend.py
- test cases/cython/2 generated sources/libdir/gen.py
- test cases/cython/2 generated sources/libdir/meson.build
- test cases/cython/2 generated sources/meson.build
This is a follow-up to gh-8706 (Cc @dcbaker), which contained the initial fix to `ninjabackend.py` but somehow lost it. This re-applies the fix and adds a test for it.
Without the fix, the error is:
```
ninja: error: 'ct2.pyx', needed by 'libdir/ct2.cpython-39-x86_64-linux-gnu.so.p/ct2.pyx.c',
missing and no known rule to make it
```
> Fix issue with generated Cython code in a subdir

- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/boost.py
- mesonbuild/dependencies/cmake.py
- mesonbuild/dependencies/coarrays.py
- mesonbuild/dependencies/configtool.py
- mesonbuild/dependencies/cuda.py
- mesonbuild/dependencies/dev.py
- mesonbuild/dependencies/dub.py
- mesonbuild/dependencies/factory.py
- mesonbuild/dependencies/framework.py
- mesonbuild/dependencies/misc.py
- mesonbuild/dependencies/mpi.py
- mesonbuild/dependencies/pkgconfig.py
- mesonbuild/dependencies/platform.py
- mesonbuild/dependencies/system.py
- mesonbuild/dependencies/ui.py
- mesonbuild/modules/python.py
- run_mypy.py
- test cases/failing/68 wrong boost module/test.json
This makes two changes. First it introduces a new SystemDependency intermediate class, this works much like PkgConfigDependency or ConfigToolDependency, but for system dependencies, this resolves the actual issue. Then I've added a `typeing.NewType`, which allows mypy to find cases where we're accidently writing the dependeny name to the type_name. It found a few cases of that.
Fixes #8877
> Fix System dependencies setting type_name instead of name

- docs/markdown/_include_qt_base.md
- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/qt.py
- test cases/failing/45 abspath to srcdir/test.json
- test cases/frameworks/4 qt/meson.build
This fixes two issues:
1. using extend where we should be using append
2. preprocess previously accepted strings for include directories, make that work again.
> Qt: Fix some issues with the type safety reworks

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/build-target-found.md
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreterbase/baseobjects.py
- test cases/common/182 find override/meson.build
- test cases/common/182 find override/otherdir/meson.build
As a side-effect from #8885 `find_program()` returns now `Executable`
objects when `meson.override_find_program` is called with an
executable target. To resolve this conflict the missing methods
from `ExternalProgram` are added to `BuildTarget`.
> fix: Ensure that build targets have all methods from ExternalProgram

- mesonbuild/cmake/interpreter.py
- mesonbuild/compilers/compilers.py
- test cases/cmake/25 assembler/main.c
- test cases/cmake/25 assembler/meson.build
- test cases/cmake/25 assembler/subprojects/cmTest/CMakeLists.txt
- test cases/cmake/25 assembler/subprojects/cmTest/cmTest.c
- test cases/cmake/25 assembler/subprojects/cmTest/cmTestAsm.s
This patch adds a variable, assembler_suffixes, which is added to the list of supported suffixes in the CMake interpreter.
> Fix for Issue 8910 (Meson filters CMake asm files)

- run_project_tests.py
Since 25df6e7d split the iteration over tests to start them from the iteration to collect their results, the variable `name` is only being
set in the first iteratiorn, so all tests are treated as being in the last test category read (probably `wasm`) for `skipppable()` and in the
XML output.
> Fix project tests category name used in skippable() and XML output

- docs/markdown/Reference-manual.md
- mesonbuild/build.py
- test cases/common/22 object extraction/check-obj.py
- test cases/common/22 object extraction/header.h
- test cases/common/22 object extraction/meson.build
QEMU would like to use the result of `extract_objects` in a custom target; examples are using `objcopy`, or using the object files as the key to look up command line arguments in `compile_commands.json`.  This is slightly peculiar and not covered by the test suite, but it mostly works; in order to avoid regressions, add a test case and document it.
One case that fails is when the custom_target inputs include header files, either by way of direct mention (which is common when using sourcesets) or simply because `extract_all_objects` is being used. In both cases ignore the headers and only use the source files, as done already in the case of unity builds.
> extract_objects: fixes, tests and documentation for using the result in a custom_target

- docs/markdown/Builtin-options.md
- docs/markdown/Reference-manual.md
- docs/markdown/snippets/newvsbackends.md
- mesonbuild/backend/backends.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/vs2012backend.py
- mesonbuild/backend/vs2013backend.py
- mesonbuild/cmake/common.py
- mesonbuild/coredata.py
- test cases/common/137 whole archive/meson.build
Hi,
This PR attempts to add Visual Studio 2012/2013 backends, along with implementing `link_whole:` on pre-Visual Studio 2015 Update 2.
The 2012/2013 backend is a quick port from the 2015 one, and the implementation of `link_whole:` is a port from the one that is being done in PR 8802, but adapted for the Visual Studio backends.
Also fix the Visual Studio 2015 version string in `mesonbuild/cmake/interpretor.py`.
> Add Visual Studio 2012/2013 backends

- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/mesonlib/universal.py
- mesonbuild/minstall.py
- run_unittests.py
- test cases/failing/30 invalid man extension/test.json
- test cases/failing/31 no man extension/test.json
- test cases/failing/95 custom target install data/test.json
I've gone to much greater lengths to validate the inputs than was done originally, especially for the `install_mode` argument, this may catch some invalid cases that were being silently ignored before. I've also removed using `None | FileMode` from these, functions, and instead always return `FileMode`, as it's simpler and having a `FileMode` with no values has always been valid.
> Add annotations for the various install_* functions

- mesonbuild/interpreter/interpreter.py
That change introduced when porting to @typed_pos_args breaks gtk4. We
could decide to deprecate/warn but should not error for backward
compatibility.
> interpreter: Empty list used to be allowed in install_headers/man

- mesonbuild/build.py
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreterbase/__init__.py
- mesonbuild/interpreterbase/baseobjects.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/interpreterbase/helpers.py
- mesonbuild/interpreterbase/interpreterbase.py
- mesonbuild/mesonlib/universal.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/pkgconfig.py
- test cases/common/178 bothlibraries/meson.build
This commit introduces a new type of `HoldableObject`: The
`SecondLevelHolder`. The primary purpose of this class is
to handle cases where two (or more) `HoldableObject`s are
stored at the same time (with one default object). The
best (and currently only) example here is the `BothLibraries`
class.
> refactor: Refactor BothLibraries logic

- mesonbuild/compilers/detect.py
As per #8338 - enable use of current Intel Fortran on windows by accommodating the change in reported compiler name.
> Ifort windows oneapi

- mesonbuild/backend/backends.py
- test cases/common/121 object only target/meson.build
- test cases/common/121 object only target/objdir/meson.build
- test cases/common/121 object only target/objdir/source4.c
- test cases/common/121 object only target/objdir/source5.c
- test cases/common/121 object only target/objdir/source6.c
- test cases/common/121 object only target/prog.c
Using objects in library with the vs backend will generate a project with the wrong path to the object.
This merge request adds more tests to this specific test case and fixes the issue with vs backend.
Warning: the test case will leave object files in the source directory.
> build: fix object path for vs backend

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/custom-target-feed.md
- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/scripts/meson_exe.py
- test cases/common/243 custom target feed/data_source.txt
- test cases/common/243 custom target feed/meson.build
- test cases/common/243 custom target feed/my_compiler.py
- test cases/common/243 custom target feed/test.json
An example of a tool not accepting an input file param is [scdoc](https://git.sr.ht/~sircmpwn/scdoc/).
> Add feed arg to custom_target()

- docs/markdown/Commands.md
- docs/markdown/snippets/subprojects_command_parallel.md
- mesonbuild/msubprojects.py
This moves all the code into a class and call its run() method in a
thread. The class queues all logs to print them at the end to avoid
mixing output of multiple actions.
> msubprojects: Run action on all subprojects in parallel

- mesonbuild/compilers/detect.py
- mesonbuild/linkers/linkers.py
[2nd try, since I had some difficulties with my 1st rebasing...] When using the C2000 toolchain under a non Windows-OS meson can't setup or compile the project since the linker binary is hard-coded within `linkers.py`. With this PR the setting from the cross-file will be used.
I'm not sure if
`super().__init__(exelist, for_machine, '', [],`
should be preferred instead of
`super().__init__(exelist or ['cl2000.exe'], for_machine, '', [],`
`exelist or ['cl2000'] `should work for windows and non-windows OS but since this is a cross-compile setup, the compiler must be set within the crossfile and `exelist` will always be **not** empty, so the hard coded `cl2000.exe` isn't needed at all(?).
> C2000: linker uses now binary setting defined within the cross-file

- mesonbuild/modules/unstable_cuda.py
Continuing to use Table 3 in the [Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html) as the reference.
> Add minimum NVIDIA driver version entry in table for newly-released CUDA Toolkit 11.4.0.

- mesonbuild/backend/ninjabackend.py
Currently all arguments are being passed to scan-build as part of the
refactoring of how Meson internally handles arguments, but that's wrong,
only project specific arguments are supposed to be passed.
Fixes: #8818
> backends/ninja: only pass project specific arguments to scan-build

- mesonbuild/msubprojects.py
- mesonbuild/wrap/wrap.py
- run_unittests.py
We need to store the original filename as well as whether the wrap was
redirected in order to properly purge the redirected wrap.
Follow on to https://github.com/mesonbuild/meson/pull/8524. Maybe it is worth backporting.
> Delete redirected wrap files in subprojects purge

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/required_and_disabled_import.md
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/unstable_cuda.py
- mesonbuild/modules/unstable_external_project.py
- test cases/common/67 modules/meson.build
- test cases/common/67 modules/meson_options.txt
- test cases/failing/57 kwarg in module/meson.build
- test cases/failing/57 kwarg in module/test.json
This adds a new `.foud()` method to imported modules, just like programs and dependencies, as well as the required and disabled keyword arguments. This means you can do something like:
```meson
rust = import('unstable-rust', required : false)
if rust.found()
...
endif
```
This simplifies optional module dependencies, as `required`, works with `feature_option`s, and should help smooth things over for projects that want to use alternate Meson implementations that don't have said module, like my progressing Meson++ implementation.
> Add required and disabled to import, modules.found method

- mesonbuild/mdist.py
`meson dist` currently excludes all files starting with `.git`. The actual special files used by Git are `.git/`, `.gitattributes`, `.gitignore` and `.gitmodules`; other files starting with `.git` are not part of revision control metadata. The current behavior can leave users surprised, mainly because it is undocumented (happened to me in #8541).
I've never touched Python, so my solution could be extremely inefficient, and maybe there is a method to avoid duplicating code as I did :)
> dist: only exclude actual git files

- docs/markdown/Users.md
git.archlinux.org has been decomissioned [1]
[1] https://lists.archlinux.org/pipermail/arch-dev-public/2021-June/030466.html
> Users: Update URL for pacman

- mesonbuild/dependencies/dev.py
In LLVMDependencyConfigTool, the members compile_args and required_modules are
either converted to or stored as sets, which do not have a stable ordering. This
results in nondeterministic builds, particularly with required_modules causing
the order in which the LLVM libraries are linked in to the output binaries to
change across independent builds. As any guarantee about ordering for
compile_args is lost by being converted from a list to a set and back, and the
modules added to required_modules was even already sorted once, sort both when
converting them to lists.
> dependencies: Deterministic LLVM compile and link arg ordering

- mesonbuild/compilers/mixins/gnu.py
An `f` was dropped in bd6f46e723813dfadaba1f7c87d3b0b751d05219
> Fix unsupported linker error message

- docs/markdown/snippets/wrc.md
- mesonbuild/modules/windows.py
It has a similar interface to windres, but it produces ELF instead of
COFF binaries. It uses its own preprocessor which doesn't support
creating depfiles, but we can convince it to use the system preprocessor
instead and pass those arguments using the --preprocessor option.
Together with some hacks to override the shared library/executable
suffix and some wine patches [1] this is enough to compile dxvk when
ripping out the hand-rolled rc support.
[1] https://www.winehq.org/pipermail/wine-devel/2021-July/190100.html
https://www.winehq.org/pipermail/wine-devel/2021-July/190098.html
https://www.winehq.org/pipermail/wine-devel/2021-July/190099.html
https://www.winehq.org/pipermail/wine-devel/2021-July/190101.html
> windows: Support wrc resource compiler

- .github/workflows/os_comp.yml
- ci/ciimage/bionic/image.json
- ci/ciimage/fedora/image.json
- ci/ciimage/opensuse/image.json
- data/test.schema.json
- docs/markdown/Contributing.md
- run_project_tests.py
- run_single_test.py
- test cases/frameworks/15 llvm/meson.build
- test cases/frameworks/15 llvm/test.json
- test cases/frameworks/16 sdl2/test.json
- test cases/frameworks/17 mpi/test.json
- test cases/frameworks/25 hdf5/test.json
- test cases/frameworks/26 netcdf/test.json
- test cases/frameworks/29 blocks/test.json
- test cases/frameworks/30 scalapack/test.json
- test cases/frameworks/34 gir static lib/test.json
- test cases/frameworks/4 qt/test.json
Replace the hard-coded list of 'may be skipped' framework tests in `skippable()` with annotations in `test.json` which record 'will be skipped in these specific CI jobs'.
The motivation here is that, at the moment, if something is dropped from any VM image our CI runs on, if it's permitted by `skippable()`, we'll just silently stop testing it.  This is particularly relevant where we don't control the VM image (e.g. on Windows), and has actually happened with boost on Windows (see the comments for commit 5c0cb0547bd52230faff322a33bfeac0eaaeea0d).
> Annotate framework tests with where they are expected to skip in CI

- azure-pipelines.yml
This restricts the pipeline from running on 'non-code' pushes and PRs in the same way that GitHub workflows which run project tests are (although the syntax is different, and must be made more explicit as wildcards aren't supported).
> Add path filter to azure pipelines trigger

- ci/run.ps1
Propagate the run_tests.py exit code, rather than overwriting it with the codecov exit code.
> azure: propagate run_tests.py exit code

- mesonbuild/compilers/mixins/clang.py
Fix #8986
**Motivation for this change**
Calling `clang` without any `-O` option is **NOT** equivalent to calling it with `-O0`.
One important difference is that when debugging, without `-O0` (and even with `-Og`), certain parameter values are marked as `<optimized out>` in GDB;
On the contrary, using `-O0` allows to get the value of any variable.
> Clang: Apply `-O0`

- .github/codecov.yml
code coverage may be interesting to some people as an informational update, but it's really fragile and sometimes obscure, and overall we would really like to NOT have most PRs reporting a red X in the CI overview, when all project/unittests succeeded but codecov decides that by some inscrutbale metric, coverage by % has dropped.
Elegant refactorings are penalized, because removing lines of code or rewriting them to be more compact, means the overall percentage of covered code is "less", even though no uncovered code got added.
Even worse, the coverage reports often erroneously complain that a PR has "added lines #L<num> - L<num> were not covered by tests" even though github helpfully points out they are "Unchanged files with check annotations". Or more generally, codecov claims that …
> coverage: disable the concept of "CI failures"

- mesonbuild/linkers/linkers.py
Somewhere between 0.56 and 0.57, linking using Intel [Visual] Fortran on Windows was broken, due to a failure to specify the target windows subsystem.  This patch restores specification of the /subsystem:xxx argument (where xxx is console, unless otherwise specified by the win_subsystem option.
> Ifort xilink subsystem

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/mixins/islinker.py
- mesonbuild/linkers/linkers.py
For an ELF targets, shared_module() builds a module with SONAME field (using -Wl,-soname argument). This is wrong: only the shared_library() needs SONAME, while shared_module() does not. Moreover, tools such as debian's dpkg-shlibdeps use presence of SONAME field as an indicator that this is shared library as opposed to shared module (e.g., for the module it is okay to have unresolved symbols which are imported from the executable which loads the module, while a library should have all symbols resolved).
This was in fact already the behavior on Darwin.
Fixes: #8746
> Do not add SONAME to shared modules

- mesonbuild/modules/gnome.py
g-ir-scanner does not convert relative -L paths to runtime paths which
are added to `-Wl,-rpath` and `LD_LIBRARY_PATH` / `DYLD_LIBRARY_PATH`
/ `PATH`. This means that the local library will either not be found at
runtime (while building introspection data), or the system-wide
library will be picked instead.
See: `giscanner/ccompiler.py:get_internal_link_flags()` in
gobject-introspection for more details.
This is a regression likely from the time when we moved `@BUILD_ROOT@` from an absolute path to a relative path; the oldest known working version of Meson is 0.55. Both 0.58.1 and 0.59.0rc2 are broken.
> gnome: Always pass absolute -L paths to g-ir-scanner

- mesonbuild/msubprojects.py
If the command fails for one subproject we should still continue with
others. Failed subprojects are reported at the end.
This issue became more problematic when doing parallel tasks because the
reason the command fails was completely hidden by other parallel tasks.
> msubprojects: catch exceptions and continue with others

- docs/markdown/snippets/python_dependency_args_removed.md
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/cmake.py
- mesonbuild/dependencies/coarrays.py
- mesonbuild/dependencies/configtool.py
- mesonbuild/dependencies/dev.py
- mesonbuild/dependencies/dub.py
- mesonbuild/dependencies/framework.py
- mesonbuild/dependencies/misc.py
- mesonbuild/dependencies/pkgconfig.py
- mesonbuild/dependencies/ui.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/pkgconfig.py
- mesonbuild/modules/python.py
- run_unittests.py
I wanted to get us down to one set of python dependency classes, but that's still not achieved here. What is achieved is a complete set of type annotations for the python module (there's still some places where things fail because we need more typing in the interpreter), the use of the `typed_*` decorators where applicable, and the conversion of the mega `PythonDependency` to a dependency factory. The use of a factory allows us to drop a bunch of legacy cruft that had been mostly purged, but was sitll around because of this one dependency.
@xclaesse I dropped the test that checked the pkg_config.pcdep test, but I'm not sure if you were specifically trying to test `.pcdep` or if that was just the method you used to test the module itself. If the latter I can rewrite the test instead.
> Cleanup the python module

- docs/markdown/_include_qt_base.md
- mesonbuild/modules/qt.py
This works for `moc_*` and `ui_files`, but it never could have worked
for `qresources` due to the implementation assuming a `str` or `File`.
To restore previous compatibility I've added `CustomTarget` where it
would have worked, but not where it would have failed, the former would
raised an exception along the lines anyway.
Fixes #9007
> qt: Allow CustomTargets for qt.preprocess source arguments

- docs/markdown/Feature-autodetection.md
- docs/markdown/Unit-tests.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/scripts/coverage.py
- test cases/common/150 reserved targets/coverage-sonarqube/meson.build
Sonarcloud.io only can read the sonarqube based report that gcovr can
produce.  This change enables support for this output in meson and
ninja.
Signed-off-by: Weston Schmidt <Weston_Schmidt@alumni.purdue.edu>
> Add support for gcovr --sonarqube report

- docs/markdown/snippets/Cross_compilation_with_C2000_toolchain_supports_CLA_files.md
- mesonbuild/compilers/mixins/c2000.py
Some TI C2000 controllers own a [Control Law Accelerator](https://software-dl.ti.com/C2000/docs/cla_software_dev_guide/intro.html) (CLA, like some kind of limited co-processor). 
For code that should run on the CLA it is mandatory that the suffix is ".cla", so this PR just adds this suffix to the list of compilable source types.
> C2000 compiler also accepts *.cla files

- mesonbuild/ast/interpreter.py
- mesonbuild/ast/printer.py
- mesonbuild/ast/visitor.py
- run_unittests.py
- test cases/unit/57 introspection/meson.build
Without this PR, introspection fails if any fstrings are present.
> ast: Add dummy "support" for fstrings in the ast package

- mesonbuild/build.py
- test cases/common/49 custom target/meson.build
Fix ERROR: Argument <CustomTargetIndex:...>[0]> in "command" is invalid.
> build: learn to take CustomTargetIndex as custom_target command argument

- unittests/internaltests.py
As we've run into a few programs using ansi escapes in their version
outputs, we'd like to test them as well.
> interenaltests: Add some version strings with ansi escapes in them

- mesonbuild/mesonmain.py
" bat_info = json.loads(bat_json) " may produce error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 ...
Because the vswhere.exe's output is not utf-8 by default
Use UTF-8 encoding for vswhere.exe can fixing it .
> fix bat_info UTF-8 string error

- mesonbuild/dependencies/base.py
GTestDependencySystem (and other similar dep classes) sets
self.is_found=True, but the version check could still fail. In the case
the dependency is not required `ExternalDependency._check_version()`
won't raise an exception and thus the dependency is accepted.
_check_version() sets self.is_found() in the case self.version is not
empty, we should do it too when self.version is empty.
Fixes: #9036.
> Fix when gtest dep is found but does not pass version check

- mesonbuild/modules/dlang.py
These should have been changed from Holders to the base objects, but weren't. If anyone tried to run this on 0.59.0 they'd not get the results they expected, as the objects have been unholdered already.
Found through visual inspection.
> modules/dlang: Fix dependencies that should have been updated

- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- test cases/cython/2 generated sources/meson.build
We should have been using `.get_subdir()`, not `.subdir` as `CustomTargetIndex` classes don't have a `.subdir` attribute, just the `.get_subdir()` method.
> Fix using CustomTargetIndex as a cython source

- docs/markdown/Commands.md
- docs/markdown/Installing.md
- docs/markdown/snippets/relative_destdir.md
- mesonbuild/minstall.py
- unittests/allplatformstests.py
Meson already works like that, except in do_copydir() that requires
absolute destdir. Better explicitly support that instead of leaving it
undefined and unconsistent.
> destdir: Allow relative to build directory

- mesonbuild/dependencies/boost.py
- test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/include/boost/version.hpp
- test cases/frameworks/35 boost symlinks/boost/include/boost
- test cases/frameworks/35 boost symlinks/boost/lib/boost_python-vc142-mt-gd-x32-0_3.lib
- test cases/frameworks/35 boost symlinks/boost/lib/boost_python-vc142-mt-gd-x64-0_3.lib
- test cases/frameworks/35 boost symlinks/boost/lib/boost_regex-vc142-mt-gd-x32-0_3.lib
- test cases/frameworks/35 boost symlinks/boost/lib/boost_regex-vc142-mt-gd-x64-0_3.lib
- test cases/frameworks/35 boost symlinks/boost/lib/libboost_python.so.0.3.0
- test cases/frameworks/35 boost symlinks/boost/lib/libboost_regex.so.0.3.0
- test cases/frameworks/35 boost symlinks/meson.build
- test cases/frameworks/35 boost symlinks/nativefile.ini.in
This does two things:
* allows the .so files to be symlinks
* searches `lib` and `lib64` in `BOOST_ROOT` even if it finds lib
directories from the compiler
The first condition is needed for the homebrew on macs because certian
boost modules are provided by seperate packages and are put together in
a directory with symlinks to the .so files. The both conditions are
needed for high performace computing environments where dependencies are
often provided in nonstandard directories with symlinks
> Relax restrictions on detecting boost dependency

- mesonbuild/scripts/coverage.py
- test cases/common/243 escape++/meson.build
- test cases/common/243 escape++/test.c
- unittests/allplatformstests.py
Gcovr interprets exclude filters, as passed to the -e option, as
regexes. Since we want to exclude a raw path, the argument must be
escaped.
> Escape path in exclude filter passed to gcovr

- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/interpreterbase/decorators.py
- run_mypy.py
This also fixes the type checking of these keyword definitions.
@xclaesse, this should fix the issues you're seeing if you rebase on this
> Split keyword definitions from interpreter into their own module

- mesonbuild/minstall.py
On linux system ldconfig needs to be called to update
the ld.so.cache to be able to load libraries from
/usr/local/lib/x86_64-linux-gnu on debian based
distributions for example.
> install: apply ldconfig at the end of the install

- mesonbuild/modules/__init__.py
- mesonbuild/modules/gnome.py
This fix kwargs not going through typed_kwargs() decorator that sets
defaults.
Fixes: #9009
> modules: Add API to add test

- mesonbuild/dependencies/pkgconfig.py
- test cases/unit/97 link full name/.gitignore
- test cases/unit/97 link full name/libtestprovider/meson.build
- test cases/unit/97 link full name/libtestprovider/provider.c
- test cases/unit/97 link full name/proguser/meson.build
- test cases/unit/97 link full name/proguser/receiver.c
- unittests/linuxliketests.py
fixs: #9000 Meson not correctly process with -l:xxx.a link arguments in pkgconfig .pc file.
see also: https://stackoverflow.com/questions/48532868/gcc-library-option-with-a-colon-llibevent-a
> pkg-config: support for `-l:libfoo.a`

- mesonbuild/modules/__init__.py
> modules: Fix typo in state.test()

- mesonbuild/backend/vs2010backend.py
This fixes the `.vcxproj` output for native targets during cross compilation using vs backends.
Tested by using the `vcvarsall.bat amd64_arm64` cross compilation toolchain and the `cross/arm64cl.txt` file.
> Fix native targets for vs backend cross compilation

- mesonbuild/modules/gnome.py
When sending them to the introspection scanner, we must always filter
all compiler and linker flags, because g-ir-scanner does not accept any
random argument but only a specific subset.
Fixes: #8876
> gnome: Filter all compiler and linker flags

- mesonbuild/interpreter/interpreter.py
This is a regression when porting to typed_pos_args().
> interpreter: Fix spurious warning in configure_data()

- test cases/frameworks/8 flex/lexer.l
- test cases/frameworks/8 flex/prog.c
This adds the noyywrap option so flex doesn't wait for more input once
we reached EOF. This also adds the nounput and noinput options to fix
compilation warnings.
We can now run the test as expected.
> Make the flex test case work

- docs/markdown/snippets/msvc_cplusplus_define.md
- mesonbuild/compilers/cpp.py
- test cases/windows/18 msvc cplusplus define/main.cpp
- test cases/windows/18 msvc cplusplus define/meson.build
- test cases/windows/3 cpp/meson.build
- unittests/windowstests.py
accurate
Otherwise it always returns the value for c++98.
TODO: needs test
TODO: needs docs
> compilers/cpp: Set the MSVC macro to make the __cplusplus define

- test cases/cuda/16 multistd/meson.build
Should fix Arch Cuda CI failure.
> Disable asan memory leak checks on a Cuda test.

- run_project_tests.py
Fixes regression in commit 75688240cfca7eed08c2754daa784c9bd1a70a73. Even though this function is *currently* only invoked on Windows, these environment variables may not actually exist -- and apparently don't in at least the "UnusedMissingReturn / windows" test run, which... did not get triggered by that commit, since it only edited the testsuite runner, not any test cases. \o/
> tests: make detecting broken compilers always run without tracebacks

- docs/markdown/snippets/remove_unittest_args_method.md
- mesonbuild/compilers/c.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/fortran.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/coredata.py
- mesonbuild/interpreter/compiler.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreterbase/baseobjects.py
- mesonbuild/interpreterbase/decorators.py
- run_mypy.py
- unittests/allplatformstests.py
- unittests/baseplatformtests.py
This uses a full set of `typed_pos_args` and `typed_kwargs` to the `interpreter/compiler` module. In doing this I discovered several deficiencies in the `compiler` annotations, as well as one case of undesirable behavior for the type checkers.
I did remove the `unittest_args` method, which has been marked in the docstring as deprecated for some time, as well as not being documented. I feel like given those two features, it's fine to remove it.
> Add type checking for the Compiler and RunResult objects

- run_project_tests.py
This reverts commit 75688240cfca7eed08c2754daa784c9bd1a70a73
Should've been fixed by c95bffb295dd8ae12dd37c9a6c33372a20cf9a68. Let's see if it was.
> Revert "Disable vs2017 + 32bit Rust combo as it is broken."

- mesonbuild/backend/ninjabackend.py
- run_project_tests.py
- test cases/rust/5 polyglot static/meson.build
* test cases/rust: clang-cl also needs extra_winlibs
* rust targets: lld-link is the same as link for static libs
> Revert "Disable Rust + clangcl." and fix the actual bugs it was demonstrating

- mesonbuild/backend/ninjabackend.py
- mesonbuild/scripts/depscan.py
Currently, we write each file to the command line, but this can result in
situations where the number of files passed exceeds OS imposed command
line limits. For compilers, we solve this with response files. For
depscan I've chosen to use a JSON list instead. JSON has several
advantages in that it's standardized, there's a built-in python module
for it, and it's familiar. I've also chosen to always use the JSON file
instead of having a heuristic to decide between JSON and not JSON,
while there may be a small performance trade off here, keeping the
implementation simple with only one path is wort it.
Fixes #9129
> backends/ninja: write depscan input files to json

- .github/workflows/macos.yml
- test cases/frameworks/1 boost/meson.build
Previously the meson test case would only test boost-python on linux.
With the #7909 it is now possible to use boost-python on macOS/homebrew.
This enables the boost-python test on both linux and macOS.
It also uses python.extension_module() instead of shared_library to make the
python extension module.
> Test boost-python on macOS

- data/test.schema.json
- docs/markdown/Contributing.md
- mesonbuild/modules/python.py
- run_project_tests.py
- test cases/python/2 extmodule/blaster.py.in
- test cases/python/2 extmodule/ext/meson.build
- test cases/python/2 extmodule/ext/nested/meson.build
- test cases/python/2 extmodule/ext/tachyon_module.c
- test cases/python/2 extmodule/ext/wrongdir/meson.build
- test cases/python/2 extmodule/meson.build
- test cases/python/2 extmodule/test.json
Currently it installs to libdir instead.
While I am at it, I had to extend the testsuite to support configuring via test.json, if a file is a python file and needs to be configured with python-specific path expansions.
Fixes #6331
> make python extension_module install to the documented location

- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/unstable_rust.py
The `bindgen` method of the rust module currently doesn't use the `typed_kwargs` helper, and instead still relies on `permittedKwargs` with  hand rolled type checking. The end result is a small diff, with nice consistant error messages and less re-used code. Some of the `KwargInfo types can even be shared with other `CustomTarget` wrappers in the future, so there may be more code sharing savings.
> Fully type check rust.bindgen

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/xcodebackend.py
- mesonbuild/build.py
- mesonbuild/compilers/compilers.py
- mesonbuild/environment.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/mesonlib/universal.py
- run_mypy.py
My goal was to add type annotations to backend/backends.py, as it seemed like a good starting point for looking into the backend. This ended up requiring a lot of fixes for the build module as well, and revealed several issues in already typed modules, like mesonlib. I've split each change into a single patch, as this is good practice, and makes bisecting easier for regressions.
> Type annotations and fixes for backend/backends

- docs/markdown/_include_qt_base.md
- docs/markdown/snippets/qt_module_generated_inputs.md
- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/qt.py
This has two things in it, a fix for #9007, in which CustomTargets were erroneously excluded as inputs to the various `qt.preprocess` arguments, and then a series of patches to make the various `compile_*` arguments accept all forms of generated inputs, not just `CustomTargets` (including CustomTargetIndex and GeneratedList inputs`.
@nirbheek: the first patch to this series should be pulled for 0.59.1, but the rest should not.
@ximion: can you see if the first patch fixes your issue?
> Qt module generated sources

- unittests/linuxliketests.py
using `TestCase.addCleanup` is both neat and tidy, and also ensures that
the cleanup will be done, even if the test fails.
> unittests: Ensure that symlink is removed after tests complete

- mesonbuild/interpreter/interpreter.py
We recommend people use declare_dependency and access it via dependency() in a parent project. But this requires a wrap file (or to use override_dependency and an explicit subproject call).
Let's actually mention that.
Fixes #9146
> Fix incomplete guidance on solving sandbox violations

- mesonbuild/interpreterbase/interpreterbase.py
- test cases/failing/1 project not first/test.json
Explicitly mention that the project definition is invalid, and clarify that project is `project()` -- a function.
Also try to walk the directory tree upward, and if there are parent meson.build files, just say this isn't the project root, and "maybe you meant to run meson there instead?"
This won't catch calls to subdir('foo/bar') but we can't be perfect, only better than before and catch the *majority* of such cases, and hopefully it's a lot more clear if meson protests that the project is "invalid, there is no project() function", where the user should look for a potential solution.
Fixes #3426
> use a more informative error message for invoking meson in a subdir

- mesonbuild/munstable_coredata.py
One percent-formatted string had a .format() method style placeholder and thus never output anything other than
```
TypeError: not all arguments converted during string formatting
```
The other error may be due to changing format elsewhere, because it attempted to treat an entire tuple as though it only contained one element. Based on context, it's clear this is supposed to be the actual dependency name, but the internal representation may have changed over time.
These fixes allow the command to run to completion successfully; of course it is still unstable and possibly not actually maintained, since it's been broken for 2 years and no one actually noticed.
> fix coding errors in unstable-coredata subcommand

- mesonbuild/interpreterbase/interpreterbase.py
Follow-up on commit 5a7b8d86d0c455680096d47cb87f0de08c0954ac
Sometimes, we find a parent meson.build which is also malformed, and we shouldn't suggest that maybe the user meant to use that, if it isn't a valid project() either. Do a rough and dirty check to see if the very first line is a project() declaration, and if not, don't try to be clever and suggest using it.
The "invalid source tree" error suffices here, since we're not absolutely sure meson can be successfully run in that parent directory and actually advising people about the wrong location is a lot more confusing than just saying "please figure this out yourself, here is what to look for".
Granted, we miss cases where project() comes after blank lines and/or comments, but doing a full AST parse here is excessively overkill and …
> use even more informative error message for invoking meson in a subdir

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/static_fallback_override.md
- mesonbuild/interpreter/dependencyfallbacks.py
- mesonbuild/interpreter/mesonmain.py
- test cases/common/98 subproject subdir/meson.build
- test cases/common/98 subproject subdir/subprojects/sub_static/meson.build
- unittests/allplatformstests.py
It should build the fallback subprject with default_library=static and
override the dependency for both static=True and static kwarg not given.
Fixes: #8050.
> interpreter: Fix dependency(..., static: true) fallback

- mesonbuild/modules/java.py
It should apply to the *next* stable release.
Reported-by: Tristan Partin <tristan@partin.io>
> java module: fix FeatureNew version

- mesonbuild/modules/gnome.py
The tool needs to run the preprocessor (but does not actually produce compiled outputs), and meanwhile ignores lots of flags it doesn't think it needs. In the case of -D_FORTIFY_SOURCE=...  this is only valid if -O is there too, but otherwise spits out confusing warnings.
The warnings are spurious and can be safely ignored, but in this case let's go the extra mile and fix g-ir-scanner's upstream bug by removing the fortify flag first.
Fixes #9161
> gnome: don't let fortify defines into the g-ir-scanner after stripping -O

- mesonbuild/interpreter/compiler.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreter/mesonmain.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/modules/python.py
- mesonbuild/modules/qt.py
- test cases/failing/23 rel testdir/test.json
- unittests/internaltests.py
Currently we're allowing default values to be values that we don't allow as inputs, that creates some real, confusion as `ContainerTypeinfo` doesn't assume that's going to happen. This series adds assertions to make sure we're doing that right thing, and fixes all the cases of doing the wrong thing.
> Validate default values for KwargInfo

- mesonbuild/modules/gnome.py
Otherwise, if these environment variables already exist, they will
override values we set for the developer environment.
> gnome: Prepend devenv, not append

- mesonbuild/mcompile.py
`ninja -l` accepts a double. We should do the same.
Bug: https://bugs.gentoo.org/810655
> mcompile: treat load-average as a float

- mesonbuild/modules/python.py
We use distutils, not setuptools, for probing information.
> python module: fix error message mentioning setuptools

- mesonbuild/environment.py
- unittests/internaltests.py
I've added aarch64_be, as well as some unit tests. I know this is a bit of a nitty unittest, and in some ways is a "test what I say" case, but these are getting big enough and complicated enough that I think it warrants tests, especially since many of these values can only be tested on specific operating systems with specific cpus, some of which are quite rare. I've also thrown in a few type annotations :)
Fixes #9191
> Handle aarch64_be as a cpu family

- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/mesonmain.py
- mesonbuild/interpreter/type_checking.py
EnvironmentVariablesObject is a somewhat odd class, it's effectively a holder for `build.EnvironmentVariables`, but it it's not. This series converts it into one, and adds some additional type checking and validation.
My motivaiton here is that doing this simplifies add the type checking decorators to the various target interfaces, as we know we'll have an EnviornmentVariables object. This also is nice, in that it means that all cases where an and EnvironmentVariables is expected can get one, instead of each caller having to go through the dance of "is this a list? a dict? a str? an EnviornmentVariablesObject?" Instead that's all done in the inerpreter, and the lower layers always get a ciearn, EnvironmentVaraibles object.
> Make EnvironmentVariablesObject a  holder

- docs/markdown/snippets/comp_error.md
- mesonbuild/ast/interpreter.py
- mesonbuild/interpreter/__init__.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/primitives/__init__.py
- mesonbuild/interpreter/primitives/integer.py
- mesonbuild/interpreterbase/__init__.py
- mesonbuild/interpreterbase/_unholder.py
- mesonbuild/interpreterbase/baseobjects.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/interpreterbase/interpreterbase.py
- mesonbuild/interpreterbase/operator.py
- run_mypy.py
- test cases/common/16 comparison/meson.build
- test cases/failing/50 executable comparison/test.json
The goal of this PR is to introduce a foundation for holderifying all the primitive types that currently need special logic in `InterpreterBase`. The end goal is to just have `InterpreterBase` deal with method and operator calls to `InterpreterObjects`.
I have only added an `IntegerHolder` to keep (for once) the diff on the small side. The downside here is that some extra logic in `InterpreterBase` is required to support a mix of primitive holders and old-style primitive handling while the conversion process is in progress.
Finally, the long deprecated/undefined behavior comparisons with `==` and `!=` for objects with different types has been turned into a hard error.
> interpreter: Add IntegerHolder

- mesonbuild/interpreter/interpreter.py
- mesonbuild/mesonlib/universal.py
- unittests/internaltests.py
Instead of using an object that happens to be unpicklable to ensure the Interpreter isn't pickled, we can just make it an error to call the dunder methods used for pickling. I've also added a test for this, to ensure it remains working in the future.
> replace `an_unpicklable_object` with proper python dunder methods

- docs/markdown/snippets/msvc_utf8.md
- mesonbuild/compilers/mixins/visualstudio.py
- test cases/windows/18 msvc charset/iso-8859-1.c
- test cases/windows/18 msvc charset/meson.build
- test cases/windows/18 msvc charset/meson_options.txt
- test cases/windows/18 msvc charset/utf8.c
- unittests/windowstests.py
Currently every project that uses UTF8 for its source files must add
'/utf-8' argument otherwise they don't work non-English locale MSVC.
Since meson.build itself is assumed to be UTF8 by default, seems better
to assume it for source files by default too.
For example:
- https://gitlab.freedesktop.org/gstreamer/gst-build/-/blob/master/meson.build#L62
- https://gitlab.gnome.org/GNOME/glib/-/blob/main/meson.build#L29
> msvc: Assume UTF8 source by default

- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/clang.py
Clang has a peculiar behavior, that it seems to allow functions that exist in c headers on some OSes/libc implementations even if the current one doesn't provide that function. For example, `strlcat` is available on the BSDs and Solaris, but not in glibc. Despite this running `cc.has_header_symbol('string.h', 'strlcat')` on glibc with clang will result in a warning, but a successful return code; while GCC will error. This does not work for never defined symbols, such as a `foobar`. To ensure that clang correctly errors in these cases Meson should add the `-Werror=implicit-function-declarations` to clang's check arguments.
Fixes #9140
> Clang should error for all implicit function checks

- mesonbuild/interpreter/dependencyfallbacks.py
- test cases/failing/114 allow_fallback with fallback/meson.build
- test cases/failing/114 allow_fallback with fallback/test.json
That used to abort in previous Meson versions but 0.59 stopped
forbidding that by mistake.
> dependency: fallback and allow_fallback are mutually exclusive

- docs/markdown/snippets/run_target-depends.md
- mesonbuild/backend/backends.py
- mesonbuild/build.py
- test cases/unit/65 alias target/meson.build
- test cases/unit/65 alias target/subdir/meson.build
- unittests/allplatformstests.py
run_target: do not yield broken names with subdirs
A run_target object created in a subdir/meson.build always has a ninja rule name of "name", not "subdir/name".
Fixes #9175
> run_target depends

- mesonbuild/modules/i18n.py
And more accurate too, TBH. Currently it says it is building "lang.mo", even though it is actually building "domain.mo" inside lang/LC_MESSAGES/.
Since meson loudly complains if I try to name the display name "lang/domain.mo", name it with a dash instead of a slash. The actual name isn't a priority here IMO, and this is nicely readable.
> make the display name of a gettext translation build, look prettier

- mesonbuild/wrap/wrap.py
"ERROR: Git program not found" is both highly true, and somewhat inscrutable. Sure, looking at the line number you can basically figure out that subproject('something') must somehow need git to operate, but that may not be immediately obvious.
Make mention of the fact that it is needed to "download foo.wrap".
Fixes #7764
> log a more informative error when wrap-git subprojects cannot be downloaded

- mesonbuild/mesonlib/universal.py
WSL 2 removes the "Microsoft" from `platform.version` but leaves it inside `platform.release`. This lets us detect both types of WSL without issue.
Followup from #9208
> Improve WSL detection

- mesonbuild/mdist.py
- unittests/allplatformstests.py
- unittests/subprojectscommandtests.py
Fixes various inconsistencies:
- gitattributes is respected
- export-subst
- export-ignore
- submodules with relative paths are not checked out relative to the
local clone (which does not work anyway)
- no need to manually remove gitfiles with inaccurate heuristics
Fixes #2287
Fixes #3081
Fixes #8144
> mdist: use git archive with git repositories for correctness

- mesonbuild/compilers/mixins/clike.py
Modern GCC and ICC support the `-framework` flag. Without this change, configuration results in:
```
ERROR: Dependency "appleframeworks" not found, tried framework
```
Fixes #8792
Fixes #8733
> Support for appleframeworks with GCC and Intel

- mesonbuild/_typing.py
- mesonbuild/dependencies/base.py
- mesonbuild/mlog.py
- test cases/unit/72 summary/meson.build
- unittests/allplatformstests.py
Dependencies are currently printed as
[<mesonbuild.mlog.AnsiDecorator object at 0x7faa85aeac70>, ' ', <mesonbuild.mlog.AnsiDecorator object at 0x7faa85aeab50>]
This was introduced in commit adb1b2f3f6ad54b346348ec6e5b8d96f2f7ba0a6, due to
an incorrect type annotation on the AnsiText constructor.  Fix both the
annotation and the usage.
This is a regression in 0.59.
> summary: fix dependencies

- mesonbuild/compilers/objc.py
- mesonbuild/compilers/objcpp.py
The clang compiler now reimplements and re-checks the c_std and cpp_std options in order to use them for objc as well, but it didn't consistently support the same options. First it completely excluded all the gnu ones, and then it added a handful of them but not for C++.
Be fully consistent -- or at least as consistent as we can be, given a minimally working fix. (The C/C++ compiler mixin actually gates different stds depending on detected clang version, we do not do that here.)
Fixes regression in c54dd63547b030e3d9feee694ec6f49c434f0df8
Fixes incomplete fix from #8766 (which didn't fix objcpp at all)
Fixes #9237
> objc/objcpp compiler: accept all gnu stds corresponding to c/c++ stds

- mesonbuild/compilers/detect.py
- mesonbuild/compilers/fortran.py
- mesonbuild/dependencies/misc.py
- mesonbuild/linkers/__init__.py
- mesonbuild/linkers/linkers.py
- run_project_tests.py
- test cases/fortran/12 submodule/child.f90
Not sure whether you need a specific test case with this (since it's a proprietary compiler); here's a shell script I used for testing:
```sh
#!/bin/sh
set -eux
pdir=nagfor_proj
bdir=build
export FC=nagfor
mkdir -p "${pdir}"
cd "${pdir}"
main_file="prog.f90"
cat <<EOF > "${main_file}"
Program p
Interface
Function f(i)
Integer, Intent (In) :: i
Integer :: f
End Function
End Interface
If (f(11)/=53) Stop 'FAIL'
Print *, 'ok'
End Program
EOF
lib_file="f.f90"
cat <<EOF > "${lib_file}"
Function f(i)
Integer, Intent (In) :: i
Integer :: f
f = i + 42
End Function
EOF
cat <<EOF > meson.build
project('nagfor test', 'fortran', meson_version: '>=0.59.99')
both_libs = both_libraries('mylib', '${lib_file}')
ste = executable('stprog', '${main_file}', link_with: both_libs.get_static_lib())
she = …
```
> Implemented some missing operation for the NAG Fortran Compiler.

- docs/markdown/Machine-files.md
Older meson versions would not honor the `<lang>_args` and `<lang>_link_args` in the built-in
options section, add a note about this to the relevant section as it can cause quite some surprises
when using a crossfile with an older meson version.
> docs: add note about built-in options support

- mesonbuild/modules/qt.py
- test cases/frameworks/4 qt/main.cpp
- test cases/frameworks/4 qt/meson.build
- test cases/frameworks/4 qt/qt4_lang.qrc
- test cases/frameworks/4 qt/qt4embedded_fr.ts
- test cases/frameworks/4 qt/qt5_lang.qrc
- test cases/frameworks/4 qt/qt5embedded_fr.ts
Regression in commit d7ac2f10655433989e5e17867b6c8ef428fd39e8 since self.{tool_name} is not how it used to be tracked, and the "found" dictionary is a legacy of the old location.
> qt module: correctly register a found tool and stop looking for it

- mesonbuild/msetup.py
The option for layout=flat is horribly broken beyond repair in various circumstances which no one really keeps track of, no one seems to actually use it in practice for any good reason, CI doesn't test it, no one is committed to maintaining it, etc. etc. etc.
How is it broken? Well:
- projects doing trivially reasonable things, such as generating "foo/util.py" and "bar/util.py", create clashing output names. This will never, ever, ever, ever work with layout=flat. This is by design, because they are fundamentally incompatible goals.
- Generally, meson assumes all over the place that files go in their subdir output directories, and since it is never tested in CI, these assumptions go unnoticed...
- Sometimes meson itself generates files in subdir-based layouts, for example my recent …
> Die, layout=flat, die

- mesonbuild/backend/vs2010backend.py
- unittests/allplatformstests.py
Alias commands did not work with the vs backend, due to trying to access
target.command[0] with an empty command. Fix this by just not emitting a
CustomBuild node for alias targets - the project references are enough to
trigger the necessary actions.
Fixes: #9247
> backends/vs: Do not emit dummy command for alias_command().

- mesonbuild/compilers/mixins/c2000.py
While working with meson and the `C2000` toolchain, I noticed that changes in the header file did not result in a recompilation of the corresponding source files. Since the function `get_dependency_gen_args()` was not implemented, this is not a big surprise.
> C2000: Added depfile generation for incremental builds

- mesonbuild/msubprojects.py
This command is useful to e.g. update a cloned subproject which does not have its packagefiles merged, or which has updated packagefiles. This does not strictly require internet, so if we can satisfy the ref, simply log a warning and continue.
This enables a workflow where for network-isolated builds, the subproject is cloned and moved into place and later on the build orchestrator runs `meson subprojects update` without a network interface to initialize the subproject.
While we are at it, if the revision is a commit hash we can immediately tell if we don't even need to *try* finding updates. So short-circuit that.
This ameliorates a workflow concern raised in https://github.com/Plagman/gamescope/issues/61
> msubprojects: gracefully handle being offline

- mesonbuild/backend/ninjabackend.py
- test cases/fortran/7 generated/meson.build
- test cases/fortran/7 generated/mod3.f90
After we changed to the depscan tool consuming a json file, we lost the correct ordering dependencies, so we need to add those back.
Fixes: #9258
> fix depscan json depends

- mesonbuild/compilers/fortran.py
- test cases/fortran/1 basic/simple.f90
- test cases/fortran/10 find library/main.f90
- test cases/fortran/12 submodule/parent.f90
- test cases/fortran/13 coarray/main.f90
- test cases/fortran/14 fortran links c/f_call_c.f90
- test cases/fortran/16 openmp/main.f90
- test cases/fortran/18 first_arg/main.f90
- test cases/fortran/19 fortran_std/legacy.f
- test cases/fortran/19 fortran_std/std2003.f90
- test cases/fortran/19 fortran_std/std2008.f90
- test cases/fortran/19 fortran_std/std2018.f90
- test cases/fortran/19 fortran_std/std95.f90
- test cases/fortran/2 modules/prog.f90
- test cases/fortran/20 buildtype/main.f90
- test cases/fortran/21 install static/main.f90
- test cases/fortran/5 static/main.f90
- test cases/fortran/6 dynamic/main.f90
- test cases/fortran/8 module names/test.f90
This PR ensures that the test programs can be compiled with standards conforming compilers like conda's `gfortran` and others.
- Fixes compiler check
- Updates tests
- ~Changes `.gitignore` to ignore generated `fortran`~
> Fix fortran

- mesonbuild/programs.py
This will always be wrong, because when a directory component is provided we need to match an exact filename on a manual search path, for example find_program with dirs: or the current meson.build subdir.
If we ever get this far, shutil.which will do the same "is there a dirname, if so just check whether the filename exists relative to
cwd"... except that the documented meson lookup path is that we check relative to meson.build subdir, not relative to the cwd, and the cwd could be anything, but is probably the root sourcedir.
Since internally, meson does not actually os.chdir into the sourcedir, it could be absolutely anything at all, though.
...
The actual returned name for shutil.which(name) given a literal pathname with a directory component is "return name" without adding the absolute …
> during executable lookup, do not search PATH if a directory component is given

- mesonbuild/backend/ninjabackend.py
When setup creates a Visual Studio environment, a message is logged
which contains a path to the build directory. Typically, this path is
converted to a relative path prior to printing. If the path cannot be
converted to a relative path (e.g., because buildpath is on a different
drive from the cwd), print out the full path instead of failing with an
unhandled exception.
> ninjabackend/vs: handle builddir on different drive than cwd

- mesonbuild/mtest.py
Currently, if the test fails to produce XML (or valid XML) then the test
fails with a backtrace. It's actually pretty easy to get into this
situation, a total failure of the test will result in no XML being
written (this can happen, for example, if rpaths to gtest are not
correctly set up). If we can't read the test, go ahead and complete
using `TestRunExitCode.complete()`, which will fail for the bad exit
code.
> mtest: Allow gtest protocol test to fail more gracefully

- mesonbuild/compilers/mixins/clang.py
- mesonbuild/interpreter/interpreter.py
`-Oz` is the appropriate flag to use when you want to produce the smallest possible binary, and is one would expect when setting `optimization` to `s` or using the `minsize` build type.
More info [here](https://android.googlesource.com/platform/ndk/+/master/docs/ClangMigration.md#versus) 
Related to #7176
> Use `-Oz` when `optimization=s` in Clang

- mesonbuild/backend/vs2010backend.py
- test cases/windows/19 vs install static lib with generated obj deps/both_lib_source.c
- test cases/windows/19 vs install static lib with generated obj deps/copyfile.py
- test cases/windows/19 vs install static lib with generated obj deps/generated_source.c
- test cases/windows/19 vs install static lib with generated obj deps/meson.build
- test cases/windows/19 vs install static lib with generated obj deps/static_lib_source.c
- test cases/windows/19 vs install static lib with generated obj deps/test.json
When a static library B to a static library A with generated sources, B
directly references the object file corresponding to the generated source in
A. For that reference in B object_filename_from_source() is used.  But A did
not specify the object file name, ending up with cl.exe's default.
This contains the test @jenatali wrote in #9259 / #9235
> backends/vs: Set ObjectFileName for generated sources.

- docs/markdown/Cython.md
- docs/markdown/snippets/cython-c++-intermediate.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/compilers/cython.py
- mesonbuild/interpreter/interpreter.py
- test cases/cython/1 basic/libdir/storer.h
- test cases/cython/1 basic/test.json
This patch adds a new meson built-in option for cython, allowing it to
target C++ instead of C as the intermediate language. This can, of
course, be done on a per-target basis using the `override_options`
keyword argument, or for the entire project.
WIP: there are still some corners here in regards to the automatic
addition of C and C++ compilers when using cython that need to be
resolved.
Fixes #9015
> Allow cython to be transpiled to c++

- mesonbuild/build.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/fortran.py
- test cases/fortran/9 cpp/meson.build
This should be done in all cases of language_stdlib_only_link_flags, but
I don't have access to all of the compilers to test it.
This is required in cases where object files created by gfortran are
linked using another compiler with a different default search path, such
as gfortran and clang together. And also on nixos, where no compilers
implementation libs are in another compiler's path.
> compilers: Add default search path stdlib_only_link_flags

- mesonbuild/mlog.py
- mesonbuild/mtest.py
I was annoyed by e.g. the meson's test subcommand's output's usage of the scissors emoji that never displayed properly in my development environments and set out to improve the look and feel of the test subcommand's output. 
In the commit message I write:
> This change set aims to fix various "issues" seen with the current
> implementation. The changes can be summarized with the following list:
> 
> * Replace emojis and spinners with multiline status displaying the name
>   and running time of each currently running test.
> * The test output (especially in verbose mode or when multiple failing
>   tests' output gets printed out) can get confusing. Try to make the
>   output easier to read and grasp. Most notable change here is the
>   addition of the test number to the beginning of each …
> mtest: fix test output issues (in console)

- docs/markdown/Reference-manual.md
- docs/markdown/Syntax.md
- docs/markdown/snippets/str_join.md
- mesonbuild/ast/interpreter.py
- mesonbuild/build.py
- mesonbuild/interpreter/__init__.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreter/mesonmain.py
- mesonbuild/interpreter/primitives/__init__.py
- mesonbuild/interpreter/primitives/string.py
- mesonbuild/interpreterbase/__init__.py
- mesonbuild/interpreterbase/_unholder.py
- mesonbuild/interpreterbase/baseobjects.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/interpreterbase/helpers.py
- mesonbuild/interpreterbase/interpreterbase.py
- test cases/common/35 string operations/meson.build
- test cases/common/35 string operations/test.json
- test cases/failing/11 object arithmetic/test.json
- test cases/failing/12 string arithmetic/test.json
Another commit in my quest to rid InterpreterBase from all higher
level object processing logic.
Additionally, there is a a logic change here, since `str.join` now
uses varargs and can now accept more than one argument (and supports
list flattening).
> interpreter: Introduce StringHolder

- .pylintrc
- ci/run.ps1
- docs/markdown/snippets/rust-clippy-driver-support.md
- docs/markdown/snippets/rustc-improvements.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/__init__.py
- mesonbuild/compilers/detect.py
- mesonbuild/compilers/rust.py
- test cases/rust/1 basic/clippy.toml
- test cases/rust/1 basic/prog.rs
- unittests/allplatformstests.py
- unittests/baseplatformtests.py
This pull request fixes a few bugs for Rust, plus implements a number of missing compiler abstractions like werror, warn arguments, and pic. Finally it adds support for using clippy, which is a rust linter that wraps rustc, but doesn't provide the necessary information in it's output for Meson to figure that out.
> More enhancements for Rust + clippy support

- mesonbuild/dependencies/dev.py
Handle is_sunos() machines in __machine_info_to_platform_include_dir
> dependencies: Add JDK system dependency for Solaris

- unittests/linuxliketests.py
Running 'cc --version' finds the Solaris Studio C compiler, not gcc,
and it doesn't support --version.
> unittests: Make test_prelinking work on Solaris

- mesonbuild/interpreter/interpreter.py
- test cases/unit/48 reconfigure/subprojects/sub1/meson.build
- unittests/allplatformstests.py
This was allowed by accident despite what meson said would work, because in python a bool counts as a subclass of int.
> fix message function accepting bools and casting to string

- docs/markdown/Reference-manual.md
- docs/markdown/snippets/mixed_language_linker_tests.md
- mesonbuild/compilers/__init__.py
- mesonbuild/compilers/compilers.py
- mesonbuild/interpreter/compiler.py
- mesonbuild/mesonlib/universal.py
- test cases/unit/97 compiler.links file arg/meson.build
- test cases/unit/97 compiler.links file arg/test.c
- unittests/allplatformstests.py
These patches makes it possible to test that the C++ driver (e.g. g++) can be used to link C objects, for example to check that the C compiler's `libsanitizer` is compatible with the one included by the C++ driver.
For example `meson.get_compiler('cpp').links(files('main.c'))` results in the following log:
```
Command line:  cc /home/pbonzini/ff/main.c -o /home/pbonzini/ff/build/meson-private/tmpa0bmxj_m/output.obj -pipe -D_FILE_OFFSET_BITS=64 -O0
Command line:  c++ /home/pbonzini/ff/build/meson-private/tmpa0bmxj_m/output.obj -o /home/pbonzini/ff/build/meson-private/tmpa0bmxj_m/output.exe -O0
```
Fixes: #7703
> Use appropriate compiler for the source file for "links" tests with file argument

- CODEOWNERS
"git shortlog" lists myself as the main contributor to `meson test`. Add myself to CODEOWNERS so that I automatically get subscribed to pull requests and can help with review.
> CODEOWNERS: add myself as "meson test" owner

- mesonbuild/modules/python.py
- test cases/python/1 basic/meson.build
- test cases/python3/1 basic/meson.build
Hardcoding the name is fragile, and enabling it based on the existence of
/etc/debian_version (as the is_debianlike helper does) will result in
incorrect paths if the Python binary is not provided by Debian.
Using the deb_system distutils scheme instead makes sure we use the
install path from the current interpreter, which Debian could change
between releases, and gives us the correct value on Python installations
that are not provided by Debian (eg. deadsnakes, Github Action Python,
etc.)
Do notice, though, that there is still no guarantee that these are the
correct paths, as they assume all schemes paths have the install prefix
as a base, see #9284.
Signed-off-by: Filipe Laíns <lains@riseup.net>
> modules: python: better handling of the Python paths for Debian

- test cases/rust/5 polyglot static/meson.build
> tests/rust: add libm to fix build with rust 1.55

- mesonbuild/mlog.py
- mesonbuild/mtest.py
This reverts commit 5fcb0e6525e2044e0f82bda488a51350e0f7f29f.
The commit is a massive change that should have been split in
separate pieces, and it also removes a few features:
* in verbose mode, subtests are not printed as they happen
* in non-verbose mode the progress report does not include the number of subtests that have been run
* in non-parallel mode, output is batched rather than printed as it happens
Furthermore, none of these changes are not documented in the release
notes.  Revert so that each proposal can be tested, evaluated and
documented individually.
> Revert "mtest: fix test output issues (in console)"

- data/syntax-highlighting/vim/indent/meson.vim
The b:undo_indent variable gets executed to undo the effects of the
options set earlier in the file.
Signed-off-by: Doug Kearns <dougkearns@gmail.com>
Signed-off-by: Liam Beguin <liambeguin@gmail.com>
> syntax-highlighting: vim: set b:undo_indent

- mesonbuild/compilers/c.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/detect.py
- mesonbuild/compilers/fortran.py
- mesonbuild/compilers/mixins/elbrus.py
- test cases/frameworks/4 qt/meson.build
- unittests/linuxliketests.py
Some new changes primarily to keep Elbrus platform support up to date.
Support is generally still was ok, but a few unit tests were failed, so I've fixed it:
* `-std` support clarified for various versions of Elbrus compiler
* Added required prelinking arguments for linking with `-r` parameter
* Don't fail unit tests if `pkg-config` is less than 0.29.1 (0.29 it is on reference Elbrus OS)
* Don't fail unit tests if there is more than one major versions of qt installed (reference Elbrus OS has qt4 and qt5)
Unit tests results:
| Host | Arch | OS | Python | gcc/lcc | clang | Result |
|-------|-------|-------|-------|-------|-------|-------|
| flandre | x86_64 | Ubuntu 20.04.2 | 3.8.10 | gcc 9.3.0 | 10.0.0 | 394 passed, 54 skipped in 39.51s |
| shizuha | i686 | Ubuntu 18.04.5 | 3.6.9 | gcc …
> Update of Elbrus support

- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/modules/pkgconfig.py
- mesonbuild/modules/qt.py
- mesonbuild/modules/unstable_external_project.py
This is a rather lengthy series on it's own, but it's built on top of #9090. I tried to rebase it directly on master, and gave up.
This was originally suppsoed to be part of a larger series to fix the layering violations between the build and interpreter layers, but that turns out to be a *lot* of work, for a lot of reasons. To simplify things, and because this fixes an actual bug, I split some of the work off into it's own series.
Fixes #9096
> Use `typed_kwargs` and `typed_pos_args` for CustomTarget

- mesonbuild/backend/ninjabackend.py
- test cases/unit/100 rlib linkage/lib2.rs
- test cases/unit/100 rlib linkage/main.rs
- test cases/unit/100 rlib linkage/meson.build
- unittests/allplatformstests.py
Otherwise changes to a dependency don't propagate
> rust: dependencies need to cause a rebuild/relink not just reorder

- mesonbuild/modules/cmake.py
We ended up passing a NoneType as the program binary, which is a very awkward way to communicate an error when failing to write a basic package version file.
> cmake module: if cmake cannot be found, do not traceback

- mesonbuild/modules/i18n.py
The previous commit bd2fcb268b9ff48797bebb6a2ef94d2741234191
accidentally used the wrong var so the param name was missing,
leading to an error of "unrecognized arguments" for the
datadirs parameter value.
> modules/i18n: fix gettext use of --datadirs param

- mesonbuild/linkers/detect.py
Broken in commit 3feaea6b29197cd224fbce0ac65fd43d08c3beac.
> fix typo in error message breaking newline escape

- mesonbuild/interpreter/type_checking.py
We wrote:
ERROR: install_emptydir keyword argument "install_mode" permissions string must
be exactly 9 characters, got "4" in the form rwxr-xr-x
Let's change this around to be easier to read.
Also, 1-based numbering was used (for components) and 0-based for "bits".
And actually the "bits" are not bits, but octal digits. So say "permissions
character 1", "permissions character 2".
And finally change "must be … if provided" to "can only be". (If it isn't
provided, it "is not", so the sentence is still valid. The user will only
get this error if they provide something, so we don't need to be super precise
and say "if provided". And then we avoid confusing the reader whether
it's "if provided" attaches to the the "False" or to the whole sentence.)
> interpreter: improve the error message about install_mode

- mesonbuild/dependencies/base.py
- mesonbuild/mesonlib/universal.py
- mesonbuild/modules/unstable_external_project.py
- run_mypy.py
~~This is based on the i18n series, so that should land first.~~ i18n changes are in.
This is more work toward being able to refactor the CustomTarget argument handling out of the build module and into the interpreter.
> Add type annotations and typed_kwargs for external_project

- ci/ciimage/build.py
- mesonbuild/dependencies/cmake.py
- test cases/linuxlike/13 cmake dependency/cmake_fake1/cmMesonTestF1Config.cmake
- test cases/linuxlike/13 cmake dependency/meson.build
- test cases/linuxlike/13 cmake dependency/test.json
CMakes `target_link_libraries()` supports certain keywords to only enable specific libraries for specific CMake configurations. We now try our best to replicate this for Meson dependencies.
Additionally, a warning is printed if the old fallback variables are used instead of an imported target.
This is not a regression but a bug fix. However, it should still be good for 0.59.2. Feel free to remove the milestone if there are any concerns.
Fixes:
- https://github.com/mesonbuild/meson/issues/9197
- https://gitlab.freedesktop.org/libnice/libnice/-/issues/140
> CMake: Implement support for keywords in *_LIBRARIES variables.

- mesonbuild/compilers/detect.py
If the compiler specified is a *path* to a compiler, the current detection is broken. It needs to use just the compiler name instead.
@dcbaker
> Fix compiler detection for cl/clang-cl

- docs/markdown/Gnome-module.md
- docs/markdown/snippets/gnome_yelp_sources.md
- mesonbuild/modules/gnome.py
Yelp currently can take sources two different ways, the first is via
variadic arguments, the second is by a keyword argument. If the keyword
is passed then the variadic arguments are silently ignored, which is
obviously not ideal. Fortunately the variadic form was never documented,
and is likely not in wide use.
This patch fixes it by deprecating the variadic form, and warning if
both are passed. It does not change behavior as someone may be relying
on it.
> modules/gnome: deprecate yelp variadic sources

- mesonbuild/compilers/mixins/clike.py
warning: ISO C does not allow extra ';' outside of a function [-Wpedantic]
> clike compilers: drop semicolon at function end

- mesonbuild/cmake/toolchain.py
- unittests/linuxliketests.py
Sometimes, the machine file can include compiler command line options, in order to pick the correct multilib.  For example, Meson uses `$cc --print-search-dirs` to find the library search path, where `$cc` is the cc from the machine file.  Because the
outputs of `gcc -m32 --print-search-dirs` and `gcc --print-search-dirs` are different, this only works if you have
[binaries]
cc = ['gcc', '-m32']
in the machine file.  Right now, however, the cmake module assumes that the compiler listed in the machine file is either a compiler, or a "launcher" followed by the compiler.  Check if the second argument starts with a slash (for Microsoft-like compilers) or a dash (for everyone else), and if so presume that `CMAKE_*_COMPILER_LAUNCHER` need not be defined.
> cmake: handle arguments in the [binaries] section of the machine file

- README.md
- docs/markdown/Getting-meson.md
Make this actually visible to users. We have previously documented this but only in README.md... it got removed "temporarily" because it was incompatible with multiple entry points, which we no longer use, but the docs never got restored at that time.
Motivation: this is helpful to e.g. packagers such as https://github.com/openwrt/openwrt/pull/4635 but people simply don't know it exists until I mention it directly.
> Zipapp docs

- docs/markdown/snippets/subprojects_packagefiles.md
- mesonbuild/msubprojects.py
This will re-apply the meson.build patch overlay, ensuring it is up to date. Also take the opportunity offered by this infrastructure to repatch when performing `update --reset` since internally this will run `git stash` and thus cause the (possibly locally modified) meson.build files to disappear.
/cc @xclaesse
> msubprojects: add new subcommand "packagefiles"

- mesonbuild/interpreter/primitives/string.py
- test cases/common/35 string operations/meson.build
- test cases/common/35 string operations/test.json
This reverts commit c0efa7ab22f8900f6fa1dadf0d306ec375569c8d.
This was a nice idea, or a beautiful hack depending on your perspective. Unfortunately, it turns out to be a lot harder than we originally thought. By operating on bare nodes, we end up triggering a FeatureNew on anything that isn't a string literal, rather than anything that isn't a string.
Since no one else has come up with a better idea for implementing a FeatureNew, let's just revert it. Better to not have a warning, than have it trigger way too often.
> Revert "interpreter: Add FeatureNew check"

- mesonbuild/mesonlib/vsenv.py
The `except` line was missing its `as e` clause.
As a result, when erroring out, after not finding a compiler, Meson
gives an error ending:
```
File "C:\Users\Matthew\AppData\Roaming\Python\Python39\site-packages\mesonbuild\mesonlib\vsenv.py",
line 100, in setup_vsenv
mlog.warning('Failed to activate VS environment:', str(e))
```
> Add missing but expected as exception clause

- mesonbuild/mtest.py
If meson is not a process group leader, a SIGINT will be delivered also to its parent process (and possibly other processes).  The parent process then will probably exit and mtest will continue running in the background, without any way to interrupt the run completely.
To fix this, treat SIGINT and SIGTERM the same way unless mtest is a process group leader.
This can be reproduced when a parallel make invokes "meson test".
> mtest: limit "magic" CTRL+C behavior to process group leaders

- mesonbuild/linkers/detect.py
This should make CI green again. Homebrew's "lld -v" output now starts with "Homebrew LLD", and Meson no longer detects it,
> linkers: detect LLD when built with PACKAGE_VENDOR

- mesonbuild/modules/unstable_cuda.py
CUDA Toolkit 11.5 GA just came out, and per Table 3 of this [Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-major-component-versions), corresponds to drivers 495.29.05 (linux) and 496.04 (windows). Add its entry to `import('cuda').min_driver_version()`.
Also add an entry for 11.4.1 since it (and 11.4.2) both require the same slightly newer driver than 11.4 GA.
With your permission @jpakkane @nirbheek would love if it could be squeezed in for 0.60.0 final and 0.59.3 as it is a very low-risk addition, but won't begrudge you for delaying it to 0.60.1 or 0.61.0.
> Add entries for new CUDA Toolkit versions

- docs/markdown/Windows-module.md
- docs/markdown/snippets/windows_custom_targets.md
- mesonbuild/build.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/modules/windows.py
- run_mypy.py
Mostly this is the addition of type annotations and the `typed_*` decorators. It also adds support for CustomTargetIndexes, and relaxes the rule that only allows CustomTargets with 1 output, by generating a resource compile for all outputs of such CustomTargets. Since CustomTargetIndex is now accepted, anyone with a CustomTarget that generates both a resource file and a non-resource file can use that to avoid invalid targets.
> Typing for the Windows module

- mesonbuild/backend/ninjabackend.py
I tested this to work with 1.10.1.
1.10.2 is not in Debian Unstable or latest Ubuntu, so this is needed for correct operation.
> Fix version requirement on Ninja feature.

- test cases/common/51 run target/check-env.py
- unittests/baseplatformtests.py
- unittests/linuxliketests.py
For some reason two tests are failing on Cygwin because the argument
is passed as a long-path and the Path is ending up as a short-path:
AllPlatformTests.test_run_target_files_path
```
File "/cygdrive/d/a/meson/meson/test cases/common/51 run target/check-env.py", line 22, in <module>
assert build_root == env_build_root
AssertionError
```
SubprojectsCommandTests.test_purge
```
>       self.assertEqual(deleting(out), sorted([
str(self.subprojects_dir / 'redirect.wrap'),
str(self.subprojects_dir / 'sub_file'),
str(self.subprojects_dir / 'sub_git'),
]))
E       AssertionError: Lists differ: ['/cygdrive/c/Users/runneradmin/AppData/Local/Temp/tmpeaa2a49[205 chars]git'] != ['/cygdrive/c/Users/RUNNER~1/AppData/Local/Temp/tmpeaa2a49z/s[196 chars]git']
[...] …
```
> Fix cygwin test failure due to shortpath usage

- mesonbuild/compilers/detect.py
This is an addition to #2237. I also added logging for when unsupported `cl.exe` binaries are detected :).
> Add 64-bit paths to check for unsupported Watcom cl.exe clones.

- mesonbuild/build.py
- mesonbuild/envconfig.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/gnome.py
This series is the starting work of a larger gnome module modernization/cleanup I've been working on. The series is quite large, and the keyword argument conversion is much more involved, and likely to require a deeper review. I've shaved off what are (hopefully) smaller, easier to verify changes.
The first part of this series is groundwork, adding or fixing type annotations, using helpers instead of open coding, fixing polymorphism in union types, and that sort of thing.
Then i've added most of the "easy" type annotations to the gnome module, namely those that don't involve using typed_pos_args or typed_kwargs.
Finally, the last par of the series makes use of `typed_pos_args` or `noPosargs`, as appropriate. I'll follow this up with work on using typed_kwargs, some of which is done, some …
> Use typed_pos args in gnome module (and other typing cleanups)

- mesonbuild/backend/ninjabackend.py
- mesonbuild/environment.py
- mesonbuild/scripts/coverage.py
We say:
> If version 4.2 or higher of the first is found, targets coverage-text, coverage-xml, coverage-sonarqube and coverage-html are generated.
But this is totally untrue. Make it true, by actually checking (and not generating broken coverage commands when older versions of gcovr are found).
Fixes #9505
> coverage generator: obey the documentation and only generate supported outputs

- mesonbuild/wrap/wrap.py
Since 0.59.0 Meson downloads multiple wraps in parallel, so the
packagecache directory could be created by one then the 2nd would hit
error when calling os.mkdir() because it already exists.
> wrap: Fix concurrent os.mkdir()

- mesonbuild/build.py
It's supposed to emit an error message, but instead it did a traceback. It used to be, if no install_dir was specified then it was simply not in kwargs, but due to typed_kwargs it will now be there, but not have viable contents, so the dict membership check got skipped.
Fixes #9522
> fix custom_target with install: true and no install_dir, crashing

- mesonbuild/interpreter/primitives/string.py
- test cases/common/35 string operations/meson.build
String formatting should validly assume that printing a list means printing the list itself. Instead, something like this broke:
```
'one is: @0@ and two is: @1@'.format(['foo',  'bar'], ['baz'])
```
which would evaluate as:
```
'one is: foo and two is: bar'
```
or:
```
'the value of array option foobar is: @0@'.format(get_option('foobar'))
```
which should evaluate with '-Dfoobar=[]' as
```
'the value of array option foobar is: []'
```
But instead produced:
```
meson.build:7:0: ERROR: Format placeholder @0@ out of range.
```
Fixes #9530
> fix regression that broke string.format with list objects

- docs/yaml/objects/compiler.yaml
All kwargs inherited from has_header need to be prefixed `header_` so we cannot just do straight inheritance. And the part of the description that highlighted the way kwargs are derived and evolved, went entirely missing.
Fixes #9551
> docs: fix refman 2.0 regression in correctly describing find_library(has_headers)

- mesonbuild/compilers/cpp.py
This comes from a similar place to https://github.com/mesonbuild/meson/pull/9419 but is a bit more limited in scope. 
The original C2000 C++ support was never tested and possibly copied from the CCRX implementation. It actually just needs to be very similar to the C implementation (with the exception of compiler standards where c++03 is the only supported type).
> Remove incorrect arguments for C2000 C++ compiler.

- mesonbuild/interpreter/interpreter.py
This is a trivial typo.  Fix projeccts to projects.
Signed-off-by: Yasushi SHOJI <yashi@spacecubics.com>
> interpreter: Fix a typo

- mesonbuild/backend/ninjabackend.py
Don't hardcode one of the three possible source types, thus ignoring the needed vapis for dependencies using .gs or .vapi sources.
Fixes #9544
> valac dependencies: use the canonical list of vala source names

- docs/markdown/Dependencies.md
- mesonbuild/dependencies/dev.py
- test cases/common/221 zlib/meson.build
I noticed that the zlib system method currently doesn't work on android and it seems it wasn't included with #6421. The same method that the BSDs use should also work for android, and with some very light testing on my end with cross-compiling to android it behaves as expected.
> dependencies/zlib: Add system zlib method for android

- mesonbuild/compilers/mixins/clang.py
If the LTO threads == 0 clang will default to the same argument we manually pass, which meant we dropped support for admittedly ancient versions of clang that didn't yet add that option.
Drop the extraneous argument, and add a specific error condition when too old versions of clang are detected.
Fixes #9569
> only pass clang LTO arguments when they are needed

- docs/markdown/Gnome-module.md
- mesonbuild/modules/gnome.py
- test cases/vala/11 generated vapi/libbar/meson.build
- test cases/vala/11 generated vapi/libfoo/meson.build
This is not complete for the module, but it is a start. I've broken this up as these are fairly complex changes:
- A fair number of helper functions are ripped out as they are not helpful once we konw that the key in the dictionary exists
- avoiding kwargs mutation
- moving invalid argument handling to the typed_kwarg helper
Since this is already around 750 LOC change,  I thought it would be easier to review in smaller pieces like this.
> Add typed_kwargs to some of the gnome module functions

- mesonbuild/modules/python.py
Virtualenvs do not have their Python DLLs etc in the `sys.prefix`
directory, but in the `sys.base_prefix` directory.  This directory is
the same as `sys.prefix` if not in a virtualenv, so is safe for either
case:
https://docs.python.org/3/library/sys.html#sys.base_prefix
> Fix to find Python files for Windows virtualenvs

- mesonbuild/modules/gnome.py
This looks like it was probably removed in a bad rebase
> modules/gnome: Add back deprecation message

- mesonbuild/mtest.py
While the horizontal line and the other pictograms in mtest have an ASCII-only
version, the spinner does not.  This causes mtest to fail with a
UnicodeEncodeError exception on non-Unicode locales.
> mtest: add an ASCII-only version of the spinner

- mesonbuild/compilers/c.py
I'd usually keep such esoteric support in a personal fork, but the change is so simple it might be worth merging.
GCC didn't support the `-Winvalid-pch` flag til 3.4.0 (released in 2004, might I add). Amazingly, removing it is all that's required to get code from back then compiling using meson.
Flags like --std=c11 aren't going to fail gracefully, but it should be fairly obvious if you're using a compiler that old that c89/c99 is all you get.
> Support ancient (<3.4.0) gcc versions

- mesonbuild/modules/i18n.py
When input kwarg is missing in i18n.merge_file() it was crashing with a
backtrace because of kwargs['input'][0]. That code was useless anyway
because CustomTarget now uses first output as default name which is what
we need here.
> i18n: Fix backtrace when missing input kwarg

- mesonbuild/dependencies/hdf5.py
Depending on whether hdf5 is compiled with parallel support, the same config-tool program may be installed with a mysterious "p" in the name. In this case, dependency lookup will totally fail, unless of course you use the superior pkg-config interface in which case you get a predictable name.
Work around this insanity by checking for both types of config-tool name.
Fixes #9555
> hdf5 dependency: check for alternative config-tool names

- test cases/osx/5 extra frameworks/meson.build
- unittests/failuretests.py
This tries to link the system provided python, which is deprecated and
will result in an ambiguous error like "your binary is not an allowed
client of .../Library/Frameworks/python.framework/python.tbd for
architecture x86_64". Just remove it, we already have coverage of
extraframeworks anyway.
> tests: remove extraframework test for python

- mesonbuild/dependencies/cmake.py
- test cases/frameworks/15 llvm/test.json
> Update expected skip condition for llvm framework test on msys2

- mesonbuild/dependencies/dev.py
Contrary to most system method checks, zlib currently functions as a
whitelist of OSes. This isn't really needed however. The first special
case for OSes that provide zlib as part of the base OS is worth keeping.
However, the elif for windows is more than generic enough to allow any
other potential OSes to try. Just make it a simplie if/else instead.
> dependencies/zlib: Allow for generic OS checks

- docs/markdown/Builtin-options.md
- docs/markdown/Configuring-a-build-directory.md
- docs/markdown/snippets/vs_2022.md
- docs/yaml/builtins/meson.yaml
- mesonbuild/backend/backends.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/vs2022backend.py
- mesonbuild/cmake/common.py
- mesonbuild/coredata.py
Visual Studio 2022 just released yesterday. I saw no issue and PR about supporting this backend so here is my attempt.
The motivation to add this is that if the user just have VS 2022 installed, it only includes platform toolset v143, while vs2019 backend uses v142. Meaning without manually retarget the generated project files to v143, `meson compile` will fail to build.
This is my first time to do anything about Meson source code, so I may very likely miss some spots to change. Please let me know or edit when you merge.
I basically just copied whatever in vs2019 and change version numbers. I did test this change locally.
> Support Visual Studio 2022 backend

- mesonbuild/modules/cmake.py
Whilst working on the [Reproducible Builds effort](https://reproducible-builds.org/), I noticed that meson did not generate reproducible `.cmake` files: they include the full path name. This commit not only makes the build reproducible, but it also matches CMake's own behaviour. Specifically, CMakePackageConfigHelpers.cmake does the equivalent transformation using `get_filename_component(inputFileName "${_inputFile}" NAME)`.
I originally filed this in Debian as [bug #1000327](https://bugs.debian.org/1000327).
> Make the generated reproducible .cmake files reproducible.

- docs/yaml/objects/compiler.yaml
After a discussion implementing this for muon [1] and clarification onIRC on Meson's behaviour.
> Clarify some wording for compiler.find_first_argument

- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/qt.py
As evidenced by the warning message immediately below this, I meant to write "5.15" here. As is, this will enable depfile support on too-old versions of moc.
@textshell
cf. https://github.com/mesonbuild/meson/pull/7451#issuecomment-975694152
> qt module: fix stupid copy-paste error

- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/unstable_rust.py
- test cases/failing/115 nonsensical bindgen/meson.build
- test cases/failing/115 nonsensical bindgen/src/header.h
- test cases/failing/115 nonsensical bindgen/src/source.c
- test cases/failing/115 nonsensical bindgen/test.json
- unittests/allplatformstests.py
This ensures that there is no warnings when running meson on `test cases/common/22 object extraction`.
> interpreter: extract_objects provides a valid source

- mesonbuild/modules/gnome.py
Commit dbb109703e0b1f91965868c3ab193eff6e45eb22 broke generate_gir
by using FeatureDeprecated without importing it.
> modules/gnome: import missing FeatureDeprecated for generate_gir

- mesonbuild/backend/backends.py
- mesonbuild/build.py
- test cases/unit/17 prebuilt shared/meson.build
- test cases/unit/17 prebuilt shared/meson_options.txt
- test cases/unit/17 prebuilt shared/rejected.c
- test cases/unit/17 prebuilt shared/rejected.h
- test cases/unit/17 prebuilt shared/rejected_main.c
- unittests/allplatformstests.py
In 0.60 a bug was fixed where a cached variable was being mutated. Unfortunately, we were relying on that mutation to get the behavior of recursively looking up the dependency web of a target. This series does a bit of cleanup, then fixes the bug by explicitly doing the up chain lookup.
Fixes #9542
> Recursively look for rpath dependencies

- docs/yaml/functions/shared_library.yaml
- docs/yaml/functions/shared_module.yaml
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- test cases/failing/75 link with shared module on osx/test.json
- test cases/unit/1 soname/main.c
- test cases/unit/1 soname/meson.build
- unittests/allplatformstests.py
- unittests/linuxliketests.py
Emit a detailed deprecation warning that explains what to do instead.
Also add a unittest.
```
DEPRECATION: target main1 links against shared module linked_module1, which is incorrect.
This will be an error in the future, so please use shared_library() for linked_module1 instead.
If the target requires undefined symbols, you can use `override_options: ['b_lundef=false']`.
```
Fixes https://github.com/mesonbuild/meson/issues/9492
> shared_module: Add soname when used as a link target

- mesonbuild/dependencies/misc.py
This header is required anyway. And the compile test for linking to libc with the iconv_open symbol, can succeed when we try to use the literal symbol name without includes, but fail later during project build, because actually including iconv.h might redefine the function to match a forked symbol. This happens when GNU iconv is installed as a standalone library on systems that have a less fully-featured iconv implementation.
So, by including the header in has_function, we ensure that we test against the default resolved header. In the event that the symbol which is #define'd by the header is 'libiconv_open', linking will fail against libc even when a builtin iconv does exist, and we will fall back to the iconv dependency that provides -liconv (and which is needed to properly use the …
> iconv dependency: include header when checking for libc builtin

- mesonbuild/mesonlib/universal.py
- unittests/internaltests.py
This adds the missing module and type to the repr method, and adds a few tests. surprise, surprise, there are bugs!
> Small cleanup and tests for OptionKey

- docs/markdown/snippets/fix_backend_startup_project.md
- mesonbuild/backend/vs2010backend.py
As mentioned here https://github.com/mesonbuild/meson/pull/9611#discussion_r754671772
> Stop backend_startup_project from erasing the last project in sln.

- mesonbuild/minstall.py
They don't utilize a soname cache, so running ldconfig without arguments
is basically pointless -- and at least some of them are buggy: running
ldconfig with the verbose flag switches on "delete all directories from
the hints file, and recreate it using 0 command-line positional
arguments", which would soft-brick the system.
Fixes #9592
> minstall: do not run ldconfig on the *BSDs

- mesonbuild/interpreter/interpreterobjects.py
- test cases/failing/106 feature require.bis/meson.build
- test cases/failing/106 feature require.bis/meson_options.txt
- test cases/failing/106 feature require.bis/test.json
Don't show a blank error when no `error_message` was passed as argument.
> interpreter: fix `feature.require` handling of error message

- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/vs2012backend.py
- mesonbuild/backend/vs2013backend.py
- mesonbuild/backend/vs2015backend.py
- mesonbuild/backend/vs2017backend.py
- mesonbuild/backend/vs2019backend.py
- mesonbuild/backend/vs2022backend.py
Visual Studio Version Selector is super fussy about the comment line in a solution. If wrong, you just get an arbitrary (or newest, or most recently installed, or whatever it might be...) VS launched when opening a solution.
- 2010 `# Visual Studio 2010`
- 2012 `# Visual Studio 2012`
- 2013 `# Visual Studio 2013`
- 2015 `# Visual Studio 14`
- 2017 `# Visual Studio 15`
- 2019 `# Visual Studio Version 16`
- 2022 `# Visual Studio Version 17`
(I'm actually not sure how far back VSVS would go, but these are the VS-created solution comments from each version.)
Couple of points:
1. I've also adjusted the `Format Version N` in the sln file as appropriate. This doesn't seem to be required for VSVS, but surely better to be closer to the "native" files.
2. Similarly, VS created solutions have the …
> Allow Visual Studio Version Selector to open the correct VS version

- mesonbuild/build.py
We want to loop over all link_targets to update
backwards_compat_want_soname if necessary.
Fixes: ec9bdc6edb17d1d9da5df2d6525025242c119f3a
> Remove premature return in BuildTarget.check_module_linking()

- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/mesonmain.py
- mesonbuild/interpreter/type_checking.py
This covers many of the non target uses remaining, `add_test_setup`, `project`, `summary`, and `find_program`. Some of these already used `typed_pos_args`, but not `typed_kwargs`
> More use of typed_* in the interpreter module

- mesonbuild/compilers/mixins/visualstudio.py
Fixes InternalTests
```
Stdout:
WARNING: Could not find toolset for version '19.30.30705'
```
> Fix _calculate_toolset_version for VS2022.

- mesonbuild/dependencies/misc.py
has_function(prefix: '...') is useless to check the difference between builtins and external library functions. It has code to detect
"builtins" that misfires and reports that iconv_open is defined as a builtin on mingw, but only if you include the header.
Instead compile an open-coded test file that this iconv dependency implementation fully controls, that doesn't get up to imaginative edge cases like trying to find `__builtin_iconv_open`.
Fixes commit db1fa702f3943c6e4fec142b2bf5468c89173993, which merely moved the brokenness over one step to the right (by breaking mingw instead of freebsd)
Fixes https://github.com/mesonbuild/meson/pull/9632#issuecomment-979581509
> iconv dependency: try even harder to find working iconv

- mesonbuild/backend/backends.py
- mesonbuild/minstall.py
This fix comes in two parts:
- prevent ldconfig from running in a broken fashion
- add a new feature to use ldconfig -m and add the configured libdir
Fixes #9592
/cc @jbeich, thoughts?
At least the first commit should probably go into 0.60.2
> fix BSD ldconfig handling

- mesonbuild/modules/gnome.py
generate_gir forces building both the typelib and gir, and some people only want one or the other (probably only the typelib?) which means flagging the other as install_dir: false in the same way custom_target supports.
As this always worked, albeit undocumented, make sure it keeps working. It's pretty reasonable to allow, anyway.
Fixes https://github.com/mesonbuild/meson/pull/9484#issuecomment-980131791
> gnome module: fix install_dir x3, by allowing false *_gir and *_typelib

- mesonbuild/interpreter/compiler.py
- unittests/allplatformstests.py
If the compiler check is updated as a string in meson.build, we force rebuild, which is a good thing since the outcome of that check changes the configuration context and can enable or disable parts of the build.
If the compiler check came from a files() object then we didn't add a regen rule on those files.
Fixes #1656
> make sure files arguments to compiler.compiles and friends, performs rebuild

- docs/yaml/functions/run_command.yaml
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/programs.py
There is one strange thing about this function, we allow `build.Executable` to be passed through the type guards, even though it's actually an error to use it. We do this so that we can generate a better error message.
This also adds support for passing `Compiler` objects to any of the positional arguments of `run_command`, not just the first one.
> use typed_* args for the `run_command` function

- mesonbuild/interpreter/interpreterobjects.py
They passed the arguments in the wrong order, so the version parsed as the message and the message parsed as a version.
While we are at it, pass the location node in too.
> fix broken FeatureNew checks that never printed

- docs/markdown/snippets/cmake_deprecated.md
- mesonbuild/cmake/interpreter.py
See:
- #7832
- #9676
I did *not* deprecate CMake <3.14 support for CMake dependencies, since it makes no difference because the CMake server API is not used. The only meaningful minimum version bump for CMake deps would be to 3.17.0
> cmake: Deprecate CMake <3.14 and warn for <3.17

- mesonbuild/modules/i18n.py
It was originally forgotten in merge_file() and later added for parity with gettext(). This means that the FeatureNew for each function is different.
> i18n module: correctly annotate the availability of data_dirs

- mesonbuild/modules/gnome.py
Make it possible to specify a wrapper for executing binaries.
(useful in cross-compiling)
> gtkdoc: add support for a binary wrapper

- mesonbuild/modules/qt.py
Originally name should have been set to required=True, but since then
the requirement to name CustomTargets (which compile_resources is a
wrapper around) has been dropped. As such we just need to allow the
default value of None through.
Fixes: #9698
> modules/qt: compeil_resources allow name to be unset

- mesonbuild/backend/backends.py
Re-use any already determined rpaths for a target.
Fixes #9695
> Fix performance regression in build file generation

- docs/markdown/snippets/extract-more-objects.md
- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- test cases/common/22 object extraction/create-source.py
- test cases/common/22 object extraction/meson.build
- test cases/common/245 custom target index source/main.c
- test cases/common/245 custom target index source/meson.build
- test cases/failing/116 run_target in test/test.json
This fixes two pending issues related to custom targets, allowing them to be used in extract_objects and in test. 
Fixes #7585
Fixes #8333
> Allow custom targets in extract_objects and test

- .github/workflows/cygwin.yml
- .github/workflows/macos.yml
- .github/workflows/msys2.yml
- ci/ciimage/common.sh
- ci/ciimage/ubuntu-rolling/install.sh
- ci/run.ps1
- mesonbuild/interpreterbase/decorators.py
- unittests/internaltests.py
TypedKwarg currently doesn't allow an extra message to be passed when it uses FeatureDeprecated or FeatureNew, which is not commonly needed, but is needed sometimes. This series adds support for that.
> Add deprecation messages to KwargInfo deprecation and since

- docs/markdown/Gnome-module.md
- mesonbuild/modules/gnome.py
- test cases/frameworks/12 multiple gir/gir/meson.build
- test cases/frameworks/12 multiple gir/meson.build
- test cases/frameworks/12 multiple gir/mesongir/meson.build
- test cases/frameworks/12 multiple gir/test.json
generate_gir forces building both the typelib and gir, and some people only want one or the other (probably only the typelib?) which means flagging the other as install_dir: false in the same way custom_target supports.
As this always worked, albeit undocumented, make sure it keeps working. It's pretty reasonable to allow, anyway.
Fixes https://github.com/mesonbuild/meson/pull/9484#issuecomment-980131791
> gnome module: document and fix install_dir x3, by allowing false *_gir and *_typelib

- docs/markdown/Gnome-module.md
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/modules/gnome.py
This is a smaller follow up to the last set of cleanups to the gnome module with conversions to `typed_kwargs`. There are only two functions covered here, genmarshal and generate_vapi. Again, this allows a number of nice cleanups. In addition I noticed that genmarshal still exposes `build_always` without deprecation. I've made that deprecated, and added the `build_always_stale` and `build_by_default` keyword arguments matching the behavior of `custom_target`.
> More typed_kwargs for the gnome module

- mesonbuild/compilers/mixins/visualstudio.py
Related to #7114.
I'm not sure how to please the type checker on this CI failure.
> clang-cl: add a translation pass for `-isystem` args to work

- docs/yaml/functions/configure_file.yaml
We were missing the most important keyword argument of them all!
> docs: Add the `configuration` keyeword argument to `configure_File`

- mesonbuild/mtest.py
Currently, `meson compile` will activate the Visual Studio commandline before doing anything, which works great. `meson test` doesn't do this and just runs ninja directly to build/rebuild tests before running them, which fails because it can't find `cl.exe`.
This fixes that.
> Activate VS env when running `meson test`

- mesonbuild/backend/backends.py
- mesonbuild/minstall.py
Even if we install without a DESTDIR set, we should never update
ldconfig when cross compiling.
Fixes #9707
> install: Don't run ldconfig on cross builds

- mesonbuild/modules/gnome.py
There were some regressions (clearly our tests are insufficient!) in the gnome.genmarshal caused by my recent conversion to type checked arguments. thanks @alex-tee for reporting these
> Fix regressions caused by typing changes

- mesonbuild/dependencies/misc.py
In 1fb6c939473ca7cdab2 the intl dep gained support for static linking
which also forwarded this property to the iconv sub dependency.
The refactoring in 214d03568f75 lost this change, which results in
iconv getting linked dynamically again.
Forward static again to fix this.
> intl dep: forward static to iconv if needed

- docs/markdown/Rewriter.md
- docs/markdown/snippets/rewriter_extra_files.md
- mesonbuild/rewriter.py
- test cases/rewrite/6 extra_files/addExtraFiles.json
- test cases/rewrite/6 extra_files/info.json
- test cases/rewrite/6 extra_files/meson.build
- test cases/rewrite/6 extra_files/rmExtraFiles.json
- unittests/rewritetests.py
Add ability to mutate a target's `extra_files` list through the rewriter.
The logic is copied from sources add/rm, but changes the `extra_files` kwarg instead of the sources positional argument.
Has additional logic to handle creating the `extra_files` list if it doesn't exist.
> rewriter: create {add,rm}_extra_files commands

- mesonbuild/mesonlib/universal.py
We really don't want to be mutating global state, so let mypy yell at us
when we try.
> mesonlib: make get_meson_command return an ImmutableList

- docs/markdown/Reference-tables.md
- mesonbuild/envconfig.py
Is there anything one needs to to 'support' a new family? this is only use for quirks correct?
closes #9670
> add ft32 cpu family

- mesonbuild/modules/gnome.py
this makes two sets of distinct changes
1. it cleans up mkenums and mkenums_simple so that they don't call into each other
2. it uses typed_kwargs for both of them
This is currently based on #9594, and that should be reviewed and merged first.
This does not fix all the type issues in the gnome module, I'll follow this up with another series to address that separately, but this does get us complete typed_pos_args and typed_kwargs coverage
> Clean up gnome mkenums, and use typed_kwargs

- mesonbuild/modules/cmake.py
- mesonbuild/modules/dlang.py
Do not use ExternalProgram as that is too low-level and doesn't handle e.g. machine file overrides.
Fixes #9733
> modules: use find_program implementation to find programs

- mesonbuild/build.py
- mesonbuild/modules/pkgconfig.py
- test cases/common/44 pkgconfig-gen/meson.build
- test cases/common/44 pkgconfig-gen/test.json
When generating pkgconfig file for a library that links to an
uninstalled static library built by custom_target() Meson was crashing
when trying to access some attributes that does not exist on that class.
Also fix is_internal() implementation, it only really make sense on a
CustomTargetIndex or if CustomTarget has only a single output.
> pkgconfig: Fix linking to a custom target

- mesonbuild/backend/backends.py
- mesonbuild/mesonlib/universal.py
- test cases/common/44 pkgconfig-gen/answer.c
- test cases/common/44 pkgconfig-gen/foo.c
- test cases/common/44 pkgconfig-gen/meson.build
- test cases/common/44 pkgconfig-gen/test.json
- unittests/allplatformstests.py
If a pkg-config dependency has multiple libraries in it, which is the most common case when it has a `Requires:` directive, or when it has multiple `-l` args in `Libs:` (rare), then we don't add `-Wl,-rpath` directives to it when linking.
The existing test wasn't catching it because it was linking to a pkgconfig file with a single library in it. Update the test to demonstrate this.
This function was originally added for shared libraries in the source directory, which explains the name: https://github.com/mesonbuild/meson/pull/2397
However, now it is also used for linking to *all* non-system shared libraries that we link to with absolute paths: https://github.com/mesonbuild/meson/pull/3092
But that PR is incomplete / wrong, because it only adds RPATHs for dependencies that specify a single …
> Set RPATH for all non-system libs with absolute paths

- mesonbuild/compilers/mixins/clike.py
- mesonbuild/mesonlib/universal.py
Removed errant "type: ignore".
Fixed issue with "fetch" call. This issue was the following:
Dict::get() and Dict::pop() have the following signature:
T.Callable[[_T, _U], _U | None] OR T.Callable[[_T], _U | None]
Note how the return type is _U here. When the fetch() function was
actually being called, it had the following signature:
T.Callable[[_T, T.List[_U]], T.Union[T.List[_U], _U]]
This is incompatible with the previous definitions. The solution is
simply to move where the default value is introduced if fetch() produces
None.
> Fix mypy 0.930 issues

- .github/workflows/cygwin.yml
multiple versions of python are packaged by cygwin, and the default python is auto-selected as the latest one via a Debian-like alternatives system.
This recently broke because dblatex is built against 3.9, causing it to be installed too and resulting in multiple (inconsistent) versions of python being installed, and `python3` pointing to the one we don't have devel packages for and isn't even the default version.
Fix this by pointing back to the intended python.
> cygwin: fix broken python versions

- .github/workflows/lint_mypy.yml
And the outdated pin means some error messages that are a lot better in newer versions aren't available.
> unpin pylint in CI -- the mentioned issue is long since fixed

- .github/workflows/lint.yml
For a long time now, this has done 3 different things, only one of which is mypy. But they are labeled:
- LintMypy / lint
(runs pylint)
- LintMypy / custom_lint
(runs a custom script)
- LintMypy / mypy
(actually runs mypy)
This reduces the usable length of the label which isn't all that long to begin with, is actively misleading, and even when you know what is going on, it becomes harder to tell at a glance what failed. Change it to be more unambiguous.
> rename lint workflow for less confusion

- mesonbuild/modules/cmake.py
- mesonbuild/modules/dlang.py
- mesonbuild/modules/fs.py
- mesonbuild/modules/python3.py
- mesonbuild/modules/qt6.py
Going back to 0.38, though some of them are far older. The original implementation of FeatureNew only added backdated feature checks that far, anyway.
> add FeatureNew decorators for various modules that were lacking them

- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/mixins/islinker.py
- mesonbuild/coredata.py
- mesonbuild/linkers/linkers.py
- mesonbuild/mesonlib/universal.py
- mesonbuild/mlog.py
And also a broken variable reference.
I discovered these problems while bored and trying to get cython to convert all of meson into compiled C modules. Cython actually uses type annotations at runtime, and also has a much better undefined variables scanner.
> Fix some broken type annotations

- .github/workflows/website.yml
- docs/markdown/snippets/refman_man_page_backend.md
- docs/meson.build
- docs/refman/generatorbase.py
- docs/refman/generatorjson.py
- docs/refman/generatorman.py
- docs/refman/main.py
With this pr you can pass `-g man` to genrefman.py and get one big man page with all information that refman knows about.  I haven't integrated this into the build yet since I'm not sure what would be best.
> Add a man page backend to refman

- docs/markdown/snippets/about_minimum_python_version.md
- mesonbuild/mesonmain.py
Same basic thing we did for python 3.5, figured it could not hurt.
https://github.com/mesonbuild/meson/pull/9510#issuecomment-986287722
> add pending deprecation notice for python 3.6

- docs/markdown/snippets/armclang-support.md
- mesonbuild/build.py
- mesonbuild/compilers/c.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/detect.py
- mesonbuild/compilers/fortran.py
- mesonbuild/compilers/mixins/arm.py
---
Initial support for ARM Ltd.'s `armclang` toolchain. Not to be confused with Keil's `armclang` cross-compilation toolchain for embedded devices. Passes basic smoke tests at least.
> Armclang support

- mesonbuild/compilers/c.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/cs.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/fortran.py
- mesonbuild/compilers/java.py
- mesonbuild/compilers/mixins/arm.py
- mesonbuild/compilers/mixins/c2000.py
- mesonbuild/compilers/mixins/ccrx.py
- mesonbuild/compilers/mixins/clang.py
- mesonbuild/compilers/mixins/compcert.py
- mesonbuild/compilers/mixins/elbrus.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/compilers/mixins/intel.py
- mesonbuild/compilers/mixins/pgi.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/compilers/mixins/xc16.py
- mesonbuild/compilers/rust.py
- mesonbuild/compilers/swift.py
- mesonbuild/compilers/vala.py
It really is a per class value, and shouldn't be set per instance. It
also allows us to get rid of useless constructors, including those
breaking mypy
> compilers: push the compiler id to a class variable

- mesonbuild/modules/gnome.py
This typo was introduced in 9ef36fa80bf4483bcd837ea3985a51ab533c7972 - #9594 and can cause a build failure, because --metadatdir is not a valid vapigen option. This can be seen for example in the [fontmanager](https://github.com/FontManager/font-manager) or [AppStream](https://github.com/ximion/appstream) builds, so this fix should ideally be part of 0.60.1.
@eli-schwartz @dcbaker
> gnome: fix typo in vapigen option metadatadir

- mesonbuild/modules/__init__.py
Regression in commit 566c2c9a9c98d13f85ccef624e9ac584f64c6a4a.
The interpreter details are a bit of black magic. Functions expect tuples, but they receive lists and then the type-checking decorators convert those to tuples.
So, directly manhandling a `self._interpreter.func_*()` but passing it the tuple it nominally expected, actually explodes in your face by way of failing an assert, then dumping 'ERROR: Unhandled python exception'.
Fixes use of `gnome.gtkdoc(..., check: true)`, for example when building glib.
/cc @paper42
> fix broken module tests which caused gtkdoc-check to traceback on assert

- docs/markdown/Users.md
The mesa website is a bit more helpful as an introduction to the project than the gitlab-project. So it seems better to link there instead.
> link to mesa website instead of gitlab

- mesonbuild/modules/gnome.py
> Gnome regressions
