mesonbuild/meson

- mesonbuild/interpreter/interpreter.py
- test cases/failing/120 subproject version conflict/meson.build
- test cases/failing/120 subproject version conflict/subprojects/A/meson.build
- test cases/failing/120 subproject version conflict/subprojects/B/meson.build
- test cases/failing/120 subproject version conflict/test.json
Fixes a bug where the subproject version was not validated
when the subproject had already been processed.
The bug would cause inconsistent build results if the subproject was
referenced more than once (diamond) with conflicting version requirements.
> subproject: fix version validation on lookup

- mesonbuild/mesonlib/vsenv.py
vswhere.exe does not find vs express when using only the workload 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64'.
This adds the 'Microsoft.VisualStudio.Workload.WDExpress' worlkload, like in [setuptools](https://github.com/pypa/setuptools/blob/40725756391163a7557113b9922d2086506b9db0/setuptools/msvc.py#L176).
Verified ok on my system.
> Detect visual studio express edition

- test cases/frameworks/10 gtk-doc/doc/foobar1/meson.build
- test cases/frameworks/10 gtk-doc/doc/foobar2/meson.build
- test cases/frameworks/10 gtk-doc/test.json
- test cases/frameworks/7 gnome/gdbus/data/com.example.Sample.xml
- test cases/frameworks/7 gnome/gdbus/meson.build
- test cases/vala/11 generated vapi/libfoo/foo.metadata
- test cases/vala/11 generated vapi/libfoo/meson.build
Regression tests for the following PRs: https://github.com/mesonbuild/meson/pull/9806 https://github.com/mesonbuild/meson/pull/9807 https://github.com/mesonbuild/meson/pull/9812 https://github.com/mesonbuild/meson/pull/9817
> Add gnome, gtk-doc, and vala regression tests

- mesonbuild/mesonlib/vsenv.py
- mesonbuild/minstall.py
- run_tests.py
- unittests/baseplatformtests.py
- unittests/helpers.py
- unittests/windowstests.py
Otherwise we might not find a ninja that was picked up from the Visual
Studio installation.
```
$ meson setup _build
...
Activating VS 15.9.40
...
Found ninja-1.8.2 at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.EXE"
$ meson compile -C _build
Activating VS 15.9.40
...
$ meson install -C _build
Can't find ninja, can't rebuild test.
```
Fixes https://github.com/mesonbuild/meson/issues/9774
> install: Setup VS env if we did that during setup

- docs/yaml/objects/cfg_data.yaml
- docs/yaml/objects/feature.yaml
- mesonbuild/build.py
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/boost.py
- mesonbuild/dependencies/pkgconfig.py
- mesonbuild/dependencies/qt.py
- mesonbuild/interpreter/__init__.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/modules/cmake.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/sourceset.py
- mesonbuild/modules/unstable_simd.py
- test cases/common/14 configure file/meson.build
- test cases/common/187 args flattening/meson.build
- unittests/allplatformstests.py
- unittests/linuxliketests.py
This series adds full type annotations and use of the typed_* decorators for interpreter objects. as part of that work I've changed the `ConfigurationDataObject` into a proper `ConfigurationDataHolder`, that is a holder and acts and works like a holder, with all of the core logic pushed into `build.ConfigurationData`, and the interpreter logic in the interpreter. This has a nice cleaning effect throughout the code base.
There is one contentious change here, and that's dropping support for setting and getting values that are not `str | int | bool`. We never meant to accept other kinds of values, but we did, and we only deprecated that support at the start of the year, so it may well be too soon to drop that. Nevertheless, I've included that in the series as it allows more cleanups, and …
> Full typing and typed_* for the interperterobjects module

- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/dependencies/base.py
- mesonbuild/modules/gnome.py
- run_mypy.py
Finally, with these changes (and the ones in #9700), the gnome module has become type safe, and with it all callers of CustomTarget, so I can finally get to the work I actually wanted to, fixing the layering violation between the build and interpreter modules!
> Fully type check the gnome module

- ci/ciimage/bionic/install.sh
- ci/ciimage/ubuntu-rolling/install.sh
- docs/markdown/i18n-module.md
- docs/markdown/snippets/i18n-itstool_join-added.md
- mesonbuild/modules/i18n.py
- mesonbuild/scripts/itstool.py
- test cases/frameworks/6 gettext/data3/com.mesonbuild.test.intlprog.metainfo.xml
- test cases/frameworks/6 gettext/data3/meson.build
- test cases/frameworks/6 gettext/data3/metainfo.its
- test cases/frameworks/6 gettext/data3/verify.py
- test cases/frameworks/6 gettext/meson.build
- test cases/frameworks/6 gettext/po/de.po
- test cases/frameworks/6 gettext/po/intltest.pot
- test cases/frameworks/6 gettext/po/meson.build
- test cases/frameworks/6 gettext/test.json
Hi!
This PR adds support for the "join" feature of `itstool` to Meson. While (x)gettext can merge XML, when working with AppStream metadata I found out that it is pretty unpredictable in how data is merged, especially when inline tags are involved. At the very least, inline markup gets XML-escaped, and I found no way at all to work around this particular issue.
[Itstool](http://itstool.org/) however always generates correct results and obeys the rules defined in ITS files properly. This tool is also very widespread and available in every Linux distribution I checked. It also is used by GNOME's help.
Using `itstool` from Meson is pretty cumbersome at the moment, as you need to scrape through the output generated from `i18n.gettext()` and rename mo files so itstool can infer locale names. …
> i18n: Add support for joining XML localization via itstool

- docs/markdown/i18n-module.md
- mesonbuild/modules/i18n.py
It was not added in 0.61.0 as that was already released.
> fix broken version annotations for the new itstool_join feature

- docs/markdown/Subprojects.md
This adds a link to
https://mesonbuild.com/Builtin-options.html#specifying-options-per-subproject
in two different places and provides an example for changing the default
options.
This info is partially based on a [recent
discussion](https://github.com/mesonbuild/meson/discussions/9830)
between me and @eli-schwartz
> Subprojects.md:add extra detail

- docs/markdown/Contributing.md
I thought it would good to specify a general rule here so people can set
their line wrapping appropriately.
[skip ci]
> Contributing.md:specify max line length for docs

- mesonbuild/interpreter/interpreterobjects.py
Python inherited a really bad design from C, booleans happen to be ints.
Which is awful, but it's true.
Fixes: #9858
> interpreterobjects: Don't warn on set10(bool)

- mesonbuild/interpreter/interpreter.py
Due to the support for specifying version as files('VERSION'), we need to internally accept an array, since that is what files() returns. Before that, we didn't accept arrays, and after that, we don't intend to accept generic arrays, only arrays as a side effect of files(). So tighten the typechecking to ensure that that is what we actually get.
See https://github.com/mesonbuild/meson/pull/9531#discussion_r757838111
> properly error out when project version is an array other than files()

- docs/markdown/Dependencies.md
For whatever reason, the original PR was merged without documentation.
> Add docs for JDK system dependency

- mesonbuild/mcompile.py
In commit 928078982c8643bffd95a8da06a1b4494fe87e2b a good error message about the directory not being a valid build directory, was replaced by a worse message.
In commit abaa980436f53100041bd5535589bb1c42019bd6 the error message was replaced by a traceback when trying to load the coredata before checking if it was a build directory.
Revert back to using the helper function with the good error message. Reorganize code so that we check basic things first, and do less work before detecting errors.
Fixes #9584
> mcompile: fix broken codepaths and restore orphaned code

- docs/markdown/Reference-tables.md
- mesonbuild/compilers/c_function_attributes.py
- test cases/common/197 function attributes/meson.build
retain is a relatively young attribute which has proven itself useful
for working with --gc-sections -z start-stop-gc.
> compilers/c_function_attributes: add retain + typo correction

- mesonbuild/modules/gnome.py
Otherwise it shows up during my builds with
```
Build-time dependency gtk-4.0 found: NO (tried pkgconfig and cmake)
```
which is extremely confusing
> gnome: Fix gtk4 pkgconfig name

- mesonbuild/mesonlib/universal.py
- mesonbuild/modules/unstable_external_project.py
Do not require users to convert it to a string first. This is a waste of time and effort for exactly the same results.
> Popen_safe and wrappers can accept os.PathLike for cwd

- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/type_checking.py
In commit 06481666f4e74ecef01e59351fc345ab0962d998 this warning got moved from build.py to the interpreter. Unfortunately it got added to the wrong function... it is supposed to be part of custom_target and even mentions this as the feature_name.
Since then, build_always became a KwargInfo and has the deprecated-since attribute baked into it. But it didn't have the additional message which it really should have.
Add that message at the same time we remove it from vcs_tag.
> remove incorrect deprecated feature for vcs_tag

- mesonbuild/modules/gnome.py
- test cases/frameworks/7 gnome/gdbus/meson.build
This was allows up to 0.61.0 (including with the initial type
annotations), but was accidentally broken by fixes for other bugs in
0.61.1.
Fixes: #9883
> modules/gnome: Allow gdbus_annotations to take an empty list again

- mesonbuild/mesonmain.py
It's not a MesonBug which needs to be reported, and the existing error already adequately points out the problematic file.
It is impossible to get a PermissionError for files created by meson itself, once the build directory has been created, anyway.
> do not report context on python traceback, for PermissionError

- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/hotdoc.py
- mesonbuild/modules/i18n.py
- mesonbuild/modules/java.py
- mesonbuild/modules/qt.py
- mesonbuild/modules/unstable_external_project.py
- mesonbuild/modules/unstable_rust.py
- mesonbuild/modules/windows.py
- test cases/failing/41 custom target plainname many inputs/test.json
Since we now do all of our user input type checking in the interpreter, the `CustomTarget` initializer can act much more as a dumb initializer, and (for the most part) assigning values to attributes. This makes the whole thing much cleaner and easier to understand, and has allowed mypy to find at least one bug!
> Type checking for the CustomTarget initializer

- mesonbuild/backend/backends.py
- unittests/allplatformstests.py
- unittests/baseplatformtests.py
- unittests/linuxcrosstests.py
- unittests/linuxliketests.py
- unittests/rewritetests.py
For example:
```
meson builddir \
--native-file vs2019-paths.txt \
--native-file vs2019-win-x64.txt \
--cross-file vs2019-paths.txt \
--cross-file vs2019-win-arm64.txt
```
This was causing the error:
> ERROR: Multiple producers for Ninja target "/path/to/vs2019-paths.txt". Please rename your targets.
Fix it by using a set() when generating the list of regen files, and add a test for it too.
Also fix a warning about distutils deprecation.
> ninja backend: Fix usage of same constants file for native and cross

- docs/yaml/functions/find_program.yaml
This was the case since 067ff7eeae26eda8edc9f7f7432f551c3e373eaa, i.e. version 0.50.0. Fixes #3856
Edit: this is useful to know, so that users (like me) can stop using `python.find_installation()` when they want to be sure to always get a result back
> docs: find_program can return the current Python3 interpreter

- .github/workflows/lint.yml
- docs/markdown/Yaml-RefMan.md
- docs/refman/loaderyaml.py
- docs/refman/main.py
`genrefman.py -l yaml` currently takes about 80 seconds on my machine.  This is almost entirely due to the usage of `strictyaml`, which [does not consider speed to be a priority](https://hitchdev.com/strictyaml/why/speed-not-a-priority/).  This PR adds a `fastyaml` loader which uses the `CLoader` from `pyyaml`.  On my machine this reduces the runtime to 0.95 seconds.  I'm not entirely sure if this is of interest to meson developers, since you can already use `-l pickle` for a similar speedup (after you do the initial load), but I thought I would put it here just in case :).
> Add a fastyaml loader for refman docs

- mesonbuild/backend/ninjabackend.py
Basically the last thing we did during target processing was to generate shlib symlinks for e.g. libfoo.so -> libfoo.so.1.
In some cases we would dispatch to another function and return early, though, which meant we never got far enough to generate the symlinks. This then led to breakage when people tried to compile against libfoo.so
This surely breaks -uninstalled.pc usage, and also caused problems in https://github.com/rust-lang/rust/pull/90260
> backends/ninja: generate symlink aliases for rust/cs/swift libraries too

- docs/markdown/Dependencies.md
- docs/markdown/snippets/libdl-dependency.md
- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/misc.py
The background to this patch can be seen here: https://github.com/mpv-player/mpv/pull/9793
In a nutshell:
Different systems/implementations of libc have different policies about having the 'libdl' library in the system. On some systems (*BSD, glibc >= 2.34) the dynamic linker interface is part of libc, on others (mostly glibc < 2.34) a separate 'libdl' library is supplied which contains the necessary functions.
In order to simplify the handling of having libdl in meson, @eli-schwartz suggested that I implement separate logic for this in meson, similar to mesonbuild/meson@2c6ccfe and mesonbuild/meson@214d035.
That's exactly what I ended up doing.
Tested the mpv build with meson with my changes on OpenBSD (libdl is missing) and on Archlinux (glib 2.33, libdl comes as a separate library).
I …
> new custom dependency lookup for libdl

- docs/markdown/Shipping-prebuilt-binaries-as-wraps.md
This PR adds documentation to resolve https://github.com/mesonbuild/meson/issues/8830 
Installing a precompiled library without a soname field causes binaries referencing the library to require a hard link to the pre-install location instead of installing it "properly". I've documented two solutions for adding a soname to a library that is missing it.
> Update precompiled library documentation

- docs/markdown/snippets/no_ldconfig.md
- mesonbuild/backend/backends.py
- mesonbuild/minstall.py
This was a nice idea in theory, but in practice it had various problems:
- On the only platform where ldconfig is expected to be run, it is
really slow, even when the user uses a non-default prefix and ldconfig doesn't even have permission to run
- On FreeBSD, it bricked the system: #9592
- On cross builds, it should not be used and broke installing, because ldconfig may not be runnable without binfmt + qemu: #9707
- it prints weird and confusing errors in the common "custom prefix" layout: #9241
Some of these problems can be or have been fixed. But it's a constant source of footguns and complaints and for something that was originally supposed to be just "it's the right thing to do anyway, so just do it automatically" it is entirely too risky.
Ultimately I do not think there is …
> minstall: stop running ldconfig for the user

- docs/markdown/CMake-module.md
- docs/markdown/snippets/cmake_version_file_arch.md
- mesonbuild/modules/cmake.py
CMake's `write_basic_package_version_file` has supported an `ARCH_INDEPENDENT` option since version 3.14 that make it skip its architecture check in the Version file.
With this patch Meson now supports it as well, and the change is also compatible with older CMake versions, as they will simply ignore the option.
This also slightly changes the contents of the generated Version file when `arch_independent` is not set: previously, the `if()` needed to skip the arch check was always filled with an empty string, while CMake puts `"FALSE"` (or `"TRUE"`) in it. Now, that `if()` will always be filled with either `"False"` or `"True"`, better matching CMake's behaviour.
I still have to add this to the documentation and mark the new kwarg as introduced in Meson 0.62.0 (I don't know how, though), so …
> cmake: add arch_independent kwarg

- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/factory.py
- mesonbuild/dependencies/misc.py
On some platforms, this is provided by the base system, which nevertheless refrains from providing the .pc files that go along with it. As a result, it's impossible to sensibly find these dependencies.
I'm looking at you, FreeBSD...
Upstream tracking bug: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=257659
This is also a problem on macOS, but that's unfixable (and I believe they provide some truly ancient and out-of-support version anyway) and you probably want to use the homebrew OpenSSL. Still, meson can now detect these old versions and even set their version number.
> dependencies: add a system dependency for OpenSSL

- mesonbuild/backend/ninjabackend.py
- test cases/rust/17 staticlib link staticlib/branch.rs
- test cases/rust/17 staticlib link staticlib/leaf.rs
- test cases/rust/17 staticlib link staticlib/meson.build
- test cases/rust/17 staticlib link staticlib/prog.c
- test cases/rust/17 staticlib link staticlib/test.json
For static library crates that depend on other internal static library
crates, all link_with targets get promoted to link_whole targets. Due to
a bug, only link_with targets are considered when generating a Rust
target for the ninja backend. This made it impossible to link a Rust
static library with another internal Rust static library.
This change fixes that issue by chaining link_whole_targets with
link_targets, just like many other languages within the ninja backend.
> ninjabackend: treat link_whole_targets like link_targets for Rust targets

- mesonbuild/mesonlib/vsenv.py
As discussed on Matrix, this doesn't seem to be a true indicator of Visual Studio environment activation
> Remove unnecessary check during VS activation

- docs/yaml/functions/project.yaml
The array of licenses is not clear, where and SPDX expression using AND
and OR is very clear, take for example this: `['Apache', 'GPLv2']`. What
does that mean? Any Apache license you like and GPLv2? Using a valid
SPDX license identifier however makes it extremely clear what is meant:
`'Apache-2.0 OR GPL-2.0-only'`. It is very clear that you mean, "this is
Apache 2.0, however, you can use as GPL-2.0 for the purpose of linking
it into your GPL-2.0 project".
This is also useful as many projects need to create a SBOM (Software Bill Of Materials), using a SPDX (which is an ISO) standard, is extremely helpful as many of the tools that analyze an SBOM natively understand SPDX.
> docs: strongly recommend the use of SPDX instead of array of license

- mesonbuild/mesonlib/universal.py
It may be `None`. This was encountered with radare's build system on
Windows, where symbolextractor.py crashes without any output displayed.
> mesonlib: Fix Popen_safe_legacy() stderr assumption

- mesonbuild/interpreter/compiler.py
In commit 0deab2ee9efc2ffe9e43f2787611e34656e6a304 we added the ability to pass a declare_dependency() to any compiler method that accepts "dependencies", but we never marked the version it is available since.
Fixes #9957
> add FeatureNew check for compiler.* methods with dependency on internal dep

- mesonbuild/interpreter/mesonmain.py
This has never worked for built/found programs, only for script files.
In commit 2fabd4c7dc22373e99fc63823d80083ad30704b8 scripts learned an attribute stating which subproject they came from. In commit 3990754bf55727ef5593769b48f0a03c6b7a3671 dist scripts learned to run even from a subproject, and relied on that attribute to know when, in fact, they came from a subproject.
Unfortunately the original attribute was only set in one half of an if/else, and the other half returned early with only part of the work done.
Fixes #9964
> mdist: fix dist scripts in subprojects being marked as superproject scripts

- setup.cfg
This will really help with pipx run, as `pipx run meson[ninja]` will now work on any system with pipx 0.17 or newer, no dependencies required. This now includes GitHub Actions, which just updated to pipx 1.0.0. Pipx run lets you use recent (always <1 week old) versions of anything on PyPI.
> pypi: include a ninja extra

- setup.cfg
This adds 3.10 (didn't check to see if it was tested on 3.10, that should be done, but I'm using it on 3.10).
setup_requires is deprecated and should be producing warnings on modern setuptools, and never worked for setuptools anyway - setuptools can't update itself, and setuptools is what is reading this anyway!
FYI, you can keep you setup.cfg classifiers up to date with setup-cfg-fmt and pre-commit, see https://scikit-hep.org/developer for that and other recommendations for modern Python packaging.
> setup.cfg: update classifier, drop deprecated

- pyproject.toml
The first version of setuptools to properly support pyproject.toml was 42 (40-41 were buggy). It is also necessary to specify `build-backend = "setuptools.build_meta"`, otherwise you get the (horrible) default `build-backend = "setuptools.build_meta:__legacy__"`.
> setup.py: better requirements

- mesonbuild/minstall.py
RuntimeError is way too generic when we have an explicit class for "Meson reports to the user, something went wrong".
Moreover we now tell people that generic exceptions are "Meson bugs and should be reported", so our failure to do the technically correct thing and report the right kind of exception means we get haunted by demons of confusion. Specifically, people complain to us that Meson told them "there is a bug in Meson" when their install fails due to meson.build or build environment issues.
> minstall: raise explicit errors, by using MesonException

- mesonbuild/interpreter/compiler.py
In commit b30dddd4e5b4ae6e5e1e812085a00a47e3edfcf1, various refactorings were done, during which a kwarg got accidentally dropped from the function that determined part of the log message. As a result, a ':' suddenly appeared in the log message where none should be.
Example expected output:
```
Checking if "-Werror=shadow with local shadowing" compiles: YES
```
What actually happened:
```
Checking if "-Werror=shadow with local shadowing" : compiles: YES
```
Fixes #9974
> fix UI regression in compiler.compiles logging

- mesonbuild/backend/ninjabackend.py
- test cases/rust/1 basic/meson.build
- test cases/rust/1 basic/subdir/meson.build
- test cases/rust/1 basic/test.json
This substitution matches the [behaviour of rustc][1] when inferring
crate name based on file name.
[1]: https://github.com/rust-lang/rust/tree/4e8fb743ccbec27344b2dd42de7057f41d4ebfdd/compiler/rustc_session/src/output.rs#L88
> ninjabackend: fix rust program names with dashes

- mesonbuild/interpreter/interpreter.py
We do not want anyone touching this entire directory tree, but due to the way it was implemented, we only checked if its direct parent was a subproject violation. This generally worked, unless people tried to add `subprojects/` as an include directory.
Patch this hole. It now provides the same warning any sandbox violation does (but is not currently an error, just a "will become an error in the future").
> validate the literal directory "subprojects" when checking sandbox violations

- packaging/createmsi.py
Fixes regression in commit 05b5a1e56fe8f5400b65d0d69680cc6531fe74f8. This added usage of another module in the python module's introspection of `meson.exe runpython`, but the MSI packaging didn't adapt, causing it to fail to be detected due to ImportError.
Fixes #9975
> packaging: fix the MSI bundling of distutils sub-packages

- .github/workflows/macos.yml
- run_unittests.py
- unittests/helpers.py
The $CI environment variable may be generally set by Github or Gitlab actions, and is not a reliable indicator of whether we are running "CI". It could also, for an absolutely random example that didn't *just happen*, be Alpine Linux's attempt to enable the Meson testsuite in their packaging, which... uses Gitlab CI.
In this case, we do want to perform normal skipping on not-found requirements. Instead of checking for $CI, check for $MESON_CI_JOBNAME as we already use that in all of our own CI jobs for various reasons.
This makes it easier for linux distros to package Meson without accumulating hacks like "run the testsuite using `env -u CI`".
> unittests: fine-tune the check for whether we are in CI

- mesonbuild/dependencies/ui.py
On Windows using MSYS2 MinGW installing the package `mingw-w64-x86_64-wxmsw3.1` provides `wx-config-3.1`. I have tried building my software by making this exact change and it build correctly.
> Add wx-config-3.1 provided by mingw-w64-x86_64-wxmsw3.1

- mesonbuild/build.py
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreter/primitives/range.py
- mesonbuild/interpreterbase/__init__.py
- mesonbuild/interpreterbase/baseobjects.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/interpreterbase/interpreterbase.py
- mesonbuild/optinterpreter.py
- mesonbuild/wrap/wrap.py
Use a derived type when passing `subproject` around, so that mypy knows it's actually a SubProject, not a str. This means that passing anything other than a handle to the interpreter state's subproject attribute becomes a type violation, specifically when the order of the *four* different str arguments is typoed.
> FeatureNew: add mypy type annotations for subproject arg

- docs/yaml/functions/shared_module.yaml
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
Android requires shared modules that use symbols from other shared modules to be linked before they can be dlopen()ed in the correct order. Not doing so leads to a missing symbol error: https://github.com/android/ndk/issues/201
We need to always allow linking for this. Also add a soname, although it's not confirmed that it's needed, and it doesn't really hurt if it isn't needed.
> shared module: Allow linking on Android

- docs/markdown/snippets/pkgconfig_directory_variables.md
- mesonbuild/modules/pkgconfig.py
- test cases/common/44 pkgconfig-gen/meson.build
- test cases/common/44 pkgconfig-gen/test.json
Automatically generate additional variables and write them into the generated pkg-config file.
This means projects no longer need to manually define the ones they use, which is annoying for dataonly usages (it used to forbid setting the base library-relevant "reserved" ones, and now allows it only for dataonly. But it's bloat to manualy list them anyway).
It also fixes a regression in commit 248e6cf4736ef9ec636228da66c28f9be03aa74f which caused libdir to not be set, and to be unsettable, if the pkg-config file has no libraries but uses the ${libdir} expansion in a custom variable. This could be considered likely a case for dataonly, but it's not guaranteed.
Obsoletes / Closes #9992
> pkgconfig module: allow custom variables to reference builtin directories

- mesonbuild/mesonmain.py
Do not report a MesonBugException if the command is `runpython`, because that is 100% other people's code, not ours. It's only used as an alternative to sys.executable for reporting a path to python, in the event of a Windows MSI install.
While we are at it, refactor the logic for PermissionError to be a bit more unified (and sadly use isinstance instead of except, but it is what it is).
> fine-tune the logic for reporting context on tracebacks

- .flake8
- MANIFEST.in
- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/cmake/traceparser.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/detect.py
- mesonbuild/compilers/mixins/clang.py
- mesonbuild/compilers/mixins/pgi.py
- mesonbuild/dependencies/cmake.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/primitives/range.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/interpreterbase/interpreterbase.py
- mesonbuild/mesonlib/vsenv.py
- mesonbuild/minstall.py
- mesonbuild/modules/gnome.py
- mesonbuild/mparser.py
- mesonbuild/msubprojects.py
- mesonbuild/wrap/wrap.py
Down from 242 warnings to 189.
There is one behavioral change I discovered while investigating a bizarre textwrap.dedent alignment issue: df1642f15770a40f27e6635f4d212317cbd411fc
> fix malformed warning to print the way it was meant to print
Other than that it's mostly just whitespace juggling.
> flake8 fixes

- mesonbuild/dependencies/misc.py
- run_project_tests.py
- run_tests.py
- test cases/common/120 extract all shared library/meson.build
- test cases/common/155 subproject dir name collision/custom_subproject_dir/C/meson.build
- test cases/common/72 shared subproject/subprojects/C/meson.build
- test cases/common/73 shared subproject 2/subprojects/C/meson.build
- test cases/common/75 custom subproject dir/custom_subproject_dir/C/meson.build
- test cases/linuxlike/13 cmake dependency/cmVers.sh
- test cases/linuxlike/13 cmake dependency/meson.build
- unittests/helpers.py
See https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/29489
changes:
- make ninja detection faster and more robust. Actually checks, even on CI
- remove pointless dependency on bash in one test
- a couple of changes to how we check whether we are in CI. Distinguishes between "CI environment, so do UX and accessibility quirks" and "Meson CI environment, don't allow tests to be surprisingly skipped"
- fix the testsuite on musl libc
and finally:
- runtime fix for detecting `dependency('intl')`
> tests: various improvements to make alpine packaging work

- mesonbuild/mtest.py
If --no-rebuild is used, the test program might not exist, spawning a FileNotFoundError inside a long traceback rooted in subprocess.Popen trying to run that test program. Current versions of Meson even say it's an "unhandled python exception".
But we can do one better and actually tell the user what is wrong, why, and what to do to fix it. And we can do so before getting waist deep in partially running tests.
Fixes #10006
Closes #10007
> mtest: raise informative error message when test program doesn't exist

- docs/yaml/functions/summary.yaml
The docs for summary don't include all valid keywords.
> Add all supported arguments in docs for summary()

- docs/markdown/Builtin-options.md
- docs/markdown/snippets/python_module_env.md
- mesonbuild/coredata.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/python.py
The default behavior of installing relative to prefix may be unexpected, and is definitely wrong in many cases.
Give users control in order to specify that yes, they actually want to install to a venv.
This is particularly useful for projects that use meson as a build system for a python module, where *all* files shall be installed into the python site-packages.
> python module: add option to specify a python environment to install to

- docs/markdown/CMake-module.md
- docs/markdown/snippets/cmake_configure_package_config_dict.md
- mesonbuild/modules/cmake.py
- test cases/cmake/20 cmake file/meson.build
I liked so much adding a new kwarg to `write_basic_package_version_file` I thought I would try to also add something to `configure_package_config_file`. Functions taking a `cfg_data` object can generally also take a `dict`, but cmake's `configure_package_config_file` was an exception, so I added the possibility to also pass a `dict` to it.
Following @eli-schwartz's suggestion in https://github.com/mesonbuild/meson/pull/9916#discussion_r795921708 I also refactored a bit the function to use `@typed_kwargs`, but in doing so I encountered a couple of issues I don't know how to solve... The first is a regression, as now the `input` kwarg complains when passing the result of `files()`, saying that it expects a `File` or a `str` while an `array[File]` has been passed in. I think this could be …
> cmake: configure_package_config_file refactor

- mesonbuild/mtest.py
Verbose, non-parallel tests generally print their output as they run, rather than
after they finish.  This however is not the case if stdout of the test is parsed
as is the case for TAP and Rust tests.  In this case, the output during the run
is the list of the subtests, but stderr still has to be printed after the test
finishes.
> mtest: print stderr of TAP/Rust tests in verbose/non-parallel mode

- mesonbuild/modules/sourceset.py
In commit c0be7e05b070d85b38c79088df882970a5cd0279 the setting of merged sourcesets as immutable in a loop accidentally got dedented, and only applied to the last loop iteration.
Fixes regression in #9854
> sourceset module: fix minor regression in making sourcesets immutable

- mesonbuild/wrap/wraptool.py
Do not traceback when trying to update a wrap that isn't a [wrap-file], just report the problem.
Do not traceback on perfectly valid WrapDB wraps that don't have a patch_url because they have upstream meson.build, instead try to parse the version from the source tarball filename.
> wraptool: be forgiving of local wrap files

- docs/markdown/Dependencies.md
The docs don't mention this, but the shaderc system method also checks
shaderc_static if shaderc_combined is not found.
> docs: correct the shaderc documentation

- docs/markdown/snippets/jar_default_install_dir.md
- mesonbuild/build.py
- mesonbuild/environment.py
The previous install dir seemed incorrect when looking at various Linux distributions.
Closes #3830
> Change jar() default install dir

- docs/markdown/Commands.md
- docs/markdown/snippets/devenv.md
- docs/yaml/builtins/meson.yaml
- docs/yaml/functions/environment.yaml
- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreter/mesonmain.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/mdevenv.py
- mesonbuild/minstall.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/python.py
- mesonbuild/msetup.py
- test cases/unit/91 devenv/meson.build
- test cases/unit/91 devenv/src/mymod/mod.py
- test cases/unit/91 devenv/src/mymod2/meson.build
- test cases/unit/91 devenv/src/mymod2/mod2.c
- test cases/unit/91 devenv/test-devenv.py
`meson devenv` idea comes from GStreamer project' `gst-env.py` script. They have more goodies we could make everyone benefit.
- Allow setting method/separator in environment() and meson.add_devenv()
- devenv: Do not prepend empty list to PATH and LD_LIBRARY_PATH
- devenv: Add --dump option
- devenv: Setup GDB auto-load scripts
- devenv: Source bash completion scripts
- devenv: Set PYTHONPATH where we install python modules
- Add API for modules that wants to define their devenv
- modules: Make ExtensionModule inherit from NewExtensionModule
- backends: Cache creation of install data
- Cache the result of python.find_installation()
> devenv: Backport more features from gst-env.py

- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/dev.py
- mesonbuild/dependencies/misc.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/modules/unstable_external_project.py
Typically needed for stuff with completely custom logic due to being:
- method `builtin` on some systems
- a base system library on other systems or simply not providing pkg-config
Plus jdk which is, um, Java. /cc @tristan957 and cross-reference #9879
(Yes, the `self.featurechecks` list is not currently used by my PR. It *will* be used by jdk -> jni, because I have a fast path for new dependencies which I think is potentially quite common, but I don't have a fast path for deprecated dependencies which I don't foresee being at all common.)
> Dependency lookups with custom functionality can now trigger FeatureNew

- docs/markdown/Java-module.md
- docs/markdown/snippets/java_generate_native_headers.md
- mesonbuild/modules/java.py
- test cases/java/9 jdk/lib/meson.build
- test cases/java/9 jdk/src/com/mesonbuild/meson.build
After implementing a much more extensive Java native module than what
currently exists in the tests, I found shortcomings.
1. You need to be able to pass multiple Java files.
2. Meson needs more information to better track the generated native
headers.
3. Meson wasn't tracking the header files generated from inner classes.
This new function should fix all the issues the old function had with
room to grow should more functionality need to be added. What I
implemented here in this new function is essentially what I have done in
the Heterogeneous-Memory Storage Engine's Java bindings.
> Deprecate java.generate_native_header() in favor of java.generate_native_headers()

- mesonbuild/compilers/mixins/gnu.py
GCC with optimization set to 0 does not actually result in no
optimizations, which can be annoying when trying to use a debugger like
gdb, and finding that your variable has been optimized out. We already
do this with clang, so gcc is a bit of an outlier here.
> compilers/gnu: set level 0 optimization to '-O0'

- docs/yaml/functions/install_headers.yaml
- mesonbuild/interpreter/interpreter.py
It makes no sense to specify both:
- `install_dir`, which overrides the `-Dincludedir=` builtin option
- `subdir`, which suffixes the `-Dincludedir=` builtin option
We've always silently ignored the `subdir` in this case, which is really surprising if someone actually passed it and expected it to do something. We also confusingly didn't say anything in the documentation about it.
Document that the options are incompatible, and explicitly check to see if they are both passed -- if so, raise an error message pointing out that only `install_dir` should be used.
Fixes #10046
> document and raise an error for disallowed combination of install_headers args

- ci/ciimage/bionic/install.sh
- ci/ciimage/ubuntu-rolling/install.sh
This is needed in order to test a pending improvement to the jni dependency in #10048.
/cc @tristan957
The purpose of this PR is to rebuild the images with the needed change. Some images are expected to fail to rebuild due to preexisting issues and we can ignore that -- they fail the weekly scheduled rebuilds too.
This lets the CI pass on Ubuntu for the other PR, because Ubuntu *does* rebuild once this is merged to master.
> CI images: add the JRE to Ubuntu

- docs/markdown/Dependencies.md
- docs/markdown/snippets/jni-system-dep-modules.md
- mesonbuild/dependencies/dev.py
- test cases/java/9 jni/meson.build
This allows someone to link against libjvm.so and libjawt.so.
Fixes #9601 
cc @eli-schwartz @sp1ritCS
> Jni dep libraries

- docs/markdown/snippets/merge_file_sanity.md
- mesonbuild/modules/i18n.py
- mesonbuild/scripts/gettext.py
- mesonbuild/scripts/itstool.py
- mesonbuild/scripts/msgfmthelper.py
- test cases/frameworks/6 gettext/data/meson.build
- test cases/frameworks/6 gettext/data2/meson.build
By the way, argparse sucks and I hate it.
Some things this fixes:
- argparse sucks and mishandles arguments, but only sometimes
- check for tools which we need at configure time and respect machine file overrides, rather than using `shutil.which('xgettext')` as a universal sentinel. Log what we found, because state.find_program has decent logging and shutil.which does not because shutil.which is a low level python function and not something that belongs in the high level parts of the Meson interpreter
- Stop disabling really important, downright crucial parts of peoples' builds.
Fixes #6165
Fixes #8436
> lots of fixes to i18n script tool handling

- docs/markdown/snippets/find_program-version.md
- docs/yaml/objects/external_program.yaml
- mesonbuild/interpreter/interpreterobjects.py
- test cases/common/26 find program/meson.build
It is often useful to check the found version of a program without checking whether you can successfully find `find_program('foo', required: false, version: '>=XXX')`
/cc @xclaesse
> find_program: add a version() method to match the one for dependencies

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/minstall.py
- mesonbuild/mintro.py
- test cases/unit/99 install all targets/meson.build
- unittests/allplatformstests.py
Versioned shared libraries should have .so file in devel, .so.1 and
.so.1.2.3 in runtime.
> Fix default install tag for shared lib symlinks

- mesonbuild/interpreter/interpreter.py
This should have been removed in commit 4a2058cb836242a6423870e671b6b76fa48167f3 but was forgotten.
> remove unused code after subproject conversion to typed_kwargs

- docs/markdown/snippets/rust_proc_macro_crates.md
- docs/yaml/functions/_build_target_base.yaml
- mesonbuild/build.py
- test cases/failing/54 wrong shared crate type/test.json
- test cases/rust/18 proc-macro/meson.build
- test cases/rust/18 proc-macro/proc.rs
- test cases/rust/18 proc-macro/use.rs
Proc macros are the only type of rust crate that we don't support, and support is rather trivial. Plus, I've had a request to add support for them.
> Add support for rust proc-macro crates

- mesonbuild/modules/python.py
There are two cases where we can assume we found the python dependency with its requisite libraries using sysconfig:
- we found the library with find_library and are prepared to link to it
- the library is not actually part of the dependency, so its presence or absence is irrelevant
In the latter case, we should consider it found if link_libpython is False. Originally we did this, but the logic was inverted in commit 5b422fce87826beff3bca85e9c9081f22b3f45b7 in an unrelated change and without explanation, likely by accident.
Normally this doesn't much matter, since a python invariably comes with a predictably located libpython and the first condition evaluates true. But that is not true for pypy, and in fact that is the reason the link_libpython check was originally added in commit …
> fix correctly detecting whether python is found if link args are empty

- docs/markdown/snippets/env2cross.md
- mesonbuild/mesonmain.py
- mesonbuild/scripts/env2mfile.py
Let's get this ball rolling. This is very much not complete, just the basis. This is basically a port of `debcrossgen` that is used for Debian package cross-compilation. Needs among other things:
- final API design
- implementation for envvars
- also do the same for native files somehow?
- doc fixes
Add your comments and desires below.
> Add new env2cross command.

- test cases/osx/7 bitcode/meson.build
The bitcode test did not actually have bitcode enabled,
making it not really useful.
> tests: bitcode: add missing b_bitcode option

- mesonbuild/interpreter/interpreter.py
It used to be possible to do this:
```
bomb = find_program('nonexisting', required: false)
test('traceback during meson test', bomb)
```
and it would in fact bomb out, with:
```
[0/1] Running all tests.
File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 149, in run
File "/usr/lib/python3.10/site-packages/mesonbuild/mtest.py", line 2017, in run
return th.doit()
File "/usr/lib/python3.10/site-packages/mesonbuild/mtest.py", line 1685, in doit
runners.extend(self.get_test_runner(test) for test in tests)
File "/usr/lib/python3.10/site-packages/mesonbuild/mtest.py", line 1685, in <genexpr>
runners.extend(self.get_test_runner(test) for test in tests)
File …
```
> add early sanity check for test programs existing

- mesonbuild/modules/gnome.py
In commit c88bfdbefc2f79ac2dfa9bff5847c350de5f5db8 we added support for an exe_wrapper to gtkdoc, which checked twice whether the environment says it is needed, and didn't check at all whether one was provided.
The result:
```
File "/usr/lib/python3/dist-packages/mesonbuild/modules/gnome.py", line 1354, in gtkdoc
t_args.append('--run=' + ' '.join(state.environment.get_exe_wrapper().get_command()))
AttributeError: 'NoneType' object has no attribute 'get_command'
```
Instead, check whether we have a valid exe_wrapper (if we don't need one, then even when one is defined in the cross file, we get an EmptyExternalProgram) and if we do, use it.
If we don't have one, but need one, then we revert back to the behavior before commit c88bfdbefc2f79ac2dfa9bff5847c350de5f5db8, which probably means …
> fix python traceback when gtkdoc needs an exe_wrapper but doesn't have one

- docs/markdown/snippets/dataonly-pkgconfig-default-install-path.md
- mesonbuild/modules/pkgconfig.py
- test cases/common/44 pkgconfig-gen/test.json
dataonly files are architecture independent (lib vs lib64 for example).
Fixes #9902
CC @Tachi107 @eli-schwartz
> Move dataonly pkgconfig file to datadir/pkgconfig

- mesonbuild/modules/python.py
This prints many lines of unwanted `"done /absolute/path"`, I noticed this when testing 0.62.0rc1 with SciPy.
Introduced in commit 79c6075b56, Cc @xclaesse. Can this be backported for 0.62.0?
[ci skip]
> Remove a spurious debug print in Python module

- mesonbuild/compilers/detect.py
- mesonbuild/interpreter/interpreter.py
- test cases/common/66 vcstag/meson.build
We are supposed to fallback on the fallback when running the vcstagger, but instead we errored out during configure.
Fixes regression in commit b402817fb6f0392812bfa272bdbc05c9c30139fa. Before this, we used shutil.which || relative paths, and in the latter case if it could not be found we still wrote out that path but it failed to run in vcstagger. Now, we use find_program under the hood, so it needs to be run in non-fatal mode, and if it is not found, we simply keep the original command string. It's a VCS command, so if we magically end up finding it at runtime because it was installed after running configure, that is *fine*.
> fix regression in vcs_tag when the VCS program is not installed

- data/syntax-highlighting/vim/syntax/meson.vim
- docs/markdown/Rust.md
- docs/markdown/snippets/structured_sources.md
- docs/sitemap.txt
- docs/yaml/functions/_build_target_base.yaml
- docs/yaml/functions/structured_sources.yaml
- docs/yaml/objects/structured_src.yaml
- mesonbuild/ast/interpreter.py
- mesonbuild/ast/introspection.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/mesonlib/universal.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/unstable_rust.py
- mesonbuild/scripts/copy.py
- test cases/failing/121 structured source empty string/meson.build
- test cases/failing/121 structured source empty string/test.json
- test cases/failing/122 structured_sources conflicts/meson.build
- test cases/failing/122 structured_sources conflicts/test.json
- test cases/rust/18 structured sources/gen.py
- test cases/rust/18 structured sources/meson.build
- test cases/rust/18 structured sources/no_copy_test.py
- test cases/rust/18 structured sources/src/foo.rs.in
- test cases/rust/18 structured sources/src/main.rs
- test cases/rust/18 structured sources/src2/foo/mod.rs
- test cases/rust/18 structured sources/src2/main-unique.rs
- unittests/allplatformstests.py
This is a reworked version of https://github.com/mesonbuild/meson/pull/8775, with the main complaints resolved.
The purpose of this series is to provide a mechanism for languages in which filesystem layout is relevant to ensure that generated sources end up in the right place. To do this, one describes the layout they want to a `structrued_sources` object, which the backend converts (if necessary) into a series of copy commands, to build the correct directory structure in the build directory. This structure is placed in the private directory of the target, to eliminate collisions. Then the actual compile is done on the copied sources rather than on the original sources. This is done at build time to avoid reconfiguration when any of the structured sources are changed.
> Structured Sources

- mesonbuild/interpreter/interpreter.py
We need this for the python module, as implemented in commit e8375d20a9aeb8c3b0ad58f299ded0e5e978b447, but that then crashed in subprojects because those options were never forwarded to the subproject interpreter.
> give subproject interpreters a view of user defined options

- mesonbuild/backend/backends.py
- mesonbuild/mtest.py
In this case, the test fname might have an implicit extension and cannot be found by `os.path.isfile()` -- intead use `shutil.which()` since it is guaranteed to find anything that subprocess.Popen or asyncio.create_subprocess_exec can successfully run.
Fixes #10027
> mtest: fix logic bug that broke tests where the cmd is a Windows found program

- mesonbuild/modules/gnome.py
In commit 68e684d51f1e469e0d9f4b499ffda15146cad98a the _get_link_args function was modified from returning a list[str] of arguments, to a tuple of both that and a modified copy of the entire target's current/enhanced dependencies (why not just the new ones? I don't know).
However, the existing use of the function was not adapted to this change, and tried to turn this entire tuple into a node of the command line. Tuples cannot flatten to lists, and mesonlib.File or HoldableObjects don't make good command line arguments.
As a result we errored out with:
```
ERROR: Argument (['-L/path/to/builddir/', '--extra-library=foo'], [<SharedLibrary 25a6634@@foo@sha: foo>, <SharedLibrary 25a6634@@foo@sha: foo>, <SharedLibrary 25a6634@@foo@sha: foo>]) in "command" is invalid
```
Split out the flags and …
> gnome module: fix crash due to misused function while generating gir command

- mesonbuild/modules/sourceset.py
- test cases/common/212 source set configuration_data/meson.build
Dependencies in the `if_true` keyword argument do not prevent the
sources from being used; in other words, they work just like dependencies
with `disabler: false`.
However, this was broken in commit ab0ffc6a2 ("modules/sourceset: Fix
remaining typing issues", 2022-02-23) which changed logic instead of
just fixing typing issues.  This was likely an attempt to avoid using
`dependencies.Dependency` after the "dependencies" field was declared,
but it also broke QEMU.
> Fix sourceset breakage after mypy conversion

- mesonbuild/modules/python.py
It was originally added because proper detection was not working on
Debian, but that has been fixed since. It was causing annoying warning
by default when prefix is /usr/local that can only be avoided by setting
options.
> python: Remove warning about invalid install path

- mesonbuild/coredata.py
When reverting from 0.62 to 0.59, one can see an error like this:
line 1003, in load
obj = pickle.load(f)
File "/Users/pm215/src/qemu-for-merges/meson/mesonbuild/mesonlib/universal.py",
line 2076, in __setstate__
self.__init__(**state)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'module'
FAILED: build.ninja
Raise a MesonException for TypeError as well, so that reconfiguration
proceeds using cmd_line.txt.
> coredata: be even more robust on unpickling errors

- test cases/python/8 different python versions/meson.build
Apparently Azure provides 64-bit python2 when we try to test 32-bit, and that breaks everything on the 32-bit test runner.
I don't understand the environment setup, and that runner is disappearing soon anyway. Hopefully this shuts up the known breakage.
> tests: make python2 dependency on 32-bit windows non-fatal

- mesonbuild/modules/gnome.py
While gtk+-3.0 / gtk4 do exist, they have never provided the location of the gtk-update-icon-cache program as a pkgconfig variable. Trying to find one anyway, resulted in two things happening:
- a useless dep lookup
- a fatal-meson-warnings error and build failure because the get_pkgconfig_variable() in question never existed
The desktop-file-utils package is a package solely providing some command line programs, and has never provided a pkg-config file in the first place, so this always logged that the dependency was not found and fell back to normal find_program_impl(), although without fatal-meson-warnings build errors.
Fixes #10139
> gnome module: fix incorrect lookup of nonexistent dependencies in post_install

- mesonbuild/modules/unstable_rust.py
Which we pretty obviously need if any of our headers are generated
> modules/rust: set bindgen include_dirs for both build and source dir

- docs/markdown/Rust.md
VSCode is perfectly happy with the trailing `---`, github only likes
`...` apparently.
> docs/rust: fix markdown title

- mesonbuild/backend/ninjabackend.py
We print a warning if a compilation database isn't successfully generated, which is good, because that gives some visibility in case the user really wanted to use the compdb. But warnings default to being fatal with --fatal-meson-warnings, which is not so good, because this isn't a very important warning at all, and we'd rather not error out in such cases when building works fine and a random bonus IDE feature doesn't work.
Mark this particular warning as non-fatal.
Fixes side issue in https://github.com/mesonbuild/wrapdb/pull/343#issuecomment-1074545609
> ninja backend: do not fatally error on compdb failure

- mesonbuild/dependencies/dub.py
- test cases/d/14 dub with deps/meson.build
- test cases/d/14 dub with deps/test.d
This is nearly a complete rewrite of Dub dependencies that were broken except for the most simple cases.
- fix the research of target built by DUB
- explicitely state that DUB dynamic libraries and source libraries are not supported (yet) (#6581)
- fix the build settings of recipes having sub-dependencies (#7560)
- fix the link to windows library coming from dub
- sanitization, comments, explanations...
My test case is a simple executable depending on `vibe-d:http`. Vibe-d is complex and has a many dependencies.
I tested with success on Linux and Windows (to figure out the right order of static libraries took some time but is now OK).
The non-compatibility with Dub package having sub-dependencies is especially annoying and is the main motivation for me to write this PR.
My meson file …
> Fix Dub dependencies

- mesonbuild/dependencies/boost.py
Looks like boost dependency mixes up it's compiler and linker argument
order when it is removing duplicates (?) from those. This causes
unnecessary recompilations of everything depending on those components.
Use OrderedSet to remove the duplicates while also maintaining
consistent order for them.
> boost: preserve compiler/linker argument order

- mesonbuild/modules/gnome.py
Commit [a0cade8f](https://github.com/mesonbuild/meson/commit/a0cade8f1d1470cf3203baae16d181eb4df8e9fe) introduced a typo and wrongly checks for gtk4-update-icon-cache twice.
If gtk4-update-icon-cache (gtk4) is not found, look for gtk-update-icon-cache (gtk3) instead.
> gnome module: properly fallback to gtk-update-icon-cache

- mesonbuild/minstall.py
In case a link is pointing_to an absolute path and we are using $DESTDIR
we fail in case the target is missing.
This is incorrect because we may need to use an absolute path to an
already installed file that is in $DESTDIR.
So if an absolute target is not existing, check if we have such file in
$DESTDIR before failing for real.
> install_symlink: Handle $DESTDIR case for links with absolute path

- mesonbuild/msubprojects.py
- mesonbuild/wrap/wrap.py
- mesonbuild/wrap/wraptool.py
We currently inconsistently handle connection, `has_ssl`, and printing errors on urlopen failure between `meson subprojects` and `meson wrap`.
Make the latter work more like the former.
> wrap: use shared function to connect to wrapdb with better errors

- mesonbuild/mesonmain.py
argparse is the gift that keeps on giving, hahaha. Suppress the script argument when --version is specified to avoid "required argument not provided" errors, and print the python version.
The version argument is required in order to make this baseline functional as a resolved python for find_program, which may specify a version and expect this to work with python itself. Our incomplete CLI wrapper over the python CLI interface was missing this.
Fixes #10162
> runpython: support --version

- .github/workflows/macos.yml
- mesonbuild/modules/gnome.py
- test cases/frameworks/10 gtk-doc/meson.build
- test cases/frameworks/10 gtk-doc/test.json
The `-framework Foundation -framework CoreFoundation` ended up de-duplicated by OrderedSet into `-framework Foundation CoreFoundation`.
Fixes: https://github.com/mesonbuild/meson/issues/5202
> gnome: Fix gtk-doc when using multiple Apple frameworks

- mesonbuild/dependencies/dev.py
- mesonbuild/interpreter/dependencyfallbacks.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/modules/fs.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/java.py
- mesonbuild/modules/qt.py
- mesonbuild/scripts/depscan.py
- mesonbuild/scripts/run_tool.py
- run_project_tests.py
- use `__future__.annotations`
- move imports to TYPE_CHECKING
- move type-checking classes to TYPE_CHECKING
> type annotations cleanup

- data/syntax-highlighting/vim/syntax/meson.vim
- docs/markdown/snippets/new-debug-function.md
- docs/yaml/functions/debug.yaml
- mesonbuild/ast/interpreter.py
- mesonbuild/interpreter/interpreter.py
- test cases/unit/104 debug function/meson.build
- unittests/platformagnostictests.py
Adds a new debug() function that can be used in the meson.build to
log messages to the meson-log.txt that will not be printed to stdout
when configuring the project.
> Add new debug() function

- mesonbuild/compilers/mixins/gnu.py
Fixes the following ResourceWarnings:
```
ResourceWarning: subprocess 25556 is still running
_warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
mesonbuild/compilers/mixins/gnu.py:195: ResourceWarning: unclosed file <_io.BufferedReader name=4>
return gnulike_default_include_dirs(tuple(self.exelist), self.language).copy()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
> compilers/gnu: use Popen_safe to prevent resource leaks

- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/mixins/visualstudio.py
- run_tests.py
- unittests/allplatformstests.py
Add two new ways to check if functions have underscore prefix:
- Query the compiler-provided `__USER_LABEL_PREFIX__` define
- Check a hardcoded list of cases where we know the outcome
Fix #5482
> Fix underscore detection

- docs/yaml/functions/shared_library.yaml
We have always accepted an int here as an alternative to a string, but the initial documentation thought it was only a string.
> docs: correct documentation of shared_library soversions

- mesonbuild/modules/gnome.py
In commit 823da3990947a8f4a2152826f0d7229f8a7a0159 we tried to fix disappearing dependencies. Instead, we appended the replacement dependencies to the existing ones. But this, too, was wrong. The function doesn't return new dependencies... it returns a copied list of all the dependencies, then alone of all parts of that API, expects to overwrite the existing variable.
(Sadly, part of the internals actually uses the entire list for something.)
As a result, we produced a repeatedly growing list, which eventually scaled really badly and e.g. OOMed on gstreamer.
Instead, let's just replace the dependencies with the updated copy.
> fix continued breakage in gnome module API

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/modules/i18n.py
They are RunTargets because they are one-shot commands without outputs. But we implement them purely via our internal wrapper for gettext, so there is no reason to wrap them *again* in our internal wrapper for meson_exe and set a bunch of environment variables we know we absolutely do not need, use, or want.
This avoids the ugly "wrapped due to env" status, and allows users to directly see the command being run without going into despair at obscure pickled nonsense.
It also offers a tiny defense against upgrading Meson without reconfiguring. People should not do that, and we error out about this in a bunch of places, but `--internal gettext` has a perfectly stable interface just like most build tools that aren't part of Meson internals, since it uses command line arguments instead of …
> i18n: don't let our maintainer targets run via wrapped env

- mesonbuild/mesonmain.py
msys/python in MSYS2 pretends to be cygwin in all cases for some time
now, so this check was impossible to hit.
The underlying confusion it tried to prevent is still there, namely trying
to build with mingw but wrongly using a msys/cygwin python/meson.
We can use the MSYSTEM env var to detect if we are in a mingw shell, and
in case the Python doesn't match we suggest installing mingw variants of both
python and meson.
Using msys/python + meson in a MSYS environment works fine on the other hand,
so no need to error out in that case.
Fixes #8726
Also addresses the concern raised in
https://github.com/mesonbuild/meson/issues/3653#issuecomment-474122564
> main: Make the msys/python check work again, in some cases

- docs/markdown/howtox.md
- unittests/linuxliketests.py
Since this PR was first opened, just about everything it was supposed to do already happened, so now it is just refining the docs and tests for existing behavior.
> Document and test env vars a bit better

- run_project_tests.py
- run_single_test.py
We expose a reason after the string 'MESON_SKIP_TEST', but it is actually ignored when running the test, so it is only useful as documentation and really might as well be a comment.
Make it even more useful by actually printing that string after the '[SKIPPED]' message.
Also, sometimes a test can be skipped for multiple reasons, and it would be useful to know which one occurred.
> project tests: log the reason why a test is skipped

- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/unstable_wayland.py
This moves generally useful logic from GNOME module's
_get_native_binary() into find_program() implementation. We could decide
later to expose it as public API.
> wayland: Also lookup scanner in pkgconfig

- packaging/hook-mesonbuild.py
- setup.cfg
Running pyinstaller to create a bundle, and using the resulting `pyinst-tmp/meson/meson setup ...` with the cmake module revealed that no data files were being bundled, unlike what we did for setup.cfg. Fix this oversight.
Fixes #10163
> packaging: make sure pyinstaller sees our distributed data files

- .github/workflows/msys2.yml
- ci/run.ps1
- mesonbuild/modules/python.py
- run_project_tests.py
Fix one source of problems when using meson with PyPy3: the name of the DLL. 
Along the way, fix a file descriptor being left open.
> python module: windows dll name for pypy needs special casing

- mesonbuild/dependencies/qt.py
- mesonbuild/modules/qt.py
- test cases/frameworks/4 qt/meson.build
- test cases/frameworks/4 qt/qt6_lang.qrc
- test cases/frameworks/4 qt/qt6core_fr.ts
- test cases/frameworks/4 qt/qt6embedded_fr.ts
This is @jlindgren90's "Add support for Qt 6.1+" #9792 with the following changes:
1. Initialize `_QtBase.libexecdir` to `None` so earlier versions of Qt that didn't report a libexec/ directory still work.
2. Handle the non-libexec/ case in `get_qmake_host_libexecs()` too.
3. Add a new commit "tests: fix incomplete Qt 6 support" that makes test "frameworks/4 qt" really work with Qt 6.
The goal is to detect the moc, rcc, uic Qt tools on Qt 6 where they moved from the bin/ directory to the libexec/ directory.
@eli-schwartz: Since @jlindren90 has not been active lately I reworked his pull request from earlier this year. This obsoletes #9792 and #10255.
> Look for Qt 6 tools in libexec/

- mesonbuild/dependencies/qt.py
- mesonbuild/modules/qt.py
- test cases/frameworks/4 qt/test.json
- unittests/linuxliketests.py
There is broken behavior w.r.t. looking up tool names:
- we tried to find `foo-Qt5` instead of `foo-qt5`, resulting in two wrongly skipped jobs
- we don't look for `foo6` on Qt6, but the Qt Company finally standardized a name and it's not the one the community gathered around
Okay, now that we actually look for the right name, we actually find qt6 at all, ever. So now it turns out our support is broken. Yay! This goes together with #9792
> Qt: fix broken tool names

- mesonbuild/mconf.py
In print_options() k was a string instead of OptionKey, but
self.yielding_options expects OptionKey. Not sure how this has not been
catched by mypy.
Fix by keeping k as OptionKey which makes self.yielding_options useless.
Fixes: #9503
> mconf: Fix printing <inherited from main project> for yielding options

- mesonbuild/compilers/mixins/compcert.py
This has been broken ever since the original implementation. Due to a typo, the optimization flag used a zero instead of an uppercase "o", which the compiler then breaks on during argument parsing because it is an invalid argument.
Fixes #10267
> compilers: fix broken CompCert support for release flags

- docs/markdown/Syntax.md
Companion to https://github.com/mesonbuild/meson/pull/10284
> Add note in docs that multiline f-strings are not supported

- mesonbuild/mesonlib/universal.py
Solves the problem on Darwin PowerPC, when `meson` fails to identify `ppc7400` as `ppc`, which causes universal build failure.
Example: https://trac.macports.org/ticket/64787
P. S. Should these be added or not? I did not encounter such cases myself so far, but I seldom use cpu-specific optimizations.
```
stdo = stdo.replace('ppc7450', 'ppc')
stdo = stdo.replace('ppc970', 'ppc')
stdo = stdo.replace('ppc970-64', 'ppc64')
```
Ref: https://opensource.apple.com/source/cctools/cctools-836/cctools-836/libmacho/arch.c
> Fix universal builds on Darwin PPC: add ppc7400 definition

- docs/markdown/Builtin-options.md
- docs/markdown/snippets/pkgconfig-relocatable.md
- mesonbuild/coredata.py
- mesonbuild/modules/pkgconfig.py
- test cases/failing/123 pkgconfig not relocatable outside prefix/meson.build
- test cases/failing/123 pkgconfig not relocatable outside prefix/test.json
- test cases/unit/105 pkgconfig relocatable with absolute path/meson.build
- unittests/allplatformstests.py
- unittests/datatests.py
Add `relocatable` module option for the `pkgconfig` module. When set to `true` the `prefix` of the generated pkgconfig files will be relative to their `install_dir`. 
By default this is set to `false`.
For more detail see the discussion in  #10269.
> Relocatable pkgconfig

- test cases/python3/1 basic/meson.build
Match what the `python` module does.
We really should kill this module, though.
> Fix purelib and platlib validation in Python3 module.

- mesonbuild/scripts/symbolextractor.py
Choose FreeBSD backend (OpenBSD backend would also work).
> Add NetBSD support in symbolextractor.

- docs/yaml/functions/vcs_tag.yaml
- mesonbuild/interpreter/interpreter.py
- test cases/common/66 vcstag/meson.build
- test cases/common/66 vcstag/version.py
Hi,
Currently `vcs_tag` does not accept anything but string as its first `command` argument, which forces you to write things like this:
https://github.com/gsliepen/tinc/blob/1.1/meson.build#L38-L40
https://github.com/gsliepen/tinc/blob/1.1/src/include/meson.build#L3-L4
Docs were updated to match annotated types on top of the function. Not sure how you're supposed to call `vcs_tag` with `custom_target`, so there's no test for it.
Could it be an error in type annotation, or is there something obvious I'm not seeing?
> vcs_tag: properly handle non-str commands

- mesonbuild/scripts/gtkdochelper.py
Hi,
When attempting to build GLib's documentation using Meson, the build failed as the `--path` argument for `gtkdoc-mkhtml` passed paths that were separated by `:`, which is not valid on Windows `cmd.exe` consoles.  Fix this by using `os.pathsep` instead.
> gtkdochelper.py: Use os.pathsep for --path argument

- run_meson_command_tests.py
Starting with Python 3.10 Debian changed how it reports paths via sysconfig.
They now have a 'local' path segment in them, presumably to match that
when installed system-wide things to go "/usr/local". When you install in
a custom dir, though, the "local" part is not actually used. So don't use that
then.
> Strip "local" bits from system paths.

- docs/markdown/Localisation.md
Meson already supplies the same value in `mesonbuild/scripts/gettext.py`:
```
def run_potgen(src_sub: str, xgettext: str, pkgname: str, datadirs: str, args: T.List[str]) -> int:
...
return subprocess.call([xgettext, '--package-name=' + pkgname, '-p', src_sub, '-f', listfile,
'-D', os.environ['MESON_SOURCE_ROOT'], '-k_', '-o', ofile] + args,
env=child_env)
```
> docs: Remove deprecated meson.source_root() from localisation page example

- mesonbuild/compilers/mixins/visualstudio.py
Hi,
In PR #9192, we assume the `/utf-8` compiler flag in order to fix building items on non-English language version of Windows (CJK versions, in particular, which is what I am using), but then there are some drawbacks:
*  This flag is only available on Visual Studio 2015 or later.  So, if people are trying to check whether the compiler supports a certain flag, assuming `/utf-8` universally can break such checks as we are always going to get `command line warning D9002: unknown command line argument '/utf-8'` (or something like that).
*  I came across a few projects that produce broken code with this flag enabled when building on CJK language versions of Windows, such as libthai.  Maybe we want to (in another PR) add a flag in the project settings blob in the beginning of the Meson build …
> Visual Studio: Only use /utf-8 on VS2015 or later

- docs/markdown/Builtin-options.md
- mesonbuild/coredata.py
A trivial tweak to docs/help; "debug" is not a very helpful help message.
> improve help for -Ddebug

- docs/markdown/Installing.md
- mesonbuild/build.py
- mesonbuild/modules/gnome.py
Purpose of the pull request:
1. There is a regression: `CustomTarget` does not set `install_tag` correctly if one tag should be used for all outputs (see comment https://github.com/mesonbuild/meson/pull/10304#issuecomment-1107636710).
2. Currently there is no way to specify to only install `help` generated by `gnome.yelp`. So this changes allow to use the `man` `install_tag` for installing `help` files.
> Fix handling of install_tag and extend its usage in gnome module 

- mesonbuild/modules/qt.py
Since the conversion of func_custom_target to take over errorchecking from build.CustomTarget, compile_translations has been incapable of installing anything properly.
Fixes #10301
> Qt compile translations errorchecking

- docs/markdown/Reference-tables.md
- docs/markdown/snippets/mold-support.md
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/detect.py
- mesonbuild/compilers/mixins/clang.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/compilers/rust.py
- mesonbuild/linkers/detect.py
- mesonbuild/linkers/linkers.py
- unittests/linuxliketests.py
**[why]**
Support for the relatively new mold linker is missing. If someone wants
to use mold as linker `LDFLAGS="-B/path/to/mold"` has to be added instead
of the usual `CC_LD=mold meson ...` or `CXX_LD=mold meson ...`.
**[how]**
Allow `mold' as linker for clang and newer GCC versions (that versions
that have support).
The error message can be a bit off, because it is generic for all GNU
like compilers, but I guess that is ok. (i.e. 'mold' is not listed as
possible linker, even if it would be possible for the given compiler.)
**[note]**
GCC Version 12.0.1 is not sufficient to say `mold` is supported. The
expected release with support will be 12.1.0.
On the other hand people that use the un-released 12.0.1 will probably
have built it from trunk. Allowing 12.0.1 is helping bleeding edge …
> linkers: Add support for mold linker

- docs/markdown/snippets/d_compiler_checks.md
- mesonbuild/compilers/d.py
- test cases/d/14 dub with deps/meson.build
- test cases/d/15 compiler run checks/meson.build
- test cases/d/15 compiler run checks/test_sizeof.d
Implement and test a few compiler checks for D:
- run
- sizeof
- has_header
- alignment
May be a function to test built-in D versions would be useful too, but that would be specific to D.
Something like:
```meson
meson.get_compiler('d').has_version('LittleEndian')
```
> D compiler checks

- mesonbuild/build.py
- mesonbuild/dependencies/pkgconfig.py
- mesonbuild/environment.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/unstable_external_project.py
- unittests/linuxliketests.py
We need to setup the environment we pass to g-ir-scanner because it will
try to use pkg-config to find dependencies, and that must respect user
settings from machine file. Also make it use uninstalled pc files Meson
generated in the case dependencies, such as glib, have been built as
subproject.
> gnome: Make sure g-ir-scanner can use pkg-config properly

- mesonbuild/wrap/wrap.py
When using a wrapped git subproject with revision specified as tag instead of commit SHA, the clone command used for cloning subprojects prints out unnecessary warning about detached head.
Meson ignores this warning for revisions specified as commit SHAs as implemented [here](https://github.com/mesonbuild/meson/commit/b57b1050a6c6d38b3adf4b8f5e40e25892c878a6) with its corresponding issue [here](https://github.com/mesonbuild/meson/issues/9318). Meson does this by cloning the repository and then doing `checkout` while ignoring `advice.detachedHead`.
However when we use tag as revision in .wrap and doing shallow clones with `depth = 1`, git clones the repository and detaches the head automatically in one step while executing `clone` command. This is done by passing `--branch` to `git clone` …
> Ignore detached head warning while cloning subprojects with tags

- docs/markdown/Dependencies.md
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/cmake.py
- mesonbuild/dependencies/configtool.py
- mesonbuild/dependencies/pkgconfig.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreter/primitives/__init__.py
- mesonbuild/interpreter/primitives/string.py
- test cases/common/251 subproject dependency variables/meson.build
- test cases/common/251 subproject dependency variables/subprojects/subfiles/meson.build
- test cases/common/251 subproject dependency variables/subprojects/subfiles/subdir/foo.c
- test cases/common/251 subproject dependency variables/subprojects/subfiles/subdir2/foo.c
- test cases/common/251 subproject dependency variables/test.json
- test cases/failing/123 subproject sandbox violation/meson.build
- test cases/failing/123 subproject sandbox violation/meson_options.txt
- test cases/failing/123 subproject sandbox violation/subprojects/subproj1/meson.build
- test cases/failing/123 subproject sandbox violation/subprojects/subproj1/nested/meson.build
- test cases/failing/123 subproject sandbox violation/subprojects/subproj2/meson.build
- test cases/failing/123 subproject sandbox violation/subprojects/subproj3/meson.build
- test cases/failing/123 subproject sandbox violation/test.json
- test cases/unit/63 cmake parser/meson.build
There are somewhat common, reasonable and legitimate use cases for a dependency to provide data files installed to /usr which are used as command inputs. When getting a dependency from a subproject, however, the attempt to directly construct an input file from a subproject results in a sandbox violation. This means not all dependencies can be wrapped as a subproject.
One example is wayland-protocols XML files which get scanned and used to produce C source files.
Teach Meson to recognize when a string path is the result of fetching a dep.get_variable(), and special case this to be exempt from subproject violations.
> dependencies: allow get_variable to expose files from subprojects

- run_project_tests.py
Move GlobalState to a runtime T.NamedTuple, use it for constructing the tuple we are passing around rather than expecting mypy to detect that the one we already have matches.
> another day, another mypy update becomes stricter about typing

- docs/markdown/Syntax.md
- docs/markdown/snippets/support-multiline-fstring.md
- mesonbuild/interpreterbase/interpreterbase.py
- mesonbuild/mparser.py
- test cases/common/62 string arithmetic/meson.build
- test cases/common/62 string arithmetic/test.json
+ Extend the parser to recognize the multiline f-strings, which the
documentation already implies will work.
The syntax is like:
```
x = 'hello'
y = 'world'
msg = f'''This is a multiline string.
Sending a message: '@x@ @y@'
'''
```
which produces:
```
This is a multiline string.
Sending a message: 'hello world'
```
+ Added some f-string tests cases to "62 string arithmetic" to exercise
the new behavior.
> Add support for multiline f-strings

- mesonbuild/modules/python.py
Hi,
From the commit message:
<i>On Python 3.8.x and later, if the imported module requires non-system DLLs that are not installed nor bundled with the module package, `os.add_dll_directory()` must be called on every path that contains the required DLLs, so that the module
can be imported successfully by Python.</i>
<i>Make things easier for people by calling `os.add_dll_directory()` on the valid directories in %PATH%, so that such module checks can be carried out successfully with much less manual intervention.</i>
Note that for running applications, application authors and/or packagers are still responsible for bundling the needed DLLs and/or using `os.add_dll_directory()` as needed.
With blessings, thank you.
> Windows: Improve Python 3.8+ module check on Windows

- mesonbuild/interpreter/interpreter.py
This handles various edge cases.
> use shared implementation to convert files() strings to File objects

- docs/markdown/D.md
- docs/markdown/Release-notes-for-0.62.0.md
- docs/yaml/functions/declare_dependency.yaml
Fix wrong name in the documentation: `d_module_features` was used in place of `d_module_versions`.
Complete the documentation of `declare_dependency` with addition of `d_module_versions` and `d_import_dirs` kwargs.
> Fix documentation

- data/syntax-highlighting/vim/syntax/meson.vim
- docs/markdown/snippets/add_project_dependencies.md
- docs/yaml/functions/add_project_dependencies.yaml
- mesonbuild/ast/interpreter.py
- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter/compiler.py
- mesonbuild/interpreter/interpreter.py
- test cases/common/251 add_project_dependencies/inc/lib.h
- test cases/common/251 add_project_dependencies/lib.c
- test cases/common/251 add_project_dependencies/main.c
- test cases/common/251 add_project_dependencies/meson.build
- test cases/failing/124 override and add_project_dependency/inc/lib.h
- test cases/failing/124 override and add_project_dependency/lib.c
- test cases/failing/124 override and add_project_dependency/meson.build
- test cases/failing/124 override and add_project_dependency/subprojects/a/meson.build
- test cases/failing/124 override and add_project_dependency/subprojects/a/prog.c
- test cases/failing/124 override and add_project_dependency/test.json
- test cases/failing/125 targets before add_project_dependency/inc/lib.h
- test cases/failing/125 targets before add_project_dependency/lib.c
- test cases/failing/125 targets before add_project_dependency/meson.build
- test cases/failing/125 targets before add_project_dependency/test.json
This function can be used to add fundamental dependencies such as `libm`, `dependency('threads')` or glib to all build products in one fell swoop.  This can be useful whenever, due to a project's coding conventions, it is not really possible to compile any source file without including the dependency.
This function also makes it possible to add an `include_directories()` object to the project, removing the need to list both source and global directories. An example from QEMU is this:
```
add_project_arguments('-isystem', meson.current_source_dir() / 'linux-headers',
'-isystem', 'linux-headers',
language: ['c', 'cpp'])
```
which might become:
```
linux_headers = declare_dependency(include_directories: 'linux-headers').as_system('system')
add_project_dependencies(linux_headers, language: …
```
> interpreter: add a new function add_project_dependencies()

- mesonbuild/interpreter/interpreter.py
- test cases/common/251 subproject dependency variables/meson.build
- test cases/common/251 subproject dependency variables/subprojects/subfiles/foo.c
- test cases/common/251 subproject dependency variables/subprojects/subfiles/meson.build
- test cases/common/251 subproject dependency variables/test.json
Some projects treat meson.project_source_root() as the root of the dependency files, because the project itself merely wraps a bunch of datafiles. Our validation to make sure this doesn't point to another subproject, made use of pathlib.Path's generator for all component paths, which... did not include the path itself. So go ahead and explicitly check that too. Add a test case to verify it while we are at it.
Fixes https://github.com/mesonbuild/meson/pull/10103#issuecomment-1114901033
> dependencies: handle one more case of subproject installed files

- docs/markdown/Builtin-options.md
- docs/markdown/Configuring-a-build-directory.md
- docs/markdown/snippets/prefer_static.md
- mesonbuild/coredata.py
- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/hdf5.py
- mesonbuild/dependencies/misc.py
- mesonbuild/dependencies/scalapack.py
- mesonbuild/interpreter/compiler.py
- mesonbuild/mesonlib/universal.py
By default, meson will try to look for shared libraries first before
static ones. In the meson.build itself, one can use the static keyword
to control if a static library will be tried first but there's no simple
way for an end user performing a build to switch back and forth at will.
Let's cover this usecase by adding an option that allows a user to
specify if they want dependency lookups to try static or shared
libraries first. The writer of the meson.build can manually specify the
static keyword where appropriate which will override the value of this
option.
I suppose this needs test cases to go with it? I was a bit lost on where exactly tests should be made/created so that was left out for now (guidance would be appreciated).
Fixes #2816
Fixes #4276
Fixes #6109
Fixes #6629
Fixes #7621
> [RFC] add prefer_static built-in option

- mesonbuild/minit.py
Some executable names are invalid, and while it's unlikely anyone will specify such a thing using the --executable argument, it's not unlikely that people experimenting will attempt to use meson init in a directory named "test".
This then defaults to that for both the project name and the sample target name, and the latter produces errors when you try to build it.
Fixes #10321
> minit: refuse to allow creating broken projects

- docs/markdown/snippets/coverage_config_files.md
- mesonbuild/scripts/coverage.py
gcovr will read this file anyway, but if it exists we don't need to assume that the project wishes to exclude subprojects/ -- they can determine that themselves.
Fixes #3287
Closes #9761
lcov doesn't read the config file by default, but we can do the smart thing here.
Fixes #4628
> coverage: be clever and detect config files for gcovr/lcov

- mesonbuild/compilers/mixins/visualstudio.py
This pr fixes #10283 as per https://github.com/mesonbuild/meson/issues/10283#issuecomment-1100425769, namely it adds the `-Werror=unknown-warning-option` flag to the clang-cl command line like the fix for #755.
> compiler.has_argument: Add `-Werror=unknown-warning-option` to clang-cl cmd line

- docs/markdown/snippets/msvc_cplusplus_define.md
- mesonbuild/compilers/cpp.py
- test cases/windows/18 msvc cplusplus define/main.cpp
- test cases/windows/18 msvc cplusplus define/meson.build
- test cases/windows/3 cpp/meson.build
Otherwise it always returns the value for c++98, starting with MSVC 2017 15.7 or later. Earlier versions are not affected by this mis-feature
This was originally applied as 0b97d585480e973d8b149618901f7a4ddfa1a906 but later reverted because it made the CI red. Try it again, now.
> compilers/c++: Add MSVC option to make the __cplusplus define accurate

- mesonbuild/build.py
In commit fb2cdd0fe2797b30e1fd4c118407302402739a3b the internal property was renamed, but one use case of it in raising a MesonException was not changed to go with it.
This meant that instead of erroring out with:
```
ERROR: GNU symbol visibility arg XXXX not one of: default, internal, hidden, protected, inlineshidden
```
we instead errored out with:
```
AttributeError: 'SharedLibrary' object has no attribute 'symbol_visibility'
```
Fixes #9659
> fix regression in reporting errors for invalid gnu_symbol_visibility

- docs/markdown/Python-module.md
- docs/markdown/snippets/python-extension-module-visibility.md
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/modules/python.py
python compiled extensions should never need to expose any symbol other than `PyInit_*` which is declared with default visibility via `PyMODINIT_FUNC` on supported compilers.
Thus, a reasonably sane default is to mark any other symbols as hidden, while still respecting any manually specified visibility.
gate this on the version of python itself, as not all versions decorate `PyMODINIT_FUNC` properly.
/cc @rgommers
> python module: default extensions to hidden symbol visibility

- mesonbuild/linkers/linkers.py
Previously, any value other than `windows` or `console` caused an exception. 
This change allows for `efi_application` to be passed as the `win_subsystem` to MinGW based linkers.
This means Meson can now be used to build EFI applications that can be run from a UEFI shell.
I've `grep`ed the whole repository for "subsystem", and I didn't find any docs that needed updated, or any other places that 
might need changed. Please let me know if there's anything I'm missing.
fixes https://github.com/mesonbuild/meson/issues/10366
> linkers/MinGW: Allow `efi_application` value for `win_subsystem`

- packaging/create_zipapp.py
Compress files under source directory using Deflate method.
By default, files are not compressed in the archive.
Compression is active only when this option is defined.
[--compress](https://docs.python.org/3/library/zipapp.html?highlight=zipapp#cmdoption-zipapp-c) has no effect when copying an archive.
> Add optional compress

- docs/markdown/Creating-OSX-packages.md
Hello,
After I moved my Qt application, [ZeGrapher](https://github.com/AdelKS/ZeGrapher), to `meson`. I find it useful to update the doc on how to bundle, in a more automated way, OSX Qt packages as Qt offers a tool to automatize most of what needs to be done regarding its libraries.
Hope this is useful.
Adel
> [doc] update Creating-OSX-packages.md

- mesonbuild/mtest.py
This was added in commit 01be50fdd90851f17de5499537f10b5b62c9fb49 with zero explanation as a side effect of moving code around. It seems like a really bad idea and it causes people to view debugging Meson projects on e.g. debuginfod systems as "painful".
/cc @tristan957
> mtest: stop disrespecting the gdb config file

- mesonbuild/interpreter/type_checking.py
In commit 6acfe48f32110671a0adf80ad3497a35105b265d, the kwarg was added to environment() in addition to the env object methods. As part of the associated refactor, a shared KwargInfo was used, and evolved to be new since 0.62.0 in the two cases where it is in fact new.
However, it *also* set the base KwargInfo for the exact same newness, which is wrong as it was present ever since the initial introduction in 0.34.0
As usual for anything that predates 0.37.0 we simply don't tag FeatureNew. Revert this back to the same KwargInfo definition from before the refactoring commit.
Fixes #10402
> fix incorrect FeatureNew for separator kwarg in environment object methods

- mesonbuild/interpreter/interpreter.py
We were poking directly at the node, so if it was a FunctionNode then this broke. Instead, just do a reverse lookup in the overrides table to get the original find_program name.
> fix traceback when run_command has a find_program as the inline arg

- mesonbuild/interpreter/compiler.py
Change message
Header <foo.h> has symbol "BAR"
to
Header "foo.h" has symbol "BAR"
with the first part also now in bold.  This is more consistent with
other messages like
Has header "foo.h"
and
Checking whether type "foo" has member "bar"
> Tweak "header has symbol" message

- mesonbuild/compilers/mixins/ti.py
A wrong command line option is passed to the TI CL2000 compiler if the optimization level is set to 's' (0 instead of O).
> Fix optimization level 's' for the TI CL2000 compiler

- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/type_checking.py
We accept boolean false to indicate "do not install this one particular output", but the type checking simply checked if it is a bool. We do this correctly for configure_file, so copy the same validator from there.
> fix custom_target crash if boolean true is specified in install_dir

- docs/README.md
- docs/markdown/Contributing.md
- skip_ci.py
The CI correctly handles documentation changes automatically, it's no longer necessary to do it by hand.
Relevant: https://github.com/mesonbuild/meson/pull/10433
> don't tell documentation contributors to skip CI

- mesonbuild/linkers/detect.py
mingw GCC using ld.bfd emits diagnostics that include "-plugin-opt=-pass-through=-lmoldname" and this triggers a match for
mold when it should not.
Instead, always check the very beginning of the output for the linker id. This is pretty consistent:
- it is always on stdout
- GCC may put additional things on stderr we don't care about
- swift is bizarre and on some OSes redirects the linker stdout to swiftc's stderr, but it will still be the only stderr; we didn't even check stderr at all until commit 712cbe056811ebdf0d7358ba07a874717a1c736f
For gold/bfd linkers, the linker id is always the *second* word, after the legally mandated "GNU" we already check for.
> linkers: try a bit harder to autodetect the correct linker id

- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/type_checking.py
override_options makes no sense for custom_target as we don't use it for anything. Also, this was added in commit c3c30d4b060239654c9b848092692ab346ebed9d despite not being allowed in permittedKwargsc3c30d4b0.
For inexplicable reasons, we had a known_kwargs for custom_target that looped over kwargs and issued a warning, not an error, for unknown kwargs. It was impossible to ever hit that check to begin with, though, ever since commit e08d73510552fa4a3a087af1a9e5fded8f5749fd which added permittedKwargs and obsoleted those manual checks with real errors.
So at one point override_options was specially permitted to be used without emitting a warning, and then for about half a decade it was an error, and then based on some dead code it was allowed again for a bit. But through all this it …
> fix incorrectly allowed kwarg for custom_target

- docs/markdown/snippets/install_headers_preserve_path_arg.md
- docs/yaml/functions/install_headers.yaml
- mesonbuild/interpreter/interpreter.py
- test cases/common/9 header install/child/childdir.h
- test cases/common/9 header install/meson.build
- test cases/common/9 header install/test.json
This allows for structures like
```meson
headers = [
'header1.h',
'header2.h',
'header3.h',
'inner/header1.h',
'inner/header2.h',
'inner/header3.h'
]
```
with headers living alongside source files in a dir with multiple child-dirs.
to be passed to `install_headers(headers, subdir: 'mylib', preserve_path: true)` while keeping the original meaning.
This was requested in #14 and again in #3371
Fixes #3371
> implemented `preserve_path` for install_headers

- mesonbuild/backend/vs2010backend.py
Previously the output of the custom target was always captured
and it was not possible to see the output unless build failed.
> Fix that VS backend respects "console" keyword in custom_target

- docs/markdown/i18n-module.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/modules/i18n.py
- mesonbuild/modules/unstable_rust.py
- test cases/failing/26 output subdir/test.json
I started this journey wondering whether it was possible to create bad ninja targets that clash with builtin target names. Turns out it is possible, but only in very specify circumstances.
While looking at that and inspecting the sanity checking for custom_target's `output:` kwarg, I noticed that it does a lot of useful checks that aren't necessarily being done elsewhere, such as configure_file which turned out to not actually need the first fix.
So yeah, turns out that we need to do custom_target's output validator checks in several more places. Let's do that.
> better sanity checks on target output names

- mesonbuild/mdevenv.py
We might be using all fallbacks, or be super weird and not use bash-completion, or simply have a different PKG_CONFIG_LIBDIR set. And devenv already checks whether the dependency is found, but defaults to required anyway, which is wrong.
> devenv: do not fatally error if pkg-config or bash-completion is not available

- docs/markdown/Builtin-options.md
- docs/markdown/Configuring-a-build-directory.md
- mesonbuild/compilers/compilers.py
Leak sanitizer can be enabled without the whole AddressSanitizer, this
can be done by passing -fsanitize=leak as documented at [1].
Meson doesn't support this, so add support for it.
[1] https://clang.llvm.org/docs/LeakSanitizer.html
> compilers: Add support for stand-alone leak sanitizer

- docs/markdown/Wrap-dependency-system-manual.md
- docs/markdown/snippets/diff_files.md
- mesonbuild/msubprojects.py
- mesonbuild/wrap/wrap.py
- test cases/common/153 wrap file should not failed/meson.build
- test cases/common/153 wrap file should not failed/subprojects/packagefiles/patchfile/0001-Change-foo-to-executable.patch
- test cases/common/153 wrap file should not failed/subprojects/packagefiles/patchfile/0001-Change-return-value-to-43.patch
- test cases/common/153 wrap file should not failed/subprojects/packagefiles/patchfile/0002-Change-return-value-to-44.patch
- test cases/common/153 wrap file should not failed/subprojects/patchfile.wrap
As discussed in #4570, I'd like to submit an updated patch. Since I'm building on the work by @xclaesse, I added him in `Co-authored-by`.
I made the following changes compared to the original PR:
* hardcode `-p1` instead of configuring strip level: this should be good for most workflows (e.g. patches generated from Git), and if the user has an incompatible patch, they can always convert or re-generate it
* instead of a separate section, use a single property, `diff_files`:
* "diff" instead of "patch" since "Meson build patches" unfortunately already mean something else
* I proposed `diff_filename` previously, for consistency with `patch_filename`; but it looks awkward when used for multiple patches (and `diff_filenames` could be an annoying source of typos)
* parse a comma-separated list …
> wrap: Add support for applying a list of patch files

- mesonbuild/backend/backends.py
- mesonbuild/build.py
- test cases/unit/98 install all targets/meson.build
- unittests/allplatformstests.py
There are a couple issues that combine to make the current handling a bit confusing.
- we call it "install_dir_name" but it is only ever the class default
- CustomTarget always has it set to None, and then we check if it is None then create a different variable with a safe fallback. The if is useless -- it cannot fail, but if it did we'd get an undefined variable error when we tried to use `dir_name`
Remove the special handling for CustomTarget. Instead, just always accept None as a possible value of outdir_name when constructing install data, and, if it is None, fall back to {prefix}/outdir regardless of what type it used to be.
This resolves some of the confusion inherent in #9474 but unfortunately does not *actually* fix it. Python shared extension_modules are no longer generated with …
> intro-install_plan: fix destinations for build_targets with custom install_dir

- mesonbuild/modules/__init__.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/unstable_wayland.py
Just like some of glib tools, wayland-scanner can be defined in the
pkgconfig dependency variables. Share code between gnome and wayland
modules into ModuleState.
> wayland: Lookup for wayland-scanner using pkgconfig

- mesonbuild/build.py
CustomTarget.is_linkable_target has '.dylib'.
See also 93b1d31af9d90f306aa104eee1e9be8e1ebbacad that added '.dylib'
to CustomTarget.is_linkable_target but didn't add '.dylib' to
CustomTargetIndex.is_linkable_target.
> build: CustomTargetIndex.is_linkable_target misses '.dylib'

- mesonbuild/compilers/detect.py
Current version of ACfL is 22.0.2, which has 3 components. Current version detection assumes 2 components (and a build number), so maybe something like this could work?
> Allow for 3-component ACfL versions

- mesonbuild/interpreter/interpreter.py
Most importantly, tell people it's broken and to stop using it for 0.62.0
> add Feature checks for install_subdir creating an empty directory

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- unittests/baseplatformtests.py
'meson-test-prereq' now depends on any targets that were formerly added directly to 'all'. Behavior is not changed -- the all target still depends on this other meta-rule, and thus indirectly depends on all targets it used to depend on.
It is now possible to build just the targets needed for the testsuite and then e.g. run `meson test --no-rebuild`.
> ninja backend: generate additional meta-rules for test/benchmarks targets

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/xcodebackend.py
- mesonbuild/build.py
- test cases/common/216 custom target input extracted objects/check_object.py
- test cases/common/216 custom target input extracted objects/libdir/gen.py
- test cases/common/216 custom target input extracted objects/libdir/meson.build
- test cases/common/216 custom target input extracted objects/meson.build
- test cases/failing/126 extract from unity/meson.build
- test cases/failing/126 extract from unity/src1.c
- test cases/failing/126 extract from unity/src2.c
- test cases/failing/126 extract from unity/test.json
Fix yet another extract_objects corner case.  This time however the fix is generic and removes some ugly hooking from build.py to the backend. Crossing fingers that it works on Xcode and VS...
> Fix custom_target whose input is extract_objects of generated sources

- mesonbuild/interpreter/interpreter.py
- test cases/unit/107 new subproject on reconfigure/meson.build
- test cases/unit/107 new subproject on reconfigure/meson_options.txt
- test cases/unit/107 new subproject on reconfigure/subprojects/foo/foo.c
- test cases/unit/107 new subproject on reconfigure/subprojects/foo/meson.build
- unittests/platformagnostictests.py
When a subproject is disabled on the initial configuration we should not
add it into self.coredata.initialized_subprojects because that will
prevent calling self.coredata.init_builtins() on a reconfigure if the
subproject gets enabled.
Fixes: #10225.
> Fix crash when a reconfigure adds a new subproject

- mesonbuild/mdevenv.py
- mesonbuild/scripts/cmd_or_ps.ps1
Checks "pwsh.exe" in addition to "powershell.exe" and "cmd.exe"
to support PowerShell 7 on Windows. The Powershell 7 support was added
in GStreamer (which is the origin of this script) already via
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/2545
> devenv: Add support for PowerShell 7 on Windows

- tools/regenerate_docs.py
If we increment the build revision and re-release a wrap, it's a bugfix of an old version, so we can simply not bother to list it in the table. Just list the latest and greatest wrap for each tagged release.
The rest are obviously still available if you look up the relevant tag manually on github, but they aren't very interesting to show here.
> docs: only list the latest build of a given stable tag for each wrapdb entry

- mesonbuild/coredata.py
- mesonbuild/mesonlib/universal.py
- mesonbuild/minstall.py
When need to catch exceptions just like we do in coredata.load() to
print proper error message instead of backtrace when user mix meson
versions.
This happens frequently when user has a newer version of meson installed
in their HOME and then "sudo meson install" uses the system version of
meson.
> minstall: Add more safety checks when unpickling installdata

- mesonbuild/build.py
- test cases/failing/127 subproject object as a dependency/main.c
- test cases/failing/127 subproject object as a dependency/meson.build
- test cases/failing/127 subproject object as a dependency/subprojects/sub/meson.build
- test cases/failing/127 subproject object as a dependency/test.json
```python
[...]
dep_d_features = dep.d_features
for feature in ('versions', 'import_dirs'):
if feature in dep_d_features:
self.d_features[feature].extend(dep_d_features[feature])
[...]
```
Code in this snippet tries to access the `d_features` attribute on `dep` before the if-else chain can ensure that `dep` is valid.
I wasn't quite sure if this has to be executed where it currently is, so I just moved it to the end of the for loop. If that's not the case, this snippet can be made into its own function to avoid an extra call to `isinstance` and get called in the first two branches of the if-else statement.
Fixes #10468
> fix: `add_dep` function accessing `dep` attrs before checking if it's a valid dependency

- docs/genrelnotes.py
Merging snippets happens in arbitrary order -- whatever filesystem globbing results in. This didn't matter too much when we ran it once at release time and checked the resulting release notes into git. However, now that we generate a temporary version of the release notes for development versions, the order of the results will periodically change.
Sort the files before processing them in order to guarantee that whatever order they are in, they stay that way.
As a side effect, it's now technically possible to guarantee an ordering by judicious use of snippets naming.
> docs: ensure stable order of release notes

- mesonbuild/mdevenv.py
- mesonbuild/mesonlib/universal.py
- mesonbuild/mtest.py
- mesonbuild/programs.py
- mesonbuild/scripts/meson_exe.py
- Remove duplicated code in mdevenv.py
- Change the limit to 1024 instead of 2048 which is what has been
tested.
- Skip shortening if it is already short enough.
- Skip shortening with wine >= 6.4 which does not seems to have that
limitation any more.
- Downgrade exception to warning in the case WINEPATH cannot be
shortened under 1024 chars, it is possible that it will still work.
> Improve WINEPATH reduction

- mesonbuild/backend/ninjabackend.py
- mesonbuild/interpreter/dependencyfallbacks.py
- mesonbuild/modules/pkgconfig.py
At several points in the code base, f-strings are not correctly expanded due to missing 'f' string prefix. This fixes all the occurrences I could find.
> fix parameter expansion in several error messages

- mesonbuild/interpreter/interpreter.py
- test cases/unit/106 subproject symlink/cp.py
- test cases/unit/106 subproject symlink/meson.build
- test cases/unit/106 subproject symlink/symlinked_subproject/datadir/datafile
- test cases/unit/106 subproject symlink/symlinked_subproject/datadir/meson.build
- test cases/unit/106 subproject symlink/symlinked_subproject/meson.build
As discussed with @eli-schwartz in #10449  I ran into some problems with subprojects and symlinks earlier. Couldn't get it to work without the attached change. I think the current behavior is unintended but perhaps @eli-schwartz could verify I haven't misunderstood something here.
> interpreter: fix a subproject check with symlinks

- mesonbuild/scripts/externalproject.py
Sometimes the make command will be `/usr/bin/make` instead of just `make`, which will prevent the multi-threading flag from being added. This PR addresses that by removing the test entirely, as it seems to me that `self.gnu_make()` is sufficient.
Thanks to @xclaesse for finding the issue!
> Fix issue where the -j flag would sometimes not be added to certain external projects

- mesonbuild/modules/gnome.py
In commit 3dcc7125833cae138987aa4535c88dbd4dbd960d we moved to typed_pos_args. In the process, we deleted some code to specifically raise an error if you use custom_target or generator outputs, instead leaving it out of the typed pos args.
However, that support was specifically supposed to be there. It was onlyan error in part of an if statement for handling old versions of glib-compile-resources. The specific error it calls out is that we need to manually parse the depfile at configure time, due to an external bug; obviously this is impossible if the gresource is only created at build time.
Reinstate the original error message check, and allow built outputs to be used as compile_resources() inputs.
Fixes #10367
> gnome module: fix regression that broke using built xml files as gresources

- docs/markdown/Python-module.md
- docs/markdown/snippets/python-extension-module-implicit-dependency.md
- mesonbuild/modules/python.py
- test cases/python/2 extmodule/ext/meson.build
- test cases/python/2 extmodule/ext/nested/meson.build
- test cases/python/2 extmodule/ext/wrongdir/meson.build
If there isn't a preexisting dependency on python, append one. It's almost assuredly needed, so just do the right thing out of the box.
/cc @rgommers
See modified unittest. After removing the passed-around dep from `dependencies: ...` it still builds. Quickly tested with SciPy as well -- seems to build, does NOT build if you use `py3_dep.partial_dependency()` as the loophole in the release notes indicates.
As discussed elsewhere, I don't know why one would ever *not* want to have this dep, but... if you really really don't, then the partial_dependency lets you skip out on it. :shrug:
> python module: implicitly add python dep to extensions

- mesonbuild/backend/ninjabackend.py
- test cases/d/16 code generation/exe.d
- test cases/d/16 code generation/generator.d
- test cases/d/16 code generation/input.txt
- test cases/d/16 code generation/meson.build
> add D generated files to order-only deps

- mesonbuild/compilers/mixins/visualstudio.py
Hi,
From the commit message:
<i>In PR 10263, we didn't account for that we may initialize the Visual Studio-like compiler two times, once for a C compiler and once for the C++ compiler, so we end up with Meson breaking on Visual Studio 2013 or earlier, such as when building GLib.</i>
<i>Fix this by checking for a ValueError, just like what we did when /[source|execution]-charset:... is specified, , so that we do not error out when we have already removed /utf-8 from the set of always-used compiler arguments.</i>
> visualstudio.py: Don't error out when removing /utf-8 (fix regression)

- mesonbuild/interpreter/type_checking.py
- test cases/common/148 shared module resolving symbol in executable/meson.build
We have to handle this, because Windows needs to link to the implib of the executable (???) in order to create a shared module. This is explicitly checked for and handled in the backend, and creating a build target with `link_with: some_exe` still works, even. But updating declare_dependency to typed_kwargs neglected to take that into account, so creating a convenience interface for those same arguments failed.
Discovered by @paper42 from Void Linux during rc1 testing.
> fix type checking for declare_dependency to allow linking to executable

- mesonbuild/mconf.py
```python
total_width = shutil.get_terminal_size(fallback=(160, 0))[0]
_col = max(total_width // 5, 20)
four_column = (_col, _col, _col, total_width - (3 * _col))
```
In the case where `total_width <=60` is true, `textwrap.wrap(line[3], four_column[3])` raises a `ValueError` which in turn causes meson to error out and exit.
I see that this has been brought up on #10211 and believe that instead of leaving it as-is, falling back to `_col` seems to be the right thing to do.
> fix: prevent `meson configure` from exiting abnormally when the terminal width (or $COLUMNS) is equal or less than 60

- .github/workflows/file_format.yml
- .github/workflows/lint.yml
- .github/workflows/macos.yml
- .github/workflows/msys2.yml
- .github/workflows/nonative.yml
- .github/workflows/os_comp.yml
- .github/workflows/unusedargs_missingreturn.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- mesonbuild/backend/vs2010backend.py
Add a missing `lower()` for MSVCbackend platform detection. This PR will fix #10539.  
I am not familiar with meson. So I hope someone who knows MSVC backend well can check my code. Hope my changes will not affect the build of any other architectures.
> Fix the wrong detection of Win32 platform in MSVC backend

- mesonbuild/scripts/__init__.py
The old implementation assumed a path is of Windows iff the second character is a colon. However, that is not always true. First, a colon can be included in a non-Windows path. For example, it is totally fine to have a directory named `:` on Linux 5.17.0 tmpfs. Second, a Windows path may start with `\\` for UNC or extended length.
Use pathlib to handle all of these cases.
The problem was found during QEMU development:
https://github.com/patchew-project/qemu/commit/a923ba2db1bd396ecf98cc74d7ed6e2398f77fe1#diff-cb6cd6656e23b30f170ce2692ea2f8582de1cb46c92c3b659b34dcbd2ee83b19R10-R18
> Fix destdir_join

- mesonbuild/modules/pkgconfig.py
For the same reasons commit 7aa28456d ("Add dependency type for
Valgrind") removed linking with valgrind, pkgconfig shouldn't generate
"Requirements" for it, in general.
This solves dbus meson port question/issue from:
https://gitlab.freedesktop.org/dbus/dbus/-/merge_requests/303#note_1444819
> pkgconfig: do not add valgrind as requirement

- mesonbuild/modules/gnome.py
This removes one line of stderr output per GObject Introspection file
processed, e.g.
g-ir-scanner: link: gcc -o Fwupd-2.0 Fwupd-2.0.o -L. -Wl,-rpath...
> gnome module: Use --quiet to supress printing the link command line

- docs/markdown/Cross-compilation.md
When looking through the cross-compilation docs for the first time, I was slowed by the absence of minimal example.  From experiences with autotools and cmake, the compiler executable is the one thing I'm certain that I have to specify somewhere.  It wasn't unless I found [a fork](https://thiblahute.github.io/jpakkane.github.io/Cross-compilation.html) that I made the connection with the `[binaries]` section.
Even then, my first attempt omitted the `[host_machine]` section, which unfortunately worked.  I assumed that the lack of an error meant that this information had been extracted from the toolchain (eg. by looking at pre-defined macros).  Thankfully I noticed that Linux specific compiler arguments were being passed for a cross-mingw build, and looked further.
This PR adds what I think …
> docs: add cross-file example

- run_single_test.py
So you can do things like `run_single_test.py <path> -- -Ddefault_library=both`
> run_single_test: Allow passing extra args like run_project_test

- azure-pipelines.yml
- ci/intel-scripts/activate_windows.bat
- ci/intel-scripts/cache_exclude_windows.sh
- ci/intel-scripts/install_windows.bat
- ci/run.ps1
- cross/arm64cl.txt
- cross/none.txt
- mesonbuild/compilers/mixins/visualstudio.py
- test cases/fortran/14 fortran links c/meson.build
- test cases/fortran/9 cpp/meson.build
- unittests/allplatformstests.py
And fix the regression that totally broke it.
@Hofer-Julian this should fix the issue we discussed.
@dcbaker thoughts?
...
Actually running this correctly is a bag of mixed results. I don't understand why the `vc2019x64vs` job has 13 failing tests in which, randomly, I get errors about how it cannot find some command (e.g. rc.exe, but also cmd.exe)
> add intel oneAPI ifort compiler to azure and run fortran tests

- docs/markdown/Wrap-dependency-system-manual.md
It saves bandwidth and disk usage on downloaded subprojects, and people
very rarely need more than the single commit they’re using.
Add `depth=1` to the `[wrap-git]` examples in the rest of the
documentation, to make it more likely that people will copy-and-paste it
into their `.wrap` files.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
> docs: Suggest using depth=1 by default for wrap-git

- mesonbuild/backend/backends.py
If the user requests to use /Z7 debug information embedded in
object files, msvc generates a warning: (D9025 : overriding '/Zi' with '/Z7')
> backends: Remove /Zi arg if equested to use /Z7

- mesonbuild/scripts/depscan.py
In Fortran and C++ all the bits we care about are in ASCII. 8-bit
characters can only occur in comments and string literals and we don't
parse those.
Closes #10571
> Ignore encoding errors when scanning. Closes #10571.

- mesonbuild/wrap/wrap.py
The path to the patch must be provided relative to the working directory used to run the command: `patch` or `git`.
The feature doesn't work when using `meson subprojects update` without this fix.
> wrap: Fix diff_files not finding the patch to apply

- mesonbuild/backend/ninjabackend.py
Ninja backend will fail to find the vs dep dependency
prefix string in a mingw64 environment. This change
simply updates the regex to be able to capture mingw64's unique
file separation pattern.
> Fix finding of Visual studio path in mingw64

- mesonbuild/mesonmain.py
Fixed the code for reported bug raised in issues (#10584 ).
Now code will not display any python error for help command with unknown param, but instead it will show basic meson help module.
> Resolve KeyError while executing help command with unknown param

- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/unstable_wayland.py
- run_mypy.py
This ends up being pretty small since they're already using the typed_*args helpers.
> Add typing annotations to the wayland module

- mesonbuild/compilers/detect.py
meson-log.txt should contain information on what commands were run, exactly, to get some classes of error.
/cc @rgommers @mkoeppe As promised.
Inspired by https://github.com/scipy/scipy/issues/16536
The following error message:
```
C compiler for the host machine: ccache cc (clang 13.1.6 "Apple clang version 13.1.6 (clang-1316.0.21.2.5)")
C linker for the host machine: cc ld64 764
../../meson.build:1:0: ERROR: Unable to get clang pre-processor defines:
error: invalid argument '-std=gnu++11' not allowed with 'C'
A full log can be found at /Users/mkoeppe/s/sage/scipy/.mesonpy-029irg41/build/meson-logs/meson-log.txt
```
Now becomes:
```
C compiler for the host machine: clang (clang 13.0.1 "clang version 13.0.1")
C linker for the host machine: clang ld.bfd 2.36.1
meson.build:1:0: ERROR: …
```
> Improvements to logging commands during compiler detection

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/detect.py
- mesonbuild/linkers/linkers.py
- unittests/allplatformstests.py
Hi! I just got to the bottom of a regression cross-compiling a project for macOS (using the Linux-based "osxcross" toolchain).
It bisected to 0a3a9fa0c3ebf45c94d9009a59cead571cbecf7b.
The Meson behavior change that killed us (in case of LTO builds) was invoking llvm-ar with the options "csrDT" instead of "csrD"... which had been thoughtfully prevented already, but based on a condition that unfortunately doesn't work for cross builds.
Please feel free to rewrite the patch if it's an awkward fit.
The heart of the matter is replacing a `mesonlib.is_osx()` check in linkers.py.
My real-life test case is pretty horrible in terms of download size and time to test, but I can provide details if helpful.
I've tried it with the below patch successfully, and I can retest if further changes are …
> ar linker: detect the "osx ld" case (thin archives not OK) based on the host OS

- mesonbuild/backend/ninjabackend.py
- mesonbuild/scripts/depscan.py
In commit 4ca9a16288f51cce99624a2ef595d879acdc02d8 we added unreliable support (it warns you if you try it) for gcc-compatible treatment of uppercase-C files being C++ instead of C. In order to handle it correctly, we needed to evaluate can-compile by special-casing "C" to avoid lowercasing it for comparisons.
This didn't cover all cases where we check if "C" is a C++ language file. We also straight-up check the language of a file (rather than working backwards to see if a C++ compiler can compile it) when doing module scanning, and this needs to special-case "C" as well.
We also had one case where we only checked lowercase fortran extensions, but not lowercase C++ extensions. While we are at it, use lowercase for C++ as well, except the "C" special case.
Fixes #10629
> ninja depscanner: handle C++ sources named capital C

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/detect.py
- mesonbuild/linkers/__init__.py
- mesonbuild/linkers/linkers.py
- test cases/osx/9 global variable ar/libfile.c
- test cases/osx/9 global variable ar/libfile2.c
- test cases/osx/9 global variable ar/meson.build
- test cases/osx/9 global variable ar/nativefile.ini
- test cases/osx/9 global variable ar/prog.c
Apple, for some reason, decided that ranlib should not, by default, include extern'd variables in the symbol table when running ar with the `-s` option (run ranlib). So we must additionally call `ranlib -c $out` when linking a static archive, so that behavior is consistant between the Apple archiver and every other archvier other (including llvm-ar).
Incidently we never caught this because we have code to specifically chose llvm-ar when using any variaty of clang if it's available, and apple's clang is a variety of clang, and we install llvm for running llvm tests. Because of that I've modifed a test for apple that forces the use of the `ar` archiver, even when `llvm-ar` or `gcc-ar` are installed, and don't have this behavior.
> call ranlib -c after static linking on macos

- mesonbuild/modules/qt.py
(b, name) will always have the canonical tool name, not just a potentially weird bin path. We need to check stderr for qt4 tools other than lrelease, but we keyed off of the tool bin path, so matches were by no means guaranteed, and specifically, would fail if the tool is looked up via bindir.
This really should always have checked the canonical name, which is guaranteed to be correct.
Partial fix for #10443
> qt module: correctly compare program name for lrelease version

- docs/yaml/functions/custom_target.yaml
This is a follow up of the mentioned bug report:
custom_target allows selective installation if it outputs more than one
file. Mention this explicitly in install.
Additionally, fix the types for install_dir.
see: https://github.com/mesonbuild/meson/issues/505
> documentation: extend custom_target install

- mesonbuild/coredata.py
- mesonbuild/mconf.py
- test cases/unit/109 configure same noop/meson.build
- test cases/unit/109 configure same noop/meson_options.txt
- unittests/allplatformstests.py
Currently, if we run "meson configure -Doption=value", meson will
do a reconfigure when running "ninja build" afterwards, even if
the new value is the same one that was already configured previously.
To avoid this unnecessary reconfigure, let's use replace_if_different()
instead of unconditionally replacing the conf file in coredata's save()
function.
> Only reconfigure if configure options actually changed

- mesonbuild/envconfig.py
follow standard variables and allow distributions to remove some entries from their cross-files
ex:
https://github.com/void-linux/void-packages/blob/f23acdd24bfade3a4e14809fafaffe09b3c3c318/common/build-style/meson.sh#L50-L54
variables chosen from the variables nixos sets
https://github.com/NixOS/nixpkgs/blob/ea0f14a502c60223c96066de3ed548cb3be8ca47/pkgs/build-support/bintools-wrapper/setup-hook.sh#L58
sorted alphabetically
cc @Ericson2314
> envconfig: add more binutils variables

- mesonbuild/linkers/detect.py
Also, when the linker is borked and we try to detect it as Apple ld, we should not do so, so don't.
> Improve logging of issues during linker detection

- mesonbuild/mtest.py
Although the former accepts multiple awaitables, it is only ever called with a single one, so just use `wait_for` instead.
Additionally, the `try_wait_one` fails in Python 3.11, as `Process.wait()` returns a coroutine, and `asyncio.wait` only accepts tasks, so it errors out.
> mtest: Inline try_wait_one using asyncio.wait_for

- mesonbuild/build.py
- mesonbuild/dependencies/base.py
- mesonbuild/modules/gnome.py
In a bunch of places we need to list various types of libraries including custom_target outputs, and it gets very long. Use a common T.Union for this.
> typing: simplify type annotations for libraries

- mesonbuild/linkers/detect.py
Currently we invoke it with lang_args only, which is wrong and probably useless.
Fixes misdetecting the linker when overridden as -fuse-ld, which led to Meson trying to pass incompatible flags, outright failing if CFLAGS contained flags that only work with a non-default linker, or in the most benevolent case, having the status log report the wrong linker.
/cc @unhappy-ending @thesamesam
> linkers: detection should invoke the linker with lang_link_args only

- mesonbuild/interpreter/interpreter.py
- test cases/cmake/2 advanced/subprojects/cmMod/CMakeLists.txt
It ended up being more intrusive than I would have liked, but this was the only way to implement exceptions, without allowing projects to access files in the build directory.
This still won't address the issue of being able to address files in the build directory in general if the build directory is not located anywhere inside the meson project.
> cmake: Add rule relaxations for CMake subprojects (fixes #10613)

- mesonbuild/mtest.py
googletest 1.12.1 generates new JUnit4 invalid attributes file and line.
Maybe all gtest "invalid" attributes are actually valid JUnit5 attributes, and maybe schema should be upgraded to JUni5.
> mesonbuild/mtest.py: filter more invalid googletest JUnit4 attributes

- docs/markdown/Commands.md
- docs/markdown/Continuous-Integration.md
- docs/markdown/Creating-releases.md
- docs/markdown/Cross-compilation.md
- docs/markdown/Dependencies.md
- docs/markdown/GuiTutorial.md
- docs/markdown/IDE-integration.md
- docs/markdown/IndepthTutorial.md
- docs/markdown/Quick-guide.md
- docs/markdown/Release-notes-for-0.51.0.md
- docs/markdown/Release-notes-for-0.54.0.md
- docs/markdown/Release-notes-for-0.55.0.md
- docs/markdown/Release-notes-for-0.56.0.md
- docs/markdown/Release-notes-for-0.57.0.md
- docs/markdown/Using-multiple-build-directories.md
- mesonbuild/mesonmain.py
- run_project_tests.py
- unittests/baseplatformtests.py
This is ambiguous, if the build directory has the same name as a subcommand then we end up running the subcommand. It also means we have a hard time adding *new* subcommands, because if it is a popular name of a build directory then suddenly scripts that try to set up a build directory end up running a subcommand instead.
The fact that we support this at all is a legacy design. Back in the day, the "meson" program was for setting up a build directory and all other tools were their own entry points, e.g. `mesontest` or `mesonconf`. Then in commit fa278f351fe3d6924b4d1961f77b5b4a36e133f8 we migrated to the subcommand mechanism. So, for backwards compatibility, we made those tools print a warning and then invoke `meson <tool>`. We also made the `meson` tool default to setup.
However, we only …
> deprecate running "meson builddir" without setup subcommand

- mesonbuild/minstall.py
- test cases/common/190 install_mode/meson.build
install_mode can include the setuid bit, which has the special property (mentioned in the set_mode logic for minstall itself) of needing to come last, because it "will get wiped by chmod" (or at least chown).
In fact, it's not just chown that wipes setuid, but other changes as well, such as the file contents. This is not an issue for install_data / custom_target, but for compiled outputs, we run depfixer to handle rpaths. This may or may not cause edits to the binary, depending on whether we have a build rpath to wipe, or an install rpath to add. (We also may run `strip`, but that external program already has its own mode restoration logic.)
Fix this by switching the order of operations around, so that setting the permissions happens last.
Fixes …
> minstall: do not trample install_mode by rpath fixer

- docs/markdown/Fs-module.md
- docs/markdown/snippets/fs_copyfile.md
- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/fs.py
- test cases/common/14 configure file/meson.build
This is based on #9897
It's a bit of a historical accident that `configure_file` is used for copying, mainly because it was able to happen because of loose argument handling, and that we didn't yet have an `fs` module to be a clear, obvious, place to put such a helper. The `copyfile` method is basically synonymous, but with the added value of not requiring an `output` keyword argument.
> Deprecate configure_file(copy : true), and replace it with fs.copyfile

- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/modules/pkgconfig.py
- run_mypy.py
- test cases/failing/46 pkgconfig variables zero length/test.json
- test cases/failing/47 pkgconfig variables zero length value/test.json
- test cases/failing/48 pkgconfig variables not key value/test.json
- unittests/internaltests.py
~This is based on #10093.~
This began as a way to add type annotations and typed_*args to the pkgconfig module, but the typing annotations ended up leading up leading me to notice a number of other issues, largely around using CustomTarget and CustomTargetIndex as linkable targets, and around around link_whole, and then found some places where our annotations weren't strictly correct. The end result is 24 commits stepping all over the tree. I could probably shave off the last few commits and separate them into a different PR, if there was desire to land them separately.
> Add type annotations to the Pkgconfig Module, and fix lots of bugs

- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/primitives/__init__.py
- mesonbuild/interpreter/primitives/string.py
- mesonbuild/mintro.py
- mesonbuild/modules/python.py
- unittests/allplatformstests.py
Generally plumb through the values of get_option() passed to install_dir, and use this to establish the install plan name. Fixes several odd cases, such as:
- {datadir} being prepended to "share" or "include"
- dissociating custom install directories and writing them out as {prefix}/share/foo or {prefix}/lib/python3.10/site-packages
This is the second half of #9478
Fixes #10601
/cc @FFY00, @rgommers
> introspection: untangle install_plan implemetation, fix a bunch of wrong ones

- mesonbuild/interpreter/type_checking.py
- test cases/common/44 pkgconfig-gen/meson.build
- test cases/common/44 pkgconfig-gen/test.json
It used to be listified and libxml2 wrap relies on that.
> pkgconfig: Variables can be a single string

- docs/markdown/snippets/deprecated_install_mode_sticky.md
- mesonbuild/interpreter/interpreter.py
- test cases/common/190 install_mode/test.json
- unittests/linuxliketests.py
This is generally a bad idea, e.g. it causes OSError on freebsd.
It also gets ignored by solaris and thus causes unittest failures.
The proper solution is to simply reject any attempt to set this, and log a warning.
The install_emptydir function does apply the mode as well, and since it is a directory it actually does something. This is the only place where we don't reset the mode.
Although install_subdir also installs directories, and in theory it could set the mode as well, that would be a new feature. Also it doesn't provide much granularity and has mixed semantics with files. Better to let people use install_emptydir + install_subdir.
Fixes #5902
> install modes should not apply sticky bit to files

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/build.py
What happens is this:
- liba is a convenience static library
- libb is an installed static library
- libb links in liba with --link-whole
- libc links to libb
- we generate a link line with libb *and* liba, even though libb is a
strict superset of liba
This is a bug that has existed since the optimization was added to avoid
calling link-whole on convenience libraries, and to instead propagate
their dependencies up. For most linkers this is harmless, if
inefficient. However, for apple's ld64 with the addition calling `ranlib
-c`, this ends up causing multiple copies of symbols to clash (I think
that other linkers recognize that these symbols are the same and combine
them), and linking to fail.
The fix is to stop adding libraries to a target's `link_whole_targets`
when we take its objects …
> build: don't add targets to link_whole_targets if we took their objects

- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/mixins/ccrx.py
- mesonbuild/compilers/mixins/compcert.py
- mesonbuild/compilers/mixins/ti.py
- mesonbuild/compilers/mixins/xc16.py
- mesonbuild/coredata.py
- mesonbuild/linkers/detect.py
e.g. ldc -- the compiler needs to process args before consuming them.
Fixes #10693
> fix linker regression for compilers that don't accept LDFLAGS directly

- mesonbuild/modules/python.py
This reverts commit 99ad11bd9c3249f548dda0b275d9f8dd1b3f6d14.
This breaks working setups in conda. It is either wrong or incomplete and thus cannot be used.
Fixes #10737
> Revert "Windows: Improve Python 3.8+ module check on Windows"

- mesonbuild/backend/backends.py
- mesonbuild/cmake/common.py
- mesonbuild/cmake/executor.py
- mesonbuild/cmake/fileapi.py
- mesonbuild/cmake/interpreter.py
- mesonbuild/cmake/toolchain.py
- mesonbuild/cmake/traceparser.py
- mesonbuild/cmake/tracetargets.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/dependencies/cmake.py
- mesonbuild/dependencies/detect.py
- mesonbuild/dependencies/factory.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/linkers/linkers.py
- mesonbuild/mcompile.py
- mesonbuild/modules/cuda.py
- mesonbuild/modules/java.py
- mesonbuild/modules/rust.py
- mesonbuild/modules/wayland.py
- mesonbuild/scripts/coverage.py
- mesonbuild/scripts/run_tool.py
This removes all but two issues reported by flake8 for `mesonbuild`. They are mostly dealing with white spaces (7148e1b6b3dad6001746c14f778e1410b37d6187 and 057b797a42044e750a0e1a0aa5c31ae7da6a75af), but a couple of them requires in my opinion some slight moving around of the code (dfa7cf168886b74fed628c82bcfe28dc86863225) in order to meet the PEP8 coding standard while also being readable. 
The remaining errors, that I've not dealt with are
```
mesonbuild/build.py:707:71: F821 undefined name 'WrapMode'
mesonbuild/build.py:712:23: F821 undefined name 'WrapMode'
```
As I'm not entirely sure why this definition isn't imported, I've let it be as-is. That said, I'd think this would do the trick
```python
from .wrap import WrapMode
```
If someone can confirm that would be a good fix, I can …
> Flake8 errors

- mesonbuild/envconfig.py
Allow meson to use the llvm-config specified by the LLVM_CONFIG environment variable if it is defined. This was discussed in https://github.com/anarazel/postgres/pull/60#discussion_r952040174
> Add LLVM_CONFIG support

- mesonbuild/interpreterbase/interpreterbase.py
This can be triggered if someone tries to call a non-ID. The example reproducer was:
```
if (var = dependency(...)).found()
```
This produced a traceback ending in
```
raise InvalidArguments(f'Variable "{object_name}" is not callable.')
UnboundLocalError: local variable 'object_name' referenced before assignment
```
After this commit, the error is reported as:
```
ERROR: AssignmentNode is not callable.
```
> fix obscure crash on unbound variable

- mesonbuild/compilers/compilers.py
- mesonbuild/envconfig.py
- mesonbuild/scripts/env2mfile.py
Meson internally knows about many languages and tools, and `*FLAGS` variables, and which languages to use them for. Instead of duplicating this logic, import it from `mesonbuild.*`
This logic was originally standalone, but now that it is merged into the Meson tree we can have a single source of truth.
> env2mfile: reuse logical lists of interesting facts from meson itself

- mesonbuild/modules/windows.py
We had someone reporting a bug in our software build with this ugly typo (2 in one actually even! Double `d` and missing `c`) showing in the error message. I just thought I'd fix it. :-D
> Fix 2 typos in a single string which can be shown in error messages.

- mesonbuild/backend/ninjabackend.py
Currently a cosmetic bug is present: once a build dir was regenerated,
meson would start showing:
```
User defined options
backend: ninja
```
This is not true as user have not defined the option, it is default.
Fix this by omitting the `--backend ninja` parameter from "regenerate"
In my tests this does not affect the situation when one specifies
`--backend ninja` explicitly, it still shows the backend as user-defined
after reconfiguration.
Fixes: https://github.com/mesonbuild/meson/issues/10632
> backend/ninja: omit --backend when regenerating build dir

- .github/workflows/macos.yml
Need to link the qt4 install so it's in PATH.
Also need to use a symlink to fix breakage in the Tap.
> ci: Fix macOS qt4 detection

- test cases/frameworks/7 gnome/resources/generated-main.c
- test cases/frameworks/7 gnome/resources/simple-main.c
The returned GResource is transfer-none, since the generated function
basically calls g_static_resource_get_resource(). It should not be
unreffed. Causes an abort on Debian:
`GLib-GIO:ERROR:../../../gio/gresource.c:1451:g_static_resource_fini: assertion failed: (g_atomic_int_get (&resource->ref_count) >= 2)`
> tests/7 gnome: Fix incorrect unref of GResource

- test cases/frameworks/7 gnome/genmarshal/meson.build
Otherwise the test is flaky, as it may try to include a header that's
not generated yet.
> Add missing cdata update in genmarshal tests

- mesonbuild/mtest.py
- unittests/allplatformstests.py
Contains a few preparatory commits, and then the fix for the referenced commit.
Two things to call out, from the commit messages:
1) mtest: pull detection of ninja into TestHarness
This changes the exit code in case ninja isn't found from 125 to 127, which
seems more appropriate given the justification for returning 125 (to make git
bisect run skip that commit). If we can't find ninja we'll not succeed in
other commits either.
2) mtest: Run ninja build.ninja before loading tests
One issue with this is that that we will now output more useless ninja output
when nothing needs to be done (the "Entering directory" part is not repeated,
as we happen to be in the build directory already). It likely is worth
removing that output, perhaps by testing if anything needs to be done with
ninja -n, but …
> mtest: reconfigure before loading tests

- docs/markdown/Wayland-module.md
- mesonbuild/modules/wayland.py
- test cases/wayland/2 core only/meson.build
Change the name of the core_only option to include_core_only to match the flag used by wayland-scanner.
Also the use of wayland-<client|server>.h is discouraged, therefore set the default value of include_core_only to true.
> modules/wayland: Change core_only to include_core_only

- mesonbuild/minstall.py
Microsoft's WSL2 uses a Plan 9 filesystem, which returns IOError when file is missing.
Fixes: https://github.com/mesonbuild/meson/issues/10774
> minstall: handle extra error for selinuxenabled

- mesonbuild/wrap/wrap.py
When we do wrap resolution, we do a case-insensitive lookup because keys, i.e. `dep_name = variable_name`, are case insensitive. In order to check whether we should process a subproject, we need to know if the lowercased dependency name matches.
We do this by looking up the lowercase name, and assuming that the stored name is also lowercase. But for dependency_names, this isn't "case insensitive and stored in lowercase" so we need to manually force it to be consistent.
Likewise, when looking up the wrap name (which works like dependency_names and doesn't need a provide section at all) the disk filename of the wrap file is case sensitive, but needs to be manually forced for consistency.
> wrap: correctly override dependency names with capital letters

- mesonbuild/compilers/cpp.py
We compared a Visual Studio (the IDE) version, but we wanted a MSVC (the compiler) version. This caused the option to be passed for a few too many versions of MSVC, and emit a "D9002 : ignoring unknown option" on those systems.
Compare the correct version using the version mapping from https://walbourn.github.io/vs-2017-15-7-update/
Fixes #10787
Co-authored-by: CorrodedCoder <38778644+CorrodedCoder@users.noreply.github.com>
> compilers: correct the MSVC version comparison for turning on __cplusplus

- mesonbuild/compilers/compilers.py
In commit d326c87fe22507b8c25078a7cd7ed88499ba7dc1 we added a special holder object for cached compilation results, with some broken attributes:
- "command", that was never set, but used to print the log
- "args", that was set to some, but not all, of the information a fresh compilation would log, but never used
Remove the useless args attribute, call it command, and use it properly.
> compilers: fix regression in logging cached compile commands

- docs/markdown/Installing.md
GLib installs a few executables that are not needed by applications that use the glib libraries, but are used either by build systems or by user scripts. Debian splits them into libglib2.0-dev-bin and libglib2.0-bin packages. Another example is GStreamer tools (e.g. gst-launch-1.0) that Debian packages separately in gstreamer1.0-tools.
It is common enough that Meson documentation should recommend a tag for consistency across projects.
> doc: Recommend tags for libraries utilities

- mesonbuild/backend/vs2010backend.py
%% survived into the output since 038b31e72bc02f0a9b. That failed to fail, at least in the common cases, because the whole command sequence is unnecessary / redundant - it appears to come from cmake, which executes multiple commands within a single CustomBuild element. So this PR just removes all of the batch scripting.
We'd need the setlocal back if meson ever were to set the working directory and/or environment variable from within the custom build - but that seems mighty unlikely?
> vs: Fix and simplify CustomBuild command

- test cases/warning/8 target with no sources/meson.build
- test cases/warning/8 target with no sources/test.json
Since this was broken for a long time, we should have a test for it, as pointed out by @jon-turney
> tests: Add a test for a target with no sources

- mesonbuild/backend/backends.py
When calculating the output filename for a compiled object, we sanitize the whole input path, more or less. In cases where the input path is very long, this can overflow the max length of an individual filename component.
At the same time, we do want unique names so people can recognize what these outputs actually are. Compromise:
- for filepaths with >5 components (which are a lot more likely to cause problems, and simultanously less likely to have crucial information that far back in the filepath)
- if an sha1 hash of the full path, replacing all *but* those last 5 components, produces a path that is *shorter* than the original path
... then use that modified path canonicalization via a hash. Due to the use of hashes, it's unique enough to guarantee correct builds. Because we keep the …
> backends: limit maximum path of generated filenames

- mesonbuild/modules/__init__.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/hotdoc.py
- mesonbuild/modules/i18n.py
Gettext should search for input files relative to the (sub)project source root, not the global source root.
> i18n: Fix source root in Gettext targets for subprojects

- mesonbuild/mcompile.py
There is no reason to wait 2s before starting the compilation command.
Fixes: #10698.
> mcompile: Remove useless sleep

- docs/markdown/Rust.md
- docs/markdown/snippets/rust_project_json.md
- mesonbuild/arglist.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/mesonlib/universal.py
When at least one Rust target is present, we now generate a
rust-project.json file, which can be consumed by rust-analyzer. This is
placed in the build directory, and the editor must be configured to look
for this (as it is not a default search path).
Fixes: #10678
> rust: Generate a rust-project.json file when rust targets are present

- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/cmake.py
- mesonbuild/dependencies/configtool.py
- mesonbuild/dependencies/detect.py
- mesonbuild/dependencies/dev.py
- mesonbuild/dependencies/factory.py
- mesonbuild/dependencies/framework.py
- mesonbuild/dependencies/misc.py
- mesonbuild/dependencies/pkgconfig.py
- mesonbuild/dependencies/platform.py
- mesonbuild/dependencies/ui.py
- test cases/failing/78 framework dependency with version/test.json
- test cases/failing/80 gl dependency with version/test.json
- test cases/failing/81 threads dependency with version/test.json
In the debug logs, always log if a dependency lookup raises a DependencyException. In the `required: false` case, this information  would otherwise disappear forever, and we would just not even log that we tried it -- it doesn't appear in "(tried x, y and z)".
In the `required: true` case, we would re-raise the first exception if it failed to be detected. Update the raise message with the same information we print to the debug logs, indicating which dependency and which method was used in the failing attempt.
> dependencies: log the real reason for a dependency lookup failing

- mesonbuild/compilers/mixins/clike.py
- unittests/linuxliketests.py
This ensures correct removal of default include paths in -isystem options when symbolic links are involved.
> Use os.path.samefile for default include paths testing in -isystem.

- mesonbuild/msubprojects.py
- mesonbuild/wrap/wrap.py
- unittests/allplatformstests.py
Motivated by [this comment](https://github.com/mesonbuild/meson/issues/10348#issuecomment-1135107044) on #10348. This PR resolves #10348.
55624565adaba206aad79c5536e4bb04b2221c27 adds a cache file for subprojects with a wrap file. It saves off a the hash of the wrap file when it first executes the subproject. Then when configuring the subproject, it checks the current hash against the saved hash. If they differ, then it warns the user that the subproject may be out-of-date.
73e95a0c82e83d99d3d898ea9d6d029bdda4c672 is not really related, just a bit of housekeeping I came across while working on this.
> Git subproject revision checking

- mesonbuild/interpreter/type_checking.py
In commit 47426f3663f795ae9af59075297bf8215ae81f40 we migrated to typed_kwargs, but the validator accepted a list and checked to see if it was a single Dependency object.
Fixes #10813
> declare_dependency: fix regression in printing the correct error

- mesonbuild/mdevenv.py
- mesonbuild/scripts/cmd_or_ps.ps1
gwmi command does not exist any more and is replaced by Get-CimInstance. See https://github.com/PowerShell/PowerShell/issues/4766.
While at it, use a do..while loop to avoid duplicated lines.
Fixes: #10820
> Fix cmd_or_ps.ps1 script with pwsh7

- docs/markdown/snippets/conf_pager.md
- mesonbuild/mconf.py
- mesonbuild/mlog.py
It is useful to redirect some outputs, such as "meson configure" to a pager (e.h. less). This is similar to most git commands.
> mlog: Add support for pager

- .github/workflows/msys2.yml
"MSYSTEM= python ..." no longer works because of some changes in the MSYS2 runtime
Until this is fixed in either MinGW Python or the MSYS2 runtime this should revert things to the previous behaviour to get the CI green again.
See https://github.com/msys2/msys2-runtime/pull/101#issuecomment-1255195675
> CI: Add a temporary workaround for broken MSYS2 Python path separator behaviour

- mesonbuild/mesonmain.py
- address https://github.com/mesonbuild/meson/pull/10810#issuecomment-1255369694: `meson --internal regenerate` no longer handles exceptions and formats them as `ERROR: XXX`, so you just get pythonic tracebacks
- runpython shouldn't interject Meson's own suggestions about OSError
- make the error message for OSError a bit nicer
> fixes and cleanups to mesonmain entrypoint's error handler

- .pylintrc
- mesonbuild/mesonlib/universal.py
- mesonbuild/mintro.py
- mesonbuild/mlog.py
- mesonbuild/modules/gnome.py
- mesonbuild/scripts/depfixer.py
- mesonbuild/scripts/meson_exe.py
- mesonbuild/scripts/symbolextractor.py
- mesonbuild/wrap/wrap.py
- unittests/linuxliketests.py
python's `global` is a code smell, so even though this introduces a bunch of `pylint: disable` comments, I think that's a good thing. It forces you to really think about whether global is a great idea. It turns out, in fact, we don't need it nearly as much as we're using it anyway. non-assigning mutations don't need global, so you can replace
```python
global foo
foo += ['bar']
```
with
```python
foo.append('bar')
```
no `global` necessary.
You also don't need it to read a global.
And In one case we're using a global where we should be using a class var.
> pylint: warn on global use

- docs/markdown/snippets/test-maxfail.md
- mesonbuild/mtest.py
This allows early exit of the project tests once a certain number of failures are detected. For example `meson test --maxfail=1` will abort as soon as a single test fails.
Currently running tests are marked as failed via INTERRUPT.
Resolves #9352
> mtest: implement a maxfail option

- mesonbuild/backend/ninjabackend.py
- mesonbuild/mesonlib/universal.py
Type annotation, documentation string, and implementation were doing 3 different things. Change implementation to match type annotation which makes the most sense because it match what get_target_sources() does.
All callers only use keys from the returned dictionary any way, but
that's going to change in next commits.
> ninjabackend: Fix get_target_generated_sources() return type

- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/build.py
- mesonbuild/compilers/compilers.py
Use set where order does not matter, fix is_source() to really mean only source suffixes.
> compilers: Cleanup a bit languages/suffixes lists

- mesonbuild/modules/gnome.py
itstool detects a language code from the mo file’s basename, so when https://github.com/mesonbuild/meson/commit/26c1869a142a952ffa23fe566a255b259304a39b changed the file name to be prefixed with project name, values like “my-project-xx” ended up in the `xml:lang` attribute of the generated page files, instead of the expected IETF BCP 47 language tag.
Let’s fix it by passing a locale code to itstool explicitly.
----
I noticed this in gnome-nettool’s help files (click _Download from mirror_ on https://archlinux.org/packages/extra/x86_64/gnome-nettool/). For example, look at `/usr/share/help/ca/gnome-nettool/index.page`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<page xmlns="http://projectmallard.org/1.0/" type="guide" style="task" id="index" xml:lang="gnome-nettool-ca">
```
Verified …
> gnome/yelp: fix `xml:lang` attributes

- docs/markdown/Installing.md
- mesonbuild/backend/backends.py
It is common, at least in GNOME projects, to install tests. Files goes into various locations, including:
- /usr/lib/x86_64-linux-gnu/installed-tests
- /usr/share/installed-tests
- /usr/libexec/installed-tests
It is safe to assume that everything that goes into a "installed-tests" subdir should be tagged as "tests" by default.
> Automaticall tag installed tests

- mesonbuild/wrap/wrap.py
- test cases/common/254 subsubproject inplace/meson.build
- test cases/common/254 subsubproject inplace/subprojects/sub/meson.build
- test cases/common/254 subsubproject inplace/subprojects/sub/subprojects/subsub-1.0/meson.build
- test cases/common/254 subsubproject inplace/subprojects/sub/subprojects/subsub.wrap
A subproject could have a sub-subproject as a git submodule, or part of
the subproject's release tarball, and still have a wrap file for it
(e.g. needed for [provide] section). In that case we need to use the
source tree for the sub-subproject inplace instead of downloading a new
copy into the main project.
This is the case with GLib 2.74, it has a subproject "gvdb" as git
submodule, and part of release tarball, it ships gvdb.wrap file as well.
> wrap: If the directory exists in a sub-subproject, uses it inplace

- mesonbuild/compilers/mixins/clike.py
We need to support cases where the library might be called "foo.so" and therefore we check for exact matches too. But this also allows `cc.find_library('libfoo')` to find libfoo.so, which is strange and won't work in many cases. Emit a warning when this happens.
Fixes #10838
> find_library with argument beginning in "lib" is a bad idea, warn about it

- docs/markdown/Gnome-module.md
- docs/markdown/snippets/gnome_update_mime_database.md
- mesonbuild/modules/gnome.py
Fixes https://github.com/mesonbuild/meson/issues/10865
> gnome: add support for update-mime-database

- .github/workflows/macos.yml
Downgrade to LLVM-14 from LLVM-15 which is somewhat broken when using
static linking at present:
https://github.com/Homebrew/discussions/discussions/3666#discussioncomment-3681821
We can't use LLVM's lld instead of ld on macOS because we don't detect
it as an Apple linker and pass --as-needed etc to it. Even when that
is fixed and we set -lto_library etc correctly, the linker just hangs.
The LLVM@15 test is shared-only now and moved to the qt4 macOS job.
> ci: Fix llvm static linking on macOS CI

- .github/workflows/stable_builddir.yml
- manual tests/13 builddir upgrade/foo.c
- manual tests/13 builddir upgrade/lib.c
- manual tests/13 builddir upgrade/meson.build
- manual tests/13 builddir upgrade/mod.py
This tests stable maintenance branches, to ensure that build directories created with older versions of Meson continue to work without wiping, after updating to a bugfix release.
> Add stable regression test

- mesonbuild/linkers/linkers.py
As ld's manpage says:
"The ld command processes all input files in the same manner, whether they are archives or not"
> AIX: allow link_whole, it's the only supported behaviour anyway

- .github/workflows/msys2.yml
There hasn't been any progress on this upstream lately, so try what we use in MSYS2 CI right now
@eli-schwartz
> CI: add potential workaround for python crashes in MSYS2

- docs/markdown/Builtin-options.md
- docs/markdown/Configuring-a-build-directory.md
- docs/markdown/snippets/add_optimization_plain_option.md
- mesonbuild/backend/xcodebackend.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cs.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/mixins/arm.py
- mesonbuild/compilers/mixins/clang.py
- mesonbuild/compilers/mixins/compcert.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/compilers/mixins/intel.py
- mesonbuild/compilers/mixins/ti.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/compilers/mixins/xc16.py
- mesonbuild/compilers/rust.py
- mesonbuild/compilers/swift.py
- mesonbuild/coredata.py
- test cases/failing/101 number in combo/test.json
https://github.com/mesonbuild/meson/pull/9287 changed the `optimization=0` to pass `-O0` to the compiler. This change is reasonable by itself but unfortunately, it breaks `buildtype=plain`, which promises that “no extra build flags are used”.
`buildtype=plain` is important for distros like NixOS, which manage compiler flags for optimization and hardening themselves.
Let’s introduce a new optimization level that does nothing and set it as the default for `buildtype=plain`.
> compilers: Add optimization=plain option

- docs/markdown/Using-wraptool.md
- docs/markdown/snippets/wrapdb.md
- docs/yaml/functions/dependency.yaml
- mesonbuild/interpreter/dependencyfallbacks.py
- mesonbuild/wrap/wrap.py
- mesonbuild/wrap/wraptool.py
- unittests/platformagnostictests.py
New command `meson wrap update-db` downloads the DB into `subprojects/wrapdb.json`. If that file exists, dependency() will automatically download missing wrap files from WrapDB.
> Automatically use WrapDB fallback

- mesonbuild/interpreter/compiler.py
`cc.compiles()`, and other compiler checks that use `cc.compiles()` under the hood, do not use link args at all when doing the compile check, so messages like this:
```
Checking if "have zlib" with dependency -lz compiles: YES
```
are very misleading. The compiler check command-line for that is:
```
cc [...]/testfile.c -o [...]/output.obj -c -D_FILE_OFFSET_BITS=64 -O0
```
Note the lack of linker args.
> interpreter: Don't say we're using -lfoo args when we're not

- mesonbuild/backend/vs2010backend.py
Looks like setting FavorSizeOrSpeed even with `/Od` means (some) optimization is taking place, making debugging problematic.
This is what I'm using locally to avoid setting FavorSizeOrSpeed with a debug build. Obviously my mod is not distinguishing between cl or clang-cl toolsets, but I suspect that's no bad thing!
Regards
Luke.
> clang-cl with VS backend debug builds not very debuggable

- mesonbuild/build.py
> BUG: Don't add debug files as targets when not building in debug mode

- docs/markdown/snippets/preprocess.md
- docs/yaml/objects/compiler.yaml
- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/build.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/interpreter/compiler.py
- test cases/common/255 preprocess/bar.c
- test cases/common/255 preprocess/foo.c
- test cases/common/255 preprocess/foo.h
- test cases/common/255 preprocess/meson.build
- test cases/common/255 preprocess/src/file.map.in
- test cases/common/255 preprocess/src/meson.build
This exposes any clike compiler's preprocessor. Many projects preprocess their files using a custom_target() or a generator() but that implies knowing the command line syntax of different compilers (especially MSVC) which is something Meson already knows. It's makes preprocessing unconsistent because they don't use the same CFLAGS as normal compilation because a custom target does not always have access to cflags added via `add_project_arguments()`, `-Dc_args`, etc.
The way it is implemented in the ninja backend ensures that the preprocessing uses exactly the same command line than normal compilation, there is almost no special casing for preprocessor. Howerver, things are more complicated for other backends, so it internally converts to a Generator to reuse existing infrastructure.
Lots …
> Add cc.preprocess() method

- run_mypy.py
If those files are not yet known to be typed, skip them. This makes it possible to trivially check a shortlist of files that were just changed and see if they regress our mypy coverage. Ideal for use in a git pre-commit hook.
> run_mypy: add extra logging and permit specifying files to check

- docs/markdown/Reference-tables.md
- docs/markdown/snippets/asm.md
- mesonbuild/build.py
- mesonbuild/compilers/asm.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/detect.py
- mesonbuild/envconfig.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/scripts/yasm.py
- test cases/nasm/2 asm language/hello.asm
- test cases/nasm/2 asm language/meson.build
Currently Meson can only compile `.s` assembly files when the C compiler supports it. To compile `.asm` files with NASM we need a generator, see for example: https://code.videolan.org/videolan/dav1d/-/blob/master/meson.build#L442.
This adds a new language `asm` to build `.asm` files using NASM.
Note for example that OpenSSL generates .s files on Linux that build with gcc, but .asm files on Windows that build with nasm, so this is going to be useful there too.
> Add NASM compiler

- docs/markdown/snippets/summary-disabler.md
- mesonbuild/interpreter/interpreter.py
- test cases/unit/71 summary/meson.build
- unittests/allplatformstests.py
They are commonly used as a replacement for a `dependency`, and not accepting them in `summary` breaks the last example in [1] when used as a value.
Also fix a typo in the `summary` test case.
[1] https://mesonbuild.com/Disabler.html#disabling-parts-of-the-build
> Accept disablers in summary values

- docs/markdown/Reference-tables.md
- docs/markdown/snippets/asm.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/asm.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/detect.py
- mesonbuild/compilers/swift.py
- test cases/windows/21 masm/hello.masm
- test cases/windows/21 masm/meson.build
This PR is based on top of https://github.com/mesonbuild/meson/pull/9379 that adds NASM. For now this only adds the `masm` language and associate `.masm` file extension to it.
The next step, not part of this PR, is to make cl.exe preprocess `.S` files into `.masm` and then get the masm compiler pick those preprocessed files and compile them. That's basically the same workflow than a transpiler like cython.
> Add MASM compiler

- docs/markdown/Reference-tables.md
- docs/markdown/snippets/oneapi_compilers.md
- mesonbuild/compilers/c.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/detect.py
- mesonbuild/compilers/fortran.py
- run_project_tests.py
Linux-only support for oneapi compilers. I have not used meson before, but know how to use the intel compilers. My only test was to build c, cpp, and fortran hello world programs.
I introduced new classes because I expect we will want some differences (e.g. compiler id) relative to base class compiler.
Trying to unblock https://github.com/spack/spack/pull/31810#issuecomment-1272448547.
> basic oneapi compiler support for linux

- mesonbuild/dependencies/dev.py
Only searches if the project already added that language before.
CC @eli-schwartz
> Move JNISystemDependency to dependencies.base.detect_compiler

- .github/workflows/macos.yml
Fixed in Homebrew/homebrew-core#112154.
This reverts commit c20fb659f600149c08d635fc3750f03632164b9b.
CC @nirbheek
> Revert "ci: Fix llvm detection on macOS CI"

- docs/markdown/Dependencies.md
- docs/markdown/Python-module.md
- docs/markdown/_include_qt_base.md
- docs/yaml/builtins/meson.yaml
- docs/yaml/functions/_build_target_base.yaml
- docs/yaml/functions/dependency.yaml
- docs/yaml/functions/subdir_done.yaml
- mesonbuild/interpreter/interpreter.py
This is based on searching for `@FeatureNew*` decorators.
There is also one correction to a version in a decorators; `build_by_default` was added in #1303, which is 0.38.0, not 0.40.0.
> Add missing since annotations in docs

- mesonbuild/environment.py
- mesonbuild/utils/universal.py
- mesonbuild/utils/vsenv.py
Native compilation was broken if the python process was emulated on arm.
The only way I could find to reliably detect that meson is being emulated is with [IsWowProcess2](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2), as Windows will even spoof the `PROCESSOR_ARCHITECTURE` environment variable.
Also added a fix to `vsenv.py` to use the native arm64 compiler if available
> Fix native compilation on ARM64 Windows

- mesonbuild/compilers/asm.py
- mesonbuild/compilers/c.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/cs.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/detect.py
- mesonbuild/compilers/fortran.py
- mesonbuild/compilers/java.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/mixins/elbrus.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/compilers/objc.py
- mesonbuild/compilers/objcpp.py
- mesonbuild/compilers/rust.py
- mesonbuild/compilers/swift.py
- mesonbuild/compilers/vala.py
- unittests/internaltests.py
ccache was used in all command lines but disabled using CCACHE_DISABLE in Compiler.compile() method. Wrapping invokations still has a cost, especially on Windows.
With sccache things are even worse because CCACHE_DISABLE was not respected at all, making configure *extremely* slow on Windows when sccache is installed.
> compilers: Make sure to not use ccache in compiler checks

- .github/workflows/cygwin.yml
- .github/workflows/file_format.yml
- .github/workflows/images.yml
- .github/workflows/lint.yml
- .github/workflows/macos.yml
- .github/workflows/msys2.yml
- .github/workflows/nonative.yml
- .github/workflows/os_comp.yml
- .github/workflows/unusedargs_missingreturn.yml
👋 
During the testing of #10966, I noticed that in my fork every newly pushed commit cancelled CI for all branches, not just the one that was pushed. This is because, according to the [documentation](https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value), `github.head_ref` is a variable that is only defined for pull requests and not for individual push events.
This PR fixes the issue by adding the official suggested fallback value to all affected jobs.
> ci: Fix usage of concurrency in branches other than master

- mesonbuild/interpreter/interpreter.py
This was introduced in commit 3a6e2aeed9737f1082571e868ba50e72957f27c7 as part of 0.50.0, but did not contain a FeatureNew. As a result, people would use it without realizing that they broke support for versions of Meson included in their minimum requirements.
> emit a FeatureNew when using include_directories as a string

- mesonbuild/interpreter/interpreter.py
- test cases/common/178 bothlibraries/foo.cpp
- test cases/common/178 bothlibraries/main2.c
- test cases/common/178 bothlibraries/meson.build
Regression test: libccpp has both C and C++ sources. The executable only has C sources. It should still link using the C++ compiler. When using both_libraries the static has no sources and thus no compilers, resulting in the executable linking using the C compiler. https://github.com/Netflix/vmaf/issues/1107
> both_libraries: Make sure to select the right linker for static lib

- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- test cases/osx/9 global variable ar/libfile.c
- test cases/osx/9 global variable ar/libfile2.c
- test cases/osx/9 global variable ar/meson.build
- test cases/osx/9 global variable ar/nativefile.ini
- test cases/osx/9 global variable ar/prog.c
This reverts commit c94c492089e7fecb56b7cc11ea76712a770f1e34.
This broke propagated deps as well as PCH in MSVC, and has not been fixed in time for the final release of 0.64.0, so it needs to be reverted and then brought back later.
Fixes #10745
Fixes #10975
Also reverts the following commits that were broken and fixed by c94c492089e7fecb56b7cc11ea76712a770f1e34 and therefore need to be reverted by it:
- Revert "tests: Test extern'd globals on MacOS with the Apple Archiver"
This reverts commit d285be763f193606b078f218fdedc58679dfe037.
- Revert "backends/ninja: run `ranlib -c $out` when using the apple ar"
This reverts commit bdc6f243e9f95246b5801d2c0ccf64173fb280f3.
> Revert some commits that broke PCH on MSVC, and others

- mesonbuild/minstall.py
- test cases/unit/103 strip/lib.c
- unittests/linuxliketests.py
👋 
This PR fixes #10943 by ensuring the `do_strip` step runs as prescribed by the macOS man pages. I've ported existing tests to check that `strip=true` keeps working in Linux-like platforms, and works in Darwin.
> minstall: make do_strip run with -Sx for macOS targets

- mesonbuild/compilers/asm.py
This fix a crash when using NASM on Windows.
> nasm: Implement get_crt_compile_args()

- mesonbuild/backend/backends.py
- test cases/unit/98 install all targets/meson.build
- unittests/allplatformstests.py
It was only trying to guess install tag, and log missing tags, for files installed by install_data(). Do it also for all other files, especially custom_taget() that commonly installs generated headers.
> backends: Try guessing install tag for all installed files

- mesonbuild/dependencies/hdf5.py
- mesonbuild/mesonmain.py
- mesonbuild/scripts/depfixer.py
- mesonbuild/utils/universal.py
- run_tests.py
python 3.11 adds a warning that in 3.15, UTF-8 mode will be default. This is fantastic news, we'd love that. Less fantastic: this warning is silly, we *want* these checks to be affected. Plus, the recommended alternative API would (in addition to warning people when UTF-8 mode removed the problem) also require using a minimum python version of 3.11 (in which the warning was added) or add verbose if/else soup.
The simple, and obvious, approach is to add a warnings filter to hide it.
> python 3.11: suppress an incorrect EncodingWarning

- run_mypy.py
mypy has a bug when running on/for 3.11 which results in incorrect analysis of the codebase, specifically due to enum.Enum's self.name
See:
https://github.com/python/typeshed/issues/7564
https://github.com/python/mypy/issues/12483
> target python 3.10 as the mypy language version

- mesonbuild/modules/hotdoc.py
We consistently use the "dependencies" kwarg to refer to C-like CFLAGS/LDFLAGS interfaces. And for hotdoc, we actually accept libraries for this as well, as we may want to document their (generated?) sources, so we want their CFLAGS too.
But we also accepted custom targets and just added a build order dependency on these, which was odd and typically we call that "depends". Let's deprecate this in favor of the depends kwarg.
> hotdoc module: add dedicated depends kwarg, deprecate file deps in dependencies

- docs/markdown/Builtin-options.md
Fixes:
- Incorrect, redundant, or overabundant usage of "just"
- Missing punctuation
- Missing "the"
- Parenthesized text far from what it describes
There are some subjective changes, I hope those aren't controversial.
Sorry I didn't make this the same PR as https://github.com/mesonbuild/meson/pull/11025, it was only after it was merged that I noticed these less obvious errors.
> docs: improve ESL text, fix some English errors

- docs/markdown/Installing.md
PR #10826 adds a couple of missing installation tags for the GNOME module, ensure we document these.
> docs: installation tags for the GNOME module

- .github/workflows/macos.yml
- test cases/python/2 extmodule/meson.build
- test cases/python3/3 cython/meson.build
In a couple of python module tests, we try to test things that rely on the default python being the same one we look up in the python module. This is unsolvable for the deprecated python3 module, as it actually uses the in-process version of python for everything. For the python module, we could actually look up the default system python instead of the one we are running with, but then we wouldn't be testing the functionality of that alternative python... and also the install manifest tests would see files installed for the wrong version of python, and report a combination of missing+extra files...
Solve both tests by just skipping the parts we cannot check.
> tests: fix edge case where non-default python is used, by skipping it

- docs/markdown/Builtin-options.md
unescaped it's turned into a list item
> escape asterisk used for footnote

- docs/markdown/External-Project-module.md
- docs/markdown/Release-notes-for-0.56.0.md
- docs/markdown/Release-notes-for-0.57.0.md
Apparently this is a misspelling even though it has been in the docs since the creation of the module.
> Change `unstable_external_project` to `unstable-external_project`

- mesonbuild/linkers/linkers.py
The system linkers don't support this particular GNU extension on these OS'es, so don't build them there.
Based on an OpenIndiana patch created by @AndWac. Closes #9882.
> linkers: Don't build thin archives on illumos or Solaris

- mesonbuild/interpreter/interpreter.py
Penalizing users for helping to test unstable modules really makes no sense. As a fatal warning, users can no longer use `--fatal-meson-warnings`.
> Change the warning generated by importing an unstable module to non-fatal

- unittests/allplatformstests.py
clippy changed output message.
If we need to check rust version instead of the arbitrary `or` clause, please tell me.
fix #11004
> Fix test_rust_clippy for rust 1.65

- azure-pipelines.yml
- ci/coverage.ps1
- ci/run.ps1
The coverage report was always the final section of the main test run. This made it hard to scroll around and find exactly what went wrong -- particularly as not everyone realizes that coverage isn't part of the test run, but also because the output from coverage is... excessively long.
This mirrors what we do in our other workflows.
> fix confusing azure pipelines status for coverage

- mesonbuild/coredata.py
Since commit 1420d0daceb10cafb52a7405f157032a5cc811a5 we use coredata's cmd_line.txt handler to get the right setup arguments. But there's a bug in that -- it mishandles cross/native files, producing invalid descriptions of the command line. The only other place this was used, though, is when generating meson-log.txt.
Fix it to produce correctly formatted arguments.
Fixes #10980
> mdist: fix error when running tests with a cross file

- mesonbuild/templates/cudatemplates.py
The original version will output something like `xtakes no arguments`, and the modified version will correctly output `x takes no arguments`.
> Fix a typo in the CUDA template

- run_meson_command_tests.py
- run_project_tests.py
- test cases/frameworks/4 qt/meson.build
- unittests/linuxliketests.py
- we don't test Qt4 in CI
- we don't test whether the tests succeed if some random obscure system dep is installed
- we don't test non-default pythons
The latter two are just bugs in our test definitions. Then first one is actually a bug in the project definition.
...
Also throw in a free deprecation warning fix.
> Fix a few testsuite failures I encountered locally

- docs/markdown/Rust-module.md
- docs/markdown/snippets/rust_module_stabilized.md
- mesonbuild/modules/rust.py
Mesa is using the rust module in production, so we should stabilize it.
> modules/rust: stabilize

- mesonbuild/modules/hotdoc.py
Since commit 32b14b1bb533e10c7344c2e04125a226553c9b9f, hotdoc is run during configure as an external program. It turns out though, that in some cases we passed NoneType in the cmd array, previously to hotdoc.run_hotdoc.run() and now via subprocesses. The former "worked" due to ignoring unknown arguments (?) but the latter was broken because command line interfaces don't accept python NoneType objects, naturally.
End result: when for example building Meson's own documentation, this fails with a python traceback.
The reason this happens to begin with turns out to be, once again, because of the legacy debt of homebrewed kwargs parsing. We have a function for `process_known_args` that handles args and ignores them if they are NoneType, and then include_paths is handled via a custom processor …
> hotdoc module: fix broken include paths

- docs/markdown/snippets/cxx_warn_args_dtor.md
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/objcpp.py
-Wnon-virtual-dtor is not what people think of as a standard warning flag. It was previously removed from -Wall in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=16190 on the grounds that people didn't like it and were refusing to use -Wall at all because it forced this warning. Instead, it is enabled by -Weffc++ which is typically not enabled and even comes with GCC documentation warnings stating that the standard library doesn't obey it, and you might need to `grep -v` and filter out warnings. (!!!)
It doesn't fit into the typical semantics of Meson's warning_level option, which usually aligns with compiler standard warning levelsrather than a niche ideological warning level.
It was originally added in commit 22af56e05aa9cba4740d2ff303d876bb0c3cfb2b, but without any specific rationale …
> compilers: remove opinionated c++ warning flag

- mesonbuild/modules/python.py
- run_project_tests.py
In Python version prior to 3.8.7 the `sysconfig` provides the wrong suffix. The right one can be obtained from `distutils.sysconfig`. `distutils` is deprecated and will be removed in Python 3.12 thus get the information from `distutils` only when building for a Python version know to present this issue.
Simplify the extension module filename suffix lookup to use the same method used by `setuptools`.
Fixes #10960.
> python: Use correct extension filename suffix on Python < 3.8.7

- mesonbuild/cmake/interpreter.py
- mesonbuild/modules/python.py
The `py.dependency(embed: false)` method is supposed to consistently provide a distutils-like `python.pc` / `python-embed.pc` interface regardless of Python version. It handles both pkg-config and sysconfig scraping. For the latter, we respect the value of self.link_libpython as determined by distutils, and construct a fully custom dependency. For the former, we blindly assume pkg-config is correct.
It isn't correct, not until Python 3.8 when embed was added. Before then, we need to process the pkg-config dependency based on link_libpython. We did this, but only inside the extension_module method, which is obviously wrong.
Delete the special casing from extension_module, and handle it inside the dependency.
Fixes #11097
> python module: fix broken non-embed dependency

- mesonbuild/coredata.py
"meson setup" ignores unused compiler options, like "cpp_args" on a project without C++.
"meson configure" doesn't have the filtering from "set_default_options", so it fails with : ERROR: Unknown options: "cpp_args"
So now unused compiler options (ie not in coredata.options) are no longer marked unknown.
Fixes: #11060
> Ignore unused compiler options for "meson configure"

- docs/markdown/Builtin-options.md
- docs/markdown/Configuring-a-build-directory.md
- docs/markdown/snippets/warning_level_everything.md
- mesonbuild/compilers/c.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/fortran.py
- mesonbuild/compilers/mixins/arm.py
- mesonbuild/compilers/mixins/ccrx.py
- mesonbuild/compilers/mixins/compcert.py
- mesonbuild/compilers/mixins/elbrus.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/compilers/mixins/pgi.py
- mesonbuild/compilers/mixins/ti.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/compilers/mixins/xc16.py
- mesonbuild/compilers/objc.py
- mesonbuild/compilers/objcpp.py
- mesonbuild/coredata.py
- unittests/allplatformstests.py
Adds a new highest warning level that is roughly equivalent to "all warnings".
This adds a way to use `/Wall` with MSVC (without the previous broken warning),
`-Weverything` with clang, and almost all general warnings in GCC with
strictness roughly equivalent to clang's `-Weverything`.
For objectivity, all warnings are included except those that require specific
values or are related to language level compatibility.  This warning level is
mainly intended for new code, and it is expected that projects will need to add
some suppressions.
Since the warnings enabled at this level are inherently unstable with respect
to compiler versions, it is intended for use by developers and not to be set as
the default.
> Add warning_level=everything

- .github/codeql/codeql-config.yml
- .github/codeql/lgtm.qls
- .github/workflows/codeql-analysis.yml
lgtm.com was acquired by github. It is deprecated and on its way out, because they've integrated the functionality itself into github. Take a look at what its official replacement can do.
This does run as yet another Actions slot, which is already fairly excessive, but the average runtime seems about 5 minutes so that's not too bad...
> Add github's CodeQL scanner to CI.

- mesonbuild/compilers/d.py
> Don't ignore documentation-related flags for D compilers

- mesonbuild/cmake/tracetargets.py
- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/cuda.py
- mesonbuild/dependencies/dev.py
- mesonbuild/dependencies/misc.py
- mesonbuild/dependencies/mpi.py
- mesonbuild/dependencies/qt.py
Add a MissingCompiler class returned by compiler detecting methods
instead of None - accessing such an object raises a DependencyException
> @10586: [WIP] Fix crash when toolchain is missing

- mesonbuild/modules/cuda.py
Adds support for CUDA Toolkit 11.8 in the Meson CUDA module. Based on #11114 but modified.
Normally, the Meson `cuda.nvcc_arch_*()` functions are supposed to be a reflection of CMake's own [`select_compute_arch.cmake`](https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA/select_compute_arch.cmake). However, they have not added CUDA 11.8 support yet and so we are obliged to improvise by ourselves, generalizing from what already exists. This PR constitutes an attempt at it.
I have chosen to deviate from #11114 in a few significant ways, most notably:
- I selected _Lovelace_ over _Ada_. All other architecture names (e.g. _Ampere_, _Turing_) are last names, not first names. Ada breaks that pattern. Lovelace isn't a last name, it's more of a title (_"Ada, Countess of Lovelace"_) but …
> Support CUDA Toolkit 11.8

- .pylintrc
- mesonbuild/dependencies/dev.py
a.k.a. pylint: enable implicit-str-concat
Which catches a very real bug. The zlib system dependency failed to work on MSVC since initial implementation in commit
c1a3b37ab7e4ccf3a946ee4ba6da81a4c230ecc4 -- it looked for the wrong name.
Cherry-picked from #10767 because this one needs to be backported.
> fix broken zlib dependency lookup for MSVC

- .github/workflows/cygwin.yml
- .github/workflows/images.yml
- .github/workflows/website.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- mesonbuild/interpreter/interpreter.py
when using `dependency(...)` and the `not_found_message` parameter is specified, the message gets logged twice instead of once.
fixes https://github.com/mesonbuild/meson/issues/8150
> interpreter: `not_found_message` was being printed twice

- docs/markdown/Design-rationale.md
I accidentally followed a very old link and was briefly discombobulated. To save other people from this mistake, use the current location of the Meson repository, and tweak the surrounding text so it is more clear that it was written nearly 10 years ago.
Signed-off-by: Tony Finch <dot@dotat.at>
> docs: change old SourceForge link to GitHub

- data/macros.meson
Fixes the following warning when building a rpm pkg using %meson macro:
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
> Use meson setup [options] in meson RPM macro

- docs/markdown/Rust-module.md
- docs/markdown/snippets/rust_bindgen_str_include.md
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/interpreterbase/decorators.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/rust.py
- test cases/rust/12 bindgen/meson.build
- test cases/rust/12 bindgen/test.json
This also includes a flexible mechanism for creating FeaturewNew and FeatureDeprecated checks in KwargInfo structs.
> Allow string include directories to rust.bindgen

- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/scripts/clangformat.py
- test cases/common/51 run target/.clang-format
- test cases/common/51 run target/meson.build
There are two problems which this PR solves:
- `clang-format-check` will rewrite files, then rewrite them back. clang-format has an option now, which can avoid doing that and also provides better UX
- I can create a valid meson.build which produces `clang-format` rules, that the documentation *claims* will override the builtin rules, but instead Meson errors out claiming there are multiple targets named `clang-format`
> fixes for auto-generated clang-format rule (and friends)

- mesonbuild/mtest.py
- unittests/taptests.py
In commit a7e458effadbc884eacf34528df3a57b60e43fe3 we stopped erroring out on invalid TAP stream contents, with the rationale that "prove" has become more lenient.
A close reading of the TAP spec indicates why, though:
> A TAP parser is required to not consider an unknown line as an error but may optionally choose to capture said line and hand it to the test harness, which may have custom behavior attached. This is to allow for forward compatability. Test::Harness silently ignores incorrect lines, but will become more stringent in the future. TAP::Harness reports TAP syntax errors at the end of a test run.
The goal of treating unknown lines as an error in the TAP parser is not because unknown lines are fine and dandy. The goal is to allow implementing future versions of TAP, and handling …
> mtest: warn on invalid TAP output

- mesonbuild/utils/universal.py
- mesonbuild/wrap/wrap.py
- unittests/subprojectscommandtests.py
:wave:
This PR fixes #10931 by not adding `--branch` in the mentioned circumstances. I've added a new test to ensure it gets caught in the future.
> wrap: Don't use --branch with shallow clones against HEAD

- mesonbuild/modules/python.py
When finding a py.dependency() we try to use pkg-config. We then apply our own custom base class, which replaces self.name with the informative comment "override the name from the "real" dependency lookup", to which I can only say "uhhh why". Why do we want to do that???
It turns out we don't, it was just a really old legacy design because we had a SystemDependency with a .pkgdep attribute hiding the real dependency bizarro-land style. We cleaned that up in commit 4d67dd19e5b7dcec6716840d30984fa41eef55c6 and as part of that, we *shifted over* the self.name assignment to preserve the visible effects, sort of. We didn't have a *reason* to override the name, we just did it because... we weren't sure whether it mattered.
Unfortunately it very much does matter the other way -- we don't want …
> python module: don't overwrite and destroy the .pc dependency name

- docs/markdown/Commands.md
- docs/markdown/snippets/devenv.md
- mesonbuild/backend/backends.py
- mesonbuild/environment.py
- mesonbuild/mdevenv.py
- mesonbuild/modules/gnome.py
- mesonbuild/programs.py
- mesonbuild/utils/core.py
commit 9f7ce6aff2e17ba320015faffbb2f536f62cf458 (HEAD -> devenv)
devenv: Always include env for HOST machine
Cross compiled executables could still be run with an exe wrapper, or
with proper binfmt installed.
Fixes: #10999
commit 675baa28371f0c3b5106f7d6c952d47e88aa7fc8
devenv: Add executables locations to both PATH and WINEPATH
Handles the case when wine-binfmt is installed, which makes .exe files
executable without without specifying an exe wrapper.
commit c7c7af30ac91c72086d7591ec295c044e5c58825
devenv: Do not include system values in --dump
This makes --dump print variables like `FOO=/path:$FOO:/another/path`.
commit a53d1640b3f68c51968067be300e10bc158b9699
devenv: Add more info how to get gdb scripts working
Now that top builddir is not the default workdir any more, the .gdbinit
file …
> devenv: various improvements

- docs/markdown/Rust-module.md
- docs/markdown/snippets/rust_bindgen_deps.md
- mesonbuild/modules/rust.py
- test cases/rust/12 bindgen/dependencies/clib2.c
- test cases/rust/12 bindgen/dependencies/external_dep.h
- test cases/rust/12 bindgen/dependencies/internal_dep.h
- test cases/rust/12 bindgen/dependencies/internal_main.rs
- test cases/rust/12 bindgen/dependencies/meson.build
- test cases/rust/12 bindgen/meson.build
Allows passing `dependency` objects to the `rust.bindgen` method. This is useful when the header you're generating bindings for includes system headers, and needs to pass include flags to clang from said dependencies. In addition we can create correct ordering for generated sources in an `internal_dependency` for the bindgen call
This includes https://github.com/mesonbuild/meson/pull/11062, but that PR should be merged first because it needs backport, while the rest of this doesn't.
> Add a `dependencies` keyword argument to bindgen

- mesonbuild/modules/cuda.py
CUDA 12 was released yesterday. Update the CUDA module with the driver-version and compute-capabilities information.
CUDA 12 notably removes support for the Kepler (CC 3.x) architectures entirely. However, it introduces no new architectures or compute capabilities itself, as Orin (8.7), Lovelace (8.9) and Hopper (9.0) architectures were all first added in CUDA 11.8.
> CUDA 12 module updates

- mesonbuild/environment.py
- test cases/frameworks/24 libgcrypt/test.json
This is no longer implicitly installed due to libxslt. Actually though, we don't need to test this in order to ensure that the custom dependency works -- we have other jobs that test it, and the config-tool handling itself won't suddenly fail on msys2 specifically.
> CI: skip libgcrypt test on msys2

- docs/markdown/Rust-module.md
Small follow-up on #11072. This PR removes the note about the unstable API of the Rust module, since it's no longer unstable as of Meson 1.0.0.
> DOCS: Rust-module: Remove note about unstable API

- mesonbuild/mlog.py
See #11075 for details. This unbreaks pager output from e.g. `meson configure` when the user has `PAGER=less` set in their environment (without `-R`). This follows the behaviour of tools such as git and bat. If the old behaviour is *really* desired, users can still set e.g. `PAGER='less -+RXF'`.
The copy of `os.environ` is probably not required over just setting `os.environ['LESS']`, but better safe than sorry.
Also, this is only tested on current Arch Linux (and notably not Windows), as that's the only development system I have to hand right now.
> mlog: set LESS environment variable for pager.

- mesonbuild/arglist.py
OpenBSD now has execinfo as compiler lib. DragonFly has all along.
This reverts commit 0241948d8fa37f59eb93088a26e9b7ae642cc2d0.
> Revert "openbsd: execinfo is not a compiler lib"

- mesonbuild/utils/universal.py
ctypes uses FFI, and surprisingly often people's Python installations will be broken because ctypes is broken (e.g. the system libffi has been updated and Python needs to be recompiled). That is not our fault, but it does manifest as Meson failing to run. It turns out we aren't even using it though. At least, pretty often.
We have two uses of ctypes, and both of them are for Windows. One of them is already conditionally imported in the function that uses it, but the other is imported at startup. Move this down into the invoking function.
On non-Windows systems, it is now impossible for Meson to fail to run when ctypes is broken, because we don't use it. Anecdotally, this issue tends to come up on Linux systems primarily.
Fixes #11111
Closes #11112
> delay importing ctypes unless it is actually used

- mesonbuild/scripts/depfixer.py
- test cases/unit/110 classpath/com/mesonbuild/Simple.java
- test cases/unit/110 classpath/meson.build
- unittests/helpers.py
- unittests/machinefiletests.py
`fix_jar()` tries to remove an existing `Class-Path` entry from the jar manifest by postprocessing the manifest and passing it to `jar -um`.  However, `jar -um` can only add/replace manifest entries, not remove them, and it also complains loudly when replacing an entry:
Dec 13, 2022 7:11:19 PM java.util.jar.Attributes read
WARNING: Duplicate name in Manifest: Manifest-Version.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
Thus `fix_jar()` produces one such warning for each entry in the manifest and accomplishes nothing else.
Use `jar -uM` instead.  This completely removes the manifest from the jar and allows adding it back as a normal zip member, …
> depfixer: silence `fix_jar()` and make it do something

- mesonbuild/mtest.py
TAP 14 states:
> Harnesses may treat any TAP stream lacking a version as a failed test.
TAP 13 states:
> In the absence of any version line version 12 is assumed. It is an
> error to explicitly specify any version lower than 13.
So, modern TAP is saying that we should treat a missing version as a test definition bug, it's no longer okay to use a missing version as saying "let's use TAP 12". But, we can choose whether to treat it that way or error out.
Let's do a diagnostic, as we do elsewhere. But allow TAP streams that aren't well defined, if they used to be well defined (back in TAP 12).
> mtest: handle TAP tests with unknown version.

- .lgtm.yml
- README.md
- setup.cfg
LGTM is [discontinued](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/) and badges, scanning have already been disabled.
As a side note, I added Python 3.11 to setup.cfg classifiers.
> LGTM remove

- docs/yaml/functions/_build_target_base.yaml
- test cases/unit/15 prebuilt object/cp.py
- test cases/unit/15 prebuilt object/meson.build
The documentation for build_target(...) does not list file or str as the possible types for the "objects" keyword argument, even though in theory the argument is meant for prebuild object files that are part of the sources.
Of course that is only the theory, because an ExtractedObjects object is probably used a lot more than a file in the source tree.  But at least make the reference manual's typing information accurate.
> fix build_target(objects: ...) documentation

- mesonbuild/interpreter/interpreter.py
`static_library` has already calculated pic for us, so let's use that instead of re-calculating.
This was based on some issues I noticed in my build.py typed_kwargs series
> use static_library's pic calculation instead of recalculating

- mesonbuild/dependencies/pkgconfig.py
If `pkg-config --modversion foobar` fails, we don't know why. The general issue here, though, is that call_pkgbin routinely logs stdout for informational purposes, but not stderr.
Fixes #11076
> dependencies: better logging of pkg-config call outputs

- cross/wasm.txt
- mesonbuild/compilers/c.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/detect.py
- mesonbuild/compilers/mixins/emscripten.py
- mesonbuild/linkers/linkers.py
See the individual commits for more details. 
In short, this PR ensures that Emscripten settings are specified without a space between the `-s` and option name. This would fix the generation of pkg-config files that CMake cannot link against, see for example this diff:
<details>
<summary>Details</summary>
```diff
--- a/vips.pc
+++ b/vips.pc
@@ -6,5 +6,5 @@ Name: vips
Description: Image processing library
Version: 8.13.2
Requires: glib-2.0 >= 2.40, gio-2.0, gobject-2.0, gmodule-no-export-2.0, expat, imagequant, cgif >= 0.2.0, libexif >= 0.6, libjpeg, spng >= 0.7, libwebp >= 0.6, libwebpmux >= 0.6, libwebpdemux >= 0.6, libtiff-4, lcms2
-Libs: -L${libdir} -lvips -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4 -lm -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4 -s …
```
> emscripten: prefer to specify options as single arguments

- docs/markdown/IDE-integration.md
I've written a small utility called [`mmeson`](https://github.com/stephanlachnit/mmeson) which is essentially a ccmake clone for Meson projects. I think it fits well in the list.
I also noticed in there was still the old repo to the vscode plugin and fixed it. I also don't think Meson support is still experimental in Eclipse, at least I couldn't find a reference to it being experimental. Meson-UI and Meson Cmake Wrapper are still unmaintained (last commits over two years ago), so maybe it is time to remove them.
> docs: update IDE integrations

- test cases/common/94 threads/meson.build
- test cases/common/94 threads/threadprog.c
Delayed until clang 16, -Werror=incompatible-function-pointer-types is the default. GCC 14 is "likely to do the same".
See https://wiki.gentoo.org/wiki/Modern_C_porting
> tests: fix test that has source code incompatible with modern C

- docs/markdown/Builtin-options.md
- docs/markdown/snippets/license_files_project_info.md
- docs/markdown/snippets/licensesdir_option.md
- docs/yaml/builtins/meson.yaml
- mesonbuild/backend/backends.py
- mesonbuild/build.py
- mesonbuild/coredata.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/mesonmain.py
- mesonbuild/utils/universal.py
- test cases/common/42 subproject/meson.build
- test cases/common/42 subproject/subprojects/sublib/meson.build
- test cases/common/42 subproject/test.json
Hook this up to installed dependency manifests. This is often needed above and beyond just an SPDX string -- e.g. many licenses have custom copyright lines.
> add license_files kwarg to project

- mesonbuild/backend/backends.py
- mesonbuild/compilers/cpp.py
- mesonbuild/coredata.py
- mesonbuild/dependencies/dev.py
- mesonbuild/environment.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/mlog.py
- mesonbuild/modules/gnome.py
- mesonbuild/mparser.py
- mesonbuild/msetup.py
- mesonbuild/utils/universal.py
- mesonbuild/wrap/wrap.py
At least, that's how it started. Then I noticed that I wasn't get completions, and realized that I was lazy when I annotated the mlog module, and used lots of `**kwargs: T.Any`, which is less than ideal. In cleaning tha tup I found some annoying mypy issues, as well as a few actual bugs or shortcomings in the exiting code. Finally we get to adding `fatal=False` in a bunch of places where the end user cannot reasonably be expected to fix the warning (old versions of software, the need to support old versions of meson, etc). I noticed this when there was a suggestion to bump the required c++ version of a wrap to c++14 because of a warning that MSVC doesn't support c++11, and we just set it to c++14 instead.
> Make more uses of `mlog.warning` non-fatal

- docs/markdown/snippets/dep_objects.md
- docs/markdown/snippets/gen_objects.md
- docs/yaml/functions/_build_target_base.yaml
- docs/yaml/functions/declare_dependency.yaml
- docs/yaml/objects/build_tgt.yaml
- mesonbuild/build.py
- mesonbuild/dependencies/base.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/external_project.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/pkgconfig.py
- test cases/common/260 declare_dependency objects/bar.c
- test cases/common/260 declare_dependency objects/foo.c
- test cases/common/260 declare_dependency objects/meson.build
- test cases/common/260 declare_dependency objects/prog.c
- test cases/unit/15 prebuilt object/meson.build
In order to fix the issue documented in https://github.com/mesonbuild/meson/issues/8151#issuecomment-754796420, this pull request adds a new "objects" keyword argument to declare_dependency.
When a dependency is added to a static library and the static library is then used with `link_whole`, duplicate objects can occur at the time of the final link:
```
ar csrDT libbar.a libfoo.a.p/foo.c.o libbar.a.p/bar.c.o
ar csrDT libfoo.a libfoo.a.p/foo.c.o
cc  -o prog prog.p/prog.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,--whole-archive -Wl,--start-group libfoo.a libbar.a -Wl,--end-group -Wl,--no-whole-archive
/usr/bin/ld: libfoo.a.p/foo.c.o: in function `foo':
../foo.c:3: multiple definition of `foo'; libfoo.a.p/foo.c.o:../foo.c:3: first defined here
```
To fix this, it is easiest to bypass the …
> Add `declare_dependency(objects: ...)`

- docs/markdown/snippets/clang_cl_c++20.md
- mesonbuild/compilers/cpp.py
clang-cl now supports `/std:c++20`. I'm not sure exactly when it was added, but given `ClangClCPPCompiler` does no version checking (at least from a cursory comparison with `VisualStudioCPPCompiler`), I guess that's not an issue. Anyway, it's certainly there in current (i.e. clang-cl 15.0.1 from VS 17.4.3).
Obviously preferable to use over `c++latest` as that enables a lot of C++23 stuff...
Here's a quick fix if you want it. Wasn't sure if it warrants a release snippet since it's not really a new feature, but happy to add it.
Thanks
> clang-cl supports /std:c++20 now.

- mesonbuild/backend/ninjabackend.py
It is possible, albeit possibly inadvisable, for the exact combination of MSVC and "$CXX has C++ specific flags in it" to occur. When this happens, and cl.exe is given a filename ending in .c, it complains that you cannot compile a .c file with that option.
Instead, pick the first filename matching that language and use that as the temporary filename. This more or less matches what we do in compiler-time checks. And it's the proper thing to do, rather than assume that cl.exe, when detected as the current C++ compiler, can *also* compile C because it's *also* a C compiler.
Fixes #11257
> msvc: handle filename extensions for incdetect based on the compiler language

- mesonbuild/linkers/linkers.py
This was actually probing bfd without always_args passed.
Fixes: #10763
> linkers: Fix lld detection

- mesonbuild/linkers/detect.py
- mesonbuild/linkers/linkers.py
Adjusted version of https://github.com/mesonbuild/meson/pull/10880.
ld64 is currently detected as LLVMDynamicLinker, causing incompatible arguments to be passed:
```
Detecting linker via: /opt/homebrew/opt/llvm/bin/clang -Wl,--version -fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld
linker returned <Popen: returncode: 0 args: ['/opt/homebrew/opt/llvm/bin/clang', '-Wl,--vers...>
linker stdout:
Homebrew LLD 15.0.6
linker stderr:
```
```
ld64.lld: error: unknown argument '--as-needed'
ld64.lld: error: unknown argument '--no-undefined'
ld64.lld: error: unknown argument '--start-group'
ld64.lld: error: unknown argument '--end-group'
```
This commit detects `ld64` as an `AppleDynamicLinker` as described in [this comment](https://github.com/mesonbuild/meson/pull/10880#issuecomment-1264553781), by …
> linkers: detect ld64 as AppleDynamicLinker

- docs/markdown/Reference-tables.md
I forgot to ask the original author to add this to the original MR (#11243)
> docs: Add ld64.lld to linker reference table

- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/xcodebackend.py
- test cases/common/105 generatorcustom/gen.c
- test cases/common/105 generatorcustom/host.c
- test cases/common/105 generatorcustom/meson.build
- test cases/failing/129 generator host binary/exe.c
- test cases/failing/129 generator host binary/lib.in
- test cases/failing/129 generator host binary/meson.build
- test cases/failing/129 generator host binary/test.json
The code below this already handles being passed an Executable or ExternalProgram, and it does it correctly, since it handles host binaries that need an exe_wrapper correctly, while the code in the generator paths doesn't.
The xcode backend is, like always, problematic, it doesn't handle things the same way as the ninja and vscode backends, and generates a shell script instead of using meson as a wrapper when needed (it seems likely that just forcing the meson path for xcode would be better). I don't have a working mac to develop a fix for, so I've left a todo comment there.
Fixes: #11264
> backends: Stop passing generator exes to ExecutableSerialisation as strings

- cross/armclang-linux.txt
- cross/armclang.txt
- cross/ccomp-armv7a.txt
- cross/iphone.txt
- cross/tvos.txt
- cross/ubuntu-armhf.txt
c_args are meant to be overridden by the user if needed (even via the environment CFLAGS variables + -Doptimization=plain, for example), so they should not contain any option that affect the multilib search path.  For example, a hypothetical native file like this:
```
[binaries]
c = gcc
[built-in options]
c_args = ['-m32']
```
would *not* build 32-bit binaries if -Dc_args is passed to meson. Such options, instead should be in the [binaries] section.  Adjust the sample cross files included with meson.
(That said, I am not sure who is using these cross files and I wonder if it would be better to just delete them).
> cross: move multilib options to [binaries] section

- cross/ubuntu-armhf.txt
Partial revert of commit cf23e341878286790885352fd1d6548be5798391. This mostly moved existing arguments to the "right" location, but also introduced new arguments that didn't previously exist -- which was wrong.
... also, these cross files are used by CI (if they have a corresponding .json file) and this change broke the CI. Because --target isn't a valid gcc option, although clang/rustc do accept it. For GCC, the argument parser decides you wanted --target-help, which prints documentation text and then quits.
/cc @bonzini
> remove totally invalid gcc arguments from cross file

- run_project_tests.py
- properly log the reason why a test got unexpectedly skipped
- track when an entire category is skipped and be quieter
> misc changes to run_project_tests.py

- mesonbuild/backend/ninjabackend.py
- test cases/cython/2 generated sources/includestuff.pyx
- test cases/cython/2 generated sources/meson.build
- test cases/cython/2 generated sources/stuff.pxi.in
- unittests/allplatformstests.py
Generated graph looks correct.
xref #8961.
(Note: This is for the .pyx-> c phase for a target for pandas)
In pandas, we are including the generated .pxi as sources, but I also tested using them as dependencies, and it still works.
I'm not sure how to test this, though.
Ideas could be write test cases and compare against a golden ninja.build file, or running ninja directly against the pyx target to make sure the deps work correctly (not sure how to hook into the build system to invoke ninja directly)
cc @rgommers @eli-schwartz @xclaesse (Sorry for pinging so close to the weekend).
> BUG: Fix generated sources not being included as dependencies in cython transpilation

- mesonbuild/dependencies/pkgconfig.py
- mesonbuild/utils/core.py
- run_mypy.py
EnvironmentVariables was always broken, it used MutableMapping because everyone <3 abstract interfaces, especially when they are broken and don't actually do what you want.
This needs a dict interface, exposing `.copy()`. We either use a dict or os._Environ, and the latter also supports that.
> properly type utils/core.py and add it to mypy

- mesonbuild/mparser.py
And fix a bug where `not in` is in the wrong order.
> mparser: Use a literal for the ComparisonNode

- mesonbuild/coredata.py
- mesonbuild/interpreter/interpreter.py
This is an even more cut down version of https://github.com/mesonbuild/meson/pull/10714, with just one bug fix, and the typed_pos_args conversion included. This is straight-forward enough that It can probably land now
> use typed_pos_args for build target functions

- mesonbuild/dependencies/configtool.py
- mesonbuild/dependencies/misc.py
The latest release of libpcap added argument validation to pcap-config, but still doesn't support --version. The next version of libpcap will support --version.
Add support for config-tool dependencies which expect to break on --version, to fallback to an option that does not error out or print version info, for sanity checking.
> dependencies: fix pcap-config which now errors on --version

- mesonbuild/utils/universal.py
We shouldn't be hardcoding library dirs anyway. And we usually get this from the compiler.
This function has been unused since its users were moved to use the compiler method, in the following commits:
- a1a4f66e6d915c1f6aae2ead02cf5631b10c76f1
- a3856be1d50eaefe32fee5d3347d55d934d15b50
- 08224dafcba1b694fb624553e7d84deb565aae22
> remove dead code

- mesonbuild/mdevenv.py
On Windows, `meson devenv` calls vsenv, but this is useless since env vars are not transfered to the subprocess.
This fixes that by importing env vars from vsenv, and updating the PATH accordingly. 
It allows to call scripts and executables from Visual Studio when activating the devenv shell.
For instance, before this fix, calling `meson devenv msbuild` was working, but calling `meson devenv` then `msbuild` was not.
> devenv should import env vars from vsenv

- mesonbuild/coredata.py
- mesonbuild/modules/pkgconfig.py
- mesonbuild/utils/universal.py
This patch set correct install path used by Haiku operating system (https://www.haiku-os.org/). Currently Haiku use after install Bash scripts to adjust install locations to Haiku native ones, but it is a hack and native Meson support would be preferred.
Background:
Haiku (and its descendent BeOS) use its own file system hierarchy that significantly differs from other UNIX-like systems. There are four install prefixes recognized by system:
1. $HOME/config/non-packaged
2. $HOME/config
3. /boot/system/non-packaged
4. /boot/non-packaged
`/boot` is a mount point of a volume containing currently booted system installation (something like `C:` in Windows, not boot loader data as in Linux). `non-packaged` directories means software not managed by package manager and installed manually (such as …
> Haiku paths support

- mesonbuild/environment.py
This reverts commit 79d7891746a7864a1407d48eac8a753b225ec6c3.
This debug print probably should not have ended up live. Moreover, the function it debugs is, surprisingly, called rather often. Adding I/O to it causes it to begin to noticeably lag, on the scale of adding actual *minutes* to a setup run.
Fixes #11322
> Revert "debug cygwin CI"

- mesonbuild/mtest.py
Partial rollback of commit b7a5c384a1f1ba80c09904e7ef4f5160bdae3345. The rationale was based on a confusing wording of the TAP14 spec, which is under discussion for clarification / amendment.
TAP14 doesn't (shouldn't) really say that missing a version line is potentially an error. Rather, this is the correct way to denote TAP12, which a TAP14 harness may not understand or try to parse. The intention was never to suggest that harnesses "should" take exception to the missing version line on the grounds that one should really add a version line.
So, stop emitting an annoying warning for something that's valid usage. Meson understands TAP12 and that's okay.
However, we do need to keep the part of that commit which set the version to 12 if it was otherwise unspecified. But instead of …
> mtest: do not warn when the TAP stream version is 12

- test cases/failing/111 empty fallback/test.json
This test case checks stdout and demands a `dependency()` lookup fail. The resulting error message can be different depending on whether cmake is installed, or not. For cmake-specific tests we would simply skip the test if cmake is not installed, but here we can just fine-tune the pattern matching we use to determine if the test failed "correctly".
Fixes #11320
> tests: avoid unexpected failure when cmake is not installed

- mesonbuild/modules/gnome.py
Ensuring the order is respected
Without that we get `ninja: fatal: posix_spawn: Argument list too long` generating the girs against gstreamer-full
> gnome: Deduplicate include dirs to generate gir

- mesonbuild/dependencies/data/CMakeListsLLVM.txt
- mesonbuild/dependencies/dev.py
- test cases/frameworks/15 llvm/meson.build
- test cases/frameworks/15 llvm/meson_options.txt
- test cases/frameworks/15 llvm/test.json
This patch allows to link dynamically with LLVM when CMake requested.
For now, only linking with libLLVM.so is supported (not linking to individual libraries).
There are certainly some bugs.
Fixes #10592
> cmake: allow dynamic linking with LLVM

- mesonbuild/ast/introspection.py
- mesonbuild/mlog.py
Because that is what the real interpreter does, too. It logs a failure and carries on.
Bonus: make `mlog.exception()` actually print errors.
> introspect: avoid crashing when add_languages for an optional language fails

- mesonbuild/mesonmain.py
- run_meson_command_tests.py
In commit 4e4f97edb3d475273108b203bc02b04bd6840b06 we added support for runpython to accept `-c 'code to execute'` in addition to just script files. However, doing so would mangle the sys.argv in the executed code -- which assumes, as python itself does, that argv is the stuff after the code to execute. We correctly handled this for script files, but the original addition of -c support pushed this handling into a script-file specific block.
> runpython: make it work for -c as well

- mesonbuild/compilers/mixins/visualstudio.py
- unittests/internaltests.py
With VisualStudio, the `/validate-charset-` option conflicts with `/uft-8` option. This PR prevents a warning when `/validate-charset-` options is present.
> remove /utf-8 option when /validate-charset- is present

- mesonbuild/modules/python.py
The default parameter for python.install_sources(install_tag) is set to "runtime" but should be "python-runtime" according to the existing documentation.
- https://mesonbuild.com/Python-module.html#install_sources
- https://mesonbuild.com/Installing.html#installation-tags
> default install_tag for python.install_sources() should be "python-runtime"

- mesonbuild/mconf.py
When project is configured with -Dauto_features=disabled, meson configure should not print "auto" value but "disabled" instead.
> mconf: Use auto_features value for auto options

- mesonbuild/compilers/mixins/visualstudio.py
Hi,
This is a resurrection of the attempts in PR #10263, to drop `/utf-8` from the `always_args` member of the compiler class, where we drop it when we call the `get_always_args()` method instead.
Please let me know the items that I can further test on.
> Visual Studio: Drop /utf-8 if it is not supported (second shot at PR10263)

- test cases/vala/5 target glib/GLib.Thread.vala
- test cases/vala/5 target glib/retcode.c
```
clang [...] -c valaprog.p/GLib.Thread.c
../test cases/vala/5 target glib/GLib.Thread.vala:17:17: error: incompatible integer to pointer conversion passing 'gint' (aka 'int') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]
g_thread_exit (get_ret_code ());
^~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gthread.h:158:66: note: passing argument to parameter 'retval' here
void            g_thread_exit                   (gpointer        retval);
^
1 error generated.
```
Already tested in the stable branch: 
https://github.com/mesonbuild/meson/actions/runs/4112669496/jobs/7097877168
https://github.com/mesonbuild/meson/actions/runs/4112669496/jobs/7097877356
> test cases/vala: Fix clang error during int to pointer coercion

- mesonbuild/modules/java.py
This was causing a ninja issue where the native headers were always being generated because io.github.hse-project.hse_Hse.h was being expected, but io.github.hse_project.hse_Hse.h was actually generated.
> Replace dashes in Java package names with underscores when generating native headers

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/cython.py
- test cases/cython/2 generated sources/meson.build
- test cases/cython/2 generated sources/simpleinclude.pyx
- test cases/cython/2 generated sources/simplestuff.pxi
- unittests/allplatformstests.py
Cython 0.29.33 is now out, and supports emitting depfiles for incremental rebuild detection. When support is detected, emit this in the compiler rules.
@rgommers @lithomas1 @dnicolodi
Fixes #9049
> Cython depfile support

- mesonbuild/compilers/asm.py
Before version 2.14.01, -MD required an output filename argument, with `-MD outfile` equivalent to later versions' `-MD -MF outfile`. The older syntax is still supported, and is still listed as the preferred syntax in documentation.
Reference: https://github.com/netwide-assembler/nasm/commit/3475462e  
Resolves: https://github.com/mesonbuild/meson/issues/11395
> asm: Use more backward-compatible invocation syntax for nasm

- docs/markdown/snippets/run_script_dry_run.md
- docs/yaml/builtins/meson.yaml
- mesonbuild/interpreter/mesonmain.py
- mesonbuild/minstall.py
- mesonbuild/utils/core.py
- test cases/common/53 install script/meson.build
- test cases/common/53 install script/myinstall.py
- unittests/allplatformstests.py
With complex install scripts, it may be useful to be able to run them when calling `meson install --dry-run`.
This adds a parameter to `meson.add_install_script` to allow running install script in dry-run.
This adds a variable `MESON_INSTALL_DRY_RUN` to notify the install script it is in dry run mode.
> allow install script to run in dry-run mode

- docs/markdown/Shipping-prebuilt-binaries-as-wraps.md
This doc is seriously out of date. Let's add some information on using `meson.override_dependency()`, as well as how to use a .wrap file.
> Update docs on how to use pre-built binaries with wraps

- mesonbuild/compilers/mixins/gnu.py
As per subject. It noisy and I'd rather not set `-Wno-ignored-optimization-argument`:
```
clang++ main.cpp -fprofile-correction
clang-15: warning: optimization flag '-fprofile-correction' is not supported [-Wignored-optimization-argument]
```
From #2159. I'm afraid I don't know if any other GCC frontend compilers have the same issue and whether it's better to change GnuLikeCompiler / GnuCompiler instead.
Thanks
> clang: -fprofile-correction isn't a valid flag.

- mesonbuild/build.py
The current check results in *any* value to `export_dynamic` generating vala import targets, even `false`. This is pretty clearly wrong, as it really wants to treat an unset export_dynamic as false.
> vala: don't build .h, .vala, and .gir if export_dynamic is False

- mesonbuild/utils/posix.py
I encounter the following error on a workstation:
```console
$ meson setup build
File "$HOME/.local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 148, in run
File "$HOME/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 294, in run
app.generate()
File "$HOME/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 184, in generate
with mesonlib.BuildDirLock(self.build_dir):
File "$HOME/.local/lib/python3.6/site-packages/mesonbuild/mesonlib/posix.py", line 32, in __enter__
fcntl.flock(self.lockfile, fcntl.LOCK_EX | fcntl.LOCK_NB)
OSError: [Errno 95] Operation not supported
ERROR: Unhandled python exception
This is a Meson bug and should be reported!
NOTICE: You are using Python 3.6 which is …
```
> fix: handle OSError from fcntl.flock

- azure-pipelines.yml
- mesonbuild/compilers/asm.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/detect.py
- mesonbuild/interpreter/interpreter.py
- test cases/nasm/2 asm language/meson.build
- test cases/nasm/3 nasm only/dummy.asm
- test cases/nasm/3 nasm only/dummy.def
- test cases/nasm/3 nasm only/meson.build
- nasm: Link with windows CRT libs when nasm is used as linker language
- ci: Install NASM on MSVC jobs
- interpreter: Do not ignore all exceptions when adding compiler
Suppressing all exceptions was hidding even syntax errors in compiler
source code. If a compiler cannot be found, a MesonException is raised,
we should only expect that type.
> nasm: Link with windows CRT libs when nasm is used as linker language

- docs/yaml/builtins/meson.yaml
- mesonbuild/interpreter/mesonmain.py
- test cases/unit/110 list build options/meson.build
- test cases/unit/110 list build options/meson_options.txt
- unittests/allplatformstests.py
👋 
This PR proposes adding a method, `meson.build_options()`, that allows meson.build to introspect on the changed options. It works by merely exposing the same set of data that is logged by `MesonApp._generate`.
Fixes #10898
> interpreter/mesonmain: Add build_options method

- docs/markdown/Installing.md
- docs/markdown/snippets/meson_install_drop_privs.md
- docs/markdown/snippets/meson_install_elevate.md
- mesonbuild/minstall.py
- minstall: when elevating to root, don't allow ninja to rerun
- minstall: rework root elevation prompt for extensibility and behavior
- minstall: drop privileges before running rebuild_all
- minstall: check 5 times for an answer to the elevation prompt
- minstall: add a timeout when waiting for user input for elevation
Now:
- `sudo ninja install` still does ninja as root, and messes things up before running the install target, but `sudo meson install` will actually drop privileges to run ninja, which is a very sensible approach and works, and that's ideally the only thing we want to do
- `meson install` won't ever run polkit or anything else, if there's no tty to interact with the user
- `meson install` has stopped automatically running polkit. Instead, it:
- searches for 3 different …
> minstall: handle elevation to root better

- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/misc.py
- mesonbuild/dependencies/python.py
- mesonbuild/modules/python.py
- mesonbuild/scripts/python_info.py
- run_project_tests.py
This moves the python dependency factory out of modules/python.py and into dependencies/python.py. As a result, we get some consistency -- particularly, bugfixes! for the sysconfig resolver for `dependency('python3')`. It's also a lot cleaner, and easier to read modules/.
Finally, fix bad overlinking in the sysconfig dependency.
> Python dependency refactor

- mesonbuild/backend/ninjabackend.py
- test cases/rust/2 sharedlib/meson.build
- test cases/rust/2 sharedlib/stuff.rs
- test cases/rust/2 sharedlib/value.c
- test cases/rust/3 staticlib/meson.build
- test cases/rust/3 staticlib/other.rs
- test cases/rust/3 staticlib/prog.rs
- test cases/rust/3 staticlib/stuff.rs
- test cases/rust/3 staticlib/value.c
- test cases/rust/5 polyglot static/clib.c
- test cases/rust/5 polyglot static/meson.build
- test cases/rust/5 polyglot static/prog.c
- test cases/rust/5 polyglot static/stuff.rs
- test cases/rust/5 polyglot static/test.json
Rustc as of version 1.61.0 has support for controlling when whole-archive linking takes place, previous to this it tried to make a good guess about what you wanted, which worked most of the time. This is now implemented. Additionally, because meson breaks some rustc assumption about library naming on windows, we have to manually pass whole-archive libraries, bypassing rustc's interface and talking directly to the linker for MSVC (and those imitating it), which we were doing incorrectly. This has been fixed.
Fixes: #10723
Fixes: #11247
> implement rustc controlled whole-archive linking

- mesonbuild/modules/python.py
Backports the bug fixes from #11392
But not the deep refactoring that preceded it, which is too risky for backporting.
> Python dependency refactor backport 1.0

- mesonbuild/mcompile.py
When giving full path to a target there is no reason to skip targets from subprojects, the path can start with `subprojects/`.
> mcompile: Do not exclude targets from subprojects

- docs/markdown/Generating-sources.md
- mesonbuild/scripts/python_info.py
- test cases/common/257 generated header dep/meson.build
- test cases/common/44 pkgconfig-gen/meson.build
- test cases/failing/115 run_target in test/meson.build
- test cases/failing/116 run_target in add_install_script/meson.build
- test cases/java/8 codegen custom target/com/mesonbuild/meson.build
- test cases/unit/64 alias target/meson.build
- test cases/unit/70 cross test passed/meson.build
- test cases/unit/71 summary/meson.build
- test cases/unit/71 summary/meson_options.txt
- test cases/unit/73 dep files/meson.build
- test cases/unit/99 custom target name/meson.build
- test cases/windows/13 test argument extra paths/test/meson.build
- unittests/allplatformstests.py
We do not need the python module's find_installation() for this, as this does various things to set up building and installing python modules (pure python and C-API). This functionality is already tested in the python tests.
Elsewhere, when we just need an interpreter capable of running python scripts in order to guarantee a useful scripting language for custom commands, it suffices to use find_program(), which does not run an introspection script or do module imports, and is thus faster and a bit cleaner.
Either way, both methods are guaranteed to find the python3 interpreter, deferring to mesonlib.python_command for that guarantee.
> test cases: use best practices method to find the python3 program

- mesonbuild/dependencies/python.py
- mesonbuild/minstall.py
- mesonbuild/mintro.py
- test cases/unit/98 install all targets/excludes/excluded.txt
- test cases/unit/98 install all targets/excludes/excluded/placeholder.txt
- test cases/unit/98 install all targets/excludes/installed.txt
- test cases/unit/98 install all targets/meson.build
- unittests/allplatformstests.py
These are necessary for projects outside Meson itself that want to extend the 'meson install' functionality as meson-python does to assemble Python package wheels from Meson projects.
Fixes #11426.
> Add exclude_files and exclude_dirs to install_plan introspection data

- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/coredata.py
- mesonbuild/interpreter/compiler.py
cc.sizeof() and cc.alignment() are easily cacheable tests that currently aren't cached, because they internally use Compiler.run(). This series introduces Compiler.cached_run() and then uses it to make .sizeof(), .alignment() cached.
This reduces the re-configure time in postgres from 11.285s to 10.225s (average of three runs). The effect on the time until meson.build processing is done is bigger, the time until "Found ninja" goes from 7.134s to 6.014s. The build.ninja generation could stand some profiling attention...
> Caching sizeof alignment

- mesonbuild/ast/postprocess.py
- mesonbuild/ast/printer.py
Inside of mesonbuild.ast.* we can and should import from .foobar, rather than importing from .__init__'s re-exported version of that object.
Failing to do so results in an extremely brittle codebase where simply changing the order of lines in __init__.py can result in ImportError.
> refactor a few subsystem-relative imports that imported the wrong location

- mesonbuild/backend/backends.py
- unittests/allplatformstests.py
Commit e88887be4a08 ("Only remove substring if it is part of string") removed the source dir from the rpath when the following check succeeds:
```python
if absdir.startswith(self.environment.get_source_dir()):
rel_to_src = absdir[len(self.environment.get_source_dir()) + 1:]
````
For example, absdir '/myproject/foo' starts with source dir '/myproject', so we want to generate the relative path 'foo'.
This code doesn't work with absdir '/myproject-libs/foo' though, because we'll incorrectly turn it into a relative path 'libs/foo' after stripping away '/myproject-'.
Use os.path.commonpath() instead of str.startswith() so path components are correctly handled.
Cc: Niklas Claesson <niklas.claesson@cosylab.com>
Signed-off-by: Stefan Hajnoczi <stefanha@gmail.com>
> backends: fix source dir stripping from rpaths

- mesonbuild/backend/ninjabackend.py
As meson requires source_dir!=build_dir and stores the rust-project.json inside the build directory, while software like rust-analyzer expects it at the root of the source directory, manual steps are needed for making them work together.
One option, as described in the documentation, is per project configuration. Another option, that works correctly with compile-commands.json and clangd, is to store a symlink to the file in the build directory at the root of the source directory.
As currently rust-project.json stores paths relative to the location of the file itself and rust-analyzer does not resolve symlinks, this does not work.
To solve this, store absolute paths in rust-project.json as is already done in compile_commands.json for the directory.
----
rust-analyzer PR to resolve …
> rust: Store absolute paths in rust-project.json

- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreterbase/__init__.py
- mesonbuild/interpreterbase/baseobjects.py
- mesonbuild/interpreterbase/interpreterbase.py
- mesonbuild/mparser.py
- test cases/common/261 testcase clause/meson.build
- test cases/common/261 testcase clause/test.json
- unittests/datatests.py
This is currently only enabled when running unit tests to facilitate writing failing unit tests.
Fixes: #11394
> interpreter: Add testcase..endtestcase clause support

- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreterbase/interpreterbase.py
- mesonbuild/mparser.py
- test cases/common/33 run program/meson.build
- test cases/common/33 run program/test.json
- test cases/failing/130 invalid ast/meson.build
- test cases/failing/130 invalid ast/test.json
- test cases/failing/131 invalid project function/meson.build
- test cases/failing/131 invalid project function/test.json
- test cases/failing/20 version/test.json
- [`handle meson_version even when the build file fails to parse`](https://github.com/eli-schwartz/meson/commit/41280fed96907eeee184dba513f15a80339e796b)
If we add new syntax to meson.build, this syntax can cause old versions of Meson to crash. We currently cannot escape from that by setting a `meson_version: '>=X.Y'` to inform people what version to upgrade to
- [`interpreter: report FeatureNew for kwargs to project()`](https://github.com/eli-schwartz/meson/commit/20745af22e6b7ccbc61c2192d18e464e4d9e1523)
FeatureNew is never triggered except by code running on the second line. This includes stuff like `version: run_command(..., check: true).stdout().strip()`
> respect `meson_version` very early

- docs/markdown/snippets/mintro_outputs.md
- mesonbuild/mintro.py
Disabling logging can hide some problems, like not seeing warnings.
I redirected stdout to stderr instead. This way, logs are still printed, while not interfering with stdout.
> mintro: redirect stdout to stderr

- run_mypy.py
Mainly motivated by the fact that this would allow mypy_primer, a regression testing tool for mypy, to run against the meson codebase.
Also mypy 1.0.0 is out, so we don't need to run against an artificially constrained python version.
> run_mypy cleanups

- mesonbuild/msubprojects.py
- unittests/subprojectscommandtests.py
Untracked files need to be stashed too, or resetting may fail when trying to (re-)apply a patch that adds one of those untracked files.
> msubprojects: fix potential error when resetting a git checkout

- mesonbuild/modules/hotdoc.py
We used to just abort during configure because we ran in-process and hotdoc's argparse would leak into our own process space. Now we fail to handle this case and succeed at configuring, only for building to fail because the hotdoc config file doesn't exist.
> hotdoc module: properly error out when configuring fails

- docs/markdown/Dependencies.md
- docs/markdown/snippets/pybind11_dep.md
- mesonbuild/dependencies/__init__.py
- mesonbuild/dependencies/python.py
This works with pkg-config and cmake without any special support. The custom factory adds further support for config-tool, via `pybind11-config`. This is useful because the config-tool will work out of the box when pybind11 is installed, but the pkg-config and cmake files are shoved into python's site-packages, which is an unfortunate distribution model and makes it impossible to use in an out of the box manner.
It's possible to manually set up the PKG_CONFIG_PATH to detect it anyway, but in case that does not happen, having the config-tool fallback is extremely useful.
Depends on https://github.com/pybind/pybind11/pull/4526 (sort of, the version will be unknown without that PR)
> dependencies: add pybind11 custom factory

- mesonbuild/coredata.py
- mesonbuild/minstall.py
- mesonbuild/utils/universal.py
It's actually Generic, and we should use Generic annotations to get the correct result. This means that we don't have to assert or cast the return type, because mypy just knowns
> utils: fix annotation of pickle_load

- mesonbuild/interpreter/compiler.py
- mesonbuild/interpreterbase/decorators.py
- test cases/common/40 options/test.json
In commit c2a55bfe43fae1b44cf49a083297d6755c89e1cc multiple bugs were fixed, but a FeatureNew was only added for the one that was mentioned in the commit message.
Make sure to warn users about the reliability of the one that wasn't mentioned, too.
> emit FeatureNew warning for compiler.preprocess used multiple times

- mesonbuild/interpreter/interpreter.py
- mesonbuild/utils/universal.py
In commit 97a72a1c53e68cf53541285075b4000f7c85ccc6 we started to allow cmakedefine with 3 tokens, as cmake expects (unlike mesondefine). This would silently start working even if the declared minimum version was older than 0.54.1
> configure_file: emit FeatureNew when a cmake-formatted file has too many tokens

- test cases/common/254 long output/meson.build
This test is intended to test really long output, so it prints 100k lines of stdout/stderr. It completes in two seconds on my machine, but the default 30-second timeout is apparently too much for CI, because on Windows we often get flaky tests due to this. e.g. we'll get within 200 lines of the end.
Bump the CI time by x2. We know this isn't particularly surprising behavior, and allowing it to request another 30 seconds won't hang the CI. But it will save us from some spurious failures and restarted jobs.
> tests: allow a long test to have more time to complete before timing out

- mesonbuild/compilers/detect.py
clang --version can yield a string like below when its installed into
such a directory
clang version 14.0.0 (https://github.com/llvm/llvm-project 3f43d803382d57e3fc010ca19833077d1023e9c9)
Target: aarch64-yoe-linux
Thread model: posix
InstalledDir: /mnt/b/yoe/master/build/tmp/work/cortexa72-yoe-linux/gnome-text-editor/42.0-r0/recipe-sysroot-native/usr/bin/aarch64-yoe-linux
as you can see InstallDir has 'xt-' subtring and this trips the check to
guess gcc
if 'Free Software Foundation' in out or 'xt-' in out:
Therefore, check if compiler is clang then there is no point of running
this check anyway.
Signed-off-by: Khem Raj <raj.khem@gmail.com>
> Check for clang before guessing gcc or lcc

- mesonbuild/compilers/mixins/gnu.py
Moves this warning to start with GCC 9 to avoid issues during the 8 series.  See the commit message for details.
> Fix warning_level=everything with GCC 8

- mesonbuild/build.py
It will allow to distinguish AliasTarget from RunTarget in introspection files (e.g. meson-info/intro-targets.json).
> add typename to AliasTarget

- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/fortran.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/mixins/emscripten.py
- mesonbuild/compilers/vala.py
- mesonbuild/dependencies/pkgconfig.py
- unittests/internaltests.py
Because there is not such implied `lib` prefix for libraries on msvc, and it is sometime a convention (notabily for boost) to prefix static libraries with `lib` prefix. 
This solves warnings when importing packages like boost and grpc from pc files generated using conan.
> Do not warn about lib name starting with lib in pkg-config

- mesonbuild/coredata.py
- mesonbuild/mconf.py
- test cases/unit/108 configure same noop/meson_options.txt
- unittests/allplatformstests.py
This was added in f774609 to only change the access time of the coredata file if the coredata struct actually changed. However, this doesn't work as pickle serializations aren't guaranteed to be stable. Instead, let's manually check if options have changed values and skip the save if they haven't changed.
> Stop using replace_if_different() for coredata pickle file

- mesonbuild/build.py
- mesonbuild/mcompile.py
- mesonbuild/mconf.py
Exclude coredata from build.dat because it gets pickled separately already.
> coredata: Do not pickle it twice

- mesonbuild/msubprojects.py
The argument position is wrong since
https://github.com/mesonbuild/meson/commit/1c631ec8abd34df9971ab03faf22d709f1c54348
> Fix "meson subprojects checkout -b" regression

- mesonbuild/interpreter/type_checking.py
This patch changes 
```
ERROR: Multiple producers for Ninja target "file.c". Please rename your targets.
```
to 
```
meson.build:4:0: ERROR: custom_target: "output" keyword argument contains "file.c" multiple times
```
> Better error message when custom_targets has duplicates in the output kwarg

- mesonbuild/compilers/mixins/clike.py
I'm currently going through the issues in this repo, seeing where I could make myself useful.
This PR fixes #3912
> Small fix on how cc.sizeof (and similar functions) use the 'prefix' kwarg

- docs/markdown/Builtin-options.md
- docs/markdown/snippets/none-backend.md
- mesonbuild/backend/backends.py
- mesonbuild/backend/nonebackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/backend/vs2012backend.py
- mesonbuild/backend/vs2013backend.py
- mesonbuild/backend/vs2015backend.py
- mesonbuild/backend/vs2017backend.py
- mesonbuild/backend/vs2019backend.py
- mesonbuild/backend/vs2022backend.py
- mesonbuild/backend/xcodebackend.py
- mesonbuild/coredata.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/mdist.py
- mesonbuild/minstall.py
- mesonbuild/mtest.py
- run_project_tests.py
- run_tests.py
- test cases/python/7 install path/meson.build
- test cases/python/7 install path/target/meson.build
- unittests/baseplatformtests.py
- unittests/platformagnostictests.py
It can only be used for projects that don't have any rules at all, i.e. they are purely using Meson to:
- configure files
- run (script?) tests
- install files that exist by the end of the setup stage
This can be useful e.g. for Meson itself, a pure python project.
> backends: add a new "null" backend

- mesonbuild/dependencies/ui.py
Following discussion https://github.com/mesonbuild/meson/discussions/11554 highlighting the fact that although MacOS X and Windows have a special implementation to acquire the 'system' GL library, Linux does not (it may not even be shipped with the system).
This pull request provides an option for Linux operating systems to query the C compiler directly for the GL library, and then assigns the returned flags to this dependency, if it is found.
> Add a system method for obtaining GL dependency on Linux OS

- test cases/frameworks/14 doxygen/doc/Doxyfile.in
- test cases/frameworks/14 doxygen/doc/meson.build
- test cases/frameworks/14 doxygen/meson.build
It was totally subproject-unsafe, and setting a super bad example. This is bad, because doxygen is annoying to get right and we occasionally tell people to go use our example test case.
Fixes #11579
> tests: fix critical existence failure of doxygen test

- mesonbuild/backend/backends.py
When running tests on Windows (or for devenv), paths of shared libraries need to be added to the PATH envvar for Windows to be able to find them. Meson is currently using the path of the import lib, which is wrong in many cases.
This fix does two things: if there is a variable bindir in the pkg-config file, those variable values are added to the list of path. This is for conan dependencies, if conan decides to export those paths. See https://github.com/conan-io/conan/issues/13532 .
The fallback is to replace `lib` by `bin` in the import library path. This heuristic will work most of the time (but the bin directory could have a different name, or the dll itself could have a different name). In all cases, it cannot be worse than current implementation, and it solves many cases.
> find dll path on Windows

- docs/markdown/snippets/reconfigure.md
- mesonbuild/msetup.py
This allows to run setup command regardless whether the builddir has been configured or not previously. This is useful for example with scripts that always repeat all options.
meson setup builddir --reconfigure -Dfoo=bar
> Allow --reconfigure and --wipe of empty builddir

- data/syntax-highlighting/vim/ftdetect/meson.vim
- docs/markdown/Adding-new-projects-to-wrapdb.md
- docs/markdown/Build-options.md
- docs/markdown/Configuring-a-build-directory.md
- docs/markdown/Fs-module.md
- docs/markdown/IDE-integration.md
- docs/markdown/Porting-from-autotools.md
- docs/markdown/snippets/meson_options.md
- docs/yaml/functions/dependency.yaml
- docs/yaml/functions/subproject.yaml
- man/meson.1
- mesonbuild/ast/introspection.py
- mesonbuild/backend/xcodebackend.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/mintro.py
- test cases/warning/9 meson.options/meson.build
- test cases/warning/9 meson.options/meson.options
- test cases/warning/9 meson.options/subprojects/no-warn/meson.build
- test cases/warning/9 meson.options/subprojects/no-warn/meson.options
- test cases/warning/9 meson.options/subprojects/no-warn/meson_options.txt
- test cases/warning/9 meson.options/test.json
- unittests/failuretests.py
This provides support for using `meson.options` instead of `meson_options.txt`.
This makes sense for a couple of reasons:
1. text editors (and other tools) expect `.txt` files to be plain text files, not build scripts
2. meson.options is more consist with meson.build
The goal has been to design this in such a way that if a project uses a `meson.options` file with a minimum below 1.1, then meson will warn, but if a `meson_options.txt` exist, and both point to the same file, then the error is reduced to a debug message.
Fixes: #11176
Fixes: #6951
Fixes: #5288
> Add support for storing options in meson.options

- mesonbuild/mesonmain.py
- run_meson_command_tests.py
We embed the route to executing meson in various cases, most especially regen rules in build.ninja. And we take care to ensure that it's a canonicalized path. Although the code has moved around over time, and adapted in ways both bad and good, the root of the matter really comes down to commit 69ca8f5b544f700210d9f18613311bcce3c2e37a which notes the importance of being able to run meson from any location, potentially not on PATH or anything else.
For this reason, we switched from embedding sys.argv[0] to os.path.realpath, a very heavy stick indeed. It turns out that that's not actually a good thing though... simply resolving the absolute path is enough to ensure we can accurately call meson the same way we originally did, and it avoids cases where the original way to call meson is via a …
> do not resolve symlinks when calculating the meson command

- docs/refman/generatormd.py
- docs/refman/templates/object.mustache
The title is used only in the sidebar. There is no need to have "extends" information there. For returned objects the actual name is not meaningful so it's better to use the long name. For builtin objects the name is important because that's the global variable name.
> doc: Use better name for builtin/return object title

- mesonbuild/dependencies/python.py
- test cases/common/117 shared module/meson.build
- test cases/common/147 simd/simd_mmx.c
- test cases/common/148 shared module resolving symbol in executable/prog.c
- test cases/common/245 custom target index source/main.c
- test cases/python/2 extmodule/meson.build
- test cases/rust/12 bindgen/dependencies/meson.build
pyconfig.h defines it in limited cases, but as empty, rather than as "1" which is what command-line defines generally do. Explicitly define it as a compatible definition so the compiler does not log a warning that the value has changed.
Fixes #11592
> python dependency: avoid redefinition warnings for MS_WIN64

- docs/markdown/Builtin-options.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/coredata.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/mcompile.py
- mesonbuild/mdevenv.py
- mesonbuild/mdist.py
- mesonbuild/minit.py
- mesonbuild/minstall.py
- mesonbuild/msetup.py
- mesonbuild/mtest.py
- mesonbuild/utils/universal.py
We need to remember its value when reconfiguring, but the Build object is not reused, only coredata is.
This also makes CLI more consistent by allowing `-Dvsenv=true` syntax.
Fixes: #11309
> Make --vsenv a readonly builtin option

- mesonbuild/msetup.py
- unittests/allplatformstests.py
- unittests/platformagnostictests.py
This fix regression caused by https://github.com/mesonbuild/meson/pull/11431 and also integrate changes from https://github.com/mesonbuild/meson/pull/11590 and https://github.com/mesonbuild/meson/pull/11427.
Fixes #11418
Closes #11427
Closes #11590
> msetup: Allow (re)configure of not empty builddir

- mesonbuild/msubprojects.py
In commit 8da060706c2c34fbea91898509123cb190894f3e we fixed an issue where stashing would ignore untracked files, potentially conflicting with what we reset to.
Unfortunately in the process it broke the functionality entirely, by producing an invalid git command... according to some versions of git. This is actually a git bug, fixed upstream in git 2.37.0 via commit b02fdbc80a41f73ceb6c99e8e27b22285243a335. It causes git itself to re-synthesize the command line for a negation pathspec with a "." rather than "", as that's what is needed to make it match all files other than the negation.
For backwards compatibility to older versions of git, we manually pass the dot pathspec ourselves.
> fix regression that broken git-based wraps with dirty contents

- mesonbuild/backend/backends.py
This reverts my previous commit, and uses a more robust function instead.
There were edge cases that were not covered by my previous attempt.
> Better algo to find DLL paths on Windows 

- mesonbuild/compilers/rust.py
- test cases/rust/16 internal c dependencies/meson.build
Rust doesn't have a concept of dependency compile arguments, i.e. something like headers. Dependencies are linked in and all required metadata is provided by the linker flags.
----
This shows up when using e.g. a pkg-config dependency as dependency of a Rust target. Without this, `-I` and other compile flags are passed to the Rust compiler, which makes no sense.
> rust: Don't pass dependency compile arguments to the compiler

- mesonbuild/backend/ninjabackend.py
Dashes can't be used as identifiers in Rust and cargo is converting dashes in crate names to underscores for the same reason.
----
CC @dcbaker
> rust: Convert dashes in crate names to underscores

- mesonbuild/backend/ninjabackend.py
Both types don't provide any Rust metadata but just a plain C ABI, so treat them as such.
With the two main commits here we make sure that a cdylib doesn't dynamically link to std unless it links to actual Rust shared libraries (`dylib`, not `cdylib`), and that no special Rust handling for them is performed by the compiler.
The third commit is just a trivial cleanup.
The main reason why I looked into this was because I'm creating a cdylib and it should be self-contained, i.e. not depend on the shared version of the Rust standard library. I.e. the same behaviour you'd get with cargo with this crate type.
----
CC @dcbaker
> rust: Treat staticlib/cdylib Rust libraries like static/shared libraries from any other language

- mesonbuild/minstall.py
A user might run `sudo somewrapper` to build and install something with meson, and it is not actually possible to drop privileges and build, since the build directory is also owned by root.
A common case of this is `sudo pip install` for projects using meson-python or other python build-backends that wrap around meson.
Fixes #11662
Fixes #11665
> minstall: do not drop privileges if msetup also ran under sudo

- mesonbuild/build.py
This is the same fix as the one in #10800 for shared libraries but applied to executables instead.
> mbuild: .pdb files are created only when debug symbols are enabled

- mesonbuild/utils/universal.py
- packaging/hook-mesonbuild.py
pyinstaller considers .py files to not be data by default. The entire architecture of pyinstaller is, in fact, different from zipapp or unpacked modules -- because it actually has to use a resource loader with on-disk files *separate* from the module itself. So just because a file gets packaged in the application does not mean it's usable as an importlib.resources compatible resource.
Although we collect data files in general, we need to make sure that .py files are collected from scripts, because we may try to run them standalone from an external process.
Fixes #11689
> fix data collection with pyinstaller

- mesonbuild/modules/pkgconfig.py
- test cases/common/44 pkgconfig-gen/meson.build
If the optional first "mainlib" argument is there, then we infer several values. Otherwise, some of those values fall back to a generic default, and two of them -- name and description -- fall back to being mandatory.
In commit e84f293f672a372d2434d0ce4fa39d3f902b6ce8, we removed validation for description as part of refactoring that never actually validated anything.
> pkgconfig module: fix traceback on invalid missing description

- mesonbuild/backend/ninjabackend.py
They're only used at build-time and whether they exist or not should not have any effect on the final build artifact.
----
CC @dcbaker
> rust: Don't use prefer-dynamic in case of proc-macro Rust dependencies

- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
The library names are directly mapped to filenames by meson while the
crate name gets spaces/dashes replaced by underscores. This works fine
to a certain degree except that rustc expects a certain filename scheme
for rlibs that matches the crate name.
When using such a library as a dependency of a dependency compilation
will fail with a confusing error message.
See https://github.com/rust-lang/rust/issues/110460
----
CC @dcbaker
> rust: Don't allow spaces/dashes in Rust library names

- docs/markdown/Rust-module.md
- docs/markdown/snippets/rustc-ndebug.md
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cuda.py
- mesonbuild/compilers/d.py
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/compilers/rust.py
- mesonbuild/modules/rust.py
- test cases/rust/1 basic/meson.build
- test cases/rust/1 basic/prog.rs
Rust has a `debug_assert!()` macro, which is designed to be toggled on the command line. It is on by default in debug builds, and off by default in release builds, in cargo. This matches what meson's b_ndebug does in `if-release` mode. In addition, this fixes an oversight in the rust module where bindgen wouldn't be passed `-DNDEBUG` when `b_ndebug=false`.
Fixes #11438
> Add support for b_ndebug to rust

- docs/markdown/snippets/rust_dependency_map.md
- docs/yaml/functions/_build_target_base.yaml
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- test cases/rust/17 staticlib link staticlib/branch.rs
- test cases/rust/17 staticlib link staticlib/meson.build
This allows changing the crate name with which a library ends up being available inside the Rust code, similar to cargo's dependency renaming feature or `extern crate foo as bar` inside Rust code.
----
Only the top commit is interesting here, the others are from other PRs but they change related code.
CC @dcbaker who suggested this as a possible solution.
> rust: Add new `rust_dependency_map` target configuration

- mesonbuild/dependencies/python.py
- test cases/python/1 basic/meson.build
`import('python').find_installation('python').version()` causes exception because of a missing initialization
> fix python.version() not working

- cross/metrowerks-arm.txt
- cross/metrowerks-eppc.txt
- cross/metrowerks.lcf
- docs/markdown/Reference-tables.md
- docs/markdown/snippets/add_metrowerks_compiler.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/compilers/c.py
- mesonbuild/compilers/cpp.py
- mesonbuild/compilers/detect.py
- mesonbuild/compilers/mixins/metrowerks.py
- mesonbuild/linkers/__init__.py
- mesonbuild/linkers/linkers.py
- run_project_tests.py
Hello meson devs!
I added preliminary support for the Metrowerks C/C++ compiler(s). Metrowerks is a company with a focus on providing toolchains targeting embedded systems. It was acquired in 2005 by Freescale Semiconductors, which itself was acquired by NXP Semiconductors in 2015. However, the tools are still named after Metrowerks (they are prefixed with 'mw'), so I believe Meson should do the same.
While all Metrowerks compilers share a common CLI, I decided to focus on the Embedded ARM and PowerPC toolchains for the time being. They contain a C/C++ compiler, a standalone assembler, and a linker that acts both as a static and dynamic linker. The linker is compatible with GNU AR archives, but does not support thin archives.
I suppose this isn't perfect on first try (plus I don't usually …
> Add support for Metrowerks C/C++ compilers

- docs/markdown/Dependencies.md
- mesonbuild/dependencies/ui.py
- test cases/frameworks/16 sdl2/meson_options.txt
- test cases/frameworks/16 sdl2/test.json
> dependencies: allow to fallback on CMake to find the SDL2 library

- .github/workflows/cygwin.yml
- .github/workflows/macos.yml
- .github/workflows/msys2.yml
- .github/workflows/nonnative.yml
- .github/workflows/os_comp.yml
- .github/workflows/unusedargs_missingreturn.yml
- test cases/frameworks/15 llvm/meson.build
See: https://github.com/mesonbuild/meson/issues/11642
The idea is to keep bumping this version as new LLVM versions are released till this is fixed. That way we won't just forget to re-enable the test once the issue is fixed.
> ci: Don't search for llvm modules with LLVM 16.0.x

- mesonbuild/mtest.py
Replace illegal characters when reading gtest generated xml file, to prevent a ParseError and a stacktrace.
catch et.ParseError, just in case, to prevent stopping other tests if the xml file was malformed.
> mtest: prevent parse error with gtest protocol

- mesonbuild/scripts/coverage.py
Currently, when trying to generate an html coverage report when using clang as a compiler and gcovr for the coverage generation on linux, gcov errors out.
This can be easily reproduced by running this when having gcovr installed:
```bash
mkdir test_proj && cd test_proj
meson init -n test_proj -l cpp
CC=clang CXX=clang++ meson build -Db_coverage=true
ninja -C build test
ninja -C build coverage
```
This PR fixes this by also providing the `gcov_exe_args` (which hold the flags to use `llvm-cov-<version> gcov` as the executable) to the coverage producing command, just like in the other calls to generate xml, sonarqube and text output.
I believe this was forgotten in #7196
> fix: fixes html coverage report generation when using clang on linux

- docs/markdown/Gnome-module.md
- docs/markdown/snippets/generate_gir_kwarg_env.md
- mesonbuild/modules/gnome.py
- mesonbuild/utils/core.py
- test cases/frameworks/7 gnome/gir/dep1/dep1.h
- test cases/frameworks/7 gnome/gir/dep1/dep2/dep2.h
- test cases/frameworks/7 gnome/gir/dep1/dep3/dep3.h
- test cases/frameworks/7 gnome/gir/meson-sample.h
- test cases/frameworks/7 gnome/gir/meson-sample2.h
- test cases/frameworks/7 gnome/gir/meson.build
- test cases/frameworks/7 gnome/meson.build
My mission to clean the issue tracker continues, I hope this is welcome.
This time I fixed two 6 year old issues:
Fixes #384
Fixes #1035
Without my patch, `test cases/frameworks/11 gir subproject` fails if gcc is not installed (even if e.g. clang is installed):
```
$ ninja
[7/12] Generating subprojects/mesongir/Meson-1.0.gir with a custom command (wrapped by meson to set env)
FAILED: subprojects/mesongir/Meson-1.0.gir 
env 'PKG_CONFIG_PATH=/home/volker/Sync/git/meson/test cases/frameworks/11 gir subproject/build/meson-uninstalled' /usr/bin/g-ir-scanner --quiet --no-libtool --namespace=Meson --nsversion=1.0 --warn-all --output subprojects/mesongir/Meson-1.0.gir '-I/home/volker/Sync/git/meson/test cases/frameworks/11 gir subproject/subprojects/mesongir' '-I/home/volker/Sync/git/meson/test …
```
> g-ir-scanner environmental variables

- test cases/common/178 bothlibraries/meson.build
Test case `common/178 bothlibraries` fails on MacOS Catalina (which has Apple clang 12) because the C++ part uses C++11 features without specifying a `-std=`flag, and the default for that compiler is not C++11. I know that most or all modern systems out there will not need this flag, but it does not do any harm and there may be some older or less well-known compiler versions which need it.
```
% meson compile -C builddir
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/local/bin/ninja -C '/Projects/meson/test cases/common/178 bothlibraries/builddir'
ninja: Entering directory `/Projects/meson/test cases/common/178 bothlibraries/builddir'
[25/28] Compiling C++ object libccpp.dylib.p/foo.cpp.o
FAILED: libccpp.dylib.p/foo.cpp.o 
c++ -Ilibccpp.dylib.p -I. …
```
> Fix failing test common/178 on older macos

- mesonbuild/environment.py
- unittests/internaltests.py
MIPS64 can run MIPS32 code natively, so there is a chance that a mixture of MIPS64 kernel and MIPS32 userland exists. Before this Meson just treats such mixture as mips64, because `uname -m` returns mips64.
So in this case we have to check compiler builtin defines for actual architecture and CPU in use.
Fixes #11671.
> environment.py: detect_cpu: Fix mips32 detection on mips64

- mesonbuild/wrap/wrap.py
`patch` on Windows is provided by MSYS, which only understands POSIX paths, with `/`. Using Windows paths with `\` results in a "file not found" error.
We got a little lucky here because the path is relative, so the drive letter difference doesn't affect us.
> wrap: Always pass posix paths to patch

- .github/workflows/website.yml
In this case, we have the secret available, and the workflow ran even though it wasn't on branch "master" because of the pull request trigger.
Since the change hasn't landed on master, though, we do not want to update the website. So check for pushes to master, specifically.
> avoid re-uploading the docs when a PR is based on the upstream repo

- docs/markdown/Python-module.md
- docs/markdown/snippets/python-find-version.md
- mesonbuild/modules/python.py
- Fixes the fallback for `python2` when python2 is not installed (Fixes #11057)
- Allow to find `python3.xx`, or any version allowed by `py.exe` launcher.
- Better logging when python is not found (Fixes #11686)
> Better pymod.find_installation() on Windows

- mesonbuild/modules/cmake.py
fixes https://github.com/NixOS/nixpkgs/issues/229358
restores the pre caching behavior (https://github.com/mesonbuild/meson/commit/808d5934dd6c6a6c16f66e9dc51dae6e83e02cef)
> fix regression in precomputing CMAKE_SIZEOF_VOID_P

- docs/markdown/Builtin-options.md
- docs/markdown/snippets/python_bytecompile.md
- mesonbuild/backend/backends.py
- mesonbuild/coredata.py
- mesonbuild/minstall.py
- mesonbuild/modules/__init__.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/python.py
- mesonbuild/msetup.py
- mesonbuild/scripts/pycompile.py
- mesonbuild/utils/core.py
- test cases/common/252 install data structured/meson.build
- test cases/python/2 extmodule/blaster.py.in
- test cases/python/2 extmodule/ext/meson.build
- test cases/python/2 extmodule/ext/nested/meson.build
- test cases/python/2 extmodule/ext/tachyon_module.c
- test cases/python/2 extmodule/ext/wrongdir/meson.build
- test cases/python/2 extmodule/meson.build
- test cases/python/2 extmodule/meson_options.txt
- test cases/python/2 extmodule/subinst/printer.py
- test cases/python/2 extmodule/subinst/submod/printer.py
- test cases/python/2 extmodule/test.json
- test cases/python/7 install path/meson.build
- unittests/baseplatformtests.py
- unittests/helpers.py
- unittests/pythontests.py
For all source `*.py` files installed via either py.install_sources() or an `install_dir: py.get_install_dir()`, produce `*.pyc` files at install time. Controllable via a module option.
> python module: add an automatic byte-compilation step

- unittests/allplatformstests.py
Handle the case where `sccache` is installed and used over `ccache`.
> tests: fix `test_always_prefer_c_compiler_for_asm`

- mesonbuild/dependencies/configtool.py
- mesonbuild/dependencies/python.py
If the dependency permits it, we can just do a PATH search instead of mandating that it be listed in the cross file. This is useful for the limited case where a specific dependency is known to be compatible with any machine choice.
Mark the pybind11 dependency as supporting this. It's a valid choice because pybind11 is a header-only C++ library.
See https://github.com/contourpy/contourpy/pull/226#issuecomment-1533685324
/cc @ianthomas23
> dependencies: allow config-tool to fallback to default program names

- ci/run.ps1
- mesonbuild/dependencies/python.py
- test cases/cython/1 basic/meson.build
- test cases/cython/2 generated sources/meson.build
- test cases/cython/3 cython_args/meson.build
- test cases/python/3 cython/libdir/meson.build
- test cases/python/3 cython/meson.build
- unittests/allplatformstests.py
In gh-10775 an issue with building a simple Cython extension with MSVC on Windows was reported. Right now the Cython tests are skipped on Azure - from [example CI log](https://dev.azure.com/jussi0947/jussi/_build/results?buildId=15089&view=logs&jobId=5015ea34-1c35-577b-b206-c8bea8465a58&j=5015ea34-1c35-577b-b206-c8bea8465a58&t=d96bae21-2af5-55ef-6693-add22ffd7f07):
```
Not running cython tests.
[SKIPPED]   cython: 1 basic    (cython_language=c)
Reason: not run because preconditions were not met
[SKIPPED]   cython: 1 basic    (cython_language=cpp)
Reason: not run because preconditions were not met
[SKIPPED]   cython: 2 generated sources
Reason: not run because preconditions were not met
[SKIPPED]   cython: 3 cython_args
Reason: not run because preconditions were not met
```
[skip actions]
> Add Cython to Windows CI jobs on Azure

- docs/README.md
- docs/meson.build
- docs/meson_options.txt
- add meson option to control use of "fastyaml" loader by @annacrombie 
- add meson option to skip building HTML documentation and "just" build the man page
- check for required python modules at setup time. Closes #11772
> docs: build rework

- mesonbuild/backend/ninjabackend.py
- test cases/fortran/22 extract_objects/meson.build
Fixes #11047
This commit message I found seems relevant:
```
commit 8bee336e2a9bf0033d2fa852a48d6d17ce2a8869 (HEAD)
Author: Nirbheek Chauhan <nirbheek@centricular.com>
Date:   Fri Oct 21 07:23:15 2016 +0530
ninja: Always use RawFilename for unity sources and deps
The use of has_dir_part is a terrible back that we need to move away
from. This will eventually be fixed by always using File() objects
everywhere. For now, this is needed for unity builds to work.
```
> Fix paths of Fortran order dependencies

- mesonbuild/ast/introspection.py
- mesonbuild/compilers/detect.py
- mesonbuild/coredata.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/java.py
- unittests/allplatformstests.py
Let's say you have the following meson.build file:
```meson
project('demo', 'c')
add_languages('objc', required: false)
```
and a machine with no objc compiler. Without my patch, meson does this:
```
$ /old/meson.py setup build
Version: 1.1.99
Source dir: /home/volker/Documents/mesoncases/9431/many
Build dir: /home/volker/Documents/mesoncases/9431/many/build
Project name: demo
Project version: undefined
C compiler for the host machine: cc (gcc 12.2.1 "cc (GCC) 12.2.1 20230201")
C linker for the host machine: cc ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for language objc for the build machine not found.
Compiler for language objc for the host machine not found.
Build targets in project: 0
Found ninja-1.11.1 …
```
> Sanity Check Reconfigure Fix

- mesonbuild/dependencies/cmake.py
- mesonbuild/dependencies/data/CMakeLists.txt
- test cases/rust/13 external c dependencies/test.json
Fixes #1709
Why did I remove the `{ "static": true, "method": "cmake" }` testcase?
Before my PR, it actually linked dynamically, so it never *really* worked. Now it fails for the same reason that `{ "static": true, "method": "pkg-config" }` fails.
> Make `dependency('foo', static: true, method: 'cmake') link statically

- mesonbuild/backend/ninjabackend.py
Currently, include args for precompiled headers are placed in front of all other compiler args, as this is needed by gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100462
However, Metrowerks compilers need these include args to come last, or else intraprocedural analysis breaks. This PR adds logic in ninjabackend.py to handle the Metrowerks case, while keeping the status quo for all other compilers.
> Metrowerks: move PCH args to the end of the command line

- mesonbuild/dependencies/dub.py
- test cases/d/11 dub/meson.build
- test cases/d/14 dub with deps/meson.build
Dub versions starting at 1.32 have a new cache directory structure into which Meson doesn't know where to find compatible artifacts.
This PR informs the user of why the dependency can't be found.
```
Found DUB: /home/remi/dlang/dmd-2.103.1/linux/bin64/dub (version 1.32.1)
Run-time dependency vibe-d:http found: NO 
meson.build:35:21: ERROR: Dependency lookup for vibe-d:http with method '' failed: DUB version 1.32.1 is not compatible with Meson (can't locate artifacts in Dub cache)
```
#11773
> Check dub version

- mesonbuild/wrap/wrap.py
It is a common mistake that is hard to find because Meson silently
ignore unknown sections. Better have an explicit error message.
> wrap: Check for common "provides" typo

- mesonbuild/mintro.py
- unittests/allplatformstests.py
This is a follow-up on #11627 .
- add `extra_paths` to intro-tests.json to know paths needed to run a test on Windows;
- add `depends` to alias targets in intro-targets.json to know what targets does an alias point to;
- add `depends` to intro-dependencies.json to know libraries linked with an internal dependency;
- renamed `deps` to `dependencies` in `intro-dependencies.json` for more uniformity.
> intro: add more details to generated files(part 2)

- mesonbuild/modules/i18n.py
- A POSIX-style msgfmt may only accept POSIX-style arguments, be compatible there. This is especially interesting since the next edition of POSIX defines msgfmt, but at least the Solaris native msgfmt triggers this meson bug anyway.
- merge_file is a GNU-specific concept workflow, so require GNU gettext. This fails on Solaris before and after the patch, but the patch makes it a configure time error telling you what software to install, instead of a build time "invalid argument".
/cc @alanc 
/cc @awilfox @q66 this should work fine with gettext-tiny based on my limited local testing -- gettext-tiny shims this out and sets wildly big version numbers to make sure it matches any conceivable version check. I can't grep for `--xml` or `--desktop` in the help text, apparently.
Partial fix for …
> handle more gettext variants

- docs/yaml/objects/feature.yaml
- mesonbuild/dependencies/qt.py
- mesonbuild/programs.py
- test cases/frameworks/15 llvm/meson.build
- test cases/frameworks/4 qt/meson.build
Currently you can only use one of qt4, qt5, qt6 in a single project when using a machine file because the config-tool lookup for qt only looks at `qmake` in the machine files, instead of looking up the binary names directly.
Allow specifying `qmake` `qmake4` `qmake5` and `qmake6`.
This is necessary for gstreamer, which can build separate qt5 and qt6 plugins that are distributed as static libraries, so the user can pick which one to use.
> qt: Allow specifying separate tools for qt4/5/6

- mesonbuild/interpreter/interpreterobjects.py
This has never been undocumented and there's no obvious value to having it or using it. We're not even sure anyone ever has used it.
Closes #6061
> deprecate the buildtarget.get_id() method

- docs/markdown/Gnome-module.md
It is not very clear from the documentation that the dependencies in the resource file are added as default dependencies to the target.
I've seen this at least in evince and gnome-control-center, and fixed it there. Just a justification that it might not have been very clear for some other people apart from me.
> docs: gnome: mention that compile_resources adds dependencies by default

- azure-pipelines.yml
I would like to use the same pattern rule as github actions uses:
'[0-9]+.[0-9]+'
But azure pipelines doesn't document what the syntax here is, and it scares me that perhaps the reason we didn't already do this is because it doesn't work at all.
> azure pipelines: fix branch patterns to support 1.x release branches

- docs/yaml/functions/configure_file.yaml
- docs/yaml/functions/custom_target.yaml
- docs/yaml/functions/install_data.yaml
- docs/yaml/functions/install_emptydir.yaml
- docs/yaml/functions/install_headers.yaml
- docs/yaml/functions/install_man.yaml
- docs/yaml/functions/install_subdir.yaml
- mesonbuild/coredata.py
- mesonbuild/interpreter/type_checking.py
We silently dropped all integer values to install_mode since the original implementation of doing this in KwargInfo, in commit 596c8d4af50d0e5a25ee0ee1e177e46b6c7ad22e.
This happened because install_mode is supposed to convert False (exactly) to None, and otherwise pass all arguments in place. But a generator is homogeneous and attempting to do this correctly produced a mypy error that FileMode arguments were allowed to be ints -- well of course they are -- so that resulted in the convertor... treating ints like False instead, to make mypy happy.
Fixes #11538
> repair install_mode support for uid/gid effectively everywhere

- mesonbuild/msubprojects.py
- mesonbuild/utils/universal.py
- mesonbuild/wrap/wrap.py
- Do not hardcode terminal width of 100 chars, that breaks rendering on smaller terminal. It already uses current console width by default.
- Disable progress bar when downloading from msubprojects because it fetches multiple wraps in parallel.
- Do not display rate when it's not a download.
- Do not display time remaining/elapsed to simplify the rendering.
> ProgressBar: Fix some rendering issues

- docs/markdown/Commands.md
- docs/markdown/Unit-tests.md
- docs/markdown/snippets/test_name_filters.md
- mesonbuild/mtest.py
- unittests/allplatformstests.py
Allow the use of wildcards (e.g. *) to match test names in `meson test`.
Raise an error is given test name does not match any test.
Optimize the search by looping through the list of tests only once.
> mtest: wildcard selection

- test cases/failing/78 framework dependency with version/meson.build
- test cases/objc/2 nsstring/meson.build
- test cases/osx/6 multiframework/meson.build
This issue was encounetered while working on a contribution to nixpkgs. Nix allows the store to be installed on a separate, case-sensitive APFS volume. When the store is on a case-sensitive volume, these tests fail because they try to use `foundation` instead of `Foundation`.
> Fix test failures on Darwin on a case-sensitive fs

- ci/ciimage/common.sh
- test cases/java/3 args/meson.build
In this case, PEP 668 was created to allow a thing that Debian wanted, which is for `pip install foobar` to not break the system python. This despite the fact that the system python is fine, unless you use sudo pip which is discouraged for separate reasons, and it is in fact quite natural to install additional packages to the user site-packages.
It isn't even the job of the operating system to decide whether the user site-packages is broken, whether the operating system gets the answer correct or not -- it is the job of the operating system to decide whether the operating system is broken, and that can be solved by e.g. enforcing a shebang policy for distribution-packaged software, which distros like Fedora do, and mandating not only that python shebangs do not contain `/usr/bin/env`, but …
> ciimage: fix pathological brokenness in Debian packaging of python

- mesonbuild/backend/ninjabackend.py
ninja's configured command for regenerating a build directory on any action that *requires* reconfiguring, specifies the source and build directories as they were known during initial project generation. This means that if the build directory is no longer the *same* build directory, we will regenerate... the original location, rather than the location we want.
After that, ninja notices that build.ninja is still out of date, so it goes and reconfigures again. And again. And again.
This is probably broken intentions, but endless reconfigure loops are a kind of evil beyond all evils. There are no valid options here whatsoever other than:
- doing what the user actually meant
- spawning a clear error message describing why meson refuses to work, then exiting with a fatal error
But it turns out …
> avoid endless reconfigure loops when a build directory is copied around

- mesonbuild/coredata.py
- mesonbuild/interpreter/dependencyfallbacks.py
We actually do not and should not care about wrap-mode at all for this. We want to cache dependency lookups whenever humanly possible, but only use them in cases where we would anyways be using them -- which in particular means if we said to force a subproject fallback for this dep, we want to bypass the cache.
Currently, we handle this by always looking up the cache for all dependencies, but clearing the cache at startup if a reconfigure means we are changing our resolution strategy. This is bad -- we might have many dependencies that are worth caching, and only one dependency that should stop being cached and use a subproject instead.
The simple solution is to handle the forcefallback case when doing a cache lookup, and not do a cache lookup at all. Now we don't have to nuke the entire …
> avoid clearing the dependency cache unnecessarily based on wrap-mode

- docs/refman/generatorprint.py
- mesonbuild/compilers/c.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/mconf.py
- mesonbuild/mlog.py
- mesonbuild/modules/external_project.py
- unittests/baseplatformtests.py
- unittests/internaltests.py
mlog uses a lot of global state, which it needs to mutate. This leaves a lot to be desired, especially since we provide some getter/setters for this state, and some we just poke at directly. We really don't want to be poking directly, and some of the methods we have are actually less than ideal: setup/teardown pairs that could be replaced by context managers 100% of the time, for example.
The main patch, the first one, uses a private class to track the state, and exposes it's methods as module constants. This allows the API between the global variables version and the class version to remain unchanged (with a few small improvements). Then I've cleaned up some typing stuff.
> Get rid of global usage in mlog module

- mesonbuild/utils/universal.py
This fallbacks to short commit id in case the git repository does not contain any annotated tag, for example before the first release of a project.
> vcs_tag: Add --always to git describe

- mesonbuild/build.py
- mesonbuild/compilers/rust.py
rustc enables PIC by default and Meson currently has no way to force
disabling PIC, it can only force enable or use compiler's default.
> rust: PIC is always enabled

- mesonbuild/dependencies/qt.py
e.g. QtQml with Qt 6.4.0 referencing QtQmlIntegration is one such example
> dependencies/qt: add support for Qt frameworks referencing includes include directory

- mesonbuild/cargo/builder.py
- mesonbuild/cargo/cfg.py
- mesonbuild/cargo/interpreter.py
- mesonbuild/cargo/manifest.py
- mesonbuild/cargo/version.py
- run_mypy.py
- run_unittests.py
- unittests/cargotests.py
This is still *very* WIP, but I wanted to be able to track the status of it publically, since I'm trying to get this ready to solve real issues in Mesa, ASAP.
This is the second attempt at cargo-as-a-subproject. It differs from the previous attempt in a couple of major ways:
- uses `tomli` instead of `toml`. `tomli` is on track to be in the standard library of python 3.11, so it will only be an external dependency for older versions of python
- uses a different AST builder approach
- uses a bewtter cfg parser
- is structured better, due to me understanding the problem better
TODO:
> Cargo subprojects, take two

- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/dev.py
- mesonbuild/environment.py
- mesonbuild/linkers/linkers.py
Fixes an issue with rust.bindgen if a cmake LLVM dependency with the
system include_type is getting used as a dependency.
Needed for https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21612
> dependencies/llvm: strip default include dirs 

- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/detect.py
- mesonbuild/dependencies/configtool.py
- mesonbuild/dependencies/pkgconfig.py
- mesonbuild/linkers/detect.py
- mesonbuild/utils/universal.py
- unittests/baseplatformtests.py
The version output scraping for identifying strings checked for "IFORT" in parentheses after the executable name, which is probably a mistake by Intel. Current versions of ifx have "IFX" in parentheses there.
Detect both.
Fixes #11873
> compilers: fix detection of ifx compiler

- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/primitives/integer.py
- mesonbuild/interpreterbase/__init__.py
- mesonbuild/interpreterbase/decorators.py
This lets us unconditionally warn about problematic code constructs in the event that it is so wrong we don't want people to use it in *any* version of meson.
Update some existing FeatureDeprecated to this.
Also implement a new check. In meson:
- `true == 1` is a fatal error: ```The `==` operator of bool does not accept objects of type int```.
- likewise, `true >= 1` is a fatal error: ```Object <[BooleanHolder] holds [bool]: True> of type bool does not support the `<=` operator.```
- likewise, `true + 1` is a fatal error: ```Object <[BooleanHolder] holds [bool]: True> of type bool does not support the `+` operator.```
Due to internal implementation details of python, the reverse was valid:
- `1 == true` was a truthy statement.
- `1 >= true` was also a truthy statement
- `1 + true` had a …
> Add new Featurebroken check, and check for non-commutative equality operator

- mesonbuild/interpreter/interpreter.py
> Interpreter: Using executable in run_command/configure_file is not a bug

- mesonbuild/modules/windows.py
Clang, clang-cl, and MSVC all rely on RC.EXE to build resource files.
Fixes #11845
> windows: Fix windres detection for Microsoft shipped Clang

- mesonbuild/compilers/detect.py
RUST_LD was deprecated in Meson 0.54 in favor of RUSTC_LD.
> compilers: don't recommend deprecated env var

- docs/markdown/snippets/add_str_splitlines_method.md
- docs/yaml/elementary/str.yml
- mesonbuild/interpreter/primitives/string.py
- test cases/common/35 string operations/meson.build
The new ~parse_as_list~ splitlines method on str is intended to replace usage of fs.read('whatever').strip().split('\n').
The problem with the .strip().split() approach is that it doesn't have a way to represent empty lists (an empty string becomes a list with one empty string, not an empty list), and it doesn't handle Windows-style line endings.
> Add str.splitlines method

- docs/markdown/snippets/option_dict.md
- docs/yaml/elementary/dict.yml
- docs/yaml/functions/_build_target_base.yaml
- docs/yaml/functions/dependency.yaml
- docs/yaml/functions/project.yaml
- docs/yaml/functions/subproject.yaml
- mesonbuild/interpreter/dependencyfallbacks.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/modules/cmake.py
- test cases/common/264 default_options dict/lib.c
- test cases/common/264 default_options dict/meson.build
- test cases/common/264 default_options dict/meson_options.txt
This takes https://github.com/mesonbuild/meson/pull/11493 but excluding the part where we deprecate `c_args` and friends. In addition it add support for setting other types than string options in the dictionary.
> Allow default_options and override_options as dictionaries

- docs/yaml/objects/env.yaml
The object is not used only for tests, but also for `custom_target` etc.
> Clarify `environment` docs.

- docs/markdown/Rust.md
- mesonbuild/backend/ninjabackend.py
- test cases/rust/18 proc-macro/meson.build
<details>
<summary>Original description</summary>
I noticed when building a project that uses a proc macro that Meson passed `-C prefer-dynamic` for the executable, and not the proc macro, while cargo passed `-C prefer-dynamic` for the proc macro, but not for the executable.  Meson's behavior broke setting `-C panic=abort` on the executable.
The change here is to try to match Cargo's behavior for `prefer-dynamic` as closely as possible.  The relevant code in Cargo is this:
```rust
let prefer_dynamic = (unit.target.for_host() && !unit.target.is_custom_build())
|| (contains_dy_lib && !cx.is_primary_package(unit));
```
`for_host()` means either a proc macro, plugin, or build script, and then `is_custom_build()` also means build script.  `contains_dy_lib` just means whether `--crate-type …
> rust: fix prefer-dynamic behavior

- mesonbuild/coredata.py
> coredata: Malformed machine file is not a Meson bug

- docs/yaml/functions/_build_target_base.yaml
Opening the meson directory in visual studio generates a '.vs' dir for various visual studio things that shouldn't be tracked as git changes, so have added '.vs' to '.gitignore'.
Also, since I wasted a bit of time struggling to figure out how certain missing function exports in a .dll were disappearing and how best to ensure they're preserved, and eventually trying 'link_whole', I thought the description could be improved to explicitly add that 'link_whole' uses the MSVC linker option '/WHOLEARCHIVE', which propagates/re-exports exported  symbols from all objects of a static lib.
> Better 'link_whole' description and add '.vs' to '.gitignore'

- mesonbuild/interpreter/interpreter.py
The [python docs](https://docs.python.org/3/library/os.html#os.scandir) say `os.scandir` returns an object that must be closed. Using a context manager ensures that. It's been possible to use `os.scandir` as a context manager since Python 3.6. `contextlib.nullcontext` has been available since Python 3.7.
I noticed this running meson under a debug python build, which makes `ResourceWarning` visible by default. It may make sense to set up a CI job that removes `ResourceWarning` from the default warning ignore list.
> interpreter: ensure os.scandir is closed by using as a context manager

- mesonbuild/backend/ninjabackend.py
- mesonbuild/compilers/compilers.py
- mesonbuild/envconfig.py
- mesonbuild/linkers/linkers.py
- mesonbuild/minstall.py
This PR is to fix the issue discussed in https://github.com/mesonbuild/meson/issues/10532
This code change to ensure we archive shared libraries in AIX.
The things we do are:
Archive shared library
Install archived shared library
Build all must build the archived shared library
blibpath must have the archived shared library dependency.
> Archive shared library in AIX

- docs/markdown/Machine-files.md
- docs/markdown/Rust-module.md
- docs/markdown/snippets/rust_bindegen_extra_args.md
- docs/markdown/snippets/rust_extra_clang_bindgen_arguments.md
- docs/markdown/snippets/rust_test_link_with.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/envconfig.py
- mesonbuild/modules/rust.py
- test cases/rust/20 rust and cpp/lib.cpp
- test cases/rust/20 rust and cpp/lib.hpp
- test cases/rust/20 rust and cpp/main.rs
- test cases/rust/20 rust and cpp/meson.build
- test cases/rust/20 rust and cpp/test.json
- test cases/rust/9 unit tests/helper.rs
- test cases/rust/9 unit tests/meson.build
- test cases/rust/9 unit tests/test3.rs
- unittests/machinefiletests.py
These are issues that Mesa has run into with Rust in Meson. This is still a draft because docs and tests are missing, but I wanted to put this is up because it's really important for mesa to land these for 1.2.0, so I wanted to get it on the milestone and on the radar
> Rust module enhancements for mesa

- docs/markdown/Reference-tables.md
- mesonbuild/environment.py
While both kernels are derived from the OpenSolaris project of Sun, they have diverged and code that works with one may not work with the other. As such, we should provide different values for them. This was requested by both Oracle and the illumos upstreams.
Fixes: #11922
> environment: separate illumos and Solaris kernels in Machines

- mesonbuild/compilers/cpp.py
Because it does matter in some cases, namely when we use rustc to link C++ code.
Fixes: #11921
> Do a better job of detecting libc++ vs libstdc++

- mesonbuild/compilers/mixins/clike.py
- test cases/common/132 get define/test.json
Fixes get_define() for MSVC. cl (tested with 19.36.32535) seems to always add trailing space character when substituting, even if macro is not defined. Since they cannot contain spaces it is safe to simply strip parsed value.
Also I'm certain is was working correctly not so long ago, so it might be a change in recent MSVC that triggered this.
Fixes #10179
Closes #10182
> compilers: strip get_define output

- mesonbuild/ast/introspection.py
- mesonbuild/backend/backends.py
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/compilers/mixins/visualstudio.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/rust.py
- test cases/rust/5 polyglot static/meson.build
- test cases/rust/5 polyglot static/test.json
- test cases/unit/113 complex link cases/main.c
- test cases/unit/113 complex link cases/meson.build
- test cases/unit/113 complex link cases/s1.c
- test cases/unit/113 complex link cases/s2.c
- test cases/unit/113 complex link cases/s3.c
- unittests/allplatformstests.py
- unittests/linuxliketests.py
Case 1:
- Prog links to static lib A
- A link_whole to static lib B
- B link to static lib C
- Prog dependencies should be A and C but not B which is already included in A.
Case 2:
- Same as case 1, but with A being installed.
- To be useful, A must also include all objects from C that is not installed.
- Prog only need to link on A.
> Fix niche cases when linking static libs

- mesonbuild/build.py
We need a union of the compilers used by the target, and by those used by all dependencies, not all the compilers in all projects. We do, however, need to look compilers up from all possible compilers, as a dependency that is a subproject could use a language not present in the current project.
@xclaesse, as pointed out on IRC. I was wrong though, we didn't need an intersection, we needed the target's compilers
> build: use self.compilers instead of all_compilers for stdlib langs

- mesonbuild/backend/backends.py
- test cases/unit/39 external, internal library rpath/built library/meson.build
This reverts commit 904b47085fdd985175b4b2c3224f65b9d33f04d7.
This is not a real bottleneck, and we want to create it thrice -- once before the backend is generated. The final install data needs to be created fresh.
Fixes https://bugs.gentoo.org/910050
> Revert "backends: Cache creation of install data"

- mesonbuild/wrap/wrap.py
When downloading wrap content, we need to know at some point if the server is going to respond with "hello, yes, I'm here and I have data for you". The alternative is to sometimes infinitely hang.
In commit 8f7781f1d6bf36c064b39e7d0794c686f1b78665 we added such a timeout, but using an extremely generously high number -- ten minutes. We don't need to wait this long just to find out if the other end exists, so decrease that time to 30 seconds, whch is still ludicrously generous but not quite as much so.
See https://github.com/bugaevc/wl-clipboard/issues/182#issuecomment-1625346745
> wrap: detect network timeouts 20x faster

- mesonbuild/modules/windows.py
By default, clang-cl based environments use rc.exe as resource compiler. However, when cross compiling with clang-cl, one might want to use llvm-rc instead.
Try to detect llvm-rc based on the output from "$CMD /?".
This requires a very recent llvm-rc; previosly, the output of "/?" with llvm-rc was very generic and didn't explicitly indicate that it actually was llvm-rc. This was changed in
https://github.com/llvm/llvm-project/commit/bab6902eba55026a829d232629f99ac276936ef0 which will be included in the upcoming LLVM 17.0.0 release.
Contrary to the other regexes, don't include the preceding parts of the line in the log printout, as it includes an unhelpful "OVERVIEW:" prefix.
> windows: Fix detection of the llvm-rc resource compiler

- mesonbuild/mtest.py
In commit 628effb3698e85e403351d2705d576cf4ee8c50c we started verifying the build.ninja file was up to date before even `--list`ing tests, because we could end up with incorrect information. This meant that ninja always runs at startup, and typically returns "no work to do", which ended up listed as "one of" the tests.
Instead of unconditionally running ninja attached to the console, first check it in dry-run mode with stdout intercepted, to see if ninja considers itself up to date. If it is, continue. Only if an actual refresh is needed, do we run it while attached to the console.
In the garden path, this avoids useless information. In cases where we'd already print a full meson reconfigure log, we continue to do so.
/cc @anarazel
> mtest: try a bit harder to avoid weird non-parseable output at startup

- docs/markdown/Fs-module.md
Adds clear instructions on how to import filesystem module.
Should make it less likely that one has to try
```
fs = import('FS')
```
or
```
fs = import('filesystem')
```
first.
> Add import instructions for filesystem module

- mesonbuild/mtest.py
- test cases/unit/110 replace unencodable xml chars/meson.build
- test cases/unit/110 replace unencodable xml chars/script.py
- unittests/allplatformstests.py
Replace unencodable XML chars with their printable representation, so that, xmllint can parse test outputs without error.
Closes #9894
Closes #10680
> mtest: fix unencodable XML chars

- mesonbuild/utils/universal.py
- unittests/darwintests.py
Some macos libraries use arm64e instead of arm64 as architecture. Due to the string replace approach taken so far, we'd end up with aarch64e as architecture, which the rest of meson doesn't know.
Move architecture mapping to map whole architecture names and add arm64e -> aarch64 mapping.
This change doesn't touch the case for armv7[s], where we add arm, rather than replace armv7[s], but it's certainly not in line with the other mappings.
Fixes: #9493
Closes: #10718
> macos: map arm64e to aarch64, map "whole" architecture strings

- mesonbuild/modules/cmake.py
- test cases/cmake/26 cmake package prefix dir/cmakePackagePrefixDirConfig.cmake.in
- test cases/cmake/26 cmake package prefix dir/meson.build
- test cases/cmake/26 cmake package prefix dir/test.json
On windows, meson would mix posix and windows dir separators in the computed PACKAGE_RELATIVE_PATH.
Here we force posix directory separator even on Windows. This matches the CMake behavior and fixes interpretation of the resulting path.
Fixes #6955
Fixes #9702
> cmake: fix directory separators in generated packageConfig.cmake files

- mesonbuild/interpreter/compiler.py
- test cases/common/28 try compile/meson.build
In order to pass a File object down into the compiler impl and compile it, we cannot pass a string with the filename, and we cannot either pass the File object as-is, since it relies on being given Environment attributes to calculate the relative location. So we build a fresh File object as an absolute path.
But the code to do this was totally broken. Instead of using the File method to get an absolute path, we used one that expected to create builddir-relative paths... and then gave it the absolute source dir as the "relative path portion" prefix. This worked by accident as long as it wasn't a built File, but if it was a built file then we intentionally didn't include that prefix -- which was wrong anyway, since we need the build directory!
Use the correct method to get an absolute path …
> compiler.compiles: fix silent failure when compiling a built File object

- mesonbuild/compilers/rust.py
- test cases/rust/5 polyglot static/clib.c
- test cases/rust/5 polyglot static/meson.build
- test cases/rust/5 polyglot static/overflow_size_checks.py
- test cases/rust/5 polyglot static/stuff.rs
These result in very large binaries when linked, and are not generally useful. A user can turn them back on by passing `-C overflow-checks=yes` manually via `-Drust_args` or the `RUSTFLAGS` environment variable
fixes: #11785
> rust: disable overflow-checks by default

- test cases/d/13 declare dep/meson.build
- test cases/d/9 features/meson.build
Do not run tests that use integers in versions with compiler that do not support them.
Old versions of GDC supported plain integers in version and debug strings but they are deprecated and GDC 13 hard errors on them.
> Fix build using GDC 13

- mesonbuild/cmake/tracetargets.py
This removes the "if Windows" restriction.  I'm not sure why there was one.
The [CMake doc](https://cmake.org/cmake/help/latest/command/target_link_libraries.html) mention this as a possible input:
> - **A plain library name**: The generated link line will ask the linker to search for the library (e.g. foo becomes -lfoo or foo.lib).
> The library name/flag is treated as a command-line string fragment and will be used with no extra quoting or escaping.
I'm pretty sure this is (was?) also the typical way to link with glibc libs like `m`, `dl` etc.
I encountered this when depending on openssl from vcpkg, meson was not finding (nor linking) `dl`.
> cmake: find dependencies with bare library names on all platforms

- mesonbuild/cmake/generator.py
The [manual](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:BOOL) says:
> Converts string to 0 or 1. Evaluates to 0 if any of the following is true:
> - string is empty,
> - string is a case-insensitive equal of 0, FALSE, OFF, N, NO, IGNORE, or NOTFOUND, or
> - string ends in the suffix -NOTFOUND (case-sensitive).
>
> Otherwise evaluates to 1.
This pull request fix the behavior for the first case ("string is empty"), which currently evaluates to true.
I needed this to properly parse CMake config of [yhirose/cpp-httplib](https://github.com/yhirose/cpp-httplib).
> cmake: fix empty BOOL generator expression evaluating to true

- docs/markdown/snippets/deprecate_build_target_jar.md
- docs/yaml/functions/build_target.yaml
- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/type_checking.py
I'd like to start landing the build_targets typed_kwargs work. This is an attempt to build a first, bitsize chunk that (hopefully) has nothing contentious in it. As a high level overview this adds:
- the stubs in the kwargs module for annotating the functions
- structured stubs in the type_checking module to make sharing arguments between the various functions easier (and uses them in the interpreter)
- adds the exclusive Jar arguments as an example of how this sharing works
- add typing checking for build_target(target_type)
- deprecates the jar value for build_target(target_type), which as has been discussed before was, in retrospect, a design mistake. This requires the jar arguments to `KwargInfo`'d so that we can properly deprecate them in `build_target`
> bytesize start on using typed_kwargs for build_targets

- mesonbuild/backend/ninjabackend.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/mlog.py
- mesonbuild/msetup.py
When running setup with `--profile-self` option,
there are currently no logs after "Found ninja...". However, there are
still some lengthy processes for generating targets and ninja.build.
This add more log entries, when profiling, only for the purpose of
displaying the timestamps of the different steps in ninja generation.
Also fix timestamps displayed twice in summary sections.
> Display more timestamps when profiling ninja

- mesonbuild/backend/xcodebackend.py
```
File "/opt/homebrew/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 194, in run
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/mesonbuild/msetup.py", line 358, in run
app.generate()
File "/opt/homebrew/lib/python3.11/site-packages/mesonbuild/msetup.py", line 183, in generate
return self._generate(env, capture, vslite_ctx)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/mesonbuild/msetup.py", line 253, in _generate
captured_compile_args = intr.backend.generate(capture, vslite_ctx)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/mesonbuild/backend/xcodebackend.py", line 276, in generate …
```
> backend: fix checking dep instance for xcode

- mesonbuild/dependencies/hdf5.py
- test cases/frameworks/25 hdf5/main.cpp
Fix wrong env vars and remove redundant C subdependency.
This patch fixes two problems with the HDF5 module. First one is env vars for the HDF5 compile tool. The custom linker is expected to be in `HDF5_CLINKER` var in case of C (see https://github.com/HDFGroup/hdf5/blob/develop/bin/h5cc.in#L97) and in `HDF5_FLINKER` in case of fortran (see https://github.com/HDFGroup/hdf5/blob/develop/fortran/src/h5fc.in#L93).
The second problem is C subdependency for C++ and fortran. The original code for this behaviour was written by @scivision 4 years ago. Unfortunately, he left no contact information, so I wasn't able to ask him why it was implemented the way it was. All my attempts to contact him failed. @scivision if you are reading this, please comment. The way subdependency is implemented now - …
> Update HDF5 module

- mesonbuild/build.py
- mesonbuild/interpreter/interpreter.py
BuildTarget.need_install is basically just an alias of Target.install,  so let's just fix that to be correct. There's also a `dict.get` call that does nothing, so we can get rid of that too.
> Small cleanups for build

- mesonbuild/modules/pkgconfig.py
- test cases/unit/90 devenv/meson.build
When the pkgconfig module is imported, but not used, it will insert None on the end of the devenv list. This list is not expected to contain None, and causes Meson to crash. This can happen in complex build setups (reported from mesa), where pkgconfig is only used in some configurations
Fixes: #12032
> modules/pkgconfig: Don't insert None into devenv list

- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/build.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/mixins/gnu.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/linkers/linkers.py
This moves the handling of gui_app and win_subsystem to typed_kwargs. This obvious is an improvment in itself, but it also makes `gui_app` a purely interpreter level concept. The interpreter will simply populate the win_subsystem value based on the value of gui_app, and from the build and backend layers it doesn't exist. This makes for less code overall, and less duplication of codepaths.
> use typed_kargs for Executable gui_app and win_subsystem

- packaging/hook-mesonbuild.py
mesonbuild.dependencies.* is now lazy-imported and not automatically detected. Add them as hidden imports.
Fixes #12036
> packaging: fix regression that prevented pyinstaller from getting custom deps

- mesonbuild/modules/python.py
- mesonbuild/modules/python3.py
The python and python3 modules have methods that are thin wrappers around creating a shared module. There is some validation of these due to going through the public API. This has drawbacks of not checking the types before the wrappers poke at the arguments; that the error messages will be wrong (they'll say `shared_module` instead of `python.extension_module`; and that we have an extra function call we don't need.
This way will allow us to transparently get updates to the python modules as we add new checking to shared_module too.
> use build target kwargs in modules

- unittests/windowstests.py
For some (atm unknown) reason mingw Python fails to load some modules when MSYS2 is removed from PATH, like in this test.
Skip for now to make the test suite pass again. Once https://github.com/msys2-contrib/cpython-mingw/issues/141 is fixed this can be reverted.
> tests: skip a test that fails with new Python 3.11 from MSYS2

- .github/workflows/msys2.yml
This reverts commit e945f35cd72402d0d204ff10870e2a95c59b6192.
With MSYS2 udpating to Python 3.11, this should no longer be needed. See https://github.com/msys2/MINGW-packages/issues/17415#issuecomment-1606085553
> Revert "CI: add potential workaround for python crashes in MSYS2"

- mesonbuild/compilers/cpp.py
- unittests/linuxliketests.py
Clang compilers do not support c++23 standard.  Add it and add support for c++26 to both Clang and GCC.
Closes #9053
> add support for newer C++ -std= flags on Clang/GCC

- mesonbuild/build.py
- mesonbuild/coredata.py
- mesonbuild/interpreterbase/baseobjects.py
We allow custom_target() but check for it based on hasattr, ever since the initial implementation way back in the day, in commit 66a6ea984bc43d9ac144e22cf411c16e9f911bb3. This is a bit broken because various objects might support that but still aren't supposed to work. We can actually just use isintance checks like we do immediately above, which are more accurate and avoid crashes on things that aren't even targets at all, like run_target(). Although custom_target indexes are actually targets those didn't work either.
Fixes #9648
> do better sanity check for vs_module_defs input

- docs/markdown/Cross-compilation.md
This changeset fixes a typo, changing "As an example if you cross file has this:" to "As an example if your cross file has this:"
> Fix typo in Cross-compilation.md

- docs/markdown/snippets/find_program_default_options.md
- docs/yaml/functions/find_program.yaml
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
- test cases/common/265 default_options in find_program/meson.build
- test cases/common/265 default_options in find_program/subprojects/dummy.wrap
- test cases/common/265 default_options in find_program/subprojects/dummy/dummy.c
- test cases/common/265 default_options in find_program/subprojects/dummy/meson.build
- test cases/common/265 default_options in find_program/subprojects/dummy/meson_options.txt
This PR adds a `default_options` argument to `find_program()`. It allows users to pass options to the subproject in case of a fallback , in a similar fashion as the argument of the same name in `dependency()`. If this feature is acceptable, I will proceed to write a test for it.
> Add default_options argument to find_program()

- docs/markdown/snippets/required_keyword_for_has_functions.md
- docs/yaml/objects/compiler.yaml
- mesonbuild/interpreter/compiler.py
- test cases/common/262 required keyword in has functions/meson.build
- test cases/common/262 required keyword in has functions/meson_options.txt
add `required` keyword as in [compiler.check_header](https://mesonbuild.com/Reference-manual_returned_compiler.html#compilercheck_header)
so instead of
```meson
some_dep = dependency('some_name')
assert(cc.has_function('some_function', dependencies: [some_dep]))
```
i can write
```meson
some_dep = dependency('some_name')
cc.has_function('some_function', dependencies: [some_dep], required: true)
```
... etc
fix #7541
todo
> add required keyword to "has" functions: has_function has_type has_member has_members

- mesonbuild/environment.py
- unittests/internaltests.py
* tests: Pass a mock C compiler to detect_cpu(), detect_cpu_family()
In some cases the desired result can be different if there are no
compilers at all. The expectations here are based on there being at
least one compiler, so reflect that by providing one; a later test
enhancement can cover the case where there are no compilers provided.
As a result of the mock any_compiler_has_define(), all that matters
will be the distinction between an empty or non-empty dict: the compiler
object itself is unused.
* environment: Assume that mips64 can run 32-bit mips binaries
The relationship between mips64 and mips is similar to the relationship
between x86_64 and x86. Representing it here is necessary so that we
will not require an exe_wrapper when cross-compiling for 32-bit mips on
mips64, or when a …
> Fix mips64 regression in 1.2.0

- mesonbuild/build.py
Improve the error message when a build target is assigned as dependency of another build target, which allows to better pinpoint where the issue lies on.
In the example that follow, modules/meson.build:294 is in a for loop creating library targets from an array of dictionary, and doesn't point to the location where interop_sw_plugin is assigned with vlc_opengl:
Before:
modules/meson.build:294:17: ERROR: Tried to use a build target as a dependency.
You probably should put it in link_with instead.
After:
modules/meson.build:294:17: ERROR: Tried to use a build target vlc_opengl as a dependency of target interop_sw_plugin.
You probably should put it in link_with instead.
It would probably be best to directly pinpoint where the assignment was made but it's probably harder so start simple by …
> build.py: improve BuildTarget error message

- docs/yaml/builtins/meson.yaml
Add a missing full stop in the description of the `meson.global_source_root` function.
> docs: add missing punctuation

- mesonbuild/build.py
- test cases/rust/5 polyglot static/meson.build
- test cases/unit/113 complex link cases/meson.build
- unittests/linuxliketests.py
When an installed static library A links to an internal static library B
built using a custom_target(), raise an error instead of a warning. This
is because to be usable, A needs to contain B which would require to
extract the archive to get its objects files.
This used to work, but was printing a warning and was installing broken
static library, because we used to overlink in many cases, and that got
fixed in Meson 1.2.0. It now fails at link time with symbols from the
custom target not being defined. It's better to turn the warning into an
hard error at configure time.
While at it, noticed this situation can happen for any internal custom
or rust target we link to, recursively.
get_internal_static_libraries_recurse() could be called on CustomTarget
objects which does not implement it, …
> Error when an installed static library links to internal custom target

- mesonbuild/dependencies/ui.py
Fixes #12072 
Attempts to detect the Vulkan version first by using `compiler.run()` then from `VULKAN_SDK` environment variable using heuristics, as discussed with @tristan957 and @eli-schwartz.
I currently only check for `run.compiled == false or run.returncode != 0` is there any other way how `run()` could fail?
> Detect version for Vulkan system dependency

- mesonbuild/dependencies/base.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/kwargs.py
I realized after I reviewed the previous PR that it didn't have type annotations. Surprise, surprise, mypy found some issues, both with internal annotations, ~and some actual bugs~, nope just annotation issues.
> add type annotations to `declare_dependency`

- mesonbuild/utils/vsenv.py
- test cases/python/4 custom target depends extmodule/blaster.py
- test cases/python3/4 custom target depends extmodule/blaster.py
This fixes "test_vsenv_option" with Python 3.11+ and both "4 custom target depends extmodule" on Windows with Python 3.8+. See the commits for details.
(This is required to keep MSYS2 CI green after the next Python update there)
> tests: some Windows fixes with newer Python

- mesonbuild/compilers/mixins/clang.py
Clang supports the same arguments as GCC [since version 3.3.0](https://github.com/llvm/llvm-project/commit/7e2da79efaf866cd6a0142d154aea371714f3fea) from 10 years ago.
It's not properly documented, like quite a few other options... but it works well!  It's also the only way to explicitly pass "auto" as you can see [here](https://github.com/llvm/llvm-project/blob/729b55ef5e7aff33fb1d191c5ef576bbda03b801/clang/lib/Frontend/CompilerInvocation.cpp#L2162).  Currently meson treats "auto" as the same thing as "always" with clang.
If someone was explicitly asking meson for "auto" (the default is "always") and then using ninja (which pipes the output), they will lose the colors after this patch.  But I think this is an acceptable breakage, and we should implement the correct behavior for everyone …
> clang: use gcc syntax to enable diagnostics color

- mesonbuild/utils/universal.py
Popen can raise OSError when program is not found, or PermissionError if not executable, etc.
> Popen_safe_logged: Also log exceptions

- mesonbuild/build.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/type_checking.py
A set of nice, simple cleanups to use typed_kwargs for shared_library exclusive keyword arguments.
> use typed_kwargs for exclusive SharedLibrary keyword arguments

- data/test.schema.json
- docs/markdown/Builtin-options.md
- docs/markdown/Python-module.md
- docs/markdown/snippets/python_extension_module_limited_api.md
- mesonbuild/coredata.py
- mesonbuild/dependencies/python.py
- mesonbuild/modules/python.py
- mesonbuild/scripts/python_info.py
- run_project_tests.py
- test cases/python/10 extmodule limited api disabled/meson.build
- test cases/python/10 extmodule limited api disabled/module.c
- test cases/python/9 extmodule limited api/limited.c
- test cases/python/9 extmodule limited api/meson.build
- test cases/python/9 extmodule limited api/not_limited.c
- test cases/python/9 extmodule limited api/test.json
This PR adds the ability for a user to target the [Python Limited API] directly in the build system by supplying a new, optional keyword argument to the `extension_module` function on the `python_installation` object. For example:
```meson
pymod = import('python')
pyinst = pymod.find_installation()
ext_mod = pyinst.extension_module('my_module',
'my_module_source.c',
limited_api: '3.6',
)
```
Under the hood, Meson takes the `'3.6'` argument and converts it to a hex value corresponding to the equivalent `PY_VERSION_HEX`. It then sets the value of the `Py_LIMITED_API` preprocessor directive to this value.
There is an extra complexity on Windows: when targeting Python's limited API on Windows one must link to `python3.dll` and not `python3.X.dll`. In order to allow enable this, the …
> Allow users to target Py_LIMITED_API via python's extension_module

- README.md
This documents useful to target Meson versions for projects that want to support older Python versions.
> README: Document python requirement history

- docs/markdown/Tutorial.md
Before you would get a deprecation warning on compile:
```
warning: ‘G_APPLICATION_FLAGS_NONE’ is deprecated: Use 'G_APPLICATION_DEFAULT_FLAGS' instead [-Wdeprecated-declarations]
```
And now it's fixed!
Would you by any chance be interested in me updating `Tutorial.md` to GTK4?
> Replace deprecated GTK flag

- docs/markdown/Fs-module.md
- docs/markdown/snippets/fs_relative_to.md
- mesonbuild/modules/fs.py
- test cases/common/220 fs module/meson.build
- test cases/common/220 fs module/subdir/btgt.c
- test cases/common/220 fs module/subdir/meson.build
Returns a relative path from arg 2 to arg 1 similar to os.path.relpath().
Closes: https://github.com/mesonbuild/meson/pull/7908
> Add fs.relative_to()

- mesonbuild/mtest.py
- test cases/unit/110 replace unencodable xml chars/meson.build
- unittests/allplatformstests.py
This was an unintended consequence of the original patch in #11977.
> Remove XML filter from testlog.{json,txt} and std streams

- run_unittests.py
- setup.cfg
Change [this](https://github.com/mesonbuild/meson/actions/runs/5857616111/job/15879865080?pr=12119#step:6:2698) into [this](https://github.com/benoit-pierre/meson/actions/runs/5858924537/job/15883873847#step:6:2696).
> tests: fix assertion rewriting when pytest is used

- mesonbuild/coredata.py
Every time I update meson, I spend about 20 minutes on frustrated googling to figure out how to update my build directory to work with the new version. I'm forgetful, okay? Ease this pain point by suggesting a potential fix in the error message.
> Suggest fix in MesonVersionMismatchException

- mesonbuild/backend/ninjabackend.py
The most notable problem this causes is that when running `meson setup --reconfigure` the build.ninja file is erroneously seen as out of date, so ninja immediately tries to regenerate it again as it didn't see the file get updated.
There are two problems.
The first problem is that we looked for the wrong file. Ninja creates a few internal files, and one of them is the one we care about: `.ninja_log`, which contains stat'ed timestamps for build outputs to aid in checking when things are out of date. But the thing we actually checked for is `.ninja_deps`, a file that contains a compressed database of depfile outputs. If the latter exists, then the former surely exists too.
Checking for the wrong file meant that we would restat outputs, but only when some build edges were previously built …
> ninja backend: fix the automatic restat of outputs when reconfiguring

- mesonbuild/compilers/mixins/clike.py
- test cases/common/262 internal dependency includes in checks/include/test_262_header.h
- test cases/common/262 internal dependency includes in checks/meson.build
The include directories were not passed to the compiler.
> compilers: fix checks handling of internal dependencies

- mesonbuild/dependencies/cuda.py
* Without this, using nvcc as the sole driver vs dependency('cuda') and host compiler driver yields differently linked binaries.
> Use `cudart_static` by default in dependency('cuda')

- mesonbuild/minstall.py
Previously the log had no indication of which file failed to install, merely a list of files already installed. Printing the actually failing file allows a user to narrow down which part of the install fails.
---
One of the projects I worked on installed to the system udev dir (regardless of prefix) but narrowing that down was frustrating. There's no indication what failed, so it's hard to guess which option didn't take the custom prefix I used. And while it asked for pkexec there too was no indication *why* it needed the privileges.
This patch fixes it, at least this way we can narrow down which file/group of files is affected.
> minstall: print the filename in case of PermissionError

- docs/markdown/Commands.md
- docs/markdown/snippets/msetup.md
- mesonbuild/mconf.py
- mesonbuild/msetup.py
- unittests/baseplatformtests.py
- unittests/platformagnostictests.py
`meson setup -Dfoo=bar builddir` command returns success but does not
update options.
This now also update options. It is useful because it means
`meson setup -Dfoo=bar builddir && ninja -C builddir` works regardless
whether builddir already exists or not, and when done in a script,
changing options in the script will automatically trigger a reconfigure
if needed. This was already possible by always passing --reconfigure
argument, but that triggers a reconfigure even when options did not
change.
> msetup: Update options when builddir is already configured

- docs/markdown/FAQ.md
Prior to Windows 10, libfoo.a were usually not usable with MSVC. This is not true any more since Autotools projects built with UCRT produce libfoo.a that are compatible with MSVC.
This is another reason for using that naming convention in Meson.
> FAQ: MinGW UCRT are compatible with MSVC and also use libfoo.a

- mesonbuild/build.py
- mesonbuild/interpreter/compiler.py
- mesonbuild/mintro.py
- test cases/common/28 try compile/meson.build
Compiler checks were not adding build dir side, which prevents using headers generated with configure_file().
> include_directories: Always add both source and build dirs

- mesonbuild/modules/__init__.py
- mesonbuild/modules/gnome.py
- test cases/frameworks/36 gtkdoc cpp/foo-docs.xml
- test cases/frameworks/36 gtkdoc cpp/foo.cpp
- test cases/frameworks/36 gtkdoc cpp/foo.h
- test cases/frameworks/36 gtkdoc cpp/meson.build
- test cases/frameworks/36 gtkdoc cpp/test.json
- test cases/frameworks/37 gir cpp/foo.cpp
- test cases/frameworks/37 gir cpp/foo.h
- test cases/frameworks/37 gir cpp/meson.build
- test cases/frameworks/37 gir cpp/test.json
gtkdoc() and generate_gir() methods assumes there is a C compiler, but pure C++ projects might not add it explicitly.
Fixes: #12162
> gnome: Fix crash in gtkdoc and generate_gir in C++ projects

- docs/markdown/Builtin-options.md
- docs/markdown/snippets/cstd.md
- mesonbuild/compilers/c.py
- mesonbuild/compilers/compilers.py
- mesonbuild/compilers/cpp.py
- mesonbuild/coredata.py
- mesonbuild/mcompile.py
- mesonbuild/optinterpreter.py
- test cases/unit/114 c cpp stds/meson.build
- unittests/allplatformstests.py
- unittests/baseplatformtests.py
Projects that prefer GNU C but can fallback to ISO C can now set for
example `default_options: 'c_std=gnu11,c11'` and it will use gnu11 when
available, fallback to c11 otherwise. It is an error only if none of the
values are supported by the current compiler.
This allows to deprecate gnuXX values from MSVC compiler, that means
that `default_options: 'c_std=gnu11'` will now print warning with MSVC
but still fallback to 'c11' value. No warning is printed if at least one
of the values is valid, i.e. `default_options: 'c_std=gnu11,c11'`.
In the future that deprecation warning will become an hard error because
`c_std=gnu11` should mean GNU is required, for projects that cannot be
built with MSVC for example.
> c_std, cpp_std: Change to a list of desired versions in preference order

- test cases/linuxlike/13 cmake dependency/meson.build
If we want to make the CI green waiting for the cmake update on cygwin...
> Disable failing cmake test on cygwin

- test cases/linuxlike/11 runpath rpath ldlibrarypath/main.c
- test cases/linuxlike/11 runpath rpath ldlibrarypath/meson.build
The bug it was blocked on was fixed in
a0514a7c4183a9e42d436865087d2f887d658d54.
> Re-enable "11 runpath rpath ldlibrarypath"

- docs/yaml/functions/add_languages.yaml
It was listed as `bool`, but it can be a `feature` too.
> Doc: fix type signature for add_languages.required

- mesonbuild/compilers/detect.py
Currently on main with `CC=/usr/lib/ccache/bin/cc`:
```
$ ./run_project_tests.py
Meson build system 1.2.99 Project Tests
Using python 3.11.5 (main, Aug 28 2023, 20:02:58) [GCC 13.2.1 20230801] ('/usr/bin/python3')
host machine compilers
c      : [gcc]      /usr/lib/ccache/bin/cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230801")
cpp    : [gcc]      /usr/lib/ccache/bin/c++ (gcc 13.2.1 "c++ (GCC) 13.2.1 20230801")
cs     : [mono]     mcs (mono 6.12.0.0)
cuda   : [not found]
cython : [cython]   cython (cython 3.0.2)
d      : [llvm]     ldc2 (llvm 1.33.0 "LDC - the LLVM D compiler (1.33.0):")
fortran: [gcc]      gfortran (gcc 13.2.1 "GNU Fortran (GCC) 13.2.1 20230801")
java   : [unknown]  javac (unknown 1.8.0)
masm   : [not found]
nasm   : [not found]
objc   : [gcc]      sccache cc (gcc 13.2.1)
objcpp : …
```
> compilers: fix compiler detection when the "ccache" string is in the path

- run_project_tests.py
> CI: improve project tests logging

- docs/markdown/IDE-integration.md
Adding a rewritten version of Meson-UI into the  IDE-integration.md page.
> Adding Meson-UI back on IDE-integration.md [SKIP_CI]

- mesonbuild/backend/ninjabackend.py
- mesonbuild/linkers/linkers.py
- test cases/osx/9 global variable ar/libfile.c
- test cases/osx/9 global variable ar/libfile2.c
- test cases/osx/9 global variable ar/meson.build
- test cases/osx/9 global variable ar/nativefile.ini
- test cases/osx/9 global variable ar/prog.c
This is a regression test for:
https://github.com/mesonbuild/meson/issues/11165.
The test was initially merged as part of:
https://github.com/mesonbuild/meson/pull/10628, but had to be reverted.
A second attempt at fixing the root cause also had to be reverted: https://github.com/mesonbuild/meson/pull/10699.
A 3rd attempt got merged but missed this unit test: https://github.com/mesonbuild/meson/pull/11742.
> tests: Test extern'd globals on MacOS with the Apple Archiver

- data/shell-completions/bash/meson
The bash completion code seems to be missing some love! Here's some improvements, if such a thing is possible with any bash completion code. Shudder.
`meson test<tab>`
```
meson testTraceback (most recent call last):
File "<string>", line 2, in <module>
File "/usr/lib64/python3.11/json/__init__.py", line 293, in load
return loads(fp.read(),
^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None …
```
> Bash completion additions and fixes (fixes #9077)

- docs/markdown/snippets/compiler_has_define.md
- docs/yaml/objects/compiler.yaml
- mesonbuild/compilers/mixins/clike.py
- mesonbuild/interpreter/compiler.py
- test cases/common/132 get define/meson.build
Adds a new method to the compiler object, has_define. This makes it possible to check if a preprocessor macro/define is set or not.
This is especially helpful if the define in question is empty, for example:
#define MESON_EMPTY_DEFINE
This would yield the same results as a missing define with the existing get_define method, as it would return an empty string for both cases. Therefore this additional method is needed.
> Add compiler.has_define

- mesonbuild/build.py
- mesonbuild/compilers/cuda.py
- mesonbuild/coredata.py
- mesonbuild/interpreter/compiler.py
- mesonbuild/utils/universal.py
- test cases/common/223 persubproject options/subprojects/sub2/meson.build
> Compiler checks must use per-subproject options

- data/test.schema.json
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- run_project_tests.py
- test cases/vala/7 shared library/lib/meson.build
- test cases/vala/7 shared library/test.json
Installing python sources causes the python module to call create_install_data() before Ninja backends adds extra outputs to Vala targets.
Target objects are supposed to be immutable, adding outputs that late is totally wrong. Add extra vala outputs immediately, but be careful because the main output is only added later from post_init(). Luckily the base class already puts a placeholder item in self.outputs for the main filename so we can just replace self.outputs[0] instead of replacing the whole list which would contain vala outputs at that stage. This is surprisingly what SharedLibrary was already doing.
> Fix crash when installing a vala library and python sources

- mesonbuild/interpreter/interpreter.py
- run_project_tests.py
- test cases/common/18 includedir/meson.build
- test cases/common/18 includedirxyz/do_not_delete
Fixes #12217.
- On Windows, it was not detected if include directory was an absolute path to source directory, because of the mis of path separators.
- In the edgecase the include directory begins with the exact same string as the source directory, but is a different directory, it was falsely reported as an error.
> Fix include_directories test for relative path

- mesonbuild/dependencies/qt.py
You cannot listdir() a directory that doesn't exist. This header directory may not exist if suitable devel packages in distros with split devel packages, aren't installed.
In theory we could raise a suitable error here. But it would be inconsistent -- we don't otherwise validate that the Qt include directories exist, usually just assuming they do because the dependency was found. And this is niche code inside a non-default special kwarg. At least for pkg-config, it's probably a bug in the distro if pkg-config files exist but the headers don't. The qmake status is less clear.
Avoiding a crash means that at the very least, if those headers are in fact directly used by the project, an obvious compiler error occurs instead of a noisy meson traceback.
Fixes #12214
> dependencies: fix crash in Qt if private_headers dir not found

- docs/markdown/snippets/clike_compilers_implicit_includes.md
- docs/yaml/objects/compiler.yaml
- mesonbuild/compilers/mixins/clike.py
A standard C library may not exist for cross-compile environments, thus the existence of <stdio.h> cannot be guaranteed. Use <stddef.h>, which comes directly from the compiler, instead.
> clike compilers: fix cross_* functions' include

- docs/markdown/snippets/int_to_string_fill.md
- docs/yaml/elementary/int.yml
- mesonbuild/interpreter/primitives/integer.py
- test cases/common/270 int_to_str_fill/meson.build
As per title, this PR implements being able to convert an int to a string padded with leading zeroes. Very simple functionality, just a kwarg for int.to_string(). If you are on board with it, I'll proceed with editing the docs.
> Add support for padding zeroes in int.to_string() method

- docs/markdown/Gnome-module.md
- mesonbuild/modules/gnome.py
- test cases/frameworks/7 gnome/mkenums/meson.build
- test cases/frameworks/7 gnome/mkenums/subdir/h2.h.in
- test cases/frameworks/7 gnome/mkenums/subdir/h3.h
- test cases/frameworks/7 gnome/mkenums/subdir/meson.build
It was generating #include with the basename of every header file. That assumes that every directory where there are headers are also included into search path when compiling the .c file.
Change to use path relative to current subdir, which can be both in build or source directory. That means that we assume that when the .c file is compiled, the target has a include_directories pointing to the directory where gnome.mkenum_simple() has been called, which is generally '.' and added automatically.
Also fix type annotation to only allow str and File sources, other types have never been working, it would require to iterate over custom target outputs, etc.
> gnome.mkenum_simple(): Fix include path when header is in subdir

- mesonbuild/dependencies/cmake.py
- mesonbuild/dependencies/misc.py
- test cases/unit/117 openssl cmake bug/meson.build
- test cases/unit/117 openssl cmake bug/nativefile.ini
- unittests/platformagnostictests.py
Fixes #12098
Fixes #11145
DependencyFactory was returning a lambda, but it has no log_tried() function.
> fix bug with openssl when cmake is missing

- mesonbuild/ast/interpreter.py
- mesonbuild/interpreter/interpreter.py
- test cases/common/40 options/meson.build
When option name contains more that one dot, it should be detected earlier to prevent an assert to be raised.
Fixes #11904.
> Fix assertion raised with invalid option name

- unittests/windowstests.py
This reverts commit 68dce66bf9a2bcb3d23c291beb2354225a74b954.
The upstream issues https://github.com/msys2-contrib/cpython-mingw/issues/141 has been fixed now.
> Revert "tests: skip a test that fails with new Python 3.11 from MSYS2"

- docs/markdown/Unit-tests.md
`lcov` moved from sourceforge to github, so this change updates the link.
> Update link to lcov

- docs/markdown/Users.md
Wayland, Weston, wlroots migrated to gitlab.freedesktop.org
> Changed outdated links to wayland, weston and wlroots

- mesonbuild/backend/backends.py
- mesonbuild/dependencies/base.py
- mesonbuild/dependencies/boost.py
- mesonbuild/dependencies/cmake.py
- mesonbuild/dependencies/configtool.py
- mesonbuild/dependencies/pkgconfig.py
- mesonbuild/dependencies/qt.py
- mesonbuild/dependencies/scalapack.py
- mesonbuild/envconfig.py
- mesonbuild/interpreter/interpreterobjects.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/mdevenv.py
- mesonbuild/modules/external_project.py
- mesonbuild/modules/gnome.py
- mesonbuild/modules/pkgconfig.py
- mesonbuild/utils/universal.py
- run_tests.py
- test cases/unit/114 empty project/expected_mods.json
- unittests/failuretests.py
- unittests/linuxliketests.py
-    pkgconfig: Set PKG_CONFIG in env for devenv and g-ir-scanner
-    pkgconfig: Deprecate "pkgconfig" in favor of "pkg-config" in [binaries]
-    pkgconfig: Restore logging of pkg-config version
While at it, make more methods private by storing the version found on
the instance. That avoids having to call check_pkgconfig() as static
method from unittests.
-    pkgconfig: Use lru_cache instead of caching command lines
-    pkgconfig: Cache the implementation instance
-    Remove get_configtool_variable()
This also makes it more consistent with get_pkgconfig_variable() which
always return empty value instead of failing when the variable does not
exist. Linking that to self.required makes no sense and was never
documented any way.
-    Remove get_pkgconfig_variable()
Make sure that …
> pkgconfig: cleanups and fix define_variable type

- docs/markdown/Rust-module.md
- docs/markdown/snippets/rust_crate_type.md
- docs/yaml/functions/_build_target_base.yaml
- docs/yaml/functions/library.yaml
- docs/yaml/functions/shared_library.yaml
- docs/yaml/functions/shared_module.yaml
- docs/yaml/functions/static_library.yaml
- mesonbuild/backend/ninjabackend.py
- mesonbuild/build.py
- mesonbuild/compilers/rust.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/interpreter/type_checking.py
- mesonbuild/modules/rust.py
- test cases/failing/53 wrong shared crate type/meson.build
- test cases/failing/53 wrong shared crate type/test.json
- test cases/failing/54 wrong static crate type/meson.build
- test cases/failing/54 wrong static crate type/test.json
- test cases/rust/18 proc-macro/meson.build
- test cases/rust/4 polyglot/meson.build
- test cases/rust/4 polyglot/proc.rs
- test cases/rust/4 polyglot/stuff.rs
- test cases/rust/4 polyglot/test.json
-    Rust: Fix both_libraries() case
Rustc does not produce object files we can reuse to build both
libraries. Ideally this should be done with a single target that has
both `--crate-type` arguments instead of having 2 different build rules.
As temporary workaround, build twice and ensure they don't get conflicts
in intermediary files created by rustc by passing target's private
directory as --out-dir.
See https://github.com/rust-lang/rust/issues/111083.
-    Rust: Use Popen_safe_logged in sanity checks
-    Rust: Fix proc-macro usage when cross compiling
Force BUILD machine and allow to link with HOST machine.
-    Rust: Prevent linking Rust ABI with C library/executable
-    Rust: Remove unit test already covered in "rust/4 polyglot"
-    Rust: Replace rust_crate_type with rust_abi …
> Rust: Replace rust_crate_type with rust_abi

- docs/yaml/functions/add_project_link_arguments.yaml
It should refer to `add_project_arguments`, not `add_global_arguments`.
> docs: fix `add_project_link_arguments` documentation

- mesonbuild/compilers/objcpp.py
Separated out from the other pull request, just including the change to fix #11890.
Based on the current list of supported standards from Apple Clang 15 (Xcode 15 beta):
```
$ clang++ -dM -xobjective-c++ -E -std=arglbargle /dev/null -o -
error: invalid value 'arglbargle' in '-std=arglbargle'
note: use 'c++98' or 'c++03' for 'ISO C++ 1998 with amendments' standard
note: use 'gnu++98' or 'gnu++03' for 'ISO C++ 1998 with amendments and GNU extensions' standard
note: use 'c++11' for 'ISO C++ 2011 with amendments' standard
note: use 'gnu++11' for 'ISO C++ 2011 with amendments and GNU extensions' standard
note: use 'c++14' for 'ISO C++ 2014 with amendments' standard
note: use 'gnu++14' for 'ISO C++ 2014 with amendments and GNU extensions' standard
note: use 'c++17' for 'ISO C++ 2017 with …
```
> fix missing C++20 support for Apple Clang with objcpp

- mesonbuild/backend/ninjabackend.py
- mesonbuild/dependencies/dev.py
Makes it stop reporting that it found a static zlib on Solaris which does not ship a static library file for libz, and thus allows "test cases/rust/13 external c dependencies" to pass.
Fixes #10906
On Solaris 11.4.57, this changes the results of that rust test case from:
```
[SUCCESS]   rust: 13 external c dependencies    (static=False method=cmake)
[SUCCESS]   rust: 13 external c dependencies    (static=False method=pkg-config)
[SUCCESS]   rust: 13 external c dependencies    (static=False method=system)
[SUCCESS]   rust: 13 external c dependencies    (static=True method=cmake)
[ERROR]    rust: 13 external c dependencies    (static=True method=system)
During: build
Reason: Compiling source code failed.
```
to
```
[SUCCESS]   rust: 13 external c dependencies    (static=False method=cmake) …
```
> ZlibSystemDependency: pass libtype to clib_compiler.find_library

- docs/markdown/Wrap-dependency-system-manual.md
- docs/markdown/snippets/wrap.md
- mesonbuild/cmake/interpreter.py
- mesonbuild/interpreter/dependencyfallbacks.py
- mesonbuild/interpreter/interpreter.py
- mesonbuild/modules/cmake.py
- mesonbuild/msubprojects.py
- mesonbuild/wrap/wrap.py
- test cases/cmake/26 dependency fallback/main.cpp
- test cases/cmake/26 dependency fallback/meson.build
- test cases/cmake/26 dependency fallback/subprojects/broken_method.wrap
- test cases/cmake/26 dependency fallback/subprojects/cmMod.wrap
- test cases/cmake/26 dependency fallback/subprojects/cmMod/CMakeLists.txt
- test cases/cmake/26 dependency fallback/subprojects/cmMod/cmMod.cpp
- test cases/cmake/26 dependency fallback/subprojects/cmMod/cmMod.hpp
- test cases/cmake/26 dependency fallback/subprojects/cmMod/cpp_pch.hpp
- test cases/cmake/26 dependency fallback/subprojects/cmake_subp/CMakeLists.txt
- test cases/cmake/26 dependency fallback/subprojects/force_cmake.wrap
- test cases/cmake/26 dependency fallback/subprojects/force_cmake/CMakeLists.txt
- test cases/cmake/26 dependency fallback/subprojects/force_cmake/meson.build
- test cases/cmake/26 dependency fallback/subprojects/meson_method.wrap
- test cases/cmake/26 dependency fallback/subprojects/meson_subp/meson.build
The method can be overriden by setting `method` key in the wrap file
and always defaults to 'meson'.  The dependency object can be retrieved
without the need of specific module API thanks to
meson.override_dependency() mechanism. cmake.subproject() is still
needed in case specific cmake options needs to be passed.
This also makes easier to extend to other methods in the future e.g.
cargo.
> Allow to fallback to cmake subproject

- mesonbuild/environment.py
this fixes the "frameworks: 15 llvm" tests with llvm 17
> get_llvm_tool_names: add llvm 17

- mesonbuild/dependencies/misc.py
llvm v17 defaults to 5.1 and without this meson fails to find openmp: 'ERROR: Dependency "openmp" not found, tried system'
Add 5.2 as well while at it.
> openmp: add 5.1/5.2, fixes openmp with llvm v17

- mesonbuild/compilers/cpp.py
c++26 support was added in #11986, but regressed in #10332 because the versions now get checked against the global _ALL_STDS list, and c++26 was missing there.
Fix by adding c++26 to _ALL_STDS
> cpp: restore c++26 support

- docs/markdown/snippets/meson_clang_tidy_fix.md
- mesonbuild/backend/ninjabackend.py
- mesonbuild/scripts/clangtidy.py
- unittests/allplatformstests.py
- unittests/helpers.py
Add the `clang-tidy-fix` target to apply clang-tidy fixes to the source code.
This is done by calling `run-clang-tidy` with `-fix` argument.
> Add clang-tidy-fix target

- mesonbuild/modules/rust.py
- test cases/rust/12 bindgen/meson.build
- test cases/rust/12 bindgen/src/global-project.h
- test cases/rust/12 bindgen/src/global.c
- test cases/rust/12 bindgen/src/global.rs
- test cases/rust/12 bindgen/test.json
This means that any arguments given project wide or globally (such as preprocessor defines) will be set.
Fixes: #12065
> rust: pass global and project C args to clang in bindgen

- test cases/linuxlike/3 linker script/meson.build
This has never, ever, ever worked. You can get away with it a tiny, tiny bit, iff you magically assume several things about both internal implementations, as well as the project source layout and builddir location.
This can be witnessed by the way using files() was mercilessly tortured through joining the undefined stringified format value of the file to the current source dir... because it didn't actually *work*, the stringified value isn't an absolute path or a builddir-relative one, but it works as long as you do it from the root meson.build file.
Furthermore, this triggers a deprecation warning if you do it. And using it for files() is frivolous, the "static map file" case was correct all along.
Fix the configure_file case to demonstrate the same painful hoops we must jump through to …
> tests: fix broken promises with linker scripts

- mesonbuild/backend/vs2010backend.py
Following on from #11362.
Using #11614 on https://github.com/lukester1975/meson-vs-filter results in:
`b_empty_dirs` is defined in `a/b/meson.build`
The path to `b.cpp` is effectively rendered as `a/b/b_empty_dirs/a/b/b.cpp`
and `main.cpp` as `a/b/b_empty_dirs/main.cpp`
... which duplicates the directory structure. IMHO, it would be better to root each project at the location of the `meson.build` defining it, as the ealier PR #11362 did:
The path to `b.cpp` appears as `a/b/b_empty_dirs/b.cpp`
and `main.cpp` as `a/b/b_empty_dirs/../../main.cpp`
Thanks
> vcxproj.filters revisited

- test cases/common/13 pch/meson.build
Xcode always fails here because this makes the PCH not be the first included header, causing Xcode to ignore it completely. There is no way around this.
> tests: Skip "withIncludeFile" for PCH on Xcode backend

- mesonbuild/compilers/mixins/clike.py
- unittests/internaltests.py
It should *be* a version comparison. We are guaranteed to get a two-element version number, which also parses as a float but a float doesn't correctly handle version sorting when the second component differs in number of digits.
The standard way to handle this is by comparing tuples such that each component is an integer. Do so here.
Fixes #12195
Co-authored-by: George Koehler <xkernigh@netscape.net>
(for unittests)
> compilers: use correct version comparison for openbsd libraries

- test cases/unit/68 clang-tidy/cttest_fixed.cpp
- unittests/allplatformstests.py
- unittests/helpers.py
The unittest case for `clang-tidy-fix` checks if the whole project is in git or not, and skips if not.
Fix this by creating a temporary git repo, copy the test files and run the tests, following how `clang-format` does.
It also reverts some help code introduced in the previous test.
Tested: Verify the test case passes.
> unittest: Fix clang-tidy-fix

- docs/markdown/snippets/executable_vs_module_defs.md
- docs/markdown/snippets/vs_module_defs_customtargetindex.md
- docs/yaml/functions/executable.yaml
- docs/yaml/functions/shared_library.yaml
- docs/yaml/functions/shared_module.yaml
- mesonbuild/backend/ninjabackend.py
- mesonbuild/backend/vs2010backend.py
- mesonbuild/build.py
- mesonbuild/interpreter/kwargs.py
- mesonbuild/interpreter/type_checking.py
- test cases/windows/10 vs module defs generated custom target/subdir/meson.build
- test cases/windows/9 vs module defs generated/exe.def
- test cases/windows/9 vs module defs generated/meson.build
- test cases/windows/9 vs module defs generated/prog.c
@tristan957 had mentioned this was needed for Executables as well, but I haven't written a test case or doc changes for that yet.
> use typed_kwargs for vs_module_defs
